### ISSUE TITLE
Mimic gel does not gain taunt if it copies a creature with taunt. Mimic gel also prompts for copy after choosing which flank meaning it also doesn't copy deploy

### ISSUE THREAD

**Issue by DaveCordeiro** [keyteki/keyteki#1000]
![image](https://user-images.githubusercontent.com/57851149/69929303-2491e080-1484-11ea-80ed-5b0cb1d8dd37.png)
https://pastebin.com/RDkb2FkC

**Comment by romanogit** [comment]
Mimic is now working properly with taunt. It should not copy deploy, though, as per it is played as a copy, so it needs to enter play first.
