### ISSUE TITLE
Angwish not working properly

### ISSUE THREAD

**Issue by henuka** [keyteki/keyteki#1001]
Even when damaged enemy made a key with normal cost.

![angwish not working](https://user-images.githubusercontent.com/58422025/69949618-8db43b00-14fa-11ea-8c09-fd0f8972faee.png)

**Comment by romanogit** [comment]
![image](https://user-images.githubusercontent.com/2104075/70233760-f6d7c080-173d-11ea-8465-058cacef1b12.png)

**Comment by romanogit** [comment]
I was not able to reproduce this one. I created a test case in #1017 .

Is it possible that your opponent had played "We Can ALL Win" in his previous turn?

![image](https://user-images.githubusercontent.com/2104075/70240952-f3980100-174c-11ea-9a1d-9d754ddd4f3a.png)

**Comment by romanogit** [comment]
Unable to reproduce and tests were added. If you see the issue again, please, reopen the ticket with more game log information.
