### ISSUE TITLE
Rotgrub with Duskrunner doesn't steal when reaping

### ISSUE THREAD

**Issue by dlocke** [keyteki/keyteki#1004]
I'm sorry I don't have the logs for this, but I played a game recently where I put the Duskrunner upgrade (reap: steal 1A) on a Rotgrub (reap: archive Rotgrub).  When I reaped, I expected the steal effect to fire and then the archive but what actually happened is that the archive happened first and the steal didn't happen.

When a creature has multiple reap effects, would it be possible to choose the order in which they resolve?

**Comment by romanogit** [comment]
This issues is fixed already:

![image](https://user-images.githubusercontent.com/2104075/73566035-9d3ff980-4441-11ea-8d3c-678dfa515d65.png)

![image](https://user-images.githubusercontent.com/2104075/73566046-a4ff9e00-4441-11ea-9cb6-cc45a9eaffc3.png)

![image](https://user-images.githubusercontent.com/2104075/73566065-b47ee700-4441-11ea-8d2c-4399b44e846b.png)

Make sure you have your game options properly set:

![image](https://user-images.githubusercontent.com/2104075/73566091-c791b700-4441-11ea-8312-937993252d09.png)
