### ISSUE TITLE
Gargantodon vs. empty opponent's board

### ISSUE THREAD

**Issue by bensissel** [keyteki/keyteki#1005]
Gargantodon is in play under my control. My opponent has no creatures in play and plays Trust No One for the max 3 value. Per Crucible Cast 14 ruling:
"Gargantodon replaces "Steal Æmber" with "Capture Æmber" therefore, if you have no creatures in play that can capture Æmber, nothing happens because captured Æmber has no place to go."
So no stealing should have occurred.

**Comment by Herzbube76** [comment]
This problem still exists!
