### ISSUE TITLE
Uncharted Lands

### ISSUE THREAD

**Issue by Renin16** [keyteki/keyteki#1009]
"Uncharted Lands": Artifact - Play: Place 6A from the common supply on Uncharted Lands. Each Star Alliance creature gains, “Reap: Move 1A from Uncharted Lands to your pool.” 

The artifact continues to give aember after the aember pool on the card is depleted.

**Comment by romanogit** [comment]
![image](https://user-images.githubusercontent.com/2104075/70233785-035c1900-173e-11ea-96c4-7ee6cc2c5a9f.png)

**Comment by benjamintownsend** [comment]
I too had this problem
