### ISSUE TITLE
Gleeful Mayhem ordering

### ISSUE THREAD

**Issue by Jacksuhn** [keyteki/keyteki#1010]
Gleeful mayhem forces house order. I always have to choose Dis first, when I don't always want to. Sometimes I need to pop a ward before hitting the Harbringer of Doom.
![Screenshot_20191204-033244_Chrome](https://user-images.githubusercontent.com/45366494/70131439-ecd39600-1647-11ea-992d-e0db0c5a9c1c.jpg)

**Comment by romanogit** [comment]
![image](https://user-images.githubusercontent.com/2104075/70139733-e0643300-1671-11ea-9d5c-f6e527819545.png)

**Comment by romanogit** [comment]
@Jacksuhn : I think the order should not matter because the damage must be simultaneous.

You should be able to decide whether you want to remove ward before Harbinger, imho.

**Comment by Jacksuhn** [comment]
It shouldn't matter, but in the past when I used it and selected Harbinger first as I was forced to do, it wiped the board before I couple select the next creature.

**Comment by romanogit** [comment]
Damage is simultaneous and it is working as expected:

![image](https://user-images.githubusercontent.com/2104075/101064197-7dea8f00-3572-11eb-9262-bf814aee5c53.png)
