### ISSUE TITLE
Disruption Field

### ISSUE THREAD

**Issue by Awrukinam** [keyteki/keyteki#1011]
When i play Disruption FIeld on one of my oponents crature first effect should apply to my opponent, because I'm the OWNER of this upgrade, BUT fight/reap affect should stick to creature, sooo... In this situation Disruption field should be a problem for my opponent not for me...

**Comment by Awrukinam** [comment]
Maniu is shuffling their deck
VerifiedSnoopy is shuffling their deck
Maniu is playing as the Archon: Chytry Filip z Pragi
VerifiedSnoopy is playing as the Archon: Marco, Worldly Pub Ripper
 Maniu has connected to the game server
 VerifiedSnoopy has connected to the game server
Maniu draws 6 cards up to their maximum hand size of 6
VerifiedSnoopy draws 6 cards up to their maximum hand size of 6
Maniu is shuffling their deck
Key phase - Maniu
Maniu does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - Maniu
Maniu chooses staralliance as their active house this turn
Main phase - Maniu
Maniu plays Information Officer Gray
Maniu uses Information Officer Gray to reveal Imperial Scutum from their hand, and archive it
Ready phase - Maniu
Maniu readies all of their cards
Draw phase - Maniu
Maniu draws 2 cards up to their maximum hand size of 6
End of turn 1
Maniu: 0 Æmber VerifiedSnoopy: 0 Æmber
Turn 1
Key phase - VerifiedSnoopy
VerifiedSnoopy does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - VerifiedSnoopy
VerifiedSnoopy chooses logos as their active house this turn
Main phase - VerifiedSnoopy
VerifiedSnoopy plays Hapsis
VerifiedSnoopy plays Sanitation Engineer
VerifiedSnoopy plays Babbling Bibliophile
Ready phase - VerifiedSnoopy
VerifiedSnoopy readies all of their cards
Draw phase - VerifiedSnoopy
VerifiedSnoopy draws 3 cards up to their maximum hand size of 6
End of turn 1
Maniu: 0 Æmber VerifiedSnoopy: 0 Æmber
Turn 2
Key phase - Maniu
Maniu does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - Maniu
Maniu chooses shadows as their active house this turn
Main phase - Maniu
Maniu plays Hugger-Mugger
Maniu plays Whisper
Maniu plays Special Delivery, gaining 1 Æmber
Ready phase - Maniu
Maniu readies all of their cards
Draw phase - Maniu
Maniu draws 3 cards up to their maximum hand size of 6
End of turn 2
Maniu: 1 Æmber VerifiedSnoopy: 0 Æmber
Turn 2
Key phase - VerifiedSnoopy
VerifiedSnoopy does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - VerifiedSnoopy
VerifiedSnoopy chooses logos as their active house this turn
Main phase - VerifiedSnoopy
VerifiedSnoopy plays Information Exchange
VerifiedSnoopy uses Information Exchange to steal 1 Æmber from Maniu
VerifiedSnoopy uses Babbling Bibliophile to reap with Babbling Bibliophile
VerifiedSnoopy uses Babbling Bibliophile to draw 2 cards
VerifiedSnoopy uses Hapsis to make Hapsis fight Information Officer Gray
VerifiedSnoopy uses Hapsis to ward Hapsis
VerifiedSnoopy plays Titan Guardian
VerifiedSnoopy uses Sanitation Engineer to reap with Sanitation Engineer
VerifiedSnoopy uses Sanitation Engineer to discard Mogghunter
Ready phase - VerifiedSnoopy
VerifiedSnoopy readies all of their cards
Draw phase - VerifiedSnoopy
End of turn 2
Maniu: 0 Æmber VerifiedSnoopy: 3 Æmber
Turn 3
Key phase - Maniu
Maniu does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - Maniu
Maniu chooses saurian as their active house this turn
Maniu moves all the cards in their archives to their hand
Main phase - Maniu
Maniu plays Odoac the Patrician
Maniu uses Odoac the Patrician to capture 1 Æmber from VerifiedSnoopy, placing it on Odoac the Patrician
Maniu plays Odoac the Patrician
Maniu uses Odoac the Patrician to capture 1 Æmber from VerifiedSnoopy, placing it on Odoac the Patrician
Maniu plays Praefectus Ludo
Maniu plays Praefectus Ludo
Maniu plays Imperial Scutum, gaining 1 Æmber attaching it to Odoac the Patrician
Maniu uses Special Delivery to sacrifice Special Delivery and deal 3 damage to Hapsis
VerifiedSnoopy uses Hapsis to remove its ward token
Ready phase - Maniu
Maniu readies all of their cards
Draw phase - Maniu
Maniu draws 4 cards up to their maximum hand size of 6
End of turn 3
Maniu: 1 Æmber VerifiedSnoopy: 1 Æmber
Turn 3
Key phase - VerifiedSnoopy
VerifiedSnoopy does not forge a key. They have 1 amber. The current cost is 6 Æmber
House phase - VerifiedSnoopy
VerifiedSnoopy chooses shadows as their active house this turn
Main phase - VerifiedSnoopy
VerifiedSnoopy plays Whisper
VerifiedSnoopy plays Pestering Blow, gaining 1 Æmber
VerifiedSnoopy uses Pestering Blow to deal 1 damage and enrage Praefectus Ludo
VerifiedSnoopy plays Hidden Stash, gaining 1 Æmber
VerifiedSnoopy uses Hidden Stash to archive a card
VerifiedSnoopy plays Oubliette
VerifiedSnoopy uses Oubliette to purge Whisper
Ready phase - VerifiedSnoopy
VerifiedSnoopy readies all of their cards
Draw phase - VerifiedSnoopy
VerifiedSnoopy draws 5 cards up to their maximum hand size of 6
End of turn 3
Maniu: 1 Æmber VerifiedSnoopy: 3 Æmber
Turn 4
Key phase - Maniu
Maniu does not forge a key. They have 1 amber. The current cost is 6 Æmber
House phase - Maniu
Maniu chooses saurian as their active house this turn
Main phase - Maniu
Maniu plays Imperial Road
Maniu uses Praefectus Ludo to make Praefectus Ludo fight Sanitation Engineer
VerifiedSnoopy uses Sanitation Engineer to deal 1 damage to Praefectus Ludo
Maniu plays Tribute, gaining 1 Æmber
Maniu uses Tribute to capture 2 Æmber from VerifiedSnoopy, placing it on Praefectus Ludo
Maniu exalts Praefectus Ludo to repeat the effect of Tribute
Maniu uses Tribute to capture 2 Æmber from VerifiedSnoopy, placing it on Praefectus Ludo
Maniu plays Ancient Power, gaining 1 Æmber
Maniu uses Ancient Power to ward all friendly creatures with Æmber on it
Maniu uses Odoac the Patrician to reap with Odoac the Patrician
Maniu uses Odoac the Patrician to reap with Odoac the Patrician
Maniu uses Praefectus Ludo to reap with Praefectus Ludo
Ready phase - Maniu
Maniu readies all of their cards
Draw phase - Maniu
Maniu draws 3 cards up to their maximum hand size of 6
 Maniu declares Check!
End of turn 4
Maniu: 6 Æmber VerifiedSnoopy: 0 Æmber
Turn 4
Key phase - VerifiedSnoopy
VerifiedSnoopy does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - VerifiedSnoopy
VerifiedSnoopy chooses logos as their active house this turn
Main phase - VerifiedSnoopy
VerifiedSnoopy plays Twin Bolt Emission, gaining 1 Æmber
VerifiedSnoopy uses Twin Bolt Emission to deal 2 damage to Praefectus Ludo and Hugger-Mugger
Maniu uses Praefectus Ludo to remove its ward token
VerifiedSnoopy uses Hapsis to make Hapsis fight Praefectus Ludo
VerifiedSnoopy uses Babbling Bibliophile to reap with Babbling Bibliophile
VerifiedSnoopy uses Babbling Bibliophile to draw 2 cards
VerifiedSnoopy plays Self-Bolstering Automata
VerifiedSnoopy uses Titan Guardian to reap with Titan Guardian
Ready phase - VerifiedSnoopy
VerifiedSnoopy readies all of their cards
Draw phase - VerifiedSnoopy
 VerifiedSnoopy declares Check!
End of turn 4
Maniu: 6 Æmber VerifiedSnoopy: 7 Æmber
Turn 5
Key phase - Maniu
Maniu forges the red key , paying 6 Æmber
House phase - Maniu
Maniu chooses staralliance as their active house this turn
Main phase - Maniu
Maniu plays Tactical Officer Moon
Maniu uses Tactical Officer Moon to rearrange creatures on a battleline
Maniu plays Quintrino Flux
Maniu uses Quintrino Flux to destroy Hugger-Mugger, Whisper, Self-Bolstering Automata, and Babbling Bibliophile
VerifiedSnoopy uses Self-Bolstering Automata to heal all damage from Self-Bolstering Automata, exhaust it and move it to a flank
Maniu plays Uncharted Lands
Maniu uses Uncharted Lands to place 6 Æmber on Uncharted Lands
Maniu plays Disruption Field, gaining 1 Æmber attaching it to Titan Guardian
Ready phase - Maniu
Maniu readies all of their cards
Draw phase - Maniu
Maniu draws 4 cards up to their maximum hand size of 6
End of turn 5
Maniu: 1 Æmber VerifiedSnoopy: 7 Æmber
Turn 5
Key phase - VerifiedSnoopy
VerifiedSnoopy forges the red key , paying 6 Æmber
House phase - VerifiedSnoopy
VerifiedSnoopy chooses staralliance as their active house this turn
VerifiedSnoopy moves all the cards in their archives to their hand
Main phase - VerifiedSnoopy
VerifiedSnoopy plays Techivore Pulpate
VerifiedSnoopy plays Cloaking Dongle, gaining 1 Æmber attaching it to Titan Guardian
VerifiedSnoopy plays First Officer Frane
Maniu
hmm. I think disruption field shouldnt work like that ;p
VerifiedSnoopy uses First Officer Frane to capture 1 Æmber from Maniu, placing it on Titan Guardian
VerifiedSnoopy
how do you mean
VerifiedSnoopy plays Information Officer Gray
VerifiedSnoopy uses Information Officer Gray to reveal A. Vinda from their hand, and archive it
Maniu
I'm the owner of upgrade, so your key should cost 1 more
Maniu
BUT
VerifiedSnoopy
ooohhh
VerifiedSnoopy
i didnt even realize
VerifiedSnoopy
i thought it was a smart play
Maniu
Your creature should gain fight/reap effect
VerifiedSnoopy
yeah thats lame you are right
VerifiedSnoopy plays Quadracorder, attaching it to Titan Guardian
VerifiedSnoopy plays Cloaking Dongle, gaining 1 Æmber attaching it to First Officer Frane

**Comment by romanogit** [comment]
This is fixed. I have a deck and played with it several times today.
