### ISSUE TITLE
Self-Bolstering Automata getting +2 Power when all conditions not met

### ISSUE THREAD

**Issue by muircurial** [keyteki/keyteki#1012]
Card reads: " If you have any other creatures in play, instead of destroying Self-Bolstering Automata, fully heal it, exhaust it, and move it to a flank. If you do, give it two +1 power counters."

Currently, I can use the Automata to fight (which exhausts it). If it then is marked for destruction, it will heal and move to a flank. However, it is already exhausted and should not receive the +1 power counters.

**Comment by dlocke** [comment]
I can confirm that this is still an issue.

**Comment by romanogit** [comment]
This is fixed in feature/mm branch . 
See PR https://github.com/keyteki/keyteki/pull/1323

**Comment by romanogit** [comment]
Keeping just https://github.com/keyteki/keyteki/issues/1469 opened
