### ISSUE TITLE
Pip Pip triggers before reap not after reap

### ISSUE THREAD

**Issue by DaveCordeiro** [keyteki/keyteki#1013]
Ugluk4242 uses Yxilo Bolter to reap with Yxilo Bolter
Batnu uses Pip Pip to stun Yxilo Bolter
Ugluk4242 uses Yxilo Bolter to deal 2 damage to Pip Pip

I was watching this game and noticed that the bolter got stunned when it would not have if the timing chart had been followed. REAP: happens during the reap, and After Reap happens after. Pip would not be in play to stun the bolter.

**Comment by cryogen** [comment]
Actually, Reap and after reap happen in the same window

**Comment by hydrophilic-attack** [comment]
Indeed they are in the same window, which means that the active player should be allowed to change the order in which they happen. Unless something has been changed very recently, this is one of those situations where the prompt to order simultaneous abilities doesn't work properly. Same as play abilities on 1 power creatures vs damage from Bellowing Patrizate where active player currently is not able to choose the order in which they resolve (at least not in the case of neutron shark where damage currently kills it before you get the chance to trigger the play ability).

I know you're concerned that allowing the player to order each and every ability that occurs in the same window would slow the game down to a crawl and be annoying for players. But until you all figure out the right balance on how to do that, may I suggest to, in the meantime, make more intelligent assumptions on which abilities the active player would prefer to happen first. 99% of the time active player would prefer to have reap abilities trigger before abilities that stun or destroy creatures after they have reaped. 99% of the time active player would prefer to have play abilities trigger before abilities that deal damage to a creature after entering play.

**Comment by romanogit** [comment]
I will add a test case to this one, but I believe it has been fixed by the Timing Refactor

![image](https://user-images.githubusercontent.com/2104075/79578791-1512dd00-809d-11ea-98f7-be895c26d1e5.png)

![image](https://user-images.githubusercontent.com/2104075/79578800-193efa80-809d-11ea-9340-b243e2e55a72.png)

**Comment by romanogit** [comment]
This issue does not happen anymore after Timing Refactor and proper game properties enabled:

![image](https://user-images.githubusercontent.com/2104075/79698482-91edb480-825f-11ea-9899-9a50d3390150.png)
