### ISSUE TITLE
The Floor is Lava Timing

### ISSUE THREAD

**Issue by bensissel** [keyteki/keyteki#1018]
The timing is off. It's supposed to be at the start of my turn before I choose a house. A House Plant creature was able to gain one off of me choosing before the floor is lava killed it.

**Comment by romanogit** [comment]
![image](https://user-images.githubusercontent.com/2104075/70256265-f7388180-1766-11ea-87dd-632898c7f059.png)

**Comment by romanogit** [comment]
This is not a bug:

![image](https://user-images.githubusercontent.com/2104075/73541095-5b4a8f80-4410-11ea-8187-acb5eba4e94d.png)

The Floor is Lava happens right before 1.1

Untamed Plant happens after 2.1

**Comment by bensissel** [comment]
Exactly- it is bugged. Right I have The floor is Lava out, And the prompt should start at the START of my turn. Currently- I am forging a key, choosing a house, THEN selecting targets for the Floor is Lava. Which is wrong. Please reopen the issue. it's not resolved.

**Comment by romanogit** [comment]
That's true. I misread the issue.

**Comment by romanogit** [comment]
Just submitted a PR for it.
