### ISSUE TITLE
Dis - Gabos Longarms

### ISSUE THREAD

**Issue by Grenmund** [keyteki/keyteki#1029]
The DIS card "Gabos Longarms" states that, "Before Fight: Choose a creature. Gabos Longarms deals damage to that creature rather than the one it is fighting." However within Crucible Online, the targeting works but the card still only does the damage to the second creature.

https://decksofkeyforge.com/cards/gabos-longarms

**Comment by romanogit** [comment]
@Grenmund : I don't understand this bug report. You say it only does damage to the second creature and I believe that's how it is supposed to work.

**Comment by SkyJedi** [comment]
https://archonarcana.com/Gabos_Longarms

Gabos only does damage on the creature targeted by his ability, not the creature it targets to fight.
