### ISSUE TITLE
Imperial Road playing creature already in play

### ISSUE THREAD

**Issue by gamer1886** [keyteki/keyteki#1030]
I just played a match in which my opponent used Imperial Road to repeatedly play Senator Shrix allowing him to exalt it every turn.

**Comment by romanogit** [comment]
![image](https://user-images.githubusercontent.com/2104075/71088196-a704ea80-217c-11ea-9664-29e76c2dc6e3.png)

**Comment by gamer1886** [comment]
Sorry, my fault, I mentioned it in the title but not in my comment.  The creature was already in play and it was allowing him to trigger the play effect of the creature again.

**Comment by romanogit** [comment]
I am unable to reproduce this one:

![image](https://user-images.githubusercontent.com/2104075/71202542-3a244a00-227b-11ea-9680-499e5ef7d180.png)

We cannot select the creature in play (it is grayed out)

**Comment by cryogen** [comment]
Reproduction steps:

0. Make sure there are no saurian creates in hand
1. Trigger Imperial Road and play a saurian creature out of turn
2. (Optional) unstun the creature
3. End the turn
4. Trigger Imperial Road
5. Note that it plays the last played card, again
