### ISSUE TITLE
Favor of Rex on opposing Restringuntus does not work properly

### ISSUE THREAD

**Issue by DaveCordeiro** [keyteki/keyteki#1031]
Favor of rex on my opponent's restringuntus should lock my opponent out of whatever house I choose, instead it locks me out of whatever house I choose.
https://pastebin.com/QUC6LWT1
![image](https://user-images.githubusercontent.com/57851149/70664668-7975e980-1c30-11ea-8009-90e46b38e17d.png)

**Comment by DaveCordeiro** [comment]
Tested again this time choosing a house in the favor of rex deck to confirm 
![image](https://user-images.githubusercontent.com/57851149/70665030-46802580-1c31-11ea-9061-405392c01253.png)

**Comment by romanogit** [comment]
![image](https://user-images.githubusercontent.com/2104075/71606721-4ac5a180-2b52-11ea-8e30-c0cebb83bb51.png)

**Comment by DaveCordeiro** [comment]
FAvor of rex also doesn't work right with opposing creatures capturing aember. It should capture from the opponent of the favor of rex player, not the opponent of the creature that captures things

**Comment by jeremylarner** [comment]
Fixed in #1247
