### ISSUE TITLE
Quintrino Flux destroys warded creatures when chosen powers are equal

### ISSUE THREAD

**Issue by strib** [keyteki/keyteki#1032]
In [this log](https://www.thecrucibletracker.com/games/cea9f930-1c87-11ea-977d-3b5a45bd2ef0), on nedmike's turn 2, they play Quintrino Flux and choose a warded, exalted Centurion Stenopius (current power 6) on their side, and a Champion Anaphiel (power 6) on the other side.  The Centurion was destroyed, even though it was warded.  I'm pretty sure the destruction only happens once, and so the ward should be removed but the creature not destroyed.

![image](https://user-images.githubusercontent.com/8516691/70679374-c0240d80-1c49-11ea-9943-2065b232c2ef.png)

Thanks!

**Comment by stebsteb** [comment]
It would be worht testing the behaviour of Standardized Testing too

**Comment by romanogit** [comment]
![image](https://user-images.githubusercontent.com/2104075/71177969-ee0de100-224b-11ea-8308-183fb05fd10c.png)
