### ISSUE TITLE
Shadow of Dis

### ISSUE THREAD

**Issue by Organwolf** [keyteki/keyteki#1033]
Yo, shadow of dis doesn't work. It should stop play effects for example, which it doesn't. Fix it and keep up the good work.

**Comment by JTLSound** [comment]
Do you have a screenshot? Or a copy of the chat? Please read the Pinned Issue before posting.

**Comment by stebsteb** [comment]
Duplicate of #359 and #386 
Please search previous issues before posting!

**Comment by Organwolf** [comment]
Never!

**Comment by Organwolf** [comment]
Although the issue isn't resolved yet it appears that other keyforge lovers have brought the issue to the devs attention. 
Auviedersen
