### ISSUE TITLE
2x Mimic Gel - Error

### ISSUE THREAD

**Issue by sirkooze** [keyteki/keyteki#1035]
![thumbnail_image1](https://user-images.githubusercontent.com/58870055/70842780-0f527580-1de5-11ea-916e-8038de8b47e1.jpg)

Apologies for closing my TCO window before gathering all information.

Issue occured when trying to play a second Mimic Gel on my side.
First Mimic Gel was played to copy an opponents Grom-Nine Toes.
Second Mimic Gel was played a few turns later when first Mimic Gel had 2 damage on it, but received error and the second Mimic Gel was sent to discard pile.
We turned on manual mode and I tried to drag Mimic Gel from discard pile onto battlefield, but it didn't work. Then I tried to putting it to my hand which worked. Turned off manual mode and tried to play Mimic Gel again, but received same error and Mimic Gel was sent to the discard pile.

Unfortunately I left the game so I could not test to remove the first Mimic Gel to see if that was the problem.

Deck name is "Rhomforce, the Ruffian Roboticist"
https://www.keyforgegame.com/deck-details/6a3704a6-ced1-42db-ac96-fbd67d5a728d

**Comment by sirkooze** [comment]
ok tried again in another match and same thing:

![image](https://user-images.githubusercontent.com/58870055/70843037-bb499000-1de8-11ea-94c1-2d01e668f4e0.png)

CHAT LOG
kooze is shuffling their deck
Vguras is shuffling their deck
kooze is playing as the Archon: Rhomforce, the Ruffian Roboticist
Vguras is playing as the Archon: Rioter Lucretia Splinterdingo
 kooze has connected to the game server
 Vguras has connected to the game server
kooze
gl hf
kooze draws 6 cards  up to their maximum hand size of 6
Vguras draws 6 cards  up to their maximum hand size of 6
Vguras
hi :)
Key phase - kooze
kooze does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - kooze
kooze chooses logos  as their active house this turn
Main phase - kooze
kooze plays Hologrammophone, gaining 1 Æmber 
Ready phase - kooze
kooze readies all of their cards 
Draw phase - kooze
End of turn 1
kooze: 1 Æmber  Vguras: 0 Æmber 
Turn 1
Key phase - Vguras
Vguras does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Vguras
Vguras chooses saurian  as their active house this turn
Main phase - Vguras
Vguras plays Tricerian Legionary
Vguras uses Tricerian Legionary to ward Tricerian Legionary
Vguras plays Imperial Scutum, gaining 1 Æmber  attaching it to Tricerian Legionary
Ready phase - Vguras
Vguras readies all of their cards 
Draw phase - Vguras
Vguras draws 2 cards  up to their maximum hand size of 6
End of turn 1
kooze: 1 Æmber  Vguras: 1 Æmber 
Turn 2
Key phase - kooze
kooze does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - kooze
kooze chooses saurian  as their active house this turn
Main phase - kooze
kooze plays Thero Centurion
kooze uses Thero Centurion to capture 1 Æmber  from Vguras, placing it on Thero Centurion
kooze plays Rhetor Gallim
kooze uses Rhetor Gallim to increase Vguras's key cost by 3 until the end of their next turn
kooze plays Imperium, gaining 1 Æmber 
kooze uses Imperium to ward Rhetor Gallim and Thero Centurion
Ready phase - kooze
kooze readies all of their cards 
Draw phase - kooze
kooze draws 3 cards  up to their maximum hand size of 6
End of turn 2
kooze: 2 Æmber  Vguras: 0 Æmber 
Turn 2
Key phase - Vguras
Vguras does not forge a key. They have 0 amber. The current cost is 9 Æmber 
House phase - Vguras
Vguras chooses brobnar  as their active house this turn
Main phase - Vguras
Vguras discards Ballcano
Vguras plays Tremor
Vguras uses Tremor to stun Rhetor Gallim and Thero Centurion
Vguras plays Alaka
Ready phase - Vguras
Vguras readies all of their cards 
Draw phase - Vguras
Vguras draws 3 cards  up to their maximum hand size of 6
End of turn 2
kooze: 2 Æmber  Vguras: 0 Æmber 
Turn 3
Key phase - kooze
kooze does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - kooze
kooze chooses saurian  as their active house this turn
Main phase - kooze
kooze exhausts Rhetor Gallim to remove its stun
kooze exhausts Thero Centurion to remove its stun
kooze plays Thero Centurion
kooze plays Sic Semper Tyrannosaurus
kooze uses Sic Semper Tyrannosaurus to take all Æmber  from Thero Centurion and destroy it
kooze uses Thero Centurion to remove its ward token
Ready phase - kooze
kooze readies all of their cards 
Draw phase - kooze
kooze draws 2 cards  up to their maximum hand size of 6
End of turn 3
kooze: 3 Æmber  Vguras: 0 Æmber 
Turn 3
Key phase - Vguras
Vguras does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Vguras
Vguras chooses brobnar  as their active house this turn
Main phase - Vguras
Vguras plays Alaka
Vguras plays Mogghunter
Vguras plays Fyre-Breath, gaining 1 Æmber  attaching it to Mogghunter
Vguras uses Alaka to reap with Alaka
Ready phase - Vguras
Vguras readies all of their cards 
Draw phase - Vguras
Vguras draws 3 cards  up to their maximum hand size of 6
End of turn 3
kooze: 3 Æmber  Vguras: 2 Æmber 
Turn 4
Key phase - kooze
kooze does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - kooze
kooze chooses logos  as their active house this turn
Main phase - kooze
kooze plays Hologrammophone, gaining 1 Æmber 
kooze plays Mini Groupthink Tank
kooze uses Mini Groupthink Tank to deal 8 damage to Rhetor Gallim
kooze uses Rhetor Gallim to remove its ward token
kooze plays Mimic Gel
kooze uses Mimic Gel to to copy Mogghunter
kooze plays Wormhole Technician
kooze uses Hologrammophone to ward Mogghunter
Ready phase - kooze
kooze readies all of their cards 
Draw phase - kooze
kooze draws 4 cards  up to their maximum hand size of 6
End of turn 4
kooze: 4 Æmber  Vguras: 2 Æmber 
Turn 4
Key phase - Vguras
Vguras does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - Vguras
Vguras chooses brobnar  as their active house this turn
Main phase - Vguras
Vguras plays Stilt-Kin
Vguras uses Alaka to reap with Alaka
Vguras uses Mogghunter to make Mogghunter fight Mini Groupthink Tank
Vguras uses Mogghunter to deal 2 damage to the neighbors of Mogghunter
kooze uses Mogghunter to remove its ward token
Vguras uses Mogghunter to deal 2 damage to Thero Centurion
Vguras uses Alaka to reap with Alaka
Vguras plays Blood Money
Vguras uses Blood Money to place 2 Æmber  on Mogghunter
Ready phase - Vguras
Vguras readies all of their cards 
Draw phase - Vguras
Vguras draws 2 cards  up to their maximum hand size of 6
End of turn 4
kooze: 4 Æmber  Vguras: 4 Æmber 
Turn 5
Key phase - kooze
kooze does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - kooze
kooze chooses shadows  as their active house this turn
Main phase - kooze
kooze plays No Safety in Numbers, gaining 1 Æmber 
kooze uses No Safety in Numbers to deal 3 damage to Thero Centurion, Rhetor Gallim, Thero Centurion, Stilt-Kin, Alaka, Tricerian Legionary, Alaka, and Mogghunter
Vguras uses Tricerian Legionary to remove its ward token
kooze plays Yantzee Gang
 kooze has disconnected. The game will wait up to 30 seconds for them to reconnect
 kooze has reconnected
 kooze has connected to the game server
kooze plays Kymoor Eclipse
kooze uses Kymoor Eclipse to return Yantzee Gang, Thero Centurion, Alaka, and Mogghunter to their deck
kooze is shuffling their deck
Vguras is shuffling their deck
kooze plays J. Vinda
Ready phase - kooze
kooze readies all of their cards 
Draw phase - kooze
kooze draws 4 cards  up to their maximum hand size of 6
End of turn 5
kooze: 5 Æmber  Vguras: 4 Æmber 
Turn 5
Key phase - Vguras
Vguras does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - Vguras
Vguras chooses saurian  as their active house this turn
Main phase - Vguras
Vguras plays Diplo-Macy, gaining 1 Æmber 
Vguras uses Diplo-Macy to apply a lasting effect
Vguras plays Tricerian Legionary
Vguras uses Tricerian Legionary to ward Tricerian Legionary
Vguras uses Tricerian Legionary to make Tricerian Legionary fight Mogghunter
Vguras uses Tricerian Legionary to exalt Tricerian Legionary
Vguras plays Imperium, gaining 1 Æmber 
Vguras uses Imperium to ward Alaka and Tricerian Legionary
Ready phase - Vguras
Vguras readies all of their cards 
Draw phase - Vguras
Vguras draws 3 cards  up to their maximum hand size of 6
 Vguras declares Check!
End of turn 5
kooze: 5 Æmber  Vguras: 6 Æmber 
Turn 6
Key phase - kooze
kooze does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - kooze
kooze chooses logos  as their active house this turn
Main phase - kooze
kooze plays Information Exchange
kooze uses Information Exchange to steal 1 Æmber  from Vguras
kooze plays Hapsis
kooze uses Hologrammophone to ward Mogghunter
kooze uses Wormhole Technician to reap with Wormhole Technician
kooze uses Wormhole Technician to reveal Fidgit, which is not a Logos  card, so it gets archived
kooze uses Mogghunter to make Mogghunter fight Tricerian Legionary
kooze uses Mogghunter to exalt Mogghunter
kooze uses Mogghunter to remove its ward token
Vguras uses Tricerian Legionary to remove its ward token
kooze uses Mogghunter to deal 2 damage to Tricerian Legionary
Vguras uses Tricerian Legionary to remove its ward token
kooze uses Hologrammophone to ward Mogghunter
kooze plays Mimic Gel
A Server error has occured processing your game state, apologies. Your game may now be in an inconsistent state, or you may be able to continue. The error has been logged.
kooze
yeah this deck is not playable
kooze
the game bugs when i play 2 mimic gels
Vguras
:)
kooze
happened last game too, but wasn't sure if it was a bug
kooze
i'm going to report this and quit game, gg
Vguras
ok :)
Vguras
well
Vguras
it was nice game?
Vguras
:)
 Vguras has left the game

**Comment by sebastienode** [comment]
Do you have an ETA about the correction ?

**Comment by romanogit** [comment]
Working on this one...
