### ISSUE TITLE
2 feature requests

### ISSUE THREAD

**Issue by scrowner** [keyteki/keyteki#1036]
1. Add a current key forging aember adjustment counter for modifiers on the board.

2. Add a window to slide action cards across the play field indicating they were played before entering the discard.

**Comment by JTLSound** [comment]
I think both of these already exist. The current key cost is reported in the chat at the beginning of each turn. You can click drag cards from you hand to play to play them. If you do this with an action card, it will enter the discard, indicating that it's been played.
