### ISSUE TITLE
memory chip : order of archive

### ISSUE THREAD

**Issue by skrohmagnon** [keyteki/keyteki#105]
the two following effects become after choosing you house. The active player should choose the order
- take your archives back
- archive a card with memory chip

**Comment by Deuzerre** [comment]
Huh, no.
Rulebook: After choosing a house, the active player has the option to take all
cards in their archives and add them to their hand. (See “Archives” in
the Glossary.)
Archives in the glossary: . During step 2 of a player’s turn,
after they select an active house, the active player is permitted to pick up
all cards in their archives and add those cards to their hand.

Memory chip: After you select logos as your active house, archive a card.
They are simultaneous.

So the active player should get to choose in which order they decide.

**Comment by cryogen** [comment]
I think you both just said the same thing :)

**Comment by cryogen** [comment]
![image](https://user-images.githubusercontent.com/1053365/68840095-f2c5ff00-06b9-11ea-929d-7c26449d7faf.png)

The new (since this issue was raised) timing chart clarifies the order of these events and we do get it right, so closing this.
