### ISSUE TITLE
Imperial Traitor not showing opponents hand

### ISSUE THREAD

**Issue by mikefuni** [keyteki/keyteki#1051]
This has happened multiple times. So far every game I played my opponent did not have sanctum. I have attached a screen shot of the chat/history window

![ImperialTraitor](https://user-images.githubusercontent.com/58352562/71278487-c12dfc80-2325-11ea-8991-f83a59ebeb3d.png)

**Comment by romanogit** [comment]
This has been recently fixed. It only happens if opponent does not have a Sanctum card in his hand.
#1038

**Comment by romanogit** [comment]
It should be moved to live server soon.
