### ISSUE TITLE
Controller of Gargantadon kills an opponent's Magda the Rat

### ISSUE THREAD

**Issue by entropyguardian** [keyteki/keyteki#1054]
It looks like the active player should be forced to capture the aember on one of their own creatures (Garganadon's allies) instead of stealing it.

How it works now apparently is it allows you to force your opponent's creature to capture it which is completely wrong.

**Comment by entropyguardian** [comment]
![Untitled](https://user-images.githubusercontent.com/53681800/71305051-fd984180-2393-11ea-83fd-ef255aecc9f2.png)

**Comment by romanogit** [comment]
Fixed by #1107
