### ISSUE TITLE
Crassosaurus not purging 

### ISSUE THREAD

**Issue by Bigstubbo** [keyteki/keyteki#1055]
I have just played Crassosaurus and only put 3 ember on it, when I clicked done I expected it to be purged,  it was not it just sat on my side like any other creature.

**Comment by romanogit** [comment]
![image](https://user-images.githubusercontent.com/2104075/71681253-f21d2100-2d6a-11ea-9287-dfd483331118.png)

**Comment by Bigstubbo** [comment]
Yes that is the card, should there be a comment?

**Comment by romanogit** [comment]
@Bigstubbo : just added the card here for quick reference
