### ISSUE TITLE
Consistency with "amber" vs "Æmber"

### ISSUE THREAD

**Issue by avehlies** [keyteki/keyteki#1056]
When a user cannot forge a key, the following message appears:
>(User) does not forge a key. They have 3 amber. The current cost is 5 Æmber

The "amber" in "They have 3 amber." should be spelled with the "Æ" character.

There may be other places that the word "amber" appears in text.

**Comment by avehlies** [comment]
This is probably very low priority, but I can fix it. I can also do a quick look around for other uses.

**Comment by cryogen** [comment]
Amber is replaced with Æmber on the client side, so if it's inconsistent, it's a bug there, no need to change any wording.  I suspect the full stop after the first amber in your example is the issue
