### ISSUE TITLE
Marmo Swarm and Gub "Power Gain" Issue.

### ISSUE THREAD

**Issue by PerigoCigano** [keyteki/keyteki#1057]
I Was playing a game with a friend, he played Marmo Swarm, having "x" Æmbar in his Pool. The Marmo Swarm didn't get the power bonus per Æmbar. Similar, the Gub card didn't get the bonus and effect for not being in the flank.

Deck: https://www.keyforgegame.com/deck-details/986a7d1f-c557-4037-92e0-e972b32a8187

**Comment by romanogit** [comment]
I have a deck with Gub and Marmo Swarm and they work well, no issues.
Is there a chance your opponent played Shadow of Dis?
![image](https://user-images.githubusercontent.com/2104075/71327986-a955a480-24ee-11ea-87ee-82bbe73fbce1.png)

**Comment by PerigoCigano** [comment]
No, It persisted through multiple turns. And the cards didn't gain the buff at all.

**Comment by romanogit** [comment]
Why do you say they did not get the power. TCO does not have a power increase icon. Only if the creature gains power tokens. Gub and marmo swarn do not get an icon
