### ISSUE TITLE
In deck page, archon back always keep the result from the first page

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#1069]
In deck page, archon back always keep the result from the first page.
when you click the deck name, the summary shows the correct image, though.
Bellow shows page two:
![image](https://user-images.githubusercontent.com/2104075/71630304-f61d3780-2be0-11ea-9151-f23765e5922d.png)
@SkyJedi

**Comment by SkyJedi** [comment]
https://github.com/keyteki/keyteki/pull/1008  this has been fixed
