### ISSUE TITLE
Active player with Gargantuon and steal with Brend the Fanatic

### ISSUE THREAD

**Issue by unzinc** [keyteki/keyteki#1070]
I had Brend the Fanatic in my battle line. Opponent had a Gargantuon. 

On my opponent's turn they kill my Brend the Fanatic. Gargantuon's replacement effect says any stolen amber is captured by a creature of the active player. However, one of my creatures captured the 3 amber instead from my opponent. It should have been one of their  creatures capturing from themselves. 

Anon. turn 9 https://www.thecrucibletracker.com/games/248cbf00-2bff-11ea-8f01-c3dd366cb390

![image](https://user-images.githubusercontent.com/46981693/71632112-ee05cd80-2bc9-11ea-83df-4f72c7607420.png)

**Comment by romanogit** [comment]
Fixed by #1107
