### ISSUE TITLE
Mimicry + Swindle

### ISSUE THREAD

**Issue by unzinc** [keyteki/keyteki#1071]
Opponent played Mimicry. Copied my Swindle. Profited.

**Comment by unzinc** [comment]
Sorry, and then played about 5 other Untamed cards on their turn.

**Comment by KiVi-Kopf** [comment]
Same with Mimicry + Eureka! So it seems to be a bug with Mimicry + Alpha / Omega.
![ddd](https://user-images.githubusercontent.com/36154617/73129067-b0833d00-3fdb-11ea-9c2a-b4a396bc2a0d.PNG)
