### ISSUE TITLE
Warded Rhetor Gallim was not destroyed by Bloodshard Imp

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#1075]
Rhetor Gallim was warded and then opponent played Bloodshard Imp. I reaped with RG, and it was not sacrified, but the ward token was not removed.

```
romanomagacho22 uses Rhetor Gallim to reap with Rhetor Gallim
romanomagacho22 uses Gargantodon to make Gargantodon fight Bloodshard Imp
```

![image](https://user-images.githubusercontent.com/2104075/71723513-ab333800-2e0b-11ea-81ca-0adf5e16d5ff.png)

![image](https://user-images.githubusercontent.com/2104075/71723507-a1113980-2e0b-11ea-90a6-ee6cf4d80ad3.png)

**Comment by romanogit** [comment]
To be able to recreate, we cannot click to exalt Rhetor Gallim. Click the Done button.

**Comment by admiraldeathrain** [comment]
I could reproduce this even with unwarded creatures. Tested with Rhetor and Livia the Elder, appears to be an issue with optional reap-abilities, they seem to make all reap-abilities optional.

**Comment by romanogit** [comment]
@admiraldeathrain ,
seems to be a different issue. What happened with Rethor and Livia the Elder?

**Comment by romanogit** [comment]
I am not able to recreate my original issue anymore. I see a PR that could have fixed this:
https://github.com/keyteki/keyteki/pull/1100

This may not be in production yet.

**Comment by romanogit** [comment]
@cryogen : can you confirm if https://github.com/keyteki/keyteki/pull/1100 is already live?

**Comment by admiraldeathrain** [comment]
I did test locally, but I'm afraid my working files were outdated by about a week or so, so if a fix has been merged in that time I wouldn't have that.

**Comment by cryogen** [comment]
> @cryogen : can you confirm if #1100 is already live?

Negative. Will be deploying today

**Comment by romanogit** [comment]
Fixed by https://github.com/keyteki/keyteki/pull/1100
