### ISSUE TITLE
Review unstun ruling for out of house unstun

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#1076]
The new ruling does not allow unstun for non-house cards, unless another card forces you to use the stunned card, such as a Gangerchief.

A few cards need retest after unstun is updated:
- [ ] Deipno Spymaster: Omni: Choose a friendly creature. You may use that creature this turn. : https://archonarcana.com/Deipno_Spymaster
- [ ] HOUSE Ambassador: Fight/Reap: You may play or use a HOUSE card this turn. 
- [ ] Horseman of War: https://archonarcana.com/index.php?title=Outstanding_Issues#Submitted_9.2F16.2F2019
- [ ] Combat Pheromones
- [ ] Signal of Fire

**Comment by 4ugeistr** [comment]
Hi. 
Can you please quote what ruling are you refering to?

I might have missed something, but the latest (v11, Dec 2016) rulebook still contains clarification implying that "may Use" cards can be used to remove stun tokens:
![image](https://user-images.githubusercontent.com/23107141/73234144-9a1ee200-4191-11ea-8ae8-0773662026fd.png)

**Comment by 4ugeistr** [comment]
[Deleted my comment after reading the Stun status ruling changes carefully]

**Comment by romanogit** [comment]
This ruling was rolledback
