### ISSUE TITLE
Spangler Box and Ward

### ISSUE THREAD

**Issue by JTLSound** [keyteki/keyteki#1079]
Spangler Box should remove the Ward, and stay in the owner's control (as a creature was not Purged). Instead, it ignores Ward, and acts as it normally would.
![Screen Shot 2020-01-03 at 6 30 22 PM](https://user-images.githubusercontent.com/49758354/71755145-574e4080-2e57-11ea-8afc-0f5106c3ef27.jpg)

**Comment by romanogit** [comment]
This one is fixed in #1328 . When we merge MM features to branch master, this one will be fixed together.
