### ISSUE TITLE
Bellowing Patrizate + Helper Bot

### ISSUE THREAD

**Issue by GavinForge** [keyteki/keyteki#1080]
When Helper Bot is played, active player should be able to decide which to resolve first: Helper Bot's play ability or Bellowing Patrizate since both 'Play' and 'After Play' abilities resolve in the same window and it would be active player's decision which to resolve first. Instead, currently in TCO, Bellowing Patrizate's 1 damage kills Helper Bot, before Helper Bot's play ability goes off.

I imagine Autocannon and similar cards would cause this situation. I wonder if other 1-power player ability cards would also be having the same issue in TCO currently.

**Comment by romanogit** [comment]
Hello @GavinForge ,
can you check your user profile page? At the very bottom, you have two check boxes:

![image](https://user-images.githubusercontent.com/2104075/71829641-db850b80-3083-11ea-817e-dace2922c5cd.png)

It would allow you to decide on the order of simultaneous abilities.

**Comment by GavinForge** [comment]
That the issue! Not sure how that got turned off. Thanks! Consider issue closed.
