### ISSUE TITLE
Interaction with Auto-Legionary and Mars Needs Aember

### ISSUE THREAD

**Issue by DubiousG320** [keyteki/keyteki#1084]
A damaged Auto-Legionary on the opponents battle line did not capture aember from from its own side when Mars Needs Aember was played. Text on the Auto-Legionary says that once it is on the battleline, it is considered a creature, not an artifact.

**Comment by jtrussell** [comment]
I believe that since Auto-Legionary belongs to house Mars when it's a creature MNA won't cause it to capture.

**Comment by DubiousG320** [comment]
Thank you for clarifying. There is additional text on Auto-Legionary that says it belongs to all houses.
