### ISSUE TITLE
Ortannu's reap effect ignores ward

### ISSUE THREAD

**Issue by dlocke** [keyteki/keyteki#1085]
When Ortannu the Chained is used to reap and a binding is returned from the discard pile, the damage (possibly just the splash damage) ignores ward. Because the creatures that were hit had more than two power, we were able to correct the result manually.

I was playing the first game of an adaptive match when I encountered this issue so I didn't save the game log.

**Comment by Osarek** [comment]
I confim damage and splash ignores ward
