### ISSUE TITLE
Obsidian Forge not allowing you to forge if no creatures have been sacrificed

### ISSUE THREAD

**Issue by UltraUltraUltra** [keyteki/keyteki#1092]
I had no creatures in play but plenty of aember to forge at current cost +6, but when I used Remote Access on my opponent's Obsidian Forge, I wasn't given the option to forge a key.

![2020-01-15 15_08_13-](https://user-images.githubusercontent.com/55008319/72447744-c7d95380-37ad-11ea-8d7e-1b053ba89f6a.png)

**Comment by romanogit** [comment]
Card text says:
Action: Sacrifice any number of friendly creatures. Then, you may forge a key at +6 Æmber current cost, reduced by 1 Æmber for each creature sacrificed this way. If you do, destroy Obsidian Forge. 

There is a `then` clause after sacrificing. I believe it is mandatory to sacrifice. I don't think 0 should be understood as any number. Even if you sacrifice none, it would not fulfill the previous clause and you would not execute the then clause.
