### ISSUE TITLE
why i can't use exhume then kill the creature with Hecatomb

### ISSUE THREAD

**Issue by cccchris72184** [keyteki/keyteki#1095]

**Comment by romanogit** [comment]
Was it a Dis creature?

**Comment by cccchris72184** [comment]
The card exhume has a description of you may play that creature as if it
belonged to the active house and was in your hand. If i choose dis as house
this turn, any creature that is revived by exhume should be count as dis
and should be destroy by hecatomb.

Romano Silva <notifications@github.com> 於 2020年1月17日 週五 下午11:14寫道：

**Comment by jtrussell** [comment]
The wording _as if_ here indicates that it is not actually becoming a member of the active house. You get to the creature as though it were from house Dis, but it is still not a Dis creature.

**Comment by romanogit** [comment]
This is not a bug
