### ISSUE TITLE
Papanca, Jaga

### ISSUE THREAD

**Issue by Herzbube76** [keyteki/keyteki#111]
Skirmish of Papanca, Jaga didnt work for my creatures. They were at the left side of Papanca, Jaga! I was verifying this :-) When try to manual couldnt deploy my cards what would be helpful to manual this bug.

**Comment by MorgothNL** [comment]
Same here

**Comment by Herzbube76** [comment]
Not fixed. STill the same problem. I played papanca at he right, so all creatures left should get skirmish, but they hadnt,

**Comment by cryogen** [comment]
Fix isn’t deployed to the site yet
