### ISSUE TITLE
Menolith is not working right

### ISSUE THREAD

**Issue by KeyforgeJupiter** [keyteki/keyteki#1119]
I grafted an action on to it and then can only continue to ask to graft but I can not use the cards under it

**Comment by romanogit** [comment]
Memolith is working as expected, even though the UX is not the best:

![image](https://user-images.githubusercontent.com/2104075/101219587-00527c00-3663-11eb-9dce-c12156e1907e.png)

You have to either click on the cards in your hand or the cards under it to activate their play effect. Maybe that was not very clear.
