### ISSUE TITLE
Alaka not entering play ready after attacking with Shorty

### ISSUE THREAD

**Issue by AlgernonR** [keyteki/keyteki#1122]
Played yesterday and used Shorty to attack, killing the opponents creature with the Assault damage. When playing Alaka after that the card entered play exhausted.

![8890ED12-3899-43B6-9545-2184167C3C2F](https://user-images.githubusercontent.com/60708264/73864570-3441f280-4842-11ea-8c2e-d76247353a85.png)

**Comment by romanogit** [comment]
Similar to #1148

**Comment by romanogit** [comment]
Dupe to #1148
