### ISSUE TITLE
timequake did not draw new cards

### ISSUE THREAD

**Issue by JEBailey** [keyteki/keyteki#1128]
Played timequake which shuffles all friendly cards in play into my deck and allows me to draw a card for each one shuffled.

The shuffling occurred correctly, but as a stated in the chat log, no cards were drawn

[chat.txt](https://github.com/keyteki/keyteki/files/4174581/chat.txt)
![Screenshot from 2020-02-08 10-39-52](https://user-images.githubusercontent.com/915311/74088174-3766f980-4a61-11ea-9ba9-a77767c6b243.png)

**Comment by andy-hartley** [comment]
Hi there, yes i have the same issue with timequake. It does happen this wasn't fixed since Feb

**Comment by romanogit** [comment]
The problem here was the warded Quant

**Comment by romanogit** [comment]
It was fixed by https://github.com/keyteki/keyteki/pull/1344
