### ISSUE TITLE
Enhancement: Property Icons

### ISSUE THREAD

**Issue by SeiferTim** [keyteki/keyteki#1131]
For a whole number of reasons (card scale, screen size, card art not loading, lots of cards on the screen at once, etc), it is _even easier_ to miss _important_ things while playing online.

For example, a card that has an end-of-turn effect, or cards that give neighbors properties...

I don't know how many times I've lost a game because I missed that a card had elusive because of a cloaking dongle, or there was a Bloodshard Imp in play with a 'broken image'.

I propose coming up with a series of small, unobtrusive, but helpful icons that could sit just above or below cards when they have elusive, or an automatic ability (like Strange Gizmo, or Peace Accord). Just to help make it a little more clear what's going on.

Similarly, I think it would be useful if cards had increased power from other cards (not +1 counters), that their total power could be displayed somewhere. Trying to figure out the math when someone has Tribune Pompitus and Primus Unguis out at the same time is not fun.

Further discussion to decide which cards/properties should have these icons would be ideal.

**Comment by SkyJedi** [comment]
Power level is done, Armor is next on my list

**Comment by SkyJedi** [comment]
armor and tokens are all done.

**Comment by romanogit** [comment]
@SkyJedi , can we close this one?

**Comment by romanogit** [comment]
@SkyJedi : I noticed that for gigantic creatures, power / armor are not aligned with original image.

**Comment by romanogit** [comment]
This is done
