### ISSUE TITLE
Missing fuse token for 'The Big One'

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#1137]
Missing fuse token for 'The Big One'

**Comment by SkyJedi** [comment]
Hows this? 
![image](https://user-images.githubusercontent.com/2967416/77711707-ad86d780-6f9f-11ea-906e-dc0159973d2f.png)


![image](https://media.discordapp.net/attachments/606915584063570100/692906282566549534/050.png)

**Comment by romanogit** [comment]
Nice. I will try it tomorrow

**Comment by romanogit** [comment]
@SkyJedi : is that a transparent image?

**Comment by SkyJedi** [comment]
@romanogit i can get it transparent, just a placeholder at the moment

**Comment by SkyJedi** [comment]
![fuse](https://user-images.githubusercontent.com/2967416/78466488-33550200-76c7-11ea-9c68-bf82651b605a.png)
