### ISSUE TITLE
Morpheus and Kirby interaction fails in some situations

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#1138]
I was able to use Kirby and Morpheus fine, but I believe that if I play an artifact first, then I am unable to play a second non-SA action card.

**Comment by bensissel** [comment]
This has been a problem for me for while. I actually can't think of a single time this interaction has worked. Most of my kirby activations have been on upgrades.

**Comment by romanogit** [comment]
I am unable to replicate this one
