### ISSUE TITLE
Tezmal and Brain Stem Antenna 

### ISSUE THREAD

**Issue by Dabar53** [keyteki/keyteki#1144]
I was just in a game where I was not able to pick none of my houses and the opponent was not willing to let me do manual. 
The rules that keyforge provide state that when I can't pick any houses or I am forced to choose a house that is not eligible to be picked I can pick any of the houses as I must be able to choose a house

**Comment by romanogit** [comment]
I did not understand how Brain Stem Antenna affected this scenario.

**Comment by romanogit** [comment]
I belive Tezmal is working as designed:
![image](https://user-images.githubusercontent.com/2104075/101696679-3aea5900-3a55-11eb-9105-5e01da2c3f56.png)

Rules says if there is no available option, you go without an active house.
