### ISSUE TITLE
Finch Cloak with Duskrunner upgrade adds cards steal condition to the upgrade steal effect

### ISSUE THREAD

**Issue by donders** [keyteki/keyteki#1146]
![Finch Cloak](https://cdn.keyforgegame.com/media/card_front/en/452_267_G58J6265CQ3Q_en.png) 
 interacting with upgrade   
![Duskrunner](https://cdn.keyforgegame.com/media/card_front/en/452_253_P6MMX3WR7MC6_en.png)  
seems to apply the cards own condition to the upgrade's steal effect.

**Comment by romanogit** [comment]
@donders ,
This one is a bit old and it contains few information.
Do you have "Prompt for simultaneous abilities" checked in your profile (Go to Profile, scroll all the way to the bottom)? If not, the platform will resolve those abilities automatically, but not necessarily always in your favor.
The order of steal (upgrade or card) would matter for the card effect.

**Comment by romanogit** [comment]
Prompt is displayed:

![image](https://user-images.githubusercontent.com/2104075/101064914-492b0780-3573-11eb-8fb5-2dc995ee7829.png)

Selected Finch Cloak first

![image](https://user-images.githubusercontent.com/2104075/101064961-5647f680-3573-11eb-9db0-fe95007f47b3.png)

There might be situations where it can be tricky, depending on the order of reap resolution.

You need to enable the check box in game configuration:

![image](https://user-images.githubusercontent.com/2104075/101065042-6eb81100-3573-11eb-85f4-68884e868e2a.png)

It is disabled by default. You can set in your profile as well or per game.
