### ISSUE TITLE
Alaka does not enter ready after attacking with Sköll

### ISSUE THREAD

**Issue by HaircutPolice** [keyteki/keyteki#1148]
On turn 12 I fought with Skoll, destroying Chief Engineer Walls with its Assault damage. Then I played Alaka, which should have entered ready. However, Alaka entered exhausted.

Screenshots were taken when the game ended (sorry). Also I had my card sizes set to XL so it's hard to see what's going on.

I hope this helps.

Chat log:

HaircutPolice is shuffling their deck
Aselilath is shuffling their deck
 Aselilath has connected to the game server
 HaircutPolice has connected to the game server
HaircutPolice
hi
Aselilath
Heyo
Aselilath
Glhf :D
HaircutPolice
u2
HaircutPolice draws 6 cards  up to their maximum hand size of 6
Aselilath draws 6 cards  up to their maximum hand size of 6
Key phase - Aselilath
Aselilath does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Aselilath
Aselilath chooses saurian  as their active house this turn
Main phase - Aselilath
Aselilath plays Imperial Road
Ready phase - Aselilath
Aselilath readies all of their cards 
Draw phase - Aselilath
End of turn 1
HaircutPolice: 0 Æmber  (0 keys) Aselilath: 0 Æmber  (0 keys)
Turn 1
Key phase - HaircutPolice
HaircutPolice does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - HaircutPolice
HaircutPolice chooses shadows  as their active house this turn
Main phase - HaircutPolice
HaircutPolice plays Rigged Lottery, gaining 1 Æmber 
HaircutPolice uses Rigged Lottery to discard Explo-rover, Trust No One, Cowfyne, Shorty, and Lieutenant Khrkhar
HaircutPolice discards Explo-rover, Trust No One, Cowfyne, Shorty, and Lieutenant Khrkhar from HaircutPolice's deck, and HaircutPolice gains 1 amber. They also discard Brutodon Auxiliary, Cloaking Dongle, Buzzle, Senator Shrix, and Binding Irons from Aselilath's deck and Aselilath gains 0 Æmber 
Ready phase - HaircutPolice
HaircutPolice readies all of their cards 
Draw phase - HaircutPolice
HaircutPolice draws 1 cards  up to their maximum hand size of 6
End of turn 1
HaircutPolice: 2 Æmber  (0 keys) Aselilath: 0 Æmber  (0 keys)
Turn 2
Key phase - Aselilath
Aselilath does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Aselilath
Aselilath chooses staralliance  as their active house this turn
Main phase - Aselilath
Aselilath plays Chief Engineer Walls
Aselilath uses Chief Engineer Walls to return Cloaking Dongle to their hand
Aselilath plays Helmsman Spears
Aselilath plays Tactical Officer Moon
Aselilath uses Tactical Officer Moon to rearrange creatures on a battleline
Aselilath plays Cloaking Dongle, gaining 1 Æmber  attaching it to Tactical Officer Moon
Ready phase - Aselilath
Aselilath readies all of their cards 
Draw phase - Aselilath
Aselilath draws 3 cards  up to their maximum hand size of 6
End of turn 2
HaircutPolice: 2 Æmber  (0 keys) Aselilath: 1 Æmber  (0 keys)
Turn 2
Key phase - HaircutPolice
HaircutPolice does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - HaircutPolice
HaircutPolice chooses brobnar  as their active house this turn
Main phase - HaircutPolice
HaircutPolice plays Ballcano
HaircutPolice uses Ballcano to deal 4 damage to all creatures, gaining 2 chains
HaircutPolice plays Ragwarg, gaining 1 Æmber 
HaircutPolice discards Ballcano
Ready phase - HaircutPolice
HaircutPolice readies all of their cards 
Draw phase - HaircutPolice
HaircutPolice draws 2 cards  up to their maximum hand size of 6
HaircutPolice's chains are reduced by 1 to 1
End of turn 2
HaircutPolice: 3 Æmber  (0 keys) Aselilath: 1 Æmber  (0 keys)
Turn 3
Key phase - Aselilath
Aselilath does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Aselilath
Aselilath chooses dis  as their active house this turn
Main phase - Aselilath
Aselilath plays Lilithal
Aselilath plays Rotgrub
Aselilath uses Rotgrub to make HaircutPolice lose 1 Æmber 
Aselilath plays Not Finished with You, gaining 1 Æmber 
Aselilath uses Not Finished with You to return Tactical Officer Moon, Senator Shrix, Brutodon Auxiliary, Helmsman Spears, and Chief Engineer Walls to their deck
Aselilath is shuffling their deck
Aselilath uses Imperial Road to do several things
Aselilath plays Paraguardian
Ready phase - Aselilath
Aselilath readies all of their cards 
Draw phase - Aselilath
Aselilath draws 4 cards  up to their maximum hand size of 6
End of turn 3
HaircutPolice: 2 Æmber  (0 keys) Aselilath: 2 Æmber  (0 keys)
Turn 3
Key phase - HaircutPolice
HaircutPolice does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - HaircutPolice
HaircutPolice chooses staralliance  as their active house this turn
Main phase - HaircutPolice
HaircutPolice plays Sci. Officer Qincan
HaircutPolice plays Medic Ingram
HaircutPolice uses Medic Ingram to heal 3 damage and ward Sci. Officer Qincan
Ready phase - HaircutPolice
HaircutPolice readies all of their cards 
Draw phase - HaircutPolice
HaircutPolice draws 2 cards  up to their maximum hand size of 6
HaircutPolice's chains are reduced by 1 to 0
End of turn 3
HaircutPolice: 2 Æmber  (0 keys) Aselilath: 2 Æmber  (0 keys)
Turn 4
Key phase - Aselilath
Aselilath does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - Aselilath
Aselilath chooses dis  as their active house this turn
Main phase - Aselilath
Aselilath plays Etaromme
Aselilath uses Imperial Road to do several things
Aselilath plays Gargantodon
Aselilath uses Gargantodon to stun Gargantodon
Aselilath uses Lilithal to make Lilithal fight Medic Ingram
Aselilath uses Lilithal to capture 1 Æmber  from HaircutPolice, placing it on Lilithal
Aselilath uses Rotgrub to reap with Rotgrub
HaircutPolice uses Ragwarg to deal 2 damage to Rotgrub
Ready phase - Aselilath
Aselilath readies all of their cards 
Draw phase - Aselilath
Aselilath draws 2 cards  up to their maximum hand size of 6
End of turn 4
HaircutPolice: 1 Æmber  (0 keys) Aselilath: 3 Æmber  (0 keys)
Turn 4
Key phase - HaircutPolice
HaircutPolice does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - HaircutPolice
HaircutPolice chooses shadows  as their active house this turn
HaircutPolice uses Sci. Officer Qincan to steal 1 Æmber  from Aselilath
Aselilath uses Gargantodon
Main phase - HaircutPolice
HaircutPolice plays Umbra
Ready phase - HaircutPolice
HaircutPolice readies all of their cards 
Draw phase - HaircutPolice
HaircutPolice draws 2 cards  up to their maximum hand size of 6
End of turn 4
HaircutPolice: 1 Æmber  (0 keys) Aselilath: 2 Æmber  (0 keys)
Turn 5
Key phase - Aselilath
Aselilath does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - Aselilath
Aselilath chooses saurian  as their active house this turn
Main phase - Aselilath
Aselilath exhausts Paraguardian to remove its stun
Aselilath exhausts Gargantodon to remove its stun
Aselilath plays Chant of Hubris, gaining 1 Æmber 
Aselilath uses Chant of Hubris to remove 1 Æmber  from Lilithal
Aselilath uses Chant of Hubris to place 1 Æmber  on Gargantodon
Aselilath plays Brutodon Auxiliary
Ready phase - Aselilath
Aselilath readies all of their cards 
Draw phase - Aselilath
Aselilath draws 2 cards  up to their maximum hand size of 6
End of turn 5
HaircutPolice: 1 Æmber  (0 keys) Aselilath: 3 Æmber  (0 keys)
Turn 5
Key phase - HaircutPolice
HaircutPolice does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - HaircutPolice
HaircutPolice chooses brobnar  as their active house this turn
Main phase - HaircutPolice
HaircutPolice plays Tremor
HaircutPolice uses Tremor to stun Lilithal, Gargantodon, and Paraguardian
HaircutPolice plays Tremor
HaircutPolice uses Tremor to stun Brutodon Auxiliary, Lilithal, and Etaromme
HaircutPolice plays Barn Razing
HaircutPolice uses Barn Razing to cause their opponent to lose 1 Æmber  each time a friendly creature fights
HaircutPolice discards Power of Fire
Ready phase - HaircutPolice
HaircutPolice readies all of their cards 
Draw phase - HaircutPolice
HaircutPolice draws 4 cards  up to their maximum hand size of 6
End of turn 5
HaircutPolice: 1 Æmber  (0 keys) Aselilath: 3 Æmber  (0 keys)
Turn 6
Key phase - Aselilath
Aselilath does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - Aselilath
Aselilath chooses saurian  as their active house this turn
Main phase - Aselilath
Aselilath exhausts Paraguardian to remove its stun
Aselilath exhausts Gargantodon to remove its stun
Aselilath exhausts Brutodon Auxiliary to remove its stun
Aselilath plays Senator Shrix
Aselilath uses Senator Shrix to exalt Senator Shrix
Ready phase - Aselilath
Aselilath readies all of their cards 
Draw phase - Aselilath
Aselilath draws 1 cards  up to their maximum hand size of 6
End of turn 6
HaircutPolice: 1 Æmber  (0 keys) Aselilath: 3 Æmber  (0 keys)
Turn 6
Key phase - HaircutPolice
HaircutPolice does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - HaircutPolice
HaircutPolice chooses shadows  as their active house this turn
Main phase - HaircutPolice
HaircutPolice uses Umbra to make Umbra fight Lilithal
HaircutPolice uses Umbra to steal 1 Æmber  from Aselilath
Aselilath uses Gargantodon
HaircutPolice plays Hit and Run
HaircutPolice uses Hit and Run to deal 2 damage to Brutodon Auxiliary
HaircutPolice plays Chain Gang
HaircutPolice plays The Shadow Council
HaircutPolice plays Umbra
Ready phase - HaircutPolice
HaircutPolice readies all of their cards 
Draw phase - HaircutPolice
HaircutPolice draws 3 cards  up to their maximum hand size of 6
End of turn 6
HaircutPolice: 1 Æmber  (0 keys) Aselilath: 2 Æmber  (0 keys)
Turn 7
Key phase - Aselilath
Aselilath does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - Aselilath
Aselilath chooses staralliance  as their active house this turn
Main phase - Aselilath
Aselilath plays Force Field, gaining 1 Æmber  attaching it to Senator Shrix
Aselilath plays Transporter Platform, gaining 1 Æmber 
Ready phase - Aselilath
Aselilath readies all of their cards 
Draw phase - Aselilath
Aselilath draws 2 cards  up to their maximum hand size of 6
End of turn 7
HaircutPolice: 1 Æmber  (0 keys) Aselilath: 4 Æmber  (0 keys)
Turn 7
Key phase - HaircutPolice
HaircutPolice does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - HaircutPolice
HaircutPolice chooses staralliance  as their active house this turn
Main phase - HaircutPolice
HaircutPolice plays Transporter Platform, gaining 1 Æmber 
HaircutPolice plays Ingram’s Blaster, gaining 1 Æmber  attaching it to Sci. Officer Qincan
HaircutPolice plays Light of the Archons, gaining 1 Æmber  attaching it to Sci. Officer Qincan
HaircutPolice plays Zap, gaining 1 Æmber 
HaircutPolice uses Zap to deal 1 damage to a creature for each house represented among creatures in play
HaircutPolice uses Sci. Officer Qincan to reap with Sci. Officer Qincan
HaircutPolice uses Sci. Officer Qincan to deal 2 damage to Senator Shrix
HaircutPolice uses Ragwarg to deal 2 damage to Sci. Officer Qincan
HaircutPolice uses Sci. Officer Qincan to remove its ward token
Ready phase - HaircutPolice
HaircutPolice readies all of their cards 
Draw phase - HaircutPolice
HaircutPolice draws 4 cards  up to their maximum hand size of 6
 HaircutPolice declares Check!
End of turn 7
HaircutPolice: 7 Æmber  (0 keys) Aselilath: 4 Æmber  (0 keys)
Turn 8
Key phase - Aselilath
Aselilath does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - Aselilath
Aselilath chooses dis  as their active house this turn
Main phase - Aselilath
Aselilath discards Three Fates
Aselilath exhausts Etaromme to remove its stun
Aselilath plays Festering Touch, gaining 1 Æmber 
Aselilath uses Festering Touch to deal 1 damage to Umbra and Chain Gang
Aselilath uses Imperial Road to do several things
Aselilath plays Tricerian Legionary
Aselilath uses Tricerian Legionary to ward Brutodon Auxiliary
Ready phase - Aselilath
Aselilath readies all of their cards 
Draw phase - Aselilath
Aselilath draws 3 cards  up to their maximum hand size of 6
End of turn 8
HaircutPolice: 7 Æmber  (0 keys) Aselilath: 5 Æmber  (0 keys)
Turn 8
Key phase - HaircutPolice
HaircutPolice forges the red key  , paying 6 Æmber 
House phase - HaircutPolice
HaircutPolice chooses shadows  as their active house this turn
Main phase - HaircutPolice
HaircutPolice plays Subtle Chain, gaining 1 Æmber 
HaircutPolice uses Chain Gang to ready Chain Gang
HaircutPolice uses Subtle Chain to discard a card  at random from their hand
Aselilath discards Explo-rover at random
HaircutPolice plays Subtle Chain, gaining 1 Æmber 
HaircutPolice uses Chain Gang to ready Chain Gang
HaircutPolice uses Subtle Chain to discard a card  at random from their hand
Aselilath discards Sensor Chief Garcia at random
HaircutPolice
oh I am an idiot XD
Aselilath
xD
HaircutPolice uses Chain Gang to return Subtle Chain to their deck
Aselilath uses Gargantodon
Aselilath
Sealed is truly a punch in the eyes
HaircutPolice
yup
HaircutPolice uses Umbra to reap with Umbra
HaircutPolice uses Ragwarg to deal 2 damage to Umbra
HaircutPolice uses The Shadow Council to reap with The Shadow Council
Ready phase - HaircutPolice
HaircutPolice readies all of their cards 
Draw phase - HaircutPolice
HaircutPolice draws 2 cards  up to their maximum hand size of 6
End of turn 8
HaircutPolice: 5 Æmber  (1 key) Aselilath: 4 Æmber  (0 keys)
Turn 9
Key phase - Aselilath
Aselilath does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - Aselilath
Aselilath chooses saurian  as their active house this turn
Main phase - Aselilath
Aselilath plays City-State Interest
Aselilath uses City-State Interest to make each friendly creature capture 1 Æmber 
Aselilath exhausts Tricerian Legionary to remove its stun
Aselilath uses Brutodon Auxiliary to reap with Brutodon Auxiliary
HaircutPolice uses Ragwarg to deal 2 damage to Brutodon Auxiliary
Aselilath uses Brutodon Auxiliary to remove its ward token
Aselilath uses Gargantodon to reap with Gargantodon
Aselilath uses Paraguardian to reap with Paraguardian
Aselilath uses Paraguardian to exalt Paraguardian and ward its neighbors
Ready phase - Aselilath
Aselilath readies all of their cards 
Draw phase - Aselilath
Aselilath draws 3 cards  up to their maximum hand size of 6
 Aselilath declares Check!
End of turn 9
HaircutPolice: 0 Æmber  (1 key) Aselilath: 7 Æmber  (0 keys)
Turn 9
Key phase - HaircutPolice
HaircutPolice does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - HaircutPolice
HaircutPolice chooses shadows  as their active house this turn
Main phase - HaircutPolice
HaircutPolice uses Chain Gang to return Subtle Chain to their deck
Aselilath uses Gargantodon
HaircutPolice plays Subtle Chain, gaining 1 Æmber 
HaircutPolice uses Chain Gang to ready Chain Gang
HaircutPolice uses Subtle Chain to discard a card  at random from their hand
Aselilath discards Harbinger of Doom at random
HaircutPolice uses Chain Gang to reap with Chain Gang
HaircutPolice uses Ragwarg to deal 2 damage to Chain Gang
HaircutPolice plays Hidden Stash, gaining 1 Æmber 
HaircutPolice uses Hidden Stash to archive a card 
HaircutPolice uses The Shadow Council to reap with The Shadow Council
HaircutPolice plays Kymoor Eclipse
HaircutPolice uses Kymoor Eclipse to return Sci. Officer Qincan, The Shadow Council, Brutodon Auxiliary, and Tricerian Legionary to their deck
HaircutPolice is shuffling their deck
Aselilath is shuffling their deck
Ready phase - HaircutPolice
HaircutPolice readies all of their cards 
Draw phase - HaircutPolice
HaircutPolice draws 4 cards  up to their maximum hand size of 6
 HaircutPolice declares Check!
End of turn 9
HaircutPolice: 6 Æmber  (1 key) Aselilath: 10 Æmber  (0 keys)
Turn 10
Key phase - Aselilath
Aselilath forges the red key  , paying 6 Æmber 
House phase - Aselilath
Aselilath chooses dis  as their active house this turn
Main phase - Aselilath
Aselilath plays Infurnace
Aselilath uses Infurnace to purge Ingram’s Blaster and Subtle Chain
HaircutPolice
nooooo not my chain :D
Aselilath
x.x
Ready phase - Aselilath
Aselilath readies all of their cards 
Draw phase - Aselilath
Aselilath draws 2 cards  up to their maximum hand size of 6
End of turn 10
HaircutPolice: 4 Æmber  (1 key) Aselilath: 4 Æmber  (1 key)
Turn 10
Key phase - HaircutPolice
HaircutPolice does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - HaircutPolice
HaircutPolice chooses staralliance  as their active house this turn
HaircutPolice moves all the cards  in their archives to their hand
Main phase - HaircutPolice
HaircutPolice plays United Action
HaircutPolice uses United Action to allow them to play from any house ​for which they have a card  in play
HaircutPolice plays Sci. Officer Qincan
HaircutPolice plays Commander Chan
HaircutPolice plays Alaka
HaircutPolice plays Sköll
Ready phase - HaircutPolice
HaircutPolice readies all of their cards 
Draw phase - HaircutPolice
HaircutPolice draws 4 cards  up to their maximum hand size of 6
End of turn 10
HaircutPolice: 4 Æmber  (1 key) Aselilath: 4 Æmber  (1 key)
Turn 11
Key phase - Aselilath
Aselilath does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - Aselilath
Aselilath chooses staralliance  as their active house this turn
Main phase - Aselilath
Aselilath plays Quintrino Flux
Aselilath uses Quintrino Flux to destroy Commander Chan, Alaka, Infurnace, and Etaromme
Aselilath uses Etaromme to remove its ward token
Aselilath plays Armsmaster Molina
Aselilath plays Chief Engineer Walls
Aselilath uses Chief Engineer Walls to return Cloaking Dongle to their hand
Aselilath plays Cloaking Dongle, gaining 1 Æmber  attaching it to Gargantodon
Aselilath plays Tactical Officer Moon
Aselilath uses Tactical Officer Moon to rearrange creatures on a battleline
Aselilath uses Imperial Road to do several things
Aselilath plays Senator Shrix
Aselilath uses Senator Shrix to exalt Senator Shrix
Ready phase - Aselilath
Aselilath readies all of their cards 
Draw phase - Aselilath
Aselilath draws 5 cards  up to their maximum hand size of 6
 Aselilath declares Check!
End of turn 11
HaircutPolice: 5 Æmber  (1 key) Aselilath: 5 Æmber  (1 key)
Turn 11
Key phase - HaircutPolice
HaircutPolice does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - HaircutPolice
HaircutPolice chooses shadows  as their active house this turn
HaircutPolice uses Sci. Officer Qincan to steal 1 Æmber  from Aselilath
Aselilath uses Gargantodon
Main phase - HaircutPolice
HaircutPolice plays Subtle Chain, gaining 1 Æmber 
HaircutPolice uses Subtle Chain to discard a card  at random from their hand
Aselilath discards First Officer Frane at random
HaircutPolice plays Mug, gaining 1 Æmber 
HaircutPolice uses Mug to move 1 Æmber  from Senator Shrix to their pool and deal 2 damage to it
HaircutPolice plays The Shadow Council
HaircutPolice plays Ronnie Wristclocks
HaircutPolice uses Ronnie Wristclocks to steal 1 Æmber  from Aselilath
Aselilath uses Gargantodon
Ready phase - HaircutPolice
HaircutPolice readies all of their cards 
Draw phase - HaircutPolice
HaircutPolice draws 4 cards  up to their maximum hand size of 6
HaircutPolice's deck has run out of cards, so they shuffle
HaircutPolice is shuffling their deck
 HaircutPolice declares Check!
End of turn 11
HaircutPolice: 8 Æmber  (1 key) Aselilath: 3 Æmber  (1 key)
Turn 12
Key phase - Aselilath
Aselilath does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - Aselilath
Aselilath chooses dis  as their active house this turn
HaircutPolice uses Sci. Officer Qincan to steal 1 Æmber  from Aselilath
Aselilath uses Gargantodon
Main phase - Aselilath
Aselilath plays The Evil Eye, gaining 1 Æmber 
Aselilath uses The Evil Eye to increase HaircutPolice's key cost by 3 until the end of their next turn
Aselilath plays Harvest Time
Aselilath uses Harvest Time to purge all cards  with the elf trait and each player gains Æmber  equal to the number of their cards  purged
HaircutPolice
nice
Aselilath uses Imperial Road to do several things
Aselilath plays Tricerian Legionary
Aselilath uses Tricerian Legionary to ward Senator Shrix
Ready phase - Aselilath
Aselilath readies all of their cards 
Draw phase - Aselilath
Aselilath draws 4 cards  up to their maximum hand size of 6
End of turn 12
HaircutPolice: 10 Æmber  (1 key) Aselilath: 4 Æmber  (1 key)
Turn 12
Key phase - HaircutPolice
HaircutPolice forges the blue key  , paying 9 Æmber 
House phase - HaircutPolice
Aselilath
This deck has cards  that i've never seen before
Aselilath
Sheehs
HaircutPolice chooses brobnar  as their active house this turn
Main phase - HaircutPolice
HaircutPolice uses Sköll to make Sköll fight Chief Engineer Walls
HaircutPolice uses Sköll to deal 3 damage to Chief Engineer Walls
HaircutPolice uses Sköll to place 1 +1 power counter on Sci. Officer Qincan
HaircutPolice plays Alaka
HaircutPolice
it's not ready?
HaircutPolice
it should be, right?
Aselilath
Yeah
Aselilath
Pretty strange
HaircutPolice
hmm
HaircutPolice
I'll remember to report that later
HaircutPolice plays Shorty
Aselilath
Sometimes it just gets bugged
HaircutPolice plays Ganger Chieftain
HaircutPolice uses Ganger Chieftain to ready and fight with a neighboring creature
HaircutPolice uses Shorty to make Shorty fight Armsmaster Molina
HaircutPolice uses Shorty to deal 4 damage to Armsmaster Molina
Ready phase - HaircutPolice
HaircutPolice readies all of their cards 
Draw phase - HaircutPolice
HaircutPolice draws 3 cards  up to their maximum hand size of 6
End of turn 12
HaircutPolice: 1 Æmber  (2 keys) Aselilath: 4 Æmber  (1 key)
Turn 13
Key phase - Aselilath
Aselilath does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - Aselilath
Aselilath chooses saurian  as their active house this turn
Main phase - Aselilath
Aselilath uses Gargantodon to reap with Gargantodon
HaircutPolice uses Ragwarg to deal 2 damage to Gargantodon
Aselilath uses Gargantodon to remove its ward token
Aselilath uses Paraguardian to reap with Paraguardian
Aselilath uses Paraguardian to exalt Paraguardian and ward its neighbors
Aselilath exhausts Tricerian Legionary to remove its stun
Aselilath exhausts Senator Shrix to remove its stun
Aselilath plays Senator Shrix
Aselilath uses Senator Shrix to exalt Senator Shrix
Aselilath plays Questor Jarta
Aselilath plays Brutodon Auxiliary
Aselilath plays Legatus Raptor
Ready phase - Aselilath
Aselilath readies all of their cards 
Draw phase - Aselilath
Aselilath draws 4 cards  up to their maximum hand size of 6
Aselilath's deck has run out of cards, so they shuffle
Aselilath is shuffling their deck
 Aselilath declares Check!
End of turn 13
HaircutPolice: 1 Æmber  (2 keys) Aselilath: 6 Æmber  (1 key)
Turn 13
Key phase - HaircutPolice
HaircutPolice does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - HaircutPolice
HaircutPolice chooses staralliance  as their active house this turn
Main phase - HaircutPolice
HaircutPolice plays CALV-1N, attaching it to Sci. Officer Qincan
HaircutPolice plays Light of the Archons, gaining 1 Æmber  attaching it to Sci. Officer Qincan
HaircutPolice discards United Action
HaircutPolice plays Medic Ingram
HaircutPolice uses Medic Ingram to heal 3 damage and ward Sci. Officer Qincan
HaircutPolice uses Sci. Officer Qincan to reap with Sci. Officer Qincan
HaircutPolice uses Sci. Officer Qincan to draw 1 cards 
HaircutPolice uses Ragwarg to deal 2 damage to Sci. Officer Qincan
HaircutPolice uses Sci. Officer Qincan to remove its ward token
HaircutPolice plays Commander Chan
HaircutPolice uses Transporter Platform to return CALV-1N, Light of the Archons, and Sci. Officer Qincan to their hand
HaircutPolice plays Sci. Officer Qincan
HaircutPolice plays Light of the Archons, gaining 1 Æmber  attaching it to Medic Ingram
HaircutPolice plays CALV-1N, attaching it to Medic Ingram
Ready phase - HaircutPolice
HaircutPolice readies all of their cards 
Draw phase - HaircutPolice
HaircutPolice draws 4 cards  up to their maximum hand size of 6
End of turn 13
HaircutPolice: 4 Æmber  (2 keys) Aselilath: 7 Æmber  (1 key)
Turn 14
Key phase - Aselilath
Aselilath forges the yellow key  , paying 4 Æmber 
House phase - Aselilath
Aselilath chooses saurian  as their active house this turn
Main phase - Aselilath
Aselilath uses Gargantodon to reap with Gargantodon
HaircutPolice uses Ragwarg to deal 2 damage to Gargantodon
Aselilath uses Gargantodon to remove its ward token
Aselilath uses Paraguardian to reap with Paraguardian
Aselilath uses Paraguardian to exalt Paraguardian and ward its neighbors
Aselilath uses Senator Shrix to reap with Senator Shrix
Aselilath uses Senator Shrix to exalt Senator Shrix
Aselilath uses Tricerian Legionary to reap with Tricerian Legionary
Aselilath uses Senator Shrix to reap with Senator Shrix
Aselilath uses Senator Shrix to exalt Senator Shrix
Aselilath uses Questor Jarta to reap with Questor Jarta
Aselilath uses Questor Jarta to exalt Questor Jarta and gain 1 Æmber 
Aselilath uses Brutodon Auxiliary to reap with Brutodon Auxiliary
Aselilath uses Legatus Raptor to reap with Legatus Raptor
Ready phase - Aselilath
Aselilath readies all of their cards 
Draw phase - Aselilath
 Aselilath declares Check!
End of turn 14
HaircutPolice: 4 Æmber  (2 keys) Aselilath: 12 Æmber  (2 keys)
Turn 14
Key phase - HaircutPolice
HaircutPolice does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - HaircutPolice
HaircutPolice chooses brobnar  as their active house this turn
Main phase - HaircutPolice
HaircutPolice plays Barn Razing
HaircutPolice uses Barn Razing to cause their opponent to lose 1 Æmber  each time a friendly creature fights
HaircutPolice uses Shorty to make Shorty fight Tricerian Legionary
HaircutPolice uses Shorty to deal 4 damage to Tricerian Legionary
loses 1 Æmber  due to Barn Razing's effect
HaircutPolice uses Ganger Chieftain to make Ganger Chieftain fight Senator Shrix
Aselilath uses Senator Shrix to remove its ward token
loses 1 Æmber  due to Barn Razing's effect
HaircutPolice uses Alaka to make Alaka fight Senator Shrix
loses 1 Æmber  due to Barn Razing's effect
HaircutPolice uses Sköll to make Sköll fight Paraguardian
HaircutPolice uses Sköll to deal 3 damage to Paraguardian
loses 1 Æmber  due to Barn Razing's effect
HaircutPolice plays Tremor
HaircutPolice uses Tremor to stun Paraguardian, Tactical Officer Moon, and Gargantodon
HaircutPolice plays Tremor
HaircutPolice uses Tremor to stun Legatus Raptor, Questor Jarta, and Brutodon Auxiliary
HaircutPolice
you win
HaircutPolice
good game
Aselilath
gg man
 Aselilath has disconnected. The game will wait up to 30 seconds for them to reconnect

**Comment by HaircutPolice** [comment]
![Capture2](https://user-images.githubusercontent.com/61554217/75463582-ec644600-597d-11ea-8b51-04e63a4acccd.PNG)
![Capture1](https://user-images.githubusercontent.com/61554217/75463594-eec6a000-597d-11ea-822a-5e0cc0105027.PNG)

**Comment by jtrussell** [comment]
Looks like this is bug in how we're determining if a creature fought this turn. We're setting `context.player.creatureFought = true` in the [ResolveFightAction](https://github.com/keyteki/keyteki/blob/master/server/game/GameActions/ResolveFightAction.js#L76). 
But that won't fire if the defender is killed in the `BeforeFight` (either by a `BeforeFight: ...` ability or something like assault).

Before fight abilities, and assault damage, are both included in using a creature to fight. We should probably be marking the player as having used a creature to fight when they initiate the fight, rather than when all the steps complete successfully.
