### ISSUE TITLE
Overrun incorrectly caused loss of aember

### ISSUE THREAD

**Issue by ACinJC** [keyteki/keyteki#1149]
Please see this game: https://www.thecrucibletracker.com/games/28c40ab0-599f-11ea-a293-919cc2ac4874

On AcidicSkull's Turn 31, he played Ballcano to kill my Grabber Jammer. He followed with Overrun, which should not have made me lose two Aember, because only one of my creatures was killed (Overrun requires three). 

Fortunately, opponent was a good sport and allowed manual mode because of the bug to give me the win.

**Comment by UltraUltraUltra** [comment]
Just to confirm Overrun is still not working correctly.  I didn't destroy any of my opponent's creatures but my opponent still lost 2 aember.

![image](https://user-images.githubusercontent.com/55008319/87324988-ca342480-c528-11ea-8060-50c8831db1ef.png)

**Comment by hydrophilic-attack** [comment]
Yeah this happened to me in two sealed games recently as well
