### ISSUE TITLE
United Action (Owning cards problems) 

### ISSUE THREAD

**Issue by Kittiwatt** [keyteki/keyteki#1150]
I had the issue this morning. 
If i'm right my problem is an owning card problem that can affect other effets of the game.

For now **United Action** doesn't take into account the cards that the active player owns but that are not on his side of the board. Exemple I play **United Action** (alpha) with no creatures and no artefact on board but if have two upgrades placed on my opponents creatures. I should in theory be able to play cards from the upgrade's houses this turn. That doesn't work in the curent version of TCO. 

Thx for your work

Axel

**Comment by romanogit** [comment]
PR submitted
