### ISSUE TITLE
Ganger Chieftans

### ISSUE THREAD

**Issue by Warfare13** [keyteki/keyteki#1154]
Hi,

I had this situation when playing 2 Ganger Chieftains after each other when a Logos Foggify was played the turn before.
The first chieftain readied the adjacent brobnar creature and i could only reap, all fine
The second chieftain was played next to the first but it forced me to fight with the first chieftain instead of just reading and allowing me to reap with it

**Comment by Achocholacek** [comment]
I can't recreate this issue. I have updated test coverage to reflect this situation and everything passes.

If this happens again, please let us know.

**Comment by romanogit** [comment]
Closing
