### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by Tilbo** [keyteki/keyteki#1156]
A lot of users in chat have been saying they're getting kicked from games, server issues, d/c'd etc etc. 
Not sure if this will help Cyrogen or the bods but should we start putting screenshots of game with date/times and all that stuff here?

![image](https://user-images.githubusercontent.com/53436024/76315878-780c9980-62d1-11ea-9851-edc17678ef2c.png)

**Comment by cryogen** [comment]
What would really help is:

- Noting what happens when you get disconnected, does the signal bar at the top go red and stay red? does it go to blue and stay blue? or does it go from red to blue to green?
- Press f12 (or open the developer tools of your browser) and copy/paste any error messages noted there
- While you're experiencing the issue, run this command in a console prompt: "ping -n 50 thecrucible.online" and copy/paste the summary of that when it finishes

**Comment by ModestOrange** [comment]
JQMIGRATE: Migrate is installed with logging active, version 3.0.0
api/account/checkauth:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
bundle.js:1 Loading Crucible Tracker v0.0.39
:1 Unchecked runtime.lastError: The message port closed before a response was received.
staralliance.png:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
api/decks?_=1583875657159:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
bundle.js:1 Game format is archon
breadcrumbs.js:58 Connected to socket
breadcrumbs.js:58 Looking for archon
breadcrumbs.js:58 Player data Array(2)
breadcrumbs.js:58 Looking for cards in hand
bundle.js:1 Hand: Array(7)
breadcrumbs.js:58 Looking for cards in hand
img/cards/exhume.png:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
img/cards/triumph.png:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
daughter.png:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
img/cards/brutodon-auxiliary.png:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
odoac-the-patrician.png:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
img/cards/brutodon-auxiliary.png:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
odoac-the-patrician.png:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
websocket.js:242 WebSocket connection to 'wss://thecrucible.online/node2/socket.io/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTExZjA1NWNmYzc4NWZlMjY5NTE4MjQiLCJ1c2VybmFtZSI6Ik1vZGVzdE9yYW5nZSIsImVtYWlsIjoibW9kZXN0b3JhbmdlQGhvdG1haWwuY29tIiwic2V0dGluZ3MiOnsiZGlzYWJsZUdyYXZhdGFyIjpmYWxzZSwiY2FyZFNpemUiOiJ4LWxhcmdlIiwiYmFja2dyb3VuZCI6IlN0YXIgQWxsaWFuY2UiLCJvcHRpb25TZXR0aW5ncyI6eyJtYXJrQ2FyZHNVbnNlbGVjdGFibGUiOnRydWUsImNhbmNlbE93bkFiaWxpdGllcyI6ZmFsc2UsIm9yZGVyRm9yY2VkQWJpbGl0aWVzIjp0cnVlLCJjb25maXJtT25lQ2xpY2siOnRydWUsInNob3dTdGF0dXNJblNpZGViYXIiOmZhbHNlfX0sInByb21wdGVkQWN0aW9uV2luZG93cyI6bnVsbCwicGVybWlzc2lvbnMiOnt9LCJ2ZXJpZmllZCI6dHJ1ZSwiZW5hYmxlR3JhdmF0YXIiOmZhbHNlLCJibG9ja0xpc3QiOltdLCJpYXQiOjE1ODM4NzU3NTIsImV4cCI6MTU4Mzg3NjA1Mn0.UOcbvzAKPjnRxUt16oqShOBzbpn2EHJRu7G_lzaWGpw&EIO=3&transport=websocket&sid=hnWUEeCOGdNCiOjcAI9_' failed: WebSocket is closed before the connection is established.
CIKq.f.doClose @ websocket.js:242

**Comment by granttitus** [comment]
Me and some friends in the U.S. have been experiencing D/Cs where you remain in the game, but nothing happens because your connection to the gamenode socket has been closed. I believe what happens is the [30,000ms heartbeat timeout](https://github.com/keyteki/keyteki/blob/41a4698f819563e8efe38605954ebc6b65be9909/server/gamenode/gameserver.js#L63) is exceeded and the gamenode closes your connection. I reconnect to the game by clearing the site's cookies and logging back in.
 
In my last game I listened to the heartbeat event and found it almost exceeded the 30,000ms limit a couple times.

**Code**
```
let time = new Date();
socket.io.engine.on('heartbeat', () => {
  console.log('heartbeat (ms):', new Date() - time);
  time = new Date();
});
```

**Log**
```
heartbeat (ms): 400
heartbeat (ms): 1019
heartbeat (ms): 2844
heartbeat (ms): 6660
heartbeat (ms): 119
heartbeat (ms): 1357
heartbeat (ms): 917
heartbeat (ms): 9978
heartbeat (ms): 3258
heartbeat (ms): 1070
heartbeat (ms): 20796
heartbeat (ms): 3144
heartbeat (ms): 3070
heartbeat (ms): 1572
heartbeat (ms): 5247
heartbeat (ms): 1522
heartbeat (ms): 2607
heartbeat (ms): 2432
heartbeat (ms): 1757
heartbeat (ms): 702
heartbeat (ms): 398
heartbeat (ms): 884
heartbeat (ms): 648
heartbeat (ms): 473
heartbeat (ms): 627
heartbeat (ms): 17
heartbeat (ms): 246
heartbeat (ms): 24884
heartbeat (ms): 11251
heartbeat (ms): 3477
heartbeat (ms): 1226
heartbeat (ms): 2049
heartbeat (ms): 1636
heartbeat (ms): 1330
heartbeat (ms): 3683
heartbeat (ms): 1053
heartbeat (ms): 17875
heartbeat (ms): 1234
heartbeat (ms): 683
heartbeat (ms): 542
heartbeat (ms): 463
heartbeat (ms): 857
heartbeat (ms): 492
heartbeat (ms): 1090
heartbeat (ms): 1842
heartbeat (ms): 22
heartbeat (ms): 518
heartbeat (ms): 24601
heartbeat (ms): 13413
heartbeat (ms): 12628
heartbeat (ms): 401
heartbeat (ms): 1543
heartbeat (ms): 1686
heartbeat (ms): 4260
heartbeat (ms): 12293
heartbeat (ms): 1574
heartbeat (ms): 877
heartbeat (ms): 1141
heartbeat (ms): 380
heartbeat (ms): 949
heartbeat (ms): 146
heartbeat (ms): 14241
heartbeat (ms): 1603
heartbeat (ms): 1507
heartbeat (ms): 1698
heartbeat (ms): 6296
heartbeat (ms): 1468
heartbeat (ms): 3152
heartbeat (ms): 4140
heartbeat (ms): 16358
heartbeat (ms): 25127
heartbeat (ms): 22816
heartbeat (ms): 1838
heartbeat (ms): 463
heartbeat (ms): 2302
heartbeat (ms): 8034
heartbeat (ms): 4530
heartbeat (ms): 1134
heartbeat (ms): 915
heartbeat (ms): 574
heartbeat (ms): 1979
heartbeat (ms): 689
heartbeat (ms): 641
heartbeat (ms): 614
heartbeat (ms): 275
heartbeat (ms): 3428
heartbeat (ms): 10142
heartbeat (ms): 3577
heartbeat (ms): 11402
heartbeat (ms): 5263
heartbeat (ms): 5463
heartbeat (ms): 2173
heartbeat (ms): 1942
heartbeat (ms): 2034
heartbeat (ms): 2967
heartbeat (ms): 2144
heartbeat (ms): 1840
heartbeat (ms): 1614
heartbeat (ms): 4631
heartbeat (ms): 1379
heartbeat (ms): 18882
heartbeat (ms): 218
heartbeat (ms): 477
heartbeat (ms): 863
heartbeat (ms): 899
heartbeat (ms): 959
heartbeat (ms): 647
heartbeat (ms): 2904
heartbeat (ms): 343
heartbeat (ms): 1121
heartbeat (ms): 743
heartbeat (ms): 2638
heartbeat (ms): 13513
heartbeat (ms): 8121
heartbeat (ms): 10676
heartbeat (ms): 6851
heartbeat (ms): 2914
heartbeat (ms): 15615
heartbeat (ms): 4636
heartbeat (ms): 1942
heartbeat (ms): 11429
heartbeat (ms): 1534
2heartbeat (ms): 1228
heartbeat (ms): 8497
heartbeat (ms): 1840
heartbeat (ms): 112
heartbeat (ms): 1114
heartbeat (ms): 4503
heartbeat (ms): 5078
heartbeat (ms): 2537
heartbeat (ms): 594
heartbeat (ms): 970
heartbeat (ms): 1020
heartbeat (ms): 427
heartbeat (ms): 672
heartbeat (ms): 583
heartbeat (ms): 741
heartbeat (ms): 244
heartbeat (ms): 5240
heartbeat (ms): 1372
heartbeat (ms): 24845
heartbeat (ms): 266
heartbeat (ms): 1153
heartbeat (ms): 2250
heartbeat (ms): 3073
heartbeat (ms): 14184
heartbeat (ms): 5651
heartbeat (ms): 14
heartbeat (ms): 3708
img/cards/sloppy-labwork.png:1 GET https://thecrucible.online/img/cards/sloppy-labwork.png net::ERR_CERT_DATE_INVALID
Image (async)
vt @ react-dom.production.min.js:55
(anonymous) @ react-dom.production.min.js:112
ga @ react-dom.production.min.js:209
Ha @ react-dom.production.min.js:214
Ba @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Es @ react-dom.production.min.js:250
Ds @ react-dom.production.min.js:249
Ss @ react-dom.production.min.js:248
Ms @ react-dom.production.min.js:245
Qa @ react-dom.production.min.js:243
enqueueSetState @ react-dom.production.min.js:130
w.setState @ react.production.min.js:13
i.handleChange @ connect.js:302
f @ createStore.js:172
(anonymous) @ configureStore.prod.js:18
(anonymous) @ api-middleware.js:15
c @ runtime.js:45
(anonymous) @ runtime.js:271
e.<computed> @ runtime.js:97
re @ index.js:14
s @ api-middleware.js:5
(anonymous) @ api-middleware.js:5
r @ api-middleware.js:5
(anonymous) @ api-middleware.js:5
(anonymous) @ index.js:11
dispatch @ applyMiddleware.js:35
(anonymous) @ game.js:30
(anonymous) @ index.js:8
dispatch @ applyMiddleware.js:35
(anonymous) @ game.js:148
r.emit @ index.js:133
KFGy.p.onevent @ socket.js:278
KFGy.p.onpacket @ socket.js:240
(anonymous) @ index.js:21
r.emit @ index.js:133
p.ondecoded @ manager.js:345
(anonymous) @ index.js:21
r.emit @ index.js:133
Vo14.d.add @ index.js:251
p.ondata @ manager.js:335
(anonymous) @ index.js:21
r.emit @ index.js:133
l.onPacket @ socket.js:459
(anonymous) @ socket.js:276
r.emit @ index.js:133
Gbct.i.onPacket @ transport.js:148
Gbct.i.onData @ transport.js:140
ws.onmessage @ websocket.js:154
Show 20 more frames
ghostly-hand.png:1 GET https://thecrucible.online/img/cards/ghostly-hand.png net::ERR_CERT_DATE_INVALID
Image (async)
vt @ react-dom.production.min.js:55
(anonymous) @ react-dom.production.min.js:112
ga @ react-dom.production.min.js:209
Ha @ react-dom.production.min.js:214
Ba @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Es @ react-dom.production.min.js:250
Ds @ react-dom.production.min.js:249
Ss @ react-dom.production.min.js:248
Ps @ react-dom.production.min.js:251
Sn @ react-dom.production.min.js:85
r @ helpers.js:74
heartbeat (ms): 21404
heartbeat (ms): 9561
heartbeat (ms): 2122
heartbeat (ms): 1842
heartbeat (ms): 2501
heartbeat (ms): 9083
heartbeat (ms): 20624
heartbeat (ms): 1081
heartbeat (ms): 1430
heartbeat (ms): 1978
heartbeat (ms): 1172
heartbeat (ms): 1154
heartbeat (ms): 1893
heartbeat (ms): 1748
heartbeat (ms): 1972
heartbeat (ms): 905
heartbeat (ms): 855
heartbeat (ms): 1076
heartbeat (ms): 364
heartbeat (ms): 1460
heartbeat (ms): 12504
heartbeat (ms): 25125
heartbeat (ms): 16528
heartbeat (ms): 3395
heartbeat (ms): 444
heartbeat (ms): 1288
heartbeat (ms): 1228
heartbeat (ms): 1195
heartbeat (ms): 1024
heartbeat (ms): 687
heartbeat (ms): 5575
heartbeat (ms): 2996
heartbeat (ms): 6755
heartbeat (ms): 9732
shaffles.png:1 GET https://thecrucible.online/img/cards/shaffles.png net::ERR_CERT_DATE_INVALID
Image (async)
vt @ react-dom.production.min.js:55
(anonymous) @ react-dom.production.min.js:112
ga @ react-dom.production.min.js:209
Ha @ react-dom.production.min.js:214
Ba @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Es @ react-dom.production.min.js:250
Ds @ react-dom.production.min.js:249
Ss @ react-dom.production.min.js:248
Ps @ react-dom.production.min.js:251
Sn @ react-dom.production.min.js:85
r @ helpers.js:74
heartbeat (ms): 25119
heartbeat (ms): 16521
heartbeat (ms): 1755
heartbeat (ms): 1012
heartbeat (ms): 3869
heartbeat (ms): 630
9[Violation] Forced reflow while executing JavaScript took <N>ms
heartbeat (ms): 1163
heartbeat (ms): 192
heartbeat (ms): 959
heartbeat (ms): 895
heartbeat (ms): 1759
heartbeat (ms): 785
heartbeat (ms): 2594
heartbeat (ms): 912
heartbeat (ms): 2015
heartbeat (ms): 582
heartbeat (ms): 1045
heartbeat (ms): 603
heartbeat (ms): 889
heartbeat (ms): 1504
heartbeat (ms): 3909
heartbeat (ms): 1729
heartbeat (ms): 869
heartbeat (ms): 1149
heartbeat (ms): 1001
heartbeat (ms): 1191
batdrone.png:1 GET https://thecrucible.online/img/cards/batdrone.png net::ERR_CERT_DATE_INVALID
Image (async)
vt @ react-dom.production.min.js:55
(anonymous) @ react-dom.production.min.js:112
ga @ react-dom.production.min.js:209
Ha @ react-dom.production.min.js:214
Ba @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Es @ react-dom.production.min.js:250
Ds @ react-dom.production.min.js:249
Ss @ react-dom.production.min.js:248
Ms @ react-dom.production.min.js:245
Qa @ react-dom.production.min.js:243
enqueueSetState @ react-dom.production.min.js:130
w.setState @ react.production.min.js:13
i.handleChange @ connect.js:302
f @ createStore.js:172
(anonymous) @ configureStore.prod.js:18
(anonymous) @ api-middleware.js:15
c @ runtime.js:45
(anonymous) @ runtime.js:271
e.<computed> @ runtime.js:97
re @ index.js:14
s @ api-middleware.js:5
(anonymous) @ api-middleware.js:5
r @ api-middleware.js:5
(anonymous) @ api-middleware.js:5
(anonymous) @ index.js:11
dispatch @ applyMiddleware.js:35
(anonymous) @ game.js:30
(anonymous) @ index.js:8
dispatch @ applyMiddleware.js:35
(anonymous) @ game.js:148
r.emit @ index.js:133
KFGy.p.onevent @ socket.js:278
KFGy.p.onpacket @ socket.js:240
(anonymous) @ index.js:21
r.emit @ index.js:133
p.ondecoded @ manager.js:345
(anonymous) @ index.js:21
r.emit @ index.js:133
Vo14.d.add @ index.js:251
p.ondata @ manager.js:335
(anonymous) @ index.js:21
r.emit @ index.js:133
l.onPacket @ socket.js:459
(anonymous) @ socket.js:276
r.emit @ index.js:133
Gbct.i.onPacket @ transport.js:148
Gbct.i.onData @ transport.js:140
ws.onmessage @ websocket.js:154
Show 20 more frames
heartbeat (ms): 686
heartbeat (ms): 21333
heartbeat (ms): 3360
heartbeat (ms): 844
heartbeat (ms): 1350
heartbeat (ms): 1928
heartbeat (ms): 2852
heartbeat (ms): 1844
heartbeat (ms): 2043
heartbeat (ms): 15094
heartbeat (ms): 692
heartbeat (ms): 1199
pandemonium.png:1 GET https://thecrucible.online/img/cards/pandemonium.png net::ERR_CERT_DATE_INVALID
Image (async)
vt @ react-dom.production.min.js:55
(anonymous) @ react-dom.production.min.js:112
ga @ react-dom.production.min.js:209
Ha @ react-dom.production.min.js:214
Ba @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Es @ react-dom.production.min.js:250
Ds @ react-dom.production.min.js:249
Ss @ react-dom.production.min.js:248
Ms @ react-dom.production.min.js:245
Qa @ react-dom.production.min.js:243
enqueueSetState @ react-dom.production.min.js:130
w.setState @ react.production.min.js:13
i.handleChange @ connect.js:302
f @ createStore.js:172
(anonymous) @ configureStore.prod.js:18
(anonymous) @ api-middleware.js:15
c @ runtime.js:45
(anonymous) @ runtime.js:271
e.<computed> @ runtime.js:97
re @ index.js:14
s @ api-middleware.js:5
(anonymous) @ api-middleware.js:5
r @ api-middleware.js:5
(anonymous) @ api-middleware.js:5
(anonymous) @ index.js:11
dispatch @ applyMiddleware.js:35
(anonymous) @ game.js:30
(anonymous) @ index.js:8
dispatch @ applyMiddleware.js:35
(anonymous) @ game.js:148
r.emit @ index.js:133
KFGy.p.onevent @ socket.js:278
KFGy.p.onpacket @ socket.js:240
(anonymous) @ index.js:21
r.emit @ index.js:133
p.ondecoded @ manager.js:345
(anonymous) @ index.js:21
r.emit @ index.js:133
Vo14.d.add @ index.js:251
p.ondata @ manager.js:335
(anonymous) @ index.js:21
r.emit @ index.js:133
l.onPacket @ socket.js:459
(anonymous) @ socket.js:276
r.emit @ index.js:133
Gbct.i.onPacket @ transport.js:148
Gbct.i.onData @ transport.js:140
ws.onmessage @ websocket.js:154
Show 20 more frames
heartbeat (ms): 5380
heartbeat (ms): 673
heartbeat (ms): 1016
heartbeat (ms): 768
heartbeat (ms): 741
pandemonium.png:1 GET https://thecrucible.online/img/cards/pandemonium.png net::ERR_CERT_DATE_INVALID
Image (async)
vt @ react-dom.production.min.js:55
(anonymous) @ react-dom.production.min.js:112
ga @ react-dom.production.min.js:209
Ha @ react-dom.production.min.js:214
Ba @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Es @ react-dom.production.min.js:250
Ds @ react-dom.production.min.js:249
Ss @ react-dom.production.min.js:248
Cs @ react-dom.production.min.js:250
Re @ react-dom.production.min.js:39
On @ react-dom.production.min.js:86
r @ helpers.js:74
heartbeat (ms): 2618
heartbeat (ms): 1162
heartbeat (ms): 252
heartbeat (ms): 269
heartbeat (ms): 282
heartbeat (ms): 445
heartbeat (ms): 553
heartbeat (ms): 772
heartbeat (ms): 815
heartbeat (ms): 2967
heartbeat (ms): 379
heartbeat (ms): 850
heartbeat (ms): 370
heartbeat (ms): 2881
heartbeat (ms): 25122
```

From the same game
```
$ ping -c 50 thecrucible.online | pbcopy
PING thecrucible.online (46.235.227.53): 56 data bytes
64 bytes from 46.235.227.53: icmp_seq=0 ttl=52 time=123.601 ms
64 bytes from 46.235.227.53: icmp_seq=1 ttl=52 time=118.297 ms
64 bytes from 46.235.227.53: icmp_seq=2 ttl=52 time=119.169 ms
64 bytes from 46.235.227.53: icmp_seq=3 ttl=52 time=119.806 ms
64 bytes from 46.235.227.53: icmp_seq=4 ttl=52 time=120.157 ms
64 bytes from 46.235.227.53: icmp_seq=5 ttl=52 time=119.655 ms
64 bytes from 46.235.227.53: icmp_seq=6 ttl=52 time=121.786 ms
64 bytes from 46.235.227.53: icmp_seq=7 ttl=52 time=119.372 ms
64 bytes from 46.235.227.53: icmp_seq=8 ttl=52 time=126.162 ms
64 bytes from 46.235.227.53: icmp_seq=9 ttl=52 time=126.980 ms
64 bytes from 46.235.227.53: icmp_seq=10 ttl=52 time=191.469 ms
64 bytes from 46.235.227.53: icmp_seq=11 ttl=52 time=120.474 ms
64 bytes from 46.235.227.53: icmp_seq=12 ttl=52 time=130.187 ms
64 bytes from 46.235.227.53: icmp_seq=13 ttl=52 time=122.012 ms
64 bytes from 46.235.227.53: icmp_seq=14 ttl=52 time=121.926 ms
64 bytes from 46.235.227.53: icmp_seq=15 ttl=52 time=120.140 ms
64 bytes from 46.235.227.53: icmp_seq=16 ttl=52 time=121.955 ms
64 bytes from 46.235.227.53: icmp_seq=17 ttl=52 time=127.516 ms
64 bytes from 46.235.227.53: icmp_seq=18 ttl=52 time=120.092 ms
64 bytes from 46.235.227.53: icmp_seq=19 ttl=52 time=129.117 ms
64 bytes from 46.235.227.53: icmp_seq=20 ttl=52 time=125.064 ms
64 bytes from 46.235.227.53: icmp_seq=21 ttl=52 time=125.121 ms
64 bytes from 46.235.227.53: icmp_seq=22 ttl=52 time=125.531 ms
64 bytes from 46.235.227.53: icmp_seq=23 ttl=52 time=120.924 ms
64 bytes from 46.235.227.53: icmp_seq=24 ttl=52 time=118.636 ms
64 bytes from 46.235.227.53: icmp_seq=25 ttl=52 time=120.192 ms
64 bytes from 46.235.227.53: icmp_seq=26 ttl=52 time=125.656 ms
64 bytes from 46.235.227.53: icmp_seq=27 ttl=52 time=124.703 ms
64 bytes from 46.235.227.53: icmp_seq=28 ttl=52 time=119.822 ms
64 bytes from 46.235.227.53: icmp_seq=29 ttl=52 time=126.501 ms
64 bytes from 46.235.227.53: icmp_seq=30 ttl=52 time=121.256 ms
64 bytes from 46.235.227.53: icmp_seq=31 ttl=52 time=120.080 ms
64 bytes from 46.235.227.53: icmp_seq=32 ttl=52 time=124.090 ms
64 bytes from 46.235.227.53: icmp_seq=33 ttl=52 time=149.854 ms
64 bytes from 46.235.227.53: icmp_seq=34 ttl=52 time=137.911 ms
64 bytes from 46.235.227.53: icmp_seq=35 ttl=52 time=128.938 ms
64 bytes from 46.235.227.53: icmp_seq=36 ttl=52 time=122.807 ms
64 bytes from 46.235.227.53: icmp_seq=37 ttl=52 time=142.010 ms
64 bytes from 46.235.227.53: icmp_seq=38 ttl=52 time=134.015 ms
64 bytes from 46.235.227.53: icmp_seq=39 ttl=52 time=129.279 ms
64 bytes from 46.235.227.53: icmp_seq=40 ttl=52 time=124.848 ms
64 bytes from 46.235.227.53: icmp_seq=41 ttl=52 time=122.469 ms
64 bytes from 46.235.227.53: icmp_seq=42 ttl=52 time=149.248 ms
64 bytes from 46.235.227.53: icmp_seq=43 ttl=52 time=140.009 ms
64 bytes from 46.235.227.53: icmp_seq=44 ttl=52 time=139.058 ms
64 bytes from 46.235.227.53: icmp_seq=45 ttl=52 time=123.677 ms
64 bytes from 46.235.227.53: icmp_seq=46 ttl=52 time=169.844 ms
64 bytes from 46.235.227.53: icmp_seq=47 ttl=52 time=149.886 ms
64 bytes from 46.235.227.53: icmp_seq=48 ttl=52 time=126.540 ms
64 bytes from 46.235.227.53: icmp_seq=49 ttl=52 time=125.571 ms

--- thecrucible.online ping statistics ---
50 packets transmitted, 50 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 118.297/128.668/191.469/13.486 ms
```

**Comment by cryogen** [comment]
That's strange.  If the heartbeat timeout is invoked the client should reconnect and then try 5 times before it gives up.  One theory I have is that sometimes it might be retrying and getting the intermittent cert error.  The server already logs every disconnect.  Most are either "ping timeout" or "remote host closed the connection", the latter is usually when the browser gives up on the server or the user refreshes the page.  In either case the client should be reconnecting.  Thanks for the info, keep it coming!

**Comment by JediCat** [comment]
Firefox can’t establish a connection to the server at wss://thecrucible.online/socket.io/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZDg5OWZlZjMwMjliZDVlOGM0YmQ5YmMiLCJ1c2VybmFtZSI6InZhZnRzczIiLCJlbWFpbCI6ImFiaWV6ZW5za2kzQGdtYWlsLmNvbSIsInNldHRpbmdzIjp7ImRpc2FibGVHcmF2YXRhciI6ZmFsc2UsImNhcmRTaXplIjoibGFyZ2UiLCJiYWNrZ3JvdW5kIjoiTG9nb3MiLCJvcHRpb25TZXR0aW5ncyI6eyJtYXJrQ2FyZHNVbnNlbGVjdGFibGUiOnRydWUsImNhbmNlbE93bkFiaWxpdGllcyI6ZmFsc2UsIm9yZGVyRm9yY2VkQWJpbGl0aWVzIjp0cnVlLCJjb25maXJtT25lQ2xpY2siOnRydWUsInNob3dTdGF0dXNJblNpZGViYXIiOmZhbHNlfX0sInByb21wdGVkQWN0aW9uV2luZG93cyI6bnVsbCwicGVybWlzc2lvbnMiOnt9LCJ2ZXJpZmllZCI6dHJ1ZSwiZW5hYmxlR3JhdmF0YXIiOnRydWUsImJsb2NrTGlzdCI6W10sImlhdCI6MTU4NDIzNTc4NSwiZXhwIjoxNTg0MjM2MDg1fQ.4kLVh_cP44lCjZ59J8o9PfYx-Dj-CNB79vBclHWJu3E&version=2020-02-07&EIO=3&transport=websocket&sid=SBzBG9kvMMOqUbMCAB61. vendor.a39751d7c77f28a2946f.js:24:118329
No strings exist for this error type

Pinging thecrucible.online [46.235.227.53] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Reply from 46.235.227.53: bytes=32 time=212ms TTL=52
Request timed out.
Reply from 46.235.227.53: bytes=32 time=208ms TTL=52
Reply from 46.235.227.53: bytes=32 time=219ms TTL=52
Request timed out.
Request timed out.
Reply from 46.235.227.53: bytes=32 time=227ms TTL=52
Reply from 46.235.227.53: bytes=32 time=222ms TTL=52
Reply from 46.235.227.53: bytes=32 time=224ms TTL=52
Request timed out.
Reply from 46.235.227.53: bytes=32 time=217ms TTL=52
Request timed out.
Reply from 46.235.227.53: bytes=32 time=215ms TTL=52
Request timed out.
Reply from 46.235.227.53: bytes=32 time=214ms TTL=52
Request timed out.
Reply from 46.235.227.53: bytes=32 time=213ms TTL=52
Request timed out.
Reply from 46.235.227.53: bytes=32 time=211ms TTL=52
Reply from 46.235.227.53: bytes=32 time=220ms TTL=52
Reply from 46.235.227.53: bytes=32 time=224ms TTL=52
Request timed out.
Reply from 46.235.227.53: bytes=32 time=213ms TTL=52
Reply from 46.235.227.53: bytes=32 time=211ms TTL=52
Request timed out.
Request timed out.
Reply from 46.235.227.53: bytes=32 time=225ms TTL=52
Reply from 46.235.227.53: bytes=32 time=216ms TTL=52
Request timed out.
Reply from 46.235.227.53: bytes=32 time=214ms TTL=52
Reply from 46.235.227.53: bytes=32 time=212ms TTL=52
Reply from 46.235.227.53: bytes=32 time=214ms TTL=52
Reply from 46.235.227.53: bytes=32 time=222ms TTL=52
Request timed out.
Request timed out.
Reply from 46.235.227.53: bytes=32 time=213ms TTL=52
Reply from 46.235.227.53: bytes=32 time=214ms TTL=52
Request timed out.
Reply from 46.235.227.53: bytes=32 time=223ms TTL=52
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 46.235.227.53:
    Packets: Sent = 50, Received = 24, Lost = 26 (52% loss),
Approximate round trip times in milli-seconds:
    Minimum = 208ms, Maximum = 227ms, Average = 216ms

**Comment by miggy9001** [comment]
While looking into this issue the heartbeat is an issue however, there is also a lot of network issues around `Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID`.  After looking more into this issue it appears to simply be a configuration issue. There is nothing documented on how this is deployed so I am not sure how to suggest fixing it. The short of it is something is missing the SSL cert. Which is why it drops and losses the heart beat is that most browsers have the "feature" to block insecure traffic on a secure site. To show this is the issue if you were to open Chrome for example and allow insecure content on the site (see image below) even though you get the same errors you have have no issues connecting or reconnecting the game.

![image](https://user-images.githubusercontent.com/4131771/76693756-a1faee80-6638-11ea-8827-135064da9a3e.png)

I would be more than happy to help more with this, to do so I would need a bit more information as to how this is deployed.

**Comment by cryogen** [comment]
@JediCat your issue appears to be a bad network between you and the server.  These tend to be temporary and there's usually little I can do about it.  Where in the world are you based?

@miggy9001 Indeed, the cert issue is not helping matters and is the cause of images failing to load.  However, I can't for the life of me find out where this old certificate is coming from!  I will continue to look into this today

**Comment by cryogen** [comment]
Looks like I've managed to fix the SSL cert error.  Be interesting to see if reports of connection issues start to go down or whether that was just a red herring.  Keep the reports coming!

**Comment by johnnysavs** [comment]
I currently get the below error in the console. It also takes ages for any images to load until cached (see image 1)

POST https://thecrucible.online/api/account/checkauth 401 (Unauthorized)
  | (anonymous) | @ | breadcrumbs.js:380
-- | -- | -- | --
  | send | @ | jquery.js:9837
  | ajax | @ | jquery.js:9434
  | e.ajax | @ | jquery-migrate.js:191
  | (anonymous) | @ | api-middleware.js:49
  | c | @ | runtime.js:45
  | (anonymous) | @ | runtime.js:271
  | e.<computed> | @ | runtime.js:97
  | re | @ | index.js:14
  | s | @ | api-middleware.js:5
  | (anonymous) | @ | api-middleware.js:5
  | r | @ | api-middleware.js:5
  | (anonymous) | @ | api-middleware.js:5
  | (anonymous) | @ | index.js:11
  | dispatch | @ | applyMiddleware.js:35
  | (anonymous) | @ | account.js:132
  | (anonymous) | @ | index.js:8
  | (anonymous) | @ | bindActionCreators.js:3
  | value | @ | Application.jsx:35
  | co | @ | react-dom.production.min.js:135
  | Oi | @ | react-dom.production.min.js:167
  | ji | @ | react-dom.production.min.js:180
  | qa | @ | react-dom.production.min.js:232
  | Va | @ | react-dom.production.min.js:233
  | Ds | @ | react-dom.production.min.js:249
  | Ss | @ | react-dom.production.min.js:248
  | Ms | @ | react-dom.production.min.js:245
  | Qa | @ | react-dom.production.min.js:243
  | As | @ | react-dom.production.min.js:253
  | Rs | @ | react-dom.production.min.js:253
  | Fs.render | @ | react-dom.production.min.js:261
  | (anonymous) | @ | react-dom.production.min.js:264
  | js | @ | react-dom.production.min.js:251
  | Us | @ | react-dom.production.min.js:264
  | render | @ | react-dom.production.min.js:266
  | zak9 | @ | index.prod.jsx:61
  | f | @ | bootstrap:79
  | HAgx | @ | index.jsx:23
  | f | @ | bootstrap:79
  | 0 | @ | Maverick.png:1
  | f | @ | bootstrap:79
  | t | @ | bootstrap:45
  | r | @ | bootstrap:32
  | (anonymous) | @ | bundle.e0b7d53….js:1

Image 1
![image](https://user-images.githubusercontent.com/62869146/77878119-08784180-72b4-11ea-92d6-335eb04bf657.png)

**Comment by romanogit** [comment]
Old
