### ISSUE TITLE
Library access and wild wormhole interaction

### ISSUE THREAD

**Issue by Ginopinoshow** [keyteki/keyteki#1160]
When a "wild wormhole" is played in the same turn in which a "library access" has been played, according to page 29 of the rulebook, the player should be allowed to choose is drawing the top card of the deck or playing it.
Instead, the current implementation doesn't allow to choose.

This is especially important when there are 0 or only 1 card to draw, or when the next card in the deck has already been revealed due to other effects!

**Comment by romanogit** [comment]
Can you check your game play options (click on the gear at the right bottom side of the game area). Check if it has both checkboxes marked, that way the engine will prompt you for more decisions.

**Comment by Ginopinoshow** [comment]
yes, both the checkboxes are and were marked
