### ISSUE TITLE
Dis House - Mass Mutation

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#1167]
Dis 65 Cards / 42 New 65% 
---
- [x] 048 - [Skixuno](https://cdn.keyforgegame.com/media/card_front/en/479_048_4X83M6W9R45W_en.png)
- [x] 049 - [The Pale Star](https://cdn.keyforgegame.com/media/card_front/en/479_049_8X72CP3C4PGR_en.png)
- [x] 051 - [Turnkey](https://cdn.keyforgegame.com/media/card_front/en/479_051_G96F3F232VCG_en.png)

---

- [x] 001 - [Dark Æmber Vault](https://cdn.keyforgegame.com/media/card_front/en/479_001_8GCXGP3F824C_en.png)
- [x] 003 - [Brabble](https://cdn.keyforgegame.com/media/card_front/en/479_003_3MJP362G94PV_en.png)
- [x] 006 - [Drecker](https://cdn.keyforgegame.com/media/card_front/en/479_006_49MRFMXQ4QV9_en.png)
- [x] 011 - [Mark of Dis](https://cdn.keyforgegame.com/media/card_front/en/479_011_69QM5GGJ8Q4_en.png)
- [x] 012 - [Mindfire](https://cdn.keyforgegame.com/media/card_front/en/479_012_8GVQQ4CH9QWQ_en.png)
- [x] 023 - [Grim Reminder](https://cdn.keyforgegame.com/media/card_front/en/479_023_3W4J2VQ8873R_en.png)
- [x] 028 - [Picaroon](https://cdn.keyforgegame.com/media/card_front/en/479_028_RPH7PCCCP395_en.png)
- [x] 029 - [Relentless Creeper](https://cdn.keyforgegame.com/media/card_front/en/479_029_W3W56P8WMC2G_en.png)
- [x] 033 - [Wail of the Damned](https://cdn.keyforgegame.com/media/card_front/en/479_033_Q832C49FFHGH_en.png)
- [x] 035 - [Etan's Jar](https://cdn.keyforgegame.com/media/card_front/en/479_035_P7VQ83Q2RVGQ_en.png)
- [x] 040 - [Maleficorn](https://cdn.keyforgegame.com/media/card_front/en/479_040_44W8WFGMFQ3M_en.png)
- [x] 042 - [Painmail](https://cdn.keyforgegame.com/media/card_front/en/479_042_7Q74Q6F772X7_en.png)
- [x] 044 - [Ritual of Tognath](https://cdn.keyforgegame.com/media/card_front/en/479_044_V57XG74365G9_en.png)
- [x] 057 - [Gluttony](https://cdn.keyforgegame.com/media/card_front/en/479_057_F7VP9FHJ85WG_en.png)
- [x] 058 - [Greed](https://cdn.keyforgegame.com/media/card_front/en/479_058_QRQRH4FJ76MW_en.png)
- [x] 061 - [Sacro-Fiend](https://cdn.keyforgegame.com/media/card_front/en/479_061_J2X8Q4MFP78V_en.png)
- [x] 062 - [Sloth](https://cdn.keyforgegame.com/media/card_front/en/479_062_8JR36QMC2PJH_en.png)
- [x] 065 - [Xeno-Fiend](https://cdn.keyforgegame.com/media/card_front/en/479_065_3M885P4MH5RP_en.png)

**Comment by SkyJedi** [comment]
working down this list now
