### ISSUE TITLE
Sanctum House - Mass Mutation

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#1169]
Sanctum 57 / 33 New 58%
---
- [x] 126 - [Ardent Hero](https://cdn.keyforgegame.com/media/card_front/en/479_126_8654CP76HG8_en.png)

---

- [x] 128 - [Burning Glare](https://cdn.keyforgegame.com/media/card_front/en/479_128_8V9FCMPGMQ5C_en.png)
- [x] 129 - [Champion Anaphiel](https://cdn.keyforgegame.com/media/card_front/en/479_129_FR9V84W6X65C_en.png)
- [x] 132 - [Dæmo-Knight](https://cdn.keyforgegame.com/media/card_front/en/479_132_CV53WG3V8J78_en.png)
- [x] 135 - [General Xalvador](https://cdn.keyforgegame.com/media/card_front/en/479_135_F278PG3H957W_en.png)
- [x] 137 - [Lieutenant Gorvenal](https://cdn.keyforgegame.com/media/card_front/en/479_137_CP2G72CH5MGP_en.png)
- [x] 142 - [Æmberheart](https://cdn.keyforgegame.com/media/card_front/en/479_142_QVWRG3QMW2J4_en.png)
- [x] 143 - [Angry Mob](https://cdn.keyforgegame.com/media/card_front/en/479_143_VQJJCXPW6JWP_en.png)
- [x] 144 - [Baldric the Bold](https://cdn.keyforgegame.com/media/card_front/en/479_144_8W3R4977V5F4_en.png)
- [x] 147 - [Bring Low](https://cdn.keyforgegame.com/media/card_front/en/479_147_V3M3MQ3QXH43_en.png)
- [x] 150 - [Gizelhart’s Standard](https://cdn.keyforgegame.com/media/card_front/en/479_150_RCXWVVJ9W8QC_en.png)
- [x] 153 - [Purify](https://cdn.keyforgegame.com/media/card_front/en/479_153_6RRCF57PMCCG_en.png)
- [x] 159 - [Book of Malefaction](https://cdn.keyforgegame.com/media/card_front/en/479_159_HR3CMHC4P55R_en.png)
- [x] 160 - [Call to Action](https://cdn.keyforgegame.com/media/card_front/en/479_160_48VHJC6345XJ_en.png)
- [x] 165 - [Lady Loreena](https://cdn.keyforgegame.com/media/card_front/en/479_165_WM5FCHMM98VC_en.png)
- [x] 169 - [Master of the Grey](https://cdn.keyforgegame.com/media/card_front/en/479_169_R8JGCMC3HQX9_en.png)
- [x] 174 - [Purifier of Souls](https://cdn.keyforgegame.com/media/card_front/en/479_174_3PF2M62V5H24_en.png)
- [x] 178 - [Dino-Knight](https://cdn.keyforgegame.com/media/card_front/en/479_178_FV35M77JCR76_en.png)
- [x] 179 - [Lyco-Knight](https://cdn.keyforgegame.com/media/card_front/en/479_179_CR77WH5CRPMM_en.png)
- [x] 180 - [Techno-Knight](https://cdn.keyforgegame.com/media/card_front/en/479_180_VP289QGF88R8_en.png)
- [x] 181 - [Umbra-Knight](https://cdn.keyforgegame.com/media/card_front/en/479_181_R8V73CJXMMMX_en.png)
- [x] 182 - [Xeno-Knight](https://cdn.keyforgegame.com/media/card_front/en/479_182_FG4GCQVXH24M_en.png)

**Comment by romanogit** [comment]
Working on Berinon

**Comment by SkyJedi** [comment]
working on fangs

**Comment by SkyJedi** [comment]
workin on mad prophet

**Comment by SkyJedi** [comment]
Baldric 144 should probably be

> Before Fight: If the creature Baldric the Bold fights is the most powerful enemy creature, gain 2A.

**Comment by Toeofdoom** [comment]
Implementing some of these here: https://github.com/Toeofdoom/keyteki/tree/implement-mm-sanctum-cards
Currently implemented angry mob.
