### ISSUE TITLE
Saurian House - Mass Mutation

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#1170]
Saurian 62 (61 Deus) / 43 New 69%
---
- [x] 222 - [High Priest Torvus](https://cdn.keyforgegame.com/media/card_front/en/479_222_CX663X678C56_en.png)
- [x] 226 - [Optio Gorkus](https://cdn.keyforgegame.com/media/card_front/en/479_226_6V5WH64JR74P_en.png)
- [x] 230 - [Scylla](https://cdn.keyforgegame.com/media/card_front/en/479_230_VHG8J2GPHF29_en.png)

---

- [x] 186 - [Citizen Shrix](https://cdn.keyforgegame.com/media/card_front/en/479_186_RGCC6M9G2QRX_en.png)
- [x] 188 - [Cornicen Octavia](https://cdn.keyforgegame.com/media/card_front/en/479_188_PPPRWFXCVWWG_en.png)
- [x] 189 - [Curse of Vanity](https://cdn.keyforgegame.com/media/card_front/en/479_189_66RHWHRQ8863_en.png)
- [x] 191 - [Defense Initiative](https://cdn.keyforgegame.com/media/card_front/en/479_191_93PJW4C6WP5F_en.png)
- [x] 194 - [Monument to Ludo](https://cdn.keyforgegame.com/media/card_front/en/479_194_GVVH5C3X2PJV_en.png)
- [x] 196 - [Sagittarii's Gaze](https://cdn.keyforgegame.com/media/card_front/en/479_196_86HWRJ97W8VG_en.png)
- [x] 200 - [Blast from the Past](https://cdn.keyforgegame.com/media/card_front/en/479_200_7PW589CCHXV3_en.png)
- [x] 202 - [Curia Saurus](https://cdn.keyforgegame.com/media/card_front/en/479_202_Q556C9VQGR8P_en.png)
- [x] 204 - [Dreadbone Decimus](https://cdn.keyforgegame.com/media/card_front/en/479_204_99C6R8FF22C2_en.png)
- [x] 206 - [Gladiodontus](https://cdn.keyforgegame.com/media/card_front/en/479_206_MHPJPV8W43Q5_en.png)
- [x] 211 - [Senator Quintina](https://cdn.keyforgegame.com/media/card_front/en/479_211_V43QR4XQXW2J_en.png)
- [x] 212 - [Siren Horn](https://cdn.keyforgegame.com/media/card_front/en/479_212_6HRHX9FH7XMP_en.png)
- [x] 217 - [Crystal Surge](https://cdn.keyforgegame.com/media/card_front/en/479_217_VV6FHF96Q4C_en.png)
- [x] 219 - [Forum of Giants](https://cdn.keyforgegame.com/media/card_front/en/479_219_69G93QGR7H2H_en.png)
- [x] 224 - [Legion's March](https://cdn.keyforgegame.com/media/card_front/en/479_224_5CJCM7763QCH_en.png)
- [x] 225 - [Nerotaurus](https://cdn.keyforgegame.com/media/card_front/en/479_225_67834PXHXPQF_en.png)
- [x] 227 - [Patronage](https://cdn.keyforgegame.com/media/card_front/en/479_227_R9FVMC5QM2J4_en.png)
- [x] 234 - [Charybdis](https://cdn.keyforgegame.com/media/card_front/en/479_234_GWC5F4XX5CM2_en.png)
- [x] 236 - [Monument to Faust](https://cdn.keyforgegame.com/media/card_front/en/479_236_95GV7R388XX7_en.png)
- [x] 237 - [Monument to Octavia](https://cdn.keyforgegame.com/media/card_front/en/479_237_33G3JGXGRHGQ_en.png)
- [x] 239 - [Monument to Shrix](https://cdn.keyforgegame.com/media/card_front/en/479_239_JWJ44H36M6FG_en.png)
- [x] 243 - [Xeno-Saurus](https://cdn.keyforgegame.com/media/card_front/en/479_243_QG2X5X52G354_en.png)

**Comment by ryanch** [comment]
I'm going to start on Saurian Egg

**Comment by ryanch** [comment]
I'm going to start on Dark Centurion

**Comment by ryanch** [comment]
I'm going to start on Spoils of Battle
