### ISSUE TITLE
StarAlliance House - Mass Mutation

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#1172]
Star Alliance 60 / 40 New 67%
---
- [x] 305 - [Crewman Jörg](https://cdn.keyforgegame.com/media/card_front/en/479_305_4QW44X7Q58QV_en.png)
- [x] 306 - [Dæmo-Alien](https://cdn.keyforgegame.com/media/card_front/en/479_306_8V3P9R7QCHVV_en.png)
- [x] 308 - [Hadron Collision](https://cdn.keyforgegame.com/media/card_front/en/479_308_55R349MHQ2P7_en.png)
- [x] 309 - [Observ-u-Max](https://cdn.keyforgegame.com/media/card_front/en/479_309_58M3CG48V3QC_en.png)
- [x] 321 - [Detention Coil](https://cdn.keyforgegame.com/media/card_front/en/479_321_VFQGV2CCWH22_en.png)
- [x] 324 - [LCdr. Trigon](https://cdn.keyforgegame.com/media/card_front/en/479_324_R242QFCM77C_en.png)
- [x] 325 - [Mutagenesis Researcher](https://cdn.keyforgegame.com/media/card_front/en/479_325_W237RJ5H5V4R_en.png)
- [x] 326 - [New Frontiers](https://cdn.keyforgegame.com/media/card_front/en/479_326_5W8C7PWFJW8_en.png)
- [x] 329 - [Stealthster](https://cdn.keyforgegame.com/media/card_front/en/479_329_Q48JP863C362_en.png)
- [x] 335 - [Ambassador Liu](https://cdn.keyforgegame.com/media/card_front/en/479_335_582P839P6HF9_en.png)
- [x] 337 - [Commander Dhrxgar](https://cdn.keyforgegame.com/media/card_front/en/479_337_6FHWP43QGPJW_en.png)
- [x] 345 - [Hapless Cadet](https://cdn.keyforgegame.com/media/card_front/en/479_345_3JPX2CHRGR6J_en.png)
- [x] 346 - [Hold the Line](https://cdn.keyforgegame.com/media/card_front/en/479_346_G62M782WF22P_en.png)
- [x] 347 - [J.O.N. Cargo](https://cdn.keyforgegame.com/media/card_front/en/479_347_R4XHX8JQ3RJ_en.png)
- [x] 348 - [Kartanoo](https://cdn.keyforgegame.com/media/card_front/en/479_348_4WHJ78MJRP7M_en.png)
- [x] 353 - [Z-Force Agent 14](https://cdn.keyforgegame.com/media/card_front/en/479_353_3GQ3XM88H2QW_en.png)
- [x] 354 - [Z-Particle Tracker](https://cdn.keyforgegame.com/media/card_front/en/479_354_HJ428RH2M7HM_en.png)
- [x] 355 - [Z-Ray Blaster](https://cdn.keyforgegame.com/media/card_front/en/479_355_M2W8MWQ99C2J_en.png)
- [x] 356 - [Z-Wave Emitter](https://cdn.keyforgegame.com/media/card_front/en/479_356_58JWRV9JVR9W_en.png)
- [x] 357 - [Dino-Alien](https://cdn.keyforgegame.com/media/card_front/en/479_357_R2GX594MQ3CQ_en.png)
- [x] 358 - [Lyco-Alien](https://cdn.keyforgegame.com/media/card_front/en/479_358_HRHF7CX9C6MC_en.png)
- [x] 359 - [Sacro-Alien](https://cdn.keyforgegame.com/media/card_front/en/479_359_PRRR7MR627QR_en.png)
- [x] 360 - [Techno-Alien](https://cdn.keyforgegame.com/media/card_front/en/479_360_85RX34V2387X_en.png)
- [x] 361 - [Umbra-Alien](https://cdn.keyforgegame.com/media/card_front/en/479_361_PQMG8X4C99HJ_en.png)

**Comment by ryanch** [comment]
I'm going to try to make "access denied".

**Comment by ryanch** [comment]
I've got access denied and a test for it, but test is failing - saying cards are not registered.

**Comment by ryanch** [comment]
I'm going to start on blast shielding - have not resolved the testing issue yet.

**Comment by ryanch** [comment]
https://github.com/keyteki/keyteki/pull/1192/commits/cb4d6b2fdaacccca605536b23c936a2bc0d98485 << Access Denied

**Comment by ryanch** [comment]
Access denied is here: https://github.com/keyteki/keyteki/pull/1195

**Comment by ryanch** [comment]
Blasting Shield done. https://github.com/keyteki/keyteki/issues/1172

**Comment by ryanch** [comment]
starting on scout pete.

**Comment by SkyJedi** [comment]
Mutagenesis Researcher is a nothing-burger card

**Comment by ryanch** [comment]
Scout Pete done. 

Starting on Survey.

**Comment by ryanch** [comment]
Starting on Teleporter Chief Tink.

**Comment by ryanch** [comment]
I'm going to start on ANT1-10NY

**Comment by ryanch** [comment]
Sky Jedi is on ANT1-10NY, so I will move on to Particle Sweep

**Comment by ryanch** [comment]
I'm going to work on Matter Maker

**Comment by romanogit** [comment]
Done
