### ISSUE TITLE
Untamed House - Mass Mutation

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#1173]
Untamed 61 (60 inc Niff) / 35 New 57%
---
- [x] 362 - [Cephaloist](https://cdn.keyforgegame.com/media/card_front/en/479_362_PXR679JWGGCR_en.png)
- [x] 364 - [Dark Faerie](https://cdn.keyforgegame.com/media/card_front/en/479_364_GR696M75FX2F_en.png)
- [x] 365 - [Fandangle](https://cdn.keyforgegame.com/media/card_front/en/479_365_4MGG3MJ4GVJ6_en.png)
- [x] 368 - [Gloriana's Attendant](https://cdn.keyforgegame.com/media/card_front/en/479_368_4R7RMFG3HCPP_en.png)
- [x] 372 - [Pismire](https://cdn.keyforgegame.com/media/card_front/en/479_372_RFRFQ3J846JX_en.png)
- [x] 373 - [Rapid Evolution](https://cdn.keyforgegame.com/media/card_front/en/479_373_HCPV29XGH25X_en.png)
- [x] 380 - [Commune](https://cdn.keyforgegame.com/media/card_front/en/479_380_VRV63277QR2W_en.png)
- [x] 381 - [Dark Harbinger](https://cdn.keyforgegame.com/media/card_front/en/479_381_FGHP825MPQG6_en.png)
- [x] 383 - [Growth Surge](https://cdn.keyforgegame.com/media/card_front/en/479_383_89G8P7PMGG8_en.png)
- [x] 385 - [Lumilu](https://cdn.keyforgegame.com/media/card_front/en/479_385_MV8M8QM2PRH2_en.png)
- [x] 389 - [Trimble](https://cdn.keyforgegame.com/media/card_front/en/479_389_62HXJ98MX482_en.png)
- [x] 391 - [Vault’s Blessing](https://cdn.keyforgegame.com/media/card_front/en/479_391_66QQ7HV563PV_en.png)
- [x] 394 - [Æmberlution](https://cdn.keyforgegame.com/media/card_front/en/479_394_85J25GC24WC2_en.png)
- [x] 395 - [Blossom Drake](https://cdn.keyforgegame.com/media/card_front/en/479_395_FFJ4XQRPR824_en.png)
- [x] 396 - [Chonkers](https://cdn.keyforgegame.com/media/card_front/en/479_396_86W72JX3Q4WH_en.png)
- [x] 397 - [Dark Queen Gloriana](https://cdn.keyforgegame.com/media/card_front/en/479_397_VXF2QJ472HR8_en.png)
- [x] 400 - [Eunoia](https://cdn.keyforgegame.com/media/card_front/en/479_400_944V3788F9V2_en.png)
- [x] 402 - [Look What I Found!](https://cdn.keyforgegame.com/media/card_front/en/479_402_VV42972V63FJ_en.png)
- [x] 413 - [Mutation of Cunning](https://cdn.keyforgegame.com/media/card_front/en/479_413_RPH55X5R57F3_en.png)
- [x] 414 - [Mutation of Fury](https://cdn.keyforgegame.com/media/card_front/en/479_414_FFG6Q4WP3J73_en.png)
- [x] 415 - [Mutation of Instinct](https://cdn.keyforgegame.com/media/card_front/en/479_415_WMF2936462X5_en.png)
- [x] 418 - [Sacro-Beast](https://cdn.keyforgegame.com/media/card_front/en/479_418_FV45PQ98CR3M_en.png)
- [x] 420 - [Umbra-Beast](https://cdn.keyforgegame.com/media/card_front/en/479_420_JPJFWVPG5CGF_en.png)
- [x] 421 - [Xeno-Beast](https://cdn.keyforgegame.com/media/card_front/en/479_421_6Q3R2QMRCQ7Q_en.png)

**Comment by SkyJedi** [comment]
Umbra-Beast  is a nothing-burger

**Comment by SkyJedi** [comment]
Niffle Kong should be

```
12 power - 2 armor
Play: Search your deck and discard pile for any number of Niffle creatures, reveal them, and add them to your hand. Shuffle your deck.
Fight/Reap: You may destroy a friendly Niffle creature. If you do, deal 3 damage to a creature, steal 1A, and destroy an enemy artifact.
```

**Comment by romanogit** [comment]
I think that's how I implemented

**Comment by romanogit** [comment]
Just noticed the `any` in Niffle Kong. I will review it :)

**Comment by romanogit** [comment]
Working on top untamed cards
