### ISSUE TITLE
(Dis) Pandemonium - Not working as expected

### ISSUE THREAD

**Issue by Achocholacek** [keyteki/keyteki#12]
Card Text: "Play: Each undamaged creature captures 1 from its opponent."

Expected Behaviour - Each Undamaged Creature captures 1 Aember from its opponent.
Actual Behaviour - No Aember is Captured, regardless of damage state.

**Comment by maleckai** [comment]
Was just testing this out and it appears to work fine 🤔 Tried several combinations of damaged, undamaged creatures. Excess Aember, or a few short, or no Aember. Everything worked as expected.

Is this still an issue?

**Comment by Achocholacek** [comment]
Entirely possible that it isn't. Will close for now and it can always be re-opened.
