### ISSUE TITLE
Fetchdrones bug

### ISSUE THREAD

**Issue by Kebay** [keyteki/keyteki#1202]
If I play the card 

> Fetchdrones - artifact - Logos: action, discard the top two cards of your deck. For each Logos card discarded this way, a friendly creature captures 2 Æmber.

and discard two Logos card while having 2+ creatures in play, I cannot choose one of them twice but have to choose two different creatures. However, I think that a single creature should be allowed to capture all four amber. (I do not know what happens if only one creature is in play.)

**Comment by romanogit** [comment]
@Kebay : just created a PR for this one. Thanks for reporting.
