### ISSUE TITLE
I created a website using this code

### ISSUE THREAD

**Issue by wu123456** [keyteki/keyteki#1215]
I created a website using this code in China [](http://kf.jixhui.com) but it seems lose the images in "/public/img/idbacks/archons/". Or I make something in a wrong way.

**Comment by romanogit** [comment]
You have to build the archon back images. Look at server/scripts/build_archons.js

**Comment by romanogit** [comment]
BTW, It takes a long time to build as it combines different colors and different houses combinations, toalling 35280 images, which takes around 20GB of disk space.

**Comment by wu123456** [comment]
Thank you very much.I got it.
