### ISSUE TITLE
[AoA] [Dis] Tezmal couldn't reap

### ISSUE THREAD

**Issue by Blaph** [keyteki/keyteki#122]
Don't know exactly what happened there but I selected Dis as my active house and my Tezmal could just fight.
Could have happened because I activated "Signal Fire" just before

**Comment by romanogit** [comment]
@Blaph : do you have more information about this? Are you able to see it happening again?

**Comment by Blaph** [comment]
@romanogit Hi! Just tested it and the issue didn't happen again.

**Comment by romanogit** [comment]
Thanks for sharing. I will try to recreate it anyway.

**Comment by romanogit** [comment]
@cryogen : since this is unable to reproduce, can you close?

**Comment by cryogen** [comment]
As above, we have been unable to reproduce this issue.  If you're able to provide more information in the future please reopen this issue.
