### ISSUE TITLE
feature request: manual mode command to discard cards FROM TOP OF DECK

### ISSUE THREAD

**Issue by hydrophilic-attack** [keyteki/keyteki#1238]
There should be a way in manual mode to randomly discard cards FROM TOP OF DECK rather than from your hand.

I made an issue (#735) about this in the past, but it was closed by @Achocholacek who cited that the /discard command works.

However, this is not correct. The /discard command discards a random card from hand, This is described on the how to play page ("/discard x - Discards x cards randomly from your hand") and I also just now tested to make sure. Indeed the /discard command discards from your hand. If you have 0 cards in hand nothing happens. But the feature I requested in my previous issue was a way to manually discard THE TOP CARD OF YOUR DECK, rather than a random card from hand

**Comment by Achocholacek** [comment]
Sorry @hydrophilic-attack - I went on a mad tear cleaning up tickets and was near asleep. I completely misunderstood things. Looks like Jedi has it sorted though!

**Comment by hydrophilic-attack** [comment]
hey no worries @Achocholacek
