### ISSUE TITLE
Jargogle and Knox

### ISSUE THREAD

**Issue by babyarmben** [keyteki/keyteki#125]
Jargogle doesn't let you place a card underneath once played.

Knox doesn't get the +3 once adding a neighbor or neighbors

**Comment by Herzbube76** [comment]
game 5 minutes ago, jargogle dindt work, last game it worked... fixed or sometimes buggy only?

**Comment by Achocholacek** [comment]
Re: Knoxx - His power boosts are there, but as they are not technically "power counters" there is no official indication of them.

Potentially having some degree of iconography to show non power counter power boosts is a topic of discussion

**Comment by cryogen** [comment]
Jargogle is now live, and as mentioned Knox does not add power counters, but does increase the power of the creature.  Closing.  I wouldn't be against a new issue being opened as an enhancement to add the other indication mentioned
