### ISSUE TITLE
Harland mindlock to take control of opponent's sci. officer morpheus should let you take control of one more creature. When we tried to fix it in manual mode everything broke

### ISSUE THREAD

**Issue by hydrophilic-attack** [keyteki/keyteki#1251]
My opponent had sci. officer morpheus and lieutenant Khrkhar with cloaking dongle and qincan's blaster in play

I played Harland Mindlock to take control of morpheus. At that point we are still in the window of "after a creature is played" so Harland's play ability should trigger again thanks to morpheus. (Nexus + Spectral Tunneler ruling) This didn't happen.

When we tried to fix it in manual mode, everything went haywire. I got control, but Khrkhar didn't move to my side. We tried to put him in discard, and then there was one in discard and one still on my opponent's side of the board.

See attached log file and screenshot
[harland morpheus upgraded khrkhar.txt](https://github.com/keyteki/keyteki/files/4429940/harland.morpheus.upgraded.khrkhar.txt)
![harland morpheus](https://user-images.githubusercontent.com/45927070/78405600-1d7d0980-7601-11ea-90f0-5ee2892adb11.JPG)

**Comment by jeremylarner** [comment]
Fixed in #1247
