### ISSUE TITLE
If a reassembling automaton attacks opponent's Hapsis while there are friendly creatures in play, opponent's Hapsis should not be warded and draw a card

### ISSUE THREAD

**Issue by hydrophilic-attack** [keyteki/keyteki#1276]
[automaton hapsis.txt](https://github.com/keyteki/keyteki/files/4445768/automaton.hapsis.txt)
My opponent, who had other friendly creatures in play, used their Reassembling Automaton to attack my Hapsis. This caused my Hapsis to be warded and made me draw a card. This is incorrect, because the automaton's Destroyed ability is a replacement effect, so the Automaton is never considered to have been destroyed, meaning that my Hapsis's constant ability should not trigger.

See the attached log, turn 5

**Comment by Ginopinoshow** [comment]
Same works with other similar effects, like Mugwump
