### ISSUE TITLE
Yzphyz Knowdrone

### ISSUE THREAD

**Issue by Swiftlogix** [keyteki/keyteki#128]
Not able to purge an enemy card from their archive

**Comment by Achocholacek** [comment]
While I'm open to discussion on this - I do not believe your opponent's archives are a valid target for Knowdrone's ability.

You are only allowed to target their archives if it specifically mentions them. In this case, it does not, and I believe you are only allowed to purge from your own archive.

Leaving open for discussion purposes.

**Comment by cryogen** [comment]
There's nothing in the rules that suggests you *shouldn't* be able to target your opponent's archives.  But I don't think that's what they intended with the card.

Some discussion was had on this and I think the consensus was to offer a choice between 'your archives and opponents archives and pick one at random if opponents.

**Comment by Achocholacek** [comment]
I thought the specific understanding of the rules was that unless it specifically says it targets your opponents archives, you can't target them, as they're considered an out-of-play "unknowable" area..

I'll go with whatever, but I feel like it should only be from your archives.

**Comment by cryogen** [comment]
I think there's enough doubt to not invest any time in this until it's clarified, but i'll leave the issue open for now, perhaps reflagging it as a rules question rather than a bug

**Comment by Swiftlogix** [comment]
It was mentioned by Brad Andres at an American Vault tour when talking about the Archemedes Ruling, not sure if it's rock-solid official
  https://www.reddit.com/r/KeyforgeGame/comments/c13zzb/so_knowdrone_and_archimedes_just_got_a_whole_lot/
