### ISSUE TITLE
Can I change my user name?

### ISSUE THREAD

**Issue by Meriwether11** [keyteki/keyteki#1291]
I was just wondering if it would be possible to change my user name on the crucible online. I wanted to match it up with the same username that I have on the KeyForge app. I tried to create a new account but it won’t let me do that because I still have the same email address.I was wondering if there was an easy way to do this.  I wouldn’t even mind if I had to rescan all my decks if there was a way to delete my account and start a new one with my same e-mail address. I didn’t see any options on the profile menu. If not, not a big deal. I was just wondering if it could be done. Thanks! I appreciate everything you guys do in the crisp online 😃

**Comment by cryogen** [comment]
Fixed by #1958
