### ISSUE TITLE
2x Keyforgery bug

### ISSUE THREAD

**Issue by bensissel** [keyteki/keyteki#1296]
So far if i have 2 copies of keyforgery in play this is generally what happens when they go to forge a key.

They say Saurians, I reveal a saurian card so they nothing makes them skip their key step. The second keyforgery trigger happens, they say saurians - i reveal a shadows card - forcing them to skip their forge a key step. However- i get a "server error", neither keyforgery is destroyed, and they still didn't skip their forge a key step. 

If i manual mode and destroy one of the keyforgery cards, then the next time keyforgery happens- it will prevent the key from being forged- but then not get destroyed if they guessed incorrectly. very frustrating issue.

**Comment by SkyJedi** [comment]
i re-wrote the test for a double keyforgey 1 choice good one choice bad. tried to rewrite it based on evasion sigil but its beyond me  
[Keyforgery.spec.zip](https://github.com/keyteki/keyteki/files/4467321/Keyforgery.spec.zip)
