### ISSUE TITLE
Jargogle

### ISSUE THREAD

**Issue by filippoabba** [keyteki/keyteki#132]
I can't put a card under it

**Comment by Herzbube76** [comment]
game 5 minutes ago it didnt work. game last minute it did work.. wondering

**Comment by Herzbube76** [comment]
other bug with jargogle... if my opponent destroys it, the card comes to archive facedown as it belongs to oppenent.

**Comment by romanogit** [comment]
> if my opponent destroys it, the card comes to archive facedown as it belongs to oppenent.

Reported in https://github.com/keyteki/keyteki/issues/187

**Comment by romanogit** [comment]
> if my opponent destroys it, the card comes to archive facedown as it belongs to oppenent.

Can you provide more details? What do you mean the card belongs to the opponent? The card should go to your archive and you should see it face up when you hover the mouse over the archive pile. 

Hope my understanding is correct.

**Comment by cryogen** [comment]
Closing this as there's very little detail on it and we have other issues open on the card
