### ISSUE TITLE
Jargogle allows to play warding cards to prevent other cards destruction

### ISSUE THREAD

**Issue by Ginopinoshow** [keyteki/keyteki#1330]
If a card that grants ward is played under jargogle and then a board clear card is played, it is possible to use the card under jargogle to ward another creature and not remove it from the game. This is wrong, cause the other creature would already be tagged for destruction and so NO EFFECT (except substitution) should allow it to survive.

**Comment by romanogit** [comment]
This is not happening anymore, probably already fixed by old PRs.

![image](https://user-images.githubusercontent.com/2104075/102091476-a3db2380-3dfd-11eb-8bcf-26b868ff9ed8.png)
