### ISSUE TITLE
Bait and Switch ( bug )

### ISSUE THREAD

**Issue by Tchekoff** [keyteki/keyteki#1348]
Hello, the card did not work, it did not repeat the recovery of anember. Cordially.
[dialogue.txt](https://github.com/keyteki/keyteki/files/4530438/dialogue.txt)

**Comment by cryogen** [comment]
Thanks for your report.  Bait and Switch was errated to only trigger a maximum of twice.  Please see the following from FFG: "“Play: If your opponent has more æmber than you, steal 1 æmber. Repeat the preceding effect if your opponent still has more æmber than you.”

With this change, Bait and Switch’s steal effect can only trigger at most twice, once initially and then one additional time if your opponent still has more æmber than you. This limits the potential of the card to steal vast swathes of æmber from your opponent, but it still helps you out when you're behind."

Bait and switch is working on the site according to this errata, so I will close this
