### ISSUE TITLE
Crazy killing machine does not let you choose the order

### ISSUE THREAD

**Issue by Kebay** [keyteki/keyteki#1359]
[Crazy killing machine](https://decksofkeyforge.com/cards/crazy-killing-machine) does not prompt which creature/artifact to destroy first.

As seen in a game I just played (forgot to make a screenshot, sorry), this can be important: My opponent had a Titan Guardian next to a Shadows creature (and next to another creature), I discarded a Shadow card from his deck and a Logos card from my deck. The game prompted me to choose a Logos card to destroy. Obviously, I wanted to kill the Shadows creature first and then Titan Guardian to prevent Titan Guardian's effect from triggering but was not able to do that.

**Comment by Kebay** [comment]
After thinking about this again, I believe that I misunderstood that card. Destroying seems to happen simultaneously.

I do not know what happens if (in the scenario above) the Shadow and Logos cards are discarded from my and my opponent‘s discard pile, respectively. I *guess* that the current implementation would not allow Titan Guardian to draw two cards and hence I think that despite my misunderstanding there is still ab bug.

**Comment by romanogit** [comment]
I was able to recreate this one. Indeed, the destroy is not happening simultaneously.

![image](https://user-images.githubusercontent.com/2104075/92559961-f24db480-f247-11ea-9af8-a9635e9f8d94.png)
