### ISSUE TITLE
Soul Snatcher

### ISSUE THREAD

**Issue by Nortumal** [keyteki/keyteki#136]
When a creatures dies,the artifact owner gain also enemies ambaers. that s wrong

**Comment by skrohmagnon** [comment]
is it from the log ? because the log is wrong but the effect used to be true

**Comment by Nortumal** [comment]
If I destroyed 5 creatures ( 3 mine and 2 opponents), I gain 5 ambaers. But
that is wrong....
I had to receive 3 ambaers

**Comment by Achocholacek** [comment]
@Nortumal can you give any better idea of what board state was at the time? I cannot recreate the issue locally to troubleshoot it.
As @skrohmagnon said - the log shows one player gaining all the aember, but the actual aember totals of the players are adjusted as they should be.

**Comment by Achocholacek** [comment]
PR to clean up effect text, waiting on further details re original bug

**Comment by Nortumal** [comment]
Np
Turn 3:
I had 0 ambaers, my opponent too
He had 2 creatures o his side of field.
I play soul snatcher, 3 creatures and gateway of dis...

I think that I gain 3 ambaers, but in real I gain 5 ambaers... My opponent
none
Understand?
Soul snatcher said that owner of died creatures gain 1 ambaer, not only
artifact owner

Il lun 29 lug 2019, 02:08 Achocholacek <notifications@github.com> ha
scritto:

**Comment by cryogen** [comment]
I think #161 has fixed this, and it was a display issue.  Please reopen if this is not the case with further information.
