### ISSUE TITLE
Mass Mutation - Securi-Droid graphical error

### ISSUE THREAD

**Issue by benjamintownsend** [keyteki/keyteki#1371]
My opponent attached Securi-Druid as an upgraded to their Logo creature to give it taunt. The creature received taunt, yet graphically the card was shown attached to one of my creatures and one of my artifacts.
![SecuriDroid](https://user-images.githubusercontent.com/19664640/80802574-968f6280-8ba7-11ea-9f24-613c0a26e309.png)

**Comment by romanogit** [comment]
I think i captured a better screenshot:

![image](https://user-images.githubusercontent.com/2104075/81483669-4ef77f00-9216-11ea-9768-b67ed5b290fa.png)
