### ISSUE TITLE
One Stood Against Many vs Taunt

### ISSUE THREAD

**Issue by drallieiv** [keyteki/keyteki#1380]
One Stood Against Many seems to not check for the target card to be affected by a neighbor creature with taunt, nor if the attacking creature has taunt ignore.

Selecting a creature affected by taunt if the attacking creature doesn't have taunt ignore should not be a valid target.

**Comment by cryogen** [comment]
Thanks for the report.  OSAM isn't implemented very well, we have a catch-all for the issues that it causes in #241 so I'm going to link this to that and close this one.
