### ISSUE TITLE
Rapipdly Ever Changing Sadao - Floomf

### ISSUE THREAD

**Issue by drallieiv** [keyteki/keyteki#1381]
got a prompt for capture bonus icon on a Floomf (Sadao has 2) but the image I was shown was without the bonus pip.

So either the card listing of the deck is wrong, or the picture is wrong.

Sadao should have 1 regular Floomf and 1 with a bonus Capture pip

I was playing in french (for the image ref)

**Comment by drallieiv** [comment]
Talked with SkyJedi in chat, seems that the decklist is correct, but keyteki doesn't yet have a way to display the enhanced variants of an image.

Within the 4 MM decks, cards that exist with different combination of pips will only shown 1 version.

**Comment by romanogit** [comment]
Should we close this one, then?

**Comment by romanogit** [comment]
Enhancement is now in place. Should solve this issue.
