### ISSUE TITLE
Sneklifter

### ISSUE THREAD

**Issue by Nerapiuma** [keyteki/keyteki#139]
Now Sneklifter doesn't turn the card into a Shadows card if you don't have the house it belongs to and you have to call that house to use the artifact.

**Comment by Achocholacek** [comment]
The card is still turned into a shadows card, however, the engine still displays the house of the controlled artifact in the selection menu. If you choose shadows, you are able to use the stolen card.

@cryogen - Card works as expected, but will need to modify the ui.

**Comment by romanogit** [comment]
It would be a crazy combination to have a Shadows  maverick card as Mars, for example, being turned into Shadow back by Sneklifter when played with a deck that does not have Mars.

**Comment by romanogit** [comment]
@Achocholacek , @cryogen ,
I will try to work on this one. Not sure if this is an UI issue. The prompt is driven by the server engine.

**Comment by romanogit** [comment]
Fixed it:

Mars is not listed here:
![image](https://user-images.githubusercontent.com/2104075/63591926-9fdf1e80-c586-11e9-9ea3-d45029697eff.png)

And I am able to play it as Shadows:
![image](https://user-images.githubusercontent.com/2104075/63591951-b4231b80-c586-11e9-8836-4df53ae85163.png)

It is interesting that this card (Mothergun) says to reveal any number of Mars cards in your hands. So, not a good artifact to control with my archon :) :)

**Comment by cryogen** [comment]
Fixed in #139.  Please note this has not yet been deployed to the site.
