### ISSUE TITLE
mimic gel and duskwitch - no omega and mimic gel enters ready

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#1394]
mimic gel and duskwitch - no omega and mimic gel enters ready

Also, it did not copy Duskwitch elusive keyword

**Comment by drallieiv** [comment]
I suppose you are talking about "Mimic Gel" 
Omega ruling has not be confirmed yet, but with the interpretation of the timing chart

> PLAY A CARD.
> 1. If your card is a creature, artifact or upgrade, put it into play.
> If your card is an action, reveal it (after you play it, discard it).
> 2. Resolve the Æmber bonus on your card.
> » “PLAY:” EFFECTS AND “AFTER PLAY/ENTERS PLAY” EFFECTS TRIGGER

The After Play of Omega should be applied

> After a card with the Omega keyword is played, the current step of the game ends

Also for some weird reason, Omega does not ends turn, but ends step. So if for some weird reason an Omega creature would enter play during step 1 or 2 (Forge a key, Choose a house) you should still be able to play your step 3 entirely.

**Comment by romanogit** [comment]
Fixed by event rework
