### ISSUE TITLE
Timequake discards upgrades instead of shuffling back in and drawing

### ISSUE THREAD

**Issue by palpster** [keyteki/keyteki#1395]
I just had Ogopogo, Ganger Chieftain, Flamethrower in play when I started my turn. Played Imperial Scutum on Ogopogo and then Timequake expecting to shuffle back in all 4 cards and draw 4. What happened was I shuffled both creatures and the artifact back in, the Scutum was discarded and I did not draw for it.

Was about to get screenshot and chat log when server was restarted with impeccable timing ;)

**Comment by drallieiv** [comment]
> Timequake
> Play: Shuffle each friendly card in play into your deck. Draw a card for each card shuffled into your deck this way.
> 

Guess that the creature holding the upgrade was shuffled before it's attachement, and the attachment got discarded.

Couting the number of cards to draw went properly, but the attachments should have been shuffled.

Fix: should shuffle all attachments before creatures.

**Comment by drallieiv** [comment]
Fix PR submitted
