### ISSUE TITLE
Cincinnatus Rex + Creed of Nurture behaves incorrectly

### ISSUE THREAD

**Issue by ira212** [keyteki/keyteki#1398]
Steps to Reproduce:
**1)** Have a creature in play, Creed of Nurture in play, Cincinnatus Rex in hand, and your opponent has a creature in play that your creature can fight (and live through the fight). I recommend a Saurian creature for convenience, but any creature + Orator Hissaro will work too.

**2)** Choose house Saurian.

**3)** Use Creed of Nurture, targeting your creature in play, and choosing Cincinnatus Rex from your hand.

**4)** Play Cincinnatus Rex.

**5)** Fight with your other creature (that has Creed of Nurture), and trigger the Fight ability to ready all other friendly cards.

Notice that your creature ends up ready, and Cincinnatus Rex remains exhausted.

**Expected Behavior:** Cincinnatus Rex should be ready, and the creature that you just used to fight should be exhausted (with 1 amber on it).

Reproducability: 100%

A good deck to use for testing this: https://www.keyforgegame.com/deck-details/db137d17-0ecd-4fd7-849b-4ce7958ee29e

**Comment by drallieiv** [comment]
Might help to have the cards or at list the texts

![Creed of Nurture](https://archonarcana.com/images/f/f9/452-386.png)
![Cincinnatus Rex](https://archonarcana.com/images/thumb/9/9a/452-215.png/300px-452-215.png)

**Comment by drallieiv** [comment]
Todo : add checks on Creed of Nurture to test if it properly copies a tirggered ability such as fight and if it gets triggered.
