### ISSUE TITLE
bellowing Patrizate vs shark

### ISSUE THREAD

**Issue by AleksandrShepelev** [keyteki/keyteki#1409]
should be able to kill patrizate with shark before his effect triggers

**Comment by romanogit** [comment]
![image](https://user-images.githubusercontent.com/2104075/87969748-1affcc00-ca99-11ea-91f9-d7675ac52f8a.png)

![image](https://user-images.githubusercontent.com/2104075/87969774-24893400-ca99-11ea-8ebf-485448b5b4a6.png)

**Comment by romanogit** [comment]
This is an old one. If you have the Game Settings to decide the order of effects, and you play Shark, you should be able to decide (APC). If your opponent's play Shark, he may decide to call Shark's effect first.

![image](https://user-images.githubusercontent.com/2104075/87969901-5601ff80-ca99-11ea-900d-be5a86b805e1.png)

**Comment by AleksandrShepelev** [comment]
now it's working, thank you
