### ISSUE TITLE
Might Makes Right

### ISSUE THREAD

**Issue by twilliamson15** [keyteki/keyteki#141]
When MMR is played there are two issues:
1) There is no way to "not select" creatures to sacrifice. Card says "may" so I shouldn't have to select.
2) Card appears to allow selection of opponents creatures for sacrifice.

**Comment by Achocholacek** [comment]
Re: 1 - if you click "Cancel prompt" after playing Might Makes Right, that is the equivalent of "not selecting" creatures. I will bring your feedback to the team, though. perhaps there is a way we can make this more clear.

Re: 2 - This has been resolved in a recent PR.

**Comment by twilliamson15** [comment]
Cancel Prompt only shows after entering manual mode.

**Comment by Achocholacek** [comment]
You're 100% correct. My apologies. I have added in the ability to complete the action without selecting anything regardless of game mode.
