### ISSUE TITLE
Dysania doesn't count my own cards in opponent's archives

### ISSUE THREAD

**Issue by alexander-rymasheusky** [keyteki/keyteki#1432]
Turn 1: John plays Ulyq Zookeeper
Turn 2: Bill plays Troll
Turn 3: John's Ulyq Zookeeper reaps and captures Bill's Troll.
Turn 4: Bill plays Dysania

Expected: Troll is returned to Bill's discard; Bill gains 1 amber.
Actual: Troll is returned to Bill's discard; Bill gains 0 amber.

Should be a pretty simple change: in

keyteki/server/game/cards/01-Core/Dysania.js

should remove the "filter":
```
                ability.actions.gainAmber(context => ({
                    amount: context.player.opponent.archives.length
                }))
```

**Comment by romanogit** [comment]
the filter is there because the majority of cards in opponent's archive should go back to owner's hand. 
That's the case with Ulyq:

`Reap: Put an enemy creature into your archives. If that creature leaves your archives, it is put into its owner’s hand instead.`

Was Troll indeed discarded?

**Comment by SkyJedi** [comment]
Troll would go back to Bills hand.  Dysania says you get 1<A> for each card discarded, so troll doesnt meet that criteria.
![141](https://user-images.githubusercontent.com/2967416/81497850-d977c700-9286-11ea-9a40-7d619bc3990f.jpg)

**Comment by alexander-rymasheusky** [comment]
Indeed, my bad.
