### ISSUE TITLE
Teliga vs creatures with on play removals

### ISSUE THREAD

**Issue by AleksandrShepelev** [keyteki/keyteki#1433]
e.g. musthic murmook, shark, etc. I should be able to pick which effect to resolve first: teliga or played creature. 
Now prompt do not showed (I have special checkbox about simultaneous abilities turned on)

**Comment by SkyJedi** [comment]
Looks like a game engine issue.  reaction.onCardPlayed should have the same timing window as card.play

**Comment by AleksandrShepelev** [comment]
https://github.com/keyteki/keyteki/issues/1409 I guess it is the same issue
