### ISSUE TITLE
Password reset link not working

### ISSUE THREAD

**Issue by drcanak** [keyteki/keyteki#1441]
Went to login, forgot password.

1.  Went through Forget Password -> Reset Password
2. Entered email and received link to reset password
3. Got to reset screen, entered and confirmed new password, and received the following error:

" An error occured resetting your password, check the url you have entered and try again."

Have tried multiple times, reset cookies, cleared history, etc...  Clicked link in email.  Cut-n-pasted URL from email.  Always the same result.

Thank you for the wonderful implementation.  Looking forward to playing.

**Comment by dmikalova** [comment]
I'm getting the same issue.

**Comment by Stonefox87** [comment]
I'm also having this issue...
