### ISSUE TITLE
Bellowing Patrizate kept dealing damage to played creatures even though it was destroyed, possibly related to Shadow of Dis

### ISSUE THREAD

**Issue by hydrophilic-attack** [keyteki/keyteki#1455]
Unfortunately, I didn't think to get the log of the game

But it was very early on. So I can describe everything that happened. My opponent had just played Shadow of Dis. On the next turn, I played Bellowing Patrizate, some other creatures, and then sacrificed Bellowing Patrizate with Power of Fire.

Even though my patrizate was out of play, it kept dealing damage to creature that were played on subsequent turns until we gave up the game

**Comment by dlocke** [comment]
This is likely caused by #1867
