### ISSUE TITLE
Blypyp readies itself

### ISSUE THREAD

**Issue by poeticmatter** [keyteki/keyteki#1463]
Reap with Blypyp
Play a Mars creature
Blypyp readies Blypyp

techslut chooses to randomize the first player
Aurore won the flip and is first player
Aurore is playing as the Archon: Acrylicdine, Pod Padwar
techslut is playing as the Archon: Slatshell of the Moneylender’s Crad
Aurore is shuffling their deck
Aurore draws 6 card  s to their maximum of 6
techslut is shuffling their deck
techslut draws 6 card  s to their maximum of 6
Aurore draws 1 card 
Key phase - Aurore
Aurore does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Aurore
Aurore chooses mars  as their active house this turn
Main phase - Aurore
Aurore discards Phosphorus Stars
Ready phase - Aurore
Aurore readies all of their cards 
Draw phase - Aurore
End of turn 1
Aurore: 0 Æmber  (0 keys) techslut: 0 Æmber  (0 keys)
Turn 1
Key phase - techslut
techslut does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - techslut
techslut chooses shadows  as their active house this turn
Main phase - techslut
techslut plays Hock
techslut gains an Æmber  due to Hock's bonus icon
techslut plays Spike Trap
techslut gains an Æmber  due to Spike Trap's bonus icon
Ready phase - techslut
techslut readies all of their cards 
Draw phase - techslut
techslut draws 2 card  s to their maximum of 6
End of turn 1
Aurore: 0 Æmber  (0 keys) techslut: 2 Æmber  (0 keys)
Turn 2
Key phase - Aurore
Aurore does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Aurore
Aurore chooses sanctum  as their active house this turn
Main phase - Aurore
Aurore plays Whispering Reliquary
Ready phase - Aurore
Aurore readies all of their cards 
Draw phase - Aurore
Aurore draws 1 card  to their maximum of 6
End of turn 2
Aurore: 0 Æmber  (0 keys) techslut: 2 Æmber  (0 keys)
Turn 2
Key phase - techslut
techslut does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - techslut
techslut chooses logos  as their active house this turn
Main phase - techslut
techslut plays Mini Groupthink Tank
techslut plays Dr. Milli
techslut plays Hapsis
techslut plays Academy Training, attaching it to Dr. Milli
Ready phase - techslut
techslut readies all of their cards 
Draw phase - techslut
techslut draws 4 card  s to their maximum of 6
End of turn 2
Aurore: 0 Æmber  (0 keys) techslut: 2 Æmber  (0 keys)
Turn 3
Key phase - Aurore
Aurore does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Aurore
Aurore chooses sanctum  as their active house this turn
Main phase - Aurore
Aurore plays Champion Anaphiel
Aurore plays Horseman of Famine
Aurore uses Horseman of Famine to destroy Dr. Milli
Aurore uses Whispering Reliquary to return Spike Trap to their hand
Ready phase - Aurore
Aurore readies all of their cards 
Draw phase - Aurore
Aurore draws 2 card  s to their maximum of 6
End of turn 3
Aurore: 0 Æmber  (0 keys) techslut: 2 Æmber  (0 keys)
Turn 3
Key phase - techslut
techslut does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - techslut
techslut chooses shadows  as their active house this turn
Main phase - techslut
techslut plays Spike Trap
techslut gains an Æmber  due to Spike Trap's bonus icon
techslut plays Mug
techslut gains an Æmber  due to Mug's bonus icon
techslut uses Mug to move 1 Æmber  from Horseman of Famine to their pool and deal 2 damage to it
techslut plays Duskrunner, attaching it to Hapsis
Ready phase - techslut
techslut readies all of their cards 
Draw phase - techslut
techslut draws 2 card  s to their maximum of 6
End of turn 3
Aurore: 0 Æmber  (0 keys) techslut: 4 Æmber  (0 keys)
Turn 4
Key phase - Aurore
Aurore does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Aurore
Aurore chooses sanctum  as their active house this turn
Main phase - Aurore
Aurore plays The Harder They Come
Aurore uses The Harder They Come to purge Hapsis
Aurore uses Horseman of Famine to reap with Horseman of Famine
Aurore uses Horseman of Famine to destroy Mini Groupthink Tank
Aurore uses Champion Anaphiel to reap with Champion Anaphiel
Aurore uses Whispering Reliquary to return Spike Trap to their hand
Ready phase - Aurore
Aurore readies all of their cards 
Draw phase - Aurore
Aurore draws 1 card  to their maximum of 6
End of turn 4
Aurore: 2 Æmber  (0 keys) techslut: 4 Æmber  (0 keys)
Turn 4
Key phase - techslut
techslut does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - techslut
techslut chooses brobnar  as their active house this turn
Main phase - techslut
techslut plays Flamewake Shaman
techslut uses Flamewake Shaman to deal 2 damage to Horseman of Famine
techslut plays Narp
techslut plays Alaka
techslut plays Alaka
Ready phase - techslut
techslut readies all of their cards 
Draw phase - techslut
techslut draws 3 card  s to their maximum of 6
End of turn 4
Aurore: 2 Æmber  (0 keys) techslut: 4 Æmber  (0 keys)
Turn 5
Key phase - Aurore
Aurore does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - Aurore
Aurore chooses dis  as their active house this turn
Main phase - Aurore
Aurore plays Mind Barb
Aurore gains an Æmber  due to Mind Barb's bonus icon
Aurore uses Mind Barb to discard a card  at random from their hand
techslut discards Spike Trap at random
Aurore plays Restringuntus
Aurore uses Restringuntus to stop techslut from choosing brobnar  as their active house
Aurore plays Shooler
Aurore uses Shooler to steal 1 Æmber  from techslut
Aurore plays Ember Imp
Ready phase - Aurore
Aurore readies all of their cards 
Draw phase - Aurore
Aurore draws 4 card  s to their maximum of 6
End of turn 5
Aurore: 4 Æmber  (0 keys) techslut: 3 Æmber  (0 keys)
Turn 5
Key phase - techslut
techslut does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - techslut
techslut chooses shadows  as their active house this turn
Main phase - techslut
techslut plays Ronnie Wristclocks
techslut uses Ronnie Wristclocks to steal 1 Æmber  from Aurore
techslut plays Yantzee Gang
techslut discards Subtle Chain
Ready phase - techslut
techslut readies all of their cards 
Draw phase - techslut
techslut draws 4 card  s to their maximum of 6
End of turn 5
Aurore: 3 Æmber  (0 keys) techslut: 4 Æmber  (0 keys)
Turn 6
Key phase - Aurore
Aurore does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - Aurore
Aurore chooses dis  as their active house this turn
Main phase - Aurore
Aurore plays Mind Barb
Aurore gains an Æmber  due to Mind Barb's bonus icon
Aurore uses Mind Barb to discard a card  at random from their hand
techslut discards Babbling Bibliophile at random
Aurore discards Key Hammer
Aurore uses Shooler to make Shooler fight Yantzee Gang
Aurore uses Ember Imp to reap with Ember Imp
Aurore uses Restringuntus to reap with Restringuntus
Ready phase - Aurore
Aurore readies all of their cards 
Draw phase - Aurore
Aurore draws 2 card  s to their maximum of 6
 Aurore declares Check!
End of turn 6
Aurore: 6 Æmber  (0 keys) techslut: 4 Æmber  (0 keys)
Turn 6
Key phase - techslut
techslut does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - techslut
techslut chooses logos  as their active house this turn
Main phase - techslut
techslut plays Thorium Plasmate
techslut gains an Æmber  due to Thorium Plasmate's bonus icon
techslut uses Thorium Plasmate to move Restringuntus on Aurore's battleline and deal 2 damage to it for each neighbor that shares a house with it
techslut plays Titan Guardian
techslut discards Hyde
Ready phase - techslut
techslut readies all of their cards 
Draw phase - techslut
techslut draws 4 card  s to their maximum of 6
End of turn 6
Aurore: 6 Æmber  (0 keys) techslut: 5 Æmber  (0 keys)
Turn 7
Key phase - Aurore
Aurore forges the yellow key  , paying 6 Æmber 
House phase - Aurore
Aurore chooses mars  as their active house this turn
Main phase - Aurore
Aurore plays Blypyp
Aurore plays Squawker
Aurore gains an Æmber  due to Squawker's bonus icon
Aurore uses Squawker to ready Blypyp
Aurore uses Blypyp to reap with Blypyp
Aurore uses Blypyp to make the next Mars  creature played this turn enter play ready
Aurore plays Vezyma Thinkdrone
Aurore uses Blypyp to ready Blypyp
![blypyp](https://user-images.githubusercontent.com/9883537/81958725-0a555480-9617-11ea-9ac1-3d40eb9be48f.png)

**Comment by cryogen** [comment]
Thanks for the report. This was fixed in #1456 but at the time wasn't deployed to the live server. It's now deployed
