### ISSUE TITLE
Creed of Nurture and choosing Weasand

### ISSUE THREAD

**Issue by Hypyer946** [keyteki/keyteki#1464]
The opponent had a Brutodon Auxillary with 2 damage and a Shrix and Legatus on either side of the Brutodon. He popped Creed of Nurture revealing the Weasand and choosing the Brutodon.

Brutodon died and chat said it was due to it being on a flank when it really was between Shrix and Legatus.

**Comment by romanogit** [comment]
I was able to recreate and pushed a fix.
