### ISSUE TITLE
Self-Bolstering Automata not getting +2 Power when all conditions are met

### ISSUE THREAD

**Issue by skillzontoast** [keyteki/keyteki#1469]
I noticed when playing against my friend that his Self-Bolstering Automata was not gaining any power tokens even when the conditions were met. This was on Tuesday 12th May 2020 at around 21:00 BST. Decks used Krylov, Wimwych’s King vs The Banker that Coughs on Mail

**Comment by lotsamuffins** [comment]
I'm also having this issue

**Comment by HalifBakri** [comment]
Wanna bump this. Though the title is wrong...  As what the title states doesnt indicate that something is wrong.

For me Self-Bolstering Automata was not getting +2 power when all condition WERE met.

It only got +2 power when it was destroyed by the opponent but whenever it got destroyed by the controllers hand it. Was healed moved to a flank but no power counters were added.

Accidorius, Firemanor Rogue VS Imperator Morgyn Tallerbot

**Comment by Blaph** [comment]
It happened to me twice, that the Self-Bolstering Automata had upgraded attached on it and this bug triggered

**Comment by romanogit** [comment]
Fixed by https://github.com/keyteki/keyteki/pull/1323

**Comment by romanogit** [comment]
This should be fixed already. I will close and wait for report.
