### ISSUE TITLE
Mavericks need a better solution

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#147]
Deck is https://www.keyforgegame.com/deck-details/50195fac-c336-46c4-ad10-32fffd373fe5

Image is broken (yesterday it was working)

![missing-image](https://user-images.githubusercontent.com/2104075/62012249-51db2480-b15a-11e9-8444-c8910a64e165.PNG)

**Comment by Achocholacek** [comment]
All mavericks appear to be broken images as they try to load as <card name>_<maverick house>.png
FYI @cryogen

**Comment by cryogen** [comment]
Mavericks were manually generated for CotA and have not been done so for AoA.  Ideally we need a better solution for this.

**Comment by romanogit** [comment]
The deck I mentioned is a CotA deck

**Comment by romanogit** [comment]
It is weird how they managed this maverick. The card has the same number, but it has a different graphic template. The graphic template actually displays the house on the left side, with different card border colors.
The maverick images are not available online. The card is displayed as the original house when I navigate to it: https://keyforge-compendium.com/sets/1-cota/cards/217-doorstep-to-heaven
(I know you know it, just stating here for myself and general information)

**Comment by romanogit** [comment]
@cryogen : I would like to give a try and work on a maverick overlay mechanism. It would overlay the house and add the maverick icon. It would not change card graphics, though (like some card background colors).

Do you think that would be an acceptable solution?

**Comment by cryogen** [comment]
Sounds good! It’s the only thing I can think of that will work consistently

**Comment by romanogit** [comment]
I advanced development. I need to prepare some transparent images. Since
you said you created those manually, i wonder if you have maverick pngs
which I could use.
On the top left, i will prepare a set of transparent house corners to
overlay. I need to consider the fact that I cannot overlay the aember
image.

**Comment by romanogit** [comment]
I guess I am progressing. Still figuring out my way in the code:
![image](https://user-images.githubusercontent.com/2104075/62095319-70bee100-b256-11e9-8657-3c583383a6b9.png)

**Comment by cryogen** [comment]
Looks great!

**Comment by romanogit** [comment]
I was able to find a marvelous deck. We have a maverick which is also present in the native house:
https://www.keyforgegame.com/deck-details/e603c8f4-c416-4a0a-a118-2b567e6aab66

Man, this gave me a good couple of hours headache!

**Comment by romanogit** [comment]
@cryogen : can you review my approach: https://github.com/romanogit/keyteki/commit/adbf055e66a9ca2a5cf19dce939332063040766b

**Comment by cryogen** [comment]
Looks good to me!  Make sure you run a 'npm run lint' and remove the commented out code and stick up a PR!

**Comment by romanogit** [comment]
Take a look at the images I did so far:
https://github.com/romanogit/keyteki/blob/39e3706db7a6381893a633b0e726fc9a3015fe3f/public/img/maverick.png
https://github.com/romanogit/keyteki/blob/39e3706db7a6381893a633b0e726fc9a3015fe3f/public/img/maverick/maverick-corner.png

For each house we will have:
https://github.com/romanogit/keyteki/blob/39e3706db7a6381893a633b0e726fc9a3015fe3f/public/img/maverick/maverick-untamed-amber.png

https://github.com/romanogit/keyteki/blob/39e3706db7a6381893a633b0e726fc9a3015fe3f/public/img/maverick/maverick-untamed-amber.png

In the future, if we want to merge more parts, it is possible

**Comment by romanogit** [comment]
> Looks good to me! Make sure you run a 'npm run lint' and remove the commented out code and stick up a PR!

Thanks, I will complete the cleanup, images, commit and send the PR.

**Comment by romanogit** [comment]
Can we close?

**Comment by romanogit** [comment]
Deployed yesterday
