### ISSUE TITLE
Assault Kills and Peace Accord

### ISSUE THREAD

**Issue by JTLSound** [keyteki/keyteki#1473]
Assault kills leaves Peace Accord on the board erroneously. For Assault to happen, a creature first must be used to fight.

Peace Accord
Type: Artifact
Play: Each player gains 2A.
After a creature is used to fight, its controller loses 4A. Destroy Peace Accord.

I didn't get a picture in process, but here is the post game shot, with the chat scrolled up to an Assault kill. Peace Accord still on the board.
![Screen Shot 2020-05-15 at 14 09 55](https://user-images.githubusercontent.com/49758354/82087763-602d0980-96b6-11ea-91eb-32a4660636ce.jpg)

**Comment by romanogit** [comment]
Similar to #1148
