### ISSUE TITLE
Routine Job Didn't Steal 2nd Aember [Solved]

### ISSUE THREAD

**Issue by Starannosc** [keyteki/keyteki#1490]
User anxiospirate started the turn with 7 Aember.
User irisha555 played Routine Job to steal 1 Aember.
irisha555 had another Routine Job in their discard pile, therefore stealing a 2nd Aember - bringing anxiospirate down to 5 aember.

However, anxiospirate remained to have total 6 aember, allowing irisha555 to steal 6 aember when they forged a key for 6 aember due to The Sting. Anxiospirate should have only had 5 aember and not forged, the 2nd aember was not stolen with Routine Job.

![nnotation 2020-05-19 150007](https://user-images.githubusercontent.com/8732861/82287111-c087b800-99e2-11ea-81c6-d66c57cfd87a.png)

![Annotation 2020-05-19 150134](https://user-images.githubusercontent.com/8732861/82287109-bf568b00-99e2-11ea-9a27-9a8b317e0998.png)

**Comment by strib** [comment]
They had Tentacus out, and you used Seeker Needle.

**Comment by strib** [comment]
(It would be nice if the log stated when you paid an amber for Tentacus, though.)

**Comment by Starannosc** [comment]
> 
> 
> They had Tentacus out, and you used Seeker Needle.

That makes sense!

**Comment by romanogit** [comment]
I will open a ticket for the game message
