### ISSUE TITLE
They're Everywhere! Issue

### ISSUE THREAD

**Issue by KMarch82** [keyteki/keyteki#1494]
Card has consistently ignored creatures that aren't on the flank. Often times, it appears that the creatures that get missed are elusive, so I wonder if that has anything to do with it? I've included a screenshot of the last time it missed, and the log of the game up to that point.  Hope this helps, and thanks for all your work!
![They're Everywhere](https://user-images.githubusercontent.com/65614241/82348470-edc66d00-99c6-11ea-9e31-5ac56a1568c6.png)
[They're Everywhere Game Log.docx](https://github.com/keyteki/keyteki/files/4651601/They.re.Everywhere.Game.Log.docx)

**Comment by SkyJedi** [comment]
Theyre everywhere gets resolved one line at a time.  so if your flank creatures are killed in the first sentence then the non-flanks become flank and the second sentence has no targets

**Comment by KMarch82** [comment]
Interesting and unfortunate (for that card). No one had explained that to me before, and I appreciate it.
