### ISSUE TITLE
Draggable windows allow window out of bounds placement and do not force windows to be inside bounds

### ISSUE THREAD

**Issue by OptimalDuck** [keyteki/keyteki#1495]
Hi, 

I just have this problem on one of my two computers. The discarded cards window starts too high and i can't grab the top of it to move it down. Attached is a screenshot to show what I mean.

I have tried zooming in and out on my browser (Chrome) but it doesn't help. 
![Capture](https://user-images.githubusercontent.com/65626145/82373530-ec06a480-99da-11ea-81e2-a597fc2e1cb5.PNG)

**Comment by OptimalDuck** [comment]
This isn't happening anymore for me. Not sure what changed, but its working properly.

**Comment by cryogen** [comment]
I'm gonna reopen this as the ui shouldn't let you drag itself out of bounds, and if it is out of bounds at any point is should snap back, so it's still a bug!

**Comment by OptimalDuck** [comment]
In that case, i'll add a bit more info. The problem went away after I connected it to a different monitor, so that might have been what reset it. Back on the monitor that i was having problems with, it is still good. The timing might be a coincidence, but maybe there is something there.
