### ISSUE TITLE
Mass Mutation Print & Play Decks - Issues Observed

### ISSUE THREAD

**Issue by ajkukay** [keyteki/keyteki#1497]
Apologies for not having a screenshot/chat log - this is derived from notes while playing:

We noticed **Mad Prophet Gizelhart**'s Action: ability was not fully healing creatures - it was just removing one damage from them like **Cleansing Wave**.
_Mehitabel, Host of the Hustling Repository_'s **Double Doom** card uses the image from _Cyclonium, Chamber Agent_. _Mehitable_'s Double Doom does not have a bonus icon, so the image from _Cyclonium_ is confusing in its place (user thought they should capture when they don't).
**Exchange Officer** is letting users play cards from hand, but they should only be able to use Star Alliance cards in play.

Lastly, we also noticed the issue mentioned here: https://github.com/keyteki/keyteki/issues/1390

**Comment by jeremylarner** [comment]
Thanks for the report - I've submitted #1498 which fixes the bugs in Gizelhart and Exchange Officer.  The bonus icons/card image interactions are something we're still working on - some of it will depend on what data FFG make available through the API

**Comment by Kaiserchen** [comment]
Keyfrog forges for the active player

**Comment by romanogit** [comment]
@Kaiserchen , I opened a specific ticket for that #1510

**Comment by romanogit** [comment]
All the issues in this ticket are fixed
