### ISSUE TITLE
Scowly Caper doesn't have Skirmish

### ISSUE THREAD

**Issue by tobinlopes** [keyteki/keyteki#1500]
Hey folks,

I don't have the log but Scowly Caper doesn't have Skirmish.

Tobin
-tpl

**Comment by romanogit** [comment]
Cannot reproduce. Created a PR with extra test.

**Comment by romanogit** [comment]
Without the logs, it may be difficult to troubleshoot. Maybe opponent played `Shadow of Dis`?

**Comment by tobinlopes** [comment]
It happened in two separate games. SC attacked Symon and took one damage in
one game and attacked xanthax harvester and took 3 damage. In each case, I
think that Shadows was not the active house - so SC was used via his
text...maybe that's it?

Tobin
-tpl

**Comment by tobinlopes** [comment]
Here's the log of a game I just played where it was bugged. 

[SCbug_log_May22_2020.txt](https://github.com/keyteki/keyteki/files/4670136/SCbug_log_May22_2020.txt)

**Comment by romanogit** [comment]
I am able to recreate, but test cases passes.

![image](https://user-images.githubusercontent.com/2104075/82710333-051c8900-9c59-11ea-8a37-80edd14f90b2.png)

I am troubleshooting now.

**Comment by romanogit** [comment]
Submitted a PR to fix the issue.

**Comment by mcarulli** [comment]
This happened to me now, but apologies, I don't have screenshots or logs. It was between these decks:
https://decksofkeyforge.com/decks/686aa626-f84b-4364-95eb-472f890e47f8
https://decksofkeyforge.com/decks/2968c7e2-eba0-46ea-a2de-ec91434f0a8a
It was my Scowly Caper, and it occurred after Scowly Caper was under General Sherman and was returned to my opponent's control. It fought against Marshal Ewer and died despite having skirmish. no hazardous in either deck.
