### ISSUE TITLE
Self-Bolstering Automata causing infinite loop when being destroyed by Spartasaur

### ISSUE THREAD

**Issue by thatguynox** [keyteki/keyteki#1514]
Self-Bolstering Automata prevented the game state from moving forward as the Spartasaur kept seeing its destruction as a new trigger for its destruction as it is a non- dinosaur creature. 

This left the game stuck at that point with the opponent having to move the Self-Bolstering Automata to flank infinitely

**Comment by lotsamuffins** [comment]
We also had this issue

Slogans uses Neutron Shark to make Neutron Shark fight Daughter
Slogans uses Spartasaur to destroy Hapsis, Sanitation Engineer, Wormhole Technician, Reassembling Automaton, Self-Bolstering Automata, Mega Ganger Chieftain, Eyegor, Helmsman Spears, Chief Engineer Walls, Eyegor, Eyegor, Daughter, Sci. Officer Morpheus, Com. Officer Kirby, Sci. Officer Qincan, Sensor Chief Garcia, and Explo-rover
Slogans uses Hapsis to remove its ward token
Slogans uses Reassembling Automaton to heal all damage from Reassembling Automaton, exhaust it and move it to a flank
marcush92 uses Self-Bolstering Automata to heal all damage from Self-Bolstering Automata, exhaust it and move it to a flank
Slogans uses Spartasaur to destroy Hapsis, Reassembling Automaton, and Self-Bolstering Automata
Slogans uses Reassembling Automaton to heal all damage from Reassembling Automaton, exhaust it and move it to a flank
Slogans uses Spartasaur to destroy Reassembling Automaton
Slogans uses Reassembling Automaton to heal all damage from Reassembling Automaton, exhaust it and move it to a flank
Slogans uses Spartasaur to destroy Reassembling Automaton
Slogans uses Reassembling Automaton to heal all damage from Reassembling Automaton, exhaust it and move it to a flank
Slogans uses Spartasaur to destroy Reassembling Automaton
Slogans uses Reassembling Automaton to heal all damage from Reassembling Automaton, exhaust it and move it to a flank

**Comment by romanogit** [comment]
@cryogen , @jeremylarner 
I believe https://github.com/keyteki/keyteki/pull/1569 might have fixed this one as well
