### ISSUE TITLE
Moore wolf don't work together well. When I play Nature's Call and return one Wolf of fore I can't play it out. 

### ISSUE THREAD

**Issue by Dressagehorse** [keyteki/keyteki#1516]

**Comment by romanogit** [comment]
did you reach the rule of 6?

**Comment by Dressagehorse** [comment]
I played one wolf at a time. Initially I had all 4 in my hands. After reaping each time:
- played second wolf and reaped with the first
-played third and reaped with first and second
-played forth and reaped with other three
then played Nature's Call and return 2 enemy creatures and one of my Wolf

I could't play this Wolf out because it got stuck in my hand. I couldn't pick it. So I had to end my turn. Have I reached the rule of 6 or not? Thank you for your answer.

**Comment by SkyJedi** [comment]
Play, play, reap, play, reap, reap

That hits rule of six
