### ISSUE TITLE
Hidden Deck Lists for Spectators 

### ISSUE THREAD

**Issue by UltraUltraUltra** [keyteki/keyteki#1520]
It's been pointed out to me that when playing using hidden decklists, spectators in the game can see the decklist of the player at the bottom of the screen.  This means when playing a Sealed tournament if players are allowed to spectate other games when their game has ended (as they would in real life), they have the opportunity to scout a potential opponent's decklist, which is something they wouldn't be able to do in a real life tournament.

Is it possible to hide both decklists for spectators, if the game is being played with hidden deck lists?  Thank you. 

Thank you also for all the wonderful word you all on TCO.

**Comment by cryogen** [comment]
This was fixed a while ago and I forgot to attach it to this issue
