### ISSUE TITLE
Ragwarg timing is off and some play effects won't work if the creature dies on play.

### ISSUE THREAD

**Issue by Noveltyboy** [keyteki/keyteki#1527]
Ragwarg should deal 2 damage after a creature has reaped and the reap effects are resolved. It doesnt allow it atm if the creature would die.

Also noticed this happen on play effects vs things like auto cannon. I played an Urchin and it died before it stole 1 aember.

**Comment by blinkingline** [comment]
Do you have "Prompt for simultaneous abilities" checked in your profile (Go to Profile, scroll all the way to the bottom)?  If not, the platform will resolve those abilities automatically, but not necessarily always in your favor.

**Comment by Noveltyboy** [comment]
It shouldn't be simultaneous though. Ragwarg clearly says "after a creature reaps" so that means the reap should be completed, effects included. Play effects trigger when a creature is played. Cards like Autocannon and Bellowing Pat (can't spell it) say "after a creature is played". These are "after" effects and shouldn't require prompts for timing like 2 reap effects and I am pretty sure this has changed recently as they worked fine before.

**Comment by blinkingline** [comment]
Whenever two or more effects occur at the same time step on the [Timing Chart](https://archonarcana.com/Timing_Chart), the order that those effects resolve in is determined by the active player.

The [Timing Chart](https://archonarcana.com/Timing_Chart#Use_a_Creature_to_Reap) for uses to reap shows that Reap: effects and "After a Creature reaps" effects happen at the same time.  

The same is true for [Play: effects and "after a card is played" effects](https://archonarcana.com/Timing_Chart#Play_a_Card).

So again, if you want to order the abilities in question, you need to check the box in your profile.
