### ISSUE TITLE
"Titan Librarian" not refilling the hand at maximum

### ISSUE THREAD

**Issue by jorgecachoh** [keyteki/keyteki#1528]
Hi,

When I have two "Titan Librarian" in play (not in a flank) at the end of my turn I'm archiving 2 cards **but the hand is not getting refilled al full**, but only to a total of four cards (and I have not chains or any other effect that reduces my hand size)

Please find 3 screenshots:

![Screenshot_20200528-161134](https://user-images.githubusercontent.com/5285725/83153683-895e8880-a0ff-11ea-911d-95508c452822.png)

![Screenshot_20200528-161404](https://user-images.githubusercontent.com/5285725/83153677-882d5b80-a0ff-11ea-933b-95bdcb0aa5df.png)

![Screenshot_20200528-161557](https://user-images.githubusercontent.com/5285725/83153679-88c5f200-a0ff-11ea-99e8-0bc3818d35d9.png)

In case you need this is deck with the issue: https://decksofkeyforge.com/decks/b166458b-e642-4a96-b39b-3f7468cf7c60

THANKS!

     Jorge

**Comment by SkyJedi** [comment]
so the timing of end of turn works like this 
```
5) DRAW CARDS
1. Draw cards until you have six or more in your hand (adjusting for chains or card effects).
» END OF TURN EFFECTS TRIGGER.
```
You'll draw cards then Titan Librarian will trigger, so with two out you'll archive 2 and end up with 4 cards in hand.  You are drawing up to six then archiving.
![image](https://user-images.githubusercontent.com/2967416/83154676-0a009300-a0c6-11ea-9459-cac4e3815e49.png)
![image](https://user-images.githubusercontent.com/2967416/83154728-1a187280-a0c6-11ea-9a3f-ccbf3b5e4040.png)

![image](https://user-images.githubusercontent.com/2967416/83154510-d0c82300-a0c5-11ea-89cf-23587f3c34c5.png)
