### ISSUE TITLE
Volquill, Spawn of Crimsonmine - Card Missing from TCO Deck and Deck List

### ISSUE THREAD

**Issue by mediatorj** [keyteki/keyteki#1529]
My deck, Volquill, Spawn of Crimsonmine, includes two (2) Ghostform anomaly cards in Brobnar. (see https://www.keyforgegame.com/deck-details/fe274c61-71d3-46bf-99d0-ad3248a975a6)

When I import the deck to TCO, it only includes one Ghostform card. In the Deck List under the Decks tab, Brobnar is listed as having only 11 cards, not 12.
![Screenshot 2020-05-29 16 58 28](https://user-images.githubusercontent.com/66146999/83314296-9c8c5980-a1ce-11ea-8b10-9a5fc81887d3.png)

In a game, the deck list card includes only one Ghostform and appears to shift cards to fill in the gap. Brobnar includes Phalanx Strike (a Saurian card) and Saurians include Kymoor Eclipse (a Shadows card). Shadows only lists 11 cards because of the shift.  And I've confirmed that there is one card (Ghostform) missing from the played deck.
![Screenshot 2020-05-29 16 59 39](https://user-images.githubusercontent.com/66146999/83314304-a2823a80-a1ce-11ea-88f1-1a24a095e3ba.png)
![Screenshot 2020-05-29 17 04 16](https://user-images.githubusercontent.com/66146999/83314308-a57d2b00-a1ce-11ea-839f-bbba004d26fd.png)

**Comment by SkyJedi** [comment]
For giggles, can you remove the deck, import it, and check again?

**Comment by mediatorj** [comment]
I did, but I'll do it again. Thanks!

**Comment by mediatorj** [comment]
Same result.

**Comment by mediatorj** [comment]
Does anyone know why this happens to this deck? Are there other decks that have the same problem?

**Comment by cryogen** [comment]
Don't know yet, but have reproduced it

**Comment by mediatorj** [comment]
Checking in on this. Anyone close to figuring it out? Thanks!

**Comment by romanogit** [comment]
I will PR a fix for this one...

**Comment by mediatorj** [comment]
Thank you so much! I just played with it and was greatly missing the 2nd
Ghostform...

Jim
