### ISSUE TITLE
My opponent used Nexus to use my Auto Legionary artifact as it was his. However,  it played on my side. Should it play on his side? 

### ISSUE THREAD

**Issue by Dressagehorse** [keyteki/keyteki#1530]

**Comment by blinkingline** [comment]
Based on [the Unofficial FAQ from Archon Arcana](https://archonarcana.com/Auto-Legionary#Unofficial%20FAQ) Auto Legionary should simply exhaust.

**Comment by Feebssor** [comment]
Same issue with Remote Access.
I play Remote Access on an opponent's Auto-Legionary in Artifact state and it moved to my opponent battleline.
My understanding of the unofficial FAQ is that it should have just exhaust and stay Artifact
