### ISSUE TITLE
Wormhole Technician's ability not firing when reaping after playing Orator Hissaro

### ISSUE THREAD

**Issue by UltraUltraUltra** [keyteki/keyteki#1578]
I played an Orator Hissaro next to a Wormhole Technician.  I reaped with Wormhole Technician with cards still left in my deck, but the Wormhole Technician's ability did not fire.

![image](https://user-images.githubusercontent.com/55008319/84529775-f6664680-acd9-11ea-885b-cca5cc778897.png)

**Comment by romanogit** [comment]
Is there any alpha card in your deck?

**Comment by romanogit** [comment]
Opened a ticket more specific:
https://github.com/keyteki/keyteki/issues/2104
