### ISSUE TITLE
Nexus - Crystal Hive Gains 1 Aember

### ISSUE THREAD

**Issue by lotsamuffins** [keyteki/keyteki#1594]
Nexus uses Crystal Hive, gains 1 aember from reaping. As crystal hive is for the remainder of the turn and Nexus has completed the reap action, it should not gain aember for its own reap.

Swiftlogix uses Nexus to reap with Nexus
Swiftlogix uses Nexus to use Crystal Hive
Swiftlogix uses Crystal Hive to gain 1 Æmber  each time a creature reaps for the remainder of the turn
Swiftlogix uses Crystal Hive to gain 1 Æmber 
Swiftlogix uses Silvertooth to reap with Silvertooth
Swiftlogix uses Crystal Hive to gain 1 Æmber 
Swiftlogix uses Umbra to reap with Umbra
Swiftlogix uses Crystal Hive to gain 1 Æmber

**Comment by jeremylarner** [comment]
I think this is covered by the nexus/spectral tunneller ruling, which says that nexus can trigger it's new 'Draw a card' ability in the 'after reaping' window.  Crystal Hive triggers in the same window, so I think TCO is doing it correctly here.
