### ISSUE TITLE
Self-Bolstering Automata

### ISSUE THREAD

**Issue by arkhult** [keyteki/keyteki#1606]
Self-Bolstering Automata did not get a plus 2 counter when died and I had creatures on the board. It just went to a flank.

**Comment by blinkingline** [comment]
[Self-Bolstering Automata](https://archonarcana.com/Self-Bolstering_Automata#FFG_Rulings)'s **Destroyed:** ability uses the phrase "[If you do](https://archonarcana.com/If_you_do)", which means that in order for Self-Bolstering Automata to gain 2 counters it must: 
1) Fully [heal](https://archonarcana.com/Heal). If no damage is removed from the creature, it is not considered to have been “healed” for the purpose of card effects that reference healing.
2) Exhaust. If you used Self-Bolsteriing Automata to fight, it would have already been exhausted.
3) Be moved to a flank.

If all three of these conditions are not met, the counters should not be applied.

**Comment by romanogit** [comment]
We need more details to fix this one. Please, reopen if you think you met all of the above 3 conditions.
