### ISSUE TITLE
Fidget doesn't properly state what it discards

### ISSUE THREAD

**Issue by ira212** [keyteki/keyteki#1610]
Steps to Repro:
1) Player 2 gets 2+ cards in their archive.
2) Player 1 reaps with Fidget, and chooses to discard from the archive.

Notice that sometimes the name of the card in chat doesn't match the name of the card that was actually discarded. (When this happened to me, the 2nd card in the archive was actually discarded but the 1st card name was displayed).

**Comment by AleksandrShepelev** [comment]
https://github.com/keyteki/keyteki/issues/1601

related issue

using fidgit is really bugged now. murkens too

**Comment by xoque** [comment]
Here is a screenshot of this issue - I had reaped with Fidgit, and the log said it discarded Quintrino Flux, but if you look in the discard pile, it actually discorded Quadracorder.  Note - the other card in the archive was actually Quintrinio Flux.
<img width="957" alt="tcobug" src="https://user-images.githubusercontent.com/19242747/85927877-c54f4f80-b85d-11ea-936c-5abe9164b131.PNG">

**Comment by Kebay** [comment]
> the other card in the archive was actually Quintrinio Flux.

FWIW, that does not seem to be a coincidence. Or, at least, a similar situation happened in a recent game of mine: The log states the card *not* discarded from the archives.
