### ISSUE TITLE
Bug with second mimic gel

### ISSUE THREAD

**Issue by sapomapo** [keyteki/keyteki#1619]
If i have a mimic gel in play, if i play a second mimic gel it log an error and the system put the card into the cemetery.
Using the manual mode i have the same error.

**Comment by Ancamar** [comment]
same problem

**Comment by svyper** [comment]
This is a copy of #1035 however just adding extra information: happens with 2x Mimic Gel from same player and also when 1x Mimic Gel is on each side of the table...

**Comment by romanogit** [comment]
This is a dupe. Closing it and working on #1035
