### ISSUE TITLE
Spartasaur text active while in discard pile for subsequent turns

### ISSUE THREAD

**Issue by mcarulli** [keyteki/keyteki#1624]
Apologies in advance for not having images or chat log to share but thought I'd post anyway. Just played a game between these 2 decks and Spartasaur died on a turn, then the next turn another creature belonging to the same player died and spartasaur's text triggered from discard pile. It happened 2 other times on later turns in the same game, seemingly remaining active for the entirety of the game even after being in discard pile.

https://decksofkeyforge.com/decks/155454dc-fb50-43e2-b379-06427e4fc94a
https://decksofkeyforge.com/decks/a6c150cf-bea6-4efb-b224-aded359cd83c

**Comment by jeremylarner** [comment]
Do you remember if Spartasaur died while Shadow of Dis was active?  I thought I'd fixed that bug....

**Comment by mcarulli** [comment]
It is very possible, yes. I remember playing it while spartasaur was on table.

**Comment by dlocke** [comment]
This is likely caused by #1867
