### ISSUE TITLE
Exhume does not let allow you to not play the chosen creature. 

### ISSUE THREAD

**Issue by blinkingline** [keyteki/keyteki#1639]
When you play Exhume, you're forced to choose a creature in your discard pile. However, once you choose that card you should have the option to play the creature or not.  It seems that in the TCO implementation you always have to play the creature.

**Comment by romanogit** [comment]
If you choose not to play, what happens? Should it stay in discard pile?

In terms of playability, the "whole choose part" could be optional, right?

**Comment by blinkingline** [comment]
As annoying as the timing is.... the ability on the card is 
Play: Choose a creature in your discard pile. You may play that creature as if it belonged to the active house and was in your hand.

So first you should be prompted to choose a creature in your discard pile. 

Then. You should be asked:  Do you want to play this creature as if it belonged to the active house and was in your hand?

If you choose no, then nothing happens.

If you choose yes, then the creature is played as if it were played from your hand. (Meaning it would resolve play abiities, bonus icons, etc. )

**Comment by blinkingline** [comment]
If you choose not to play the card, it returns to the discard pile.
