### ISSUE TITLE
Unnatural selection destroyed opponents creature incorrectly

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#1642]
Harper won the flip and is first player
Harper is playing as the Archon: Harper “Fantasma”, Visir della Tana
romanomagacho22 is playing as the Archon: Vance, Sodomance’s Guide
 Harper has connected to the game server
 romanomagacho22 has connected to the game server
Harper is shuffling their deck
Harper draws 6 card  s to their maximum of 6
romanomagacho22 is shuffling their deck
romanomagacho22 draws 6 card  s to their maximum of 6
Harper draws 1 card 
Harper
hi
Key phase - Harper
Harper does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Harper
romanomagacho22
glhf
Harper chooses untamed  as their active house this turn
Main phase - Harper
Harper plays Dust Pixie
Harper gains an Æmber  due to Dust Pixie's bonus icon
Harper gains an Æmber  due to Dust Pixie's bonus icon
Ready phase - Harper
Harper readies all of their cards 
Draw phase - Harper
End of turn 1
Harper: 2 Æmber  (0 keys) romanomagacho22: 0 Æmber  (0 keys)
Turn 1
Key phase - romanomagacho22
romanomagacho22 does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - romanomagacho22
romanomagacho22 chooses untamed  as their active house this turn
Main phase - romanomagacho22
romanomagacho22 plays Musthic Murmook
romanomagacho22 uses Musthic Murmook to deal 4 damage to Dust Pixie
romanomagacho22 plays Harmonia
romanomagacho22 plays The Feathered Shaman
romanomagacho22 plays Imprinted Murmook
Ready phase - romanomagacho22
romanomagacho22 readies all of their cards 
Draw phase - romanomagacho22
romanomagacho22 draws 4 card  s to their maximum of 6
End of turn 1
Harper: 2 Æmber  (0 keys) romanomagacho22: 0 Æmber  (0 keys)
Turn 2
Key phase - Harper
Harper does not forge a key. They have 2 amber. The current cost is 7 Æmber 
House phase - Harper
Harper chooses brobnar  as their active house this turn
Main phase - Harper
Harper plays Gauntlet of Command
Harper plays Cannon
Harper plays Bilgum Avalanche
Ready phase - Harper
Harper readies all of their cards 
Draw phase - Harper
Harper draws 3 card  s to their maximum of 6
End of turn 2
Harper: 2 Æmber  (0 keys) romanomagacho22: 0 Æmber  (0 keys)
Turn 2
Key phase - romanomagacho22
romanomagacho22 does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - romanomagacho22
romanomagacho22 chooses untamed  as their active house this turn
Main phase - romanomagacho22
romanomagacho22 uses Musthic Murmook to make Musthic Murmook fight Bilgum Avalanche
romanomagacho22 uses The Feathered Shaman to reap with The Feathered Shaman
romanomagacho22 uses The Feathered Shaman to ward Imprinted Murmook and Harmonia
romanomagacho22 uses Harmonia to make Harmonia fight Bilgum Avalanche
romanomagacho22 uses Harmonia to remove its ward token
romanomagacho22 uses Imprinted Murmook to reap with Imprinted Murmook
Ready phase - romanomagacho22
romanomagacho22 readies all of their cards 
Draw phase - romanomagacho22
End of turn 2
Harper: 2 Æmber  (0 keys) romanomagacho22: 2 Æmber  (0 keys)
Turn 3
Key phase - Harper
Harper does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - Harper
Harper chooses shadows  as their active house this turn
Main phase - Harper
Harper plays Ring of Invisibility attaching it to The Feathered Shaman
Harper gains an Æmber  due to Ring of Invisibility's bonus icon
Harper plays Poison Wave
Harper gains an Æmber  due to Poison Wave's bonus icon
Harper uses Poison Wave to deal 2 damage to all creatures
romanomagacho22 uses Imprinted Murmook to remove its ward token
Harper plays Too Much to Protect
Harper gains an Æmber  due to Too Much to Protect's bonus icon
Harper plays Miasma
Harper gains an Æmber  due to Miasma's bonus icon
Harper uses Miasma to make romanomagacho22 skip their key step next turn
Ready phase - Harper
Harper readies all of their cards 
Draw phase - Harper
Harper draws 4 card  s to their maximum of 6
 Harper declares Check!
End of turn 3
Harper: 6 Æmber  (0 keys) romanomagacho22: 2 Æmber  (0 keys)
Turn 3
House phase - romanomagacho22
romanomagacho22 chooses staralliance  as their active house this turn
Main phase - romanomagacho22
romanomagacho22 plays Commander Chan
romanomagacho22 plays Information Officer Gray
romanomagacho22 uses Information Officer Gray to reveal Warriors’ Refrain from their hand, and archive it
romanomagacho22 plays Chief Engineer Walls
romanomagacho22 plays Commander Chan
Ready phase - romanomagacho22
romanomagacho22 readies all of their cards 
Draw phase - romanomagacho22
romanomagacho22 draws 5 card  s to their maximum of 6
End of turn 3
Harper: 6 Æmber  (0 keys) romanomagacho22: 2 Æmber  (0 keys)
Turn 4
Key phase - Harper
Harper forges the blue key  , paying 6 Æmber 
House phase - Harper
Harper chooses untamed  as their active house this turn
Main phase - Harper
Harper plays Lifeweb
Harper gains an Æmber  due to Lifeweb's bonus icon
Harper uses Lifeweb to steal 2 Æmber  from romanomagacho22
Harper plays Niffle Ape
Harper plays Dew Faerie
Harper plays Vigor
Harper gains an Æmber  due to Vigor's bonus icon
Harper uses Vigor to heal Niffle Ape for up to 3 damage
Ready phase - Harper
Harper readies all of their cards 
Draw phase - Harper
Harper draws 4 card  s to their maximum of 6
End of turn 4
Harper: 4 Æmber  (1 key) romanomagacho22: 0 Æmber  (0 keys)
Turn 4
Key phase - romanomagacho22
romanomagacho22 does not forge a key. They have 0 amber. The current cost is 5 Æmber 
House phase - romanomagacho22
romanomagacho22 chooses staralliance  as their active house this turn
Main phase - romanomagacho22
romanomagacho22 discards Red Alert
romanomagacho22 uses Chief Engineer Walls to make Chief Engineer Walls fight Dew Faerie
romanomagacho22 uses Information Officer Gray to reap with Information Officer Gray
romanomagacho22 uses Information Officer Gray to reveal Warriors’ Refrain from their hand, and archive it
romanomagacho22 uses Commander Chan to make Commander Chan fight Dew Faerie
romanomagacho22 uses Commander Chan to use Imprinted Murmook
romanomagacho22 uses Imprinted Murmook to reap with Imprinted Murmook
romanomagacho22 uses Commander Chan to reap with Commander Chan
Ready phase - romanomagacho22
romanomagacho22 readies all of their cards 
Draw phase - romanomagacho22
romanomagacho22 draws 2 card  s to their maximum of 6
End of turn 4
Harper: 4 Æmber  (1 key) romanomagacho22: 3 Æmber  (0 keys)
Turn 5
Key phase - Harper
Harper does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - Harper
Harper chooses untamed  as their active house this turn
Main phase - Harper
Harper uses Niffle Ape to reap with Niffle Ape
Harper uses Mimicry to to copy Red Alert
Harper plays Mimicry
Harper uses Mimicry to deal 4 damage to Commander Chan, Commander Chan, Imprinted Murmook, Information Officer Gray, and Chief Engineer Walls
Ready phase - Harper
Harper readies all of their cards 
Draw phase - Harper
Harper draws 1 card  to their maximum of 6
End of turn 5
Harper: 5 Æmber  (1 key) romanomagacho22: 3 Æmber  (0 keys)
Turn 5
Key phase - romanomagacho22
romanomagacho22 does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - romanomagacho22
romanomagacho22 chooses brobnar  as their active house this turn
romanomagacho22 moves all the cards  in their archives to their hand
Main phase - romanomagacho22
romanomagacho22 plays Shattered Throne
romanomagacho22 gains an Æmber  due to Shattered Throne's bonus icon
romanomagacho22 plays The Big One
romanomagacho22 gains an Æmber  due to The Big One's bonus icon
romanomagacho22 plays Warriors’ Refrain
romanomagacho22 gains an Æmber  due to Warriors’ Refrain's bonus icon
romanomagacho22 uses Warriors’ Refrain to stun Niffle Ape
romanomagacho22 plays Warriors’ Refrain
romanomagacho22 gains an Æmber  due to Warriors’ Refrain's bonus icon
romanomagacho22 uses Warriors’ Refrain to stun Niffle Ape
Ready phase - romanomagacho22
romanomagacho22 readies all of their cards 
Draw phase - romanomagacho22
romanomagacho22 draws 2 card  s to their maximum of 6
 romanomagacho22 declares Check!
End of turn 5
Harper: 5 Æmber  (1 key) romanomagacho22: 7 Æmber  (0 keys)
Turn 6
Key phase - Harper
Harper does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - Harper
Harper chooses shadows  as their active house this turn
Main phase - Harper
Harper plays Silvertooth
romanomagacho22 uses The Big One to place 1 fuse on The Big One
Harper plays Seeker Needle
Harper plays Nexus
romanomagacho22 uses The Big One to place 1 fuse on The Big One
Harper uses Silvertooth to reap with Silvertooth
Ready phase - Harper
Harper readies all of their cards 
Draw phase - Harper
Harper draws 3 card  s to their maximum of 6
 Harper declares Check!
End of turn 6
Harper: 6 Æmber  (1 key) romanomagacho22: 7 Æmber  (0 keys)
Turn 6
Key phase - romanomagacho22
romanomagacho22 forges the red key  , paying 6 Æmber 
House phase - romanomagacho22
romanomagacho22 chooses untamed  as their active house this turn
Main phase - romanomagacho22
romanomagacho22 plays Unnatural Selection
romanomagacho22 gains an Æmber  due to Unnatural Selection's bonus icon
romanomagacho22 uses Unnatural Selection to destroy Niffle Ape, Silvertooth, and Nexus
romanomagacho22 plays Bramble Lynx
romanomagacho22 uses The Big One to place 1 fuse on The Big One
romanomagacho22
what happened?
romanomagacho22
why were your creatures destroyed?
Harper
i don't konw
romanomagacho22
move them back
 Harper is attempting to switch manual mode on
 romanomagacho22 allows enabling manual mode
 Harper switches manual mode on
 Harper manually moves Nexus from their discard to their play area
 Harper manually moves Silvertooth from their discard to their play area
 Harper manually moves Niffle Ape from their discard to their play area
 Harper switches manual mode off
romanomagacho22 uses Mimicry to to copy Miasma
romanomagacho22 plays Mimicry
romanomagacho22 gains an Æmber  due to Mimicry's bonus icon
romanomagacho22 uses Mimicry to make Harper skip their key step next turn
Ready phase - romanomagacho22
romanomagacho22 readies all of their cards 
Draw phase - romanomagacho22
romanomagacho22 draws 3 card  s to their maximum of 6
End of turn 6
Harper: 6 Æmber  (1 key) romanomagacho22: 3 Æmber  (1 key)
Turn 7
House phase - Harper
Harper chooses brobnar  as their active house this turn
Main phase - Harper
Harper plays Smith
Harper gains an Æmber  due to Smith's bonus icon
Harper uses Smith to gain 2 Æmber

**Comment by jeremylarner** [comment]
Did you select nothing? Did you not have any creatures in play?

**Comment by romanogit** [comment]
I had zero creatures and opponent exactly 3. I selected their 3 creatures and they were destroyed.

**Comment by blinkingline** [comment]
Did the Big One trigger?

**Comment by romanogit** [comment]
No, I checked the card code. It is incorrect. I will work on it.

**Comment by romanogit** [comment]
No, I checked the card code. It ***seems*** incorrect. I will work on it.

I created a test case and it passes, which is weird..

**Comment by romanogit** [comment]
UTR
