### ISSUE TITLE
Problem with lateral shift during sealed game

### ISSUE THREAD

**Issue by anxiospirate** [keyteki/keyteki#1649]
Wouldn't let me play lateral shift even though I was in the correct house. Also was no way of manual mode correction as when opponent attempted to give me control of the creature that was selected from his hand, it wouldn't go to my side of the field. It was a sealed game and didn't even correctly show the anomaly symbol next to the card.

**Comment by romanogit** [comment]
This is an old issue and without the deck names and game log it is impossible to solve. Plz, reopen if you have faced the issue again.
