### ISSUE TITLE
Project Z.Y.X. fight/reap ability does not trigger

### ISSUE THREAD

**Issue by letsadapt** [keyteki/keyteki#165]
Project Z.Y.X. fight/reap ability does not trigger.

**Comment by Achocholacek** [comment]
Hey @letsadapt - do you remember what your board state was? I cannot reproduce this issue locally.

**Comment by letsadapt** [comment]
Sorry, I should have taken a screenshot. Go ahead and close and I'll
recreate ticket if I can recreate it.
