### ISSUE TITLE
Musthic Murmook + Shadow of Dis

### ISSUE THREAD

**Issue by Ugluk4242** [keyteki/keyteki#1666]
The issue happens when a Musthic Murmook dies while being affected by Shadow of Dis. The key cost increase of the Murmook then stays for the remaining of the game. 

In the game in which I recreated the game I killed 2 Musthic Murmooks after playing Shadow of Dis and the key cost was still 8 after.

[Murmook_SoD.txt](https://github.com/keyteki/keyteki/files/4907033/Murmook_SoD.txt)

![Murmook_SoD](https://user-images.githubusercontent.com/68158046/87227531-abd3fa80-c369-11ea-8be8-d0f6a7853cb0.JPG)

**Comment by Ugluk4242** [comment]
To clarify, the key cost was 6 during my turn so the SoD worked on the Murmooks but then the turn passed to my opponent, the key cost jumped back to 8 as if the Murmooks were still on the board.

**Comment by dlocke** [comment]
This is likely caused by #1867
