### ISSUE TITLE
Gorvenal didn't capture on a self fight

### ISSUE THREAD

**Issue by strib** [keyteki/keyteki#1669]
I fought with Lieutenant Gorvenal (who has a Shoulder Armor upgrade) into a Sacro-Bot, and Gorvenal did not capture.

![image](https://user-images.githubusercontent.com/8516691/87255787-a4cceb00-c442-11ea-9e45-467b75a88447.png)

Main phase - nedmike
nedmike plays Shoulder Armor attaching it to Lieutenant Gorvenal
nedmike gains an Æmber due to Shoulder Armor's bonus icon
nedmike plays The Vaultkeeper
nedmike uses Lieutenant Gorvenal to make Lieutenant Gorvenal fight Sacro-Bot
nedmike plays Cleansing Wave
nedmike uses Cleansing Wave to heal 1 damage from all creatures
Cleansing Wave heals Lieutenant Gorvenal and Sacro-Bot, gaining nedmike 2 Æmber
Ready phase - nedmike
nedmike readies all of their cards
Draw phase - nedmike
nedmike draws 3 card s to their maximum of 6
 nedmike declares Check!
End of turn 6
nedmike: 7 Æmber (0 keys) mortivas: 4 Æmber (0 keys)
Turn 6
Key phase - mortivas
mortivas does not forge a key. They have 4 amber. The current cost is 8 Æmber
House phase - mortivas
nedmike
shouldn't i have captured one there?
nedmike
from the fight?
mortivas
Yea
nedmike
we don't have to fix it, but I'll report
 mortivas is attempting to switch manual mode on
 nedmike allows enabling manual mode
 mortivas switches manual mode on
 mortivas sets Æmber to 3 ( -1 )
 nedmike adds an Æmber to Lieutenant Gorvenal
 mortivas switches manual mode off
mortivas chooses staralliance as their active house this turn

**Comment by romanogit** [comment]
I am not able to reproduce it. Maybe 'mortivas' played Shadow of Dis?

**Comment by strib** [comment]
Hmm, could be.  I remember playing against some deck that had it.  If so, sorry for wasting your time!

@mortivas do you remember if that deck of yours had it?
