### ISSUE TITLE
[MM 303] Blast Shielding always moves right.

### ISSUE THREAD

**Issue by mortivas** [keyteki/keyteki#1670]
![blast-shielding](https://user-images.githubusercontent.com/55995924/87255794-d1d9c780-c45b-11ea-8442-ccff49a2262c.png)

Blast Shielding doesn't seem to be activating properly. After using a creature with the attachment I am prompted (as expected) to select a neighboring creature to attach to. Regardless of picking either the current creature, or a neighboring creature, the upgrade always moves to the right. The expected behavior would be for the upgrade to either stay or move left/right depending on the creature selected.

Not sure if this is relevant, but I initially attached it to Explo-Rover (played as a creature).

**Comment by KMarch82** [comment]
Had the same issue in the MM dev server. I moved it several times and it always just moved to the neighbor on the right.
