### ISSUE TITLE
Harvest Time

### ISSUE THREAD

**Issue by KMarch82** [keyteki/keyteki#1671]
MM Deck. Played Harvest Time, selected "scientist" trait. There were several scientists on the board, and the card took no effect. Game log below. 

**KMarch plays Harvest Time
KMarch uses Harvest Time to purge all cards  with the trait and each player gains Æmber  equal to the number of their cards  purged
dukman
it only counts creatures "sacrificed this way"
KMarch
that didn't work either
KMarch
all scientist traits should be purged
dukman
what did you choose?
KMarch
we'll just move on
Ready phase - KMarch
KMarch readies all of their cards 
Draw phase - KMarch
KMarch draws 3 card  s to their maximum of 6
End of turn 8**

**Comment by cryogen** [comment]
Hmm, odd. The wording on the effect hasn't been like that for some time. I just tried it on the dev server and it worked fine. Can you confirm?

**Comment by romanogit** [comment]
I think it would be good to log the selected trait in the game message. It would allow better troubleshooting.

**Comment by cryogen** [comment]
It does log the trait, not sure why this bug report is from such an old version of the card
