### ISSUE TITLE
Burning Glare with an enhancement didn't do anything else

### ISSUE THREAD

**Issue by strib** [keyteki/keyteki#1672]
I played Burning Glare with a capture enhancement.  My opponent had one mutant creature (Odd Clawde) and one non-mutant (Daughter).  I got the prompt to capture, but then I got no prompts to do any stunning (and no stuns occurred).  Log below.

![image](https://user-images.githubusercontent.com/8516691/87256531-65090200-c448-11ea-89f6-a11df1930dab.png)

Main phase - Finchmaster
Finchmaster plays Mutagenic Serum
Finchmaster gains an Æmber due to Mutagenic Serum's bonus icon
Finchmaster plays Odd Clawde
Finchmaster plays Daughter
Finchmaster gains an Æmber due to Daughter's bonus icon
Ready phase - Finchmaster
Finchmaster readies all of their cards
Draw phase - Finchmaster
Finchmaster draws 5 card s to their maximum of 7
Finchmaster uses Fangtooth Cavern to destroy Relentless Creeper
End of turn 3
Finchmaster: 5 Æmber (0 keys) nedmike: 3 Æmber (0 keys)
Turn 4
Key phase - nedmike
nedmike does not forge a key. They have 3 amber. The current cost is 6 Æmber
House phase - nedmike
nedmike chooses sanctum as their active house this turn
Main phase - nedmike
nedmike plays Potion of Invulnerability
nedmike gains an Æmber due to Potion of Invulnerability's bonus icon
nedmike plays Dino-Knight
nedmike uses Dino-Knight to exalt Dino-Knight
nedmike plays General Xalvador
nedmike plays Burning Glare
nedmike gains an Æmber due to Burning Glare's bonus icon
nedmike captures an Æmber on General Xalvador due to Burning Glare's bonus icon
 Finchmaster has connected to the game server
nedmike
hmm it should have stunned, but that's ok
nedmike plays Smite
nedmike uses Smite to ready and fight with Dino-Knight
nedmike uses Dino-Knight to make Dino-Knight fight Odd Clawde

**Comment by romanogit** [comment]
Do you happen to know what was the enhancement?

**Comment by romanogit** [comment]
Just saw it, capture.

**Comment by romanogit** [comment]
This card and the choice engine were refactored. Very likely this issue is fixed. Closing. If it happens again (I have a deck with 2 of them, so I keep an eye opened), we reopen
