### ISSUE TITLE
Mass Mutation - cards not viewable when playing a game

### ISSUE THREAD

**Issue by skillzontoast** [keyteki/keyteki#1674]
The cards are not viewable. My opponent said they could see their cards but all I could see was a space where the card should be and the name of the card. I didn't take a screenshot of the game but did as a spectator where the same issue was occurring. 

<img width="1378" alt="Screen Shot 2020-07-12 at 23 30 32" src="https://user-images.githubusercontent.com/57757370/87258050-6530ee00-c498-11ea-971b-ece1ed481ad6.png">
<img width="575" alt="Screen Shot 2020-07-12 at 23 31 42" src="https://user-images.githubusercontent.com/57757370/87258054-69f5a200-c498-11ea-9126-10d8d85f8be6.png">

**Comment by cryogen** [comment]
The test server only has English cards and doesn’t save your cookies from the live server. You need to click on the top right and change your language to English :)

**Comment by skillzontoast** [comment]
Oh ok. I thought I had English language selected. If you look at the top right of the screen grab It says en-GB

**Comment by cryogen** [comment]
Yep that’s the bug. Should be en only
