### ISSUE TITLE
Deck being imported with 4 extra draw icons

### ISSUE THREAD

**Issue by agrandstudent** [keyteki/keyteki#1679]
When I import https://www.keyforgegame.com/deck-details/a4f14d3f-3175-4657-8526-a821f8baac8b into dev the page to assign enhancements is giving the deck 4 extra draw enhancements.  Dok, archon matrix, the the physical deck have 8 draw enhancements but it is importing with 12.  
![wrong_enchance_icons](https://user-images.githubusercontent.com/6394071/87258983-d8b50a00-c45c-11ea-9484-61a2be820a5c.PNG)

I've tried to reproduce with other decks that multiple surveys but I have not be able to reproduce this with another deck.

**Comment by strib** [comment]
One more example, this time with capture enhancements (TCO shows 11, when it really has 9):

https://www.keyforgegame.com/deck-details/0f58b9ce-b6d2-4a16-8fa1-19bea52fe364?powered_by=archonMatrixDiscord

![image](https://user-images.githubusercontent.com/8516691/87259957-b83c7e00-c463-11ea-9446-a9251b190dd5.png)

![image](https://user-images.githubusercontent.com/8516691/87259961-becaf580-c463-11ea-8f05-f9b631e9af11.png)
