### ISSUE TITLE
Program asks for extra damage pip enhancement that doesn't exist

### ISSUE THREAD

**Issue by DHaus1** [keyteki/keyteki#1682]
When putting enhancements on cards in deck for deck called "Nanni, Hive Skeptic," it asks me to put 4 pips of damage on cards, when in fact there are only 3 total pips of damage in the deck. The deck has 1 Mutagenesis Researcher and 2 Opposition Research cards that add a damage pip. There is no other card that enhances a damage pip. (Therefore I could not submit the deck to be verified). 
![Screen Shot 2020-07-12 at 9 05 21 PM](https://user-images.githubusercontent.com/68208633/87261643-0150fa00-c485-11ea-85fe-324b6075e0e9.png)

**Comment by OsramTaleka** [comment]
Happened with one of mine too!
https://www.keyforgegame.com/deck-details/ef9a415a-03e2-4446-a65d-ffdfbd67a3b8
"Catadown of the Survivalist’s Dungeon" looking for one extra damage pip. My two damage pips are coming from 2 Dark Minions.
