### ISSUE TITLE
Default username and password does not work

### ISSUE THREAD

**Issue by jonk5** [keyteki/keyteki#1687]
The default login credentials `admin`:`admin` doesn't seem to work. I'm running the app from `docker-compose`.

![image](https://user-images.githubusercontent.com/10610920/87320449-86a7dd80-c55d-11ea-9932-ccdc378f91f7.png)

**Comment by cryogen** [comment]
Try admin/password  :)

**Comment by jonk5** [comment]
Hi @cryogen , that didn't work too:
![image](https://user-images.githubusercontent.com/10610920/87321021-472dc100-c55e-11ea-8e76-630cec9c256c.png)
