### ISSUE TITLE
Unable to add a deck

### ISSUE THREAD

**Issue by jonk5** [keyteki/keyteki#1688]
I'm running the app using `docker-compose`.

Here's the deck URL: `https://www.keyforgegame.com/deck-details/eb1d0c11-3a36-4106-a5f2-e0a9778c0882`. I've tried different decks and they all turn up the same.

Seems to be a DB issue? Here are the logs:
![image](https://user-images.githubusercontent.com/10610920/87320760-e605ed80-c55d-11ea-8972-a0aba7815970.png)

**Comment by cryogen** [comment]
Thanks, that should be fixed now
