### ISSUE TITLE
Unable to add a deck from a previous expansion

### ISSUE THREAD

**Issue by jonk5** [keyteki/keyteki#1691]
The deck (AOA): [https://www.keyforgegame.com/deck-details/eb1d0c11-3a36-4106-a5f2-e0a9778c0882](https://www.keyforgegame.com/deck-details/eb1d0c11-3a36-4106-a5f2-e0a9778c0882)

Error message:
![image](https://user-images.githubusercontent.com/10610920/87325542-249ea680-c564-11ea-977d-b07f4360fb34.png)

Logs:
![image](https://user-images.githubusercontent.com/10610920/87325481-15b7f400-c564-11ea-9270-53659dcba2a0.png)

**Comment by romanogit** [comment]
This is a problem with your local development server, right? I suggest you try the discard channel to discuss dev environment issues.

**Comment by romanogit** [comment]
Closing. Unable to Reproduce.
