### ISSUE TITLE
Fandangle (MM-365) Readies artifacts as well as creatures

### ISSUE THREAD

**Issue by MrAwesomePossum** [keyteki/keyteki#1692]
Whenever I have used Fandangle (MM-365) it allows non-untamed artifacts to enter play ready, as far as the card states it should only be creatures (This only occurs when I have 4+ aember, which is how the card is stated to activate) When this issue has occurred in my deck, Dominator Bauble (MM-005) kept entering play ready.

**Comment by romanogit** [comment]
![image](https://user-images.githubusercontent.com/2104075/87333346-5f2c2300-c513-11ea-9d8a-1fc96ebb464e.png)
