### ISSUE TITLE
Dark Queen Gloriana (MM-397) only allows you to choose artifacts to bring back, not creatures.

### ISSUE THREAD

**Issue by MrAwesomePossum** [keyteki/keyteki#1693]
Whenever I play Dark Queen Gloriana (MM-397) the option only prompts artifacts to return to hand, not creatures.

**Comment by romanogit** [comment]
![image](https://user-images.githubusercontent.com/2104075/87333301-4facda00-c513-11ea-81c4-249db42f0c6f.png)
