### ISSUE TITLE
Drecker - undamaged after fight

### ISSUE THREAD

**Issue by unzinc** [keyteki/keyteki#1699]
Fought into Drecker's neighbour with a a creature with 6 power. Drecker received no damage after Drecker's Neighbour had went to the bin. Drecker had +4 power tokens on it with 3 damage already assigned and should have received 6 damage from the attack into Snar-ette. 

![image](https://user-images.githubusercontent.com/46981693/87342528-9fd26f00-c508-11ea-89fa-8dcad706c83e.png)

**Comment by cryogen** [comment]
Thanks for the report! Drecker is not yet implemented on the dev site :)
