### ISSUE TITLE
Lady Loreena MM

### ISSUE THREAD

**Issue by SharpeCode57** [keyteki/keyteki#1700]
Currently, she is providing the Taunt keyword to her neighbours neighbours, it should be that she is protecting her neighbours neighbours. :)

**Comment by romanogit** [comment]
Man, I implemented this card. I totally would never read the card like this.

**Comment by SharpeCode57** [comment]
Her taunt *applies* to her neighbours neighbours. She doesn't give them the Taunt keyword.

**Comment by romanogit** [comment]
I understand and I agree with you. Just bad interpretation of the card. This is the only card in KF that uses the verb "apply". Maybe a better wording `"LL's neighbors' neighbors are also protected by LL taunt"`

I will try to fix it.

**Comment by SharpeCode57** [comment]
FFG's wording on cards is always a massive problem. You guys are troopers for taking on the task of implementing them in scripts at all! Happy to help! :)
