### ISSUE TITLE
Could not return control of exiled creature

### ISSUE THREAD

**Issue by CorayThan** [keyteki/keyteki#1708]
I had a Val Jericho on my side of the battle field. I exiled her (accidentally). We turned on manual mode. I tried using "give control" but that did nothing. My opponent tried using "give control" but that did nothing. He tried moving her to his discard, but it caused her to go to my discard, and stay in play on his side of the board. At that point it became impossible to interact with the card in manual mode.

**Comment by Blaph** [comment]
Can confirm this with multiple cards. "Give control" has some issues I can't prove right now because I've no boardstamps but yes, it can accidentally ruin a game 👍
