### ISSUE TITLE
Aemberloution causes one half of gigantic creatures to be played

### ISSUE THREAD

**Issue by YOYOMilkworm** [keyteki/keyteki#1709]
Hello! _(First issue report here. I did read the notice about posting issues, but not until I had already left the game. So I don't have a chat log or screenshots. Sorry! I'll remember for next time!)_

**Potential Steps to Reproduce:**
1. Player A holds one half of a gigantic creature in hand (it was Niffle Kong when this happened)
2. Player B plays Aemberloution ( https://archonarcana.com/%C3%86mberlution )

**Expected Result:**
Player A's half of the gigantic creature remains in hand (actually, that's a rules question, but I think that's right)

**Actual Result:**
Player B chooses a flank for the half-gigantic creature and it remains on board even after Aemberloution is fully resolved.

**Comment by cryogen** [comment]
Thanks for the report. I will link this to this master issue that was just created, that covers some more cases #1886
