### ISSUE TITLE
Drecker did not steal

### ISSUE THREAD

**Issue by OsramTaleka** [keyteki/keyteki#1710]
I reaped with Drecker and it did not steal. There was a Cephaloist in play on the opponent's side but they only had 1 Aember. 
![image](https://user-images.githubusercontent.com/53394971/87416692-e9ac6b00-c583-11ea-9239-7cba9b7bd7e5.png)

**Comment by cryogen** [comment]
Thanks for the report!

Drecker is one of the 3 cards not yet implemented on the site.

I'll leave this open so that people searching won't create duplicate reports :)

**Comment by cryogen** [comment]
Drecker is now implemented :)
