### ISSUE TITLE
Lady Loreena's extended taunt is not being visually represented

### ISSUE THREAD

**Issue by agrandstudent** [keyteki/keyteki#1713]
![ladytaunt](https://user-images.githubusercontent.com/6394071/87456362-a7068500-c5bb-11ea-8401-95ea7b389260.PNG)

**Comment by cryogen** [comment]
I'm not sure how we would show this. It's not applying taunt, it's just extending the effect

**Comment by romanogit** [comment]
Weird, it seems it is still applying taunt to ng's ng?

**Comment by cryogen** [comment]
Oh hmm, didn't notice that. Weird.

**Comment by agrandstudent** [comment]
In my my mind Seeker of truth and the xeno-knight should both be pulled back to show that Lady Loreena was the current only legal target for attacks.

**Comment by romanogit** [comment]
My local server: it is working as expected

![image](https://user-images.githubusercontent.com/2104075/87461523-f3b28600-c5e4-11ea-8408-9041dd9d1adf.png)

**Comment by cryogen** [comment]
Oh I haven't done a deployment today, it's probably still on the old version

**Comment by cryogen** [comment]
The fix for this is now deployed
