### ISSUE TITLE
Artifacts entering play ready maybe due to Fandangle

### ISSUE THREAD

**Issue by agrandstudent** [keyteki/keyteki#1718]
In two separate games my artifacts were entering play ready when Fandangle was on the field and I had more than 4 aember. I dont know if this is always the case.  
In the screen shot below I played my Miasma Bomb and it entered play ready.  There was nothing in the chat to indicate why this happened.  
![ready_bomb](https://user-images.githubusercontent.com/6394071/87483440-94567500-c5e8-11ea-978a-842a14428c0f.PNG)
[ready_bomb.txt](https://github.com/keyteki/keyteki/files/4921832/ready_bomb.txt)

**Comment by romanogit** [comment]
I also fixed this one, but probably not yet deployed

**Comment by romanogit** [comment]
Deployed today
