### ISSUE TITLE
Ultra Gravitron missing it's Shield (and maybe the effect too)

### ISSUE THREAD

**Issue by tobinlopes** [keyteki/keyteki#1734]
Seen here: 

UG doesn't have the shield. I'm saw it too late to notice if the protection from the shield was working.

![image](https://user-images.githubusercontent.com/3495881/87612707-86782100-c6c8-11ea-8827-22d807a97cf2.png)

Tobin
-tpl

**Comment by romanogit** [comment]
@cryogen - its armor is null in MM.json. It should be 3.

**Comment by romanogit** [comment]
Also fixed in https://github.com/keyteki/keyteki-json-data/pull/34
