### ISSUE TITLE
Lucky dice are confusing

### ISSUE THREAD

**Issue by saluk** [keyteki/keyteki#1744]
It would be good if lucky dice would be more clear that they are in effect - or at least if when you try and do damage, you get a message as to why the damage didn't actually apply.

**Comment by romanogit** [comment]
We would need to add the reason why a damage is not taken:
- Damage not taken due to elusive
- Damage not taken due to elusive due to The Shadowsmith
- Damage not taken due to Ardent Hero
- Damage not taken due to Lucky Dice
