### ISSUE TITLE
Burning Glare log message doesn't accurately display what creature was stunned

### ISSUE THREAD

**Issue by saluk** [keyteki/keyteki#1745]
My opponent played a burning glare to stun my logos creature, but I had to look at my board to determine which creature was stunned:
<img width="281" alt="image" src="https://user-images.githubusercontent.com/54372/87717335-14a1e500-c765-11ea-93a1-2b5f7f845d6a.png">

**Comment by romanogit** [comment]
The message is being displayed twice saying it stun the target and Burning Glare, when select to target a any creature
