### ISSUE TITLE
Deck Davies, Waterrise's Celebrity has an extra angry mob

### ISSUE THREAD

**Issue by KodiakDuck** [keyteki/keyteki#1748]
Davies, Waterrise's Celebrity has an extra angry mob. It should only have 3, 2 with enhancements 1 without.

**Comment by romanogit** [comment]
Looks good to me:
![image](https://user-images.githubusercontent.com/2104075/87740224-0fba5100-c7b8-11ea-9d83-a1154f63d379.png)

Can you try delete and import again?

Do you mind submitting a screenshot?

Thank you

**Comment by romanogit** [comment]
Unable to reproduce. Please, reopen if you have more details or followed the steps above.
