### ISSUE TITLE
Soulsnatcher

### ISSUE THREAD

**Issue by Herzbube76** [keyteki/keyteki#175]
Doesnt work at all?!

**Comment by Achocholacek** [comment]
@Herzbube76 - do you remember the board state when it didn't work? I cannot recreate this issue locally, nor can I recreate it on the live server - everything appears to be working as expected

**Comment by tgreaves** [comment]
There aren't any tests around this card yet.  I'll add some.

**Comment by tgreaves** [comment]
I've put some basic tests around this Artifact and it is working as expected in those.

Will need to see full details (including a log) in order to investigate this one any further.
