### ISSUE TITLE
Is there plan to add korean language?

### ISSUE THREAD

**Issue by wonkh11** [keyteki/keyteki#1754]
As release of Mass Mutation, Korea was added as new language in keyforge and lot of players are now looking forward to play in online. Is there any plans on adding Korean language in Crucible online?

I saw your awsome works on Crucible online and hope to play in korean cards too.

**Comment by romanogit** [comment]
Yes, there is a plan. We are working on that.

**Comment by wonkh11** [comment]
oh its a good news!! thanks for your effort!

I also worked on translating your locale json in to korean and write on Txt file.

https://drive.google.com/file/d/1dM5nRW1D_9dcC5tCElhoiwVZC0lywuRh/view?usp=sharing

I hope this helps your work

thanks!

**Comment by romanogit** [comment]
Can you attach the file here. I do not have access to it.

**Comment by wonkh11** [comment]
https://drive.google.com/file/d/1dM5nRW1D_9dcC5tCElhoiwVZC0lywuRh/view?usp=sharing

sorry i changed authority of link.

[korea.txt](https://github.com/keyteki/keyteki/files/4938659/korea.txt)

here is file too
