### ISSUE TITLE
Unenhanced Gloriana's Attendant shows bonus capture

### ISSUE THREAD

**Issue by Apopcalyptic** [keyteki/keyteki#1755]
Gloriana's Attendant shows a capture icon in the card art; all three in this deck are unenhanced, and in play they haven't tried to capture - I will try to reproduce with another deck in a moment. 
![gloriana](https://user-images.githubusercontent.com/68425023/87777939-50e74b00-c822-11ea-9952-e56815b8a22b.jpg)

//edit - Reproduced with Monsieur A. Greybait - Also showing the capture icon. I note that Mushroom With a View shows aember/draw bonus icons too! Still implementing the art from the print and play decks?
![mushroom](https://user-images.githubusercontent.com/68425023/87778293-e256bd00-c822-11ea-999a-91dd2c0c1b19.jpg)

**Comment by SteVader** [comment]
Cards that were previously in the print and play decks are having their art displayed from those early decks rather than the base FFG images.

**Comment by SteVader** [comment]
Full list of cards that will need to be replaced:

- [ ] 002 - Bonesaw
- [ ] 004 - Dark Minion
- [ ] 007 - Gateway to Dis
- [ ] 008 - Imp-losion
- [ ] 009 - Impspector
- [ ] 013 - Sinder
- [ ] 014 - Snarette
- [ ] 015 - Stirring Grave
- [ ] 015 - StirringGrave
- [ ] 017 - Waking Nightmare
- [ ] 019 - Break-key
- [ ] 020 - Double Doom
- [ ] 021 - Essence Scale
- [ ] 034 - Dance of Doom
- [ ] 053 - Desire
- [ ] 056 - Envy
- [ ] 060 - Pride
- [ ] 063 - Umbra-Fiend Sanctum
- [ ] 064 - WrathLogos
- [ ] 067 - Bot Bookton
- [ ] 068 - Dæmo-Bot
- [ ] 070 - DiametricCharge
- [ ] 071 - Eclectic Inquiry
- [ ] 072 - Effervescent Principle
- [ ] 075 - Lethologica
- [ ] 076 - Munchling
- [ ] 077 - OppositionResearch
- [ ] 078 - Q-Mechs
- [ ] 080 - Standardized Testing
- [ ] 080 - StandardizedTesting
- [ ] 084 - Chronus
- [ ] 085 - Dimension Door
- [ ] 091 - Mutagenic Serum
- [ ] 092 - Neuro Syphon
- [ ] 093 - Novu Dynamo
- [ ] 102 - Cyber-Clone
- [ ] 107 - Mind Over Matter
- [ ] 107 - Mind Over Matter Saurian
- [ ] 112 - Skippy Timehog
- [ ] 117 - It’sComing...
- [ ] 123 - Umbra-BotShadows
- [ ] 127 - Bull-wark
- [ ] 129 - Champion Anaphiel
- [ ] 129 - ChampionAnaphiel
- [ ] 130 - Cleansing Wave
- [ ] 131 - Commandeer
- [ ] 133 - Fangs of Gizelhart
- [ ] 134 - Font of the Eye
- [ ] 135 - General Xalvador
- [ ] 136 - Gizelhart’s Zealot
- [ ] 138 - SeekerofTruth
- [ ] 140 - Squire Alys
- [ ] 140 - SquireAlys
- [ ] 145 - Barrister Joya
- [ ] 151 - Gorm of Omm
- [ ] 155 - Scrivener Favian
- [ ] 156 - Shoulder Armor
- [ ] 157 - The Spirit’s Way
- [ ] 167 - Mad Prophet GizelhartSaurian
- [ ] 183 - Axiom of Grisk
- [ ] 187 - Consul Primus
- [ ] 192 - Faust the Great
- [ ] 192 - FausttheGreat
- [ ] 193 - Galeatops
- [ ] 197 - Spoils of Battle
- [ ] 207 - Hedonistic Intent
- [ ] 207 - Hedonistic Intent
- [ ] 208 - Humble
- [ ] 210 - Saurian Egg
- [ ] 213 - Stomp
- [ ] 214 - Terrordactyl
- [ ] 215 - AmphoraCaptura
- [ ] 220 - Good of the Many
- [ ] 235 - Lyco-Saurus
- [ ] 238 - Monument to Primus
- [ ] 240 - Sacro-SaurusUntamed
- [ ] 241 - Techno-Saurus
- [ ] 244 - Deusillus
- [ ] 244 - Deusillus2
- [ ] 247 - Dark Wave
- [ ] 250 - Look Over There!
- [ ] 255 - Rad Penny
- [ ] 258 - Subtle Otto
- [ ] 259 - Tempting Offer
- [ ] 269 - Miasma Bomb
- [ ] 273 - Reckless Rizzo
- [ ] 274 - Safe House
- [ ] 287 - Mole
- [ ] 298 - Lyco-Thief
- [ ] 302 - Access Denied
- [ ] 303 - Blast Shielding
- [ ] 304 - Commander Chan
- [ ] 311 - Scout Pete
- [ ] 312 - Securi-Droid
- [ ] 313 - Sensor Chief Garcia
- [ ] 314 - Subdue
- [ ] 315 - Subject Kirby
- [ ] 316 - Survey
- [ ] 316 - Survey
- [ ] 317 - Teleporter Chief Tink
- [ ] 318 - ANT1-10NY
- [ ] 320 - Away Team
- [ ] 325 - Mutagenesis Researcher
- [ ] 327 - Particle Sweep
- [ ] 328 - Quintrino Flux
- [ ] 330 - Stunner
- [ ] 333 - Xenotraining
- [ ] 340 - EnsignEl-Samra
- [ ] 341 - ExchangeOfficer
- [ ] 349 - Matter Maker
- [ ] 351 - QuixxleStone
- [ ] 366 - Floomf
- [ ] 368 - Gloriana’s Attendant
- [ ] 369 - Keyfrog
- [ ] 374 - Reclaimed by Nature
- [ ] 375 - Resurgence
- [ ] 376 - Savage Clash
- [ ] 386 - Mushroom with a View
- [ ] 392 - Wild Bounty
- [ ] 403 - Mercy, Malkin Queen
- [ ] 411 - Word of Returning

**Comment by SteVader** [comment]
bonesaw
dark-minion
gateway-to-dis
imp-losion
impspector
sinder
snarette
stirring-grave
waking-nightmare
break-key
double-doom
essence-scale
dance-of-doom
desire
envy
pride
umbra-fiend
wrath
bot-bookton
dæmo-bot
diametric-charge
eclectic-inquiry
effervescent-principle
lethologica
munchling
opposition-research
q-mechs
standardized-testing
chronus
dimension-door
mutagenic-serum
neuro-syphon
novu-dynamo
cyber-clone
mind-over-matter
skippy-timehog
it-scoming
umbra-bot
bull-wark
champion-anaphiel
cleansing-wave
commandeer
fangs-of-gizelhart
font-of-the-eye
general-xalvador
gizelhart-s-zealot
seekeroftruth
squire-alys
squirealys
barrister-joya
gorm-of-omm
scrivener-favian
shoulder-armor
the-spirit-s-way
mad-prophet-gizelhart
axiom-of-grisk
consul-primus
faust-the-great
galeatops
spoils-of-battle
hedonistic-intent
humble
saurian-egg
stomp
terrordactyl
amphora-captura
good-of-the-many
lyco-saurus
monument-to-primus
sacro-saurus
techno-saurus
deusillus
deusillus2
dark-wave
look-over-there!
rad-penny
subtle-otto
tempting-offer
miasma-bomb
reckless-rizzo
safe-house
mole
lyco-thief
access-denied
blast-shielding
commander-chan
scout-pete
securi-droid
sensor-chief-garcia
subdue
subject-kirby
survey
teleporter-chief-tink
ant1-10ny
away-team
mutagenesis-researcher
particle-sweep
quintrino-flux
stunner
xenotraining
ensignel-samra
exchange-officer
matter-maker
quixxle-stone
floomf
gloriana-s-attendant
keyfrog
reclaimed-by-nature
resurgence
savage-clash
mushroom-with-a-view
wild-bounty
mercy-malkin-queen
word-of-returning

**Comment by cryogen** [comment]
These were indeed the print and play images. I've now redownloaded them

Thanks!
