### ISSUE TITLE
Wrong enhancements showing on cards

### ISSUE THREAD

**Issue by thestripyjumper** [keyteki/keyteki#1759]
*This is pretty minor but could cause some confusion*

My deck has two damage enhancements showing on cards that should not be there. They don't get enacted by the game - they just appear on the card images (across a number of languages).

Username: thestripyjumper
Deck name: Bladewagon, the Master Outlaw

![crucible 1 (2)](https://user-images.githubusercontent.com/68428631/87786545-01a91680-c832-11ea-89fa-d06da5719d42.png)
![crucible 2 (2)](https://user-images.githubusercontent.com/68428631/87786549-02da4380-c832-11ea-8ae1-e9d5babe04f8.png)

**Comment by SteVader** [comment]
This is fixed in #1755 If you hold down shift whilst reloading the page you'll see the corrected card images.

**Comment by thestripyjumper** [comment]
Thanks!
