### ISSUE TITLE
Rad penny y Yxilo Bolter

### ISSUE THREAD

**Issue by Landros83** [keyteki/keyteki#1760]
Acabo de jugar una partida en la cual, al usar la accion de LUCHAR del Yxilo Bolter sobre una Rad Penny, esta se ha ido a la pila de purgar, cuando deberia irse de vuelta al deck por haber saltado su DESTRUIDO.
Saludos y espero que lo solucionen pronto

**Comment by romanogit** [comment]
Fixed by https://github.com/keyteki/keyteki/pull/1784
