### ISSUE TITLE
Can save deck with all my enhancements on one card

### ISSUE THREAD

**Issue by Adzebad** [keyteki/keyteki#1761]
I have managed to save my deck with all my enhancements loaded onto one card, leaving the rest of my enhanced cards without the proper enhancements.
First, I assign all my enhancements regularly, making sure I have given each card the proper enhancements.
![Enhancements as they should be](https://user-images.githubusercontent.com/68355319/87790444-78491280-c838-11ea-9197-234cf5598910.jpg)

Then I remove all those enhancements and pile them onto one card. Once I have done this, the deck can be saved like usual. 
![Enhancements as they can be saved](https://user-images.githubusercontent.com/68355319/87790525-957de100-c838-11ea-9926-598fdcda8c0e.jpg)

If i have placed more than 5 enhancements on a card, the Image doesn't load up at all. So I went back, went through the process again, and put my damage enhancements on one card, then the rest of them on another, and again was able to save the deck like normal.
![Saved deck with 5 enhancements on one card](https://user-images.githubusercontent.com/68355319/87790656-d544c880-c838-11ea-9a7d-ee972483b44a.jpg)

**Comment by romanogit** [comment]
@cryogen ,
I believe you fixed this one, right?

**Comment by romanogit** [comment]
I believe this is already fixed :)
