### ISSUE TITLE
Import API Error

### ISSUE THREAD

**Issue by tobinlopes** [keyteki/keyteki#1764]
Hey folks,

Been loading decks I loaded to dev server onto main server and I'm hitting an error message with each deck. After multiple attempts it's gone through...but sometimes it takes 3-5 tries. 

See the video here for details: https://drive.google.com/file/d/1fnsPXoQijHNIhdQphsKoKndjWMICS1CB/view?usp=drivesdk

Tobin
-tpl

**Comment by SteVader** [comment]
Due to lots of people importing their new decks after MM was made live this morning, the TCO site is likely being throttled by the FFG APIs and this is why the error message only appears intermittently. It's just a case of being patient until the volume of deck import traffic dies down.

**Comment by cryogen** [comment]
What @SteVader said!  Just keep trying, but not too often as that will just make the problem worse. Usually waiting a couple of minutes will help
