### ISSUE TITLE
Niffle Kong Bugs

### ISSUE THREAD

**Issue by Uchti2** [keyteki/keyteki#1765]
Hey, this should be a simple one:

-  Niffle Kong currently cant chose any friendly creatures to deal damage to with his ability.

-  Niffle Kong currently has 0 Armor instead of 2.

**Comment by romanogit** [comment]
2 is fixed, probaly not deployed yet

**Comment by romanogit** [comment]
> Niffle Kong currently cant chose any friendly creatures to deal damage to with his ability.

What is wrong with this behavior?

![image](https://user-images.githubusercontent.com/2104075/87805758-429e2c80-c82c-11ea-9d98-eaa5f58fd9c6.png)

**Comment by Uchti2** [comment]
You should be able to do 3 dmg to your own creature if you chose. And if the opponent has no creatures you have to chose your own!

Currently the ability only lets you damage an opponent creature.
