### ISSUE TITLE
Novu Dynamo did not gain me an Aember

### ISSUE THREAD

**Issue by charzendat** [keyteki/keyteki#1766]
I was on 5 aember at the start of my turn with Novu Dynamo in play. I discarded a Logos card from my hand but did not gain an aember.

Round Log:
End of turn 6
maxbraavos: 1 Æmber  (1 key) **Charzendat: 5 Æmber**  (1 key)

Turn 6
Key phase - maxbraavos
maxbraavos does not forge a key. They have 1 amber. The current cost is 8 Æmber 
House phase - maxbraavos
maxbraavos chooses staralliance  as their active house this turn
Main phase - maxbraavos
maxbraavos plays Securi-Droid attaching it to Finch Cloak
maxbraavos plays Scout Pete
Choose to keep or discard top of deck.
maxbraavos discards Peace Accord
Ready phase - maxbraavos
maxbraavos readies all of their cards 
Draw phase - maxbraavos
maxbraavos draws 3 card  s to their maximum of 6
End of turn 6

maxbraavos: 1 Æmber  (1 key) Charzendat: 5 Æmber  (1 key)

Turn 7
**Charzendat uses Novu Dynamo to do several things**
Key phase - Charzendat
**Charzendat does not forge a key. They have 5 amber**. The current cost is 6 Æmber

**Comment by Apopcalyptic** [comment]
We've noticed that The Sting seems to skip over Novu Dynamo's timing trigger. Are they clashing timing points?

**Comment by benjamintownsend** [comment]
Additional:

This has reoccured in several games now, not just when I am meant to forge a key.

Also, in one game my opponent used a Misama Bomb on their turn (Action: Destroy Miasma Bomb, your opponent skips the "Forge a Key" step during their next turn). Novu Dynamo didn't trigger at all (I wasn't prompted to discard a card or destroy Novu). Novu triggers at the start of my turn (before forging a key), so skipping the Forge A Key step should not effect this.

**Comment by CalumSLZ** [comment]
Yeah this just generally seems to be problem with Novu Dynamo, but possibly with Auto-Encoder?

<img width="1275" alt="Screenshot 2020-07-18 at 13 52 52" src="https://user-images.githubusercontent.com/53399502/87852116-76965200-c8ff-11ea-847a-0b553d0da7fc.png">

**Comment by Apopcalyptic** [comment]
> Additional:
> 
> This has reoccured in several games now, not just when I am meant to forge a key.
> 
> Also, in one game my opponent used a Misama Bomb on their turn (Action: Destroy Miasma Bomb, your opponent skips the "Forge a Key" step during their next turn). Novu Dynamo didn't trigger at all (I wasn't prompted to discard a card or destroy Novu). Novu triggers at the start of my turn (before forging a key), so skipping the Forge A Key step should not effect this.

The 'start of turn" timing point is within the Forge a Key step, skipped by Miasma, Miasma Bomb and The Sting.

**Comment by cryogen** [comment]
> > Additional:
> > This has reoccured in several games now, not just when I am meant to forge a key.
> > Also, in one game my opponent used a Misama Bomb on their turn (Action: Destroy Miasma Bomb, your opponent skips the "Forge a Key" step during their next turn). Novu Dynamo didn't trigger at all (I wasn't prompted to discard a card or destroy Novu). Novu triggers at the start of my turn (before forging a key), so skipping the Forge A Key step should not effect this.
> 
> The 'start of turn" timing point is within the Forge a Key step, skipped by Miasma, Miasma Bomb and The Sting.

Actually this changed in the latest FAQ, we just haven't updated it on TCO yet

**Comment by benjamintownsend** [comment]
Actually I think Apocalyptic is right. According to the rules the "Start of Turn" step is within the "Forge a Key" step. As the whole step is skipped then the active player doesn't get the option to discard a card for aember.

![StartOfTurn](https://user-images.githubusercontent.com/19664640/87853878-bd874600-c905-11ea-8626-20836ae98318.png)

Next question is though, does Novu get destroyed? It's text reads:
**At the start of your turn, you may discard a Logos card from your hand or archives. If you do, gain 1Enhance aember.png. Otherwise, destroy Novu Dynamo.**

I think not. It gets destroyed if I do not discard a logos card at the start of my turn. But the start of my turn never happened so it should remain.

**Comment by cryogen** [comment]
That's the old timing chart.

This is the new one: 
![image](https://user-images.githubusercontent.com/1053365/87853947-28d11800-c906-11ea-87f3-8a823c946113.png)

**Comment by benjamintownsend** [comment]
:D That was from the rulebook I got from the official website

**Comment by cryogen** [comment]
![image](https://user-images.githubusercontent.com/1053365/87854032-a1d06f80-c906-11ea-9903-7d71f1f1ec4b.png)

There's a new one for MM :)

**Comment by lotsamuffins** [comment]
There's another issue with this - Novu Dynamo's aember bonus doesn't seem to trigger after the first instance.

Instance 1:
End of turn 5
Seb-112: 8 Æmber  (0 keys) Charzendat: 1 Æmber  (0 keys)
Turn 6
Charzendat uses Novu Dynamo to do several things
Key phase - Charzendat
Charzendat does not forge a key. They have 2 amber. The current cost is 6 Æmber 

Instance 2:
End of turn 6
Seb-112: 7 Æmber  (0 keys) Charzendat: 5 Æmber  (0 keys)
Turn 7
Charzendat uses Novu Dynamo to do several things
Key phase - Charzendat
Charzendat does not forge a key. They have 5 amber. The current cost is 6 Æmber

**Comment by Philingero** [comment]
Experienced it today. I had Novu for 3 turns and was able to discard 3 logos cards during those turns but didnt gain an amber. One of those times, i was at 5 amber and the gain would have forged me a key.

![image](https://user-images.githubusercontent.com/57675229/89170118-c8063880-d5b1-11ea-93c5-382c148e8dd9.png)
