### ISSUE TITLE
Opportunist missing capture

### ISSUE THREAD

**Issue by Balurdo** [keyteki/keyteki#1769]
Hello guys, its my first post here, so if I'm doing something wrong, please forgive me.

During a match today, I face a situation that I played the shadow card Opportunist in my Lyco-Thief and I missing the captured aember.

Could you check if something is wrong with this card?

Below, I'll give you the evidences I collected for.
Text:
End of turn 11
Leyto1391: 2 Æmber  (1 key) balurdo: 7 Æmber  (0 keys)
Turn 11
Key phase - balurdo
balurdo does not forge a key. They have 7 amber. The current cost is 9 Æmber 
House phase - balurdo
balurdo chooses shadows  as their active house this turn
Main phase - balurdo
balurdo plays Rad Penny
balurdo captures an Æmber  on Dino-Knight due to Rad Penny's bonus icon
balurdo uses Rad Penny to steal 1 Æmber  from Leyto1391
balurdo plays Opportunist attaching it to Lyco-Thief
balurdo gains an Æmber  due to Opportunist's bonus icon
balurdo uses Lyco-Thief to make Lyco-Thief fight Niffle Ape
balurdo uses Gamgee to reap with Gamgee
Print:
![image](https://user-images.githubusercontent.com/65313454/87810369-45505000-c833-11ea-90ad-026ad227124e.png)

Cheers,

**Comment by tobinlopes** [comment]
Your turn started with your Opponent having 2 aember, you played Rad Penny to steal one and capture one (bonus icon) leaving your opponent with 0. So, when you played Opportunist there was not aember to capture.

Tobin
-tpl
