### ISSUE TITLE
(Logos) - Wild Wormhole did not played top card

### ISSUE THREAD

**Issue by MoonWalker0** [keyteki/keyteki#177]
I encountered an situation when Wild Wormhole did not played any card - only 1 AEmber was granted. I have taken a screenshot:
![bug](https://user-images.githubusercontent.com/32847809/62063399-10ff1080-b22b-11e9-9189-3d338468f214.png)

**Comment by Achocholacek** [comment]
Wild Wormhole does work as expected, but this is the behaviour when it would normally play an alpha card. Needs a fix.

**Comment by Achocholacek** [comment]
Related to an internal bug.

**Comment by skrohmagnon** [comment]
maybe seeing the card you can't play could be a good thing (as in real life, you have to see the card to know you can't play it). I have the same problem with an upgrade and no creature on board.

**Comment by cryogen** [comment]
That's how it's implemented, it's just not working.
