### ISSUE TITLE
Delete functionality in 'my decks' is broken 

### ISSUE THREAD

**Issue by Apopcalyptic** [keyteki/keyteki#1773]
Delete a deck in 'my decks' prompts for confirmation, but clicking confirm doesn't actually commit the delete. 

Tested with several decks.

**Comment by cryogen** [comment]
I can't reproduce this, are you still having the same issue?

**Comment by Apopcalyptic** [comment]
Yeah, I've just tried again. The confirmation populates as "Delete and confirm". Clicking delete fails the delete!

All seems sorted, just UI weirdness!

**Comment by cryogen** [comment]
Excellent, thanks for confirming
