### ISSUE TITLE
Ghosthawk - Crewman Jorg

### ISSUE THREAD

**Issue by 7razcal7** [keyteki/keyteki#1780]
Ghosthawk enables the neighboring creature to reap, yet playing it next to Crewman Jorg allows CJ to use his action.

**Comment by Tutenkharnage** [comment]
I experienced a similar issue when my opponent played Ghosthawk between Gladiodontus and another card. According to my opponent, after he chose Gladiodontus and reaped, Gladiodontus readied and became enraged, at which point he was allowed to select it again. When he did, Gladiodontus reaped despite being enraged, and he was not allowed to choose the other neighbor.

**Relevant portion of game log:**

Main phase - stakoverflo-MM
stakoverflo-MM plays Ghosthawk
stakoverflo-MM uses Ghosthawk to reap with each of its neighbors in turn
stakoverflo-MM uses Gladiodontus to reap with Gladiodontus
stakoverflo-MM uses Gladiodontus to ready Gladiodontus
stakoverflo-MM uses Gladiodontus to reap with Gladiodontus

**Opponent's deck:**

https://www.keyforgegame.com/deck-details/3e8e0a1d-a968-40da-ac94-bd06c56e616a
https://decksofkeyforge.com/decks/3e8e0a1d-a968-40da-ac94-bd06c56e616a

**Comment by romanogit** [comment]
Two different problems Gladiodontus is reproduceable, but CJ is not. I will open a case just for Gladiodontus

**Comment by romanogit** [comment]
@7razcal7 ,
please, reopen the case with more details. I am unable to reproduce the issue.
