### ISSUE TITLE
Gloriana's Attendant not Capture amber bonus icon

### ISSUE THREAD

**Issue by Carle92** [keyteki/keyteki#1786]
Gloriana's Attendant don't capture amber with is enhance bonus icon

**Comment by Apopcalyptic** [comment]
Clear your image cache - you're probably seeing the print and play deck image, which were updated yesterday.

**Comment by cryogen** [comment]
As @Apopcalyptic says this is a caching issue, the card doesn't always come with that enhancement, clear your image cache and it should be less confusing :)
