### ISSUE TITLE
can't log into games or host - please help

### ISSUE THREAD

**Issue by dvntshaku** [keyteki/keyteki#1790]
Hi,

Am trying to host a game, but each time I start a game my account gets disconnected. I cannot join people's games. It says my account is "waiting for ping". Any advice on how to proceed?

Thanks everyone,
dvntshaku
<img width="1277" alt="Screen Shot 2020-07-18 at 13 34 19" src="https://user-images.githubusercontent.com/68477383/87858398-9a579900-c8fb-11ea-92aa-7c7261823bb8.png">

**Comment by cryogen** [comment]
The disconnected here is referring to the fact you haven't connected to the game server yet as you've not started the game. So you're fine to continue, I'll leave this issue open as a reminder that I need to make that clearer.

Also, waiting for ping just means you've not had a response yet, it can take a couple of minutes to show up

**Comment by dvntshaku** [comment]
Hi,

Thanks for your response. I started a game, copied said game's link, sent to a friend to try and start. They said that when they opened the link the game was "not found.' I also cannot watch other people's games on TCO. I have restarted the web browser, used a different browser, and restarted computer. Do you have any other suggestions on how I might proceed?

Thanks,
Devon

**Comment by cryogen** [comment]
Can you open the browser console (f12 on most browsers) and paste any errors you find in there?

**Comment by SkyJedi** [comment]
Is this still an issue for you @dvntshaku?
