### ISSUE TITLE
Vandalize doesn't distinguish between identically named cards when one is enhanced

### ISSUE THREAD

**Issue by Tutenkharnage** [keyteki/keyteki#1791]
I was playing a game against a friend of mine when I played Vandalize. I drew two copies of Securi-Droid and another card, whose name isn't important. The list of cards was presented to me like this:

Securi-Droid (2)
Other card

According to my playing partner, one of his four copies of Securi-Droid is enhanced, and since the two that were on the board were _not_ enhanced, one of the two drawn by Vandalized should have been, yet they weren't presented as separate cards.

My opponent's deck was Bao, District Thegn.

https://www.keyforgegame.com/deck-details/76d60cc8-73ea-4351-b34b-8030ae19f65b
https://decksofkeyforge.com/decks/76d60cc8-73ea-4351-b34b-8030ae19f65b

**Comment by romanogit** [comment]
Interesting. I was working on this prompt the other day and was asking myself if grouping was useful or more confusing. Looks like, it is better not to group now. I will check it later today.
