### ISSUE TITLE
Dark Wave ignores Ultra Gravitron's armor

### ISSUE THREAD

**Issue by roeswood** [keyteki/keyteki#1792]
Second time I've noticed this exact interaction, but I got a screenshot this time. Opponent played Dark Wave, and my Ultra Gravitron took 2 damage, when the 3 Armor should have prevented it. 
![TCOscreenshot](https://user-images.githubusercontent.com/8070356/87859675-282f8600-c8f4-11ea-9553-c8a41924dd56.png)

**Comment by romanogit** [comment]
@cryogen : still seems UG has no armor :(

**Comment by cryogen** [comment]
Redis: ```
,"ultra-gravitron":{"id":"ultra
-gravitron","name":"Ultra Gravitron","number":"125","image":"https://cdn.keyforg
egame.com/media/card_front/en/479_125_4QHXWXFGJ5MQ_en.png","expansion":479,"hous
e":"logos","keywords":[],"traits":["robot"],"type":"creature","rarity":"Rare","a
mber":0,"armor":3,"power":10,"text":"(Play only with the other half of Ultra Gravitron.)\r\nPlay: Archive the top 5 cards of your deck.\r\nFight/Reap: Discard a
 card from your archives. If you do, purge a creature and resolve each of its bo
nus icons as if you had played it."
```

Database:
```
keyteki=# SELECT "Armor" FROM "Cards" WHERE "CardId" = 'ultra-gravitron';
 Armor
-------
     3
(1 row)
```

Either this is something else or this issue was filed before it was fixed in the data

**Comment by romanogit** [comment]
@cryogen 
Can you try:
```
SELECT "Armor" FROM "Cards" WHERE "CardId" = 'ultra-gravitron2';
```

MM.json is not correct.

**Comment by cryogen** [comment]
This should be fixed in the db now. There's some work to fix the json but that can wait
