### ISSUE TITLE
Drecker not taking neighbor's damage

### ISSUE THREAD

**Issue by tobinlopes** [keyteki/keyteki#1793]
As it says, Drecker isn't taking damage. This is on the full site, not the dev site.

[PainMail_and_Drecker.txt](https://github.com/keyteki/keyteki/files/4942840/PainMail_and_Drecker.txt)

Tobin
-tpl

**Comment by codykraz** [comment]
I think it's when the neighbor dies it doesn't receive the damage correctly

**Comment by AleksandrShepelev** [comment]
+1, drecker don't take damage if neighbor die. Otherwise it get damage
