### ISSUE TITLE
Painmail not working when opponent calls Dis

### ISSUE THREAD

**Issue by tobinlopes** [keyteki/keyteki#1794]
My opponent played Pain Mail on my Dis creature. I called Dis the next turn and Painmail didn't activate at all.

[PainMail_and_Drecker.txt](https://github.com/keyteki/keyteki/files/4942843/PainMail_and_Drecker.txt)

Tobin
-tpl

**Comment by romanogit** [comment]
The problem here is "Shadow of Dis". This card is causing issues after going to discard. Its effect continues, so it blanked the artifact text.

**Comment by jeremylarner** [comment]
This isn't a bug either - Shadow of Dis is working correctly
