### ISSUE TITLE
Seeker Of Truth is showing an enhancement it shouldn't

### ISSUE THREAD

**Issue by OsramTaleka** [keyteki/keyteki#1798]
The enhancement shows on the deck page and in game. I checked with my opponent and they could not see it, only I could.
![image](https://user-images.githubusercontent.com/53394971/87866851-4a98c200-c93b-11ea-81d5-1a0e46f8597f.png)

**Comment by romanogit** [comment]
Can you try refreshing your browser with F5? Probably a cache issue.

**Comment by OsramTaleka** [comment]
Yep! I logged out, deleted all of my cookies, logged back in and it was still showing up (even on my other decks that have seeker of truth). then I refreshed and it's still there.

**Comment by romanogit** [comment]
@cryogen : a few languages are still showing enhancements from Print to Play decks.

I checked Seeker of Truth and it is showing a draw card in spanish.

**Comment by cryogen** [comment]
Cannot reproduce this, if it's still happening it's definitely a caching issue of some sort
