### ISSUE TITLE
keg frog does not forge with returned captured amber

### ISSUE THREAD

**Issue by scrowner** [keyteki/keyteki#1804]
Run Keyfrog into a creature with captured amber, enough to forge a key. Keyfrog and opponent creature destroyed from fight. Aember total with returned captured amber in excess of required key cost. This was a game win state - third key - not sure if that has something to do with it.

**Comment by romanogit** [comment]
I think Keyfrog cannot use returned amber as it would only be available
after the creature leaves play, which occurs after destroyed ability is
triggered.

Em dom, 19 de jul de 2020 8:24 AM, scrowner <notifications@github.com>
escreveu:

**Comment by sebastienode** [comment]
You’re right @romanogit

**Comment by scrowner** [comment]
Sorry, it seems that I had the order of operations incorrect. Destroyed
effects happen before captured aember is transferred from destroyed
creatures.
Scot

**Comment by romanogit** [comment]
Not a bug
