### ISSUE TITLE
Complete gigantic images not showing in portuguese

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#1807]

**Comment by romanogit** [comment]
@cryogen : you might want to put these files on the server, if not there yet
[gigantic.zip](https://github.com/keyteki/keyteki/files/4944921/gigantic.zip)

**Comment by romanogit** [comment]
i wonder if they should be in github repo as well

**Comment by cryogen** [comment]
We now build them dynamically. Fixed on the server now.
