### ISSUE TITLE
Portuguese text is too big in the Reap button

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#1808]
![image](https://user-images.githubusercontent.com/2104075/87890045-142a7800-ca0b-11ea-9cd0-e961cb47d0b1.png)

**Comment by romanogit** [comment]
Noticed not only this text but several others :( Such as Burning Glare

**Comment by cryogen** [comment]
This happens more widely than just in .pt

**Comment by romanogit** [comment]
yeah, I know... There is an ellipsis logic in place, but I think that we could still use some extra border space.
