### ISSUE TITLE
Gigantic creatures behave differently depending on which half you select

### ISSUE THREAD

**Issue by sebastienode** [keyteki/keyteki#1811]
Hello,

It seems there is an issue with gigantic creatures enhanced. 
Only the half part selected to play the whole creature triggers its bonus. 
Don’t know if the both part could be enhanced by the algorithm but in any case if in tco I don’t choose the enhanced half to play the creature the bonus icon are not resolved. 
It’s happen on my niffle Kong. Assume it’s the same for other gigantic.

**Comment by drallieiv** [comment]
It's better if both part are considered played, so that if you have enhancement on both halves, then they both count

**Comment by sebastienode** [comment]
Yes of course @drallieiv. 
But becareful with the effect after A creature is played.
