### ISSUE TITLE
Enrage counters should be removed when creature killed smb using assault or before fight damage

### ISSUE THREAD

**Issue by AleksandrShepelev** [keyteki/keyteki#1815]
From the rules (v.13)

After a creature with an enrage counter on it is used to fight, remove all enrage counters from it.

If either the attacking or defending creature is destroyed while resolving Assault, Hazardous, or "Before Fight:" abilities, then the fight (dealing damage based on power) is skipped
....
 Card effects that reference “after a creature fights” or “after a creature is used” will still trigger, as the creature was used to fight (even though the fight did not resolve).

**Comment by Tutenkharnage** [comment]
Had this happen in a game last night. I played a Gizelhart's Zealot next to Bull-Wark, used Gizelhart's Zealot to fight, and destroyed the enemy creature with the Assault 2 granted by Bull-Wark, but the enrage counter remained on Gizelhart's Zealot.

**Comment by OsramTaleka** [comment]
Just had this happen as well.

**Comment by not2night** [comment]
Happened for my teammate https://www.thecrucibletracker.com/games/b12cdc80-2382-11eb-9e71-81571277414d#b4
Turn 4 enraged Berinon fights Urchin and kills it with Bull-Wark granted assault ability and does not lose the enrage.
