### ISSUE TITLE
Causal Loop + Fidgit

### ISSUE THREAD

**Issue by drallieiv** [keyteki/keyteki#1819]
When playing my opponent archived Casual Loop with Fidgit effect.
The Causal Loop went back to my opponent's archives.
It should have went to mine.

[Causal Loop] : Action - Play: Archive a card. Archive Causal Loop.
[Fidgit] : Creature - Elusive. Reap: Discard a random card from your opponent’s archives or the top card of their deck. If that card is an action, play it as if it were yours.﻿﻿

Game Chat : 

drallieiv uses Fidgit to reap with Fidgit
drallieiv uses Fidgit to discard Causal Loop
drallieiv plays Causal Loop
drallieiv uses Causal Loop to archive a card

**Comment by romanogit** [comment]
That's a very interesting corner case :)

**Comment by rsdevigo** [comment]
In section of LEAVES PLAY of Rulebook, say: When a card leaves play it is always put into its owner’s appropriate out-of-play zone, unless a card effect explicitly states that it interacts with that zone.

I don't know if Casual Loop should be archived in your archive. Well, maybe you don't own the card.

**Comment by SkyJedi** [comment]
Opponent should archive a card then when it tries to archive casual loop it shouldn't be able to do it should just stay in discard

**Comment by romanogit** [comment]
I think this issue is not a bug. I read it incorrectly first time. I thought the opponet had archived your Casual Loop.
