### ISSUE TITLE
In game decklist shows too many blue cards

### ISSUE THREAD

**Issue by dukman00** [keyteki/keyteki#1826]
There are only 3 enhanced cards in this deck, but the decklist show almost all of them blue. My opponent's decklist was the same.

![Screenshot 2020-07-21 at 11 28 24](https://user-images.githubusercontent.com/25844406/88037887-c5352d80-cb45-11ea-9834-665cfbec42b2.jpg)

**Comment by cryogen** [comment]
Looks like @SkyJedi forgot to turn blue off when he was done with it 🤣

**Comment by SkyJedi** [comment]
Oh that's why I defined fontProps *inside* that loop.
