### ISSUE TITLE
Discombobulator bug

### ISSUE THREAD

**Issue by GiorgioPalini** [keyteki/keyteki#1827]
I assigned the Discombobulator upgrade to a creature, but my opponent still managed to lose my aember from my reserve.

**Comment by agrandstudent** [comment]
Do you have any more specifics? like what cards your opponent used to cause you to lose aember from your reserves.  Discombobulator specifically prevents aember lost from your reserves if the word "steal" was used.  It does not stop capture, interdenominational graft, or "pay" effects.

**Comment by romanogit** [comment]
@GiorgioPalini , please reopen with more details and we are unable to reproduce.
