### ISSUE TITLE
Obsidian Forge doesn't allow forging a key when no creatures are destroyed

### ISSUE THREAD

**Issue by Sangiuda** [keyteki/keyteki#1842]
I skipped forge step for a miasma bomb at 11 ambers, got to 13 ambers, used forge without sacrificing anything and no keys were forged

Key cost was 6

**Comment by jeremylarner** [comment]
Miasma (bomb) is not relevant here - issue title updated

**Comment by Sangiuda** [comment]
however usually I have always forged with obsidian forge, I inserted miasma bomb because I thought it was relevant
