### ISSUE TITLE
2 Drecker adiacent duplicate Damage taken

### ISSUE THREAD

**Issue by Duxer86** [keyteki/keyteki#1845]
Hi, 

I had 2 Drecker close to each other with no damage on and a  Gizelhart’s Zealot next to them. I used the zealot the fight Gamgee then played Smite and fought again against Gamgee. At this point both my Drecker died cause they took both 4 damage. Only the Decker close to the Zealot is supposed to take 2 damage i think.

![Drecker](https://user-images.githubusercontent.com/14357933/88204916-4c6cc900-cc4c-11ea-88b8-6c601a36eca0.png)

**Comment by drallieiv** [comment]
Drecker text says 
"Damage dealt to Drecker’s neighbors during fights is also dealt to Drecker. Reap: Steal 1A."

If your setup is 
Drecker 1 | Drecker 2 | Zealot

Then :

- the fight starts (during fights is true)
- Zealot receives damages > damage is copied to dreker 2
- We are still during a fight, dreker 2 recevied damages > damage is copied to dreker 1
- We are still during a fight, dreker 1 recevied damages > damage is copied to dreker 2
- Repeat

It behaves as expected. But I would not advise putting 2 Dreckers side by side

**Comment by jeremylarner** [comment]
I'd really like to see a ruling on this one way or the other.  The only ruling we've had so far kind of implied that drecker damage only propagates once (so drecker 1 doesn't take damage here), but it would be nice to know for sure

**Comment by Duxer86** [comment]
> I'd really like to see a ruling on this one way or the other. The only ruling we've had so far kind of implied that drecker damage only propagates once (so drecker 1 doesn't take damage here), but it would be nice to know for sure

Yea, gonna try to ask at kfrules@fantasyflightgames.com and see if they will ever response.

**Comment by Duxer86** [comment]
Miss clicked on "Close and Comment"

**Comment by drallieiv** [comment]
an entry was added to Dreker in the 1.6 FAQ : 

Drecker
If two Dreckers (MM 006) are neighbors and I fight one of them with
my 2-power creature, what happens?
Both Dreckers simultaneously take 2 damage. Because the damage is
only dealt once, it does not trigger any more instances of damage.

**Comment by jeremylarner** [comment]
That's the ruling I mentioned above which IMO implies Drecker only propagates damage once.  You clearly have a slightly different interpretation.  I don't think the ruling is clear enough to say for sure what intended behaviour in this situation is, hence my preference to get a clear ruling on this situation before I mess with the game engine any more

**Comment by Blaph** [comment]
I think the rules is clear enough.
According to the FAQ, the first Drecker should be destroyed because of the 2+2 damage dealt (2 from the fight + 2 from the neighbor Drecker). The second Drecker should take 2 damages instead
