### ISSUE TITLE
Diametric Charge doesn't hurt the neighbors

### ISSUE THREAD

**Issue by CarlosJLopez** [keyteki/keyteki#1850]
[log.txt](https://github.com/keyteki/keyteki/files/4966784/log.txt)

**Comment by SkyJedi** [comment]
It works in game testing for me and the code is the same as Lava Ball. Can you reproduce the error and screenshot @CarlosJLopez?

![image](https://user-images.githubusercontent.com/2967416/88310939-e3319800-ccd5-11ea-901f-9d599ca15cc9.png)

**Comment by CarlosJLopez** [comment]
Hi SkyJedi, the log of the game is attacched at first comment.

**Comment by SkyJedi** [comment]
> Caran_Logos uses Diametric Charge to deal 1 damage to Stealthster and 2 to their neighbors

looks like it worked via the log.  its in there both times you used it
