### ISSUE TITLE
Evasion Sigil seems to not work with one stood against many

### ISSUE THREAD

**Issue by hydrophilic-attack** [keyteki/keyteki#1855]
I just played a game where my opponent had evasion sigil and played one stood against many. It was a bit difficult to follow what happened, but it seems like the evasion sigil didn't trigger for any of the fights. The cards in my opponent's discard pile were all creatures I had killed the turn before and not any newly discarded cards

I attached the log text for the game, though it may not be very helpful since the text for one stood against many is not very descriptive, The bug happened on turn 9. I'm guessing the issue is mainly with one stood against many because the evasion sigil triggered correctly on later turns
[evasion sigil osam.txt](https://github.com/keyteki/keyteki/files/4972850/evasion.sigil.osam.txt)

**Comment by cryogen** [comment]
OSAM is known to be a problem, linking this to the issue here: #241
