### ISSUE TITLE
"Cyber-Clone"

### ISSUE THREAD

**Issue by UltraUltraUltra** [keyteki/keyteki#1858]
"Cyber-Clone" seems to copy the card it copies before the card is purged, so it copies its armour and abilities that it may have from upgrades etc.  As I read "Cyber-Clone", it should purge the card it copies first, so it should only copy the card as printed, not as it is in play.

![Cyber-Clone](https://user-images.githubusercontent.com/55008319/88459250-d3f44b00-ce8b-11ea-9b70-205e35c6718d.png)

**Comment by romanogit** [comment]
I coded this card using the same logic of Power of Fire, which considers the power of the creature before it goes to discard:

![image](https://user-images.githubusercontent.com/2104075/88459382-794af700-ce6b-11ea-86f9-a080271205bb.png)

**Comment by cryogen** [comment]
The new rules update I think clears this up:

"If cards leave play while resolving an ability, later instructions in the same
ability refer to the cards as they were immediately prior to leaving play"

**Comment by romanogit** [comment]
Closingm, not a but
