### ISSUE TITLE
Sensor Chief Garcia "Fight"ing didn't increase the opponent's Key cost

### ISSUE THREAD

**Issue by jaeiclee** [keyteki/keyteki#1863]
![Garciabug](https://user-images.githubusercontent.com/2484055/88481273-50268580-cf95-11ea-949d-f3d129dae8c9.PNG)

I forgot to take a screenshot of the board state, but neither decks had cards that decreases the forging cost, so Garcia's effect should have stopped the winner from forging a key for the turn.

https://decksofkeyforge.com/decks/7c1f8a51-eb44-4ae0-9973-168f5a9562ef
https://decksofkeyforge.com/decks/3c07f54e-ece7-4136-89a8-c970acd1d338

Edit: Garcia died after combat, but I don't think it should matter here.

**Comment by SkyJedi** [comment]
the ability won't trigger if she dies in combat

![image](https://user-images.githubusercontent.com/2967416/88497528-42b5cf00-cf86-11ea-9e57-3027a515a6eb.png)

**Comment by jaeiclee** [comment]
` After the fight resolves, if the creature that is being used to fight survives, all “Fight:” abilities the creature has, if it has any, resolve.`
D'oh. Sorry :(
