### ISSUE TITLE
Soulkeeper + Niffle Ape + Matter Maker = Soulkeeper and Niffle not working

### ISSUE THREAD

**Issue by tobinlopes** [keyteki/keyteki#1864]
Hey folks,

During an Untamed turn I played Soulkeeper on Niffle Ape, he attacked (not ignoring taunt or elusive - I was forced to attack another creature) and the Ape died and Soulkeeper didn't trigger.

[SoulkeeperNiffleApe.txt](https://github.com/keyteki/keyteki/files/4978910/SoulkeeperNiffleApe.txt)

Tobin
-tpl

**Comment by romanogit** [comment]
There was a 
`Waxabi plays Shadow of Dis`

Shadow of Dis is bugged

**Comment by jeremylarner** [comment]
This isn't a bug is it? Shadow of Dis is active, so Niffle Ape doesn't ignore Taunt, and Soulkeeper doesn't trigger....
