### ISSUE TITLE
Jargogle archiving face down

### ISSUE THREAD

**Issue by CrookedWookie** [keyteki/keyteki#187]
I had an opponent board clear while I had a Jargogle in play, and for some reason it archived my card face down, so that I couldn't look and see what it was.  Typically the way the Crucible is formatted, your own archived cards are face up, and opponent's archived cards are face down (which still seems silly, as in a real game you could still pick up your archives and look at them, I believe).  But at any rate, having your Jargoggled cards face down is a minor nuisance and not consistent with the archiving mechanics.
Thanks!

**Comment by romanogit** [comment]
I am unable to recreate. I had `Interdimensional Graft` under `Jargole` while my opponent play a `Gateway to Dis`. I can see IG facing up in my archive:

![image](https://user-images.githubusercontent.com/2104075/62538127-6ee1b880-b828-11e9-8b04-fde396aa95af.png)

**Comment by cryogen** [comment]
Closing this as not reproducible.  If you're able to provide more information please reopen this.

**Comment by Jacksuhn** [comment]
If it still matters, this same thing happened to me today. Not a board wipe, but opponent destroyed my Jargoggle, my card underneath him went into my archive face down.
