### ISSUE TITLE
Niffle Kong

### ISSUE THREAD

**Issue by getherthanthou** [keyteki/keyteki#1876]
When a Niffle Kong is the only friendly Niffle it presently tries to kill itself without any option not to if it attacks or reaps.  The text says that you MAY sacrifice a Niffle creature, therefore Niffle Kong should have a done box added once it reaps or attacks.

**Comment by romanogit** [comment]
Niffle Kong ability is currently implemented as optional.  
How are your Game Settings defined? Do you have both check boxes clicked?

**Comment by getherthanthou** [comment]
Prompt to order simultaneous abilities is off, show a prompt when initiating 1-click abilities is on.  Do you suggest I change one of them?

**Comment by romanogit** [comment]
I do not think the prompt for order would matter if just Niffle kong is in play, but without knowing the whole play area, it might be difficult to say. Can you try again setting the first one to "on"?

**Comment by getherthanthou** [comment]
Will play a game with that deck and see if that's fixed it and report back

**Comment by getherthanthou** [comment]
Just played Niffle Kong again and got the option to not sacrifice him this, so think we are good :)  Thanks
