### ISSUE TITLE
background image appears in fours

### ISSUE THREAD

**Issue by skunkwitch** [keyteki/keyteki#1877]
So I logged in to crucible today to see that you can now enter customer backgrounds for your games. I immediately added one after changing the size to 16x9 inches. I went into a game and the image appeared as 4 of the same image in a square instead of just the one image. I figured I just made the image too small and doubled the size, still had the same issue in the next game. I then realized that due to the image appearing in 4 separate images, i could not see the options at the top such as "concede" or "leave game". And that my opponent's cards in their hand and such were covering up all their information such as chains, aember, etc...
Can someone help? I also tried it with one of the preset images and had the same issue. I added a picture as proof
![wtf](https://user-images.githubusercontent.com/68925682/88719619-31d19e80-d0e9-11ea-8621-a07b82078c6a.png)

**Comment by cryogen** [comment]
I can't reproduce this. I notice you're using a browser extension to change the look and feel of the site. Can you try with that disabled?

If it still happens can you attach the image you're trying to use?

**Comment by skunkwitch** [comment]
> I can't reproduce this. I notice you're using a browser extension to change the look and feel of the site. Can you try with that disabled?
> 
> If it still happens can you attach the image you're trying to use?

I was able to fix it after removing the crucible addon extension. thanks!
