### ISSUE TITLE
Gigantic Creature Doesn't get armor or bonus pips depending on how it's played

### ISSUE THREAD

**Issue by zbarmstrong** [keyteki/keyteki#1880]
![Screen Shot 2020-07-28 at 7 22 48 PM](https://user-images.githubusercontent.com/68257504/88744410-462b9080-d115-11ea-9f31-652ea0c75aee.png)

When Ultra-Graviton is played by clicking the top half of the card, it plays the bonus icon that's included but doesn't give Ultra-Graviton it's armor (I've seen this on Niffle Kong too). When it's played by clicking the bottom half of the card, the creature is given the armor but the bonus pips are not activate.

**Comment by cryogen** [comment]
Linking this to #1811
