### ISSUE TITLE
Blast Shielding 

### ISSUE THREAD

**Issue by punske** [keyteki/keyteki#1883]
Blast Shielding's wording is "after this creature is used, its controller may attach Blast Shielding to one this creature's neighbors."

TCO is currently triggering the may effect as a must effect.

**Comment by rsdevigo** [comment]
But doesn't the Done button appear when you use the creature ?

**Comment by punske** [comment]
I'll test. But from what I recall no.

**Comment by romanogit** [comment]
Yes, there is a Done button. It is working as expected now.
