### ISSUE TITLE
Review Put into Play and gigantic

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#1886]
![image](https://user-images.githubusercontent.com/2104075/88877407-c4faf900-d1fb-11ea-9367-636f6c9daaa7.png)

- [x] Overload Greking
- [x] Purify
- [x] Saurian Egg 
- [x] Æmberlution
- [x] Spangler Box

Not applicable:
- [x] Swap Widget
- [x] Gebuk

**Comment by cryogen** [comment]
#1709

**Comment by drsheep422** [comment]
also had purify put into play just lower half of Ultra-Grav to board.  Bottom half should have stayed on top of deck.  Was able to fix with manual mode.

**Comment by romanogit** [comment]
Fixed
