### ISSUE TITLE
Untamed Ambassador Timing

### ISSUE THREAD

**Issue by nsalaway** [keyteki/keyteki#189]
This probably applies to all Ambassadors, but I experienced it with Untamed.

The card reads: "You may play or use an Untamed card this turn."

When I reap with the Ambassador, it forces me to play/use a card immediately, whereas the text suggests I may use/play a card at any time in my turn, not just immediately after using the Ambassador.

**Comment by Achocholacek** [comment]
This is a known issue with the engine that does need to be resolved in the future.
