### ISSUE TITLE
Essence Scale and Lord Invidius

### ISSUE THREAD

**Issue by Kebay** [keyteki/keyteki#1894]
I just used  [Lord Invidius](https://decksofkeyforge.com/cards/lord-invidius) to take control of my opponent's Silvertooth and then tried to use [Essence Scale](https://decksofkeyforge.com/cards/essence-scale) to destroy Silvertooth, which is a Dis creature, in order to ready another Dis creature. However, I was not able to do so.

Relevant log:

```
Main phase - KebaKebaKeba
KebaKebaKeba plays Drecker
KebaKebaKeba uses Lord Invidius to reap with Lord Invidius
KebaKebaKeba uses Lord Invidius to apply a lasting effect to Silvertooth
KebaKebaKeba uses Infurnace to reap with Infurnace
KebaKebaKeba uses Shooler to reap with Shooler
KebaKebaKeba uses Snarette to reap with Snarette
KebaKebaKeba uses Essence Scale to destroy Silvertooth
[… and then nothing more, went to manual mode here]
```

Possibly relevant quote from the rulebook:

> If cards leave play while resolving an ability, later instructions in the same
ability refer to the cards as they were immediately prior to leaving play
> Example: Code Monkey (WC 147) has the text: "Play: Archive each
neighboring creature. If those creatures share a house, gain 2 Aember. If
one of the archived cards was affected by an effect that changed which
house it belonged to, then the second part of Code Monkey's ability
refers to the houses to which those cards belonged immediately before
being archived.

**Comment by SkyJedi** [comment]
The issue seems to be that this line is returning the printed house of the destroyed card and not dis

`cardCondition: (card, context) => context.preThenEvent.card.getHouses().some((house) => card.hasHouse(house))`
