### ISSUE TITLE
Johnny Longfingers + Rad Penny: Destroyed effects not triggering

### ISSUE THREAD

**Issue by LitaLea** [keyteki/keyteki#1896]
Witnessed this issue repeat multiple times.

Johnny Longfingers text reads: "Each friendly Mutant creature gains 'Destroyed: Steal 1 aember'"

With Johnny Longfingers on the board, Rad Penny attacked Ardent Hero. While no damage was dealt to Ardent Hero, Rad Penny was Destroyed, however the Steal 1 aember effect does not trigger.

(Glancing at the log, it looks like Rad Penny's Destroyed _status_ may not have actually triggered?)

![Screen Shot 2020-08-05 at 6 59 11 PM](https://user-images.githubusercontent.com/68318681/89476426-a5faea80-d758-11ea-9552-9363c21da863.png)

**Comment by SkyJedi** [comment]
Make sure you check the order of abilities in your profile.  Rad pennys destroyed triggered first and she went back to the deck before longfingers ability triggered

**Comment by Dabar53** [comment]
Was just about to report this same issue and I would say that what you're saying SkyJedi is right but if this player is the active player then the active player has the choice of what effects get to trigger in any order. This issue has also happened with me in my last game. This bug of not being able to pick what destroyed abilities get to trigger in what order has been out for a while

**Comment by SkyJedi** [comment]
not a bug, enable this option in you profile 
![image](https://user-images.githubusercontent.com/2967416/89655667-0d678600-d890-11ea-895f-36b4a4b39dfc.png)
