### ISSUE TITLE
Captured aember and armour covering creature's name

### ISSUE THREAD

**Issue by UltraUltraUltra** [keyteki/keyteki#1900]
Is it possible to move captured aember and armour so that it doesn't cover the creature's name please?  Perhaps if they could be moved so they only cover the artwork?  Thank you.
![image](https://user-images.githubusercontent.com/55008319/89685706-c8296f80-d8f4-11ea-9797-bfd311a5741e.png)
![image](https://user-images.githubusercontent.com/55008319/89685715-ccee2380-d8f4-11ea-9044-ab0197081550.png)

**Comment by romanogit** [comment]
@SkyJedi  - this is fixed, right? or does it depend on card size?

**Comment by SkyJedi** [comment]
Oh yeah, this is done
