### ISSUE TITLE
Paid to forge a key after killing opponent's Turnkey

### ISSUE THREAD

**Issue by OzOhM** [keyteki/keyteki#1903]
Opponent played Turnkey which unforged one of my keys.
Opponent also had 2x Faust the Great on board, along with many other creatures.

On the next turn, I played Blood Money to put 2 amber on his Turnkey, which also increased my key cost of 2 because of his Fausts. I then used my Cowfyne to target the Turnkey's neighboring creature and killed his Turnkey.
This resulted in me forging a key at the cost of 2 amber.

Looking at the code I believe this is because the actual key cost calculation made on the "forgeKey" procedure doesn't match the value put in the "modifier" in the Turnkey card script.
Maybe adding an option to forge for free instead of using a negative modifier would help solving this issue and all the cards allowing to "forge at no cost"

**Comment by strib** [comment]
Just ran into the same situation with a Garcia that made my opponent pay 2 when killing Turnkey.

**Comment by Kebay** [comment]
No way to test this right now, but do Might Makes Right, REDACTED and Epic Quest have a same issue? (At least, their code is very similar.) If they do, we might as well introduce similar one-line fixes there as well.

**Comment by romanogit** [comment]
There is a slight difference in implementation. I think when REDACTED/MMR and Epic Quest is evaluated, the current key cost is the actual cost of the current player, so it does the subtraction correctly.

The problem with Turnkey is the moment the argument is evaludated and the getCurrentKeyCost method called.

**Comment by romanogit** [comment]
To be honest, I will implement it to be consistent.
