### ISSUE TITLE
Miasma skips General Order 24, based on the new timing chart it shouldn't

### ISSUE THREAD

**Issue by dukman00** [keyteki/keyteki#1905]
"Start of turn" effects are no longer part of the "forge a key" step, so Miasma shouldn't prevent General Order 24 from triggering. Not sure if this issue is also happening on Director of ZYX, Floor is Lava etc.

**Comment by cryogen** [comment]
Thanks for the report, linking this to the other issue we have open here https://github.com/keyteki/keyteki/issues/1714
