### ISSUE TITLE
Essence Scale on a warded creature

### ISSUE THREAD

**Issue by dukman00** [keyteki/keyteki#1909]
Destroying a warded creature with Essence Scale shouldn't satisfy the "if you do" check and should stop the rest of the ability from resolving. 

![Screenshot 2020-08-14 at 12 13 20](https://user-images.githubusercontent.com/25844406/90240564-c3e7df80-de29-11ea-822b-3eebcdfffe5d.jpg)

**Comment by romanogit** [comment]
This is fixed by #1895
