### ISSUE TITLE
Lay of the Land doesn't shuffle and draw when the deck is empty.

### ISSUE THREAD

**Issue by strib** [keyteki/keyteki#1911]
I managed to get my entire deck into my hand, and then played Stealth Mode, so that there were zero cards in my deck and one in my discard pile. Then I played Lay of the Land, but it did not shuffle and draw the Stealth Mode back into my hand, as it should have.

I reproduced it in manual mode, here's a screenshot:

![image](https://user-images.githubusercontent.com/8516691/90282043-8df32d00-de22-11ea-817e-26a37d67d6b3.png)

![image](https://user-images.githubusercontent.com/8516691/90282060-95b2d180-de22-11ea-829e-cb8ba8582bf9.png)

**Comment by SkyJedi** [comment]
Lat of the land doesn't shuffle discard into draw.  You need a card that says "Draw" to do that.

**Comment by strib** [comment]
@SkyJedi It says draw in the second (independent) sentence.
