### ISSUE TITLE
Ardent Hero Takes Damage from mutants

### ISSUE THREAD

**Issue by WizardRandom** [keyteki/keyteki#1913]
When attacking a mutant creature with an Ardent Hero, the Ardent Hero Takes Damage

**Comment by Blaph** [comment]
I don't take damage instead. Can you give more details, please?

**Comment by romanogit** [comment]
Without the game log, it is impossible to help. AH's test cases are passing. Maybe a Shadow of Dis?

![image](https://user-images.githubusercontent.com/2104075/100763530-067ef900-33d4-11eb-8113-0f156baa25e7.png)

Reopen with more information. 
Thank you
