### ISSUE TITLE
Yxilx Dominator comes into play not stunned?

### ISSUE THREAD

**Issue by Idunno999** [keyteki/keyteki#1918]
Not sure what caused this, after a long Mars turn, he just entered play with no stun
![chrome_XWD2qNoEVM](https://user-images.githubusercontent.com/69819293/90437898-0aa83480-e0cb-11ea-9fe7-ea747c81392d.png)

**Comment by hydrophilic-attack** [comment]
Did you play Shadow of Dis the turn before? It looks like zorg didn't enter stunned either

**Comment by Idunno999** [comment]
The answer is no, though if I recall correctly Zorg entered play stunned still.
I couldn't screenshot the board due to the game progressing and only catching this on my next turn

**Comment by romanogit** [comment]
From discord:
> PaowtrickHoje at 18:25
> Found a bug yesterday and seached for it on keyteki, and found this.. https://github.com/keyteki/keyteki/issues/1918
> So I think this is why it happening... 
> you have played a stunner creature, remove the stun, bounce the creature. When the creature is played after that, it comes in > to play  without a stun.

**Comment by romanogit** [comment]
Here is how to reproduce:
![image](https://user-images.githubusercontent.com/2104075/102086822-712e2c80-3df7-11eb-8899-bdcbbeae884e.png)

Player 1 plays Zorg and unstuns
Player 2 takes control of zorg (hypnobeam)
Player 1 returns Zorg to hand (hysteria)
...
Player 1 plays Zorg - it enters play unstunned


romano1 brings Baroness Q. Octelle to The Crucible
romano2 brings Wojownik Tracz to The Crucible
romano1 won the flip and is first player
 romano2 has connected to the game server
 romano1 has connected to the game server
 romano1 is attempting to switch manual mode on
 romano2 allows enabling manual mode
 romano1 switches manual mode on
romano1 is shuffling their deck
romano1 draws 6 card  s to their maximum of 6
romano2 is shuffling their deck
romano2 draws 6 card  s to their maximum of 6
romano1 draws 1 card 
Key phase - romano1
romano1 does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - romano1
romano1 chooses mars  as their active house this turn
Main phase - romano1
 romano1 manually moves Xanthyx Harvester from their hand to their play area
Ready phase - romano1
romano1 readies all of their cards 
Draw phase - romano1
End of turn 1
romano1: 0 Æmber  (0 keys) romano2: 0 Æmber  (0 keys)
TURN 1 - romano2
Key phase - romano2
romano2 does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - romano2
romano2 chooses mars  as their active house this turn
Main phase - romano2
 romano2 uses the /add-card command to add Zorg to their hand
romano2 plays Zorg
romano2 plays Ixxyxli Fixfinger
Ready phase - romano2
romano2 readies all of their cards 
Draw phase - romano2
romano2 draws 1 card  to their maximum of 6
End of turn 1
romano1: 0 Æmber  (0 keys) romano2: 0 Æmber  (0 keys)
TURN 2 - romano1
Key phase - romano1
romano1 does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - romano1
romano1 chooses mars  as their active house this turn
Main phase - romano1
romano1 uses Xanthyx Harvester to reap with Xanthyx Harvester
romano1 uses Xanthyx Harvester to gain 1 Æmber 
Ready phase - romano1
romano1 readies all of their cards 
Draw phase - romano1
End of turn 2
romano1: 2 Æmber  (0 keys) romano2: 0 Æmber  (0 keys)
TURN 2 - romano2
Key phase - romano2
romano2 does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - romano2
romano2 chooses mars  as their active house this turn
Main phase - romano2
romano2 uses Ixxyxli Fixfinger to reap with Ixxyxli Fixfinger
romano2 exhausts Zorg to remove its stun
Ready phase - romano2
romano2 readies all of their cards 
Draw phase - romano2
End of turn 2
romano1: 2 Æmber  (0 keys) romano2: 1 Æmber  (0 keys)
TURN 3 - romano1
Key phase - romano1
romano1 does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - romano1
romano1 chooses mars  as their active house this turn
Main phase - romano1
romano1 plays Hypnobeam
romano1 uses Hypnobeam to apply a lasting effect to Zorg
Ready phase - romano1
romano1 readies all of their cards 
Draw phase - romano1
romano1 draws 1 card  to their maximum of 6
End of turn 3
romano1: 2 Æmber  (0 keys) romano2: 1 Æmber  (0 keys)
TURN 3 - romano2
Key phase - romano2
romano2 does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - romano2
romano2 chooses dis  as their active house this turn
Main phase - romano2
romano2
/add-card histeria
 romano2 uses the /add-card command to add Hysteria to their hand
romano2 plays Hysteria
romano2 uses Hysteria to return all creatures to their owner's hand
Ready phase - romano2
romano2 readies all of their cards 
Draw phase - romano2
End of turn 3
romano1: 2 Æmber  (0 keys) romano2: 1 Æmber  (0 keys)
TURN 4 - romano1
Key phase - romano1
romano1 does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - romano1
romano1 chooses mars  as their active house this turn
Main phase - romano1
 romano1 manually moves Xanthyx Harvester from their hand to their play area
Ready phase - romano1
romano1 readies all of their cards 
Draw phase - romano1
End of turn 4
romano1: 2 Æmber  (0 keys) romano2: 1 Æmber  (0 keys)
TURN 4 - romano2
Key phase - romano2
romano2 does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - romano2
romano2 chooses mars  as their active house this turn
Main phase - romano2
romano2 plays Zorg
