### ISSUE TITLE
Red Hot Armor + Maruck the Marked

### ISSUE THREAD

**Issue by ghost** [keyteki/keyteki#192]
When active player plays Red Hot Armor and the opponent has Maruck out, he is capturing aember for the armor which is "removed" by RHA. By the way RHA is worded it seems this isn't as intended but cannot find a rules reference online regarding it. 

Red Hot Armor: "Play: Each enemy creature with armor loses all of its armor until the end of the turn and is dealt 1D for each point of armor it lost this way."

Maruck the Marked: "After Maruck the Marked prevents damage with its armor, capture 1A for each damage just prevented."

**Comment by Achocholacek** [comment]
I would concur with your assessment - it's not direct damage that he's preventing with his armor, therefore he shouldn't be capturing aember. I'd definitely like to hear some other opinions before we make an official decision or change, though.
