### ISSUE TITLE
Essence Scale on a Lord-Invidius-stolen creature doesn't ready a dis creature

### ISSUE THREAD

**Issue by strib** [keyteki/keyteki#1938]
I used Lord Invidius to steal my opponents Quant.  Once it was in my battleline, it should belong to house Dis.  Then I destroyed the Quant with Esssence Scale, but I wasn't given the option to ready a Dis creature (I didn't have any Logos creatures in play, but I assume it still thought the Quant was in house Logos.)

![image](https://user-images.githubusercontent.com/8516691/91650987-b04c9380-ea3b-11ea-8a1c-cc0e74840a85.png) 
![image](https://user-images.githubusercontent.com/8516691/91650992-b6427480-ea3b-11ea-834a-6a803d5205c1.png)

Apologies if this is a dup, but I couldn't find another issue for this yet.

**Comment by dmikalova** [comment]
I can confirm having the same issue, even with houses not in my deck.

**Comment by romanogit** [comment]
This one is tricky. Even though the code is using "clone", the effect to change the house is lost when the card goes to discard pile. clone does not seem to store previously applied effects

**Comment by romanogit** [comment]
According to https://github.com/keyteki/keyteki/pull/1895, this should be working as expected
