### ISSUE TITLE
Rad penny + Soulkeeper: Soulkeeper ability not triggered

### ISSUE THREAD

**Issue by jorgecachoh** [keyteki/keyteki#1947]
When a "Rad penny" is updated with "Soulkeeper" and destroyed -> TCO sends "Rad penny" to my hand (that is ok) but doesn't destroy the most powerful enemy creature.

**Comment by AleksandrShepelev** [comment]
depends who killed Rad Penny. If opponent - he can trigger penny ability first and then soulkeeper is not triggered
