### ISSUE TITLE
Punctuated Equilibrium

### ISSUE THREAD

**Issue by KRB4K** [keyteki/keyteki#195]
The one who plays Punctuated Equilibrium only refills up to 5 cards, whereas it should be 6 by default. Maybe Punctuated Equilibrium is still counted together with the 5 new cards, making it a false "6-card hand".

**Comment by issa** [comment]
I wrote a test for this. In my opinion this works. Could have had chains?

**Comment by issa** [comment]
On the other hand Punctuated Equilibrium should shed chains but it does not.

**Comment by KRB4K** [comment]
Hi, I'm 95% sure I had no chains. Glad my issue was still useful to have you notice it should shed chains though. 
I'll play a few more games and let you know if this still happens. Thanks for all the work you guys put in!
