### ISSUE TITLE
Any plan to provide P2P version ?

### ISSUE THREAD

**Issue by tedjung1202** [keyteki/keyteki#1951]
Hi I'm Korean Keyforge player. 
I'm not sure the reason of ping spikes (distance or the spec of server) but it happens lots of times during game anyways.

So may I ask you if you have any plan to provide P2P version (guest can connect to host directly) or improve server ping spike issue?

Of course this keyforge cruscible is awesome in this pandemic situation. But if this could be improved more, it would be much more  appreciated. : )

**Comment by cryogen** [comment]
This would require a huge rewrite of the infrastructure code and is not a direction I'd probably go in to be honest.

I have however pushed an update recently which should hopefully help with lag on slower/more latent connections to the server. Do let me know if this has helped at all
