### ISSUE TITLE
Blossom Drake and Etan's Jar

### ISSUE THREAD

**Issue by tobinlopes** [keyteki/keyteki#1952]
Blossom Drake isn't blanking Etan's Jar to allow play of cards restricted by EJ.

Once BD was played I should have been able to play Floomf.

Game log below.

Tobin
-tpl

[BD and Etans.txt](https://github.com/keyteki/keyteki/files/5190769/BD.and.Etans.txt)

**Comment by Kebay** [comment]
This is not a bug. Etan's Jar creates a persistent effect with its Play ability and hence the banned card cannot be played even after Blossom Drake enters play.
