### ISSUE TITLE
"Blast from the Past" deals damage even when it returns the top half of a gigantic creature

### ISSUE THREAD

**Issue by Tutenkharnage** [keyteki/keyteki#1965]
My opponent played Blast from the Past, chose the top half of Deusillus, and dealt 20 points of damage to my Niffle Kong. According to the rulebook, the top half of a gigantic creature does not have any power associated with it:

_**Ruleboook, p. 12, "Gigantic":** Both halves of a gigantic creature have the same title, house, and card type. Otherwise, each half has the attributes printed on it: the top half has bonus icons, while the bottom half has power, armor, and the text box._

This issue is effectively linked to https://github.com/keyteki/keyteki/issues/1898.

**Comment by AleksandrShepelev** [comment]
same problem with niffle kong and troop call. Troop call shouldn't be able to return top half of kong

**Comment by UltraUltraUltra** [comment]
Blast from the Past did 5 damage when my opponent used it to archive the top half of Deusillus (when it shouldn't have done any damage).

![Blast from the Past Bug](https://user-images.githubusercontent.com/55008319/94373404-3f150480-00fd-11eb-945a-8977f7ff9b0e.png)
