### ISSUE TITLE
Novu Dynamo and Gambling Den

### ISSUE THREAD

**Issue by Ginopinoshow** [keyteki/keyteki#1970]
When both Novu Dynamo and Gambling Den are in play, it should be possible to choose which effect activate first. Currently it is not possible (even with the Prompt to order simultaneous abilities and Show a prompt when initating 1-click abilities flag active)

**Comment by romanogit** [comment]
It is prompting for me:

![image](https://user-images.githubusercontent.com/2104075/101174952-4e478f80-3623-11eb-95f4-1396b2b20a36.png)

Can you add more details if you still have an issue, please?

Closing as working as expected
