### ISSUE TITLE
 Problem with enhancements when uploading a deck

### ISSUE THREAD

**Issue by Dressagehorse** [keyteki/keyteki#1971]
I was uploading a new MM deck. When window with enhancements to be entered popped up there were four cards but across each card  there were empty/zero enhancements available. The same window has a warning that once you enter enhancements they cannot be changed. I tried to leave the website because I wanted my deck's bonuses, however, the deck was already uploaded with no enhancements. The link to my deck is https://www.keyforgegame.com/deck-details/23db7616-0d67-4636-8aa8-277086d2fffb
Thanks.

**Comment by Dressagehorse** [comment]
I also tried another new deck and have the same problem. This time a made a screen shot.
<img width="1451" alt="Screen Shot 2020-09-15 at 8 11 55 PM" src="https://user-images.githubusercontent.com/65928690/93288204-32ed8680-f790-11ea-9c6a-57a963e4c4cf.png">

**Comment by cryogen** [comment]
This was a data issue which is now resolved. Sorry for the inconvenience!
