### ISSUE TITLE
No shield on Ultra Gravitron

### ISSUE THREAD

**Issue by fedeghi** [keyteki/keyteki#1974]
Shield 3 is missing on Ultra Gravitron.
Thanks, bye!

![Crucible_bug](https://user-images.githubusercontent.com/71407948/93386848-9945d800-f868-11ea-91ea-2170b6fdd4e0.PNG)

**Comment by roeswood** [comment]
I have also seen this.

**Comment by fedeghi** [comment]
Looks like it has been fixed O_o
I played one game yesterday, shield was there... I will keep an eye on this and report again, if required.
Bye!

**Comment by fedeghi** [comment]
... and now it is missing again U.u

**Comment by cryogen** [comment]
I had to reset the card data cache recently. It’s probably missing when you play one particular half

**Comment by fedeghi** [comment]
Ok, what is the best way to proceed? Should I try to play top or bottom half, and then report which one is not placing shield?
Thanks, bye!

**Comment by fedeghi** [comment]
I have performed a couple of tests, it seems that shield is not displayed if I play the top half of Gravitron, while it did display correctly (at least once) when I played the bottom half...
I only had time to play two games, one playing top half, one playing bottom half... so, I guess it's not a good representative statistics at all, I will keep you posted in case I find something different.

Last but not least, one thing to be noted: my deck contains an enhanced Gravitron, meaning that the top half has an extra aember bonus which is not there on majority of other Gravitron decks.

Is it possible that the enhancement placed on top half is conflicting somehow with shield token when played?
I'm suggesting this since I don't see other players reporting bugs on Gravitron, so maybe my deck has some hidden bugged interaction between bonus aember, all that "archive stuff" events triggered by gravitron, and shield placement? Just trying to guess :^P

Thanks, bye!

**Comment by JulienTr** [comment]
Same problem with gravitron (no shield).
The top half have an enhancement (draw).
And the french translation does'nt have the card picture.

**Comment by fedeghi** [comment]
Confirmed also on my deck, exact same bug (my enhancement would be a bonus Aember)
Will this be fixed?

>
> If I play the top half, I have the enhancement (draw) but no armor.
> If I play the bottom half, I have the armor but no the enhancement...
>
