### ISSUE TITLE
Opponent cannot join game server or connect to the match today

### ISSUE THREAD

**Issue by richgerrard** [keyteki/keyteki#1975]
<username> has failed to connect to the game
<username> has failed to connect to the game
<username> has failed to connect to the game
<username> has failed to connect to the game
<username> has failed to connect to the game

This is on "node3"

**Comment by cryogen** [comment]
The new node was on an AWS "free tier" instance, so some firewalls blocked it for suspicious activity. That experiment is now concluded and the node shut down
