### ISSUE TITLE
Boneverot Venom

### ISSUE THREAD

**Issue by Herzbube76** [keyteki/keyteki#198]
My opponent used a creature with already 3 damage on it and Boneverot Venom to fight an elusive creature. SO the creature should get another 2 damage but didnt happen.

**Comment by oli0** [comment]
My opponent had Z.Y.X. Researcher. I upgraded it with Bonerot Venom. Next turn he attacked my Bad Penny with Z.Y.X. Researcher. Bad Penny was destroyed, Z.Y.X. Researcher ended up with one damage and wasn't destroyed.

**Comment by skrohmagnon** [comment]
seems to be broken. Deals no damages.

**Comment by CrookedWookie** [comment]
On a similar note, it appears that using a creature to remove a stun is not counting for the purposes of triggering Bonerot Venom.  I had 2 damage on a Brend the Fanatic, who was stunned, and had Bonerot on him.  I used him to remove the stun, and it did not trigger Bonerot, which should have done 2 more damage, killed him, and in turn triggered his Steal effect.  Instead it just removed stun and exhausted him.

**Comment by avandever** [comment]
I also had a Brend not trigger Bonerot when it fought today. It had one armor, so it should've taken only 1 damage, but instead it took none. Unfortunately I didn't grab the chat log, but I did take a screenshot.
![nodamage](https://user-images.githubusercontent.com/1231665/64471746-08dba000-d10a-11e9-82f2-6ee235138a4b.PNG)

**Comment by saluk** [comment]
It appears the issue here is with creatures that have skirmish and are made to fight.

**Comment by avandever** [comment]
It should do damage, though, right? Skirmish prevents damage during the
fight, not after.

**Comment by saluk** [comment]
Correct! I'm still trying to pinpoint where the issue is in crucible. Skirmish was the theory, but I think in fact it is cards like ganger chieftain and smite where causing a creature to 'fight' is not considered a 'use'.

**Comment by saluk** [comment]
Tests here: https://github.com/saluk/keyteki/blob/bonerot_skirmish/test/server/cards/02-AoA/BonerotVenom.spec.js Ganger Chieftain is not triggering the bonerot.
