### ISSUE TITLE
Bordan the Remdeemed

### ISSUE THREAD

**Issue by Herzbube76** [keyteki/keyteki#199]
Couldnt choose the action of Bordan, only fight and reap.

**Comment by Achocholacek** [comment]
Cannot reproduce this locally - do you remember anything else about board state at the time?

**Comment by Herzbube76** [comment]
Sorry no. Tried it 2 turns. Both turns didnt work.

**Comment by Achocholacek** [comment]
Closing this for now - if issue reoccurs please open a new ticket with as much data as possible!
