### ISSUE TITLE
Cannot add enhances on MM decks

### ISSUE THREAD

**Issue by Ciampone** [keyteki/keyteki#1990]
I'm having issues on trying to add enhances on MM decks. When I add the deck, the enhance page appears, but no icons appear to click to distribute between the cards

**Comment by SkyJedi** [comment]
this still an issue @Ciampone?

**Comment by romanogit** [comment]
@Ciampone : we need the deck name (or URL) to be able to help you

**Comment by Ciampone** [comment]
I'm sorry @SkyJedi and @romanogit that was an issue the day I opened the report, since it took a month for the first reply, it was fixed. Thks again for the replies, the case can be closed

**Comment by romanogit** [comment]
Thanks
