### ISSUE TITLE
Adaptoid and Bonerot passive effect

### ISSUE THREAD

**Issue by sebastienode** [keyteki/keyteki#1996]
Hello,

I got a "funny" bug today. 
I had an adaptoid (https://decksofkeyforge.com/cards/adaptoid) on my board. 
My opponent played the upgrade bonerot-venom (https://decksofkeyforge.com/cards/bonerot-venom) and make 2 damages on my creature. So it had 2 damages on 4 power. 
Next turn I played dis. I played sacro-fend with a draw bonus. Add the effect to steal 1 amber to my adaptoid.
Then I played Starring grave. Add the same effect to my creature. 
Then I played lyco-fend with a capture bonus to add the same effect to my adaptoid but this time the upgrade trigger as if I used my creature. 

Here is the tracker report : https://www.thecrucibletracker.com/games/89165310-0182-11eb-be53-97fe1543b375 (see the end of the report). 

Regards

PS : if you want to contact me on discord for more information : Ashitaka#2525

**Comment by blinkingline** [comment]
Might be the same issue as #398

**Comment by sebastienode** [comment]
Certainly. This bug is really weird. I’ll have a look on the code cause I’m really curious.
