### ISSUE TITLE
Æmberlution and Deusillus

### ISSUE THREAD

**Issue by UltraUltraUltra** [keyteki/keyteki#1999]
I played Æmberlution with Deusillus on the board (but neither half of my other copy - my deck has two copies of Deusillus - in hand), but an additional half suddenly appeared in my Discard pile.  I manually shuffled into my deck but later on I played Resurgence and only half of the original two halves was now in the Discard pile.

Later, I had a Deusillus on the board and both halves of the one in my hand. I played Aemberlution and end-up with four copies of Deusillus (8 cards in total) on the board. The one on the board at the start of turn had an Encounter Suit attached (the one with aember on it), which is why it was not destroyed, so there should have been two when Aemberlution resolved, but definitely not four.

![image](https://user-images.githubusercontent.com/55008319/94873766-01d7ac00-0448-11eb-853d-7456ec924ac2.png)
![image](https://user-images.githubusercontent.com/55008319/94873773-0603c980-0448-11eb-9724-2280917a40d1.png)

**Comment by romanogit** [comment]
Fixed
