### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by HealerMikado** [keyteki/keyteki#2]
Hi !
Is there any way to propose a multi language application ? Like a option language in the navbar, or a auto detection and create some language file to make it easier to contribute to the translation ?
If so i can participate to the french translation =)

**Comment by romanogit** [comment]
Watching this one. 

I think for people to play, showing the cards in a specific language would be a good start.

**Comment by achen224** [comment]
I'm glad to help to translate to the traditional chinese.

**Comment by romanogit** [comment]
Some taste of image translation (just images).

English:
![image](https://user-images.githubusercontent.com/2104075/62489185-7e1b2480-b79c-11e9-9a65-bbc1d2da53b0.png)

Português:
![image](https://user-images.githubusercontent.com/2104075/62489302-c9cdce00-b79c-11e9-8e84-bc3b3cfaeeb8.png)

Français:
![image](https://user-images.githubusercontent.com/2104075/62489317-d6522680-b79c-11e9-91fc-5f1487af2a72.png)

中文:
![image](https://user-images.githubusercontent.com/2104075/62489406-0bf70f80-b79d-11e9-9590-f014edb3f89a.png)

And a 中文 (Chinese) maverick:
![image](https://user-images.githubusercontent.com/2104075/62489375-faae0300-b79c-11e9-8956-46149db1d846.png)

**Comment by romanogit** [comment]
Another teaser now with card names:

Português:
![image](https://user-images.githubusercontent.com/2104075/62571875-d3246c80-b868-11e9-97b6-6e55c979c5a0.png)

Français:
![image](https://user-images.githubusercontent.com/2104075/62571844-c3a52380-b868-11e9-839f-60dc4863638a.png)

Chinese (Traditional):
![image](https://user-images.githubusercontent.com/2104075/62571897-e1728880-b868-11e9-8d75-a9dccebf6379.png)

The basic i18n framework is already done. The work now is towards mapping literals to `<Trans>` and `{t()}` and sending JSON files for translation.

I think this should be two "week" work.

**Comment by achen224** [comment]
cool !!!
I can't find any branch about this
anything I can help now?

**Comment by romanogit** [comment]
@achen224 
I will commit some of the work on my forked branches. I will reference them here later today.

**Comment by romanogit** [comment]
@achen224 
These are the branches I am working on:

To update the load JSON script. You do not need to load the script, but you will have to check the submodule to have the CotA.json and AoA.json packages with locale attribute.
https://github.com/romanogit/keyteki-json-data/tree/i18n-scripts

Once you do that, you have to fetch the images, For that, I am working on branch bellow. This is just to update fecthdata. You can check the new README.md on this branch that explain how to load the images.
https://github.com/romanogit/keyteki/tree/i18n-scripts

Above are prerequisites for the i18n branch to work:
https://github.com/romanogit/keyteki/tree/i18n

This branch contains changes to code and localization files (to be explained in a new post once I commit).

@cryogen , @Achocholacek , @jeremylarner : FYI

**Comment by romanogit** [comment]
@achen224 ,
if you want, you start translating the attached file.
[en.zip](https://github.com/keyteki/keyteki/files/3483308/en.zip)

**Comment by achen224** [comment]
@romanogit 
https://tinyurl.com/yy22so6q
here is my try in zh_hant...
maybe need some testing...
if needed i can do some pull request later

**Comment by romanogit** [comment]
Nice. quick preview:
![image](https://user-images.githubusercontent.com/2104075/62781794-1cee9c00-ba8f-11e9-9846-fbb677c257d3.png)

**Comment by achen224** [comment]
thx, It's look COOL!!!
I 've some friend in taiwan can not wait to play in chinese :)

**Comment by romanogit** [comment]
@achen224 ,
Hello, find attached an updated list of strings.
[locales.zip](https://github.com/keyteki/keyteki/files/3501330/locales.zip)

**Comment by romanogit** [comment]
Hey @achen224,
do you have some time to finish some extra Chinese locale entries?

Are you at the Discord Keyforge lounge: https://discord.gg/vd3AQu ?

**Comment by romanogit** [comment]
i18n initial phase is in production: you can see cards and deck list in multiple languages

**Comment by achen224** [comment]
sorry, I lost msg before...
I will finish it this weekend

**Comment by romanogit** [comment]
ok, you can now get most updated files here:
https://github.com/keyteki/keyteki/tree/master/public/locales

**Comment by romanogit** [comment]
I believe 100% of the client side and 75% of server side is complete.

Client side might miss some keys, which we will get eventual reports.
Server side might also miss some prompt keys and the Game Message is not implemented.

**Comment by romanogit** [comment]
Hey @achen224,
do you have some time to finish some extra Chinese locale entries?
You can make the changes and attach the file here.
Download current file: 
https://github.com/keyteki/keyteki/blob/master/public/locales/zhhant.json

**Comment by achen224** [comment]
ok~I will do it ASAP

**Comment by romanogit** [comment]
@achen224 : I noticed you translated logos as 邏輯, but in KF vault, they use 邏機 .
What do you think?

**Comment by cryogen** [comment]
I'm going to close this now as the feature itself is implemented.  Any further issues or enhancements should be raised as news issues.  Good work everyone!
