### ISSUE TITLE
Mimicry does not allow you to copy Eureka (and possibly other Alphas)

### ISSUE THREAD

**Issue by blinkingline** [keyteki/keyteki#2005]
In multiple games during a tournament yesterday we saw issues where a player would play Mimicry as their first action of the turn, but they were unable to copy Eureka from their opponent's deck

**Comment by romanogit** [comment]
I will double check. I have a PR to fix Omega (#1143) and I noticed it is failing in the Alpha use case as well, so, possibly it was newly introduced.
