### ISSUE TITLE
problem with Xeno- Beast

### ISSUE THREAD

**Issue by scyco** [keyteki/keyteki#2015]
HI,
I have a Xeno-Beast in the middle of two Bull-wark (one on his left and the other on his right).
I attack using Xeno-Beast and this is the log 
"scyco uses Xeno-Beast to make Xeno-Beast fight Even Ivan
scyco uses Xeno-Beast to deal 4 damage to Even Ivan"

Why the special ability of Xeno-Beast was not triggered?? I have fight even if the other creature were destroyed by the combined ability given by the two Bull-warks

Can anyone help me?
Thanks

**Comment by Hypyer946** [comment]
**Fight** abilities don't trigger if assault kills the other creature.
