### ISSUE TITLE
Only 5 armor displayed

### ISSUE THREAD

**Issue by unique2101** [keyteki/keyteki#2021]
Hi,
it seems the maximum displayed armor is 5.
The Worm has 5 on its own and one should be added by Ixxyxli. However onyl 5 is shown on the Worm. When I attacked it (don't have screenshot, sorry) 6 Armor has been applied in defense.
![image](https://user-images.githubusercontent.com/10000928/95744256-558d9500-0c93-11eb-80aa-7c81d8f59e32.png)

**Comment by SkyJedi** [comment]
Fixfinger give armor to "Martian Creatures" which refers to the Martian
trait. which the worm does not have.  if it were "Mars creature" it would
be refered to as it is in  hypnotic command the

[image: image.png]

[image: image.png]

**Comment by unique2101** [comment]
Ah, OK, thank you.
With Hypnotic Command in mind (I actually do not have it in any of my decks) what you say seems right. I just considered "Martian" simple adjective created from "Mars" as the house name.

**Comment by SkyJedi** [comment]
It a common mistake that i had to do a bit of research to confirm.  thanks for the report! its always helpful to double check this kinda stuff
