### ISSUE TITLE
Two Customs Offices

### ISSUE THREAD

**Issue by OptimalDuck** [keyteki/keyteki#2023]
I was playing a game where I had two customs offices in play. My opponent had 1 aember and was able to play a niffle grounds. I received one aember when they played it, but I should have received two. I think it was okay that they played the niffle grounds because it had a pip on it which would have brought them up to two, but I only received the one. 

This was the game if it is helpful: https://www.thecrucibletracker.com/games/5c7df600-0fdd-11eb-b0bc-11e54f3d3599

**Comment by Kebay** [comment]
Note that you may not use the Aember gained from the artifact for paying Customs Office; you need to pay the Aember before you would gain it. See [Arcon Arcana](https://archonarcana.com/Customs_Office).
