### ISSUE TITLE
Damage from fight doesn't occur when instigator dies from molephin damage

### ISSUE THREAD

**Issue by xoque** [keyteki/keyteki#2024]
Here's the setup:
I have Knuckles Bolton with 2 damage on my side, next to Little Niff.
The opponent has Molephin on the board and an EDAI "Edie" 4x4.

I fight Knuckles Bolton into EDAI.
My expectations.  I steal one, EDAI dies from being fought into, and Knuckles Bolton dies from the Molephin causing damage from steal.
What happened: I steal one, EDAI is not damaged, and Knuckles Bolton dies.

**Comment by romanogit** [comment]
Did you enable the prompt for simultaneous actions?

**Comment by romanogit** [comment]
Nevermind, I was able to reproduce.

**Comment by romanogit** [comment]
Corner case: e.g. my [ancient bear] assault kills your creature with [soulkeeper], which kills my [jargoogle], which plays [little nif] next to the bear - does it trigger?

![image](https://user-images.githubusercontent.com/2104075/101082442-3839c080-358a-11eb-95dd-1e8c4fbab7ea.png)
