### ISSUE TITLE
Card images don't appear when hovering the card from the match log

### ISSUE THREAD

**Issue by daniel-herrero** [keyteki/keyteki#2027]
**Problem**

The card image doesn't appear in the upper-right corner when passing the cursor over the card link from the match's logs. 
This happens both playing with someone or alone.

I attach an image placing my cursor over the "Ghostly hand" card from the right logs (bottom yelow box), and you can see that instead the image it appears a text (upper yeloow box).

![tco_error](https://user-images.githubusercontent.com/4539017/96695459-f7933880-1389-11eb-8d21-2c20a10def93.jpg)

I have tryied other browsers (Chrome/Firefox/Edge) in Windows 10 with the same results. No one display the image but the card text.

**Comment by SkyJedi** [comment]
Yarp, my bad.  I'll get that fixed
