### ISSUE TITLE
Archimedes ability

### ISSUE THREAD

**Issue by Kalythmos** [keyteki/keyteki#204]
![bug2](https://user-images.githubusercontent.com/53453455/62159766-cc4ea480-b312-11e9-9cf4-b909ce099a21.jpg)
I had an Archimedes (each of theri neighbour get: Destroyed: Archive this creature) in left, a Pip pip in the middle and an Abond, the armoursmith in the right. My opponent use a Key of Dis and Pip pip and the Abond went to the archive. I think Abond should go to discard pile. Whats your opinion?

**Comment by Achocholacek** [comment]
This relates to the "official" ruling that came out about Archimedes.

Essentially, what happens in your scenario, is that Pip was destroyed, got archived, then your battle line collapses, and Abond is next to Archi now, and also gets the "Destroyed:" keyword, and gets archived as a result.

See the Crucible Cast here - https://youtu.be/dMIE8Q3WHnY?t=590

In this particular instance, with the ruling/accepted practice being what it is, I believe things function as they should.

**Comment by Kalythmos** [comment]
OK, thanks, I didnt know that. This is funny, Arhimedes rescue the whole team, except herself

**Comment by Achocholacek** [comment]
You must not read a lot of keyforge discussion on the internet! This was a hot topic for at least two days! :)

Thanks for reporting nonetheless!
