### ISSUE TITLE
Exile Mark of Dis

### ISSUE THREAD

**Issue by AleksandrShepelev** [keyteki/keyteki#2056]
1. Exile creature of house not represented on opponent identity card
2. Mark of dis that creature
3. Kill this creature
Expected result:
Opponent can choose any house
Actual result:
Opponent forced to choose house that is not on identity card and they don't have any cards under control

rule reference:
![image](https://user-images.githubusercontent.com/14818993/98553680-ed8d9700-22b0-11eb-92a0-9a74d7f876ad.png)

4th page of rulebook

**Comment by hydrophilic-attack** [comment]
I'd like to add that this bug also applies to Snag.

I've had games where my opponent took control of one of my creatures that were not on their identity card (via collar of subordination or hypnobeam) and then I fought that creature with snag and killed it.

Next turn, my opponent was locked into that house, despite neither controlling a card that belonging to that house nor having the house on their identity card
