### ISSUE TITLE
Artifacts should be centered

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#2057]
@SkyJedi , @cryogen 
should artifacts also be centered?

![image](https://user-images.githubusercontent.com/2104075/98666378-b6a89700-232b-11eb-90ce-9f6392114706.png)

**Comment by cryogen** [comment]
Nope. Anyone who puts their artifacts in the middle of the board IRL is just wrong :P

**Comment by SkyJedi** [comment]
Harsh 🤣

**Comment by cryogen** [comment]
:D Joking aside, it is this way on purpose. I think it looks cleaner than having the whole thing centered
