### ISSUE TITLE
[Harvest Time] Purging effect is not working

### ISSUE THREAD

**Issue by flagadur** [keyteki/keyteki#2064]
Every time I'm using Harvest time, the log is showing an error prompt and nothing is happening:`

> flagadur uses Harvest Time to purge all cards  with the trait and each player gains Æmber  equal to the number of their cards  purged

> A Server error has occured processing your game state, apologies. Your game may now be in an inconsistent state, or you may be able to continue. The error has been logged.

I chose every time a different trait, but it seems the trait is not applied (in the log, the name of the trait is not displayed).

**Comment by romanogit** [comment]
@flagadur : when you choose the trait, do you press Enter or do you mouse click the prompt button?

**Comment by flagadur** [comment]
I didn't pay attention. I think I might have tried both solution and it wasn't working. I will try to do it again.
