### ISSUE TITLE
Sealed games should not select decks without enhancements

### ISSUE THREAD

**Issue by franul** [keyteki/keyteki#2066]
Hi,
I've got this deck in sealed format. It has 21 enhancements pips but no enhancement was put on the cards and I still managed to get it on sealed.
https://decksofkeyforge.com/decks?title=outlaw%20of%20the%20respited

On screenshot you can see cards e.g Rad Penny that should have some pips but it hasn't.
![Pips](https://user-images.githubusercontent.com/53865810/99472542-1f55cc00-2949-11eb-8caf-48b1ac4c1924.PNG)

**Comment by SteVader** [comment]
> That is an unfortunate reality with MM, not much can be done about it. If someone doesn't add enhancements to their deck and it gets picked by sealed then that's just what happens.

![image](https://user-images.githubusercontent.com/2436007/101147175-ee95b800-3613-11eb-9794-c59d83e5a2e3.png)

**Comment by romanogit** [comment]
Not feasible at the moment. Need to wait for deck verification.

**Comment by romanogit** [comment]
N/A
