### ISSUE TITLE
Sneklifter house bug

### ISSUE THREAD

**Issue by franul** [keyteki/keyteki#2067]
When you steal an artifact from the opponenet and you have house of that artifact in your is one of your three houses then you can actaully use it in shadows and the house that artifact originally belonged to. As Crazy killing machine states it shouldn't be vialable: 
https://www.crazykillingmachinenetwork.co.uk/card-data-v4/Sneklifter

**Comment by romanogit** [comment]
@franul : do you have more details ? We have a test case specific for this scenario, so there must be something different. Was the artifact an "Omni" ability, maybe?

**Comment by franul** [comment]
@romanogit Sorry for issue. This is working correctly. I am sad to admit I've misread the card.
