### ISSUE TITLE
No spectators possible when "rematch" used

### ISSUE THREAD

**Issue by CorayThan** [keyteki/keyteki#2068]
How to recreate:

Two players play a game with spectators. One player selects rematch, the other player accepts. The players are now in a new game. The existing spectators are no longer watching the game. Additionally, when you go to the games list, there is no "watch" button to be able to watch the game. 

Fix:

After players use the "rematch" feature there should still be a watch button for spectators to view the match, which requires the preexisting password if any.

Nice to have:

When rematch is used, the spectators are brought along to spectate the new game.

**Comment by Gimu87** [comment]
Yes, please investigate on this issue.
During torunaments, spectators and judges are not able to enter in the match.

**Comment by AleksandrShepelev** [comment]
https://github.com/keyteki/keyteki/pull/2571/

**Comment by romanogit** [comment]
Fixed by https://github.com/keyteki/keyteki/pull/2571
