### ISSUE TITLE
No more bullies and jerks in TCO please

### ISSUE THREAD

**Issue by Blackout1991** [keyteki/keyteki#2084]
![Captura de pantalla 2020-11-30 a las 8 31 23](https://user-images.githubusercontent.com/75242026/100580852-fa693d80-32e6-11eb-9a4f-d918e986fd6d.png)

This was my log this morning... Players like The2R shows the worts part of playing... Can you ban these people or something?

Thanks

**Comment by cryogen** [comment]
Thanks for the report. I would suggest making use of the block feature that you can find in the top right hand corner of the site by clicking on your name/picture.
