### ISSUE TITLE
Continuous harassment

### ISSUE THREAD

**Issue by Diggie07** [keyteki/keyteki#209]
The following accounts are all run by the same person, or group of people. They continue to join my games and harass me. They have registered my decks so they show invalid.

cryogenabitch3 |  
ferrisman154 |  
gstringtheory |  
hoax416 |  
knightreptile

Just a heads up. It's getting tiring and I don't know of any other way to seek help.

**Comment by Achocholacek** [comment]
I imagine this is incredibly frustrating. We're working on ways to deal with this, which I know isn't a great answer, but it's the best I can offer right now.
