### ISSUE TITLE
Epic Quest forging for opponent

### ISSUE THREAD

**Issue by nakazanie** [keyteki/keyteki#2098]
![image](https://user-images.githubusercontent.com/75387797/100912027-bcb71100-34ae-11eb-92b2-0d142cda9c01.png)

So, this happened. I used Epic Quest and it forged a key for my opponent, winning him the game. Maybe something to do with the fact he used Nexus two turns before in order to prevent me from winning?

**Comment by romanogit** [comment]
@nakazanie#8391 : reproduced the bug
Trying to fix :)
