### ISSUE TITLE
Enrage should prevent Ghosthawk's reap

### ISSUE THREAD

**Issue by dukman00** [keyteki/keyteki#2107]
Based on the latest Crucible Cast (https://archonarcana.com/Crucible_Cast#Episode_25):

> "I play Ghosthawk between two ready friendly creatures; one is Stunned, the other is Enraged. What happens?
> Ghosthawk's Play: ability will cause the neighbors to reap. The Stunned creature will exhaust and clear its stun. T**he Enraged creature will not be able to reap at all, and will remain ready.**"

Right now, it is possible to reap with Ghosthawk's enraged neighbors. Not sure if this change should be applied to any additional cards besides Ghosthawk.

**Comment by romanogit** [comment]
Does other effects also apply?

- if Little Rapscal is in game, can we reap?
- if the creature has Detention Coil and is enraged, can it reap?
- The enraged creature is not on a flank and the only opponent creature has Camouflage, can it reap?
...
