### ISSUE TITLE
Neffru

### ISSUE THREAD

**Issue by AdamxPaul** [keyteki/keyteki#2112]
Neffru - Each time a creature is destroyed, its owner gains 1a.
Harbinger - Destroyed: Destroy each creature.

I have a deck with these two together, and many times when Harbinger's effect triggered, the game worked correctly and gave out NO aember to either player.  This is correct because timing rules state it goes 1) Destroyed Effects 2) Creatures are destroyed 3) "After destroyed" effects.  Neffru's effect would be in step 3, but he's already dead at this point so it doesn't trigger.

In one game today it didn't work that way, however.  I had switched to "Prompt for simultaneous triggers" to try that out, and when Harbinger's effect went off, it prompted me to order the Neffru triggers on my opponent's creatures.  Not only are these triggers not simultaneous with his destruction, but there was no option to choose Neffru as first to die (which would have ended his effect and given me an aember).  I ended up getting no aember, and my opponent got 3 for their 3 creatures destroyed in the board wipe.

I turned off the option to prompt for simultaneous triggers, played again, and it worked as intended.

**Comment by romanogit** [comment]
@AdamxPaul : what caused Harbinger to trigger? Was it a damage card (Red Alert, for example) or a board wipe?

Did the destroyed creatured have armor?

We saw a bug like this recently.

**Comment by AdamxPaul** [comment]
If I remember right (this was last week), I killed Harbinger with Obsidian Forge (artifact: destroy X creatures, etc.), so not damage.  Harbinger has armor, but I don't recall if the other creatures did.  I'm fairly sure at least one of them did not have armor.  All of them generated an aember from Neffru.

**Comment by romanogit** [comment]
Thanks, this will help troubleshooting.

**Comment by romanogit** [comment]
It is difficult to find the problem without the game log. I created test cases and all passes.

**Comment by AdamxPaul** [comment]
I'll play the deck some more today and see if I can recreate it.  If I do, just copying the game chat with the little button at the bottom and pasting that here, would that help?

**Comment by romanogit** [comment]
yes, that would be perfect.

**Comment by AdamxPaul** [comment]
I just tried it twice, once killing Harbinger with Obsidian Forge, and once with Etaromme, and it worked correctly both times, no prompts.  So I guess it was just a fluke (or I hallucinated it).  Sorry to lead you on a wild goose chase!

**Comment by romanogit** [comment]
maybe your opponent had Truebaru :)

Thanks for taking the time to retest. We have a more complete test suite now 👍
