### ISSUE TITLE
Damage Bonus Icon not affected by card's passive text

### ISSUE THREAD

**Issue by mavelata** [keyteki/keyteki#2125]
Maleficorn (MM, Dis)
Creature
Enhance DDDD.
After an enemy creature is dealt damage by a D bonus icon, deal 1D to that creature.

In my deck, it has been enhanced with a D bonus icon.
Bonus Icons are resolved once the card is in play, so it should 1D for the icon plus 1D for the passive ability.
However, I have played it in several games and what happens is that first the damage is dealt and only then is the card in play.
I am not copying log bc I think it's pretty clear.
Thanks!

**Comment by romanogit** [comment]
Without the gamelog it is difficult to find the bug. Did you target a friendly creature?

![image](https://user-images.githubusercontent.com/2104075/101659638-0f4f7a80-3a25-11eb-8762-f68857e5b58f.png)

We have quite a few test cases for Maleficorn and this is a very basic bug you are reporting and is covered in the test cases.

**Comment by mavelata** [comment]
I was pretty sure it didnt work a couple of games but I now recheked and it worked... so i must have missed something... sorry to have made you lose your valuable time. Thanks anyway, your work is admirable! also thanks for being there for issues, so good for the community!
