### ISSUE TITLE
First Blood assigns damage 1 by 1, instead of 2 at a time

### ISSUE THREAD

**Issue by dukman00** [keyteki/keyteki#2138]
"Play: Deal 2D for each friendly Brobnar creature. You may divide this damage among any number of creatures."

**Comment by UltraUltraUltra** [comment]
> "Play: Deal 2D for each friendly Brobnar creature. You may divide this damage among any number of creatures."

The amount of damage is 2 per friendly Brobnar creature, but the damage can be divided among any number of creatures, so the damage is done in steps of 1.

The 2 is just to calculate how much damage, not how the damage is assigned.

**Comment by romanogit** [comment]
Damage has to be one by one, this is correct.
