### ISSUE TITLE
Strange Gizmo + Forgemaster Og

### ISSUE THREAD

**Issue by bensissel** [keyteki/keyteki#214]
I had Strange Gizmo, opponent had Forgemaster Og with 3 amber.
from the Log:
End of turn 4
BHawk: 8 Æmber  peter1983: 3 Æmber 
Turn 4
Key phase - BHawk
BHawk forges a key, paying 6 Æmber 
peter1983 uses Forgemaster Og to make peter1983 lose 3 Æmber 
BHawk uses Strange Gizmo to destroy each creature and artifact.

What happened was Opponent Lost all of their aember, I had 2 amber left over. Not sure if it's just forgemaster og that's bugged, or that interaction. If I as active player get to choose the timing (because they both have the same timing) I would naturally default to blowing up the world with strange gizmo before forgemaster's effect can take place. But My opponent definitely should not have lost all of their amber.

**Comment by Achocholacek** [comment]
This is a twofold issue:
1) Og is bugged - but we should have her fixed soon.
2) If you don't select the "Prompt to Order Simultaneous Abilities" option under Profile > Settings, you won't be given a chance to select the order. (Although I haven't specifically tested this scenario against that setting yet, so it might not actually do anything.)

Thanks for the log paste and the details - really makes our job a lot easier!

**Comment by bensissel** [comment]
I do have the prompt simultaneous abilities enabled.
