### ISSUE TITLE
Ghosthawk played next to a ready Philophosaurus didn't trigger the Philophosaurus' reap ability.

### ISSUE THREAD

**Issue by thechillturtle** [keyteki/keyteki#2169]
Title sums things up. Played hawk between two dinos, one of which was philophosaurus. Both were able to reap, but Philo's reap effect didn't trigger.

**Comment by blinkingline** [comment]
I wasn't able to replicate this in testing.  I wonder if the player's deck might have been empty, which wouldn't allow Philophosaurus' Reap: ability to resolve.

**Comment by thechillturtle** [comment]
Yep, empty deck was probably the reason why. Appreciate your help, thanks.

**Comment by romanogit** [comment]
Closing
