### ISSUE TITLE
When a creature has multiple Reap: abilities, Replicator cannot choose between them

### ISSUE THREAD

**Issue by blinkingline** [keyteki/keyteki#2171]
This is the same issue as in #680, which has already been closed.

When you use reap with [Replicator](https://archonarcana.com/Replicator) and resolve its Reap: ability, if you select a creature that has multiple Reap: abilities, you are not presented with a way of choosing which Reap: ability you would like to resolve. 

I tested it using Replicator and [Bot Bookton](https://archonarcana.com/Bot_Bookton) upgraded with [Academy Training](https://archonarcana.com/Academy_Training).  When Replicator reaps, and I select Bot Bookton, I should be able to choose between the two Reap: abilities that Bot Bookton has. Instead, Replicator automatically resolved the printed Reap: ability of Bot Bookton.

**Comment by Kebay** [comment]
Probably somewhat related, when a creature has a single reap ability granted by an upgrade, Replicator does not copy the ability at all. Noticed this in a game with some blaster on Khrkhar.
