### ISSUE TITLE
(Dis) Shadow of Dis is "blanking" Autocannon

### ISSUE THREAD

**Issue by r0gershrubber** [keyteki/keyteki#218]
My opponent's Shadow of Dis temporarily stopped Autocannon from damaging my creatures as they entered play.

**Comment by hydrophilic-attack** [comment]
I guess this bug affects other artifacts as well? I just had a game where my opponent played shadow of Dis, and next turn it seems like my grump buggy did nothing. I was able to forge at 6 despite my opponent having multiple 5+ power creatures out
