### ISSUE TITLE
Lamindra's neighbors doesn't gain elusive

### ISSUE THREAD

**Issue by Pekkhyu** [keyteki/keyteki#221]
Lamindra's neighbors doesn't gain elusive

**Comment by Achocholacek** [comment]
Do you remember anything about board state? I cannot recreate this locally and I have written a test case that it passes with flying colours.

Any additional detail would help!

Thanks.

**Comment by Pekkhyu** [comment]
I use the Niffle grounds ability on another creature that has taunt. Then, I attacked one of the two Lamindra's neighbors and crucible make me deal the damage. But it wouldn't, because I target another creature.

**Comment by Achocholacek** [comment]
Ah this appears to be a bug with Niffle Grounds.

Will investigate!
