### ISSUE TITLE
Replicator and opponents Ultra Gravaton

### ISSUE THREAD

**Issue by Gonshuujinsama** [keyteki/keyteki#2225]
when reaping with Replicator if I target my opponents Ultra Gravaton it removes a card from their Achieves and lets me purge a creature, surely it should be from my archive not my opponents?

**Comment by romanogit** [comment]
I think there is something more that is missing. I was not able to reproduce:

![image](https://user-images.githubusercontent.com/2104075/105714309-ef9fe300-5efa-11eb-82c9-33a463bffdb4.png)

**Comment by romanogit** [comment]
Even if my opponent takes control of my UG and I use my replicator to trigger its ability, it still works:

![image](https://user-images.githubusercontent.com/2104075/105714473-270e8f80-5efb-11eb-9a78-610f391da811.png)

**Comment by romanogit** [comment]
Also tried taking ownership of replicator and also works, so it is not a "player/opponent" object error. Do you have the play log?

**Comment by Gonshuujinsama** [comment]
https://youtu.be/Mlq4q04y1zE for the game

**Comment by Gonshuujinsama** [comment]
![Screenshot (213)](https://user-images.githubusercontent.com/52086686/105726171-afa02680-5f21-11eb-8b5a-f86752ee451a.png)
should be able to see the chat log and board state that its my opponents lightouts that was discarded and their angwish
