### ISSUE TITLE
Action that causes playing encounter suit triggers it

### ISSUE THREAD

**Issue by poeticmatter** [keyteki/keyteki#2227]
The scenario that was observed:
Exhume targeting Murkens
Murkens plays card from top of deck
Top card is Encounter Suit
Encounter Suit played on Archimedes
Archimedes gets warded by Encounter Suit

Archimedes should not be warded, because Encounter Suit says before the action is resolved, which is a point that has passed.

I suspect a Wild Wormhole playing Encounter Suit will have the same result but I have not tested.

**Comment by romanogit** [comment]
I believe the same happens if you Murkens a Soft Landing. Murkens would enter play ready.

**Comment by poeticmatter** [comment]
It's true that happens, I am not sure it is wrong.
