### ISSUE TITLE
TCO is not ordering properly enhancements on cards

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#2236]
Assuming there is a pre-defined order (alphabetical), it should save and present the enhancements correctly.

Assuming the order is defined during deck import, it should keep the order of the icons clicked by the user.

TCO groups icons but follows the order of import (first icon clicked is the first group). E.g., if I click, Capture, Amber, Capture, TCO presentes as Capture - Capture - Amber

If option 1) above, it should presente as Amber - Capture - Capture or, at least keep the order (option 2) Capture - Amber - Capture

**Comment by eorlo** [comment]
the MM deck enhancement loading page may be need to also be adjusted to match the selection (option1 or 2), as currently you cannot tell what order you have selected the icons
