### ISSUE TITLE
Scowly Caper Does not Kill Neighboring Creatures

### ISSUE THREAD

**Issue by weakworse** [keyteki/keyteki#225]
Multiple times in the same game played Scowly Caper and at the end of my turn it did not kill the opponent's creature. It happened the turn after I played it as well.

**Comment by hydrophilic-attack** [comment]
He will destroy a creature at the end of his controller's turn. Meaning at the end of your opponent's turn since your opponent controls him

**Comment by tgreaves** [comment]
Rules question has been answered.
