### ISSUE TITLE
Bear Flute is allowing a player to return an Ancient Bear from Discard when there is an Ancient Bear in play

### ISSUE THREAD

**Issue by UltraUltraUltra** [keyteki/keyteki#2255]
Bear Flute allows you to either heal an Ancient Bear in play or if there are no Ancient Bears in play, search your Deck and Discard for them and put them into your hand (and if you do so, shuffle your Deck into your Library).  My opponent healed an Ancient Bear and then took another Ancient Bear from their Discard and put it into their hand (but it didn't shuffle their Discard into their Deck).

![image](https://user-images.githubusercontent.com/55008319/106928063-b4778e00-670a-11eb-9d0d-0eb65880926a.png)

**Comment by romanogit** [comment]
I think it might be related to using it previously.
