### ISSUE TITLE
Minor issue - Incubation Chamber log message is incorrect when opponent uses it but does not archive a card

### ISSUE THREAD

**Issue by UltraUltraUltra** [keyteki/keyteki#2263]
Minor log issue but the log says player uses Incubation Chamber to archive Incubation Chamber if they use the card but do not archive a card.

![image](https://user-images.githubusercontent.com/55008319/107365433-b360ab00-6ad4-11eb-8fb9-1636713a5ed2.png)

**Comment by romanogit** [comment]
I think the opponent actually archived a card, but it was incorrectly logged.

**Comment by romanogit** [comment]
Nope, you are right, I was able to actually replicate it.
