### ISSUE TITLE
Z.Y.X. Researcher doesn't prompt you to choose if your deck or discard is empty

### ISSUE THREAD

**Issue by UltraUltraUltra** [keyteki/keyteki#2264]
This was probably implemented to make things easier, but there may be occasions when you don't want to archive a card and if your deck or discard pile is empty, should there not still be the option to choose where you archive from?

![image](https://user-images.githubusercontent.com/55008319/107370666-2f5df180-6adb-11eb-8b6a-f4a1138a065d.png)

**Comment by romanogit** [comment]
Definetly related to this PR:
https://github.com/keyteki/keyteki/pull/1841

I am not sure I reviewed Z.Y.X. Researcher. If not, anyhow, it can only be fixed after the PR.

**Comment by romanogit** [comment]
This is also fixed by PR #1841. Need to wait push to server.
