### ISSUE TITLE
Maverick Pitlord Functionality

### ISSUE THREAD

**Issue by awmountain52** [keyteki/keyteki#2271]
Hi there,
I was hoping the maverick Pitlord functionality could be fixed. Currently TCO treats maverick Pitlords like regular Pitlords, requiring the player to call house dis even though they have a maverick Pitlord with no house dis on their archon card and no dis cards in play. Thank you so much for your consideration!

The FFG rulebook as stated on [Archon Arcana](https://archonarcana.com/Pitlord) states:
"I have a maverick Pitlord in play in a deck without house Dis. Am I forced to choose house Dis as my active house?
No. You cannot choose an active house unless it is on your identity card or you control a card of that house. This restriction overrides Pitlord’s effect, allowing you to choose any of your houses as your active house.
Source: Rulebook"

**Comment by romanogit** [comment]
Hello @awmountain52 ,
did this problem happen to you recently?

**Comment by awmountain52** [comment]
Hi there,
I just played a game and the maverick pitlord now seems to work properly. I will close this issue. Thank you!
