### ISSUE TITLE
"Borrow" and Shards

### ISSUE THREAD

**Issue by UltimoFox** [keyteki/keyteki#2274]
My opponent took control of my Shard of Greed with their "Borrow", but every time they used it they gained 2 aember instead of the 1 (no other shards were ever in play all game, my Shard of Knowledge was the only other shard in either of our decks). The message in the chat also said "used Shard of Greed to gain 2 aember". Assuming it's an issue with counting itself twice after having its ownership changed, but otherwise, no idea what's going on there.

**Comment by UltimoFox** [comment]
(I did take a screenshot but accidentally overwrote it, and I closed the game already, my apologies. I tried to give as much information here as possible though, since at the time minimal creatures were in play and the issue was consistent.)

(If it helps, the opponent did have Font of the Eye in play too, as well as shadows creatures like Mutant Cutpurse and Rad Penny.)

**Comment by romanogit** [comment]
I checked the code and there seems to be a bug. The card is not correctly implemented to consider `Borrow` or `Remote Access`. I will work on it.
