### ISSUE TITLE
Please move "rematch" etc to another part of screen

### ISSUE THREAD

**Issue by AleksandrShepelev** [keyteki/keyteki#2276]
it is enhancement, not an issue

this happens very frequently: when you clicking and working with your table, opponent concedes and you clicking accidentally rematch or rematch and swap decks. If opp is slow enough, you can write sorry missclick. if opp is fast enough, you have tough time explaining about missclick.

So please move these buttons :)

**Comment by SkyJedi** [comment]
dupe of #2226
