### ISSUE TITLE
Rulings for Shard of Hope and Shard of Pain

### ISSUE THREAD

**Issue by Chickin1** [keyteki/keyteki#2278]
Currently Shard of Hope and Shard of Pain are able to choose multiple targets for there abilities (Shard of Hope limiting one capture per target which is frustrating because you need three creatures to get the full value and frustrating for the opponent because they have to kill 3 creatures just to get there amber back) This isn't how these cards work. 
![shard-of-hope](https://user-images.githubusercontent.com/79659518/109206287-8232dc80-775c-11eb-8d05-524a172bf7f2.png)
![435_104_F8RRR7CCG94M_en](https://user-images.githubusercontent.com/79659518/109206302-865efa00-775c-11eb-8f62-20e6b1905e1c.png)

Shard of Hope and Shard of Pain are supposed to only target one creature so one creature would capture equal to the # of shards (Shard of Hope) and one creature would be delt # of damage equal to the number of shards (Shard of Pain). I hope this will be a quick fix :3

![shard of hope](https://user-images.githubusercontent.com/79659518/109200966-13eb1b80-7756-11eb-9425-5227af58c4a3.jpg)

**Comment by romanogit** [comment]
@Chickin1 ,
I do not think that's right. Both Shard of Hope and Shard of Pain should allow you to target the same or a different creature per shard.
They were not implemented equal and this was recently fixed.

**Comment by Chickin1** [comment]
Ok thanks for clarifying that. In that case there is still a problem. Like in the picture, it shows that shard of hope won't allow me to capture multiple amber on a creature and like you said that sould be the case. Shard of pain works as intended but not for shard of hope. I have to choose 3 different creatures like seen in the picture.

**Comment by romanogit** [comment]
Right, it has been fixed in the above PR.

**Comment by Chickin1** [comment]
https://drive.google.com/file/d/1ZWQHH6sc0a9vMtOAzNKHMwCk5LmkjEj-/view?usp=sharing
I got a video of this problem. Can you please confirm if this is how Shard of Hope is supposed to work.
