### ISSUE TITLE
Archimedes and Collar of Subordination

### ISSUE THREAD

**Issue by Jarimy123** [keyteki/keyteki#229]
If I take control of an opposing creature with Collar of Subordination, put it next to Archimedes, and then that creature is destroyed it gets sent to my archives and not the owner of the card.  It should go to my opponent's archives.

**Comment by stebsteb** [comment]
Yes this is a bug, it should go to the owner's (not controller's) archives: "If a card that has changed control leaves play for any reason, it moves to its owner’s appropriate out-of-play zone."

**Comment by romanogit** [comment]
Keeping #552 opened
