### ISSUE TITLE
Abond the armorsmith : action armor persistent

### ISSUE THREAD

**Issue by skrohmagnon** [keyteki/keyteki#237]
Last game, I used action from abond to give 1 armor for other friendly creatures for the remainder of the turn. A the beginning of the next turn, it was still active.

**Comment by Achocholacek** [comment]
I can't reproduce this and the test suite passes with no issues. Are you sure you weren't just seeing his passive +1 armor bonus that requires no action to gain?

**Comment by skrohmagnon** [comment]
I'm sure because a creature without armor has 2. But I have no screenshot.

**Comment by Achocholacek** [comment]
Do you remember anything else about the board state? I've tried a few different scenarios and cannot recreate this.

**Comment by cryogen** [comment]
Closing this as not reproducible.  Please reopen with more information (particularly screenshots) if you can get any

**Comment by kyleswartley10** [comment]
@skrohmagnon hey man, I was trying to get your Keyforge stuff if you still have it
