### ISSUE TITLE
Look What I Found! doesn't display all four selected cards in the log

### ISSUE THREAD

**Issue by Tutenkharnage** [keyteki/keyteki#2379]
"Look What I Found!" allows a player to select one of each type of card from discard and return it to hand, but the chat only showed Mindfire, an action, and then declared that LWIF had omega, ending the step. All four cards should appear in the log, as this would be open information during a game, since the player who plays LWIF would have to prove that only one card of each type was selected.

**Comment by romanogit** [comment]
This was recently fixed and duplicated https://github.com/keyteki/keyteki/issues/2282

I will keep this open until I confirm the build is live

**Comment by Tutenkharnage** [comment]
Thanks! I searched for this topic last night but used the default "is:issue is:open" tag. I'll try to be more careful next time :)

**Comment by romanogit** [comment]
Should be deployed now.
