### ISSUE TITLE
Annihilation Ritual purges creature-upgrades

### ISSUE THREAD

**Issue by Kebay** [keyteki/keyteki#2383]
[Annihilation Ritual](https://archonarcana.com/Annihilation_Ritual) seems to purge the “may be played as an upgrade instead of a creature" cards even when they are played as an upgrade.

However, they should not be purged: While in play, they are considered upgrades and 

> If cards leave play while resolving an ability, later instructions in the same ability refer to the cards as they were immediately prior to leaving play.

makes it pretty clear that Annihilation Rituals does not consider them as creatures.

This happened to me in a game with [CALV-1N](https://archonarcana.com/CALV-1N), but I suspect that all creature-upgrades are affected. I also had two Annihilation Rituals in play, not sure whether that matters.

**Comment by Kebay** [comment]
Regarding the rules question label: Before posting here, I asked how this should work in the Sanctumonious rules channel, see https://discord.com/channels/563737400275107920/588586239997902858/827850954358652959, and then cited the (in my opinion) relevant rules excerpt. Of course, that channel does not hold any official authority concerning rule questions, but I am quite confident that this is indeed a bug and not a rules misunderstanding.

**Comment by romanogit** [comment]
Should have been fixed by https://github.com/keyteki/keyteki/pull/3495
