### ISSUE TITLE
One Stood Against Many does not respect gameplay effects/restrictions

### ISSUE THREAD

**Issue by Achocholacek** [keyteki/keyteki#241]
via @stebsteb on Jadiel's GitHub:

Used One Stood Against Many on a ready creature, with three valid attack targets on the field. After surviving the 3 fights the result was that the creature stayed ready when it should have been exhausted (by the third fight).

Used One Stood Against Many on an exhausted creature, with only two valid attack targets on the field. After surviving the 2 fights the result was that the creature was exhausted when it should have been readied by the third instance of "ready and fight".

**Comment by CorayThan** [comment]
I experienced this issue too. With no fight targets creature was not readied.
