### ISSUE TITLE
Submersive Principle does not work on high tide

### ISSUE THREAD

**Issue by AlexanderBerry95** [keyteki/keyteki#2416]
Hey, I just used submersive principle while I had the high-tide and nothing happened. Not tested results with low tide.

**Comment by Lynzkar** [comment]
Functioned for me during a game i just had, could perhaps be other factors as well

**Comment by Osarek** [comment]
That works for me also

**Comment by Osarek** [comment]
> Functioned for me during a game i just had, could perhaps be other factors as well 

That works for me also

**Comment by AlexanderBerry95** [comment]
Yes, I was unable to re-produce in the next game. I will report back with more info when it happens again
