### ISSUE TITLE
Poltergeist / Tentacus Interaction

### ISSUE THREAD

**Issue by Achocholacek** [keyteki/keyteki#242]
From @mhoraigh on Jadiel's Github:

Poltergeist/Tentacus interaction - I used Poltergeist on my opponent's library of babble while I had a tentacus in play.
It appeared to charge my opponent for the artifact use.

**Comment by Achocholacek** [comment]
@mhoraigh - do you remember boardstate on this at all? I can't recreate this.

**Comment by mhoraigh** [comment]
There were no cards on the table that would have interacted with this. It’s
also possible my opponent was mistaken.

**Comment by cryogen** [comment]
Closing as not reproducible.  Please reopen with further information if it still occurs.
