### ISSUE TITLE
T3R-35A seems to give the effect to neighbors when used as upgrade

### ISSUE THREAD

**Issue by CantonaMA** [keyteki/keyteki#2420]
Using t3r-resa Star alliance card as an upgrade which should allow upgraded creature to be used as if in house of either neighbour, instead I found the neighbors of the upgraded creature could be used as if in the house of either neighbour.

**Comment by danfewell** [comment]
Not sure if this help in the process but all my cards were ready to use regardless of house. Not sure the neighbouring is working 100%, started ok, but after a couple of turns all Creatures were available to use

**Comment by sdcinglis** [comment]
It appears to me as though T3R-35A's effect is applying to all creatures on the board and not just herself
