### ISSUE TITLE
Lieutenant Valmart increases key cost of mine, too.

### ISSUE THREAD

**Issue by jakelea99** [keyteki/keyteki#2423]
Lieutenant Valmart: Play/Fight/Reap: If the tide is high, keys cost +3 during your opponent's next turn.

However, Valmart increases both's key cost now.

**Comment by romanogit** [comment]
That's working as expected. Both keys are increased cost during opponent's next turn, however, the effect has a bug which it does not wait to start until opponent's turn, it applies immediately.

**Comment by jakelea99** [comment]
But it has problem with key cheat card like 'Forging an Alliance'... right?

**Comment by jakelea99** [comment]
Oh, I see. Thanks for it.

**Comment by jakelea99** [comment]
It shares with same textbox with Sensor Chief Garcia. And, it mentioned that increase key cost of 'your opponent's'.
