### ISSUE TITLE
Grand Alliance Council not working properly

### ISSUE THREAD

**Issue by Blaph** [keyteki/keyteki#2427]
Grand Alliance Council says "Play: Choose a creature from each house. Destroy each creature not chosen", but doesn't allow choosing if the creatures in play are the only ones of their house (In our case: floomf for me, rustmiser for my opponent).
![Bug here](https://user-images.githubusercontent.com/30389835/115024442-64face80-9ec0-11eb-94fe-d7a153e58d5a.png)

Chat: https://pastebin.com/hf5H7dRy

**Comment by cmorenoserrano** [comment]
This happened to me as well just now. It costed me the game, but it's fine.

**Comment by ryanch** [comment]
taking a look at this one

**Comment by ryanch** [comment]
added test case to reproduce this. now working on fix.

**Comment by ryanch** [comment]
I have a fix, working to get my env working again to make a PR for it.

**Comment by Osarek** [comment]
seems to be resolved :D
