### ISSUE TITLE
Omnipus and witch of the dawn

### ISSUE THREAD

**Issue by albo95** [keyteki/keyteki#2428]
When i played Omnipus it discarded 16 cards instead of 8 and didn't played any tentacled discarded in this way. Also the play effect of witch of the dawn doesn't apply. Anyway thank you for all your work :)

**Comment by SkyJedi** [comment]
witch is a dupe of #2426

**Comment by cryogen** [comment]
Reopening as it's still broken. The counter is now correct, but it's still an array so you need to do .length on it

**Comment by SkyJedi** [comment]
#2487

**Comment by romanogit** [comment]
Deployed
