### ISSUE TITLE
Soulkeeper not firing if upgraded creature is sacrificed.

### ISSUE THREAD

**Issue by Achocholacek** [keyteki/keyteki#243]
From @rodigee on Jadiel's Github:
-Sacrifice a creature that has the upgrade Soulkeeper
Result: The most powerful enemy creature does not get destroyed.

**Comment by Achocholacek** [comment]
@Rodigee - do you remember board state for this? I can't reproduce it locally.

**Comment by cryogen** [comment]
I don't think this was ever reproduced
