### ISSUE TITLE
Whirlpool only triggering on one side

### ISSUE THREAD

**Issue by j00nbrains** [keyteki/keyteki#2436]
I played whirlpool and my taniwha moved to my opponent but his creature didn't move to me. 

![bug 2](https://user-images.githubusercontent.com/68278308/115051209-7948c680-9ed4-11eb-81fe-c2cfa74ddd23.JPG)

**Comment by Toeofdoom** [comment]
I think whirlpool is meant to transfer just 1 creature per turn, did it work properly on the following turn? I can't tell from the screenshot but it looks like ancient bear switched control at some point.

**Comment by j00nbrains** [comment]
Yes apologies I re read it this evening.

**Comment by romanogit** [comment]
closing
