### ISSUE TITLE
Selective Preservation didn't allow for selecting Taniwha

### ISSUE THREAD

**Issue by j00nbrains** [keyteki/keyteki#2437]
I played selective preservation and chose my power 2 and 3 creatures which killed the opponents creatures but it never gave me the option to select Taniwha and thus kill all other 8 power creatures (although there weren't any)

![bug 1](https://user-images.githubusercontent.com/68278308/115051352-a4331a80-9ed4-11eb-928f-fa2b8d46ec56.JPG)

**Comment by Pickman77** [comment]
The card  seems to be only saving the cards that are selected (because  there is more than one in play) and destroying the rest by default instead of leaving them in play

**Comment by SkyJedi** [comment]
dupe #2434
