### ISSUE TITLE
(Shadows + dis) Sneklifter

### ISSUE THREAD

**Issue by Dzak** [keyteki/keyteki#244]
My deck has house dis. I played Sneklifter in shadows turn and took control of wretched doll. After in same turn I could use it. I shouldnt have possibility to use it this turn, because it should be consider as dis house, not shadows

**Comment by Achocholacek** [comment]
Do you remember anything else about the board state? I cannot recreate this locally.

**Comment by Dzak** [comment]
Unfortunately not.Also, I am not sure if there was something unusual on the board

**Comment by Achocholacek** [comment]
I'm going to close this for now. If it reoccurs please open a new ticket with as much info as you can!

Thanks!
