### ISSUE TITLE
Orb of Wonder is...brobnar?

### ISSUE THREAD

**Issue by Blaph** [keyteki/keyteki#2443]
I admit this made me laugh a lot

Chat: 
![bug here](https://user-images.githubusercontent.com/30389835/115085442-d8293280-9f0a-11eb-99da-e07cac9c2c2c.png)
https://pastebin.com/yEjP4iDw

**Comment by Osarek** [comment]
maybe you can add here your deck name for easily reproduction?

**Comment by Blaph** [comment]
Sure, here's the deck
https://decksofkeyforge.com/decks/4b6148b9-ed89-48a6-9138-cfb08a26024c

**Comment by romanogit** [comment]
This issue has a PR, but pending review and deploy. Once done, you will need to delete and reimport your deck.
