### ISSUE TITLE
Whirlpool

### ISSUE THREAD

**Issue by dick-roland** [keyteki/keyteki#2445]
whirlpool is not working correctly. it puts the creature from the right flank to the opponents right instead of their left flank.

**Comment by SkyJedi** [comment]
merging with #2436

**Comment by Toeofdoom** [comment]
Is it possible to get screenshots of this to confirm? Left/right flank can be a bit confusing on tco because opponents cards aren't rotated the way they would be in real life (your opponents left flank appears on the left of your screen)
