### ISSUE TITLE
Rooftop laboratory image is not properly displayed

### ISSUE THREAD

**Issue by Godzil** [keyteki/keyteki#2448]
With the english language:

![image](https://user-images.githubusercontent.com/569162/115086294-e031a400-9f03-11eb-8892-2aef76ca705b.png)

The card:
![image](https://cdn.keyforgegame.com/media/card_front/en/496_009_QRFRQ899JRH5_en.png)

**Comment by Osarek** [comment]
Problems appears in English. 
not in French, didn’t check other languages

**Comment by Godzil** [comment]
I've checked other languages, but the one that do not work basically have no images for all the new cards, so I didn't reported for them

**Comment by Godzil** [comment]
Just done a quick check, the card link to the image seems to be good, something may have went wrong during import because when the client request the image it get a 0 byte long reply:

<img width="618" alt="image" src="https://user-images.githubusercontent.com/569162/115147003-eaad8400-a050-11eb-8f11-83977f3c780c.png">

**Comment by romanogit** [comment]
@cryogen : might need to run fetchdata again or manually download just this image, right?

**Comment by cryogen** [comment]
Redownloaded the image, all good now
