### ISSUE TITLE
Creatures enters play enraged at start of game when Pestergrove is in the Deck

### ISSUE THREAD

**Issue by HalifBakri** [keyteki/keyteki#2452]
First round, Pestergrove is not in hand or on the board. Any creature that enters play is enraged.

Karesh [deck](https://www.keyforgegame.com/deck-details/5f2b4524-e1bc-4e23-9079-a615f546b3e6)
Viller [deck](https://www.keyforgegame.com/deck-details/a63ec7df-b683-4cbc-bf5c-87e774a71729)

## Game Chat

Karesh brings Chancellor Handreader to The Crucible
Viller brings Ubercurve's Underwhelmed Genius to The Crucible
 Karesh has connected to the game server
 Viller has connected to the game server
Karesh chooses to go second
Karesh is shuffling their deck
Karesh draws 6 card  s to their maximum of 6
Viller is shuffling their deck
Viller draws 6 card  s to their maximum of 6
Viller draws 1 card 
Key phase - Viller
Viller does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Viller
Viller chooses logos  as their active house this turn
Main phase - Viller
Viller plays EDAI “Edie” 4x4
Viller uses EDAI “Edie” 4x4 to archive a card

## Board

![Pestergrove](https://user-images.githubusercontent.com/1030409/115089753-4a057a00-9f13-11eb-8130-bab7d849e211.png)

**Comment by SkyJedi** [comment]
Dupe #2418

**Comment by HalifBakri** [comment]
My bad, the other issue was called pestergrAve I was looking for pestergrOve. Sorry :)
