### ISSUE TITLE
The ability to raise the Tide should be available in every match regardless of the decks used

### ISSUE THREAD

**Issue by UltraUltraUltra** [keyteki/keyteki#2455]
As the Tide mechanic is part of the KeyForge rules now, shouldn't all matches have the option to raise the Tide?

While it's unlikely a player will want to change the Tide if neither player is playing a Dark Tidings deck, it is possible there that there will be times when a player might want to change the Tide (e.g. because their opponent has an anomaly version of "Valoocanth" in their Worlds Collide deck or the active player wants to gain chains to prevent them drawing a card because there is a "Gambling Den" in play).

**Comment by SteVader** [comment]
The quick start rules explicitly state that “The tide is not used during games in which neither deck includes a tide card”.

![image](https://user-images.githubusercontent.com/2436007/115110930-a600ea80-9f75-11eb-86af-38dcdda9db8b.jpeg)

**Comment by UltraUltraUltra** [comment]
Apologises.  This was raised on the basis of this ruling I saw (please see below), but I've now seen the quick rules (as posted above) and realise that it works correctly as currently implemented.

![174423894_10222853831247176_1313696803337992634_n](https://user-images.githubusercontent.com/55008319/115138023-83c4a680-a021-11eb-84ae-4a6a329bd696.jpg)

**Comment by UltraUltraUltra** [comment]
It would appear the FFG have gone back on this ruling and the Tide is once again considered to always available for either player to raise regardless of whether or not either deck comes with a Tide card.

![183553517_10161587173617837_6749685354584714762_n](https://user-images.githubusercontent.com/55008319/118346635-d5832280-b534-11eb-9aac-b4cf9fcf02b0.jpg)
