### ISSUE TITLE
Operative Espion does not allow to use itself when i raise the tide

### ISSUE THREAD

**Issue by Osarek** [keyteki/keyteki#2457]
My turn is Shadow,
I raise the tide, and i cannot select my own Operative Espion in order to use it

![image](https://user-images.githubusercontent.com/57572496/115111810-70163300-9f82-11eb-867e-0b3ca3208e71.png)

![image](https://user-images.githubusercontent.com/57572496/115111447-b9658300-9f80-11eb-9718-75b1e0520204.png)

**Comment by romanogit** [comment]
What happened with the "Whisper" card ability? I did not see it in the log. weird.

**Comment by Osarek** [comment]
I played whisper juste before raising the tide. 
So it wasn’t ready
