### ISSUE TITLE
Badgemagus

### ISSUE THREAD

**Issue by DarkArtisan** [keyteki/keyteki#2459]
It let only one of his neighbours to ready and fight with it instead of both

**Comment by romanogit** [comment]
need more information, maybe the other neighbor could not fight or no more enemy creatures in play?

**Comment by nixklapps** [comment]
Just had the issue that it doesn't let you ready and fight at all if there's only one neighbour.

**Comment by romanogit** [comment]
Ok, I am able to recreate. It is not readying and fighting. Tricky.

**Comment by romanogit** [comment]
Deployed
