### ISSUE TITLE
God of the Many - do not destroys enemy creatures.

### ISSUE THREAD

**Issue by Szczurolap** [keyteki/keyteki#2462]
God of the Many has not destroyes enemy creatures.

Do there is one of those:
1. The check on traits failed,
2.  or the Dark Tides introduces battlefield split that do not affects enemy side at all.

Dont have the logs or screen unfortunatelly,  Description below:

Issue details:
On enemy side creatures had traits: PLay (Talmage steelheart), nothing (Captain Kresage), Reap (Yeoungest Bear), nothing. 
From this deck - https://decksofkeyforge.com/decks/95b276b7-29ab-4f17-ab45-cb08b2904c5a

On my side: Action (Cornicen Octavia), Action (Cornicen Octavia), nothing (Witch of the Dawn).
From this deck https://decksofkeyforge.com/decks/575db387-7676-4cf7-8df8-60d76de6a011

Only mine card with nothing has been destroyed. No enemies. Manualy moved back the card and tried again with the same effects. Changes the Tide card and tried again - same effect.

The potential reason can be the Witch of the Dawn - it works right now on reap while should on Play.

**Comment by romanogit** [comment]
Are you confusing traits with abilities?

**Comment by Szczurolap** [comment]
Traits messed with abilities.

Can be closed.
