### ISSUE TITLE
Shield-U-Like

### ISSUE THREAD

**Issue by TH3Cap7a1n26** [keyteki/keyteki#2465]
Dont get the option to add as an upgrade.

**Comment by romanogit** [comment]
Need more info on this one (you might mean Shield-U-Later, right)?
The code is correctly implemented.

**Comment by UltraUltraUltra** [comment]
> Dont get the option to add as an upgrade.

Are you playing it by clicking on it or by dragging it on the battleline?  You only get the option to play a creature as an upgrade when you click on it to play it.

**Comment by TH3Cap7a1n26** [comment]
That would be the issue then. I thought that clicking and dragging was playing the card then you chose. I rarely do it.. Thanks. Put it down as player fault! 😂

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by romanogit** [comment]
closing
