### ISSUE TITLE
Incorrect icons in Archon card (deck list)

### ISSUE THREAD

**Issue by Gimu87** [keyteki/keyteki#2466]
The symbols of actions and artifacts are swapped.
eg: COTA 054 - Arise
COTA 075 -  Lash of Broken Dreams
![image](https://user-images.githubusercontent.com/53396189/115115416-a8267180-9f94-11eb-85aa-51dc11af5396.png)

**Comment by romanogit** [comment]
This one is already fixed, waiting for deploy

**Comment by SkyJedi** [comment]
Dupe of #2441
