### ISSUE TITLE
Witch of the dawn

### ISSUE THREAD

**Issue by Ema2210** [keyteki/keyteki#2470]
Doesn't work, doesn't allow to take a creature back

![image](https://user-images.githubusercontent.com/82717409/115117389-37805480-9f96-11eb-9c92-75d09c644762.png)

Ema22 brings Q. J. Che Ostacola l’Austerità della Terra to The Crucible
Pix98 brings Raphael, il Piumato del Santuario Ispirato to The Crucible
Ema22 won the flip and is first player
 Ema22 has connected to the game server
 Pix98 has connected to the game server
Ema22 is shuffling their deck
Ema22 draws 6 card  s to their maximum of 6
Pix98 is shuffling their deck
Pix98 draws 6 card  s to their maximum of 6
Ema22 draws 1 card 
Key phase - Ema22
Ema22 does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Ema22
Ema22 chooses untamed  as their active house this turn
Main phase - Ema22
Ema22 plays Floomf
Ready phase - Ema22
Ema22 readies all of their cards 
Draw phase - Ema22
End of turn 1
Ema22: 0 Æmber  (0 keys) Pix98: 0 Æmber  (0 keys)
TURN 1 - Pix98
Key phase - Pix98
Pix98 does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Pix98
Pix98 chooses staralliance  as their active house this turn
Main phase - Pix98
Pix98 plays Technobabble
Pix98 gains an Æmber  due to Technobabble's bonus icon
Pix98 uses Technobabble to stun Floomf
Pix98 plays Book of leQ
Ready phase - Pix98
Pix98 readies all of their cards 
Draw phase - Pix98
Pix98 draws 3 card  s to their maximum of 6
End of turn 1
Ema22: 0 Æmber  (0 keys) Pix98: 1 Æmber  (0 keys)
TURN 2 - Ema22
Key phase - Ema22
Ema22 does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Ema22
Ema22 chooses untamed  as their active house this turn
Main phase - Ema22
Ema22 changed tide  to High
Ema22 exhausts Floomf to remove its stun
Ema22 plays Deepwater Gruen
Ema22 gains an Æmber  due to Deepwater Gruen's bonus icon
Ema22 gains an Æmber  due to Deepwater Gruen's bonus icon
 Pix98 is attempting to switch manual mode on
 Ema22 is attempting to switch manual mode on
 Pix98 allows enabling manual mode
 Ema22 switches manual mode on
 Ema22 allows enabling manual mode
 Pix98 switches manual mode on
Pix98 changed tide  to High
 Ema22 sets chains to 2 ( -1 )
 Ema22 sets chains to 1 ( -1 )
 Ema22 sets chains to 0 ( -1 )
 Ema22 switches manual mode off
Ema22 plays Persistence Hunting
Ema22 gains an Æmber  due to Persistence Hunting's bonus icon
Ema22 chooses house mars 
Ema22 uses Persistence Hunting
Ready phase - Ema22
Ema22 readies all of their cards 
Draw phase - Ema22
Ema22 draws 2 card  s to their maximum of 6
End of turn 2
Ema22: 3 Æmber  (0 keys) Pix98: 1 Æmber  (0 keys)
TURN 2 - Pix98
Key phase - Pix98
Pix98 does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Pix98
 Pix98 is attempting to switch manual mode on
 Ema22 allows enabling manual mode
 Pix98 switches manual mode on
 Pix98 sets chains to 2 ( -1 )
 Pix98 sets chains to 1 ( -1 )
 Pix98 sets chains to 0 ( -1 )
 Ema22 switches manual mode off
 Ema22 is attempting to switch manual mode on
 Pix98 allows enabling manual mode
 Ema22 switches manual mode on
 Pix98 manually moves Bilgewarden from their hand to their play area
 Pix98 manually moves Bilgewarden from their play area to their hand
Pix98 chooses logos  as their active house this turn
Main phase - Pix98
Pix98 plays Bilgewarden
Pix98 uses Bilgewarden to raise tide  for Ema22
 Pix98 manually moves Bilgewarden from their play area to their hand
 Pix98 switches manual mode off
Pix98 plays Hydrocataloguer
Pix98 gains an Æmber  due to Hydrocataloguer's bonus icon
Pix98 changed tide  to High
Pix98 uses Hydrocataloguer to archive a card 
Pix98 plays Bilgewarden
Pix98 uses Bilgewarden to raise tide  for Ema22
Pix98 uses Hydrocataloguer to archive a card 
Pix98 changed tide  to High
Pix98 uses Hydrocataloguer to archive a card 
Pix98 plays EDAI “Edie” 4x4
Pix98 uses EDAI “Edie” 4x4 to archive a card 
Ready phase - Pix98
Pix98 readies all of their cards 
Draw phase - Pix98
Pix98 draws 3 card  s to their maximum of 6
Pix98's chains are reduced by 1 to 5
End of turn 2
Ema22: 3 Æmber  (0 keys) Pix98: 2 Æmber  (0 keys)
TURN 3 - Ema22
Key phase - Ema22
Ema22 does not forge a key. They have 3 amber. The current cost is 9 Æmber 
House phase - Ema22
Ema22 chooses untamed  as their active house this turn
Ema22 moves all the cards  in their archives to their hand
Main phase - Ema22
Ema22 plays All Tide Up
Ema22 gains an Æmber  due to All Tide Up's bonus icon
Ema22 uses All Tide Up to raise the tide 
Pix98 uses Hydrocataloguer to archive a card 
Ema22 uses Floomf to make Floomf fight EDAI “Edie” 4x4
Ema22 uses Floomf to place 2 +1 power counters on Deepwater Gruen
Ema22 uses Deepwater Gruen to reap with Deepwater Gruen
Ema22 plays Reap or Sow
Ema22 chooses option ' Add power counters '
Ema22 uses Reap or Sow to do several things
Ema22 plays Waste Not
Ema22 gains an Æmber  due to Waste Not's bonus icon
Ema22 uses Waste Not to destroy Deepwater Gruen
Ema22 draws 5 card  s
Ema22 plays Witch of the Dawn
 Pix98 is attempting to switch manual mode on
 Ema22 allows enabling manual mode
 Pix98 switches manual mode on
 Ema22 manually moves Deepwater Gruen from their discard to their hand
 Ema22 switches manual mode off
Ema22 plays Deepwater Gruen
Ema22 gains an Æmber  due to Deepwater Gruen's bonus icon
Ema22 gains an Æmber  due to Deepwater Gruen's bonus icon
Ema22 plays Mollymawk
Ema22 captures an Æmber  on Mollymawk due to Mollymawk's bonus icon
Ema22 uses Mollymawk to destroy Book of leQ
Ema22 plays Growth Surge
Ema22 gains an Æmber  due to Growth Surge's bonus icon
Ema22 uses Growth Surge to add 3 power counters to to Mollymawk, 2 power counters to Deepwater Gruen and 1 power counter to Floomf
Ready phase - Ema22
Ema22 readies all of their cards 
Draw phase - Ema22
 Ema22 declares Check!
End of turn 3
Ema22: 9 Æmber  (0 keys) Pix98: 1 Æmber  (0 keys)
TURN 3 - Pix98
Key phase - Pix98
Pix98 does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Pix98
Pix98 chooses untamed  as their active house this turn
Pix98 moves all the cards  in their archives to their hand
Main phase - Pix98
Pix98 plays Bombyx
Pix98 gains an Æmber  due to Bombyx's bonus icon
Pix98 uses Bombyx
Pix98 plays Fifalde
Pix98 gains an Æmber  due to Fifalde's bonus icon
Pix98 uses Fifalde
Pix98 plays Reap or Sow
Pix98 chooses option ' Ready and reap '
Pix98 uses Reap or Sow to do several things
Pix98 uses Bilgewarden to reap with Bilgewarden
Pix98 uses Bilgewarden to raise tide  for Pix98
Pix98 uses Hydrocataloguer to archive a card 
Pix98 plays Deepwater Gruen
Pix98 gains an Æmber  due to Deepwater Gruen's bonus icon
Pix98 gains an Æmber  due to Deepwater Gruen's bonus icon
Pix98 plays Fertility Chant
Pix98 gains an Æmber  due to Fertility Chant's bonus icon
Pix98 gains an Æmber  due to Fertility Chant's bonus icon
Pix98 gains an Æmber  due to Fertility Chant's bonus icon
Pix98 gains an Æmber  due to Fertility Chant's bonus icon
Pix98 uses Fertility Chant to cause Ema22 to gain 2 Æmber 
Ready phase - Pix98
Pix98 readies all of their cards 
Draw phase - Pix98
Pix98 draws 2 card  s to their maximum of 6
Pix98's chains are reduced by 1 to 4
 Pix98 declares Check!
End of turn 3
Ema22: 11 Æmber  (0 keys) Pix98: 10 Æmber  (0 keys)
TURN 4 - Ema22
Key phase - Ema22
Ema22 forges the red key  , paying 6 Æmber 
House phase - Ema22
Ema22 chooses sanctum  as their active house this turn
Main phase - Ema22
Ema22 plays Mad Prophet Gizelhart
Ema22 plays Bring Low
Ema22 gains an Æmber  due to Bring Low's bonus icon
Ema22 uses Bring Low to have friendly creatures capture 5 Æmber  from Pix98
Ema22 plays General Xalvador
Ready phase - Ema22
Ema22 readies all of their cards 
Draw phase - Ema22
Ema22 draws 3 card  s to their maximum of 6
 Ema22 declares Check!
End of turn 4
Ema22: 6 Æmber  (1 key) Pix98: 5 Æmber  (0 keys)
TURN 4 - Pix98
Key phase - Pix98
Pix98 does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - Pix98
Pix98 chooses staralliance  as their active house this turn
Main phase - Pix98
Pix98 plays CXO Taber
Pix98 plays Sabotage Mission
Pix98 gains an Æmber  due to Sabotage Mission's bonus icon
Pix98 uses Sabotage Mission to increase Ema22's key cost by 1 for each different power value of friendly creatures
Pix98 plays The Ulfberht Device
Pix98 gains an Æmber  due to The Ulfberht Device's bonus icon
Ready phase - Pix98
Pix98 readies all of their cards 
Draw phase - Pix98
Pix98 draws 3 card  s to their maximum of 6
Pix98's chains are reduced by 1 to 3
 Pix98 declares Check!
End of turn 4
Ema22: 6 Æmber  (1 key) Pix98: 7 Æmber  (0 keys)
TURN 5 - Ema22
Key phase - Ema22
Ema22 does not forge a key. They have 6 amber. The current cost is 9 Æmber 
House phase - Ema22
Ema22 chooses sanctum  as their active house this turn
Pix98 uses The Ulfberht Device to block sanctum  as their active house on their next turn
Main phase - Ema22
Ema22 plays Gatekeeper
Ema22 uses Gatekeeper to capture 2 Æmber  from their opponent , placing it on Gatekeeper
Ema22 uses Mad Prophet Gizelhart to make Mad Prophet Gizelhart fight CXO Taber
Ema22 uses General Xalvador to reap with General Xalvador
Ema22 plays Light Everlasting
Ema22 gains an Æmber  due to Light Everlasting's bonus icon
Ema22 plays Light Everlasting
Ema22 gains an Æmber  due to Light Everlasting's bonus icon
Ready phase - Ema22
Ema22 readies all of their cards 
Draw phase - Ema22
Ema22 draws 3 card  s to their maximum of 6
 Ema22 declares Check!
End of turn 5
Ema22: 9 Æmber  (1 key) Pix98: 5 Æmber  (0 keys)
TURN 5 - Pix98
Key phase - Pix98
Pix98 does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - Pix98
Pix98 chooses logos  as their active house this turn
Pix98 uses The Ulfberht Device to block logos  as their active house on their next turn
Pix98 moves all the cards  in their archives to their hand
Main phase - Pix98
Pix98 plays Information Exchange
Pix98 uses Information Exchange to steal 1 Æmber  from Ema22
Pix98 plays Static Charge attaching it to Deepwater Gruen
Pix98 gains an Æmber  due to Static Charge's bonus icon
Pix98 uses Bilgewarden to reap with Bilgewarden
Pix98 uses Bilgewarden to raise tide  for Ema22
Pix98 uses Hydrocataloguer to archive a card 
Pix98 changed tide  to High
Pix98 uses Hydrocataloguer to archive a card 
Pix98 plays Think Twice
Pix98 uses Think Twice to do several things
Pix98 plays Sabotage Mission
Pix98 gains an Æmber  due to Sabotage Mission's bonus icon
Pix98 uses Sabotage Mission to increase Ema22's key cost by 1 for each different power value of friendly creatures
Ready phase - Pix98
Pix98 readies all of their cards 
Draw phase - Pix98
Pix98 draws 2 card  s to their maximum of 6
Pix98's chains are reduced by 1 to 5
 Pix98 declares Check!
End of turn 5
Ema22: 8 Æmber  (1 key) Pix98: 9 Æmber  (0 keys)
TURN 6 - Ema22
Ema22 uses Deepwater Gruen to deal 2 damage to Floomf and Mollymawk
Key phase - Ema22
Ema22 forges the yellow key  , paying 8 Æmber 
House phase - Ema22
Ema22 chooses unfathomable  as their active house this turn
Pix98 uses The Ulfberht Device to block unfathomable  as their active house on their next turn
Ema22 moves all the cards  in their archives to their hand
Main phase - Ema22
Ema22 plays Brain Drain
Ema22 gains an Æmber  due to Brain Drain's bonus icon
Ema22 uses Brain Drain to return Technobabble to the top of their deck
Ema22 plays Brain Drain
Ema22 gains an Æmber  due to Brain Drain's bonus icon
Ema22 uses Brain Drain to return Deepwater Gruen to the top of their deck
Ema22 plays Pour-tal
Ema22 gains an Æmber  due to Pour-tal's bonus icon
Ema22 uses Pour-tal to raise the tide 
Pix98 uses Hydrocataloguer to archive a card 
Ema22 plays Flamegill Enforcer
Ema22 plays The Chosen One
Ema22 plays Frigorific Rod
Ema22 gains an Æmber  due to Frigorific Rod's bonus icon
Ema22 captures an Æmber  on Flamegill Enforcer due to Frigorific Rod's bonus icon
Ema22 plays Rakuzel's Chant
Ema22 gains an Æmber  due to Rakuzel's Chant's bonus icon
Ema22 uses Rakuzel's Chant to exhaust The Chosen One, Flamegill Enforcer, Gatekeeper, General Xalvador, Mad Prophet Gizelhart, Witch of the Dawn, Floomf, Deepwater Gruen, Mollymawk, Bilgewarden, and Deepwater Gruen
Ready phase - Ema22
Ema22 readies all of their cards 
Draw phase - Ema22
Ema22 draws 5 card  s to their maximum of 6
End of turn 6
Ema22: 5 Æmber  (2 keys) Pix98: 8 Æmber  (0 keys)
TURN 6 - Pix98
Key phase - Pix98
Pix98 forges the red key  , paying 6 Æmber 
House phase - Pix98
Pix98 chooses untamed  as their active house this turn
Pix98 uses The Ulfberht Device to block untamed  as their active house on their next turn
Pix98 moves all the cards  in their archives to their hand
Main phase - Pix98
Pix98 plays Blossom Drake
Pix98 plays Chenille
Pix98 plays The Fittest
Pix98 gains an Æmber  due to The Fittest's bonus icon
Pix98 uses The Fittest to place 1 +1 power counter on Bilgewarden, Deepwater Gruen, Blossom Drake, and Chenille
Ready phase - Pix98
Ema22 uses The Chosen One to skip Pix98's ready cards  and deal 4 damage to The Chosen One
Draw phase - Pix98
Pix98 draws 4 card  s to their maximum of 6
Pix98's chains are reduced by 1 to 4
End of turn 6
Ema22: 5 Æmber  (2 keys) Pix98: 3 Æmber  (1 key)
TURN 7 - Ema22
Ema22 uses Deepwater Gruen to deal 2 damage to Floomf and Mollymawk
Key phase - Ema22
Ema22 does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - Ema22
Ema22 chooses sanctum  as their active house this turn
Main phase - Ema22
Ema22 plays Avenging Aura
Ema22 gains an Æmber  due to Avenging Aura's bonus icon
Ema22 uses Avenging Aura to give each friendly creature assault Avenging Aura for the remainder of the turn
Ema22 uses General Xalvador to make General Xalvador fight Chenille
Ema22 uses General Xalvador to deal 1 damage to Chenille
Pix98 uses Chenille to deal 6 damage to General Xalvador
Ema22 uses Mad Prophet Gizelhart to fully heal all non-mutant creatures
Mad Prophet Gizelhart heals The Chosen One, Mollymawk, and Chenille, gaining Ema22 3 Æmber 
Ema22 uses Gatekeeper to reap with Gatekeeper
Ready phase - Ema22
Ema22 readies all of their cards 
Draw phase - Ema22
Ema22 draws 1 card  to their maximum of 6
 Ema22 declares Check!
End of turn 7
Ema22: 10 Æmber  (2 keys) Pix98: 4 Æmber  (1 key)
TURN 7 - Pix98
Key phase - Pix98
Pix98 does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - Pix98
Pix98 chooses staralliance  as their active house this turn
Main phase - Pix98
Pix98 plays Technobabble
Pix98 gains an Æmber  due to Technobabble's bonus icon
Pix98 uses Technobabble to stun Flamegill Enforcer and The Chosen One
Pix98 plays Lieutenant Khrkhar
Pix98 plays Sci. Officer Qincan
Ready phase - Pix98
Ema22 uses The Chosen One to skip Pix98's ready cards  and deal 6 damage to The Chosen One
Draw phase - Pix98
Pix98 draws 3 card  s to their maximum of 6
Pix98's chains are reduced by 1 to 3
End of turn 7
Ema22: 10 Æmber  (2 keys) Pix98: 5 Æmber  (1 key)
TURN 8 - Ema22
Ema22 uses Deepwater Gruen to deal 2 damage to Witch of the Dawn and Mollymawk
Key phase - Ema22
Ema22 forges the blue key  , paying 6 Æmber 
 Ema22 has won the game
Pix98 would like to continue
Ema22 would like to continue
House phase - Ema22
Ema22 chooses unfathomable  as their active house this turn
Main phase - Ema22
Ready phase - Ema22
Ema22 readies all of their cards 
Draw phase - Ema22
End of turn 8
Ema22: 4 Æmber  (3 keys) Pix98: 5 Æmber  (1 key)
TURN 8 - Pix98
Key phase - Pix98
Pix98 does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - Pix98
Pix98 chooses untamed  as their active house this turn
Main phase - Pix98
Pix98 plays Witch of the Dawn

**Comment by gian238** [comment]
I confirm

**Comment by Tutenkharnage** [comment]
Specifically, it is working like a "Reap:" ability rather than a "Play:" ability.

**Comment by SkyJedi** [comment]
Dupe report, patched already, awaiting deploy
