### ISSUE TITLE
Moving a ward leads to "2 wards"

### ISSUE THREAD

**Issue by Kebay** [keyteki/keyteki#2479]
I just used [Hunter or Hunted](https://archonarcana.com/Hunter_or_Hunted) to move a ward from one of my opponent's creatures to another warded opponent creature. The ward token then displayed "2" (similar to how other counters such as damage or power look like).

Later I dealt damage to this "2 ward" creature and all wards got removed, so this seems to be just a minor visual problem, not really a bug.

Sadly I forgot to take a screenshot.

**Comment by romanogit** [comment]
@Kebay , this is the expected behavior. It is a very specific corner case, but IRL, the card would have two tokens. If, for example, another instance of Hunter or Hunted is played, you could move one of those wards to another creatured without unwarding the creature with two tokens.
