### ISSUE TITLE
Pestergrove effect present even if not played

### ISSUE THREAD

**Issue by Avatar-of-Chaos** [keyteki/keyteki#2481]
I have a deck with a copy of Pestergrove. (Untamed artifact, rare, new to Dark Tidings)

Effect:

All creatures enter play enraged.

On my first game with this deck, Pestergrove was the first card I played and nothing strange occurred. All creatures entered play enraged as expected. However, this also happened in the subsequent 3 games, despite the fact that Pestergrove was not in play, or even in my hand. For several turns in a row, _every_ creature, both mine and opponents enter play enraged despite Pestergrove not being in play. It has only happened to this particular deck, so I assume this card is to blame.

**Comment by xehartnort** [comment]
I also own a deck with the same card, and I have experience the same issue until I played with a different deck.

**Comment by SkyJedi** [comment]
dupe of #2418, already patched and awaiting deploy
