### ISSUE TITLE
"Dead man's chest" doesn't work

### ISSUE THREAD

**Issue by gian238** [keyteki/keyteki#2486]
As mentioned in the title, the artifact seems to not be working.
I played "final analysis" destroying 6+ creatures on the board but nothing happened (meanwhile the artifact was ready).

**Gian23 plays Dead Man's Chest**
Gian23 gains an Æmber  due to Dead Man's Chest's bonus icon
Gian23 uses Dead Man's Chest to place 4 Æmber  on Dead Man's Chest
Ready phase - Gian23
Gian23 readies all of their cards 
Draw phase - Gian23
Gian23 draws 1 card  to their maximum of 6
End of turn 1
itbadass: 0 Æmber  (0 keys) Gian23: 1 Æmber  (0 keys)
TURN 1 - itbadass
Key phase - itbadass
itbadass does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - itbadass
itbadass chooses unfathomable  as their active house this turn
Main phase - itbadass
itbadass plays Horrid Synan
itbadass plays Hookmaster
itbadass plays Giltspine Netcaster
Ready phase - itbadass
itbadass readies all of their cards 
Draw phase - itbadass
itbadass draws 3 card  s to their maximum of 6
End of turn 1
itbadass: 0 Æmber  (0 keys) Gian23: 1 Æmber  (0 keys)
TURN 2 - Gian23
Key phase - Gian23
Gian23 does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Gian23
Gian23 chooses logos  as their active house this turn
Main phase - Gian23
Gian23 plays Bilgewarden
Gian23 uses Bilgewarden to raise tide  for Gian23
Gian23 plays EDAI “Edie” 4x4
Gian23 uses EDAI “Edie” 4x4 to archive a card 
Ready phase - Gian23
Gian23 readies all of their cards 
Draw phase - Gian23
Gian23 draws 3 card  s to their maximum of 6
End of turn 2
itbadass: 0 Æmber  (0 keys) Gian23: 1 Æmber  (0 keys)
TURN 2 - itbadass
Key phase - itbadass
itbadass does not forge a key. They have 0 amber. The current cost is 7 Æmber 
House phase - itbadass
itbadass chooses shadows  as their active house this turn
Main phase - itbadass
itbadass plays Shoulder Id
itbadass plays Mastermindy
itbadass plays Gas-Pipes Malone
Ready phase - itbadass
itbadass readies all of their cards 
Draw phase - itbadass
itbadass draws 3 card  s to their maximum of 6
itbadass uses Mastermindy to place 1 scheme on Mastermindy
End of turn 2
itbadass: 0 Æmber  (0 keys) Gian23: 1 Æmber  (0 keys)
TURN 3 - Gian23
Key phase - Gian23
Gian23 does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Gian23
Gian23 chooses logos  as their active house this turn
Main phase - Gian23
Gian23 uses EDAI “Edie” 4x4 to reap with EDAI “Edie” 4x4
Gian23 plays Infomorph
**Gian23 plays Final Analysis
Gian23 uses Final Analysis to destroy Mastermindy, Shoulder Id, Hookmaster, Horrid Synan, Giltspine Netcaster, Gas-Pipes Malone, Infomorph, EDAI “Edie” 4x4, and Bilgewarden**
Gian23 draws 3 card  s
itbadass draws 6 card  s
Gian23 plays Information Exchange
Gian23 draws a card  due to Information Exchange's bonus icon
Gian23 draws a card  due to Information Exchange's bonus icon

**Comment by romanogit** [comment]
Deployed
