### ISSUE TITLE
T3R-35A allowing me to use each creature 

### ISSUE THREAD

**Issue by KarenB4646** [keyteki/keyteki#2488]
When I have T3R-35A it lets me use my entire board without house restrictions. (image attached) It continued to do so throughout that game and in other games.

<img width="1348" alt="Screen Shot 2021-04-18 at 7 11 13 AM" src="https://user-images.githubusercontent.com/67908812/115145379-39dac100-a01f-11eb-8ebb-85ff1abf8b2d.png">

**Comment by RaulKen94** [comment]
Yes mega bug. It is hard to play with T3R3SA in play, not missclicking.

**Comment by romanogit** [comment]
Deployed
