### ISSUE TITLE
Hand Cannon on Gas-Pipes Malone doesn't work properly

### ISSUE THREAD

**Issue by RaulKen94** [keyteki/keyteki#2489]
[Sry no screenshot]
I attacked enemy Mother with my Gas-Pipes Malone upgraded with Hand Cannon.
3 damage set correctly and the capture from his board part were ok, but the **combat** effect of Hand Cannon did not work.

**Comment by ryanch** [comment]
taking a look

**Comment by ryanch** [comment]
looks like hand cannon is not implemented correctly.  Fixing.

**Comment by ryanch** [comment]
Proposed fix here: https://github.com/keyteki/keyteki/pull/2495

**Comment by romanogit** [comment]
Deployed
