### ISSUE TITLE
Evil Twin Kaupe should distribute damage's from its ability.

### ISSUE THREAD

**Issue by jakelea99** [keyteki/keyteki#2491]
![etkaupe](https://user-images.githubusercontent.com/71396125/115153976-87a10900-a0b3-11eb-8d46-b6e4a7b4ab07.PNG)

Kaupe(ET) : You cannot play more than 1 card of each type each turn. Fight/Reap: Discard any number of cards from your hand. For each card discarded this way, deal 2D to an enemy creature.

Like of 'Sack of Coins' or 'Zap', Kaupe's Fight/Reap's effect should be distributed among every enemy creatures. Not one creature. In TCO system, only choose one creature now.

**Comment by romanogit** [comment]
Deployed
