### ISSUE TITLE
The Mysticeti + "Borrow"

### ISSUE THREAD

**Issue by Tutenkharnage** [keyteki/keyteki#2496]
Relayed to me by another player without a Github account: He played "Borrow" to take control of opponent's Mysticeti. When he used it, it didn't work on friendly Untamed creatures; it worked on friendly Shadows creatures instead. Only the artifact's house should change; abilities shouldn't shift to Shadows. Depending on how wide-reaching this effect is, you might have several artifacts that need to be changed (unless everything can be fixed via "Borrow," of course).

**Comment by romanogit** [comment]
Deployed
