### ISSUE TITLE
Diplomat Agung + United Action

### ISSUE THREAD

**Issue by BaronVonFab** [keyteki/keyteki#2500]
Hi

I played United Action with Sanctum and SA cards in play. I then played Diplomat Agung to make a creature Logos as well as star alliance. I believe this should then let me play Logos cards but TCO didn't let me. I imagine it's not an interaction that's come up before but thought I'd let you guys know. 

Thanks for the awesome work! 

David

**Comment by romanogit** [comment]
Deployed
