### ISSUE TITLE
Waste not and Wards

### ISSUE THREAD

**Issue by StVelten** [keyteki/keyteki#2501]
If you use Wast Not (DT 412) on any creature that is warded, the ward gets removed, but you do not draw cards. 

Waste Not reads: Play: Destroy a friendly creature. Draw cards equal to half that creature's power (rounding up). 

There is no "if you do" or any other restriction, so what should happen is: the ward should be removed and then you draw cards.

**Comment by romanogit** [comment]
Deployed
