### ISSUE TITLE
Diplomate Augang + Grand Alliance Council

### ISSUE THREAD

**Issue by robzor** [keyteki/keyteki#2502]
Hi, think this is a bug, but might needs a rule clarification:

Board: 
Diplomat Augang / Untamed Creature

House chosen: Star Alliance.

1. Reap with Diplomat Augang, choose star alliance and the Untamed creature. The Untamed creature is now both SA and Untamed for the remainder of the turn.
2. Play Grand Alliance Council. Choose Augang and Untamed Creature.

Expected behaviour: Both Creatures survive.
Actual TCO behaviour: Untamed Creature dies (Assuming here the logic is that it is an unselected creature of house SA).

Grand Alliance Council wording:
Play: Choose a creature of each house. Destroy each creature not chosen.

Thanks! 

P.S. Thank you for all your work on TCO

**Comment by romanogit** [comment]
Dupe of #2427 
The issue is fixed, pending deploy

**Comment by romanogit** [comment]
I am reopening to continue the discussion, but my fix also include this issue. 
Are you saying that the issue happened again?

**Comment by robzor** [comment]
@romanogit Hi there, sorry! I am not saying the issue happened again I just wanted to clarify the issue I had further as I realised my original report missed the part about manually selecting the creature. I've not had a chance to test your fix but I'm going to assume it's fixed for now! :)

Thank you again for your work
