### ISSUE TITLE
"Skybooster Squadron" is asking for reactions

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#251]
"Skybooster Squadron" is asking for reactions, but the card text says "Reap: Return Skybooster Squadron" to your hand.

If I remove Aember Imp from oppenent's battle line, it does not happen. I think two effects are happening at the same time, but the effect of Aember Imp (stun the creature that reaped) is going to be ignored because "Skybooster" is going to return to my hand.

![image](https://user-images.githubusercontent.com/2104075/62378483-494c6a80-b51b-11e9-8762-4bee96629320.png)

**Comment by romanogit** [comment]
It is not a problem, since the end effect is correct, but it is confusing. So, I would mark this as an enhancement. If card is target to leave the field and the other card effect is to stun it, ignore. I wonder, however, what would be the appropriate behavior if we had a combination of "Skybooster" and a creature that after reap causes damage (do you know any of these?)

**Comment by jeremylarner** [comment]
Any reactions is misleading, but mechanically it’s working correctly. The engine wants to know which ability (stun or return to hand) you want to resolve first. As you say in this case it doesn’t matter, but in other scenarios it would matter

**Comment by romanogit** [comment]
> As you say in this case it doesn’t matter,..

Correct. I understood it. That's why I think it is just an enhancement.

> but in other scenarios it would matter

Yes, and I found one: Bloodshard Imp vs. Skybooster Squadron is a nice combination on the table

**Comment by romanogit** [comment]
Closing this one as the game is working properly.
