### ISSUE TITLE
Dark Tidings Enhancements

### ISSUE THREAD

**Issue by TheRevOnline** [keyteki/keyteki#2513]
Trying to register decks from Dark Tidings and enhancements do not seem to be picking up correctly - deck i am currently registering has four capture available but should have eight across seven creatures (deck is Camilla, Town Courier). This is the second time today i have had this issue for a dark tidings deck.

Both decks seem to have issues with capture pips and both contain Giltspine Netcaster which i suspect may be the culprit here?

**Comment by SteVader** [comment]
Hi Matt, that's super odd. I've just imported that deck using this URL https://www.keyforgegame.com/deck-details/6fa8b53b-5f31-4233-959c-27db078ce3bf and got the following:

![image](https://user-images.githubusercontent.com/2436007/115402278-2e37f780-a1e3-11eb-9ff9-a3748aec6ab5.png)

Which is correct from what you've said, yes?

Are you seeing the seven cards, but only four capture icons - or are you also seeing less cards?

**Comment by SteVader** [comment]
Maybe just an odd throttling issue on the keyforgegame.com API.
