### ISSUE TITLE
Old Egad dont ward board wipes

### ISSUE THREAD

**Issue by Landros83** [keyteki/keyteki#2523]
Old Egad dont ward neighborgs when someone cast a boardwipe. Is this correct or a bug?

**Comment by blinkingline** [comment]
With a board wipe, the creatures are already tagged for destruction when [Old Egad](https://archonarcana.com/Old_Egad)'s **Destroyed:** ability resolves and wards them. Once a creature is already tagged for destruction, it's too late for that creature to be saved by a [ward](https://archonarcana.com/Ward).

**Comment by romanogit** [comment]
Not a bug
