### ISSUE TITLE
5CO77 IS bugged when you use it TCO says that you have to use it once again and it shouldnt be like that

### ISSUE THREAD

**Issue by Imustwin** [keyteki/keyteki#2524]
5CO77 IS bugged when you use it TCO says that you have to use it once again and it shouldnt be like that 
![image](https://user-images.githubusercontent.com/82998315/115667757-7ae81380-a346-11eb-83c4-cce22ae8b189.png)

**Comment by romanogit** [comment]
I see other issues related to 5C077, but not being able to use itself.

**Comment by Osarek** [comment]
Issue is still present.
Issue is when you select itself from reap effect

![image](https://user-images.githubusercontent.com/57572496/116663395-553aba00-a997-11eb-9254-0818b856d0f0.png)

**Comment by romanogit** [comment]
Does the Add / Remove Power Counter prompt appear only at the end?

**Comment by romanogit** [comment]
Can you tell me your deck name, maybe some other card is causing issue

**Comment by Osarek** [comment]
for it was a fresh game, with manual on to explicitly get 5C077 on board ready.
its doing king of a recusirve call, on "Ready and use", the stop cause is the rule of 6, and then continue the end of the card "give +1 or -1 power)
a the end it have +6 on it.
and the deck is this one
https://decksofkeyforge.com/decks/1c0d21cd-98fc-47d0-965b-810a3b8a638f

![image](https://user-images.githubusercontent.com/57572496/116712174-e0d23c00-a9d3-11eb-8cc5-3473afc9b87e.png)

**Comment by romanogit** [comment]
I cannot reproduce with test cases

**Comment by Osarek** [comment]
can you when inside a game?

**Comment by romanogit** [comment]
No, I cannot

![image](https://user-images.githubusercontent.com/2104075/116716690-6cd16d00-a9ae-11eb-97ec-b556a85dd245.png)

**Comment by Osarek** [comment]
this seem to be a realy strange bug..
i even tried in on firefox and chrome, same issue

![tco1](https://user-images.githubusercontent.com/57572496/116719076-f303a880-a9da-11eb-8c97-038578074205.gif)

**Comment by romanogit** [comment]
I wonder if it is related to https://github.com/keyteki/keyteki/issues/2556 (which has the opposite effect)

**Comment by romanogit** [comment]
are you using the live server or a local development environment?

**Comment by Osarek** [comment]
I’m using the live server

**Comment by ju4np4** [comment]
I have the same issue. 

This is the deck
[https://decksofkeyforge.com/decks/918d7413-5be9-466e-ae9f-e4daca182e6c](url)

**Comment by romanogit** [comment]
It would be nice to paste the game log

Em sáb, 15 de mai de 2021 8:16 AM, ju4np4 ***@***.***>
escreveu:

**Comment by Osarek** [comment]
here is the game log
```
Osarek brings Gaia “Clavos”, la Dramática to The Crucible
Osarek won the flip and is first player
 Osarek has connected to the game server
Osarek is shuffling their deck
Osarek draws 6 card  s to their maximum of 6
Osarek draws 1 card 
Key phase - Osarek
Osarek does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Osarek
Osarek chooses staralliance  as their active house this turn
Main phase - Osarek
Osarek plays 5C077
Ready phase - Osarek
Osarek readies their cards 
Draw phase - Osarek
Osarek draws 1 card  to their maximum of 6
End of turn 1
Osarek: 0 Æmber  (0 keys)
TURN 2 - Osarek
Key phase - Osarek
Osarek does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Osarek
Osarek chooses staralliance  as their active house this turn
Main phase - Osarek
Osarek uses 5C077 to reap with 5C077
Osarek uses 5C077 to do several things
Osarek uses 5C077 to reap with 5C077
Osarek uses 5C077 to do several things
Osarek uses 5C077 to reap with 5C077
Osarek uses 5C077 to do several things
Osarek uses 5C077 to reap with 5C077
Osarek uses 5C077 to do several things
Osarek uses 5C077 to reap with 5C077
Osarek uses 5C077 to do several things
Osarek uses 5C077 to reap with 5C077
Osarek uses 5C077 to do several things
Osarek chooses option ' Add a power counter '
Osarek chooses option ' Add a power counter '
Osarek chooses option ' Add a power counter '
Osarek chooses option ' Add a power counter '
Osarek chooses option ' Add a power counter '
Osarek chooses option ' Add a power counter '
```

**Comment by romanogit** [comment]
How do you play alone on live server?

**Comment by Osarek** [comment]
> How do you play alone on live server?

Create a game with password, select deck and start game (button is enabled)

**Comment by romanogit** [comment]
Fixed server side bug where two files were implementing the same card.

**Comment by Osarek** [comment]
i confirme, issues is resolved 🎆🎇✨🎉🎊
