### ISSUE TITLE
problem with orb of wonder

### ISSUE THREAD

**Issue by smax82x** [keyteki/keyteki#2530]
in the deck named "ares julius protettore di pinzaveniale" the card orb of wonder is considered like a brobnar card instead that a sanctum card

**Comment by cryogen** [comment]
Thanks for the report. When was the deck imported? If it was not within the last couple of days you'll need to remove and reimport the deck. A bug was fixed but required the deck to be reimported

**Comment by romanogit** [comment]
Deck is https://www.keyforgegame.com/deck-details/acc2012b-8bd0-49a7-91f3-98e74eaedf69
I was able to see OfW as Sanctum:

![image](https://user-images.githubusercontent.com/2104075/115894631-dd690e80-a42f-11eb-8b82-1934067eea49.png)

As cryogen said, make sure you delete and import the deck again.
