### ISSUE TITLE
Stir up trouble

### ISSUE THREAD

**Issue by KarenB4646** [keyteki/keyteki#2531]
Stir up trouble makes the creatures fight instead of dealing damage. Here is an example where my opponent used it on my shadowself and I ended up stealing from them haha. As much as I'd love that to be correct I know it isn't!

<img width="211" alt="Screen Shot 2021-04-23 at 8 38 41 AM" src="https://user-images.githubusercontent.com/67908812/115873500-01692780-a411-11eb-904d-0c0c5c9b4414.png">

**Comment by romanogit** [comment]
Not a bug

**Comment by SkyJedi** [comment]
thats Shadow Id, and instead of dealing damage it steals.
