### ISSUE TITLE
Bug when add a MM deck with duplicated cards

### ISSUE THREAD

**Issue by Rikuns** [keyteki/keyteki#2538]
I tried to add this deck and somehow ended up with a 42 cards deck: https://decksofkeyforge.com/decks/1231bd6d-2bdd-4bd8-9d84-a1f57b6e4f34
![image](https://user-images.githubusercontent.com/83189520/116011888-7b87ef00-a651-11eb-8aed-ddea2d7792a3.png)

**Comment by SkyJedi** [comment]
Fix in #2537

**Comment by romanogit** [comment]
Can you try importing the deck again?

(Nice deck, by the way...)
