### ISSUE TITLE
Too much samecards (MM) 

### ISSUE THREAD

**Issue by purpletaste** [keyteki/keyteki#2539]
![1619393181928](https://user-images.githubusercontent.com/83191158/116013682-6cfb0100-a66c-11eb-9e72-60e4d3c26f52.png)
Deck : https://www.keyforgegame.com/deck-details/e1041053-cdeb-4d5d-8ce5-25110ba29f28
There are more cards than 36 cards. (Some cards are duplicated)

**Comment by blinkingline** [comment]
Duplicates #2538
