### ISSUE TITLE
More cards in deck than needed

### ISSUE THREAD

**Issue by AleksandrShepelev** [keyteki/keyteki#2541]
![image](https://user-images.githubusercontent.com/14818993/116042276-a725cc00-a687-11eb-9ccd-3d6768144e99.png)

my decklist in TCO have 4 subdue and 4 frontiers. should have only 2. all cards were in game too, not only decklist problem

**Comment by AleksandrShepelev** [comment]
https://decksofkeyforge.com/decks/64b3d7e6-b2d2-41d9-81f6-118a3cd50ff8?powered_by=archonMatrixTelegram

**Comment by romanogit** [comment]
Can you delete and import again? Thank you.
