### ISSUE TITLE
Ankylo Formation

### ISSUE THREAD

**Issue by nixklapps** [keyteki/keyteki#2543]
Ankylo Formation let's you exalt an enemy creature for its second option.

**Comment by Osarek** [comment]
adding information:

while no friendly creature, enemy creature can be exalted
before selection creature
![image](https://user-images.githubusercontent.com/57572496/116776547-39074d80-aa69-11eb-8534-0b9361e94445.png)

after selecting creature and selection option 2
![image](https://user-images.githubusercontent.com/57572496/116776551-3b69a780-aa69-11eb-8c4b-fbc7b1a9aac2.png)

**Comment by romanogit** [comment]
I think the way the card is implemented is confusing... It is in my backlog to rework it
