### ISSUE TITLE
Auto-enhanced Decks - Can the Enhancements show as Verified please?

### ISSUE THREAD

**Issue by UltraUltraUltra** [keyteki/keyteki#2547]
Thank you for implementing the auto-enhancement of decks where the enhancements can only be placed one way (i.e. when there is only one type of enhancement and the number of enhancements matches the number of enhanced cards exactly).

Is it possible for these decks to also automatically show as Valid with Enhancements Verified?  Thank you.

**Comment by SkyJedi** [comment]
Probably, I'll look into it today.  Prepare for busting!
