### ISSUE TITLE
Diplomat Agung log message doesn't say which creature has been selected

### ISSUE THREAD

**Issue by UltraUltraUltra** [keyteki/keyteki#2554]
Could the log entry for Diplomat Agung's ability say which creature has been selected?  Thank you.

![image](https://user-images.githubusercontent.com/55008319/116321178-7d68c400-a7b1-11eb-863b-414ca0191b3b.png)

**Comment by romanogit** [comment]
This is fixed, possibly pending deploy

**Comment by romanogit** [comment]
Message will look like:
`make {card} belong to house {hous} in addition to its other houses`

**Comment by romanogit** [comment]
Deployed, please, let us know if you still see the old message
