### ISSUE TITLE
The Chosen One failing to work

### ISSUE THREAD

**Issue by UltimoFox** [keyteki/keyteki#2555]
I don't know why, but in a game just a minute ago The Chosen One was destroyed by my creatures remaining exhausted. But then after it died, they all immediately readied again, and that's not how it's supposed to work. They should all remain exhausted, dealing excess damage to The Chosen One. The player I was against said it worked fine for them before, so I'm not sure what caused it to go wrong this time? Here's a screenshot I took after the game, anyway.
![TCO SS 1](https://user-images.githubusercontent.com/47079472/116334658-7f408080-a7cd-11eb-966c-440cf1fd1426.png)

**Comment by UltimoFox** [comment]
I realise the screenshot isn't that helpful, as The Chosen One worked fine in an earlier turn when it didn't die, and the text was no different. So the only difference is that The Chosen One died, and the creatures on my battleline readied (when they shouldn't have).

**Comment by romanogit** [comment]
This is fixed, pending deploy

**Comment by romanogit** [comment]
Deploy, let us know if you still see the problem and we will reopen.
