### ISSUE TITLE
Reap or Sow: Couldn't select some creatures for ready/reap

### ISSUE THREAD

**Issue by ghoxie** [keyteki/keyteki#2556]
Turn 9 of this match https://www.thecrucibletracker.com/games/5ff03a30-a70b-11eb-93ce-95960407c81a

Armadrone and Sporegorger were exhausted at the beginning of the turn. Old Bruno is ready.

Choose Untamed
Play Reap or Sow
Choose to add power counters
Add 3 power counters to Sporegorger
Play Reap or Sow (second copy)
Choose ready and reap

Actual: Only Old Bruno is selectable
Expected: Armadrone, Old Bruno, and Sporegorger are all selectable to ready and reap

**Comment by Hypyer946** [comment]
I believe this is related to a Storm Surge bug. I mentioned the same thing in #2561

**Comment by romanogit** [comment]
Totally makes sense. working on it and on #2561
