### ISSUE TITLE
Creature targeting blocked by upgrades

### ISSUE THREAD

**Issue by OsramTaleka** [keyteki/keyteki#2557]
I had a sci. Officer qincan with 4 or 5 upgrades in the middle of my battleline. When I tried to use it to attack, I couldn't click the creature directly in front of it on my opponent's battleline. A little bit of the creature I was trying to target was showing, but none of my clicks would register.

**Comment by Osarek** [comment]
duplicated of #766

**Comment by romanogit** [comment]
Closing as there is a dupe
