### ISSUE TITLE
Ganger Chieftan and Storm Surge interaction?

### ISSUE THREAD

**Issue by Hypyer946** [keyteki/keyteki#2561]
Had a case where Ganger Chieftan would not ready a Drummernaut that was in play. It worked other times in the same game. The opponent had played a Storm Surge the turn before, I don't think there was anything else that prevented readying of cards that were in play.
![Ganger Chieftain not readying](https://user-images.githubusercontent.com/57648480/116645911-d157e200-a944-11eb-8392-1b1aa955b5b4.PNG)

**Comment by SkyJedi** [comment]
Cannot > may. Ganger cannot ready creatures while storm surge is out

![366_007](https://user-images.githubusercontent.com/2967416/116692720-6cbb7800-a982-11eb-9550-096744908770.jpg)

**Comment by Hypyer946** [comment]
Storm surge specifies **during the "ready cards" step** which does not block Ganger Chieftain's Play ability during Step 3.

**Comment by romanogit** [comment]
Fixed, sent the PR
