### ISSUE TITLE
Took control of a Mimic Gel that cloned a Mars creature. House selection does not show Logos

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#2566]
I took control of Mimic Gel and when it was my turn, I could not select Logos as house:

![image](https://user-images.githubusercontent.com/2104075/116739780-7cf74580-a9ca-11eb-9728-eaff3bebe765.png)

I take control of a Star Alliance and another Logos creature. I can see SA and Logos house:

![image](https://user-images.githubusercontent.com/2104075/116739954-b3cd5b80-a9ca-11eb-9c80-753ac929f82c.png)

**Comment by Osarek** [comment]
maybe mimic gel was a copy of a non Logos creature?

**Comment by romanogit** [comment]
I actually copied a Mars creature. That's why I think there is a bug, because Mimic Gel continues to be Logos.
