### ISSUE TITLE
Ulfberht Device doesn't trigger on opponent's first turn after being played.

### ISSUE THREAD

**Issue by jghomel** [keyteki/keyteki#2567]
Card reads:

_Each player cannot choose the same active house they chose on their previous turn._ 

However, the turn after it is played, your opponent can, on their first turn after you've played it, select the same house they did on their previous turn. 

This occurrence only happens on the opponent's very first turn after Ulfberht Device is played.

Because of the way the card is implemented (its effect is only registered once it is in play), it allows this to occur.

**Comment by romanogit** [comment]
I think this is fixed, maybe not yet pushed to the site

**Comment by romanogit** [comment]
Deploy, let us know if you still see the problem and we will reopen.
