### ISSUE TITLE
Æmber-vac on enemy creatures

### ISSUE THREAD

**Issue by Jusavo** [keyteki/keyteki#2569]
If you play Æmber-vac on enemy creatures, it will capture 2AE from your opponents side each turn.

**Comment by romanogit** [comment]
There are five upgrades that uses "at the... " that needs to be reviewed:

![image](https://user-images.githubusercontent.com/2104075/116881114-405d6100-abf9-11eb-96a1-7e30a60cd703.png)

- [ ] Cybergiant rig
- [ ] Static Charge
- [ ] Ransom
- [ ] Amber-vac
- [ ] Z-wave emitter
