### ISSUE TITLE
Bot Bookton doesn't work

### ISSUE THREAD

**Issue by Rikuns** [keyteki/keyteki#2575]
It happened twice today for me. 
The first time, Bot Bookton reaped and revealed top deck which is song of the wild, but nothing happen and then Song of the Wild came back to the top deck. I didn't take that screenshot. 
And then later, in another match, Bot Bookton reaped again and revealed Dance of Doom, nothing happened again and the card returned to the deck. There was nothing stop me from playing action card. 
![image](https://user-images.githubusercontent.com/83189520/116967612-ea61e980-acdc-11eb-81b4-49c7e07f3f86.png)
Here is the screenshot.

**Comment by romanogit** [comment]
The only thing I see i common is that both the cards were non-Logos. I will investigate.

**Comment by Rikuns** [comment]
> The only thing I see i common is that both the cards were non-Logos. I will investigate.

There was another thing in common as I can remember, both cases there was Quixxle Stone in play.

**Comment by romanogit** [comment]
I am unable to reproduce. I simplified the PlayCardAction, but I do not think it would affect. I reduced a child event that could be blocking a helper message. Let's see.
