### ISSUE TITLE
Chelonia – Evil Twin     +Sea Urchin – Evil Twin = BUG

### ISSUE THREAD

**Issue by Mori4441** [keyteki/keyteki#2593]
If Chelonia – Evil Twin is on the field, then i play Sea Urchin – Evil Twin, the system will give priority to Chelonia – Evil Twin’s LOST1 AMBER

**Comment by Osarek** [comment]
did you correctly change the settings to choose the order?
![image](https://user-images.githubusercontent.com/57572496/117682293-30beb900-b1b3-11eb-9cf2-fb5b06ae907f.png)

**Comment by Mori4441** [comment]
thanks you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月10日(星期一) 晚上11:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [keyteki/keyteki] Chelonia – Evil Twin     +Sea Urchin – Evil Twin = BUG (#2593)





 
did you correctly change the settings to choose the order?

**Comment by romanogit** [comment]
not a bug
