### ISSUE TITLE
Long card name are going off the card

### ISSUE THREAD

**Issue by Osarek** [keyteki/keyteki#2598]
![0E678EBF-1E8F-4475-9872-67805A4A5D8E](https://user-images.githubusercontent.com/57572496/118041115-b341a700-b372-11eb-8fc2-5b3c41c9eb71.jpeg)

**Comment by SkyJedi** [comment]
Not much we can do about it unfortunately

**Comment by Osarek** [comment]
> Not much we can do about it unfortunately

Ok, no problem, so I close it
