### ISSUE TITLE
Maverick: Shadows Valoocanth Card image is missing 

### ISSUE THREAD

**Issue by robzor** [keyteki/keyteki#2599]
I have a deck with a maverick shadows Valoocanth but the asset is missing in TCO, meaning I cannot see the card or any damage/status tokens on it when it is in play

Deck: https://decksofkeyforge.com/decks/f33bd802-b3fa-412a-b607-0a4aa65df858

404 Error in Console: https://thecrucible.online/img/cards//valoocanth-shadows.png

**Comment by romanogit** [comment]
Same problem happens with Orb Of Wonder in this deck
https://decksofkeyforge.com/decks/e7c859c1-3804-4ad3-9f13-ba68b9c75b8d
