### ISSUE TITLE
FFG appear to have updated the rules on the Tide and it should now always be available for all matches

### ISSUE THREAD

**Issue by UltraUltraUltra** [keyteki/keyteki#2605]
The ability to raise the Tide should be available in every match regardless of the decks used.

While it's unlikely a player will want to change the Tide if neither player is playing a Dark Tidings deck, it is possible there that there will be times when a player might want to change the Tide (e.g. because their opponent has an anomaly version of "Valoocanth" in their Worlds Collide deck or the active player wants to gain chains to prevent them drawing a card because there is a "Gambling Den" in play).

I originally raised this when I saw this ruling from the French rules: 

![115138023-83c4a680-a021-11eb-84ae-4a6a329bd696](https://user-images.githubusercontent.com/55008319/118346756-85589000-b535-11eb-8d33-acbb471e985e.jpg)

which then appeared to be contradicted by the English quick start rules:

![115110930-a600ea80-9f75-11eb-86af-38dcdda9db8b](https://user-images.githubusercontent.com/55008319/118346788-c5b80e00-b535-11eb-8491-0a168217aaa3.jpeg)

which have now been contradicted by this latest ruling from FFG:

![183553517_10161587173617837_6749685354584714762_n](https://user-images.githubusercontent.com/55008319/118346708-4296b800-b535-11eb-8a62-9b629bb5a50d.jpg)

**Comment by dgbrokaw** [comment]
PR: https://github.com/keyteki/keyteki/pull/2813.

Makes the tide work as described in this rulebook: https://images-cdn.fantasyflightgames.com/filer_public/bb/3d/bb3d8067-b028-43c4-97c8-f76ff55232ba/keyforge_rulebook_v151.pdf
