### ISSUE TITLE
Incorrect House choices & Valoocanth unplayable

### ISSUE THREAD

**Issue by jaimefps** [keyteki/keyteki#2609]
I was playing a game right now and had two strange issues:

1- When picking houses at the beginning of my turn, I would be offered Brobnar as a 4th option, even though my deck doesn't include any Brobnar cards.

2- Even when the Tide was high, I wasn't able to play or use any of my Valoocanth cards.

This is my deck: https://www.keyforgegame.com/deck-details/5c992b91-7692-42f6-8ec8-5aca8a672833

**Comment by SkyJedi** [comment]
This was an import issue that has been fix.  Delete the deck and reimport and report back please 😊

**Comment by jaimefps** [comment]
Awesome, thanks; will try now

**Comment by jaimefps** [comment]
I just deleted the deck and re-improted, and still have both bugs.

**Comment by jaimefps** [comment]
Ohh, if the issue was on the Client build code, them I might've needed to do a hard refresh as well. 
I'm trying again.

**Comment by jaimefps** [comment]
Seems the bug has to do with having Valoocanth in my hand. While I don't have the card in my hand, then the Brobnar option doesn't show up. Once I draw the card, the Brobnar options is available and I can't play the Valoocanth card during my Unfa turns.

**Comment by romanogit** [comment]
I will take a look. Difficult to handle anomaly WC , normal house versus
maverick in a consistent way.

Em sáb, 15 de mai de 2021 4:30 PM, Jaime Pericas ***@***.***>
escreveu:

**Comment by romanogit** [comment]
There was indeed a newly introduced bug. Thanks for taking the time to troubleshoot. I pushed a PR to fix it. Needs to be reviewed and deployed.

**Comment by cryogen** [comment]
This is now deployed, you will have to reimport your deck though. Apologies for the inconvenience

**Comment by jaimefps** [comment]
Thanks for getting on this so quickly! 
Does the team take donations? I can't seem to fine anything under the ABOUT section on the Crucible site.
