### ISSUE TITLE
Valoocanth cannot use by Unfathom

### ISSUE THREAD

**Issue by idq129** [keyteki/keyteki#2611]
![BUG](https://user-images.githubusercontent.com/84272319/118395739-8e08ad80-b67e-11eb-8b84-5ef47907651d.jpg)

Valoocanth cannot use by Unfathom when played. 
And have Brobnar when choosing a house.

**Comment by cryogen** [comment]
Hi,

Thanks for your report.

this issue was fixed this morning with a recent update. However your deck will need to be reimported
