### ISSUE TITLE
colosseum didnt forge the key

### ISSUE THREAD

**Issue by aussiebrucio** [keyteki/keyteki#2631]
i had 6 glory counter on the colosseum and 6 amber and the cost was 6 and didnt forge the key

**Comment by romanogit** [comment]
We need a game log

**Comment by aussiebrucio** [comment]
Ok too late now I guess
If it happens again I ll try and save the game log

Sent from my iPhone

On 25 May 2021, at 2:48 pm, Romano Silva ***@***.***> wrote:

﻿

We need a game log

**Comment by romanogit** [comment]
Closing lack of information
