### ISSUE TITLE
Bestiarii Urso cannot unstun itself when played by Imperial Road

### ISSUE THREAD

**Issue by strib** [keyteki/keyteki#2636]
TCO stuns Urso after resolving its play effect, but "enters play stunned" should happen before.

![image](https://user-images.githubusercontent.com/8516691/119921967-c2ecee00-bf23-11eb-914a-265c308bec3b.png)

**Comment by romanogit** [comment]
A scenario where "stunning" versus "enter plays stunned" makes a difference :)
