### ISSUE TITLE
Might Makes Right not Counting Power Modifiers

### ISSUE THREAD

**Issue by OsramTaleka** [keyteki/keyteki#264]
I had panpaca anga to the left and 4 creatures totalling 22 power to the right. Might Makes Right ignored the power added by Anga when I sacrificed them.
![MMR TCO](https://user-images.githubusercontent.com/53394971/62409949-b4d21e80-b593-11e9-9089-63882ceaff8e.jpg)

**Comment by Achocholacek** [comment]
Thanks for the report. This is definitely bugged and will need to be resolved.
@jeremylarner - Based on how MMR is written right now - it's not verifying the power for the forge until after the sacrifice, when board effects are no longer in play. Is there a way to have it look at what effects were in play prior to sacrifice? I thought .getPower() would do it, but no joy.

**Comment by twilliamson15** [comment]
Same just happened to me with Lion Bautram in play, Lion's +2 to neighbor bonus was not counted in MMR
