### ISSUE TITLE
¡Bear Flaute me deja agarrar todas las cartas de mi mazo!

### ISSUE THREAD

**Issue by ChopeArgentina** [keyteki/keyteki#2641]
Cuando se utiliza la acción de ese artefacto, y el oso no esta en juego, TCo te permite elegir las cartas que normalmente estan inhabilitadas para seleccionar. Y asi traer todo el mazo a tu mano.

**Comment by romanogit** [comment]
Bear Flute allows returning all cards from deck when bear is not in play.

**Comment by ChopeArgentina** [comment]
El Bug sigue vigente!

**Comment by romanogit** [comment]
Needs a deploy. Should be done soon.

Em seg, 31 de mai de 2021 6:18 PM, ChopeArgentina ***@***.***>
escreveu:
