### ISSUE TITLE
Orb of Wonder -- Brobnar

### ISSUE THREAD

**Issue by moorebj2** [keyteki/keyteki#2644]
So i just played a sealed game and this deck thought Orb of Wonder was a Brobnar card.

"Flyby" Indigo Gregson

https://decksofkeyforge.com/decks/abcebd45-d3ac-4bb0-a42a-0e71098bfc73

Also not sure about this but we had an instance where I attacked with Hard Simpson and he died but still stole one.

Now he was a 6 power at time and the other guy had two Isentropic Coves and I was attacking a four power creature so questions is does each Hazardous trigger seperately if so I should steal twice??  Or does all damage happen at once??  Or is Hazardous seperate from main fight damage.

**Comment by cryogen** [comment]
Thanks for your report.

Please delete your deck and reimport it. This was due to an issue that we fixed a while ago
