### ISSUE TITLE
Sci. Officer Morpheus doesn't re-trigger Sea Urchin Play effect

### ISSUE THREAD

**Issue by Schyse** [keyteki/keyteki#2650]
I got a Dark Tidings deck with legacy Sci. Officer Morpheus. When I play Sea Urchin while Morpheus is already in play:
-The log first said: "Sci. Officer Morpheus to trigger the play effect of Sea Urchin an additional time"
-However next, there is only one (instead of 2) log on Sea Urchin capturing/stealing 1 aember.
-I checked with other cards like Old Bruno and Mollymawk and it worked just fine.
![Sci  Officer Morpheus doesn't re-trigger Sea Urchin play effect](https://user-images.githubusercontent.com/85406662/120898276-60e36580-c654-11eb-918f-2146bb47ac55.PNG)

**Comment by romanogit** [comment]
i believe the reason is that your opponent had no more amber.

**Comment by Schyse** [comment]
If you take a look at the log: "End of Turn 3 Rviere (the opponent): 6 Aembers". Then the 2 Sea Urchins were played before Old Bruno, yet there are 4 Aembers captured on Old Bruno.

**Comment by romanogit** [comment]
Sci. Officer Morpheus might be confused with a few situations:
- Optional abilities
- Conditional abilities
- Multiple play abilities

Urchin was implemented as a multiple play conditional ability, but I believe it can be modified to be a conditional action. Thanks for the report. It is a bug, indeed.
