### ISSUE TITLE
Changing the tide to neutral in manual mode

### ISSUE THREAD

**Issue by StVelten** [keyteki/keyteki#2654]
Currently it is not possible to change the tide back to neutral state in the manual mode. In chase anyone made a mistake or or miss click. This is a problem as you can't recreate the correct board state. Admittedly this won't matter often, but if it does the game is and stays broken.

**Comment by romanogit** [comment]
I am almost certain I added this feature. Did you try /tide neutral ?

Em dom, 6 de jun de 2021 5:10 PM, StVelten ***@***.***>
escreveu:

**Comment by StVelten** [comment]
Ah well sorry for the fuss. Yes it is in and it works. I just didn't mid to check help.
