### ISSUE TITLE
Urchin Steals on Reap

### ISSUE THREAD

**Issue by Jselmer466** [keyteki/keyteki#266]
EDIT: I missed the duskrunner, my bad.

_Urchin stole 1 whenever it reaped in the game I just played. Haven't had a chance to test it in a private game, but it happened more than once in this instance.

Here's a chat log for reference https://pastebin.com/V93PQbui_

**Comment by Achocholacek** [comment]
the urchin had dusk runner attached, which adds "Reap: Steal 1A" - so this would be 3xpected behaviour? or am I missing something?

**Comment by Jselmer466** [comment]
You're right, I'm not sure how I missed that. My bad lol
