### ISSUE TITLE
TCO allows playing Alpha after raising the tide

### ISSUE THREAD

**Issue by poeticmatter** [keyteki/keyteki#2660]

**Comment by romanogit** [comment]
Do you have a rules reference?

!r alpha: When a card has the Alpha keyword, it can only be played if you haven’t played, used, or discarded any other cards during the current step of your turn. 

!r tide: During the active player’s turn, they may use the ability “Omni: Raise the tide. Gain 3 chains.” **Using this ability does not require the use of a card**, and so therefore can be done at any point during the active player's turn. The tide may be raised (even from a neutral state) regardless of whether or not there are cards in play that refer to the state of the tide.

**Comment by poeticmatter** [comment]
You are correct. Disregard.
