### ISSUE TITLE
Gabos Longarms interacting with Bul-wark, Archimedes.

### ISSUE THREAD

**Issue by Rikuns** [keyteki/keyteki#2661]
I'm not sure if it's supposed to happen. But I used Gabos to attack Archimedes and chose to deal the before fight damage to Dysania. Assault 2 fro Bul-wark killed Archimedes but Dysania received no damage. 
![image](https://user-images.githubusercontent.com/83189520/121217496-19571680-c8ac-11eb-8786-03528fd9958b.png)

**Comment by romanogit** [comment]
The thing here is that, at the end, the fight did not happen, so, there is no damage to be redirected.

**Comment by blinkingline** [comment]
In this case [Gabos Longarms](https://archonarcana.com/Gabos_Longarms) has two abilities that have to resolve before the fight, the printed **Before Fight:** ability and the [Assault](https://archonarcana.com/Assault) keyword granted by [Bull-wark](https://archonarcana.com/Bull-wark). 

In this case, the player chose to resolve the **Before Fight:** ability first, choosing [Dysania](https://archonarcana.com/Dysania) to receive the fight damage that normally would be set for [Archimedes](https://archonarcana.com/Archimedes). Then the Assault keyword resolves and does two damage to Archimedes. Archimedes is tagged for destruction and leaves play. The rules for [Fight](https://archonarcana.com/Fight) say:

> If either creature in a fight is destroyed while resolving Assault, Hazardous, or "Before Fight:" abilities, then the fight 
> (dealing damage based on power) is skipped. 

Therefore no damage would be dealt in the fight, meaning Dysania receives no damage. 

It looks like TCO has this implemented correctly.

**Comment by romanogit** [comment]
Thanks for the reply, closing.
