### ISSUE TITLE
Unable to resolve the order reap effects resolve in.

### ISSUE THREAD

**Issue by charzendat** [keyteki/keyteki#2664]
If I player Dr. Verokter and give it the upgrade Reckless Experiment, it now has two reap effects.
**Reap**: Put an upgrade or action card from your discard pile on top of your deck. (Dr. Verokter)
**Reap**: Play the top card of your deck (Reckless Experimentation).

I should be allowed to choose the order these resolve in, however, it always resolves Dr. Verokter's ability first.

Additionally, in a recent game my opponent had Kangaphant out, so my Dr had 3 reap effects:
Reap: Destroy this creature. (Kangaphnat).

I should be allowed to resolve the reap effect from Kangaphant last, but the game chose to resolve it second.

**Comment by romanogit** [comment]
You need to enable in your profile. Have you done that?

**Comment by charzendat** [comment]
Sorry, I did not know that was a thing. I have done that now.
