### ISSUE TITLE
"Only new games" filter not working?

### ISSUE THREAD

**Issue by jaimefps** [keyteki/keyteki#2667]
<img width="749" alt="Screen Shot 2021-06-15 at 1 12 10 PM" src="https://user-images.githubusercontent.com/19941627/122117531-d4ffd500-cddb-11eb-8454-432f74318af4.png">

**Comment by romanogit** [comment]
I think the filter is working, but it takes until the players start the game to disappear from the lobby. Usually it is very fast.

**Comment by romanogit** [comment]
Confirmed it only leaves list when game starts. I believe this is working as intended
