### ISSUE TITLE
Sensor Chief Garcia not increasing the cost of both player's keys during opponent's turn

### ISSUE THREAD

**Issue by UltraUltraUltra** [keyteki/keyteki#2672]
I played a "Sensor Chief Garcia" and on my opponent's turn their key cost increased +2, but mine did not.  Mine was 7 (+1 from their "Grabber Jammer") and theirs were 8 (+2 from "Sensor Chief Garcia") but mine (during their turn) should have also been +2 from "Sensor Chief Garcia".

![image](https://user-images.githubusercontent.com/55008319/122481916-82830c00-cfc7-11eb-82f9-a052b02e4e8f.png)

**Comment by romanogit** [comment]
it is fixed in this PR https://github.com/keyteki/keyteki/pull/2628

But I believe it is better to take it of there and create a simpler PR, for sure.

Thanks for the report.
