### ISSUE TITLE
Containment field on Pit demon

### ISSUE THREAD

**Issue by stebsteb** [keyteki/keyteki#268]
I had a containment field attached to a pit demon. When I used it there were two different buttons to use an action (i.e. options were Action, Fight, Reap, Action). I selected the first action and I stole one but Pit demon was not destroyed.

**Comment by Achocholacek** [comment]
We're working on this one, requires some tweaks to the engine we haven't nailed down yet. Thanks for the report!

**Comment by skrohmagnon** [comment]
the same with a stunned creature. It wasn't killed it i destun

**Comment by romanogit** [comment]
Found another problem with CF: attached to a creature, click the creature and then Cancel. Creature goes to discard.

**Comment by romanogit** [comment]
Several issues found with CF. Everytime we click on the creature - for example, to prepare and attack or to spread the amber among it, CF behaves differently. 
Sometimes it destroys the creature, when shouldn't. And sometimes it keeps the creature when it should destroy it.
@Achocholacek  : any news about this one?

**Comment by romanogit** [comment]
If player stun an owned creature with CF, it gets destroyed.
