### ISSUE TITLE
Some kind of alert when opponent ends their turn

### ISSUE THREAD

**Issue by srluman** [keyteki/keyteki#269]
Would love a small sound when opponent ends their turn. 

Thanks for your consideration.

**Comment by 4ugeistr** [comment]
+1 
Sometimes you switch to another window to check up rules or decklist.
Sometimes the opponent gets disconnected and you switch to another tab waiting for him to get back and finish his turn.

**Comment by cryogen** [comment]
It's unlikely we'll ever add a sound, but I could consider a flash of the browser tab or some such thing

**Comment by srluman** [comment]
@cryogen May I ask why not? Just curious as someone who is interested in how UI/UX decisions are made across the interwebs :-) 

Thanks!

**Comment by cryogen** [comment]
Sorry for the late response.  I'm just not a huge fan of using sounds on websites, and most browsers these days are very restricted to when they will play sound.  Visual notifications are usually preferred.

**Comment by romanogit** [comment]
@cryogen : would  Notification API be an option?

**Comment by romanogit** [comment]
This Alert! has been implemented in the navigator title bar
