### ISSUE TITLE
TCO Background Image

### ISSUE THREAD

**Issue by Rikuns** [keyteki/keyteki#2692]
This is not a technical issue however I want to ask about the size for TCO background. 
I have seen people with custom background and their background image is perfect but I tried alot of size and all of them turn out to be blurry. 
Please help me by telling me the size for custom background. 
Thank you.

**Comment by blinkingline** [comment]
Here's the background one of the contributors made for Archon Arcana.  
![AAbg](https://user-images.githubusercontent.com/7368564/125117924-c7203580-e0a3-11eb-8b46-81c1997c49ee.jpeg)

It's 3276 X 1843 at 72dpi resolution. 

Hope that helps!

**Comment by SkyJedi** [comment]
Everything gets resized to  something something x 720.

**Comment by romanogit** [comment]
@Rikuns ,
did the above answer help you? Ok to close?

**Comment by Rikuns** [comment]
> @Rikuns ,
> did the above answer help you? Ok to close?

I tried both but found the pic is still blurry. Might just close the issue then :(
