### ISSUE TITLE
ambervac and tide warp

### ISSUE THREAD

**Issue by AleksandrShepelev** [keyteki/keyteki#2697]
I should be able to choose sequence of events at start of my turn

now I cannot, e.g. if tide is theirs I cannot choose warp ability and then ambervac ability

**Comment by romanogit** [comment]
Some upgrades' gained ability does not seem to consistently use `reaction` to `onBeginRound`. some of them are using `interrrupt`, which happens before. Also, the condition check in AmberVac would force it to always happen after TideWarp, but, in some circumstances, someone might not want to capture before raising the tide.

**Comment by AleksandrShepelev** [comment]
also add voice of rakuzel and static charge in tests :D

**Comment by romanogit** [comment]
Tide Warp + Static Charge + Voice of Rakuzel for sure has the same problem. Static Charge will trigger before you raise the tide with tide warp, therefore, the +1 armor of VoR would not be applied it.
