### ISSUE TITLE
Collector Worm-Time Traveler. Time Traveler retrievable by using Help from Future Self after Collector Worm fight.

### ISSUE THREAD

**Issue by Thaddd** [keyteki/keyteki#270]
Time Traveler was played. Opponent used Collector Worm to fight against Time Traveler. Next turn Time Traveler was retrievable by using Help from Future Self.

**Comment by Thaddd** [comment]
Log:
Main phase - PLAYER1
PLAYER1 plays Timetraveller, gaining 1 Æmber 
PLAYER1 uses Timetraveller to draw 2 cards 
PLAYER1 plays Archimedes
PLAYER1 plays Helper Bot
PLAYER1 uses Helper Bot to allow them to play one non-Logos card  this turn
PLAYER1 plays Nerve Blast
PLAYER1 uses Nerve Blast to steal 1 Æmber from PLAYER2
PLAYER1 plays Poke, gaining 1 Æmber 
PLAYER1 uses Poke to deal 1 damage to Challe the Safeguard
PLAYER1 plays Helper Bot
PLAYER1 uses Helper Bot to allow them to play one non-Logos card  this turn
PLAYER1 plays Eyegor
PLAYER1 uses Eyegor to look at the top 3 cards  of their deck
PLAYER1 takes a card  into their hand
Ready phase - PLAYER1
PLAYER1 readies all their cards 
Draw phase - PLAYER1
PLAYER1 draws 5 cards  up to their maximum hand size of 6
End of turn 5
PLAYER2: 1 Æmber  PLAYER1: 5 Æmber 
Turn 5
Key phase - PLAYER2
PLAYER2 does not forge a key as they have 1 Æmber  - current cost: 6 Æmber 
House phase - PLAYER2
PLAYER2 chooses mars  as their active house this turn
Main phase - PLAYER2
PLAYER2 plays Orbital Bombardment, gaining 1 Æmber 
PLAYER2 uses Orbital Bombardment to reveal Custom Virus and to deal 2 damage to a creature 1 times
PLAYER2 plays Custom Virus, gaining 1 Æmber 
PLAYER2 uses Collector Worm to make Collector Worm fight Timetraveller
PLAYER2 uses Ixxyxli Fixfinger to make Ixxyxli Fixfinger fight Eyegor
Ready phase - PLAYER2
PLAYER2 readies all their cards 
Draw phase - PLAYER2
PLAYER2 draws 2 cards  up to their maximum hand size of 6
End of turn 5
PLAYER2: 3 Æmber  PLAYER1: 5 Æmber 
Turn 6
Key phase - PLAYER1
PLAYER1 does not forge a key as they have 5 Æmber  - current cost: 6 Æmber 
House phase - PLAYER1
PLAYER1 chooses logos  as their active house this turn
PLAYER1 uses Memory Chip to archive a card 
Main phase - PLAYER1
PLAYER1 plays Eureka!, gaining 1 Æmber 
PLAYER1 uses Eureka! to gain 2 Æmber 
PLAYER1 plays Help from Future Self, gaining 1 Æmber 
PLAYER1 uses Help from Future Self to search their deck and discard for Timetraveller
PLAYER1 takes Timetraveller into their hand
PLAYER1 shuffles their discard into their deck
PLAYER1 is shuffling their deck
PLAYER1 plays Timetraveller, gaining 1 Æmber 
PLAYER1 uses Timetraveller to draw 2 cards 
PLAYER1 plays Jargogle
PLAYER1 uses Jargogle to place a card  under Jargogle
PLAYER1 uses Helper Bot to reap with Helper Bot
PLAYER1 uses Helper Bot to reap with Helper Bot

**Comment by Achocholacek** [comment]
@Thaddd So in this instance, based on what I can read from the log, nothing is incorrect, as when Collector Worm fights Timetraveller, Timetraveller dies, and therefore would not be archived by Collector Worm, but would go into his controller's discard pile, and therefore be retrievable by HFFS.

Am I missing something?

**Comment by 4ugeistr** [comment]
Yes. Both the Collector Worm and the attacked creature have to survive for the Archiving effect to happen.
Here the Time Traveler wen to discard, so everything resolved as it should.

**Comment by Thaddd** [comment]
Thanks!
