### ISSUE TITLE
Shattered Throne doesn't trigger if assault damage destroys the target

### ISSUE THREAD

**Issue by Tutenkharnage** [keyteki/keyteki#2705]
Shattered Throne is a Brobnar artifact with the constant ability "After a creature is used to fight, it captures 1 aember." If I use a creature with assault X (e.g., Shorty) to fight and the assault damage destroys the target, TCO is not triggering Shattered Throne even though the creature was "used to fight." Cf. the December 2020 fix regarding assault damage and enrage counters:

https://github.com/keyteki/keyteki/issues/1815

Thank you!

**Comment by blinkingline** [comment]
Relevant portion of the rules from [Fight](https://archonarcana.com/Fight) (emphasis mine):
> If either creature in a fight is destroyed while resolving Assault, Hazardous, or "Before Fight:" abilities, then the fight (dealing damage based on power) is skipped. The creatures are not considered to have been in a fight for the purpose of card effects that reference “fighting” or “in a fight”, and the attacking creature’s “Fight:” abilities will not trigger. **Card effects that reference “after a creature fights” or “after a creature is used” will still trigger, as the creature was used to fight (even though the fight did not resolve).**

[Shattered Throne](https://archonarcana.com/Shattered_Throne)'s ability should resolve if the creature is destroyed by [Assault](https://archonarcana.com/Assault) damage.
