### ISSUE TITLE
remote access into gorm of orm

### ISSUE THREAD

**Issue by AleksandrShepelev** [keyteki/keyteki#2708]
opponent plays remote access using my gorm
expected result: gorm leaves play before second sentence resolves, opponent should target another artifact
actual result: gorm stays, opponent can target gorm itself

**Comment by blinkingline** [comment]
Couple of salient points here:
1) When resolving [Gorm of Omm](https://archonarcana.com/Gorm_of_Omm)'s **Omni:** ability, the first sentence tags it for destruction. The rules for [Destroyed](https://archonarcana.com/Destroyed) state that a player cannot choose to destroy a creature if it is already tagged for destruction. I reached out to FFG who confirmed that the intent of the rule is that if an artifact is tagged for destruction, you can't choose to destroy it again. (See third commentary entry [here](https://archonarcana.com/Destroyed#Commentary). )

2) When resolving the **Omni:** ability, the first sentence should tag Gorm of Omm for destruction, then remove it from play as a part of resolving the destruction portion of the timing chart. Once the destruction is complete, the second sentence of the ability will resolve.  ("Once an ability on a card has been triggered (i.e. begins to resolve), that ability will finish resolving even if the card leaves play.)
