### ISSUE TITLE
[Free Markets] Always displays giving 1 Aember, instead of actual Aember gain.

### ISSUE THREAD

**Issue by 4ugeistr** [keyteki/keyteki#272]
Hi. 

[Free Market](https://keyforge-compendium.com/sets/2-aoa/cards/233-free-markets) says:
_Play: Gain 1A (to a maximum of 6) for each house represented among cards in play, except for Sanctum._

It should count the houses of both **player's and opponents** cards in play.
in my game I had Dis card deployed, and the opponent had Dis and Logos.
It only gave me 1 Aember per Free Markers card, so it seems that current logic doesn't take opponents cards into account. Should've given me 2 Aember.

![image](https://user-images.githubusercontent.com/23107141/62428834-fe934400-b70e-11e9-813e-49addeaed213.png)

**Comment by 4ugeistr** [comment]
UPD.
Another game.
Now opponent had 1 house deployed.
I had 2 houses.
The card still gave me 1 Aember only. Should've given me 3.

**Comment by Jarimy123** [comment]
Are you only reading the Chat Window?  Free Markets works fine.  Play again - watch your Aember count before and after playing it.  It works fine, it just doesn't tell you the exact amount in the chat window - it just repeats the cards effect by saying "Gains 1 aember per house" but it still gives you all the aember.

**Comment by 4ugeistr** [comment]
Yeah..... I reread the wording, and it indeed just repeats the card effect description.

I'll retest it later.

**Comment by Achocholacek** [comment]
Tested - the card works fine, the wording just sucks. Fix incoming.
