### ISSUE TITLE
Stretched images

### ISSUE THREAD

**Issue by juliejuly** [keyteki/keyteki#2720]
Image for discard and archives are stretched, does not allow me to check archives, only discard. 
![tcobug](https://user-images.githubusercontent.com/87949193/126911875-bd93636e-6716-4622-ab99-11f60b5224f1.jpg)

**Comment by SkyJedi** [comment]
https://github.com/keyteki/keyteki/pull/2719

**Comment by romanogit** [comment]
Fixed
