### ISSUE TITLE
Mimicry on Swindle doesn't end the phase.

### ISSUE THREAD

**Issue by entropyguardian** [keyteki/keyteki#273]
Mimicry would copy the Omega effect of the card as well, not allow someone to keep playing cards.

![mimicry](https://user-images.githubusercontent.com/53681800/62441029-38b51380-b718-11e9-9e3d-7e25e2c9d7b1.JPG)

**Comment by Achocholacek** [comment]
Thanks for reporting - I have condensed the mimicry issues down to one issue as the effects are universally failing in expected circumstances. See Issue #285 for notes.
