### ISSUE TITLE
Ganger Chieftain doesn't unstun Zorg when there are no opposing creatures. 

### ISSUE THREAD

**Issue by blinkingline** [keyteki/keyteki#2731]
On a previous turn, I played [Zorg](https://archonarcana.com/Zorg)  which enters my battleline [stunned](https://archonarcana.com/Stun).  

On my next turn, I play [Ganger Chieftain](https://archonarcana.com/Ganger_Chieftain) next to Zorg. I resolve Ganger Chieftain’s ability to ready and fight with Zorg. 

Zorg should unstun, but it did not.

**Comment by romanogit** [comment]
Relates to https://github.com/keyteki/keyteki/issues/2710
