### ISSUE TITLE
Hornswoggle to use The Mysticeti is moving it to owner's battleline

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#2739]
Hornswoggle to use The Mysticeti is moving it to owner's battleline. but i believe it should remain exhausted as an artifact.

**Comment by blinkingline** [comment]
Agreed, this should work in the same way as [Remote Access and Auto-Legionary](https://archonarcana.com/Auto-Legionary#FFG_Rulings).  [Mysticeti](https://archonarcana.com/The_Mysticeti) should exhaust and get the +1 Power Counters, but it will fail to go into the battleline.
