### ISSUE TITLE
When a Collector Worm kills a creature in a fight, it shouldn't be archived.

### ISSUE THREAD

**Issue by entropyguardian** [keyteki/keyteki#274]
The creature goes to the discard, not get archived if it doesn't survive the fight.

![collector worm](https://user-images.githubusercontent.com/53681800/62441073-6732ee80-b718-11e9-9bb7-4ee0dc394c66.JPG)

**Comment by tgreaves** [comment]
> "Collector Worm’s “Fight” ability does not happen until after damage is dealt from the fight and the enemy creature is destroyed and placed in the discard pile. At that point, Collector Worm is no longer able to archive it based on the rule that abilities only interact cards in play by default: “Unless an ability explicitly references an out-of-play area (such as a hand, deck, archives, or discard pile), that ability can only interact with cards that are in play.” Collector Worm’s ability does not refer to interacting with cards in the discard pile, so it cannot archive the creature from the discard pile."

**Comment by tgreaves** [comment]
Agree.  Rules clarifications indicate that this should be changed.

**Comment by Achocholacek** [comment]
@entropyguardian Do you remember anything else about board state? Artifacts, other creatures, etc? The way the card is written, it should not archive if the target dies, and the tests we have written support this. As well, In several manual test situations, the dead target is never archived.

As well, in your play log, you fight Hunting Witch (2p) with Thinkdrone (3p), and the witch doesn't die, which suggests there are other factors at play.

It may be that another card on the board is somehow affecting the resolution, so as much info as you can give us would be very helpful

**Comment by entropyguardian** [comment]
The Grey Monk was granting the two Hunting Witches 1 armor. I attacked it first to remove that, as the intention was to kill them both. I wanted to archive Hypnobeam, and be able to pull archives and not put a witch back in their hand in doing so.

Thinkdrone attacked and killed one witch. Collector Worm attacked and killed the second witch. Then it was archived.

Unless I was missing something, it should have taken lethal damage.

I have two worms (also pictured) so I'll continue to stay vigilant with this but if it is programmed to not archive on kill then I'll assume I overlooked something.

**Comment by kballard56** [comment]
i have had the same issue, I had a Streke(elusive), and a dust imp, as my only creatures. No artifacts in play. My opponent had 2 collector worms, He attacked Streke, and archived it as expected. His other collector worm attacked my dust imp, and it got archived, i did not receive 2 amber for its destruction either.

**Comment by cryogen** [comment]
I'm pretty confused by this issue, especially since I usually get complaints that it does the opposite thing!

As far as I know (and can reproduce) CW is working as it should.  Please reopen this if you can provide more information.
