### ISSUE TITLE
Timer position does not look good - should be at the same "line" as hand

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#2761]
![image](https://user-images.githubusercontent.com/2104075/132155633-3b7bee2b-2cac-40d1-91db-b58ae36cf373.png)

**Comment by SteVader** [comment]
Any objections to moving it completely?

![image](https://user-images.githubusercontent.com/2436007/132243757-1272815f-6b4f-4016-a0b6-d117b63d9295.png)
