### ISSUE TITLE
Protectrix doesn't work

### ISSUE THREAD

**Issue by Rikuns** [keyteki/keyteki#2767]
Might be my lack of knowledge but this is the second times I used Protectrix to fully heal a creature but that creature still take damage the same turn. 
![image](https://user-images.githubusercontent.com/83189520/134288933-eef74809-0ec9-4133-a927-c252c15963ac.png)

**Comment by romanogit** [comment]
Did the creature have any damage before you healed it with Protectrix?

**Comment by Rikuns** [comment]
> Did the creature have any damage before you healed it with Protectrix?

I think no. But it has to be damaged to be considered fully healed? @.@

**Comment by blinkingline** [comment]
Based on the rules for [Heal](https://archonarcana.com/Heal), a creature has to have damage removed for it to count as being healed:

Any creature can be chosen to be healed by a card effect that heals, even if it does not have any damage on it. However, if no damage is removed from the creature, it is not considered to have been “healed” for the purpose of card effects that reference healing.

**Comment by romanogit** [comment]
This is working as expected
