### ISSUE TITLE
Wild bounty on an artifact followed by reclaimed by nature doubles both bonuses

### ISSUE THREAD

**Issue by dmikalova** [keyteki/keyteki#2768]
On turn 3 my opponent played a wild bounty followed by niffle grounds to double the bonus on niffle grounds. Then a reclaimed by nature was played to purge niffle grounds and get the bonus, but it seems like wild bounty doubled the bonus that reclaimed by nature got from niffle grounds as well.

Full chat log:
TheReaperN brings Voltavolt, Front Viceroy to The Crucible
dmikalova brings Mercator of Æmberchasm Conservatory to The Crucible
dmikalova won the flip and is first player
 dmikalova has connected to the game server
 TheReaperN has connected to the game server
TheReaperN
Glhf
TheReaperN is shuffling their deck
TheReaperN draws 6 card  s to their maximum of 6
dmikalova is shuffling their deck
dmikalova draws 6 card  s to their maximum of 6
dmikalova draws 1 card 
dmikalova
hi gl hf
Key phase - dmikalova
dmikalova does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses untamed  as their active house this turn
Main phase - dmikalova
dmikalova plays Floomf
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 1 card  to their maximum of 6
End of turn 1
TheReaperN: 0 Æmber  (0 keys) dmikalova: 0 Æmber  (0 keys)
TURN 1 - TheReaperN
Key phase - TheReaperN
TheReaperN does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - TheReaperN
TheReaperN chooses saurian  as their active house this turn
Main phase - TheReaperN
TheReaperN plays Spoils of Battle
TheReaperN gains an Æmber  due to Spoils of Battle's bonus icon
TheReaperN plays Spoils of Battle
TheReaperN gains an Æmber  due to Spoils of Battle's bonus icon
TheReaperN plays Praefectus Ludo
Ready phase - TheReaperN
TheReaperN readies their cards 
Draw phase - TheReaperN
TheReaperN draws 4 card  s to their maximum of 6
End of turn 1
TheReaperN: 2 Æmber  (0 keys) dmikalova: 0 Æmber  (0 keys)
TURN 2 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses saurian  as their active house this turn
Main phase - dmikalova
dmikalova plays Consul Primus
dmikalova plays Faust the Great
dmikalova uses Faust the Great to exalt Consul Primus
dmikalova plays Ancient Power
dmikalova gains an Æmber  due to Ancient Power's bonus icon
dmikalova uses Ancient Power to ward all friendly creatures with Æmber  on it
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 3 card  s to their maximum of 6
End of turn 2
TheReaperN: 2 Æmber  (0 keys) dmikalova: 1 Æmber  (0 keys)
TURN 2 - TheReaperN
Key phase - TheReaperN
TheReaperN does not forge a key. They have 2 amber. The current cost is 7 Æmber 
House phase - TheReaperN
TheReaperN chooses shadows  as their active house this turn
Main phase - TheReaperN
TheReaperN plays Seeker Needle
TheReaperN draws a card  due to Seeker Needle's bonus icon
TheReaperN plays The Shadowsmith
TheReaperN plays Mug
TheReaperN gains an Æmber  due to Mug's bonus icon
TheReaperN uses Mug to move 1 Æmber  from Faust the Great to their pool and deal 2 damage to it
TheReaperN plays One Last Job
TheReaperN gains an Æmber  due to One Last Job's bonus icon
TheReaperN uses One Last Job to purge each friendly shadows  creature and steal that much Æmber  from dmikalova
Ready phase - TheReaperN
TheReaperN readies their cards 
Draw phase - TheReaperN
TheReaperN draws 3 card  s to their maximum of 6
End of turn 2
TheReaperN: 5 Æmber  (0 keys) dmikalova: 0 Æmber  (0 keys)
TURN 3 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses saurian  as their active house this turn
Main phase - dmikalova
dmikalova plays Axiom of Grisk
dmikalova uses Axiom of Grisk to ward Faust the Great, destroy all creatures without Æmber  and give dmikalova 2 chains
dmikalova uses Faust the Great to remove its ward token
dmikalova plays Senator Bracchus
dmikalova plays Ancient Power
dmikalova gains an Æmber  due to Ancient Power's bonus icon
dmikalova uses Ancient Power to ward all friendly creatures with Æmber  on it
dmikalova uses Consul Primus to reap with Consul Primus
dmikalova uses Consul Primus to remove 1 Æmber  from Faust the Great
dmikalova uses Faust the Great to reap with Faust the Great
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 2 card  s to their maximum of 6
dmikalova's chains are reduced by 1 to 1
End of turn 3
TheReaperN: 5 Æmber  (0 keys) dmikalova: 3 Æmber  (0 keys)
TURN 3 - TheReaperN
Key phase - TheReaperN
TheReaperN does not forge a key. They have 5 amber. The current cost is 7 Æmber 
House phase - TheReaperN
TheReaperN chooses untamed  as their active house this turn
Main phase - TheReaperN
**TheReaperN plays Wild Bounty
TheReaperN uses Wild Bounty to apply a lasting effect
TheReaperN plays Niffle Grounds
TheReaperN uses Wild Bounty to resolve the bonus icons of Niffle Grounds an additional time
TheReaperN gains an Æmber  due to Niffle Grounds's bonus icon
TheReaperN gains an Æmber  due to Niffle Grounds's bonus icon
TheReaperN plays Reclaimed by Nature
TheReaperN gains an Æmber  due to Reclaimed by Nature's bonus icon
TheReaperN uses Reclaimed by Nature to purge Niffle Grounds and resolve its bonus icons
TheReaperN gains an Æmber  due to Niffle Grounds's bonus icon
TheReaperN gains an Æmber  due to Niffle Grounds's bonus icon**
TheReaperN plays Keyfrog
TheReaperN plays Cephaloist
Ready phase - TheReaperN
TheReaperN readies their cards 
Draw phase - TheReaperN
TheReaperN draws 5 card  s to their maximum of 6
 TheReaperN declares Check!
End of turn 3
TheReaperN: 10 Æmber  (0 keys) dmikalova: 3 Æmber  (0 keys)
TURN 4 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova
it seems like you got an extra aember from reclaimed from wild bounty
dmikalova chooses saurian  as their active house this turn
Main phase - dmikalova
dmikalova plays Cornicen Octavia
TheReaperN
Weird
dmikalova plays Crystal Surge
dmikalova gains an Æmber  due to Crystal Surge's bonus icon
dmikalova uses Crystal Surge to exalt Cephaloist
dmikalova uses Consul Primus to reap with Consul Primus
dmikalova uses Consul Primus to remove 1 Æmber  from Consul Primus
dmikalova uses Consul Primus to place 1 Æmber  on Cephaloist
 TheReaperN is attempting to switch manual mode on
 dmikalova allows enabling manual mode
 TheReaperN switches manual mode on
dmikalova uses Senator Bracchus to reap with Senator Bracchus
dmikalova uses Senator Bracchus to exalt Senator Bracchus
 TheReaperN sets Æmber  to 9 ( -1 )
 TheReaperN switches manual mode off
dmikalova uses Faust the Great to reap with Faust the Great
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 2 card  s to their maximum of 6
dmikalova's chains are reduced by 1 to 0
 dmikalova declares Check!
End of turn 4
TheReaperN: 9 Æmber  (0 keys) dmikalova: 7 Æmber  (0 keys)
TURN 4 - TheReaperN
Key phase - TheReaperN
dmikalova
thanks
TheReaperN forges the yellow key  , paying 7 Æmber 
House phase - TheReaperN
TheReaperN
Np interesting case there
dmikalova
ya... time to make a bug report :p
TheReaperN chooses shadows  as their active house this turn
Main phase - TheReaperN
TheReaperN plays Ransack
TheReaperN uses Ransack to steal 1 Æmber  from dmikalova; and discard Resurgence
TheReaperN uses Seeker Needle to deal damage to Consul Primus
Consul Primus's ward token prevents the damage dealt by Seeker Needle and is discarded
TheReaperN plays Francis the "Economist"
TheReaperN plays Tempting Offer
TheReaperN gains an Æmber  due to Tempting Offer's bonus icon
TheReaperN uses Tempting Offer to return Senator Bracchus to their hand
Ready phase - TheReaperN
TheReaperN readies their cards 
Draw phase - TheReaperN
TheReaperN draws 3 card  s to their maximum of 6
End of turn 4
TheReaperN: 5 Æmber  (1 key) dmikalova: 7 Æmber  (0 keys)
TURN 5 - dmikalova
Key phase - dmikalova
dmikalova forges the yellow key  , paying 6 Æmber 
House phase - dmikalova
dmikalova chooses saurian  as their active house this turn
Main phase - dmikalova
dmikalova plays Senator Bracchus
dmikalova plays Thero Centurion
dmikalova uses Thero Centurion to capture 1 Æmber  from their opponent , placing it on Thero Centurion
dmikalova uses Consul Primus to reap with Consul Primus
dmikalova uses Consul Primus to remove 1 Æmber  from Thero Centurion
dmikalova uses Consul Primus to place 1 Æmber  on Cephaloist
dmikalova uses Cornicen Octavia to reap with Cornicen Octavia
dmikalova uses Faust the Great to reap with Faust the Great
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 2 card  s to their maximum of 6
End of turn 5
TheReaperN: 4 Æmber  (1 key) dmikalova: 4 Æmber  (1 key)
TURN 5 - TheReaperN
Key phase - TheReaperN
TheReaperN does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - TheReaperN
TheReaperN chooses saurian  as their active house this turn
Main phase - TheReaperN
TheReaperN plays Cornicen Octavia
TheReaperN gains an Æmber  due to Cornicen Octavia's bonus icon
TheReaperN plays Faust the Great
TheReaperN uses Faust the Great to exalt Cephaloist
TheReaperN plays Exile
TheReaperN gains an Æmber  due to Exile's bonus icon
TheReaperN captures an Æmber  on Cephaloist due to Exile's bonus icon
TheReaperN uses Exile to give control of Cephaloist to dmikalova
dmikalova
niiiice
TheReaperN
Lol
TheReaperN
Im just trolling i messed up
TheReaperN plays Techno-Saurus
TheReaperN uses Techno-Saurus to exalt Techno-Saurus
Ready phase - TheReaperN
TheReaperN readies their cards 
Draw phase - TheReaperN
TheReaperN draws 4 card  s to their maximum of 6
 TheReaperN declares Check!
End of turn 5
TheReaperN: 6 Æmber  (1 key) dmikalova: 3 Æmber  (1 key)
TURN 6 - dmikalova
Key phase - dmikalova
dmikalova uses 5 Æmber  from Cephaloist to forge a key
dmikalova forges the blue key  , paying 7 Æmber 
House phase - dmikalova
dmikalova
it happens :x
dmikalova chooses saurian  as their active house this turn
Main phase - dmikalova
dmikalova uses Thero Centurion to make Thero Centurion fight Faust the Great
dmikalova uses Thero Centurion to capture 1 Æmber  from their opponent , placing it on Thero Centurion
dmikalova uses Consul Primus to reap with Consul Primus
dmikalova uses Consul Primus to remove 1 Æmber  from Thero Centurion
dmikalova uses Consul Primus to place 1 Æmber  on Techno-Saurus
dmikalova uses Senator Bracchus to reap with Senator Bracchus
dmikalova uses Senator Bracchus to exalt Senator Bracchus
dmikalova uses Cornicen Octavia to reap with Cornicen Octavia
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
End of turn 6
TheReaperN: 5 Æmber  (1 key) dmikalova: 4 Æmber  (2 keys)
TURN 6 - TheReaperN
Key phase - TheReaperN
TheReaperN does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - TheReaperN
TheReaperN chooses shadows  as their active house this turn
Main phase - TheReaperN
TheReaperN plays Sacro-Thief
TheReaperN gains an Æmber  due to Sacro-Thief's bonus icon
TheReaperN draws a card  due to Sacro-Thief's bonus icon
TheReaperN uses Francis the "Economist" to make Francis the "Economist" fight Consul Primus
TheReaperN uses Francis the "Economist" to gain 1 Æmber 
TheReaperN plays Opportunist attaching it to Cornicen Octavia
TheReaperN gains an Æmber  due to Opportunist's bonus icon
TheReaperN uses Opportunist to capture 1 Æmber  from dmikalova, placing it on Cornicen Octavia
TheReaperN plays Lights Out
TheReaperN gains an Æmber  due to Lights Out's bonus icon
TheReaperN uses Lights Out to return Senator Bracchus and Cephaloist to their hand
TheReaperN uses Seeker Needle to deal damage to Keyfrog
Ready phase - TheReaperN
TheReaperN readies their cards 
Draw phase - TheReaperN
TheReaperN draws 1 card  to their maximum of 6
 TheReaperN declares Check!
End of turn 6
TheReaperN: 10 Æmber  (1 key) dmikalova: 4 Æmber  (2 keys)
TURN 7 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses dis  as their active house this turn
Main phase - dmikalova
dmikalova plays Gleeful Mayhem
dmikalova gains an Æmber  due to Gleeful Mayhem's bonus icon
dmikalova deals 1 damage to Cornicen Octavia due to Gleeful Mayhem's bonus icon
dmikalova uses Gleeful Mayhem to deal 5 damage to Cornicen Octavia, Sacro-Thief, and Keyfrog
TheReaperN uses Keyfrog to forge a key
TheReaperN forges the red key  , paying 6 Æmber 
dmikalova plays Mindfire
dmikalova uses Mindfire to discard a card  at random from TheReaperN's hand
TheReaperN discards Po’s Pixies at random
dmikalova plays Snudge
dmikalova captures an Æmber  on Cornicen Octavia due to Snudge's bonus icon
dmikalova plays Maleficorn
dmikalova plays Impspector
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 4 card  s to their maximum of 6
 dmikalova declares Check!
End of turn 7
TheReaperN: 3 Æmber  (2 keys) dmikalova: 6 Æmber  (2 keys)
TURN 7 - TheReaperN
Key phase - TheReaperN
TheReaperN does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - TheReaperN
TheReaperN chooses untamed  as their active house this turn
Main phase - TheReaperN
TheReaperN plays Resurgence
TheReaperN uses Resurgence to return Faust the Great to their hand
 TheReaperN concedes
 dmikalova has won the game
TheReaperN
Gg
dmikalova
gg
dmikalova would like a rematch
 TheReaperN has left the game

**Comment by romanogit** [comment]
This is working as expected.  I base that on the UG vs. Fission Bloom ruling:

![image](https://user-images.githubusercontent.com/2104075/194649076-6744b1eb-3196-4cd6-92dd-3f0db96b94df.png)

https://archonarcana.com/Fission_Bloom

**Comment by romanogit** [comment]
Sorry, I misread Wild Bounty.

**Comment by romanogit** [comment]
This is a very interesting corner case. Possibly it would happen if we return a card played to hand as well.
