### ISSUE TITLE
Bug - Mimicry and Might Makes Right

### ISSUE THREAD

**Issue by Peppoz93** [keyteki/keyteki#277]
Might Makes Right doesn't forge a key (I didn't have limitation on forging)
Mimicry could not chose Eureka at the end of turn, because Eureka is Alpha

**Comment by Achocholacek** [comment]
Thanks for reporting - I have condensed the mimicry issues down to one issue as the effects are universally failing in expected circumstances. See Issue #285 for notes.

Re Might Makes Right - do you remember board state? was there power modifiers or tokens on the creatures you sacrificed? That's a known issue right now.

**Comment by Peppoz93** [comment]
I played MMR in 2 different match, in first I sacrificed more than 25 power with power plus effect applied through Anga Panpaca and Marmo (with 5 aembers). In second I sacrificed 25 power written in card (without plus power effect) and it bugs again

**Comment by cryogen** [comment]
I'm pretty sure both of these issues are now resolved.  Please reopen if not the case
