### ISSUE TITLE
Borrow on Masterplan

### ISSUE THREAD

**Issue by Osarek** [keyteki/keyteki#2779]
If use borrow opponent Masterplan, i cannot see the card under it. 
may be related to https://github.com/keyteki/keyteki/issues/1665

![image](https://archonarcana.com/images/d/db/496-213.png)
![image](https://archonarcana.com/images/2/2e/496-201.png)

**Comment by SkyJedi** [comment]
We treat cards played facedown non public knowledge.  No player can see the
cards under masterplan or jargogle

**Comment by Osarek** [comment]
From rulebook 17-1 it seems that we can see facedown card
![image](https://github.com/keyteki/keyteki/assets/57572496/d8ee3c4c-2701-48d5-822f-5d17b4d00d92)
