### ISSUE TITLE
Lifeweb and Securidroid as an upgrade is bugged

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#2784]
Question: Played 2 Securidroids as upgrades and 1 other SA creature - the turn after my opponent plays Lifeweb and gets to steal from it. Is that a bug or is it intended behaviour? I think it feels off.

**Comment by dgbrokaw** [comment]
Lifeweb uses an EventRegistrar instance and sets up a listener on the onCardPlayed event. When this listener fires, the card of that event, Securi-Droid, still has the creature type and thus counts towards the creaturesPlayed count it tracks (causing the bug).

I think the issue stems from when the onCardPlayed event fires in relation to the onEffectApplied event. When Securi-Droid is played as an upgrade, PlayUpgradeAction adds a sub-event to the current event. The handler of this event is called after the onCardPlayed event has been emitted by EventWindow. The EventRegistrar in Lifeweb will trigger its listener before the onEffectApplied handler has been called.

![creature-as-upgrade-event](https://user-images.githubusercontent.com/7118380/143669787-5fc38645-ee19-4a93-9f69-97f585c480cf.png)

I thought a potential hacky solution in Lifeweb would be to also listen to the onEffectApplied event and subtract from the creaturesPlayed count if the card was the same as what had added to the count earlier. However, even though my new listener fired, the Securi-Droid still had the creature type. I don't know why yet.

<img width="569" alt="lifeweb-listener" src="https://user-images.githubusercontent.com/7118380/143669807-6f480ac8-346a-4374-aa86-9d625dbdc0c1.png">

**Comment by dgbrokaw** [comment]
I thought this would also be a problem for cards like The Big One, but upgrade-creatures have the correct type by the time those listeners fire.
