### ISSUE TITLE
Verokter fought Undagnathus during high tide, took exactly 1 damage back?

### ISSUE THREAD

**Issue by UltimoFox** [keyteki/keyteki#2785]
Not sure where this damage came from, since it wasn't on the logs at all. Couldn't find a reason, but here's the copied log as well as a screenshot of the board state after ending the turn (although there's a lot, I apologise).
![image](https://user-images.githubusercontent.com/47079472/143499932-aed4cdeb-d4d1-4d68-97b2-9e324cbe4f89.png)
TH3Cap7a1n26 brings Greenhowl, the Scofflaw of Confusion to The Crucible
UltimoFox700 brings Deepielle the Blessed to The Crucible
 UltimoFox700 has connected to the game server
 TH3Cap7a1n26 has connected to the game server
TH3Cap7a1n26
that was nice
UltimoFox700 chooses to go first
TH3Cap7a1n26 is shuffling their deck
TH3Cap7a1n26 draws 6 card  s to their maximum of 6
UltimoFox700 is shuffling their deck
UltimoFox700 draws 6 card  s to their maximum of 6
UltimoFox700 draws 1 card 
UltimoFox700
I will risk this hand
Key phase - UltimoFox700
UltimoFox700 does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - UltimoFox700
UltimoFox700 chooses logos  as their active house this turn
Main phase - UltimoFox700
UltimoFox700 plays Eureka!
UltimoFox700 gains an Æmber  due to Eureka!'s bonus icon
UltimoFox700 uses Eureka! to gain 2 Æmber 
Ready phase - UltimoFox700
Draw phase - UltimoFox700
UltimoFox700 draws 2 card  s to their maximum of 6
End of turn 1
TH3Cap7a1n26: 0 Æmber  (0 keys) UltimoFox700: 3 Æmber  (0 keys)
TURN 1 - TH3Cap7a1n26
Key phase - TH3Cap7a1n26
TH3Cap7a1n26 does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - TH3Cap7a1n26
TH3Cap7a1n26 chooses staralliance  as their active house this turn
Main phase - TH3Cap7a1n26
TH3Cap7a1n26 plays CH-337A
Ready phase - TH3Cap7a1n26
TH3Cap7a1n26 readies their cards 
Draw phase - TH3Cap7a1n26
TH3Cap7a1n26 draws 2 card  s to their maximum of 6
End of turn 1
TH3Cap7a1n26: 0 Æmber  (0 keys) UltimoFox700: 3 Æmber  (0 keys)
TURN 2 - UltimoFox700
Key phase - UltimoFox700
UltimoFox700 does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - UltimoFox700
 KarenB has joined the game as a spectator
UltimoFox700 chooses logos  as their active house this turn
Main phase - UltimoFox700
UltimoFox700 plays Static Charge attaching it to CH-337A
UltimoFox700 gains an Æmber  due to Static Charge's bonus icon
UltimoFox700 plays Static Charge attaching it to CH-337A
UltimoFox700 gains an Æmber  due to Static Charge's bonus icon
UltimoFox700 plays Bilgewarden
UltimoFox700 uses Bilgewarden to raise tide  for UltimoFox700
Ready phase - UltimoFox700
UltimoFox700 readies their cards 
Draw phase - UltimoFox700
UltimoFox700 draws 3 card  s to their maximum of 6
End of turn 2
TH3Cap7a1n26: 0 Æmber  (0 keys) UltimoFox700: 5 Æmber  (0 keys)
TURN 2 - TH3Cap7a1n26
Key phase - TH3Cap7a1n26
TH3Cap7a1n26 does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - TH3Cap7a1n26
TH3Cap7a1n26 chooses saurian  as their active house this turn
Main phase - TH3Cap7a1n26
TH3Cap7a1n26 plays Crushing Charge
TH3Cap7a1n26 uses Crushing Charge to destroy each creature with power 4 or lower and gain 1 chain
TH3Cap7a1n26 plays Consul Primus
Ready phase - TH3Cap7a1n26
TH3Cap7a1n26 readies their cards 
Draw phase - TH3Cap7a1n26
TH3Cap7a1n26 draws 1 card  to their maximum of 6
TH3Cap7a1n26's chains are reduced by 1 to 0
End of turn 2
TH3Cap7a1n26: 0 Æmber  (0 keys) UltimoFox700: 5 Æmber  (0 keys)
TURN 3 - UltimoFox700
Key phase - UltimoFox700
UltimoFox700 does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - UltimoFox700
UltimoFox700 chooses staralliance  as their active house this turn
UltimoFox700 moves all the cards  in their archives to their hand
Main phase - UltimoFox700
UltimoFox700 plays Lieutenant Valmart
UltimoFox700 uses Lieutenant Valmart to increase key cost by 3 during TH3Cap7a1n26's next turn
UltimoFox700 plays Exploratory Craft
UltimoFox700 plays Xenotraining
UltimoFox700 gains an Æmber  due to Xenotraining's bonus icon
UltimoFox700 plays Force Field attaching it to Lieutenant Valmart
UltimoFox700 gains an Æmber  due to Force Field's bonus icon
Ready phase - UltimoFox700
UltimoFox700 readies their cards 
Draw phase - UltimoFox700
UltimoFox700 draws 2 card  s to their maximum of 6
 UltimoFox700 declares Check!
End of turn 3
TH3Cap7a1n26: 0 Æmber  (0 keys) UltimoFox700: 7 Æmber  (0 keys)
TURN 3 - TH3Cap7a1n26
Key phase - TH3Cap7a1n26
TH3Cap7a1n26 does not forge a key. They have 0 amber. The current cost is 9 Æmber 
House phase - TH3Cap7a1n26
TH3Cap7a1n26 chooses staralliance  as their active house this turn
Main phase - TH3Cap7a1n26
TH3Cap7a1n26 plays Shield-U-Later
TH3Cap7a1n26 captures an Æmber  on Shield-U-Later due to Shield-U-Later's bonus icon
TH3Cap7a1n26 captures an Æmber  on Consul Primus due to Shield-U-Later's bonus icon
TH3Cap7a1n26 deals 1 damage to Lieutenant Valmart due to Shield-U-Later's bonus icon
Ready phase - TH3Cap7a1n26
TH3Cap7a1n26 readies their cards 
Draw phase - TH3Cap7a1n26
TH3Cap7a1n26 draws 2 card  s to their maximum of 6
End of turn 3
TH3Cap7a1n26: 0 Æmber  (0 keys) UltimoFox700: 5 Æmber  (0 keys)
TURN 4 - UltimoFox700
Key phase - UltimoFox700
UltimoFox700 does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - UltimoFox700
UltimoFox700 chooses staralliance  as their active house this turn
Main phase - UltimoFox700
UltimoFox700 plays Lieutenant Valmart
UltimoFox700 uses Lieutenant Valmart to increase key cost by 3 during TH3Cap7a1n26's next turn
UltimoFox700 uses Lieutenant Valmart to reap with Lieutenant Valmart
UltimoFox700 uses Lieutenant Valmart to ward Lieutenant Valmart
UltimoFox700 uses Lieutenant Valmart to increase key cost by 3 during TH3Cap7a1n26's next turn
UltimoFox700 uses Exploratory Craft
Ready phase - UltimoFox700
UltimoFox700 readies their cards 
Draw phase - UltimoFox700
UltimoFox700 draws 1 card  to their maximum of 6
 UltimoFox700 declares Check!
End of turn 4
TH3Cap7a1n26: 0 Æmber  (0 keys) UltimoFox700: 6 Æmber  (0 keys)
TURN 4 - TH3Cap7a1n26
Key phase - TH3Cap7a1n26
TH3Cap7a1n26 does not forge a key. They have 0 amber. The current cost is 12 Æmber 
House phase - TH3Cap7a1n26
TH3Cap7a1n26 chooses unfathomable  as their active house this turn
Main phase - TH3Cap7a1n26
TH3Cap7a1n26 plays Pour-tal
TH3Cap7a1n26 gains an Æmber  due to Pour-tal's bonus icon
TH3Cap7a1n26 uses Pour-tal to raise the tide 
TH3Cap7a1n26 plays Wrath or Ruin
TH3Cap7a1n26 chooses option ' Destroy a flank creature '
TH3Cap7a1n26 uses Wrath or Ruin to destroy Lieutenant Valmart
TH3Cap7a1n26 plays Sink or Swim
TH3Cap7a1n26 chooses option ' Random discard '
TH3Cap7a1n26 uses Sink or Swim to discard a card  at random from UltimoFox700's hand
UltimoFox700 discards Badgemagus at random
TH3Cap7a1n26 plays Giltspine Netcaster
Ready phase - TH3Cap7a1n26
TH3Cap7a1n26 readies their cards 
Draw phase - TH3Cap7a1n26
TH3Cap7a1n26 draws 4 card  s to their maximum of 6
End of turn 4
TH3Cap7a1n26: 1 Æmber  (0 keys) UltimoFox700: 6 Æmber  (0 keys)
TURN 5 - UltimoFox700
Key phase - UltimoFox700
UltimoFox700 forges the red key  , paying 6 Æmber 
House phase - UltimoFox700
UltimoFox700 chooses logos  as their active house this turn
Main phase - UltimoFox700
UltimoFox700 plays Rooftop Laboratory
UltimoFox700 plays Backup Plan
UltimoFox700 uses Backup Plan to archive 2 cards 
UltimoFox700 plays Theory or Conjecture
UltimoFox700 chooses option ' Play top card  '
UltimoFox700 uses Theory or Conjecture to play Biome Discovery
UltimoFox700 plays Biome Discovery
UltimoFox700 gains an Æmber  due to Biome Discovery's bonus icon
UltimoFox700 uses Biome Discovery to raise the tide 
Ready phase - UltimoFox700
UltimoFox700 readies their cards 
Draw phase - UltimoFox700
UltimoFox700 draws 4 card  s to their maximum of 6
End of turn 5
TH3Cap7a1n26: 1 Æmber  (0 keys) UltimoFox700: 1 Æmber  (1 key)
TURN 5 - TH3Cap7a1n26
Key phase - TH3Cap7a1n26
TH3Cap7a1n26 does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - TH3Cap7a1n26
TH3Cap7a1n26 chooses saurian  as their active house this turn
Main phase - TH3Cap7a1n26
TH3Cap7a1n26 plays Lapisaurus
TH3Cap7a1n26 uses Consul Primus to reap with Consul Primus
TH3Cap7a1n26 uses Consul Primus to remove 1 Æmber  from Consul Primus
TH3Cap7a1n26 uses Consul Primus to place 1 Æmber  on Lieutenant Valmart
Ready phase - TH3Cap7a1n26
TH3Cap7a1n26 readies their cards 
Draw phase - TH3Cap7a1n26
TH3Cap7a1n26 draws 1 card  to their maximum of 6
End of turn 5
TH3Cap7a1n26: 2 Æmber  (0 keys) UltimoFox700: 1 Æmber  (1 key)
TURN 6 - UltimoFox700
Key phase - UltimoFox700
UltimoFox700 does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - UltimoFox700
UltimoFox700 chooses sanctum  as their active house this turn
Main phase - UltimoFox700
UltimoFox700 plays Radiant Truth
UltimoFox700 gains an Æmber  due to Radiant Truth's bonus icon
UltimoFox700 uses Radiant Truth to stun Consul Primus and Giltspine Netcaster
UltimoFox700 plays Sir Bevor
UltimoFox700 plays Shifting Battlefield
UltimoFox700 gains an Æmber  due to Shifting Battlefield's bonus icon
UltimoFox700 uses Shifting Battlefield to do several things
UltimoFox700 plays Bring Low
UltimoFox700 gains an Æmber  due to Bring Low's bonus icon
Ready phase - UltimoFox700
UltimoFox700 readies their cards 
Draw phase - UltimoFox700
UltimoFox700 draws 4 card  s to their maximum of 6
End of turn 6
TH3Cap7a1n26: 1 Æmber  (0 keys) UltimoFox700: 4 Æmber  (1 key)
TURN 6 - TH3Cap7a1n26
Key phase - TH3Cap7a1n26
TH3Cap7a1n26 does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - TH3Cap7a1n26
TH3Cap7a1n26
i know what you mena about no E
TH3Cap7a1n26 chooses unfathomable  as their active house this turn
Main phase - TH3Cap7a1n26
TH3Cap7a1n26 plays Echo Pearl
TH3Cap7a1n26 gains an Æmber  due to Echo Pearl's bonus icon
TH3Cap7a1n26 plays Flamegill Enforcer
TH3Cap7a1n26 exhausts Giltspine Netcaster to remove its stun
TH3Cap7a1n26 plays Giltspine Netcaster
Ready phase - TH3Cap7a1n26
TH3Cap7a1n26 readies their cards 
Draw phase - TH3Cap7a1n26
TH3Cap7a1n26 draws 3 card  s to their maximum of 6
End of turn 6
TH3Cap7a1n26: 2 Æmber  (0 keys) UltimoFox700: 4 Æmber  (1 key)
TURN 7 - UltimoFox700
Key phase - UltimoFox700
UltimoFox700 does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - UltimoFox700
UltimoFox700
16 E according to DoK, but it expects each Pour-tal to provide 2 thanks to archiving
UltimoFox700 chooses staralliance  as their active house this turn
UltimoFox700 moves all the cards  in their archives to their hand
Main phase - UltimoFox700
UltimoFox700 plays Diplomat Agung
TH3Cap7a1n26
yea,
UltimoFox700 chooses house staralliance 
TH3Cap7a1n26
im really struggling to get more than 3 this game
UltimoFox700 uses Diplomat Agung to make Sir Bevor belong to house staralliance  in addition to its other houses
UltimoFox700 uses Sir Bevor to reap with Sir Bevor
UltimoFox700 uses Lieutenant Valmart to reap with Lieutenant Valmart
UltimoFox700 uses Lieutenant Valmart to ward Lieutenant Valmart
UltimoFox700 uses Lieutenant Valmart to increase key cost by 3 during TH3Cap7a1n26's next turn
UltimoFox700 plays Technobabble
UltimoFox700 gains an Æmber  due to Technobabble's bonus icon
UltimoFox700 uses Technobabble to stun Flamegill Enforcer and Giltspine Netcaster
UltimoFox700 plays Universal Translator attaching it to Diplomat Agung
UltimoFox700 gains an Æmber  due to Universal Translator's bonus icon
UltimoFox700 plays T3R-35A attaching it to Diplomat Agung
KarenB
now that's a good sign
UltimoFox700 uses Exploratory Craft
Ready phase - UltimoFox700
UltimoFox700 readies their cards 
Draw phase - UltimoFox700
UltimoFox700 draws 2 card  s to their maximum of 6
 UltimoFox700 declares Check!
End of turn 7
TH3Cap7a1n26: 2 Æmber  (0 keys) UltimoFox700: 8 Æmber  (1 key)
TURN 7 - TH3Cap7a1n26
Key phase - TH3Cap7a1n26
TH3Cap7a1n26 does not forge a key. They have 2 amber. The current cost is 9 Æmber 
House phase - TH3Cap7a1n26
KarenB
Fox almost grabs game one and then the decks is doing nothing for you first time
TH3Cap7a1n26
exactly
UltimoFox700
That is a good sign, but I have a feeling I got better draws than he did
TH3Cap7a1n26 chooses staralliance  as their active house this turn
Main phase - TH3Cap7a1n26
UltimoFox700
Probably can't all be down to draw of course, but it's something to consider
KarenB
fair
TH3Cap7a1n26 plays Grand Alliance Council
TH3Cap7a1n26 uses Grand Alliance Council to destroy Consul Primus, Flamegill Enforcer, Giltspine Netcaster, Diplomat Agung, and Lieutenant Valmart
UltimoFox700 uses Lieutenant Valmart to remove its ward token
UltimoFox700
If we get time next Tuesday I'd like to get more games in to see if we can find more evidence in any particular direction
TH3Cap7a1n26 uses Echo Pearl to destroy Echo Pearl
TH3Cap7a1n26 uses Echo Pearl to exhaust, stun and enrage Lieutenant Valmart
UltimoFox700
Or even before then if the 3 of us are free then
TH3Cap7a1n26 plays Mutagenesis Researcher
TH3Cap7a1n26 plays Com. Officer Gross
TH3Cap7a1n26 draws a card  due to Com. Officer Gross's bonus icon
TH3Cap7a1n26 uses Com. Officer Gross to search for Com. Officer Hings and add it to their hand
TH3Cap7a1n26 takes Com. Officer Hings into their hand
TH3Cap7a1n26 plays Com. Officer Hings
TH3Cap7a1n26 captures an Æmber  on Giltspine Netcaster due to Com. Officer Hings's bonus icon
TH3Cap7a1n26 uses Com. Officer Hings to search for Com. Officer Hings and add it to their hand
TH3Cap7a1n26 doesn't take anything
TH3Cap7a1n26 plays Encounter Suit attaching it to Com. Officer Hings
KarenB
still some tricks left here
TH3Cap7a1n26 plays Stunner attaching it to Shield-U-Later
TH3Cap7a1n26 gains an Æmber  due to Stunner's bonus icon
TH3Cap7a1n26 uses Shield-U-Later to make Shield-U-Later fight Sir Bevor
UltimoFox700
Yeah, not much I can do against Encounter Suit Hings here
TH3Cap7a1n26 uses Shield-U-Later to stun Sir Bevor
Ready phase - TH3Cap7a1n26
TH3Cap7a1n26 readies their cards 
Draw phase - TH3Cap7a1n26
TH3Cap7a1n26 draws 4 card  s to their maximum of 6
End of turn 7
TH3Cap7a1n26: 3 Æmber  (0 keys) UltimoFox700: 7 Æmber  (1 key)
TURN 8 - UltimoFox700
Key phase - UltimoFox700
UltimoFox700 forges the blue key  , paying 6 Æmber 
House phase - UltimoFox700
TH3Cap7a1n26
dod you too grand alliance council here?
UltimoFox700 chooses logos  as their active house this turn
Main phase - UltimoFox700
TH3Cap7a1n26
do you have two*
UltimoFox700
The deck has 2 of them, yeah
UltimoFox700 plays Think Twice
TH3Cap7a1n26 uses Encounter Suit to ward Com. Officer Hings
KarenB
painting my nails watching this lol
UltimoFox700
So I could backup plan or I could Technobabble Mutagenesis Researcher
KarenB
good entertainment
UltimoFox700 uses Think Twice to do several things
UltimoFox700 plays Backup Plan
TH3Cap7a1n26 uses Encounter Suit to ward Com. Officer Hings
UltimoFox700 uses Backup Plan to archive 4 cards 
TH3Cap7a1n26
you're in a good poistion
TH3Cap7a1n26
didnt even need THE combo
UltimoFox700 plays Reckless Experimentation attaching it to Sir Bevor
UltimoFox700 gains an Æmber  due to Reckless Experimentation's bonus icon
Ready phase - UltimoFox700
UltimoFox700 readies their cards 
Draw phase - UltimoFox700
UltimoFox700 draws 2 card  s to their maximum of 6
End of turn 8
TH3Cap7a1n26: 3 Æmber  (0 keys) UltimoFox700: 2 Æmber  (2 keys)
TURN 8 - TH3Cap7a1n26
Key phase - TH3Cap7a1n26
TH3Cap7a1n26 does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - TH3Cap7a1n26
TH3Cap7a1n26 chooses staralliance  as their active house this turn
Main phase - TH3Cap7a1n26
TH3Cap7a1n26 uses Com. Officer Hings to reap with Com. Officer Hings
UltimoFox700
We'll see, I look ahead but I don't have as many options as I'd like atm
TH3Cap7a1n26 uses Com. Officer Hings to draw 4 cards 
TH3Cap7a1n26 draws 4 card  s
TH3Cap7a1n26 uses Com. Officer Gross to reap with Com. Officer Gross
TH3Cap7a1n26 uses Com. Officer Gross to place 1 +1 power counter on Mutagenesis Researcher, Shield-U-Later, Giltspine Netcaster, and Lapisaurus
TH3Cap7a1n26 plays Operative Espion
TH3Cap7a1n26 plays Diplomat Agung
TH3Cap7a1n26 chooses house staralliance 
TH3Cap7a1n26 uses Diplomat Agung to make Giltspine Netcaster belong to house staralliance  in addition to its other houses
TH3Cap7a1n26 uses Giltspine Netcaster to reap with Giltspine Netcaster
TH3Cap7a1n26 uses Giltspine Netcaster to exhaust Lieutenant Valmart
TH3Cap7a1n26 uses Mutagenesis Researcher to reap with Mutagenesis Researcher
TH3Cap7a1n26 uses Shield-U-Later to reap with Shield-U-Later
TH3Cap7a1n26 uses Shield-U-Later to stun Sir Bevor
TH3Cap7a1n26 changed tide  to High
TH3Cap7a1n26 uses Operative Espion to use Lapisaurus
TH3Cap7a1n26 uses Lapisaurus to reap with Lapisaurus
Ready phase - TH3Cap7a1n26
TH3Cap7a1n26 readies their cards 
Draw phase - TH3Cap7a1n26
 TH3Cap7a1n26 declares Check!
End of turn 8
TH3Cap7a1n26: 9 Æmber  (0 keys) UltimoFox700: 2 Æmber  (2 keys)
TURN 9 - UltimoFox700
Key phase - UltimoFox700
UltimoFox700 does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - UltimoFox700
UltimoFox700 chooses sanctum  as their active house this turn
UltimoFox700 moves all the cards  in their archives to their hand
Main phase - UltimoFox700
UltimoFox700 exhausts Sir Bevor to remove its stun
UltimoFox700 plays Gatekeeper
UltimoFox700 uses Gatekeeper to capture 4 Æmber  from their opponent , placing it on Gatekeeper
UltimoFox700 plays Sir Bevor
UltimoFox700 plays Lærie of the Lake
UltimoFox700 plays Bull-wark
UltimoFox700 changed tide  to High
UltimoFox700 uses Operative Espion to use Lieutenant Valmart
UltimoFox700 plays Cleansing Wave
TH3Cap7a1n26 uses Encounter Suit to ward Com. Officer Hings
UltimoFox700 uses Cleansing Wave to heal 1 damage from all creatures
Cleansing Wave heals Lieutenant Valmart, gaining UltimoFox700 1 Æmber 
UltimoFox700 plays Strange Ordination
TH3Cap7a1n26 uses Encounter Suit to ward Com. Officer Hings
UltimoFox700 gains an Æmber  due to Strange Ordination's bonus icon
UltimoFox700 gains an Æmber  due to Strange Ordination's bonus icon
UltimoFox700 gains an Æmber  due to Strange Ordination's bonus icon
Ready phase - UltimoFox700
UltimoFox700 readies their cards 
Draw phase - UltimoFox700
UltimoFox700 draws 1 card  to their maximum of 6
UltimoFox700's chains are reduced by 1 to 2
 UltimoFox700 declares Check!
End of turn 9
TH3Cap7a1n26: 5 Æmber  (0 keys) UltimoFox700: 6 Æmber  (2 keys)
TURN 9 - TH3Cap7a1n26
Key phase - TH3Cap7a1n26
TH3Cap7a1n26 does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - TH3Cap7a1n26
TH3Cap7a1n26 chooses saurian  as their active house this turn
Main phase - TH3Cap7a1n26
TH3Cap7a1n26 plays Enlist Numeri
TH3Cap7a1n26 uses Encounter Suit to ward Com. Officer Hings
TH3Cap7a1n26 gains an Æmber  due to Enlist Numeri's bonus icon
TH3Cap7a1n26 uses Enlist Numeri to apply a lasting effect to Lieutenant Valmart
TH3Cap7a1n26 exhausts Lieutenant Valmart to remove its stun
TH3Cap7a1n26 uses Lapisaurus to reap with Lapisaurus
TH3Cap7a1n26 plays Scylla
TH3Cap7a1n26 plays Cornicen Octavia
TH3Cap7a1n26 plays Undagnathus
TH3Cap7a1n26 plays Bury Riches
TH3Cap7a1n26 uses Encounter Suit to ward Com. Officer Hings
TH3Cap7a1n26 uses Bury Riches to raise the tide 
TH3Cap7a1n26 uses Operative Espion to use Diplomat Agung
TH3Cap7a1n26 uses Diplomat Agung to reap with Diplomat Agung
TH3Cap7a1n26
sry
 TH3Cap7a1n26 is attempting to switch manual mode on
UltimoFox700
?
 UltimoFox700 allows enabling manual mode
 TH3Cap7a1n26 switches manual mode on
 TH3Cap7a1n26 switches manual mode off
TH3Cap7a1n26
nah too late
UltimoFox700
What was the issue?
TH3Cap7a1n26
i should have used hings
UltimoFox700
Ohhhhhhh
TH3Cap7a1n26 chooses house saurian 
TH3Cap7a1n26 uses Diplomat Agung to make Com. Officer Hings belong to house saurian  in addition to its other houses
UltimoFox700
Drawing 5 cards  could've been big, yeah
TH3Cap7a1n26
i can
TH3Cap7a1n26 uses Com. Officer Hings to reap with Com. Officer Hings
UltimoFox700
Oh wow
TH3Cap7a1n26 uses Com. Officer Hings to draw 4 cards 
TH3Cap7a1n26 draws 4 card  s
UltimoFox700
Fair play, lol
TH3Cap7a1n26 plays City-State Interest
TH3Cap7a1n26 uses Encounter Suit to ward Com. Officer Hings
TH3Cap7a1n26 uses City-State Interest to make each friendly creature capture 1 Æmber 
UltimoFox700
That deck has never done this much before
UltimoFox700
Very well played sir
KarenB
ooooh yeee
KarenB
fuck shit up Cap
Ready phase - TH3Cap7a1n26
TH3Cap7a1n26 readies their cards 
Draw phase - TH3Cap7a1n26
 TH3Cap7a1n26 declares Check!
End of turn 9
TH3Cap7a1n26: 9 Æmber  (0 keys) UltimoFox700: 0 Æmber  (2 keys)
TURN 10 - UltimoFox700
Key phase - UltimoFox700
UltimoFox700 does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - UltimoFox700
TH3Cap7a1n26
hahaha
TH3Cap7a1n26
aint dead yet"!
UltimoFox700 chooses sanctum  as their active house this turn
Main phase - UltimoFox700
TH3Cap7a1n26
sry, brb, gotta sort something
UltimoFox700 uses Lærie of the Lake to make Lærie of the Lake fight Lieutenant Valmart
UltimoFox700 plays Hammer-gram
TH3Cap7a1n26 uses Encounter Suit to ward Com. Officer Hings
UltimoFox700 captures an Æmber  on Sir Bevor due to Hammer-gram's bonus icon
UltimoFox700 uses Hammer-gram to deal 3 damage and stun Com. Officer Gross
UltimoFox700 uses Sir Bevor to reap with Sir Bevor
UltimoFox700 uses Sir Bevor to deal 4 damage to Sir Bevor
UltimoFox700 uses Sir Bevor to play Dr. Verokter
UltimoFox700 plays Dr. Verokter
UltimoFox700 uses Sir Bevor to reap with Sir Bevor
UltimoFox700 uses Sir Bevor to deal 4 damage to Sir Bevor
KarenB
that's.... unfortunate sorta
UltimoFox700 uses Bull-wark to make Bull-wark fight Shield-U-Later
UltimoFox700 uses Bull-wark to deal 2 damage to Shield-U-Later
TH3Cap7a1n26
im here
UltimoFox700
We will see
TH3Cap7a1n26
what happened
UltimoFox700 uses Gatekeeper to make Gatekeeper fight Diplomat Agung
KarenB
verokter off of the reckless
UltimoFox700 changed tide  to High
UltimoFox700 uses Operative Espion to use Dr. Verokter
KarenB
makes the combo pretty much dead
UltimoFox700
Oh wait Scylla
TH3Cap7a1n26
ahhh
UltimoFox700
Hmmmmm
TH3Cap7a1n26
yep....
UltimoFox700
I knew it was going to happen as well, I just thought this was going to work out better
TH3Cap7a1n26
that was my headache
TH3Cap7a1n26
this is disrupted
UltimoFox700 uses Dr. Verokter to make Dr. Verokter fight Undagnathus
TH3Cap7a1n26
disruptive... just come too late
UltimoFox700
What did Verokter take damage from
Ready phase - UltimoFox700
UltimoFox700 readies their cards 
Draw phase - UltimoFox700
UltimoFox700 draws 1 card  to their maximum of 6
UltimoFox700's deck has run out of cards, so they shuffle
UltimoFox700's chains are reduced by 1 to 4
End of turn 10
TH3Cap7a1n26: 8 Æmber  (0 keys) UltimoFox700: 4 Æmber  (2 keys)
TURN 10 - TH3Cap7a1n26
Key phase - TH3Cap7a1n26
TH3Cap7a1n26 forges the yellow key  , paying 6 Æmber 
House phase - TH3Cap7a1n26
TH3Cap7a1n26
yay... i got a key
UltimoFox700
I don't know why verokter has damage on it
TH3Cap7a1n26
looking back up.
TH3Cap7a1n26
im not sure either
KarenB
yeah I'm reading too
KarenB
it fought
UltimoFox700
TCO's log didn't even mention it
KarenB
but yeah
UltimoFox700
But after I attacked Undagnathus, I took 1 damage back
UltimoFox700
From where though?
KarenB
any yeah I don't know
KarenB
you can manual
KarenB
I think it's just wrong
KarenB
copy the log and report on keyteki

**Comment by not2night** [comment]
Happened in one of my games as well. Low tide and Undagnathus involved, every fight it dealt 1 damage 
turn 8 wilki
[Undagnathus fight bug.txt](https://github.com/keyteki/keyteki/files/8128067/Undagnathus.fight.bug.txt)

**Comment by StVelten** [comment]
Can confrim, had the same problem with a mindworm which died.

**Comment by romanogit** [comment]
I saw this happening in multiple games, but unable to reproduce
