### ISSUE TITLE
Archimedes does not work with simultaneous damage

### ISSUE THREAD

**Issue by Jarimy123** [keyteki/keyteki#279]
When a card like Ammonia Clouds is played, dealing 3 damage to all creatures, it is killing off all creatures on the side with Archimedes.  It should deal all damage at once, then check for Destroy: effects, and collapse the battle line in.  As of now, if applicable, it wipes the board.  Example:  I had out Arch, Helper Bot, and TT - opponent played Ammonia, all 3 went to the discard.  TT and Bot should have went to archive.

**Comment by Achocholacek** [comment]
Thanks for the report - I can replicate this locally, so we'll do some digging!

**Comment by romanogit** [comment]
This is fixed by timing refactor.
