### ISSUE TITLE
Chota Hazri it will not trigger its effect if played from the archive by Project Z.Y.X.

### ISSUE THREAD

**Issue by exohsevans** [keyteki/keyteki#2795]
Hi, I did a game recently where I had two keys and 6 amber, I used the Project Z.Y.X. reap effect, going to 7 amber. In the archive I had Chota Hazri, which I play via the Project Z.Y.X. effect to win the game. The effect in the chat has also triggered, but in reality I stay at 7 amber and lose the game. Bug? I lost a game over this. I am attaching a screen of the match.

I had 8 ambers because in the end I also collected with Eyegor, after solving the effect of Chota Hazri, which in the end is not solved.

![2022-01-07](https://user-images.githubusercontent.com/75943384/148592080-0cef4083-1980-4993-962f-4591265f735b.png)

Update: My opponent actually played my turn before "Rhetor Gallim", so this is not a bug. At best, the bug is due to my key counter not increasing to 9, remaining at 6.

**Comment by sdsantos** [comment]
The chat mentions the 9 amber key cost, and by the time your opponent wins, it should be back to 6. Are you sure it wasn't 9 in the bottom bar when it was your turn?

**Comment by SkyJedi** [comment]
During the turn you played Chota your keycost was 9.  You started your turn 5 amber, reaped 3x for a total of 8 amber, played chota lost 1 for a total of 7., which was not enough to forge for 9.

you then readed with eyegor and finished you turn at 8.

![image](https://user-images.githubusercontent.com/2967416/148593819-43072fda-5581-4a9e-9a86-a80ca56ca760.png)
