### ISSUE TITLE
verify an enhancment deck 

### ISSUE THREAD

**Issue by Onex012** [keyteki/keyteki#2801]
I have the deck evil twin but I am not able to play the deck on Crucible Online. I already added the deck and imported my link. But when I want to play it it says I have to verify my deck because of the enhancment. 

Can someone tell me what I can do to solve this problem

**Comment by SkyJedi** [comment]
When enhancements can't be auto assigned it gives you the unverified flag.  You can still use the deck. There is nothing in the code preventing you from starting a game.

Not much we can do about verification unfortunately.
