### ISSUE TITLE
Mimic gel copying scowly caper could not be used as if it belonged to the active house

### ISSUE THREAD

**Issue by mcarulli** [keyteki/keyteki#2805]
![DA75258F-4C36-40B3-8A90-C74AD34D3E7D](https://user-images.githubusercontent.com/40010247/157037124-3f477e67-4f63-46dd-aeb0-45f33be98af8.png)

I had scowly caper on my opponents board, they played mimic gel to copy it and give it to me (house logos). My next turn I called logos (which was one of my decks houses) and could use it. Then the next turn I called shadows and could not use the mimic gel.

**Comment by romanogit** [comment]
I am unable to repruce. Also added a test case:
https://github.com/keyteki/keyteki/pull/2861

**Comment by romanogit** [comment]
One thing I have just noticed and it could be interesting to test is that the original scowly caper is not on the board anymore
