### ISSUE TITLE
Colosseum gets a counter with armageddon cloak

### ISSUE THREAD

**Issue by dmikalova** [keyteki/keyteki#2824]
I had a game where there's a colosseum out lilithal fights a bull-wark with armageddon cloak and then colosseum gets a token from the cloak. I would expect that the replacement effect of armageddon cloak means colosseum does not get a token.

**Comment by dmikalova** [comment]
Rokkushin brings Kyrielle la Contrahecha del Lar to The Crucible
dmikalova brings Arrowsmith Montcarte to The Crucible
dmikalova won the flip and is first player
 dmikalova has connected to the game server
 Rokkushin has connected to the game server
dmikalova
howdy gl hf :)
Rokkushin is shuffling their deck
Rokkushin draws 6 card  s to their maximum of 6
dmikalova is shuffling their deck
dmikalova draws 6 card  s to their maximum of 6
dmikalova draws 1 card 
Rokkushin
:D
Key phase - dmikalova
dmikalova does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses logos  as their active house this turn
Main phase - dmikalova
dmikalova plays Q-Mechs
dmikalova uses Q-Mechs to draw 1 card 
dmikalova draws 1 card 
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
End of turn 1
Rokkushin: 0 Æmber  (0 keys) dmikalova: 0 Æmber  (0 keys)
TURN 1 - Rokkushin
Key phase - Rokkushin
Rokkushin does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Rokkushin
Rokkushin chooses saurian  as their active house this turn
Main phase - Rokkushin
Rokkushin plays Praefectus Ludo
Rokkushin plays Rhetor Gallim
Rokkushin uses Rhetor Gallim to increase dmikalova's key cost by 3 during their next turn
Rokkushin plays The Callipygian Ideal attaching it to Rhetor Gallim
Rokkushin uses The Callipygian Ideal to exalt Rhetor Gallim
Rokkushin plays Imperium
Rokkushin gains an Æmber  due to Imperium's bonus icon
Rokkushin uses Imperium to ward Praefectus Ludo and Rhetor Gallim
Ready phase - Rokkushin
Rokkushin readies their cards 
Draw phase - Rokkushin
Rokkushin draws 5 card  s to their maximum of 6
End of turn 1
Rokkushin: 1 Æmber  (0 keys) dmikalova: 0 Æmber  (0 keys)
TURN 2 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 0 amber. The current cost is 9 Æmber 
House phase - dmikalova
dmikalova chooses saurian  as their active house this turn
Main phase - dmikalova
dmikalova plays Techno-Saurus
dmikalova uses Techno-Saurus to exalt Techno-Saurus
Praefectus Ludo's ward token prevents the damage dealt by Techno-Saurus and is discarded
dmikalova plays Axiom of Grisk
dmikalova uses Axiom of Grisk to ward Techno-Saurus, destroy all creatures without Æmber  and give dmikalova 2 chains
dmikalova uses Q-Mechs to archive Q-Mechs
dmikalova plays Consul Primus
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 1 card  to their maximum of 6
dmikalova's chains are reduced by 1 to 1
End of turn 2
Rokkushin: 1 Æmber  (0 keys) dmikalova: 0 Æmber  (0 keys)
TURN 2 - Rokkushin
Key phase - Rokkushin
Rokkushin does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Rokkushin
Rokkushin chooses dis  as their active house this turn
Main phase - Rokkushin
Rokkushin plays E’e on the Fringes
Rokkushin plays Key to Dis
Ready phase - Rokkushin
Rokkushin readies their cards 
Draw phase - Rokkushin
Rokkushin draws 2 card  s to their maximum of 6
End of turn 2
Rokkushin: 1 Æmber  (0 keys) dmikalova: 0 Æmber  (0 keys)
TURN 3 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses sanctum  as their active house this turn
Main phase - dmikalova
dmikalova plays Burning Glare
dmikalova gains an Æmber  due to Burning Glare's bonus icon
dmikalova chooses option ' Stun an enemy creature '
dmikalova uses Burning Glare to stun Rhetor Gallim
dmikalova plays Lyco-Knight
dmikalova plays Scrivener Favian
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 3 card  s to their maximum of 6
dmikalova's chains are reduced by 1 to 0
End of turn 3
Rokkushin: 1 Æmber  (0 keys) dmikalova: 1 Æmber  (0 keys)
TURN 3 - Rokkushin
Key phase - Rokkushin
Rokkushin does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Rokkushin
Rokkushin chooses dis  as their active house this turn
Main phase - Rokkushin
Rokkushin plays Binding Irons
Rokkushin uses Binding Irons to give dmikalova 3 chains
Rokkushin uses E’e on the Fringes to make E’e on the Fringes fight Techno-Saurus
Techno-Saurus's ward token prevents the damage dealt by E’e on the Fringes and is discarded
Rokkushin uses Key to Dis to sacrifice Key to Dis
Rokkushin uses Rhetor Gallim to remove its ward token
Ready phase - Rokkushin
Rokkushin readies their cards 
Draw phase - Rokkushin
Rokkushin draws 1 card  to their maximum of 6
End of turn 3
Rokkushin: 2 Æmber  (0 keys) dmikalova: 1 Æmber  (0 keys)
TURN 4 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses sanctum  as their active house this turn
Main phase - dmikalova
dmikalova plays Champion Anaphiel
dmikalova plays Charge!
dmikalova gains an Æmber  due to Charge!'s bonus icon
dmikalova uses Charge! to apply a lasting effect
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 2 card  s to their maximum of 6
dmikalova's chains are reduced by 1 to 2
End of turn 4
Rokkushin: 2 Æmber  (0 keys) dmikalova: 2 Æmber  (0 keys)
TURN 4 - Rokkushin
Key phase - Rokkushin
Rokkushin does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - Rokkushin
Rokkushin chooses untamed  as their active house this turn
Main phase - Rokkushin
Rokkushin plays Unsuspecting Prey
Rokkushin uses Unsuspecting Prey to deal 2 damage to Champion Anaphiel
Rokkushin plays Grasping Vines
Rokkushin gains an Æmber  due to Grasping Vines's bonus icon
Rokkushin uses Grasping Vines
Rokkushin plays Cauldron Boil
Rokkushin gains an Æmber  due to Cauldron Boil's bonus icon
Rokkushin uses Cauldron Boil to deal damage to creatures equal to their existing damage
Ready phase - Rokkushin
Rokkushin readies their cards 
Draw phase - Rokkushin
Rokkushin draws 3 card  s to their maximum of 6
End of turn 4
Rokkushin: 4 Æmber  (0 keys) dmikalova: 2 Æmber  (0 keys)
TURN 5 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses logos  as their active house this turn
dmikalova moves all the cards  in their archives to their hand
Main phase - dmikalova
dmikalova plays Standardized Testing
dmikalova captures an Æmber  on Champion Anaphiel due to Standardized Testing's bonus icon
dmikalova deals 1 damage to Rhetor Gallim due to Standardized Testing's bonus icon
dmikalova uses Standardized Testing to destroy Rhetor Gallim and Champion Anaphiel
dmikalova plays Q-Mechs
dmikalova uses Q-Mechs to draw 1 card 
dmikalova draws 1 card 
dmikalova plays Bot Bookton
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 1 card  to their maximum of 6
dmikalova's chains are reduced by 1 to 1
End of turn 5
Rokkushin: 4 Æmber  (0 keys) dmikalova: 3 Æmber  (0 keys)
TURN 5 - Rokkushin
Key phase - Rokkushin
Rokkushin does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - Rokkushin
Rokkushin chooses saurian  as their active house this turn
Main phase - Rokkushin
Rokkushin plays Thero Centurion
Rokkushin uses Thero Centurion to capture 1 Æmber  from their opponent , placing it on Thero Centurion
Rokkushin plays The Golden Spiral
Rokkushin plays Imperial Scutum attaching it to Thero Centurion
Rokkushin gains an Æmber  due to Imperial Scutum's bonus icon
Ready phase - Rokkushin
Rokkushin readies their cards 
Draw phase - Rokkushin
Rokkushin draws 3 card  s to their maximum of 6
End of turn 5
Rokkushin: 5 Æmber  (0 keys) dmikalova: 2 Æmber  (0 keys)
TURN 6 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses logos  as their active house this turn
Main phase - dmikalova
dmikalova plays Dimension Door
dmikalova captures an Æmber  on Q-Mechs due to Dimension Door's bonus icon
dmikalova uses Dimension Door to steal Æmber  instead of gaining it while reaping for the remainder of the turn
dmikalova uses Bot Bookton to reap with Bot Bookton
dmikalova steals 1 Æmber  instead of gaining it due to Dimension Door's effect
dmikalova uses Bot Bookton to play Ardent Hero
dmikalova plays Ardent Hero
dmikalova uses Q-Mechs to reap with Q-Mechs
dmikalova steals 1 Æmber  instead of gaining it due to Dimension Door's effect
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 1 card  to their maximum of 6
dmikalova's chains are reduced by 1 to 0
End of turn 6
Rokkushin: 2 Æmber  (0 keys) dmikalova: 4 Æmber  (0 keys)
TURN 6 - Rokkushin
Key phase - Rokkushin
Rokkushin does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - Rokkushin
Rokkushin chooses saurian  as their active house this turn
Main phase - Rokkushin
Rokkushin plays The Colosseum
Rokkushin plays Senator Shrix
Rokkushin uses Senator Shrix to exalt Senator Shrix
Rokkushin uses Thero Centurion to make Thero Centurion fight Q-Mechs
dmikalova uses Q-Mechs to archive Q-Mechs
Rokkushin uses The Colosseum to place a glory counter on itself due to Q-Mechs being destroyed
Rokkushin uses Thero Centurion to capture 1 Æmber  from their opponent , placing it on Thero Centurion
Rokkushin plays Axiom of Grisk
Rokkushin uses Axiom of Grisk to ward Senator Shrix, destroy all creatures without Æmber  and give Rokkushin 2 chains
Rokkushin uses The Golden Spiral to exalt, ready and use Senator Shrix
Rokkushin uses Senator Shrix to reap with Senator Shrix
Rokkushin uses Senator Shrix to exalt Senator Shrix
Ready phase - Rokkushin
Rokkushin readies their cards 
Draw phase - Rokkushin
Rokkushin draws 2 card  s to their maximum of 6
Rokkushin's chains are reduced by 1 to 1
 Rokkushin declares Check!
End of turn 6
Rokkushin: 4 Æmber  (0 keys) dmikalova: 3 Æmber  (0 keys)
TURN 7 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses sanctum  as their active house this turn
Main phase - dmikalova
dmikalova plays The Spirit’s Way
dmikalova uses The Spirit’s Way to destroy Thero Centurion and Senator Shrix
Rokkushin uses Senator Shrix to remove its ward token
Rokkushin uses Thero Centurion to remove all Æmber  from Thero Centurion
dmikalova plays Lyco-Knight
dmikalova plays Smite
dmikalova uses Smite to ready and fight with Lyco-Knight
dmikalova uses Lyco-Knight to make Lyco-Knight fight Senator Shrix
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 4 card  s to their maximum of 6
 dmikalova declares Check!
End of turn 7
Rokkushin: 4 Æmber  (0 keys) dmikalova: 6 Æmber  (0 keys)
TURN 7 - Rokkushin
Key phase - Rokkushin
Rokkushin does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - Rokkushin
Rokkushin chooses dis  as their active house this turn
Main phase - Rokkushin
Rokkushin plays Snaglet
Rokkushin plays Lilithal
Ready phase - Rokkushin
Rokkushin readies their cards 
Draw phase - Rokkushin
Rokkushin draws 2 card  s to their maximum of 6
Rokkushin's chains are reduced by 1 to 0
End of turn 7
Rokkushin: 4 Æmber  (0 keys) dmikalova: 6 Æmber  (0 keys)
TURN 8 - dmikalova
Key phase - dmikalova
dmikalova forges the yellow key  , paying 6 Æmber 
House phase - dmikalova
dmikalova chooses sanctum  as their active house this turn
Main phase - dmikalova
dmikalova plays Bull-wark
dmikalova captures an Æmber  on Bull-wark due to Bull-wark's bonus icon
dmikalova plays Armageddon Cloak attaching it to Bull-wark
dmikalova gains an Æmber  due to Armageddon Cloak's bonus icon
dmikalova uses Lyco-Knight to make Lyco-Knight fight Snaglet
dmikalova uses Lyco-Knight to deal 2 damage to Snaglet
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 2 card  s to their maximum of 6
End of turn 8
Rokkushin: 3 Æmber  (0 keys) dmikalova: 1 Æmber  (1 key)
TURN 8 - Rokkushin
Key phase - Rokkushin
Rokkushin does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - Rokkushin
Rokkushin chooses dis  as their active house this turn
Main phase - Rokkushin
Rokkushin plays Harbinger of Doom
Rokkushin uses Lilithal to reap with Lilithal
Rokkushin uses Lilithal to capture 1 Æmber  from their opponent , placing it on Lilithal
Ready phase - Rokkushin
Rokkushin readies their cards 
Draw phase - Rokkushin
Rokkushin draws 2 card  s to their maximum of 6
End of turn 8
Rokkushin: 4 Æmber  (0 keys) dmikalova: 0 Æmber  (1 key)
TURN 9 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses saurian  as their active house this turn
Main phase - dmikalova
dmikalova plays Monument to Ludo
dmikalova plays Beware the Ides
dmikalova gains an Æmber  due to Beware the Ides's bonus icon
dmikalova plays Curse of Vanity
dmikalova gains an Æmber  due to Curse of Vanity's bonus icon
dmikalova uses Curse of Vanity to exalt Bull-wark
dmikalova plays Citizen Shrix
dmikalova uses Citizen Shrix to exalt Citizen Shrix and steal 1 Æmber 
dmikalova plays Praefectus Ludo
dmikalova plays Galeatops
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 6 card  s to their maximum of 6
End of turn 9
Rokkushin: 3 Æmber  (0 keys) dmikalova: 3 Æmber  (1 key)
TURN 9 - Rokkushin
Key phase - Rokkushin
Rokkushin does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - Rokkushin
Rokkushin chooses untamed  as their active house this turn
Main phase - Rokkushin
Rokkushin plays Tantadlin
Rokkushin plays Unsuspecting Prey
Rokkushin uses Unsuspecting Prey to deal 2 damage to Bull-wark, Citizen Shrix, and Praefectus Ludo
Rokkushin plays Grasping Vines
Rokkushin gains an Æmber  due to Grasping Vines's bonus icon
Rokkushin uses Grasping Vines
Rokkushin plays Po’s Pixies
Rokkushin plays Musthic Murmook
Rokkushin uses Musthic Murmook to deal 4 damage to Praefectus Ludo
Ready phase - Rokkushin
Rokkushin readies their cards 
Draw phase - Rokkushin
Rokkushin draws 5 card  s to their maximum of 6
End of turn 9
Rokkushin: 4 Æmber  (0 keys) dmikalova: 3 Æmber  (1 key)
TURN 10 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 3 amber. The current cost is 7 Æmber 
House phase - dmikalova
dmikalova chooses logos  as their active house this turn
dmikalova moves all the cards  in their archives to their hand
Main phase - dmikalova
dmikalova plays Q-Mechs
dmikalova uses Q-Mechs to draw 1 card 
dmikalova draws 1 card 
dmikalova plays Q-Mechs
dmikalova deals 1 damage to Po’s Pixies due to Q-Mechs's bonus icon
dmikalova uses Q-Mechs to draw 1 card 
dmikalova draws 1 card 
dmikalova plays Diametric Charge
dmikalova gains an Æmber  due to Diametric Charge's bonus icon
dmikalova uses Diametric Charge to deal 1 damage to Lilithal and 2 to their neighbors
dmikalova plays Mutagenic Serum
dmikalova gains an Æmber  due to Mutagenic Serum's bonus icon
dmikalova plays Opposition Research
dmikalova deals 1 damage to Musthic Murmook due to Opposition Research's bonus icon
 dmikalova uses Opposition Research to stop Rokkushin from reaping next turn
dmikalova plays Auto-Encoder
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 3 card  s to their maximum of 6
End of turn 10
Rokkushin: 4 Æmber  (0 keys) dmikalova: 5 Æmber  (1 key)
TURN 10 - Rokkushin
Key phase - Rokkushin
Rokkushin does not forge a key. They have 4 amber. The current cost is 7 Æmber 
House phase - Rokkushin
Rokkushin chooses dis  as their active house this turn
Main phase - Rokkushin
Rokkushin uses Lilithal to make Lilithal fight Bull-wark
dmikalova uses Bull-wark to deal 2 damage to Lilithal
dmikalova uses Bull-wark to heal all damage from Bull-wark and destroy Armageddon Cloak instead
Rokkushin uses The Colosseum to place a glory counter on itself due to Armageddon Cloak being destroyed
dmikalova
hmm colosseum armageddon cloaks seems off
Rokkushin uses Harbinger of Doom to make Harbinger of Doom fight Lyco-Knight
Rokkushin uses Harbinger of Doom to destroy Musthic Murmook, Tantadlin, Q-Mechs, Galeatops, Citizen Shrix, Bull-wark, Lyco-Knight, and Q-Mechs
dmikalova uses Q-Mechs to archive Q-Mechs
dmikalova uses Q-Mechs to archive Q-Mechs
Rokkushin plays Festering Touch
Rokkushin gains an Æmber  due to Festering Touch's bonus icon
Rokkushin uses Festering Touch
Rokkushin plays Lilithal
Ready phase - Rokkushin
Rokkushin readies their cards 
Draw phase - Rokkushin
Rokkushin draws 2 card  s to their maximum of 6
 Rokkushin declares Check!
End of turn 10
Rokkushin: 8 Æmber  (0 keys) dmikalova: 7 Æmber  (1 key)
TURN 11 - dmikalova
Key phase - dmikalova
dmikalova forges the blue key  , paying 6 Æmber 
House phase - dmikalova
dmikalova chooses logos  as their active house this turn
dmikalova moves all the cards  in their archives to their hand
Main phase - dmikalova
dmikalova plays Zenzizenzizenzic
dmikalova plays Q-Mechs
dmikalova deals 1 damage to Q-Mechs due to Q-Mechs's bonus icon
dmikalova uses Q-Mechs to archive Q-Mechs
dmikalova plays Q-Mechs
dmikalova uses Q-Mechs to draw 1 card 
dmikalova draws 1 card 
dmikalova plays Q-Mechs
dmikalova uses Q-Mechs to draw 1 card 
dmikalova draws 1 card 
dmikalova's deck has run out of cards, so they shuffle
dmikalova plays Eclectic Inquiry
dmikalova gains an Æmber  due to Eclectic Inquiry's bonus icon
dmikalova uses Eclectic Inquiry to archive the top two cards  of their deck
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 3 card  s to their maximum of 8
End of turn 11
Rokkushin: 8 Æmber  (0 keys) dmikalova: 2 Æmber  (2 keys)
TURN 11 - Rokkushin
Key phase - Rokkushin
Rokkushin forges the red key  , paying 6 Æmber 
House phase - Rokkushin
Rokkushin chooses dis  as their active house this turn
Main phase - Rokkushin
Rokkushin uses Lilithal to make Lilithal fight Zenzizenzizenzic
Rokkushin uses Lilithal to capture 1 Æmber  from their opponent , placing it on Lilithal
Rokkushin plays The Evil Eye
Rokkushin gains an Æmber  due to The Evil Eye's bonus icon
Rokkushin uses The Evil Eye to increase key cost by 3 during dmikalova's next turn
Rokkushin plays Draining Touch
Rokkushin uses Draining Touch to destroy Zenzizenzizenzic
Ready phase - Rokkushin
Rokkushin readies their cards 
Draw phase - Rokkushin
Rokkushin draws 2 card  s to their maximum of 6
End of turn 11
Rokkushin: 3 Æmber  (1 key) dmikalova: 1 Æmber  (2 keys)
TURN 12 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 1 amber. The current cost is 9 Æmber 
House phase - dmikalova
dmikalova chooses saurian  as their active house this turn
Main phase - dmikalova
dmikalova plays Faust the Great
dmikalova uses Faust the Great to exalt Faust the Great
dmikalova plays Curia Saurus
dmikalova plays Chant of Hubris
dmikalova gains an Æmber  due to Chant of Hubris's bonus icon
dmikalova uses Chant of Hubris to remove 1 Æmber  from Faust the Great
dmikalova uses Chant of Hubris to place 1 Æmber  on Lilithal
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 1 card  to their maximum of 6
End of turn 12
Rokkushin: 3 Æmber  (1 key) dmikalova: 2 Æmber  (2 keys)
TURN 12 - Rokkushin
Key phase - Rokkushin
Rokkushin does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - Rokkushin
Rokkushin chooses untamed  as their active house this turn
Main phase - Rokkushin
Rokkushin plays Unsuspecting Prey
Rokkushin uses Unsuspecting Prey to deal 2 damage to Q-Mechs, Q-Mechs, and Faust the Great
dmikalova uses Q-Mechs to archive Q-Mechs
dmikalova uses Q-Mechs to archive Q-Mechs
Rokkushin plays Song of the Wild
Rokkushin uses Song of the Wild to give each friendly creature 'Reap: Gain 1 amber' for the remainder of the turn
Rokkushin plays Fangtooth Cavern
Rokkushin gains an Æmber  due to Fangtooth Cavern's bonus icon
Ready phase - Rokkushin
Rokkushin readies their cards 
Draw phase - Rokkushin
Rokkushin draws 3 card  s to their maximum of 6
Rokkushin's deck has run out of cards, so they shuffle
Rokkushin uses Fangtooth Cavern to destroy Faust the Great
End of turn 12
Rokkushin: 4 Æmber  (1 key) dmikalova: 2 Æmber  (2 keys)
TURN 13 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses sanctum  as their active house this turn
dmikalova moves all the cards  in their archives to their hand
Main phase - dmikalova
dmikalova plays The Spirit’s Way
dmikalova uses The Spirit’s Way to destroy Lilithal
dmikalova plays Burning Glare
dmikalova gains an Æmber  due to Burning Glare's bonus icon
dmikalova plays Burning Glare
dmikalova gains an Æmber  due to Burning Glare's bonus icon
dmikalova plays Bull-wark
dmikalova captures an Æmber  on Bull-wark due to Bull-wark's bonus icon
dmikalova plays Lyco-Knight
dmikalova plays Armageddon Cloak attaching it to Bull-wark
dmikalova gains an Æmber  due to Armageddon Cloak's bonus icon
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 1 card  to their maximum of 6
 dmikalova declares Check!
End of turn 13
Rokkushin: 3 Æmber  (1 key) dmikalova: 7 Æmber  (2 keys)
TURN 13 - Rokkushin
Key phase - Rokkushin
Rokkushin does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - Rokkushin
Rokkushin chooses dis  as their active house this turn
Main phase - Rokkushin
Rokkushin plays Three Fates
Rokkushin gains an Æmber  due to Three Fates's bonus icon
Rokkushin uses Three Fates to destroy Lyco-Knight and Bull-wark
dmikalova uses Bull-wark to heal all damage from Bull-wark and destroy Armageddon Cloak instead
Rokkushin plays Snag
Ready phase - Rokkushin
Rokkushin readies their cards 
Draw phase - Rokkushin
Rokkushin draws 2 card  s to their maximum of 6
Rokkushin uses Fangtooth Cavern to destroy Bull-wark
dmikalova uses Bull-wark to place 1 Æmber  on Snag
End of turn 13
Rokkushin: 4 Æmber  (1 key) dmikalova: 7 Æmber  (2 keys)
TURN 14 - dmikalova
Key phase - dmikalova
dmikalova forges the red key  , paying 6 Æmber 
 dmikalova has won the game
 Rokkushin has disconnected. The game will wait up to 30 seconds for them to reconnect
dmikalova
gg

**Comment by romanogit** [comment]
Also look at https://github.com/keyteki/keyteki/issues/2830
