### ISSUE TITLE
Groundbreaking discovery does not destroy upgrades on warded creature 

### ISSUE THREAD

**Issue by mcarulli** [keyteki/keyteki#2826]
If a creature has a ward when groundbreaking discovery is triggered (such as via encounter suit), then the ward is removed but upgrades remain. Groundbreaking discovery says to destroy all cards in play, so I believe the upgrades should be removed even if the creature is not?

No log or screen shots but should be easy to verify with this deck. It happened when zenzi had encounter suit, light of the archons, aember vac on it.
https://decksofkeyforge.com/decks/4f269c70-55b7-44a2-a148-3acb2172ca74

**Comment by jeremylarner** [comment]
Looking at the code, this seems like a legitimate issue.  Groundbreaking discovery destroys `context.game.cardsInPlay`, when it should destroy those cards, plus all upgrades attached to them. Changing the target line in the destroy action to:
`context.game.cardsInPlay.reduce((array, card) => array.concat(card.upgrades)).concat(context.game.cardsInPlay)`
should fix it, but I'm not confident in my memory of array methods to put a PR up without testing it.

If someone wants to write a test and then try that though, I think it would work
