### ISSUE TITLE
I cannot find this deck in dok

### ISSUE THREAD

**Issue by bsi0409** [keyteki/keyteki#2831]
i cannot find this deck in dok

Is it possible?

![image](https://user-images.githubusercontent.com/109089283/178287351-466e1b3c-8250-4d4b-ad8f-cf6314efb16b.png)

![image](https://user-images.githubusercontent.com/109089283/178287470-6fadf255-eb89-4911-985e-f5ac736ea168.png)

**Comment by SkyJedi** [comment]
This is one of the "Impossible decks that FFG released back in 2020.

https://twitter.com/ffgames/status/1289578454048862208

![image](https://user-images.githubusercontent.com/2967416/178288457-8da46ba5-79f9-4e7d-bb4f-ad5ca88368a6.png)
