### ISSUE TITLE
Timequake didn't shuffle an Upgrade.

### ISSUE THREAD

**Issue by avandever** [keyteki/keyteki#2840]
Sorry for not capturing state better, I wasn't 100% sure it was a bug until later.
I had a Mini Groupthink Tank and Hapsis on the board, my opponent had nothing on board. My opponent played Stunner, attaching it to my Tank, then Timequake. The Stunner was not shuffled into my opponent's deck, and they did not draw a card. At the start of the game we had gone into manual mode to add chains to effect auction format. I had 8, my opponent had 6. We had ended manual mode before hitting start game, though.
My deck: https://decksofkeyforge.com/decks/5e6f5860-b0c3-47de-9556-5c5e3e7698d4
My opponent's deck: https://decksofkeyforge.com/decks/2f35119f-ec1d-43b8-975a-0cbe3519b282

**Comment by avandever** [comment]
I don’t believe so.

**Comment by romanogit** [comment]
So the creature and the upgrade were kept in play? I mean, if the creature was shuffled, the upgrade had to go somewhere.

**Comment by avandever** [comment]
My opponent plated tq. The creature was mine. The upgrade (on the creature)
was his.

**Comment by romanogit** [comment]
oh, that's very interesting scenario, indeed...
