### ISSUE TITLE
Mimicry Issues

### ISSUE THREAD

**Issue by Achocholacek** [keyteki/keyteki#285]
One issue for Mimicry to handle all the outstanding things - based on testing it appears that the following is the case:

1) Mimicry ignores Alpha/Omega.
2) Mimicry cannot handle Play effects that are anything beyond a simple gameaction with no manual targeting.

(condensing #178 #273 #275 #277 )

**Comment by romanogit** [comment]
What about #107 ?

**Comment by JTLSound** [comment]
A week ago maybe, Mimicry would allow targeting of Alpha cards, but it no longer does so.

**Comment by Tilbo** [comment]
Mimicry still not working 100%, I'm sure you're already dealing with it but I thought I'd just chime in on this.
![MIMICRYERROR2](https://user-images.githubusercontent.com/53436024/66653806-bcb3dc00-ec30-11e9-83f1-b979c7eea527.jpg)

**Comment by romanogit** [comment]
A lot of Mimicry issues are closed, including all the ones referenced in this issue.
