### ISSUE TITLE
Severe bug with "Key Hammer"

### ISSUE THREAD

**Issue by paulr79** [keyteki/keyteki#286]
I was busy losing my normal amount of games as I learn when I went up against another player. The game started with them winning the toss and playing "Strange Gizmo" before it was my turn. I played "Key to Dis" as a starter and then "Key Hammer" to gain 1 Æmber. A whole lot of text spammed up on the right as usual but then I saw the game board was clear, the other player had a key and their artifact had wiped mine out.

At first I thought they were cheating or glitching and sadly accused them of glitching. It was a surprise to me and no doubt them too. I even forgot I played "Key Hammer" and thought they had done something to make it happen. Instead it just looks to be an overlooked condition. I owe an apology to the player if / when I see them again. I'm attaching screenshots showing how it was after they left and they also show the full game text. I'm attaching the full game text in a text file too.
![image001](https://user-images.githubusercontent.com/47229054/62585186-77c99d00-b8af-11e9-82ed-e13ba4554007.jpg)
![image002](https://user-images.githubusercontent.com/47229054/62585187-77c99d00-b8af-11e9-933b-5de350d86fb7.jpg)
![image003](https://user-images.githubusercontent.com/47229054/62585188-78623380-b8af-11e9-9113-da57a8a7c735.jpg)
![image004](https://user-images.githubusercontent.com/47229054/62585189-78623380-b8af-11e9-8b58-26c6effc3fff.jpg)
![image005](https://user-images.githubusercontent.com/47229054/62585190-78623380-b8af-11e9-8a8b-0fe628798b53.jpg)
[glitch.txt](https://github.com/keyteki/keyteki/files/3474630/glitch.txt)

**Comment by paulr79** [comment]
Just commenting to add that I managed to get a very similar situation with another player and used Shadowplay to grab a short video. If that would be helpful let me know but I think what I said is all you'll need.

**Comment by saluk** [comment]
@paulr79 Keyhammer always gives 6 aember to the opponent. That's the rule. You don't want to ever play it unless the opponent has just forged a key.

**Comment by paulr79** [comment]
@saluk well that's not embarrassing at all. I'll just quietly make my way to the exit.

**Comment by saluk** [comment]
@paulr79 I'll quietly wave goodbye :) Definitely keep reporting if you run into other issues, the system isn't perfect (and the rules themselves are pretty far from perfect).
