### ISSUE TITLE
Ixxyxli Fixfinger

### ISSUE THREAD

**Issue by qanar** [keyteki/keyteki#287]
Fixfinger doesn't seem to give bonus to Zorg, Dominator and Collector Worm in this image. 
![Capture](https://user-images.githubusercontent.com/6439567/62604345-272a6200-b8f8-11e9-9d18-6f26938a0870.PNG) Mindwarper for example does has the bonus shield. 

https://keyforge-compendium.com/sets/2-aoa/cards/164-ixxyxli-fixfinger

**Comment by hydrophilic-attack** [comment]
That is because he only gives armor to creatures with the Martian trait. Dominator is a robot, while collector worm and Zorg are beasts. But they do not have the Martian trait like e.g. mindwarper has. As such they don't benefit from his armor bonus

**Comment by qanar** [comment]
Wauw... I always read that card as 'To creatures belonging to Mars house'.
