### ISSUE TITLE
Alliance Deck Maverick Issue

### ISSUE THREAD

**Issue by awmountain52** [keyteki/keyteki#2874]
Hi,
First of all thank you so much for getting Alliance decks up and running so quickly!

My opponent began an Alliance match with 37 cards instead of 36. He believes it occurred for two reasons:

1. He chose a house pod from a deck with a maverick in it (daughter in Star Alliance), but it wasn't the pod with the maverick.
2. The new deck had a logos house pod (the original house daughter is typically in).

I wanted to report this in case it impacts others going forward.

Thank you!

**Comment by cryogen** [comment]
Thanks, fixed in 85c347b1a914b9bac7f85cf07e0142e44b60bda3
