### ISSUE TITLE
Po´s Pixies vs Indermensional Graft

### ISSUE THREAD

**Issue by ejlertson** [keyteki/keyteki#288]
I just played a game where the opponent did not lose his remaining Æmber after Forging.

Po´s+ Pixies protect against Steal and Capture, but the effect from Interdimensional Graft is neither and ths the player should still se his remaining Æmber when it is being granted to me

**Comment by Achocholacek** [comment]
Good catch, thanks for the report!

**Comment by ejlertson** [comment]
My pleasure :)
Thank your for your work and dedication :D

Any news on a Patreon or paypal to help support the page?

**Comment by Achocholacek** [comment]
That's a @cryogen question so I'll leave it to him.
