### ISSUE TITLE
Might makes right didn't forge key - no special circumstances involved

### ISSUE THREAD

**Issue by MorgothNL** [keyteki/keyteki#290]
Hi,

I played Might Makes Right, and simply sacrificed exactly 25 power worth of creatures, and it didn't forge a key.
I sacrificed Lollop (11), Flaxia (4), Witch of the Eye (3), Old Yurk (5) and Tezmal (2) = 25 power

Ignore the amber and key count in the screenshot, we already gave me a key manually by the time I made the screenshot. I was on 0 keys after Might makes right. 

<img width="1440" alt="Screenshot 2019-08-07 at 13 49 12" src="https://user-images.githubusercontent.com/53401217/62621578-80a48800-b91c-11e9-96be-d961038c41e7.png">

**Comment by MorgothNL** [comment]
Still the same issue 1 minute ago (mentioning it because the status has an open 'fixed')
Again 25 power sacrificed:
<img width="288" alt="Screenshot 2019-08-07 at 17 26 11" src="https://user-images.githubusercontent.com/53401217/62635780-988a0500-b938-11e9-9cfe-56e4db29df4d.png">

**Comment by cryogen** [comment]
Fixed just means the fix has been submitted, it does not mean it’s live on the site

**Comment by MorgothNL** [comment]
Roger that, thanks for the clarification and sorry about the extra mention. Keep up the good work

**Comment by paulr79** [comment]
Any information on when this will go live on the site? I lost a game I probably would've won because of this same issue and I've had it a few times now. If I'd known it was a problem I wouldn't be using that deck either.

**Comment by Achocholacek** [comment]
@paulr79  Should be relatively soon.

In the meantime, use /forge (in the chat) to forge a key. (Note: this does NOT decrease your aember - you still need to do that manually).
