### ISSUE TITLE
WoE - Brobnar house - Specific issues created for pending cards

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#2901]
This list is still based on Spoilers, so, implement with care:
- [x] (001) **Ancient Battleground**: Each friendly creature cannot reap and gains, "`&#039;&#039;After Fight:&#039;&#039;&#039; Gain 1[[File:Enhance_aember.png|18px|frameless|class=aemberImg|link=|alt=Aember icon]]."
- [x] #3042
- [x] (008) **Frost Giant**: Frost Giant does not ready during your "ready cards" step.
- [x] #3043
your hand. Shuffle your deck. Gain chains equal to the number of cards put into your hand this way.
- [x] (011) **Harmal Atoon**: Each other friendly Brobnar creature gains, "Destroyed:Return this creature to its owner`s hand."
- [x] (013) **Kretchee**: Each time a player exalts a creature or a creature captures Aember, put 1 Aember on that creature from the common supply.     
- [x] #3044
- [x] #3045
- [x] #3046
- [x] (023) **Broken Axe Outpost**: Action: Put a friendly creature on the bottom of its owner`s deck. If you do, deal 6 D to an enemy creature.        
- [x] (024) **Crim Torchtooth**: Splash-attack 4. (When this creature attacks, also deal 4 Damage to each of the attacked creature`s neighbors.) After Fight: Enrage each of Crim Torchtooth&#039;s neighbors.
- [x] #3047
- [x] (028) **Ged Hammer**: Destroyed: Ready and enrage each other friendly Brobnar creature.
- [x] #3048
- [x] (035) **Vow of Blood**: Enhance Damage DamagePlay: Deal 2 Damage to each damaged enemy creature.
- [x] (036) **Vulka**: Each friendly Brobnar creature gains splash-attack 1.
- [x] (038) **Brikk Nastee**: After another friendly Brobnar creature fights, gain 1 Aember.
- [x] (040) **Crogg The Clumsy**: Splash-attack 2. (When this creature attacks, also deal 2 Damage to each of the attacked creature`s neighbors.)       
- [x] (042) **Fresh Marks**: Play: Destroy a friendly creature. If you do, exalt 3 enemy creatures.
- [x] #3049
- [x] (044) **Might Club**: Action: Ready and enrage a creature.
- [x] (045) **Pelf**: Skirmish. (When you use this creature to fight, it is dealt no damage in return.) After Fight: Your opponent loses 1 Aember.      
- [x] #3050
- [x] (048) **Ragnarok Prep**: Play: Make a token creature. Then, if you control more creatures than your opponent, your opponent loses 2 Aember.       
- [x] (049) **Rant and Rive**: Play: If your opponent has 8 Aember or more, they lose half their Aember (rounding down the loss).
- [x] (050) **Rowdy Skald**: Enhance Aember Damage Damage
- [x] (051) **Shock Herder**: Deploy. (This creature can enter play anywhere in your battleline.) Play: Ready and fight with a neighboring creature.    
- [x] #3051
- [x] (053) **Berserker**: Berserker enters play ready and enraged. Fight: Destroy Berserker.
- [x] (054) **Warrior**: Warrior cannot reap unless there are no enemy creatures in play.
- [x] (055) **Skirmisher**: Skirmish. (When you use this creature to fight, it is dealt no damage in return.)
- [x] (056) **Grumpus**: Splash-attack 1. (When this creature attacks, also deal 1 Damage to each of the attacked creature`s neighbors.)
House brobnar - 32 cards

**Comment by strib** [comment]
Pelf can be checked off above.
