### ISSUE TITLE
WoE - Ekwidon house - Specific issues created for pending cards

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#2902]
This list is still based on Spoilers, so, implement with care:
- [x] (057) **Æmbitrage**: Your keys cost +1 Aember. During your "draw cards" step, refill your hand to 1 additional card.
- [x] (058) **Antiquities Dealer**: Action: Gain 2 Aember if you control at least one artifact.
- [x] (059) **Avid Collecting**: Play: Return a friendly token creature to your hand.
- [x] (060) **Conductor Jărroyă**: After Reap: Ready each friendly Buggy artifact.
- [x] (061) **Corner the Market**: Play: During your opponent`s next turn, they cannot play cards, and each time they discard a card from their hand, they may archive that card.
- [x] (062) **Cursed Relic**: Enhance Aember Aember Aember Aember Aember Aember. You cannot play Cursed Relic or choose to discard it from your hand.   
- [x] (063) **Envoy of Ekwirrĕ**: Reap: Swap Envoy of Ekwirrĕ with one of its neighbors. Also swap all Aember, damage, counters, and upgrades on those creatures.
- [x] (064) **Flea Market**: Action: Look at a random card in your opponent`s hand. You may give your opponent 1 Aember. If you do, play that card as if it were yours.
- [x] (065) **Freelancer**: At the start of each turn, the active player takes control of this creature. This creature may be used as if it belonged to 
the active house.
- [x] (066) **Insurance Policy**: Play: Lose 1 Aember. This creature gains, "Destroyed: If it is not your turn, gain 4 Aember."
- [x] (067) **Molluscaller**: Reap: For the remainder of the turn, each friendly Strange Shell gets +3 power and loses all abilities.
- [x] #3130
- [x] (069) **Talent Scout**: Talent Hunter can be used as if it belonged to the active house. Play: Look at your opponent`s hand and play a creature as if it were yours. Your opponent gains control of Talent Hunter.
- [x] (070) **The Æmber Road**: Omni: Put 1 trade counter on The Æmber Road, then gain 1 Aember for each trade counter on it. Give control of The Æmber 
Road to your opponent.
- [x] (071) **Token of Appreciation**: Play: Make a token creature. Forge a key at +7 Aember current cost, reduced by 1 Aember for each friendly token creature.
- [x] (072) **Tourist Trap**: Play: Make a token creature. Action: Choose a friendly token creature and an enemy creature. If you do, swap control of those creatures.
- [x] (073) **Transitory Philosopher**: Action: Steal 1 Aember for each enemy artifact.
- [x] (074) **Exchange Program**: Play: Choose a friendly flank creature and an enemy flank creature. If you do, swap control of those creatures.       
- [x] (075) **Exo-shell System**: Play: Make a token creature. Each friendly token creature gains elusive.
- [x] (076) **Gèzdrutyü the Arcane**: Action: Steal 2 Aember. Flip Gèzdrutyò the Arcane facedown (it becomes a token creature).
- [x] (077) **Gezrăhi Blacksmith**: Elusive. At the start of each player`s turn, that player chooses to either make a token creature od draw a card.    
- [x] (078) **Ikwikĭ Outpost**: `&#039;Action:&#039;&#039;&#039; Put a friendly creature on the bottom of its owner&#039;s deck. If you do, draw 3 cards.
- [x] (079) **Market Crash**: Play: Destroy each non-token creature. Gain 2 chains.
- [x] (080) **Niffle Paw**: This creature gains, "Reap: Destroy this creature and attach Niffle Paw to another creature.
- [x] (081) **Outnegotiate**: Play: Choose a card in your discard pile. Steal Aember equal to the number of Aember bonus icons on it and put that card on the bottom of its owner`s deck.
- [x] (082) **Pull Up Stakes**: Play: Shuffle 2 friendly creatures into their owners` decks. Return 4 enemy creatures to their owners&#039; hands.      
- [x] (083) **Puzzling Trinket**: Enhance Aember Aember. When you resolve an Aember bonus icon, you may choose to resole it as a Capture, Damage, or Draw icon instead.
- [x] (084) **Sandhopper**: Action: Return a friendly creature to its owner`s hand. If you do, you may play a non-Ekwidon creature from your hand.      
- [x] (085) **Scrapscrounger**: Reap: Swap an artifact in your discard pile with a card in your hand.
- [x] (086) **Shĭzyokŭ Swopper**: After Fight: Swap control of this creature and the creature it fights. (Both creatures must survive the fight.)       
- [x] (087) **Trade Secrets**: Play: Discard any number of Ekwidon cards from your hand. Steal 1 Aember for each card discarded this way.
- [x] (088) **Tya-Arhiĭ Esquire**: Each friendly non-token creature gains, "Destroyed: Make a token creature.”
- [x] #3129
- [x] (090) **Auction Off**: Play: Purge an artifact. Its controller gains 1 Aember.
- [x] (091) **Belligerent Guard**: Belligerent Guard enters play ready. Play: Your opponent draws a card.
- [x] (092) **Closed-Door Negotiation**: Play: Your opponent draws a card. Steal 1 Aember. If you do and your opponent still has more Aember than you, trigger this effect again.
- [x] (093) **Dthoshrǎ, Recruiter**: After Reap: Make a token creature.
- [x] (094) **Forced Retirement**: Play: Destroy a creature. If you do, its controller gains 1 Aember.
- [x] (095) **Gemcoat Vendor**: Action: Steal 1 Aember. Deal 1 Damage to Gemcoat Vendor.
- [x] (096) **General Ză Orhă**: Skirmish. (When you use this creature to fight, it is dealt no damge in return.) Play: For each forged key your opponent has, make a token creature.
- [x] (097) **Generous Offer**: Play: Destroy a friendly creature. If you do, steal 2 Aember.
- [x] (098) **Hire On**: Play: Make a token creature. If there is a combined total of 6 Aember or more between both players` pools, archive Hire On.    
- [x] (099) **Mass Buyout**: Play: Destroy each creature. Each player gains Æmber equal to half the number of creatures they controlled that were destroyed this way (rounded up).
- [x] (100) **Ornate Talking Tray**: Omni: Destroy Ornate Talking Tray. Make a token creature.
- [x] (101) **Shopping Spree**: Play: Discard your hand. Draw a card for each card discarded this way.
- [x] (102) **Shrewd Investor**: Elusive. (The first time this creature is attacked each turn, no damage is dealt.) You may have your opponent gain 1A. If you do, capture 4A.
- [x] (103) **Steward Su-uzaynĕ**: Enhance Aember Aember Draw. (These icons have already been added to cards in your deck.)
- [x] (104) **The Old Tinker**: Elusive. (The first time this creature is attacked each turn, no damage is dealt.) Reap: Discard a card from your hand. 
If you do, draw a card.
- [x] (105) **The Visible Hand**: Play: Make 2 token creatures. Reveal your hand to your opponent.
- [x] (106) **Trading Frenzy**: Play: A friendly creature and an enemy creature each capture 3 Aember from their opponent.
- [x] (107) **Shĭgzisŏ Buggy**: Action: Destroy a friendly creature. If you do, gain 2 Aember.
- [x] (108) **Shĭsnyasĭ Buggy**: Action: Lose 1 Aember. If you do, draw 3 cards.
- [x] (109) **Shĭzyokŭ Buggy**: Action: Reveal two cards from your hand. If they share a house, discard them and make a token creature.
- [x] (110) **Strange Shell**: Strange Shell cannot fight or reap. Action: Put Strange Shell into your hand.
- [x] (111) **Diplomat**: Elusive. (The first time this creature is attacked each turn, no damage is dealt.) Reap` Each player gains 1 Æmber.
- [x] (112) **Trader**: Action: Steal 1 A. Destroy Merchant.
- [x] (113) **Prospector**: Destroyed: Draw a card.
House ekwidon - 57 cards

**Comment by strib** [comment]
FYI looks like Exchange Program above is checked off but it's still under review as #2982

**Comment by romanogit** [comment]
Completed or in PR
