### ISSUE TITLE
WoE mechanics to implement

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#2908]
- [x] Add Ekwidon house game
- [x] Add Ekwidon house UI
- [x] Make token from deck
- [x] Make token from selected cards (hand, for example)
- [x] Flip card down to make a token
- [x] Flip token up
- [x] Divide damage
- [x] Use creature as amber
- [x] Splash-attack
- [x] Archive restrictions
- [x] Take control of each upgrade 
- [x] Swap control
- [ ] #3280
- [x] Fetch from "new" API
- [x] Import Deck with token
- [x] Render token
- [x] Render token's versus card
- [x] Test case with token inPlay from start
- [x] Staff Up versus Ether Spider - choose redirect amber

**Comment by romanogit** [comment]
The Make token from deck needs to be redone

**Comment by strib** [comment]
I think we also need something for Staff Up (https://archonarcana.com/Staff_Up) to let the active player choose if Ether Spider is also in place.  Right now it looks like `gainAmber` uses the most recent effect and isn't built to let players choose.
