### ISSUE TITLE
WoE - New counters

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#2915]
WoE counters that need icons

- [x] yea - Election
- [x] nay - Election
- [x] wisdom - Socraterosaurus
- [x] hatch - Extrematode Infection
- [x] paint - Revo Hooligans
- [x] trade - The Æmber Road

Icons in PR: https://github.com/keyteki/keyteki/pull/3150

- [x] Update archonMaker.js
- [x] Update CardImage.jsx

**Comment by SteVader** [comment]
I'm committing the following (which includes the set icon):

<img src="https://github.com/keyteki/keyteki/assets/2436007/1bf0d3d8-b3f7-4733-afc2-7ff46d39811b" width="40" />
<img src="https://github.com/keyteki/keyteki/assets/2436007/b38e34b9-8434-4910-a35f-0073573d35ff" width="40" />
<img src="https://github.com/keyteki/keyteki/assets/2436007/3e2989de-ea20-4ab6-a9a9-2a93ffcfa3bf" width="40" />
<img src="https://github.com/keyteki/keyteki/assets/2436007/0aba53c8-8081-463a-b113-e5ecc1fa12be" width="40" />
<img src="https://github.com/keyteki/keyteki/assets/2436007/f4c10fef-d59c-47ed-beda-3649b07df572" width="40" />
<img src="https://github.com/keyteki/keyteki/assets/2436007/ed503512-0bff-4888-9bef-6deb428f8409" width="40" />
<img src="https://github.com/keyteki/keyteki/assets/2436007/a4018395-db25-42a2-bd9a-e5519d83644a" width="40" />

**Comment by romanogit** [comment]
Great, thanks a lot. We still need to update css and archonMaker
