### ISSUE TITLE
Veylan Analyst is not giving Æmber after using Epic Quest

### ISSUE THREAD

**Issue by blinkingline** [keyteki/keyteki#2920]
This was reported in https://github.com/keyteki/keyteki/issues/584 and it looks like it was fixed at that time, however, I just tested it and it seems to not be working again. 

Easy to reproduce:
Start game and add Epic Quest and Veylan Analyst to your hand.
Put both cards into play. 
Choose a house
Use Epic Quest. 
Veylan Analyst doesn't pay out.

**Comment by romanogit** [comment]
its effect should enter here:
![image](https://user-images.githubusercontent.com/2104075/204098818-322bfd1e-8e48-4d74-8697-955f2bdab46c.png)

Right?

**Comment by blinkingline** [comment]
Yes. That timing was clearer on the old timing chart, but there shouldn't be any difference.
