### ISSUE TITLE
Away Team destroy effect nullified Soulkeeper effect

### ISSUE THREAD

**Issue by MKHAUS** [keyteki/keyteki#2925]
I had Soulkeeper on Away Team. I fought into a creature killing Away Team with the intention of Soulkeeper destroying the largest enemy creature: Deusillus. But it seamed Away Teams trigger happened first, putting Soulkeeper into archives and Soulkeeper never triggered. I wasn't even given the option to choose which triggers first. 

Log chat below:
girltrumpeter85 brings [Vance P. Seargrime, the Great](https://www.keyforgegame.com/deck-details/89065fb4-68cd-4646-8267-aca004a1ff10) to The Crucible
MKHAUS brings [T. P. Menard, filoute de la simplicité](https://www.keyforgegame.com/deck-details/26062ec8-9693-4424-b051-077faf021831) to The Crucible
MKHAUS won the flip and is first player
 girltrumpeter85 has connected to the game server
 MKHAUS has connected to the game server
girltrumpeter85 is shuffling their deck
girltrumpeter85 draws 6 card  s to their maximum of 6
MKHAUS is shuffling their deck
MKHAUS draws 6 card  s to their maximum of 6
MKHAUS draws 1 card 
MKHAUS
gl
girltrumpeter85
ty, u2 - gl hf
Key phase - MKHAUS
MKHAUS does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - MKHAUS
MKHAUS chooses staralliance  as their active house this turn
Main phase - MKHAUS
MKHAUS plays Away Team
Ready phase - MKHAUS
MKHAUS readies their cards 
Draw phase - MKHAUS
End of turn 1
girltrumpeter85: 0 Æmber  (0 keys) MKHAUS: 0 Æmber  (0 keys)
TURN 1 - girltrumpeter85
Key phase - girltrumpeter85
girltrumpeter85 does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - girltrumpeter85
girltrumpeter85 chooses untamed  as their active house this turn
Main phase - girltrumpeter85
girltrumpeter85 plays Bumblebird
girltrumpeter85 plays Reclaimed by Nature
girltrumpeter85 gains an Æmber  due to Reclaimed by Nature's bonus icon
girltrumpeter85 plays Lost in the Woods
girltrumpeter85 gains an Æmber  due to Lost in the Woods's bonus icon
girltrumpeter85 uses Lost in the Woods to shuffle Bumblebird and Away Team into their owner's deck
Ready phase - girltrumpeter85
Draw phase - girltrumpeter85
girltrumpeter85 draws 3 card  s to their maximum of 6
End of turn 1
girltrumpeter85: 2 Æmber  (0 keys) MKHAUS: 0 Æmber  (0 keys)
TURN 2 - MKHAUS
Key phase - MKHAUS
MKHAUS does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - MKHAUS
MKHAUS chooses staralliance  as their active house this turn
Main phase - MKHAUS
MKHAUS plays Commander Chan
MKHAUS plays Securi-Droid
MKHAUS plays Securi-Droid
MKHAUS plays Universal Translator attaching it to Securi-Droid
MKHAUS gains an Æmber  due to Universal Translator's bonus icon
Ready phase - MKHAUS
MKHAUS readies their cards 
Draw phase - MKHAUS
MKHAUS draws 4 card  s to their maximum of 6
End of turn 2
girltrumpeter85: 2 Æmber  (0 keys) MKHAUS: 1 Æmber  (0 keys)
TURN 2 - girltrumpeter85
Key phase - girltrumpeter85
girltrumpeter85 does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - girltrumpeter85
girltrumpeter85 chooses sanctum  as their active house this turn
Main phase - girltrumpeter85
girltrumpeter85 plays Fangs of Gizelhart
girltrumpeter85 gains an Æmber  due to Fangs of Gizelhart's bonus icon
girltrumpeter85 uses Fangs of Gizelhart to purge Commander Chan
girltrumpeter85 plays Fangs of Gizelhart
girltrumpeter85 gains an Æmber  due to Fangs of Gizelhart's bonus icon
girltrumpeter85 uses Fangs of Gizelhart to purge Securi-Droid
girltrumpeter85 plays Fangs of Gizelhart
girltrumpeter85 gains an Æmber  due to Fangs of Gizelhart's bonus icon
girltrumpeter85 uses Fangs of Gizelhart to purge Securi-Droid
Ready phase - girltrumpeter85
Draw phase - girltrumpeter85
girltrumpeter85 draws 3 card  s to their maximum of 6
End of turn 2
girltrumpeter85: 5 Æmber  (0 keys) MKHAUS: 1 Æmber  (0 keys)
TURN 3 - MKHAUS
Key phase - MKHAUS
MKHAUS does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - MKHAUS
MKHAUS chooses dis  as their active house this turn
Main phase - MKHAUS
MKHAUS plays Pain Reaction
MKHAUS gains an Æmber  due to Pain Reaction's bonus icon
MKHAUS plays Dominator Bauble
MKHAUS gains an Æmber  due to Dominator Bauble's bonus icon
MKHAUS plays Bonesaw
MKHAUS discards Truebaru
Ready phase - MKHAUS
MKHAUS readies their cards 
Draw phase - MKHAUS
MKHAUS draws 4 card  s to their maximum of 6
End of turn 3
girltrumpeter85: 5 Æmber  (0 keys) MKHAUS: 3 Æmber  (0 keys)
TURN 3 - girltrumpeter85
Key phase - girltrumpeter85
girltrumpeter85 does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - girltrumpeter85
girltrumpeter85 chooses saurian  as their active house this turn
Main phase - girltrumpeter85
girltrumpeter85 plays Lyco-Saurus
girltrumpeter85 plays City-State Interest
girltrumpeter85 uses City-State Interest to make each friendly creature capture 1 Æmber 
girltrumpeter85 plays Chant of Hubris
girltrumpeter85 gains an Æmber  due to Chant of Hubris's bonus icon
girltrumpeter85 uses Chant of Hubris to remove 1 Æmber  from Lyco-Saurus
girltrumpeter85 uses Chant of Hubris to place 1 Æmber  on Bonesaw
girltrumpeter85 discards Axiom of Grisk
Ready phase - girltrumpeter85
girltrumpeter85 readies their cards 
Draw phase - girltrumpeter85
girltrumpeter85 draws 4 card  s to their maximum of 6
 girltrumpeter85 declares Check!
End of turn 3
girltrumpeter85: 6 Æmber  (0 keys) MKHAUS: 2 Æmber  (0 keys)
TURN 4 - MKHAUS
Key phase - MKHAUS
MKHAUS does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - MKHAUS
MKHAUS chooses staralliance  as their active house this turn
Main phase - MKHAUS
MKHAUS plays Subject Kirby
MKHAUS uses Subject Kirby to allow them to play one non staralliance  creature this turn
MKHAUS plays Subject Kirby
MKHAUS uses Subject Kirby to allow them to play one non staralliance  creature this turn
MKHAUS plays Hadron Collision
MKHAUS uses Hadron Collision to remove ward and deal 3 damage to Lyco-Saurus
MKHAUS plays Cephaloist
MKHAUS gains an Æmber  due to Cephaloist's bonus icon
MKHAUS plays Infurnace
MKHAUS chooses option ' Opponent's '
MKHAUS uses Infurnace to purge Lost in the Woods and Fangs of Gizelhart
MKHAUS uses Infurnace to make girltrumpeter85 lose 2 Æmber 
Ready phase - MKHAUS
MKHAUS readies their cards 
Draw phase - MKHAUS
MKHAUS draws 5 card  s to their maximum of 6
End of turn 4
girltrumpeter85: 4 Æmber  (0 keys) MKHAUS: 3 Æmber  (0 keys)
TURN 4 - girltrumpeter85
Key phase - girltrumpeter85
girltrumpeter85 does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - girltrumpeter85
girltrumpeter85 chooses untamed  as their active house this turn
Main phase - girltrumpeter85
girltrumpeter85 plays Savage Clash
girltrumpeter85 uses Savage Clash to destroy all enemy creatures except Bonesaw
girltrumpeter85 plays Lost in the Woods
girltrumpeter85 gains an Æmber  due to Lost in the Woods's bonus icon
girltrumpeter85 uses Lost in the Woods to shuffle Lyco-Saurus and Bonesaw into their owner's deck
girltrumpeter85 plays Gloriana's Attendant
girltrumpeter85 plays Rapid Evolution
girltrumpeter85 gains an Æmber  due to Rapid Evolution's bonus icon
girltrumpeter85 uses Rapid Evolution to place 7 +1 power counters on Gloriana's Attendant
girltrumpeter85 plays Rapid Evolution
girltrumpeter85 gains an Æmber  due to Rapid Evolution's bonus icon
girltrumpeter85 uses Rapid Evolution to place 8 +1 power counters on Gloriana's Attendant
Ready phase - girltrumpeter85
girltrumpeter85 readies their cards 
Draw phase - girltrumpeter85
girltrumpeter85 draws 5 card  s to their maximum of 6
 girltrumpeter85 declares Check!
End of turn 4
girltrumpeter85: 8 Æmber  (0 keys) MKHAUS: 3 Æmber  (0 keys)
TURN 5 - MKHAUS
Key phase - MKHAUS
MKHAUS does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - MKHAUS
MKHAUS chooses dis  as their active house this turn
Main phase - MKHAUS
MKHAUS plays Brabble
MKHAUS plays Mark of Dis
MKHAUS gains an Æmber  due to Mark of Dis's bonus icon
MKHAUS deals 1 damage to Gloriana's Attendant due to Mark of Dis's bonus icon
MKHAUS uses Mark of Dis to deal 2 damage to Gloriana's Attendant
MKHAUS plays Infurnace
MKHAUS chooses option ' Opponent's '
MKHAUS uses Infurnace to purge Lost in the Woods and Fangs of Gizelhart
MKHAUS uses Infurnace to make girltrumpeter85 lose 2 Æmber 
MKHAUS plays Pandemonium
MKHAUS gains an Æmber  due to Pandemonium's bonus icon
MKHAUS uses Pandemonium to cause each undamaged creature to capture 1 Æmber  from their opponent
Ready phase - MKHAUS
MKHAUS readies their cards 
Draw phase - MKHAUS
MKHAUS draws 4 card  s to their maximum of 6
End of turn 5
girltrumpeter85: 4 Æmber  (0 keys) MKHAUS: 5 Æmber  (0 keys)
TURN 5 - girltrumpeter85
Key phase - girltrumpeter85
girltrumpeter85 does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - girltrumpeter85
girltrumpeter85 chooses untamed  as their active house this turn
Main phase - girltrumpeter85
girltrumpeter85 plays Savage Clash
girltrumpeter85 uses Savage Clash to destroy all enemy creatures except Infurnace
MKHAUS uses Brabble to make girltrumpeter85 lose 3 Æmber 
girltrumpeter85 uses Gloriana's Attendant to make Gloriana's Attendant fight Infurnace
Ready phase - girltrumpeter85
girltrumpeter85 readies their cards 
Draw phase - girltrumpeter85
girltrumpeter85 draws 1 card  to their maximum of 6
End of turn 5
girltrumpeter85: 3 Æmber  (0 keys) MKHAUS: 5 Æmber  (0 keys)
TURN 6 - MKHAUS
Key phase - MKHAUS
MKHAUS does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - MKHAUS
MKHAUS chooses untamed  as their active house this turn
Main phase - MKHAUS
MKHAUS plays Lost in the Woods
MKHAUS gains an Æmber  due to Lost in the Woods's bonus icon
MKHAUS uses Lost in the Woods to shuffle Gloriana's Attendant into their owner's deck
MKHAUS plays Floomf
MKHAUS plays Floomf
MKHAUS gains an Æmber  due to Floomf's bonus icon
MKHAUS plays Punctuated Equilibrium
MKHAUS uses Punctuated Equilibrium to discard Bonesaw and Xenotraining from MKHAUS's hand and discard Mad Prophet Gizelhart, Berinon, Citizen Shrix, It’s Coming..., Thero Centurion, and Bumblebird from girltrumpeter85's hand, then make both players refill their hands
MKHAUS draws 6 card  s to their maximum of 6
girltrumpeter85 draws 6 card  s to their maximum of 6
MKHAUS discards Wild Bounty
MKHAUS discards Reclaimed by Nature
Ready phase - MKHAUS
MKHAUS readies their cards 
Draw phase - MKHAUS
MKHAUS draws 2 card  s to their maximum of 6
 MKHAUS declares Check!
End of turn 6
girltrumpeter85: 3 Æmber  (0 keys) MKHAUS: 7 Æmber  (0 keys)
TURN 6 - girltrumpeter85
Key phase - girltrumpeter85
girltrumpeter85 does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - girltrumpeter85
girltrumpeter85 chooses untamed  as their active house this turn
Main phase - girltrumpeter85
girltrumpeter85 plays Ghosthawk
girltrumpeter85 plays Gloriana's Attendant
girltrumpeter85 plays Commune
girltrumpeter85 uses Commune to do several things
girltrumpeter85 played Commune which has Omega, ending this step
Ready phase - girltrumpeter85
girltrumpeter85 readies their cards 
Draw phase - girltrumpeter85
girltrumpeter85 draws 3 card  s to their maximum of 6
End of turn 6
girltrumpeter85: 4 Æmber  (0 keys) MKHAUS: 7 Æmber  (0 keys)
TURN 7 - MKHAUS
Key phase - MKHAUS
MKHAUS forges the blue key  , paying 6 Æmber 
House phase - MKHAUS
MKHAUS chooses untamed  as their active house this turn
Main phase - MKHAUS
MKHAUS uses Floomf to make Floomf fight Ghosthawk
MKHAUS uses Floomf to place 2 +1 power counters on Floomf
MKHAUS uses Floomf to make Floomf fight Gloriana's Attendant
MKHAUS uses Floomf to place 2 +1 power counters on Floomf
MKHAUS plays Fandangle
MKHAUS plays Commune
MKHAUS uses Commune to do several things
MKHAUS played Commune which has Omega, ending this step
Ready phase - MKHAUS
MKHAUS readies their cards 
Draw phase - MKHAUS
MKHAUS draws 2 card  s to their maximum of 6
End of turn 7
girltrumpeter85: 4 Æmber  (0 keys) MKHAUS: 4 Æmber  (1 key)
TURN 7 - girltrumpeter85
Key phase - girltrumpeter85
girltrumpeter85 does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - girltrumpeter85
girltrumpeter85 chooses sanctum  as their active house this turn
Main phase - girltrumpeter85
girltrumpeter85 plays Fangs of Gizelhart
girltrumpeter85 gains an Æmber  due to Fangs of Gizelhart's bonus icon
girltrumpeter85 uses Fangs of Gizelhart to purge Floomf
girltrumpeter85 plays General Xalvador
girltrumpeter85 plays Gizelhart’s Standard
girltrumpeter85 gains an Æmber  due to Gizelhart’s Standard's bonus icon
girltrumpeter85 uses Gizelhart’s Standard to exalt General Xalvador
girltrumpeter85 plays Call to Action
girltrumpeter85 uses Call to Action to ready General Xalvador
girltrumpeter85 uses General Xalvador to make General Xalvador fight Fandangle
Ready phase - girltrumpeter85
girltrumpeter85 readies their cards 
Draw phase - girltrumpeter85
girltrumpeter85 draws 4 card  s to their maximum of 6
 girltrumpeter85 declares Check!
End of turn 7
girltrumpeter85: 6 Æmber  (0 keys) MKHAUS: 4 Æmber  (1 key)
TURN 8 - MKHAUS
Key phase - MKHAUS
MKHAUS does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - MKHAUS
MKHAUS chooses dis  as their active house this turn
Main phase - MKHAUS
MKHAUS plays Lord Invidius
MKHAUS gains an Æmber  due to Lord Invidius's bonus icon
MKHAUS plays Hystricog
MKHAUS deals 1 damage to General Xalvador due to Hystricog's bonus icon
MKHAUS uses Dominator Bauble to use Floomf
MKHAUS uses Floomf to reap with Floomf
Ready phase - MKHAUS
MKHAUS readies their cards 
Draw phase - MKHAUS
MKHAUS draws 2 card  s to their maximum of 6
 MKHAUS declares Check!
End of turn 8
girltrumpeter85: 6 Æmber  (0 keys) MKHAUS: 6 Æmber  (1 key)
TURN 8 - girltrumpeter85
Key phase - girltrumpeter85
girltrumpeter85 forges the red key  , paying 6 Æmber 
House phase - girltrumpeter85
girltrumpeter85 chooses saurian  as their active house this turn
Main phase - girltrumpeter85
girltrumpeter85 plays Deusillus
girltrumpeter85 uses Deusillus to capture all Æmber  and deal 5 damage to Lord Invidius
girltrumpeter85 plays Senator Quintina
girltrumpeter85 plays Citizen Shrix
girltrumpeter85 uses Citizen Shrix to exalt Citizen Shrix and steal 1 Æmber 
Ready phase - girltrumpeter85
girltrumpeter85 readies their cards 
Draw phase - girltrumpeter85
girltrumpeter85 draws 4 card  s to their maximum of 6
End of turn 8
girltrumpeter85: 0 Æmber  (1 key) MKHAUS: 0 Æmber  (1 key)
TURN 9 - MKHAUS
Key phase - MKHAUS
MKHAUS does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - MKHAUS
MKHAUS chooses untamed  as their active house this turn
Main phase - MKHAUS
MKHAUS uses Floomf to make Floomf fight Senator Quintina
MKHAUS uses Floomf to place 2 +1 power counters on Floomf
MKHAUS plays Gloriana's Attendant
MKHAUS plays Lost in the Woods
MKHAUS gains an Æmber  due to Lost in the Woods's bonus icon
MKHAUS uses Lost in the Woods to shuffle Gloriana's Attendant and Hystricog and Citizen Shrix and Deusillus into their owner's deck
Ready phase - MKHAUS
MKHAUS readies their cards 
Draw phase - MKHAUS
MKHAUS draws 2 card  s to their maximum of 6
 MKHAUS declares Check!
End of turn 9
girltrumpeter85: 0 Æmber  (1 key) MKHAUS: 8 Æmber  (1 key)
TURN 9 - girltrumpeter85
Key phase - girltrumpeter85
girltrumpeter85 does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - girltrumpeter85
girltrumpeter85 chooses sanctum  as their active house this turn
Main phase - girltrumpeter85
girltrumpeter85 plays Umbra-Knight
girltrumpeter85 captures an Æmber  on Umbra-Knight due to Umbra-Knight's bonus icon
girltrumpeter85 plays Lieutenant Gorvenal
girltrumpeter85 gains an Æmber  due to Lieutenant Gorvenal's bonus icon
girltrumpeter85 gains an Æmber  due to Lieutenant Gorvenal's bonus icon
girltrumpeter85 plays Lieutenant Gorvenal
girltrumpeter85 uses General Xalvador to make General Xalvador fight Floomf
girltrumpeter85 uses Lieutenant Gorvenal to capture 1 Æmber  from their opponent , placing it on Lieutenant Gorvenal
girltrumpeter85 uses Lieutenant Gorvenal to capture 1 Æmber  from their opponent , placing it on Lieutenant Gorvenal
Ready phase - girltrumpeter85
girltrumpeter85 readies their cards 
Draw phase - girltrumpeter85
girltrumpeter85 draws 3 card  s to their maximum of 6
End of turn 9
girltrumpeter85: 2 Æmber  (1 key) MKHAUS: 6 Æmber  (1 key)
TURN 10 - MKHAUS
Key phase - MKHAUS
MKHAUS forges the yellow key  , paying 6 Æmber 
House phase - MKHAUS
MKHAUS chooses staralliance  as their active house this turn
Main phase - MKHAUS
MKHAUS plays Securi-Droid attaching it to Floomf
MKHAUS plays Lyco-Alien
MKHAUS plays Teleporter Chief Tink
MKHAUS plays Away Team
Ready phase - MKHAUS
MKHAUS readies their cards 
Draw phase - MKHAUS
MKHAUS draws 4 card  s to their maximum of 6
MKHAUS's deck has run out of cards, so they shuffle
End of turn 10
girltrumpeter85: 2 Æmber  (1 key) MKHAUS: 0 Æmber  (2 keys)
TURN 10 - girltrumpeter85
Key phase - girltrumpeter85
girltrumpeter85 does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - girltrumpeter85
girltrumpeter85 chooses saurian  as their active house this turn
Main phase - girltrumpeter85
girltrumpeter85 plays Citizen Shrix
girltrumpeter85 uses Citizen Shrix to exalt Citizen Shrix and steal 1 Æmber 
girltrumpeter85 plays Deusillus
girltrumpeter85 uses Deusillus to capture all Æmber  and deal 5 damage to Lyco-Alien
girltrumpeter85 plays Lyco-Saurus
girltrumpeter85 uses Lyco-Saurus to exalt Lyco-Saurus
girltrumpeter85 plays Defense Initiative
girltrumpeter85 uses Defense Initiative to ward Deusillus
Ready phase - girltrumpeter85
girltrumpeter85 readies their cards 
Draw phase - girltrumpeter85
girltrumpeter85 draws 5 card  s to their maximum of 6
girltrumpeter85's deck has run out of cards, so they shuffle
End of turn 10
girltrumpeter85: 2 Æmber  (1 key) MKHAUS: 0 Æmber  (2 keys)
TURN 11 - MKHAUS
Key phase - MKHAUS
MKHAUS does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - MKHAUS
MKHAUS chooses dis  as their active house this turn
Main phase - MKHAUS
MKHAUS plays Hystricog
MKHAUS deals 1 damage to Deusillus due to Hystricog's bonus icon
Deusillus's ward token prevents the damage dealt by a bonus icon and is discarded
**MKHAUS plays Soulkeeper attaching it to Away Team
MKHAUS gains an Æmber  due to Soulkeeper's bonus icon
MKHAUS uses Dominator Bauble to use Away Team
MKHAUS uses Away Team to make Away Team fight Lyco-Saurus
Lyco-Saurus's ward token prevents the damage dealt by Away Team and is discarded
MKHAUS uses Away Team to archive Soulkeeper**
MKHAUS
why didn't that work?
girltrumpeter85
Probably because the archiving took place before the action?
MKHAUS
but why would that matter?
girltrumpeter85
If it's archived it's not in play to trigger.
MKHAUS
so if I put on Floof instead Deusillus kills Floof, Soul keeper kills Deusilas,
MKHAUS
Soul keeper goes to discard and Lyco gets back the ward?
MKHAUS
Away Team put back on board
girltrumpeter85
Were you given the option to select which trigger first?
MKHAUS
no
girltrumpeter85
If you trigger away team first, soulkeeper doesn't get the opportunity.
MKHAUS
oh Floof has skirmish so that wouldn't work anywy
girltrumpeter85
Yeah
girltrumpeter85
Looks like this was a bug, and since you didn't get the opportunity to select which one triggered I'll destroy deusillus
MKHAUS
Is it a bug?
girltrumpeter85
Yes, I double checked with my team.
girltrumpeter85
Sometimes it doesn't give the option.
 girltrumpeter85 is attempting to switch manual mode on
 MKHAUS allows enabling manual mode
 girltrumpeter85 switches manual mode on
 girltrumpeter85 manually moves Deusillus from their play area to their discard
 girltrumpeter85 switches manual mode off
girltrumpeter85
There you go
MKHAUS
Thanks
girltrumpeter85
Since that was clearly the intention, and you didn't get to choose
MKHAUS
Soulkeeper stays in archives?
girltrumpeter85
Yes
girltrumpeter85
Destroyed affects happen simultaneously, and active player chooses
MKHAUS
right
girltrumpeter85
In this case, you chose destroy affect first, followed by archiving the soulkeeper.
MKHAUS
makes sense
girltrumpeter85
Yup
MKHAUS plays Brabble
MKHAUS plays Infurnace
MKHAUS chooses option ' Opponent's '
MKHAUS uses Infurnace to purge Deusillus and Deusillus
Ready phase - MKHAUS
MKHAUS readies their cards 
Draw phase - MKHAUS
MKHAUS draws 4 card  s to their maximum of 6
End of turn 11
girltrumpeter85: 2 Æmber  (1 key) MKHAUS: 2 Æmber  (2 keys)
TURN 11 - girltrumpeter85
Key phase - girltrumpeter85
girltrumpeter85 does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - girltrumpeter85
girltrumpeter85 chooses untamed  as their active house this turn
Main phase - girltrumpeter85
girltrumpeter85 discards Savage Clash
girltrumpeter85 discards Savage Clash
girltrumpeter85 plays Reclaimed by Nature
girltrumpeter85 gains an Æmber  due to Reclaimed by Nature's bonus icon
girltrumpeter85 uses Reclaimed by Nature to purge Dominator Bauble and resolve its bonus icons
girltrumpeter85 gains an Æmber  due to Dominator Bauble's bonus icon
girltrumpeter85 plays Commune
girltrumpeter85 uses Commune to do several things
girltrumpeter85 played Commune which has Omega, ending this step
Ready phase - girltrumpeter85
girltrumpeter85 readies their cards 
Draw phase - girltrumpeter85
girltrumpeter85 draws 4 card  s to their maximum of 6
End of turn 11
girltrumpeter85: 4 Æmber  (1 key) MKHAUS: 2 Æmber  (2 keys)
TURN 12 - MKHAUS
Key phase - MKHAUS
MKHAUS does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - MKHAUS
MKHAUS chooses dis  as their active house this turn
Main phase - MKHAUS
MKHAUS plays Lord Invidius
MKHAUS gains an Æmber  due to Lord Invidius's bonus icon
MKHAUS uses Brabble to make Brabble fight Citizen Shrix
Citizen Shrix's ward token prevents the damage dealt by Brabble and is discarded
MKHAUS uses Brabble to make girltrumpeter85 lose 1 Æmber 
MKHAUS uses Infurnace to make Infurnace fight Lyco-Saurus
MKHAUS uses Hystricog to destroy Lyco-Saurus
MKHAUS plays Bonesaw
MKHAUS uses Bonesaw to make Bonesaw fight Citizen Shrix
Ready phase - MKHAUS
MKHAUS readies their cards 
Draw phase - MKHAUS
MKHAUS draws 2 card  s to their maximum of 6
End of turn 12
girltrumpeter85: 3 Æmber  (1 key) MKHAUS: 5 Æmber  (2 keys)
TURN 12 - girltrumpeter85
Key phase - girltrumpeter85
girltrumpeter85 does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - girltrumpeter85
girltrumpeter85 chooses sanctum  as their active house this turn
Main phase - girltrumpeter85
girltrumpeter85 plays Fangs of Gizelhart
girltrumpeter85 gains an Æmber  due to Fangs of Gizelhart's bonus icon
girltrumpeter85 uses Fangs of Gizelhart to purge Floomf
girltrumpeter85 plays General Xalvador
girltrumpeter85 plays Mad Prophet Gizelhart
girltrumpeter85 uses Lieutenant Gorvenal to reap with Lieutenant Gorvenal
girltrumpeter85 uses Lieutenant Gorvenal to reap with Lieutenant Gorvenal
girltrumpeter85 uses Umbra-Knight to reap with Umbra-Knight
Ready phase - girltrumpeter85
girltrumpeter85 readies their cards 
Draw phase - girltrumpeter85
girltrumpeter85 draws 3 card  s to their maximum of 6
 girltrumpeter85 declares Check!
End of turn 12
girltrumpeter85: 7 Æmber  (1 key) MKHAUS: 5 Æmber  (2 keys)
TURN 13 - MKHAUS
Key phase - MKHAUS
MKHAUS does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - MKHAUS
MKHAUS chooses dis  as their active house this turn
MKHAUS moves all the cards  in their archives to their hand
Main phase - MKHAUS
MKHAUS uses Lord Invidius to reap with Lord Invidius
MKHAUS uses Lord Invidius to apply a lasting effect to Mad Prophet Gizelhart
MKHAUS plays Mark of Dis
MKHAUS gains an Æmber  due to Mark of Dis's bonus icon
MKHAUS deals 1 damage to Lieutenant Gorvenal due to Mark of Dis's bonus icon
MKHAUS uses Mark of Dis to deal 2 damage to Lieutenant Gorvenal
MKHAUS uses Hystricog to destroy Lieutenant Gorvenal
MKHAUS plays Soulkeeper attaching it to Bonesaw
MKHAUS gains an Æmber  due to Soulkeeper's bonus icon
MKHAUS uses Bonesaw to make Bonesaw fight Lieutenant Gorvenal
MKHAUS uses Bonesaw to destroy Umbra-Knight
Ready phase - MKHAUS
MKHAUS readies their cards 
Draw phase - MKHAUS
MKHAUS draws 1 card  to their maximum of 6
 MKHAUS declares Check!
End of turn 13
girltrumpeter85: 7 Æmber  (1 key) MKHAUS: 10 Æmber  (2 keys)
TURN 13 - girltrumpeter85
Key phase - girltrumpeter85
girltrumpeter85 forges the blue key  , paying 6 Æmber 
House phase - girltrumpeter85
girltrumpeter85 chooses sanctum  as their active house this turn
Main phase - girltrumpeter85
girltrumpeter85 uses General Xalvador to reap with General Xalvador
girltrumpeter85 uses Lieutenant Gorvenal to reap with Lieutenant Gorvenal
Ready phase - girltrumpeter85
girltrumpeter85 readies their cards 
Draw phase - girltrumpeter85
End of turn 13
girltrumpeter85: 3 Æmber  (2 keys) MKHAUS: 10 Æmber  (2 keys)
TURN 14 - MKHAUS
Key phase - MKHAUS
MKHAUS forges the red key  , paying 6 Æmber 
 MKHAUS has won the game
girltrumpeter85
gg
MKHAUS
gg
MKHAUS
that was fun, thanks for the game
 girltrumpeter85 has left the game

**Comment by romanogit** [comment]
not a bug
