### ISSUE TITLE
Dimension Door and Æmberspine Mongrel

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#2933]
When my opponent has 0 amber and I reap after playing Dimension Door, engine does not allow me to trigger Æmberspine Mongrel's effect first and then steal with DD.

**Comment by dmikalova** [comment]
I don't think this is a bug - you get the aember from reaping immediately, and then mongrel's after reap effect happens. Dimension door is a replacement effect, so the timing doesn't change - you attempt to steal immediately, it fails, and then mongrel's effect happens.

**Comment by romanogit** [comment]
Not an issue
