### ISSUE TITLE
Allow for the Active Player to Order Their Simultaneously Destroyed or Discarded Cards in Their Discard Pile

### ISSUE THREAD

**Issue by PrinceofCurses** [keyteki/keyteki#2934]
Examples include using Eyegor. Or just being able to do this for setting up for Z.Y.X Researcher. You should be able to decide the order of the discard as per the rules. I know it comes up rarely, but in some specific interactions it could come up. Is there any way this can be implemented? If it's not feasible, I understand. I also ask because with future cards coming out, it may come up more eventually. 

Issue #102 made a reference to this in 2019 as well. I think it would be good for the game and for some specific decks in particular.

**Comment by romanogit** [comment]
We have #102 still open. It is difficult to implement due to the nature of the engine and the moment when things occur (such as ward, for example). 
Closing this one as dup.
