### ISSUE TITLE
Bottom of deck is not kept as expected

### ISSUE THREAD

**Issue by Gungnir8** [keyteki/keyteki#2949]
I noticed in a game I just played that the bottom of deck isn't kept as it is supposed to do.
I used my Dino-Alien twice in the match, first time I put a Transport Platform at the bottom which I then picked up with an Orb.
The second time, I put my Faust the Great at the bottom. The when I drew cards and only had one card left in my deck, it wasn't Faust but another card. 

![bottom_bug](https://user-images.githubusercontent.com/111249383/230793902-5f131f04-9967-4f29-9214-2839fba112f3.PNG)
[match 1.3.docx](https://github.com/keyteki/keyteki/files/11186210/match.1.3.docx)

**Comment by SkyJedi** [comment]
Orb of wonder shuffles your decks after searching.

![085](https://user-images.githubusercontent.com/2967416/230800315-2a121a53-a524-407f-8008-15355905059c.jpg)

**Comment by romanogit** [comment]
not an issue
