### ISSUE TITLE
Extra It's Coming added in Alliance deck

### ISSUE THREAD

**Issue by avandever** [keyteki/keyteki#2952]
I recently created an Alliance deck. One of the source decks had a Gigantic creature, and therefore, It's Coming. However, I did not use that pod, I used the Logos pod from that deck. My Alliance deck is titled "Emilio Moonmouth Sayidah". Here is the deck the It's Coming was pulled from: https://decksofkeyforge.com/decks/4cc98ccd-3037-4fb5-950b-d56c3dfa2b8e

**Comment by KMarch82** [comment]
I also have this issue with a recent Alliance build. It pulled the "It's Coming" from an unused Untamed House from one of the decks.

**Comment by romanogit** [comment]
Dupe of https://github.com/keyteki/keyteki/issues/2875

**Comment by romanogit** [comment]
Not fixed
