### ISSUE TITLE
Bug: Wild Wormhole into Mimicry. Mimicry did not fire

### ISSUE THREAD

**Issue by ejlertson** [keyteki/keyteki#297]
Just played a game.
I played Wild Wormhole and revealed a Mimicry.
Normally I should get the option to choose an opposing Actioncard to Mimic but I did not get the usual selection screen. He had several actions in his Descard pile so that is not the issue.

**Comment by Achocholacek** [comment]
This is a known issue surrounding mimicry/wormhole that we are working on! Thanks for the report and your patience!

**Comment by cryogen** [comment]
This is now fixed
