### ISSUE TITLE
Brend the Fanatic in two battlelines should trigger a player decision when destroyed

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#301]
Battle line is like this: "Brend the Fanatic" on my side and "Brend the Fanatic" on opponent's side. No other creature. I have "Key to Dis" artifact on my side.

Card says: Skirmish. Play: Your opponent gains 1A. Destroyed: Steal 3A.

I have 0 amber and oppoent has 3 ambers.

When I use Key to Dis, it will destroy both creatures. Depending on the order of stealing, the result will be different, right?

Scenario 1:

```
Situation:
Romano: 0
Opponent: 3

Romano steals:
Romano: 3
Opponent: 0

Opponent steals: 
Romano: 0
Opponent: 3
```

Scenario 2:

```
Situation:
Romano: 0
Opponent: 3

Opponent steals:
Romano: 0
Opponent: 3

Romano steals: 
Romano: 3
Opponent: 0
```

I think we have to have the ability to choose.

**Comment by romanogit** [comment]
Or, are the abilities triggered at the same time and the amber check done without considering the stealing part?

**Comment by romanogit** [comment]
Another exemple. I have Snib Granade and Brend. Opponent has 4 amber. 

If both are Destroyed at the same time and I am the active player, I would like to steal 3 before opponent loses 2. If decision is from opponent, then he would probably choose the opposite.

**Comment by 4ugeistr** [comment]
The rules say:
_If a card has a “Destroyed:” ability, the effect automatically resolves immediately before the card would be destroyed, which is also before it leaves play.
(The active player determines what order the destroyed cards are put into the discard pile(s).)_

Basically the Active player should be able to determine the order in which both his and opponent's cards go into discard and thus the order of triggering **Destroyed:** abilities

**Comment by romanogit** [comment]
@jeremylarner : why isn't this fixed by your timing refactors?

**Comment by romanogit** [comment]
@jeremylarner ,
This issue seems to be fixed by the timing refactor, but look at the prompt I receive:

![image](https://user-images.githubusercontent.com/2104075/70367882-70c59200-1883-11ea-9740-06ca58ab3f13.png)

**Comment by romanogit** [comment]
Fixed by timing refactor.
