### ISSUE TITLE
ActivePromptTitle of a token is showing versus card name

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#3079]
ActivePromptTitle of a token is showing versus card name

**Comment by romanogit** [comment]
Is this necessarily bad?

**Comment by strib** [comment]
Yes, it is against the rules to know what the versus card is before you place it in the battleline.  From version 17 of the rulebook:
![image](https://github.com/keyteki/keyteki/assets/8516691/efbb4d40-532a-4ab5-9f86-d876d1438c0a)
