### ISSUE TITLE
Bear Flute doesn't shuffle discard back into the deck

### ISSUE THREAD

**Issue by TeaSeaLancs** [keyteki/keyteki#310]
The card text for Bear Flute reads:

> Action: Fully heal an Ancient Bear. If there are no Ancient Bears in play, search your deck and discard pile and put each Ancient Bear from them into your hand. If you do, shuffle your discard pile into your deck.

However, the final part of the action is not being executed and the discard is not shuffled back into the deck. Examples of this can be found in the match at https://www.thecrucibletracker.com/games/abb35dc0-bafa-11e9-9188-4794827cbbfe/log

**Comment by Rognetudjiu** [comment]
Hi ! Thanks for your work on crucible ! :) Please fix bear flute, it is getting annoying to manually discard all draw pile to make all cards shuffle (i have not found any other way) ! :D

**Comment by theBHawk** [comment]
Hi - This is happening again. This time it's when i have One Ancient bear in hand, and there are no other ancient bears in the deck or discard pile (so a single ancient bear - bear flute deck).

**Comment by theBHawk** [comment]
Hi - This is happening again. This time when my only Ancient Bear got purged. However I should still be able to search my deck but just fail to find ancient bear.
