### ISSUE TITLE
Bellowing patrizate : doesn't  deal damages when stun.

### ISSUE THREAD

**Issue by skrohmagnon** [keyteki/keyteki#313]
I have a bellowing patrizate uin play and stunned. It's ready so it should deal one damage to played  creatures but it doesn't
![bellowing patrizate](https://user-images.githubusercontent.com/46242885/62821192-61eaff00-bb71-11e9-8028-fcb8a995d5ed.JPG)

**Comment by Achocholacek** [comment]
This is actually a bug with Hallowed Shield, but it's definitely a bug. Will investigate.
