### ISSUE TITLE
Bug: Bad Penny equipped with Soulkeeper did not destroy opponents most powerfull creature

### ISSUE THREAD

**Issue by ejlertson** [keyteki/keyteki#315]
On hus side was a Lion Bautrem-Rothais the Fierce-Fanghouse
I had a Bad Penny with Soulkeeper equipped. I used Smite to activate Penny and attack Rothais.
Bad Penny was returned to hand, but Rothais was not killed despite being the most powerfull creature.
With Penny having 2 Destroyed abilities, I as active player should get to choose order :)

Cheers
Poul

**Comment by Achocholacek** [comment]
Definitely an issue. Thanks for reporting.

**Comment by romanogit** [comment]
This is what happens now (I have a prompt for single action checkbox clicked)
- Bad Penny fights Rothais and then a framework effect is prompted:

![image](https://user-images.githubusercontent.com/2104075/71185364-100e6000-225a-11ea-9b3a-ecd78a16d39f.png)

- Only Bad Penny is selectable:

![image](https://user-images.githubusercontent.com/2104075/71185324-fff68080-2259-11ea-9eae-f00a4988c467.png)

- I click on Bad Penny and then I have the option to choose which Destroy ability to trigger first:

![image](https://user-images.githubusercontent.com/2104075/71185415-29afa780-225a-11ea-9ad5-37d2c9e84031.png)

(not sure what Back button does)

I choose Soulkeeper and then I am prompted to selected the most powerful creature:

![image](https://user-images.githubusercontent.com/2104075/71185502-51067480-225a-11ea-8e32-66e39b8d7fe8.png)

After I click on Rothais, Bad Penny returns to my hand.

**Comment by romanogit** [comment]
Even if I click on Bad Penny first, SK effect is applied correctly

**Comment by romanogit** [comment]
Even when the engine decides the order to apply the abilities, it is now working as expected.
