### ISSUE TITLE
Interdimensional Graft vs. Vaultkeeper

### ISSUE THREAD

**Issue by Strikeforce007** [keyteki/keyteki#319]
My opponent had Vaultkeeper on the battle-line and after playing Interdimensional Graft their Aember did not transfer to me. Unless I am mistaken since Interdimensional Graft does not indicate it is stealing the Aember I believe Vaultkeeper should not have stopped the transfer of Aember from their side to mine.

**Comment by Achocholacek** [comment]
This is a known bug and a fix is incoming.

Similar/Dupe of #288
