### ISSUE TITLE
BUG: cards with spaces do not work in tests

### ISSUE THREAD

**Issue by alifeee** [keyteki/keyteki#3193]
Using bad penny for tests fails. Not sure why.

This change breaks the tests:

- <https://github.com/alifeee/keyteki/compare/7bdd575b4d6e76272ba615301e4d797d7f1dc35d..51860830f194b5c57290a67f4942c2c031a1970d>

## Broken (with bad penny)

```bash
git clone https://github.com/alifeee/keyteki.git
npm install
git checkout 51860830f194b5c57290a67f4942c2c031a1970d
npm test test\server\cards\06-WoE\OstentatiousMount.spec.js
```

## Fixed (with hookmaster)

```bash
git clone https://github.com/alifeee/keyteki.git
npm install
git checkout 51860830f194b5c57290a67f4942c2c031a1970d
npm test test\server\cards\06-WoE\OstentatiousMount.spec.js
```

## Other cards

Using `"sir-bevor"` and `this.sirbevor` also breaks.

## Why

I don't know why. For now, I am just going to use cards without a space in between text.

**Comment by romanogit** [comment]
I you need to use badPenny or sirBevor.

Not sure if that's what you mean.

**Comment by alifeee** [comment]
Yes, I think my issue was capitalisation.

Thanks.
