### ISSUE TITLE
BUG: Games with DT decks broken on newest `woe` branch

### ISSUE THREAD

**Issue by alifeee** [keyteki/keyteki#3195]
Dark tidings decks have been broken

![image](https://github.com/keyteki/keyteki/assets/13833017/91a42a0e-07a2-4216-baf3-f203cc841067)

To replicate:

`docker-compose up --build`

1. Connect to lobby
2. Register dark tidings deck
3. Attempt to play game

**Comment by romanogit** [comment]
This is fixed
