### ISSUE TITLE
Shadow of Dis did not cancel opponent's Skirmish

### ISSUE THREAD

**Issue by roeswood** [keyteki/keyteki#321]
I played Shadow of Dis. On my opponent's next turn, they attacked with Quixo the Adventurer and Quixo did not take damage. Quixo should have lost Skirmish due to Shadow of Dis.

**Comment by romanogit** [comment]
Which creature did it attack? Any chance the creature was elusive?

**Comment by roeswood** [comment]
Pretty sure it was a Spyyder. I do remember my creature was destroyed.

**Comment by romanogit** [comment]
Ok, thanks for the extra info, I will try to recreate this one.

**Comment by romanogit** [comment]
I was able to recreate this one. It seems to be ignore abilities such as `Skirmish` and `Elusive`, but it is working to ignore `Fight` (need to check Reap and Action). I also ignored `Titan Mechanic` by not forging a key at cost 5.

**Comment by romanogit** [comment]
@jeremylarner changed the engine to consider `keywords` as `effects` (see push #326). 
I added a few more tests.

**Comment by cryogen** [comment]
Fixed by #329 (not yet deployed)
