### ISSUE TITLE
No explanation is given when a card ability tries to play another card that can't be played

### ISSUE THREAD

**Issue by hydrophilic-attack** [keyteki/keyteki#323]
Sometimes cards like Murkens and wild wormhole attempt to play cards that currently can't be played. Ideally, when this happens, the log should tell players what card is attempted to be played, but in my experience this isn't always the case. Here are a couple of examples:

1. My opponent played Murkens, targeting my archives which contain 4 cards, of which 2 have alpha. Nothing happened, presumably because one of the alpha cards was randomly selected. In this situation, the log should tell us what card was attempted to be played, but this didn't happen. The log just said "player x plays Murkens" (This one happened last week so it may have been fixed since then.)

2. In check for my opponent's final key, I desperately play Wild Wormhole, hoping to hit my Doorstep to Heaven. No card was played, presumably because my opponent had popped a Lifeward the previous turn and the top card of my deck was a creature. The log should tell us what card was attempted to be played, but only said "hydro_attack plays Wild Wormhole, gaining 1 amber"

**Comment by Achocholacek** [comment]
This is a known bug we're working on. Thanks for the report.

**Comment by hydrophilic-attack** [comment]
In case you want some more data on Murkens, here is another weird scenario that just happened.

I had 3 Fates and Shooler in my archives, my opponent plays Murkens. Here is what the log said:

Main phase - bomzzz
bomzzz plays Special Delivery, gaining 1 Æmber
bomzzz plays Bad Penny
bomzzz plays Bad Penny
bomzzz plays Murkens
bomzzz uses Murkens to play Three Fates
bomzzz plays Shooler
bomzzz uses Shooler to steal 1 Æmber from hydro_attack
bomzzz plays Throwing Stars
hydro_attack
that didn't work
bomzzz uses Throwing Stars to deal 1 damage to Titan Mechanic, Mother, and Zorg

So first Three Fates was played according to the log, but no creature was destroyed. Then it instead played my shooler who was in my archives. (My opponent didn't have shooler in their deck, so there is no way something else was going on.
