### ISSUE TITLE
WoE: Tokenized creatures retain aspects when later played as a creature

### ISSUE THREAD

**Issue by dmikalova** [keyteki/keyteki#3241]
In a couple test games it looked like a creature card that was first turned into a token, then destroyed, and then after shuffling the deck and being played, the creature still had some aspects of the token. Examples:

- Faust card was tokenized into a prospector. Prospector is destroyed, discard is shuffled into deck, and then opponent plays faust as faust. When faust was destroyed, the opponent drew a card as if faust had the prospector destroyed effect.
- Fuguru was tokenized into a raider, destroyed, discard is shuffled into deck, and then opponent plays fuguru as fuguru. I played genetic blast against fuguru, and the damage was dealt not just to fuguru, but all raiders as well as if fuguru still had the raider name.

**Comment by alifeee** [comment]
This issue should be reopened - #3287

**Comment by dmikalova** [comment]
I just had a game where a rowdy skald retained a researcher ability

> dmikalova uses Rowdy Skald to archive Ironyx Vatminder

![image](https://github.com/keyteki/keyteki/assets/324548/ee97e9c9-57a6-4d22-9d11-a4c6df0b94e4)
