### ISSUE TITLE
WoE: Talent scout is not of the active house

### ISSUE THREAD

**Issue by dmikalova** [keyteki/keyteki#3262]
Played a test game where I played a talent scout. Later on my opponent could not use talent scout, but should be able to as if it was of the active house.

**Comment by OsramTaleka** [comment]
Having this same issue. It may be because I have 2 talent scouts?
![image](https://github.com/keyteki/keyteki/assets/53394971/5cbc8ded-9b0d-4ba7-a58a-82a1f547ca16)
