### ISSUE TITLE
Mimicry + Destroy them All

### ISSUE THREAD

**Issue by BrokenSteel** [keyteki/keyteki#327]
If you don't have an artifact/upgrade whichever goes first in the code. It just greys out the whole board and you can't select anything.

**Comment by romanogit** [comment]
![image](https://user-images.githubusercontent.com/2104075/71178402-e3078080-224c-11ea-9ed9-b655c4880ee0.png)

**Comment by romanogit** [comment]
I am unable to reproduce this issue. I tested different combinations and it does not happen. Please, reopen with game log.
