### ISSUE TITLE
Grumpus Tokens created during Endless Hordes Ignoring Taunt

### ISSUE THREAD

**Issue by OsramTaleka** [keyteki/keyteki#3270]
![image](https://github.com/keyteki/keyteki/assets/53394971/af2387ce-890d-408b-ab8b-161695c242ec)

Archonimizer brings D. Chafer, Malmadine’s Pensive Paladin to The Crucible
OsramTaleka brings Xena, Rampartish Crypt Thane to The Crucible
OsramTaleka won the flip and is first player
 Archonimizer has connected to the game server
 OsramTaleka has connected to the game server
Archonimizer is shuffling their deck
Archonimizer draws 6 card  s to their maximum of 6
OsramTaleka is shuffling their deck
OsramTaleka draws 6 card  s to their maximum of 6
OsramTaleka draws 1 card 
Key phase - OsramTaleka
OsramTaleka does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - OsramTaleka
OsramTaleka chooses dis  as their active house this turn
Main phase - OsramTaleka
OsramTaleka plays Sloth
Ready phase - OsramTaleka
OsramTaleka readies their cards 
Draw phase - OsramTaleka
OsramTaleka uses Sloth to gain 1 Æmber 
End of turn 1
Archonimizer: 0 Æmber  (0 keys) OsramTaleka: 1 Æmber  (0 keys)
TURN 1 - Archonimizer
Key phase - Archonimizer
Archonimizer does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Archonimizer
Archonimizer chooses brobnar  as their active house this turn
Main phase - Archonimizer
Archonimizer plays Rowdy Skald
Archonimizer deals 1 damage to Sloth due to Rowdy Skald's bonus icon
Archonimizer deals 1 damage to Sloth due to Rowdy Skald's bonus icon
Archonimizer plays Stratosmack
Archonimizer uses Stratosmack to deal 3 damage to Sloth
Ready phase - Archonimizer
Archonimizer readies their cards 
Draw phase - Archonimizer
Archonimizer draws 2 card  s to their maximum of 6
End of turn 1
Archonimizer: 0 Æmber  (0 keys) OsramTaleka: 1 Æmber  (0 keys)
TURN 2 - OsramTaleka
Key phase - OsramTaleka
OsramTaleka does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - OsramTaleka
OsramTaleka chooses saurian  as their active house this turn
Main phase - OsramTaleka
OsramTaleka plays Thero Centurion
OsramTaleka plays Blast from the Past
OsramTaleka uses Blast from the Past to exalt Thero Centurion
 OsramTaleka is attempting to switch manual mode on
 Archonimizer allows enabling manual mode
 OsramTaleka switches manual mode on
 OsramTaleka removes an Æmber  from Thero Centurion
 OsramTaleka switches manual mode off
Ready phase - OsramTaleka
OsramTaleka readies their cards 
Draw phase - OsramTaleka
OsramTaleka draws 2 card  s to their maximum of 6
End of turn 2
Archonimizer: 0 Æmber  (0 keys) OsramTaleka: 1 Æmber  (0 keys)
TURN 2 - Archonimizer
Key phase - Archonimizer
Archonimizer does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Archonimizer
Archonimizer chooses sanctum  as their active house this turn
Main phase - Archonimizer
Archonimizer plays Haedroth’s Wall
Archonimizer plays Colonel Mariana
Archonimizer uses Colonel Mariana to capture 1 Æmber  from their opponent , placing it on Colonel Mariana
Archonimizer plays Ostentatious Mount attaching it to Rowdy Skald
Archonimizer gains an Æmber  due to Ostentatious Mount's bonus icon
Archonimizer uses Ostentatious Mount to move Rowdy Skald and give it taunt
Ready phase - Archonimizer
Archonimizer readies their cards 
Draw phase - Archonimizer
Archonimizer draws 3 card  s to their maximum of 6
End of turn 2
Archonimizer: 1 Æmber  (0 keys) OsramTaleka: 0 Æmber  (0 keys)
TURN 3 - OsramTaleka
Key phase - OsramTaleka
OsramTaleka does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - OsramTaleka
OsramTaleka chooses sanctum  as their active house this turn
Main phase - OsramTaleka
OsramTaleka plays Potion of Invulnerability
OsramTaleka gains an Æmber  due to Potion of Invulnerability's bonus icon
OsramTaleka discards Cleansing Wave
OsramTaleka plays Shoulder Armor attaching it to Thero Centurion
OsramTaleka gains an Æmber  due to Shoulder Armor's bonus icon
Ready phase - OsramTaleka
OsramTaleka readies their cards 
Draw phase - OsramTaleka
OsramTaleka draws 3 card  s to their maximum of 6
End of turn 3
Archonimizer: 1 Æmber  (0 keys) OsramTaleka: 2 Æmber  (0 keys)
TURN 3 - Archonimizer
Key phase - Archonimizer
Archonimizer does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Archonimizer
Archonimizer chooses mars  as their active house this turn
Main phase - Archonimizer
Archonimizer discards Ammonia Clouds
Archonimizer plays Yxlyx Stimrager
Archonimizer plays Mk.2 Generator
Archonimizer uses Mk.2 Generator to make a token creature
Archonimizer discards Kaboom!
Archonimizer plays Ironyx Rebel
Archonimizer uses Ironyx Rebel to ready Yxlyx Stimrager and Grumpus
Archonimizer uses Yxlyx Stimrager to reap with Yxlyx Stimrager
Ready phase - Archonimizer
Archonimizer readies their cards 
Draw phase - Archonimizer
Archonimizer draws 5 card  s to their maximum of 6
End of turn 3
Archonimizer: 2 Æmber  (0 keys) OsramTaleka: 2 Æmber  (0 keys)
TURN 4 - OsramTaleka
Key phase - OsramTaleka
OsramTaleka does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - OsramTaleka
OsramTaleka chooses saurian  as their active house this turn
Main phase - OsramTaleka
OsramTaleka uses Thero Centurion to reap with Thero Centurion
OsramTaleka plays Umbra-Saurus
OsramTaleka plays Sacro-Saurus
OsramTaleka plays Spoils of Battle
OsramTaleka gains an Æmber  due to Spoils of Battle's bonus icon
OsramTaleka captures an Æmber  on Thero Centurion due to Spoils of Battle's bonus icon
OsramTaleka uses Spoils of Battle to capture 1 Æmber 
Ready phase - OsramTaleka
OsramTaleka readies their cards 
Draw phase - OsramTaleka
OsramTaleka draws 3 card  s to their maximum of 6
End of turn 4
Archonimizer: 0 Æmber  (0 keys) OsramTaleka: 3 Æmber  (0 keys)
TURN 4 - Archonimizer
Key phase - Archonimizer
Archonimizer does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Archonimizer
Archonimizer chooses mars  as their active house this turn
Main phase - Archonimizer
Archonimizer uses Yxlyx Stimrager to reap with Yxlyx Stimrager
Archonimizer uses Ironyx Rebel to reap with Ironyx Rebel
Archonimizer plays Tyxl Beambuckler
Archonimizer uses Tyxl Beambuckler to deal 2 damage to Umbra-Saurus and move it to a flank
Archonimizer plays Kaboom!
Archonimizer uses Kaboom! to do several things
Archonimizer plays Ether Spider
Archonimizer plays Ironyx Propaganda attaching it to Ether Spider
Archonimizer gains an Æmber  due to Ironyx Propaganda's bonus icon
Archonimizer uses Mk.2 Generator to make a token creature
Ready phase - Archonimizer
Archonimizer readies their cards 
Draw phase - Archonimizer
Archonimizer draws 3 card  s to their maximum of 6
Archonimizer's chains are reduced by 1 to 2
End of turn 4
Archonimizer: 5 Æmber  (0 keys) OsramTaleka: 5 Æmber  (0 keys)
TURN 5 - OsramTaleka
Key phase - OsramTaleka
OsramTaleka does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - OsramTaleka
OsramTaleka chooses dis  as their active house this turn
Main phase - OsramTaleka
OsramTaleka plays Mindfire
OsramTaleka uses Mindfire to discard a card  at random from Archonimizer's hand
Archonimizer discards Grey Abbess at random
OsramTaleka plays Pride
OsramTaleka plays Gluttony
OsramTaleka uses Gluttony to exalt Gluttony once for each friendly sin creature in play
Ready phase - OsramTaleka
OsramTaleka readies their cards 
Draw phase - OsramTaleka
OsramTaleka draws 3 card  s to their maximum of 6
End of turn 5
Archonimizer: 5 Æmber  (0 keys) OsramTaleka: 5 Æmber  (0 keys)
TURN 5 - Archonimizer
Key phase - Archonimizer
Archonimizer does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - Archonimizer
Archonimizer chooses brobnar  as their active house this turn
Main phase - Archonimizer
Archonimizer plays Crogg the Clumsy
Archonimizer uses Grumpus to reap with Grumpus
Archonimizer plays Shock Herder
Archonimizer draws a card  due to Shock Herder's bonus icon
Archonimizer uses Shock Herder to ready and fight with a neighboring creature
Archonimizer uses Crogg the Clumsy to make Crogg the Clumsy fight Gluttony
Ready phase - Archonimizer
Archonimizer readies their cards 
Draw phase - Archonimizer
Archonimizer draws 2 card  s to their maximum of 6
Archonimizer's chains are reduced by 1 to 1
 Archonimizer declares Check!
End of turn 5
Archonimizer: 8 Æmber  (0 keys) OsramTaleka: 5 Æmber  (0 keys)
TURN 6 - OsramTaleka
Key phase - OsramTaleka
OsramTaleka does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - OsramTaleka
OsramTaleka chooses saurian  as their active house this turn
Main phase - OsramTaleka
OsramTaleka plays Axiom of Grisk
OsramTaleka uses Axiom of Grisk to ward Pride, destroy all creatures without Æmber  and give OsramTaleka 2 chains
OsramTaleka uses Pride to remove its ward token
OsramTaleka discards Axiom of Grisk
OsramTaleka plays Defense Initiative
OsramTaleka uses Defense Initiative to ward Pride
Ready phase - OsramTaleka
OsramTaleka readies their cards 
Draw phase - OsramTaleka
OsramTaleka draws 2 card  s to their maximum of 6
OsramTaleka's chains are reduced by 1 to 1
End of turn 6
Archonimizer: 8 Æmber  (0 keys) OsramTaleka: 5 Æmber  (0 keys)
TURN 6 - Archonimizer
Key phase - Archonimizer
Archonimizer forges the blue key  , paying 6 Æmber 
House phase - Archonimizer
Archonimizer chooses mars  as their active house this turn
Archonimizer moves all the cards  in their archives to their hand
Main phase - Archonimizer
Archonimizer plays Tyxl Beambuckler
Archonimizer uses Tyxl Beambuckler to deal 2 damage to Pride and move it to a flank
Pride's ward token prevents the damage dealt by Tyxl Beambuckler and is discarded
Archonimizer plays Scoop Up
Archonimizer gains an Æmber  due to Scoop Up's bonus icon
Archonimizer uses Scoop Up to archive Pride
Archonimizer plays Yxlyx Stimrager
Archonimizer uses Mk.2 Generator to make a token creature
Archonimizer plays Ironyx Rebel
Archonimizer uses Ironyx Rebel to ready Tyxl Beambuckler and Yxlyx Stimrager
Archonimizer uses Tyxl Beambuckler to reap with Tyxl Beambuckler
Archonimizer uses Yxlyx Stimrager to reap with Yxlyx Stimrager
Ready phase - Archonimizer
Archonimizer readies their cards 
Draw phase - Archonimizer
Archonimizer draws 1 card  to their maximum of 6
Archonimizer's chains are reduced by 1 to 0
End of turn 6
Archonimizer: 5 Æmber  (1 key) OsramTaleka: 5 Æmber  (0 keys)
TURN 7 - OsramTaleka
Key phase - OsramTaleka
OsramTaleka does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - OsramTaleka
OsramTaleka chooses sanctum  as their active house this turn
Main phase - OsramTaleka
OsramTaleka plays Barrister Joya
OsramTaleka deals 1 damage to Grumpus due to Barrister Joya's bonus icon
OsramTaleka plays Æmberheart
OsramTaleka plays Armageddon Cloak attaching it to Barrister Joya
OsramTaleka gains an Æmber  due to Armageddon Cloak's bonus icon
Ready phase - OsramTaleka
OsramTaleka readies their cards 
Draw phase - OsramTaleka
OsramTaleka draws 3 card  s to their maximum of 6
OsramTaleka's chains are reduced by 1 to 0
 OsramTaleka declares Check!
End of turn 7
Archonimizer: 5 Æmber  (1 key) OsramTaleka: 6 Æmber  (0 keys)
TURN 7 - Archonimizer
Key phase - Archonimizer
Archonimizer does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - Archonimizer
Archonimizer chooses mars  as their active house this turn
Main phase - Archonimizer
Archonimizer uses Yxlyx Stimrager to make Yxlyx Stimrager fight Barrister Joya
OsramTaleka uses Barrister Joya to deal 2 damage to Yxlyx Stimrager
OsramTaleka uses Barrister Joya to heal all damage from Barrister Joya and destroy Armageddon Cloak instead
Archonimizer uses Yxlyx Stimrager to deal 2 damage to Barrister Joya and move it to a flank
Archonimizer uses Tyxl Beambuckler to make Tyxl Beambuckler fight Barrister Joya
Archonimizer uses Ironyx Rebel to reap with Ironyx Rebel
Archonimizer uses Mk.2 Generator to make a token creature
Ready phase - Archonimizer
Archonimizer readies their cards 
Draw phase - Archonimizer
Archonimizer draws 1 card  to their maximum of 6
 Archonimizer declares Check!
End of turn 7
Archonimizer: 6 Æmber  (1 key) OsramTaleka: 6 Æmber  (0 keys)
TURN 8 - OsramTaleka
Key phase - OsramTaleka
OsramTaleka forges the yellow key  , paying 6 Æmber 
House phase - OsramTaleka
OsramTaleka chooses dis  as their active house this turn
Main phase - OsramTaleka
OsramTaleka plays Wrath
OsramTaleka plays Desire
OsramTaleka plays Greed
Ready phase - OsramTaleka
OsramTaleka readies their cards 
Draw phase - OsramTaleka
OsramTaleka draws 7 card  s to their maximum of 9
End of turn 8
Archonimizer: 6 Æmber  (1 key) OsramTaleka: 0 Æmber  (1 key)
TURN 8 - Archonimizer
Key phase - Archonimizer
Archonimizer does not forge a key. They have 6 amber. The current cost is 10 Æmber 
House phase - Archonimizer
Archonimizer chooses sanctum  as their active house this turn
Main phase - Archonimizer
Archonimizer plays Lightbringer Outpost
Archonimizer gains an Æmber  due to Lightbringer Outpost's bonus icon
Archonimizer plays Lightbringer Outpost
Archonimizer gains an Æmber  due to Lightbringer Outpost's bonus icon
Archonimizer plays Ostentatious Mount attaching it to Ironyx Rebel
Archonimizer gains an Æmber  due to Ostentatious Mount's bonus icon
Archonimizer uses Ostentatious Mount to move Ironyx Rebel and give it taunt
Archonimizer plays Friendship attaching it to Grumpus
Archonimizer gains an Æmber  due to Friendship's bonus icon
Ready phase - Archonimizer
Archonimizer readies their cards 
Draw phase - Archonimizer
Archonimizer draws 4 card  s to their maximum of 6
 Archonimizer declares Check!
End of turn 8
Archonimizer: 10 Æmber  (1 key) OsramTaleka: 0 Æmber  (1 key)
TURN 9 - OsramTaleka
Key phase - OsramTaleka
OsramTaleka does not forge a key. They have 0 amber. The current cost is 10 Æmber 
House phase - OsramTaleka
OsramTaleka chooses sanctum  as their active house this turn
Main phase - OsramTaleka
OsramTaleka plays Font of the Eye
OsramTaleka uses Æmberheart to exalt, ward and fully heal Desire
OsramTaleka plays Armageddon Cloak attaching it to Desire
OsramTaleka gains an Æmber  due to Armageddon Cloak's bonus icon
OsramTaleka plays General Xalvador
OsramTaleka plays The Grey Rider
OsramTaleka uses The Grey Rider to ready and fight with a neighboring creature
OsramTaleka uses Wrath to make Wrath fight Ironyx Rebel
OsramTaleka uses Wrath to enrage Grumpus, Yxlyx Stimrager, and Grumpus
Ready phase - OsramTaleka
OsramTaleka readies their cards 
Draw phase - OsramTaleka
OsramTaleka draws 4 card  s to their maximum of 9
End of turn 9
Archonimizer: 10 Æmber  (1 key) OsramTaleka: 1 Æmber  (1 key)
TURN 9 - Archonimizer
Key phase - Archonimizer
Archonimizer forges the yellow key  , paying 10 Æmber 
House phase - Archonimizer
Archonimizer chooses brobnar  as their active house this turn
Main phase - Archonimizer
Archonimizer plays Might Club
Archonimizer plays Flamethrower
Archonimizer plays Endless Hordes
Archonimizer uses Endless Hordes to make 5 token creatures
Archonimizer uses Grumpus to make Grumpus fight Wrath
Desire's ward token prevents the damage dealt by Grumpus and is discarded
Archonimizer uses Grumpus to make Grumpus fight The Grey Rider
Archonimizer uses Grumpus to make Grumpus fight Desire
OsramTaleka uses Desire to deal 2 damage to Grumpus
OsramTaleka uses Desire to heal all damage from Desire and destroy Armageddon Cloak instead

**Comment by strib** [comment]
The card says that they should ignore taunt during the Endless Hordes fight.  Seems correct to me, unless they were still ignoring taunt after Endless Hordes completed.

![image](https://github.com/keyteki/keyteki/assets/8516691/8dad0d0d-1035-46d7-bbd6-d2e4466ece0c)

**Comment by OsramTaleka** [comment]
You're right! This was my first time dealing with taunt and this card and my eyes skipped over that.
