### ISSUE TITLE
Aquilia, Lone Hero using Omni ability after being used to fight

### ISSUE THREAD

**Issue by OsramTaleka** [keyteki/keyteki#3271]
![image](https://github.com/keyteki/keyteki/assets/53394971/c9a406c9-6a86-4503-beb2-e5d2de0ddaf3)

I played Aquilia, used Symposium (Which might have caused the issue) to ready it and use it to fight. After the fight, Aquilia captured 1 as though it had used its Omni ability.

Archonimizer brings Cedarskull, the “Minister” of Pickpockets to The Crucible
OsramTaleka brings Xena, Rampartish Crypt Thane to The Crucible
OsramTaleka won the flip and is first player
 OsramTaleka has connected to the game server
 Archonimizer has connected to the game server
Archonimizer is shuffling their deck
Archonimizer draws 6 card  s to their maximum of 6
OsramTaleka is shuffling their deck
OsramTaleka draws 6 card  s to their maximum of 6
OsramTaleka draws 1 card 
Key phase - OsramTaleka
OsramTaleka does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - OsramTaleka
OsramTaleka chooses dis  as their active house this turn
Main phase - OsramTaleka
OsramTaleka plays Wrath
Ready phase - OsramTaleka
OsramTaleka readies their cards 
Draw phase - OsramTaleka
End of turn 1
Archonimizer: 0 Æmber  (0 keys) OsramTaleka: 0 Æmber  (0 keys)
TURN 1 - Archonimizer
Key phase - Archonimizer
Archonimizer does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Archonimizer
Archonimizer chooses mars  as their active house this turn
Main phase - Archonimizer
Archonimizer plays Ironyx Vatminder
Archonimizer uses Ironyx Vatminder to make a token creature
Archonimizer plays Mars Needs Æmber
Archonimizer gains an Æmber  due to Mars Needs Æmber's bonus icon
Archonimizer plays Mars Needs Æmber
Archonimizer gains an Æmber  due to Mars Needs Æmber's bonus icon
Archonimizer deals 1 damage to Wrath due to Mars Needs Æmber's bonus icon
Archonimizer plays Glylyx Weaponsmith
Ready phase - Archonimizer
Archonimizer readies their cards 
Draw phase - Archonimizer
Archonimizer draws 4 card  s to their maximum of 6
End of turn 1
Archonimizer: 2 Æmber  (0 keys) OsramTaleka: 0 Æmber  (0 keys)
TURN 2 - OsramTaleka
Key phase - OsramTaleka
OsramTaleka does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - OsramTaleka
OsramTaleka chooses saurian  as their active house this turn
Main phase - OsramTaleka
OsramTaleka plays Beware the Ides
OsramTaleka gains an Æmber  due to Beware the Ides's bonus icon
OsramTaleka uses Beware the Ides to deal 23 damage to Ironyx Vatminder
Archonimizer uses Ironyx Vatminder to make a token creature
OsramTaleka plays Umbra-Saurus
 OsramTaleka is attempting to switch manual mode on
 Archonimizer allows enabling manual mode
 OsramTaleka switches manual mode on
 OsramTaleka manually moves Diplo-Macy from their hand to their discard
 OsramTaleka sets Æmber  to 2 ( +1 )
 OsramTaleka switches manual mode off
Ready phase - OsramTaleka
OsramTaleka readies their cards 
Draw phase - OsramTaleka
OsramTaleka draws 3 card  s to their maximum of 6
End of turn 2
Archonimizer: 2 Æmber  (0 keys) OsramTaleka: 2 Æmber  (0 keys)
TURN 2 - Archonimizer
Key phase - Archonimizer
Archonimizer does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - Archonimizer
Archonimizer chooses saurian  as their active house this turn
Main phase - Archonimizer
Archonimizer plays Pale Into Insignificance
Archonimizer gains an Æmber  due to Pale Into Insignificance's bonus icon
Archonimizer draws a card  due to Pale Into Insignificance's bonus icon
Archonimizer uses Pale Into Insignificance to destroy Wrath
Archonimizer discards Crushing Charge
Archonimizer uses Bellatoran Warrior to reap with Bellatoran Warrior
Ready phase - Archonimizer
Archonimizer readies their cards 
Draw phase - Archonimizer
Archonimizer draws 1 card  to their maximum of 6
End of turn 2
Archonimizer: 4 Æmber  (0 keys) OsramTaleka: 2 Æmber  (0 keys)
TURN 3 - OsramTaleka
Key phase - OsramTaleka
OsramTaleka does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - OsramTaleka
OsramTaleka chooses sanctum  as their active house this turn
Main phase - OsramTaleka
OsramTaleka plays Burning Glare
OsramTaleka gains an Æmber  due to Burning Glare's bonus icon
OsramTaleka chooses option ' Stun an enemy creature '
OsramTaleka uses Burning Glare to stun Bellatoran Warrior
OsramTaleka plays General Xalvador
OsramTaleka plays Potion of Invulnerability
OsramTaleka gains an Æmber  due to Potion of Invulnerability's bonus icon
OsramTaleka plays Armageddon Cloak attaching it to General Xalvador
OsramTaleka gains an Æmber  due to Armageddon Cloak's bonus icon
Ready phase - OsramTaleka
OsramTaleka readies their cards 
Draw phase - OsramTaleka
OsramTaleka draws 4 card  s to their maximum of 6
End of turn 3
Archonimizer: 4 Æmber  (0 keys) OsramTaleka: 5 Æmber  (0 keys)
TURN 3 - Archonimizer
Key phase - Archonimizer
Archonimizer does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - Archonimizer
Archonimizer chooses unfathomable  as their active house this turn
Main phase - Archonimizer
Archonimizer plays Soleft
Archonimizer deals 1 damage to Umbra-Saurus due to Soleft's bonus icon
Archonimizer plays Skullback Crab
Archonimizer captures an Æmber  on Bellatoran Warrior due to Skullback Crab's bonus icon
Archonimizer draws a card  due to Skullback Crab's bonus icon
Archonimizer plays Toxicuda Venom attaching it to Glylyx Weaponsmith
Archonimizer gains an Æmber  due to Toxicuda Venom's bonus icon
Archonimizer captures an Æmber  on Glylyx Weaponsmith due to Toxicuda Venom's bonus icon
Archonimizer discards Whirlpool
Ready phase - Archonimizer
Archonimizer readies their cards 
Draw phase - Archonimizer
Archonimizer draws 3 card  s to their maximum of 6
End of turn 3
Archonimizer: 5 Æmber  (0 keys) OsramTaleka: 3 Æmber  (0 keys)
TURN 4 - OsramTaleka
Key phase - OsramTaleka
OsramTaleka does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - OsramTaleka
OsramTaleka chooses dis  as their active house this turn
Main phase - OsramTaleka
OsramTaleka plays Imp-losion
OsramTaleka gains an Æmber  due to Imp-losion's bonus icon
OsramTaleka uses Imp-losion to destroy Umbra-Saurus and Glylyx Weaponsmith
OsramTaleka plays Snarette
OsramTaleka plays Soulkeeper attaching it to Snarette
OsramTaleka gains an Æmber  due to Soulkeeper's bonus icon
Ready phase - OsramTaleka
OsramTaleka readies their cards 
Draw phase - OsramTaleka
OsramTaleka draws 3 card  s to their maximum of 6
OsramTaleka uses Snarette to capture 1 Æmber  from their opponent , placing it on Snarette
 OsramTaleka declares Check!
End of turn 4
Archonimizer: 4 Æmber  (0 keys) OsramTaleka: 6 Æmber  (0 keys)
TURN 4 - Archonimizer
Key phase - Archonimizer
Archonimizer does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - Archonimizer
Archonimizer chooses mars  as their active house this turn
Main phase - Archonimizer
Archonimizer plays Mars Needs Æmber
Archonimizer gains an Æmber  due to Mars Needs Æmber's bonus icon
Archonimizer plays Yxlix Mesmerist
Archonimizer plays Myx, the Tallminded
Archonimizer plays Ironyx Rebel
Archonimizer uses Ironyx Rebel to ready Yxlix Mesmerist and Myx, the Tallminded
Archonimizer uses Yxlix Mesmerist to capture 1 Æmber  from OsramTaleka, placing it on Snarette
Archonimizer uses Myx, the Tallminded to make Myx, the Tallminded fight Snarette
OsramTaleka uses Snarette to destroy Bellatoran Warrior
Ready phase - Archonimizer
Archonimizer readies their cards 
Draw phase - Archonimizer
Archonimizer draws 4 card  s to their maximum of 6
 Archonimizer declares Check!
End of turn 4
Archonimizer: 7 Æmber  (0 keys) OsramTaleka: 5 Æmber  (0 keys)
TURN 5 - OsramTaleka
Key phase - OsramTaleka
OsramTaleka does not forge a key. They have 5 amber. The current cost is 9 Æmber 
House phase - OsramTaleka
OsramTaleka chooses saurian  as their active house this turn
Main phase - OsramTaleka
OsramTaleka plays Axiom of Grisk
OsramTaleka uses Axiom of Grisk to ward General Xalvador, destroy all creatures without Æmber  and give OsramTaleka 2 chains
OsramTaleka uses General Xalvador to remove its ward token
Archonimizer uses Soleft to destroy General Xalvador
OsramTaleka uses General Xalvador to heal all damage from General Xalvador and destroy Armageddon Cloak instead
OsramTaleka plays Blast from the Past
OsramTaleka captures an Æmber  on General Xalvador due to Blast from the Past's bonus icon
OsramTaleka uses Blast from the Past to exalt General Xalvador
OsramTaleka uses Blast from the Past to archive Umbra-Saurus
OsramTaleka uses Blast from the Past to deal 4 damage to Bellatoran Warrior
OsramTaleka uses Potion of Invulnerability to sacrifice Potion of Invulnerability so that their creatures take no damage this turn
Ready phase - OsramTaleka
OsramTaleka readies their cards 
Draw phase - OsramTaleka
OsramTaleka draws 1 card  to their maximum of 6
OsramTaleka's chains are reduced by 1 to 1
End of turn 5
Archonimizer: 6 Æmber  (0 keys) OsramTaleka: 5 Æmber  (0 keys)
TURN 5 - Archonimizer
Key phase - Archonimizer
Archonimizer forges the yellow key  , paying 6 Æmber 
House phase - Archonimizer
Archonimizer chooses saurian  as their active house this turn
Main phase - Archonimizer
Archonimizer exhausts Bellatoran Warrior to remove its stun
Archonimizer plays Crushing Charge
Archonimizer uses Crushing Charge to destroy each creature with power 4 or lower and gain 1 chain
Ready phase - Archonimizer
Archonimizer readies their cards 
Draw phase - Archonimizer
Archonimizer's chains are reduced by 1 to 0
End of turn 5
Archonimizer: 2 Æmber  (1 key) OsramTaleka: 5 Æmber  (0 keys)
TURN 6 - OsramTaleka
Key phase - OsramTaleka
OsramTaleka does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - OsramTaleka
OsramTaleka chooses dis  as their active house this turn
Main phase - OsramTaleka
OsramTaleka plays Stirring Grave
OsramTaleka gains an Æmber  due to Stirring Grave's bonus icon
OsramTaleka uses Stirring Grave to archive Snarette
OsramTaleka plays Greed
Ready phase - OsramTaleka
OsramTaleka readies their cards 
Draw phase - OsramTaleka
OsramTaleka draws 3 card  s to their maximum of 7
OsramTaleka's chains are reduced by 1 to 0
 OsramTaleka declares Check!
End of turn 6
Archonimizer: 2 Æmber  (1 key) OsramTaleka: 6 Æmber  (0 keys)
TURN 6 - Archonimizer
Key phase - Archonimizer
Archonimizer does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - Archonimizer
Archonimizer chooses unfathomable  as their active house this turn
Main phase - Archonimizer
Archonimizer plays Flounderight
Archonimizer draws a card  due to Flounderight's bonus icon
Archonimizer plays Stir-Crazy
Archonimizer gains an Æmber  due to Stir-Crazy's bonus icon
Archonimizer uses Stir-Crazy to cause each ready creature to capture 1 Æmber  from their opponent
Archonimizer plays Crushing Deep
Archonimizer gains an Æmber  due to Crushing Deep's bonus icon
Archonimizer uses Crushing Deep to increase key cost by 3 for each forged key they have during OsramTaleka's next turn
Archonimizer plays Azure Basin Outpost
Archonimizer gains an Æmber  due to Azure Basin Outpost's bonus icon
Ready phase - Archonimizer
Archonimizer readies their cards 
Draw phase - Archonimizer
Archonimizer draws 4 card  s to their maximum of 6
End of turn 6
Archonimizer: 4 Æmber  (1 key) OsramTaleka: 5 Æmber  (0 keys)
TURN 7 - OsramTaleka
Key phase - OsramTaleka
OsramTaleka does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - OsramTaleka
OsramTaleka chooses sanctum  as their active house this turn
Main phase - OsramTaleka
OsramTaleka plays Barrister Joya
OsramTaleka deals 1 damage to Bellatoran Warrior due to Barrister Joya's bonus icon
 OsramTaleka has disconnected. The game will wait up to 30 seconds for them to reconnect
 OsramTaleka has reconnected
 OsramTaleka has connected to the game server
OsramTaleka plays Font of the Eye
OsramTaleka plays Æmberheart
Ready phase - OsramTaleka
OsramTaleka readies their cards 
Draw phase - OsramTaleka
OsramTaleka draws 4 card  s to their maximum of 7
 OsramTaleka declares Check!
End of turn 7
Archonimizer: 4 Æmber  (1 key) OsramTaleka: 7 Æmber  (0 keys)
TURN 7 - Archonimizer
Key phase - Archonimizer
Archonimizer does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - Archonimizer
Archonimizer chooses saurian  as their active house this turn
Main phase - Archonimizer
Archonimizer plays Ankylo Formation
Archonimizer gains an Æmber  due to Ankylo Formation's bonus icon
Archonimizer chooses option ' Skirmish '
Archonimizer uses Ankylo Formation to apply a lasting effect to Flounderight
Archonimizer plays Pale Into Insignificance
Archonimizer gains an Æmber  due to Pale Into Insignificance's bonus icon
Archonimizer uses Pale Into Insignificance to destroy Flounderight
Archonimizer uses Flounderight to destroy Greed
Archonimizer plays Æmbrosia Outpost
Archonimizer gains an Æmber  due to Æmbrosia Outpost's bonus icon
Archonimizer deals 1 damage to Barrister Joya due to Æmbrosia Outpost's bonus icon
Ready phase - Archonimizer
Archonimizer readies their cards 
Draw phase - Archonimizer
Archonimizer draws 3 card  s to their maximum of 6
 Archonimizer declares Check!
End of turn 7
Archonimizer: 8 Æmber  (1 key) OsramTaleka: 7 Æmber  (0 keys)
TURN 8 - OsramTaleka
Key phase - OsramTaleka
OsramTaleka forges the yellow key  , paying 6 Æmber 
House phase - OsramTaleka
OsramTaleka chooses saurian  as their active house this turn
Main phase - OsramTaleka
OsramTaleka plays Thero Centurion
OsramTaleka uses Thero Centurion to capture 1 Æmber  from their opponent , placing it on Thero Centurion
OsramTaleka plays Sacro-Saurus
OsramTaleka plays Defense Initiative
OsramTaleka uses Defense Initiative to ward Thero Centurion
OsramTaleka plays Spoils of Battle
OsramTaleka gains an Æmber  due to Spoils of Battle's bonus icon
OsramTaleka captures an Æmber  on Sacro-Saurus due to Spoils of Battle's bonus icon
OsramTaleka uses Spoils of Battle to capture 1 Æmber 
OsramTaleka plays Cornicen Octavia
OsramTaleka plays Galeatops
Ready phase - OsramTaleka
OsramTaleka readies their cards 
Draw phase - OsramTaleka
OsramTaleka draws 5 card  s to their maximum of 6
End of turn 8
Archonimizer: 2 Æmber  (1 key) OsramTaleka: 2 Æmber  (1 key)
TURN 8 - Archonimizer
Key phase - Archonimizer
Archonimizer does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - Archonimizer
Archonimizer chooses saurian  as their active house this turn
Main phase - Archonimizer
Archonimizer plays Aquilia, Lone Hero
Archonimizer plays Aquilia, Lone Hero
Archonimizer plays Symposium
Archonimizer uses Symposium to do several things
Archonimizer uses Aquilia, Lone Hero to make Aquilia, Lone Hero fight Barrister Joya
Barrister Joya's ward token prevents the damage dealt by Aquilia, Lone Hero and is discarded
Archonimizer uses Æmbrosia Outpost to return Aquilia, Lone Hero to the bottom of their owner's deck
Ready phase - Archonimizer
Archonimizer readies their cards 
Draw phase - Archonimizer
Archonimizer draws 3 card  s to their maximum of 6
End of turn 8
Archonimizer: 3 Æmber  (1 key) OsramTaleka: 2 Æmber  (1 key)
TURN 9 - OsramTaleka
Key phase - OsramTaleka
OsramTaleka does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - OsramTaleka

**Comment by strib** [comment]
> Archonimizer: 2 Æmber (1 key) OsramTaleka: 2 Æmber (1 key)
> TURN 8 - Archonimizer

And then:

> Archonimizer: 3 Æmber (1 key) OsramTaleka: 2 Æmber (1 key)
> TURN 9 - OsramTaleka

Looks like `OsramTaleka` didn't lose any amber during `Archonimizer`'s turn.  Are you sure that the amber on Aquila wasn't just the exalt from Symposium?

**Comment by OsramTaleka** [comment]
O yes so sorry!
