### ISSUE TITLE
Extrematode Infection not destroying creature after last counter removed

### ISSUE THREAD

**Issue by DylanGranger** [keyteki/keyteki#3278]
![Screenshot 2023-06-20 3 46 33 PM](https://github.com/keyteki/keyteki/assets/34193643/f01252b4-cd3c-435f-b458-1283698369fc)

Full game log below, tokens are correctly made and then the upgrade is destroyed but the original creature remains. In test game I played the thrax, attached the upgrade, then passed three turns. Log below:

Fabulosing brings Iyapo, Changeling of the Vorpal Cliff to The Crucible
Fabulousing brings Fabulousing of Earthself to The Crucible
 Fabulousing has connected to the game server
 Fabulosing has connected to the game server
Fabulousing chooses to go first
Fabulosing is shuffling their deck
Fabulosing draws 6 card  s to their maximum of 6
Fabulousing is shuffling their deck
Fabulousing draws 6 card  s to their maximum of 6
Fabulousing draws 1 card 
Key phase - Fabulousing
Fabulousing does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Fabulousing
 Fabulousing is attempting to switch manual mode on
 Fabulosing allows enabling manual mode
 Fabulousing switches manual mode on
 Fabulousing manually moves Extrematode Infection from their deck to their hand
 Fabulousing switches manual mode off
Fabulousing chooses saurian  as their active house this turn
Main phase - Fabulousing
Fabulousing plays Grammaticus Thrax
Ready phase - Fabulousing
Fabulousing readies their cards 
Draw phase - Fabulousing
End of turn 1
Fabulosing: 0 Æmber  (0 keys) Fabulousing: 0 Æmber  (0 keys)
TURN 1 - Fabulosing
Key phase - Fabulosing
Fabulosing does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Fabulosing
Fabulosing chooses dis  as their active house this turn
Main phase - Fabulosing
Ready phase - Fabulosing
Draw phase - Fabulosing
End of turn 1
Fabulosing: 0 Æmber  (0 keys) Fabulousing: 0 Æmber  (0 keys)
TURN 2 - Fabulousing
Key phase - Fabulousing
Fabulousing does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Fabulousing
Fabulousing chooses unfathomable  as their active house this turn
Main phase - Fabulousing
Fabulousing plays Extrematode Infection attaching it to Grammaticus Thrax
Fabulousing gains an Æmber  due to Extrematode Infection's bonus icon
Fabulousing uses Extrematode Infection to put 3 hatch counters on Extrematode Infection
Ready phase - Fabulousing
Fabulousing readies their cards 
Draw phase - Fabulousing
End of turn 2
Fabulosing: 0 Æmber  (0 keys) Fabulousing: 1 Æmber  (0 keys)
TURN 2 - Fabulosing
Key phase - Fabulosing
Fabulosing does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Fabulosing
Fabulosing chooses dis  as their active house this turn
Main phase - Fabulosing
Ready phase - Fabulosing
Draw phase - Fabulosing
End of turn 2
Fabulosing: 0 Æmber  (0 keys) Fabulousing: 1 Æmber  (0 keys)
TURN 3 - Fabulousing
Fabulousing uses Extrematode Infection to remove 1 hatch from Extrematode Infection
Key phase - Fabulousing
Fabulousing does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Fabulousing
Fabulousing chooses saurian  as their active house this turn
Main phase - Fabulousing
Ready phase - Fabulousing
Fabulousing readies their cards 
Draw phase - Fabulousing
End of turn 3
Fabulosing: 0 Æmber  (0 keys) Fabulousing: 1 Æmber  (0 keys)
TURN 3 - Fabulosing
Key phase - Fabulosing
Fabulosing does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Fabulosing
Fabulosing chooses logos  as their active house this turn
Main phase - Fabulosing
Ready phase - Fabulosing
Draw phase - Fabulosing
End of turn 3
Fabulosing: 0 Æmber  (0 keys) Fabulousing: 1 Æmber  (0 keys)
TURN 4 - Fabulousing
Fabulousing uses Extrematode Infection to remove 1 hatch from Extrematode Infection
Key phase - Fabulousing
Fabulousing does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Fabulousing
Fabulousing chooses unfathomable  as their active house this turn
Main phase - Fabulousing
Ready phase - Fabulousing
Fabulousing readies their cards 
Draw phase - Fabulousing
End of turn 4
Fabulosing: 0 Æmber  (0 keys) Fabulousing: 1 Æmber  (0 keys)
TURN 4 - Fabulosing
Key phase - Fabulosing
Fabulosing does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Fabulosing
Fabulosing chooses logos  as their active house this turn
Main phase - Fabulosing
Ready phase - Fabulosing
Draw phase - Fabulosing
End of turn 4
Fabulosing: 0 Æmber  (0 keys) Fabulousing: 1 Æmber  (0 keys)
TURN 5 - Fabulousing
Fabulousing uses Extrematode Infection to remove 1 hatch from Extrematode Infection
Key phase - Fabulousing
Fabulousing does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Fabulousing

**Comment by romanogit** [comment]
Yes, noticed it was destroying only the upgrade, fixed.
