### ISSUE TITLE
WoE: token UI changes

### ISSUE THREAD

**Issue by alifeee** [keyteki/keyteki#3286]
## token use prompt

When a token creature is used, it shows the underneath card in the prompt. This can be confusing when using cards like [Symposium](https://archonarcana.com/Symposium)

![image](https://github.com/keyteki/keyteki/assets/13833017/21cca2f2-ac84-4b6d-aabc-b7728344bfc9)

## token power/armor

..is offset

![image](https://github.com/keyteki/keyteki/assets/13833017/33a6c953-d2c6-4fde-9503-fdbee0102c48)

**Comment by romanogit** [comment]
close?
