### ISSUE TITLE
Shopping Spree + Cursed Relic

### ISSUE THREAD

**Issue by KMarch82** [keyteki/keyteki#3294]
Opponent played Shopping Spree and the card discarded 2 cards from hand, but didn't allow them to discard Cursed Relic. In addition, they didn't draw 2 cards for the discarded cards.

**Comment by kensterel** [comment]
The same issue happens with Cursed Relic + Trade Secrets

**Comment by FlamingHobo** [comment]
Had a similar issue. Used Shizyoku buggy to discard cursed relic and another ekwidon card. Still got the token creature for satisfying buggy effect, but cursed relic stayed in hand
