### ISSUE TITLE
WoE: Sandhopper highlights backs of cards in opponents hand

### ISSUE THREAD

**Issue by dmikalova** [keyteki/keyteki#3297]
My opponent played a sandhopper and it highlighted the creature cards in my hand, wasn't able to test it but it seemed like they would be able to select a card from my hand.

![image](https://github.com/keyteki/keyteki/assets/324548/d2ced53d-2a77-4c72-9930-c1f8edfb132c)

**Comment by KMarch82** [comment]
I also had an issue w/ Sandhopper, though not this one. I used it to pull back a token, but didn't have any creatures to play. There was no prompt ability except for showing me the back of my opponent's cards. I chose one and it played a creature from their hand.
