### ISSUE TITLE
WoE: Stratosmack does not make token exchanged creature

### ISSUE THREAD

**Issue by dmikalova** [keyteki/keyteki#3298]
One turn I play an exchange program and give my opponent a 3 power creature. Next turn I stratosmack that creature and destroy it, but it did not create a token.

**Comment by strib** [comment]
Are you sure there was a card in the deck to make a token with?  I added a test for this in #3304 but it seems to work fine.

**Comment by dmikalova** [comment]
Yes - I manual moded and pulled back stratosmack and played it again on another creature and it then made a token. Can you try in the test a regular creature instead of a token creature? I exchanged suzyanne in my game.

**Comment by strib** [comment]
Yeah I added a test for a non-token exchanged creature and it also works fine.  If you can reproduce it, can you please add screenshots/logs to this issue?

**Comment by dmikalova** [comment]
I tried testing this out with the same deck and it seems to work.
