### ISSUE TITLE
WoE: researcher effect doesn't work after first use

### ISSUE THREAD

**Issue by dmikalova** [keyteki/keyteki#3299]
My opponent had some researcher tokens. The first time they used the omni ability it allowed them to archive a mars card. The next researcher omni ability they used did not do anything, even with a mars card in hand. The next turn, their researcher's omni ability continued to do nothing.

![image](https://github.com/keyteki/keyteki/assets/324548/d00523a5-6e44-4949-a7f3-3fa983eaf1a5)

**Comment by drsheep422** [comment]
researcher seems to currently be only allowing archiving of mars creatures.  Is it using feeding pit logic?

**Comment by strib** [comment]
Yes this is fixed in the code and waiting for the next deploy.
