### ISSUE TITLE
Aristotlmimus issue

### ISSUE THREAD

**Issue by Rikuns** [keyteki/keyteki#3308]
I reaped with Aristotlmimus (while there is no Wisdom counter on it), it let me play a card in my archive. But after played, that card still remain in my archive.

**Comment by strib** [comment]
I made #3310 to test that both creatures and actions are played correctly from the archives and go to the right zone after.  Can you give more detail about which card you played, and I can try an exact test for it?

**Comment by Rikuns** [comment]
> 

It's Hire On. I forgot to take a screenshot but that happened 2 times in the same game.

**Comment by strib** [comment]
But Hire On is supposed to go back into your archives if the amber count is correct.  Are you saying the combined amber count was less than 6 each time this happened?

**Comment by Rikuns** [comment]
Yes
