### ISSUE TITLE
Creatures from Replay Pod can take infinite damage

### ISSUE THREAD

**Issue by sdsantos** [keyteki/keyteki#3311]
Board state + chat:

<img width="1280" alt="Screenshot 2023-06-21 at 21 33 54" src="https://github.com/keyteki/keyteki/assets/106415/0db4b1b0-c9f1-44b2-9484-86853c856b87">

Red alert did not kill the mars creatures I had played 2 turns ago with Replay Pod. Just the mars creatures I had already in hand.

**Comment by strib** [comment]
This will probably also be fixed by #3312 -- the cards were probably still marked as destroyed/moribund from their previous time in the play area.
