### ISSUE TITLE
Sometimes tokens are displayed with their actual card art

### ISSUE THREAD

**Issue by agrandstudent** [keyteki/keyteki#3314]
![token bug](https://github.com/keyteki/keyteki/assets/6394071/d34e83c9-a774-4496-913f-fbbd76eedcaf)
Sorry I didnt save the game log.  
The two creatures in my battle line should look like the berserker token but instead were shown as the card they actually were.  I dont know if my opponent saw that as well.

**Comment by dmikalova** [comment]
I also saw opponent token cards when destroying a bunch of tokens with destroy effects - I don't believe I can see the cards until after destroyed effects proc.

![image](https://github.com/keyteki/keyteki/assets/324548/1d8eaf71-d9f0-4b62-a546-13a1c363b90e)

**Comment by romanogit** [comment]
different root causes
