### ISSUE TITLE
WoE: Aemberlings don't always get norbyn's cavern effect

### ISSUE THREAD

**Issue by dmikalova** [keyteki/keyteki#3318]
My opponent played a norbyn's cavern, and aemberlings gained the power as expected. Next turn my opponent forged a key, but did not use the existing aemberlings as part of the cost. The next aemberling that my opponent made did not have the extra power as expected.

![image](https://github.com/keyteki/keyteki/assets/324548/13537358-d95d-4308-92f4-8762e2b51b23)

**Comment by strib** [comment]
Did it die to one damage, or could it have been just a visual issue?

**Comment by dmikalova** [comment]
I'm not sure, I didn't have a chance to try.

**Comment by romanogit** [comment]
I think this is a visual problem that is fixed by https://github.com/keyteki/keyteki/pull/3457
