### ISSUE TITLE
Might Makes Right doesn't work

### ISSUE THREAD

**Issue by Fabri972** [keyteki/keyteki#332]
When i have creatures with 25 or more power in table and i use might makes right it makes me select creatures and makes me sacrifice them but it doesn't make me forge the key

**Comment by Achocholacek** [comment]
I cannot reproduce this - do you remember anything else about board state?

**Comment by Fabri972** [comment]
Yes i have 5 creatures and the total of their power is exactly 25 anf i use
might makes right, i sacrifice all the creatures but i don't forged the key

Il Gio 15 Ago 2019, 19:43 Achocholacek <notifications@github.com> ha
scritto:

**Comment by Achocholacek** [comment]
Do you remember the creatures? Do you remember any other cards in play?

**Comment by Fabri972** [comment]
No i don't remamber, but i use the card in 3 different duels and in all i
had a total power of 25 and the card didn't work :/. I try to use in a new
duel and watch if woks.

Il Gio 15 Ago 2019, 19:52 Achocholacek <notifications@github.com> ha
scritto:

**Comment by lupo82** [comment]
It happened to me too. I think the problem is the damage on the creature and other effects that modifies the creatures power. I remember one time it failed sacrificing a marmo swarm, I thought it didn't count the modifiers due to the aember
