### ISSUE TITLE
WoE: creature previously a researcher token retains omni

### ISSUE THREAD

**Issue by dmikalova** [keyteki/keyteki#3323]
For some reason I was able to use a bumpsy while in Mars - the game let me select bumpsy, but it got used without doing anything. It appears as though it was previously tokenized as a researcher, and kept it's omni ability the next time it was played as a bumpsy.

I've attached the logs - of note:

- my turn 8, I have a grey rider make a researcher fight a sanitation engineer - this specific researcher token was a bumpsy, and it died due to hazardous
- at the very end of my turn 12 you can see the bumpsy do a nothing during my mars turn

![image](https://github.com/keyteki/keyteki/assets/324548/66e84c5c-4946-4454-a8fc-3475259c3873)

log:

MaxLvL brings Lord el Amarillo to The Crucible
dmikalova brings Kuqefolly, the She-wolf Harbinger to The Crucible
MaxLvL won the flip and is first player
 dmikalova has connected to the game server
 MaxLvL has connected to the game server
MaxLvL is shuffling their deck
MaxLvL draws 6 card  s to their maximum of 6
dmikalova is shuffling their deck
dmikalova draws 6 card  s to their maximum of 6
MaxLvL draws 1 card 
dmikalova
howdy gl hf :)
Key phase - MaxLvL
MaxLvL does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - MaxLvL
MaxLvL chooses untamed  as their active house this turn
Main phase - MaxLvL
MaxLvL plays Creed of Nurture
Ready phase - MaxLvL
MaxLvL readies their cards 
Draw phase - MaxLvL
End of turn 1
MaxLvL: 0 Æmber  (0 keys) dmikalova: 0 Æmber  (0 keys)
TURN 1 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses brobnar  as their active house this turn
Main phase - dmikalova
dmikalova plays Ged Hammer
dmikalova plays Shock Herder
dmikalova uses Shock Herder to ready and fight with a neighboring creature
dmikalova uses Ged Hammer to reap with Ged Hammer
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 3 card  s to their maximum of 6
End of turn 1
MaxLvL: 0 Æmber  (0 keys) dmikalova: 1 Æmber  (0 keys)
TURN 2 - MaxLvL
Key phase - MaxLvL
MaxLvL does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - MaxLvL
MaxLvL chooses untamed  as their active house this turn
Main phase - MaxLvL
MaxLvL plays Tantadlin
MaxLvL plays Kangaphant
MaxLvL plays Moor Wolf
Ready phase - MaxLvL
MaxLvL readies their cards 
Draw phase - MaxLvL
MaxLvL draws 3 card  s to their maximum of 6
End of turn 2
MaxLvL: 0 Æmber  (0 keys) dmikalova: 1 Æmber  (0 keys)
TURN 2 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses sanctum  as their active house this turn
Main phase - dmikalova
dmikalova plays Shoulder Armor attaching it to Shock Herder
dmikalova gains an Æmber  due to Shoulder Armor's bonus icon
dmikalova plays Shoulder Armor attaching it to Ged Hammer
dmikalova gains an Æmber  due to Shoulder Armor's bonus icon
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 2 card  s to their maximum of 6
End of turn 2
MaxLvL: 0 Æmber  (0 keys) dmikalova: 3 Æmber  (0 keys)
TURN 3 - MaxLvL
Key phase - MaxLvL
MaxLvL does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - MaxLvL
MaxLvL chooses logos  as their active house this turn
Main phase - MaxLvL
MaxLvL plays Information Exchange
MaxLvL uses Information Exchange to steal 1 Æmber  from dmikalova
MaxLvL plays Information Exchange
MaxLvL uses Information Exchange to steal 1 Æmber  from dmikalova
MaxLvL plays Wormhole Technician
MaxLvL plays Wormhole Technician
Ready phase - MaxLvL
MaxLvL readies their cards 
Draw phase - MaxLvL
MaxLvL draws 4 card  s to their maximum of 6
End of turn 3
MaxLvL: 2 Æmber  (0 keys) dmikalova: 1 Æmber  (0 keys)
TURN 3 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses brobnar  as their active house this turn
Main phase - dmikalova
dmikalova uses Shock Herder to make Shock Herder fight Wormhole Technician
dmikalova plays Vulka
dmikalova uses Ged Hammer to make Ged Hammer fight Wormhole Technician
dmikalova plays Ragnarok Prep
dmikalova deals 1 damage to Moor Wolf due to Ragnarok Prep's bonus icon
dmikalova uses Ragnarok Prep to make a token creature
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 2 card  s to their maximum of 6
End of turn 3
MaxLvL: 0 Æmber  (0 keys) dmikalova: 1 Æmber  (0 keys)
TURN 4 - MaxLvL
Key phase - MaxLvL
MaxLvL does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - MaxLvL
MaxLvL chooses untamed  as their active house this turn
Main phase - MaxLvL
MaxLvL uses Kangaphant to make Kangaphant fight Researcher
MaxLvL uses Moor Wolf to make Moor Wolf fight Ged Hammer
MaxLvL uses Tantadlin to make Tantadlin fight Shock Herder
Ready phase - MaxLvL
MaxLvL readies their cards 
Draw phase - MaxLvL
End of turn 4
MaxLvL: 0 Æmber  (0 keys) dmikalova: 1 Æmber  (0 keys)
TURN 4 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses sanctum  as their active house this turn
Main phase - dmikalova
dmikalova plays Grey Abbess
dmikalova uses Grey Abbess to make a token creature
dmikalova plays Battlefield Evangelist
dmikalova plays Membership Drive
dmikalova uses Membership Drive to make a token creature and gain 1 Æmber  for each friendly token creature
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 3 card  s to their maximum of 6
End of turn 4
MaxLvL: 0 Æmber  (0 keys) dmikalova: 3 Æmber  (0 keys)
TURN 5 - MaxLvL
Key phase - MaxLvL
MaxLvL does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - MaxLvL
MaxLvL chooses saurian  as their active house this turn
Main phase - MaxLvL
MaxLvL plays Paraguardian
MaxLvL plays Exile
MaxLvL gains an Æmber  due to Exile's bonus icon
MaxLvL uses Exile to give control of Kangaphant to dmikalova
Ready phase - MaxLvL
MaxLvL readies their cards 
Draw phase - MaxLvL
MaxLvL draws 2 card  s to their maximum of 6
End of turn 5
MaxLvL: 1 Æmber  (0 keys) dmikalova: 3 Æmber  (0 keys)
TURN 5 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses brobnar  as their active house this turn
Main phase - dmikalova
dmikalova plays Pound
dmikalova gains an Æmber  due to Pound's bonus icon
dmikalova deals 1 damage to Paraguardian due to Pound's bonus icon
dmikalova draws a card  due to Pound's bonus icon
dmikalova uses Pound to deal 2 damage to Moor Wolf and 1 to their neighbors
dmikalova plays Rowdy Skald
dmikalova uses Researcher to archive Ironyx Vatminder
dmikalova uses Researcher to archive Glylyx Weaponsmith
dmikalova uses Vulka to make Vulka fight Tantadlin
dmikalova uses Ged Hammer to make Ged Hammer fight Paraguardian
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 3 card  s to their maximum of 6
End of turn 5
MaxLvL: 1 Æmber  (0 keys) dmikalova: 4 Æmber  (0 keys)
TURN 6 - MaxLvL
Key phase - MaxLvL
MaxLvL does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - MaxLvL
MaxLvL chooses untamed  as their active house this turn
Main phase - MaxLvL
MaxLvL plays Rustgnawer
MaxLvL discards Song of the Wild
MaxLvL discards Key Charge
Ready phase - MaxLvL
MaxLvL readies their cards 
Draw phase - MaxLvL
MaxLvL draws 3 card  s to their maximum of 6
End of turn 6
MaxLvL: 1 Æmber  (0 keys) dmikalova: 4 Æmber  (0 keys)
TURN 6 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses mars  as their active house this turn
Main phase - dmikalova
dmikalova plays Braindart
dmikalova gains an Æmber  due to Braindart's bonus icon
dmikalova uses Braindart to enrage Rustgnawer and make it capture 1 Æmber  from its own side
dmikalova plays Genetic Blast
dmikalova gains an Æmber  due to Genetic Blast's bonus icon
dmikalova uses Genetic Blast to deal 2 damage to Rustgnawer and each other creature with the same name
dmikalova plays Scoop Up
dmikalova gains an Æmber  due to Scoop Up's bonus icon
dmikalova uses Scoop Up to archive Kangaphant and Rustgnawer
dmikalova uses Researcher to archive Purple Aeronaut
dmikalova uses Researcher to archive Green Aeronaut
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 5 card  s to their maximum of 6
 dmikalova declares Check!
End of turn 6
MaxLvL: 0 Æmber  (0 keys) dmikalova: 8 Æmber  (0 keys)
TURN 7 - MaxLvL
Key phase - MaxLvL
MaxLvL does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - MaxLvL
MaxLvL chooses saurian  as their active house this turn
Main phase - MaxLvL
MaxLvL plays Saurus Rex
MaxLvL plays Thero Centurion
MaxLvL uses Thero Centurion to capture 1 Æmber  from their opponent , placing it on Thero Centurion
MaxLvL plays City-State Interest
MaxLvL uses City-State Interest to make each friendly creature capture 1 Æmber 
Ready phase - MaxLvL
MaxLvL readies their cards 
Draw phase - MaxLvL
MaxLvL draws 3 card  s to their maximum of 6
End of turn 7
MaxLvL: 0 Æmber  (0 keys) dmikalova: 5 Æmber  (0 keys)
TURN 7 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses brobnar  as their active house this turn
Main phase - dmikalova
dmikalova discards Autocannon
dmikalova plays Rowdy Skald
dmikalova uses Rowdy Skald to reap with Rowdy Skald
dmikalova uses Vulka to reap with Vulka
dmikalova uses Ged Hammer to make Ged Hammer fight Thero Centurion
dmikalova uses Ged Hammer to ready and enrage each other friendly Brobnar  creature
dmikalova uses Rowdy Skald to make Rowdy Skald fight Saurus Rex
dmikalova uses Rowdy Skald to make Rowdy Skald fight Saurus Rex
dmikalova uses Vulka to reap with Vulka
dmikalova uses Researcher
dmikalova uses Researcher
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 2 card  s to their maximum of 6
 dmikalova declares Check!
End of turn 7
MaxLvL: 0 Æmber  (0 keys) dmikalova: 11 Æmber  (0 keys)
TURN 8 - MaxLvL
Key phase - MaxLvL
MaxLvL does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - MaxLvL
MaxLvL chooses logos  as their active house this turn
Main phase - MaxLvL
MaxLvL plays Hologrammophone
MaxLvL gains an Æmber  due to Hologrammophone's bonus icon
MaxLvL plays Sanitation Engineer
MaxLvL plays EDAI “Edie” 4x4
MaxLvL uses EDAI “Edie” 4x4 to archive a card 
Ready phase - MaxLvL
MaxLvL readies their cards 
Draw phase - MaxLvL
MaxLvL draws 4 card  s to their maximum of 6
End of turn 8
MaxLvL: 1 Æmber  (0 keys) dmikalova: 11 Æmber  (0 keys)
TURN 8 - dmikalova
Key phase - dmikalova
dmikalova forges the yellow key  , paying 8 Æmber 
House phase - dmikalova
dmikalova chooses sanctum  as their active house this turn
Main phase - dmikalova
dmikalova plays Haedroth’s Wall
dmikalova uses Battlefield Evangelist to make Battlefield Evangelist fight EDAI “Edie” 4x4
dmikalova uses Battlefield Evangelist to make a token creature
dmikalova uses Researcher to archive Ironyx Vatminder
dmikalova plays Celestial Gorm
dmikalova gains an Æmber  due to Celestial Gorm's bonus icon
dmikalova deals 1 damage to Sanitation Engineer due to Celestial Gorm's bonus icon
dmikalova plays The Grey Rider
dmikalova uses The Grey Rider to ready and fight with a neighboring creature
dmikalova uses Researcher to make Researcher fight Sanitation Engineer
MaxLvL uses Sanitation Engineer to deal 1 damage to Researcher
dmikalova plays The Grey Rider
dmikalova uses Grey Abbess to reap with Grey Abbess
dmikalova uses Researcher
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 5 card  s to their maximum of 6
End of turn 8
MaxLvL: 1 Æmber  (0 keys) dmikalova: 5 Æmber  (1 key)
TURN 9 - MaxLvL
Key phase - MaxLvL
MaxLvL does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - MaxLvL
MaxLvL chooses saurian  as their active house this turn
Main phase - MaxLvL
MaxLvL plays Rhetor Gallim
MaxLvL uses Rhetor Gallim to increase dmikalova's key cost by 3 during their next turn
MaxLvL plays Axiom of Grisk
MaxLvL uses Axiom of Grisk to ward Rhetor Gallim, destroy all creatures without Æmber  and give MaxLvL 2 chains
MaxLvL uses Rhetor Gallim to remove its ward token
MaxLvL plays Philophosaurus
Ready phase - MaxLvL
MaxLvL readies their cards 
Draw phase - MaxLvL
MaxLvL draws 2 card  s to their maximum of 6
MaxLvL's chains are reduced by 1 to 1
End of turn 9
MaxLvL: 1 Æmber  (0 keys) dmikalova: 5 Æmber  (1 key)
TURN 9 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 5 amber. The current cost is 9 Æmber 
House phase - dmikalova
dmikalova chooses brobnar  as their active house this turn
Main phase - dmikalova
dmikalova plays Earthshaker
dmikalova uses Earthshaker to destroy Rhetor Gallim
dmikalova plays Crim Torchtooth
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 2 card  s to their maximum of 6
dmikalova's deck has run out of cards, so they shuffle
End of turn 9
MaxLvL: 1 Æmber  (0 keys) dmikalova: 5 Æmber  (1 key)
TURN 10 - MaxLvL
Key phase - MaxLvL
MaxLvL does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - MaxLvL
MaxLvL chooses saurian  as their active house this turn
Main phase - MaxLvL
MaxLvL uses Philophosaurus to reap with Philophosaurus
MaxLvL uses Philophosaurus to archive 1 card, move 1 card  to hand and discard 1 card 
MaxLvL plays Axiom of Grisk
MaxLvL uses Axiom of Grisk to ward Philophosaurus, destroy all creatures without Æmber  and give MaxLvL 2 chains
MaxLvL uses Philophosaurus to remove its ward token
Ready phase - MaxLvL
MaxLvL readies their cards 
Draw phase - MaxLvL
MaxLvL's chains are reduced by 1 to 2
End of turn 10
MaxLvL: 2 Æmber  (0 keys) dmikalova: 5 Æmber  (1 key)
TURN 10 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses sanctum  as their active house this turn
Main phase - dmikalova
dmikalova plays Katerina the Summoner
dmikalova deals 1 damage to Philophosaurus due to Katerina the Summoner's bonus icon
dmikalova deals 1 damage to Philophosaurus due to Katerina the Summoner's bonus icon
dmikalova uses Katerina the Summoner to capture 1 Æmber  from their opponent , placing it on Katerina the Summoner
dmikalova plays Challe the Safeguard
dmikalova plays The Grey Rider
dmikalova uses The Grey Rider to ready and fight with a neighboring creature
dmikalova uses Katerina the Summoner to make Katerina the Summoner fight Philophosaurus
dmikalova uses Katerina the Summoner to make a token creature
dmikalova plays Request Donations
dmikalova deals 1 damage to Challe the Safeguard due to Request Donations's bonus icon
dmikalova uses Request Donations to make a token creature
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 4 card  s to their maximum of 6
End of turn 10
MaxLvL: 0 Æmber  (0 keys) dmikalova: 5 Æmber  (1 key)
TURN 11 - MaxLvL
Key phase - MaxLvL
MaxLvL does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - MaxLvL
MaxLvL chooses untamed  as their active house this turn
MaxLvL moves all the cards  in their archives to their hand
Main phase - MaxLvL
MaxLvL plays Kangaphant
MaxLvL plays Deepwood Druid
MaxLvL uses Deepwood Druid to heal Kangaphant fully
MaxLvL plays Moor Wolf
MaxLvL plays Moor Wolf
MaxLvL uses Moor Wolf to ready each other Wolf creature.
MaxLvL uses Moor Wolf to make Moor Wolf fight Researcher
Ready phase - MaxLvL
MaxLvL readies their cards 
Draw phase - MaxLvL
MaxLvL draws 1 card  to their maximum of 6
MaxLvL's chains are reduced by 1 to 1
End of turn 11
MaxLvL: 0 Æmber  (0 keys) dmikalova: 5 Æmber  (1 key)
TURN 11 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses brobnar  as their active house this turn
Main phase - dmikalova
dmikalova plays Bumpsy
dmikalova uses Bumpsy to make MaxLvL lose 1 Æmber 
dmikalova plays Pound
dmikalova gains an Æmber  due to Pound's bonus icon
dmikalova deals 1 damage to Moor Wolf due to Pound's bonus icon
dmikalova draws a card  due to Pound's bonus icon
dmikalova uses Pound to deal 2 damage to Moor Wolf and 1 to their neighbors
dmikalova uses Researcher to archive White Aeronaut
dmikalova uses Researcher
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 2 card  s to their maximum of 6
 dmikalova declares Check!
End of turn 11
MaxLvL: 0 Æmber  (0 keys) dmikalova: 6 Æmber  (1 key)
TURN 12 - MaxLvL
Key phase - MaxLvL
MaxLvL does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - MaxLvL
MaxLvL chooses saurian  as their active house this turn
Main phase - MaxLvL
MaxLvL plays Brutodon Auxiliary
MaxLvL plays Phalanx Strike
MaxLvL gains an Æmber  due to Phalanx Strike's bonus icon
MaxLvL uses Phalanx Strike to deal 3 damage to Researcher
MaxLvL exalts Kangaphant to repeat Phalanx Strike's effect
MaxLvL uses Phalanx Strike to deal 3 damage to The Grey Rider
MaxLvL plays Triumph
MaxLvL gains an Æmber  due to Triumph's bonus icon
Ready phase - MaxLvL
MaxLvL readies their cards 
Draw phase - MaxLvL
MaxLvL draws 3 card  s to their maximum of 6
MaxLvL's chains are reduced by 1 to 0
End of turn 12
MaxLvL: 4 Æmber  (0 keys) dmikalova: 6 Æmber  (1 key)
TURN 12 - dmikalova
Key phase - dmikalova
dmikalova forges the blue key  , paying 6 Æmber 
House phase - dmikalova
dmikalova chooses mars  as their active house this turn
dmikalova moves all the cards  in their archives to their hand
Rustgnawer leaves the archives and will be returned its owner hand
Main phase - dmikalova
dmikalova plays Mk.2 Generator
dmikalova uses Mk.2 Generator to make a token creature
dmikalova plays Braindart
dmikalova gains an Æmber  due to Braindart's bonus icon
dmikalova uses Braindart to enrage Deepwood Druid and make it capture 1 Æmber  from its own side
dmikalova plays Genetic Blast
dmikalova gains an Æmber  due to Genetic Blast's bonus icon
dmikalova uses Genetic Blast to deal 2 damage to Deepwood Druid and each other creature with the same name
dmikalova plays Ironyx Vatminder
dmikalova uses Ironyx Vatminder to make a token creature
dmikalova plays Ironyx Vatminder
dmikalova uses Ironyx Vatminder to make a token creature
dmikalova plays White Aeronaut
dmikalova gains an Æmber  due to White Aeronaut's bonus icon
dmikalova plays Green Aeronaut
dmikalova plays Purple Aeronaut
dmikalova plays Glylyx Weaponsmith
dmikalova plays Nautilixian
dmikalova uses Celestial Gorm to destroy Celestial Gorm and return each other artifact to its owner's hand
dmikalova plays Mk.2 Generator
dmikalova uses Mk.2 Generator to make a token creature
dmikalova uses Researcher to reap with Researcher
dmikalova uses Researcher to destroy Researcher
dmikalova uses Bumpsy
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 3 card  s to their maximum of 6
End of turn 12
MaxLvL: 3 Æmber  (0 keys) dmikalova: 5 Æmber  (2 keys)

**Comment by dmikalova** [comment]
This may be related to this reseracher issue as well
https://github.com/keyteki/keyteki/issues/3268

**Comment by romanogit** [comment]
Fixed by https://github.com/keyteki/keyteki/pull/3458
