### ISSUE TITLE
Pupgrade

### ISSUE THREAD

**Issue by Rikuns** [keyteki/keyteki#3331]
I played Phalanx Strike and killed the creature with Pupgrade attaching. Pupgrade became a creature, I exalted to Phalanx Strike again on Pupgrade but Pupgrade doesn't receive any damaga and stay alive with no damage. 
![image](https://github.com/keyteki/keyteki/assets/83189520/93cb6dca-657f-4beb-9b30-b86966bc465a)

**Comment by Rikuns** [comment]
I just checked, Pupgrade did in fact went to discard pile but the card is this there. Just can't interact with it in any ways.
![image](https://github.com/keyteki/keyteki/assets/83189520/3eafcc54-82c6-4680-b0f4-9996a5259271)

**Comment by romanogit** [comment]
so you Phalanx Strike'd your creature and moved your Pupgrade to your battleline or was Pupgrade attached to an enemy creature?

**Comment by Rikuns** [comment]
> No it's opponent Pupgrade. I meant I played with myself. I played Phalanx Strike on opponent's creature that has Pupgrade attaching. Then I exalted to Phalanx Strike again on the Pupgrade and the card stuck there.
