### ISSUE TITLE
Token Have Armor 0 if card under has armor

### ISSUE THREAD

**Issue by Osarek** [keyteki/keyteki#3333]
I have 3 fishes, one of that has 0 armor overlay, it seems because the card under have some armor
My opponent also see the armor, he can know that its a creature facing down

![image](https://github.com/keyteki/keyteki/assets/57572496/10c3ddd3-ad2e-438e-bdae-2a0f45368231)

![image](https://github.com/keyteki/keyteki/assets/57572496/d3bdadba-38d7-44f2-81d5-95e624e86229)

![image](https://github.com/keyteki/keyteki/assets/57572496/97fccc2e-4d76-4cb3-b30f-f203b99b3313)

Similar bug:

when the card under toner has the exact same power as the token, ther is no power « overlay ». And when there is different or no power, the overlay is present, that can be some tell aboute if there is a creature or not under

![image](https://github.com/keyteki/keyteki/assets/57572496/9c50e0c7-fdbe-4da9-aac0-b74ecac29328)

**Comment by dmikalova** [comment]
I'm seeing what may also be a related issue - I have haedroth's wall out, so flank creatures should have +2 power. I was seeing this extra power until a 0 shield researcher came out - subsequent researchers were then also lacking the extra power even without the 0 shield. See my flanks in this image:

![image](https://github.com/keyteki/keyteki/assets/324548/d6236219-0548-4d61-a510-5d9e4cb5e8f8)

**Comment by strib** [comment]
Hmm seems like @dmikalova's deck also contains a Grey Abbess.  I wonder if this is just a Grey Abbess problem somehow.

**Comment by dgbrokaw** [comment]
I got 0 armor showing with my Grey Abbess deck after destroying the Abbess
![image](https://github.com/keyteki/keyteki/assets/7118380/48def497-015b-4448-94c6-eece17a4080d)
