### ISSUE TITLE
Enhancement: allow changing username

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#334]
I have seen this request by a few people. Any impact on this or is it just a matter of time to implement? I could help with this one.

**Comment by cryogen** [comment]
I’m hesitant to do this as it opens up an avenue of abuse, and the database structure is that it will cause us some problems. Maybe in the future but not with the current platform

**Comment by romanogit** [comment]
What if, initially, we allow under certain conditions:
1) User can only do it 1 time
2) User cannot have decks associated with it
3) User cannot be in anyone else's blocklist

**Comment by romanogit** [comment]
Basically, the idea is to allow changing username after a couple of days of usage.

**Comment by cryogen** [comment]
In that instance, it's almost certainly easier for them to just make a new account

**Comment by romanogit** [comment]
Ok. Point taken.
