### ISSUE TITLE
Spectral Tunneller + Positron Bolt: PB should have an interrupt to select the neighbor to take the first damage

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#335]
Here is the table:
Opponent battleline (damage in parenthesis)
`Firespitter (0) - Headhunter (0) - Mother (3) - Mother (2) - Old Bruno (0)
`
I have:
`Spectral Tunneller`

I activate `Spectral Tunneler` and play `Positron Bolt` selecting `Mother (3)`. Should `Firespitter `or `Old Bruno` take the 1 damage? Should be both or should we be able to select?

Cosmetic: Log is missing the Mother (2) damage:
Log says `"romano2 uses Positron Bolt to deal 3 damage to Mother, 2 damage to Headhunter and 1 damage to Firespitter"`

Should be `"romano2 uses Positron Bolt to deal 3 damage to Mother, 2 damage to Headhunter  and Mother and 1 damage to Firespitter (and Old Bruno)"?`

**Comment by romanogit** [comment]
I will recreate this scenario again. rule FAQ says:

What happens if I use Spectral Tunneler on a non-flank creature (causing it to be considered  a flank creature), then play Positron Bolt on that creature?Positron Bolt will deal 3 damage to that creature. You will choose one othat creature’s neighbors to deal 2 damage to, and then deal 1 damage to the other neighbor of that second creature.

It is not both neighbors that take the damage and we need an interrupt.

**Comment by cryogen** [comment]
I think the WC ability prompt fixes this.  Can you retest on master and close if so?

**Comment by romanogit** [comment]
It does not. It deals damage to both neighbors

So I had:
Zookeeper, Yxlix Dominator and Xanthyx

I applied ST to Yxlix and target played Positron bolt on him. Both neighbors got 2 damages:

```
romano2 uses Spectral Tunneler to give Yxilx Dominator a reap ability and it is considered to be on a flank for the remainder of the turn
romano2 plays Positron Bolt, gaining 1 Æmber
romano2 uses Positron Bolt to deal 3 damage to Yxilx Dominator and 2 damage to Uxlyx the Zookeeper
```

**Comment by romanogit** [comment]
I removed the `Timing Refactor` as this is more a rule issue.

FFG rules that when creature has 2 neighbors (due to Spectral Tunneler), APC one of them.
