### ISSUE TITLE
WOE alliance won't let you use special tokens

### ISSUE THREAD

**Issue by Skunkwitch39** [keyteki/keyteki#3358]
I have 3 decks I'm alliance-ing together, one has the bellatoran warrior token. I am not using the saurian pod with the training costs (the card that puts your token as the warrior). but in the deck builder for the alliance deck i made it only shows the two tokens from the decks that aren't the warrior deck. help?

**Comment by cryogen** [comment]
Thanks for the report, this is already tracked here #3334
