### ISSUE TITLE
Near-Future Lens -- Logging entire deck on shuffle

### ISSUE THREAD

**Issue by SadCryBear** [keyteki/keyteki#3365]
When shuffling with NFL every card in the deck was logged on shuffle.

I was unable to confirm if this revealed the shuffle order (a major problem) or was just noise in the log.
<img width="1280" alt="NFL Issue" src="https://github.com/keyteki/keyteki/assets/57689889/d0c4b42e-9d59-4d6f-93e6-7b2eafaa2931">

**Comment by strib** [comment]
Ah I see.  No it wasn't the deck order, it was the code returning each card from the discard pile to the top of the deck, before shuffling it.  Fixed in #3366.  Thanks for the report!
