### ISSUE TITLE
WoE token UI: token power is invisible if equal to card underneath

### ISSUE THREAD

**Issue by alifeee** [keyteki/keyteki#3374]
to replicate:

- use [this deck](https://www.keyforgegame.com/deck-details/274651f0-e6a0-488c-baab-08fd3a42149b)
- play Tribune Pompitus
- move a power 3 card to top of deck (e.g., Gezdrutyo the Arcane)
- create a token creature (e.g., with The Visible Hand)
- play Symposium to exalt the token(s)

The token now has three power (from Pompitus), but since the card underneath has 3 power, the power does not display. This is not the case if the card underneath has a different power/is not a creature. Screenshot:

(the cards underneath token cards here are Ironyx Rebel (2/0), Gezdrutyo the Arcane (3/0))

![image](https://github.com/keyteki/keyteki/assets/13833017/d4f97613-c57f-4454-9288-2462a1775ad6)

**Comment by DaveCordeiro** [comment]
Similarly, if a creature with armor is facedown, the token shows as 0 armor instead of ~

**Comment by dmikalova** [comment]
Similarly, if the card under it is a maverick the token creature will have the maverick symbol.
