### ISSUE TITLE
Autocannon should not cause Cadet's destroyed to trigger

### ISSUE THREAD

**Issue by CorayThan** [keyteki/keyteki#3390]
Z told me the head judge at GG told him the destroyed effect would not trigger.

**Comment by strib** [comment]
Autocannon should 100% trigger Cadet's ability.  What it would not trigger is FOF Transponder to move endlessly among new Cadets as they are destroyed by Autocannon.  Maybe that is what you are thinking?

The Cadet's destroyed ability happens, just like Bad Penny's does with Autocannon.

**Comment by CorayThan** [comment]
My bad. It was a misunderstanding.
