### ISSUE TITLE
WoE: Fidgiting opponent's space invaders does not allow creature selection

### ISSUE THREAD

**Issue by dmikalova** [keyteki/keyteki#3394]
I reaped with fidgit to play space invaders from my opponent's archive. I had a few creatures in hand, but was not allowed to select them.

>dmikalova uses Fidgit to reap with Fidgit
dmikalova chooses option ' Random card  from archives '
dmikalova uses Fidgit to discard a card  at random from Varghast's archives
Varghast discards Space Invaders at random
dmikalova plays Space Invaders
dmikalova uses Space Invaders to reveal and tokenize

![image](https://github.com/keyteki/keyteki/assets/324548/b82349f6-415b-432a-9743-81bb725db263)

**Comment by strib** [comment]
You were playing a deck without a token.  You were hoping to be able to reveal the creatures and then have nothing happen?  Should they have been discarded?  I have no idea what the right behavior should be here.  Not letting you select anything seems reasonable as long as "Done" works, but I'm open to other opinions.

**Comment by dmikalova** [comment]
Ah that makes sense. The confusion came from the original card text:

> Play: Reveal any number of creatures from your hand. Put each creature revealed this way into play facedown as a token creature.

Which I interpret to let me effectively discard those creatures. But Space Invaders has been errataed to read:

> Reveal any number of creatures from your hand. Make each creature revealed this way a token creature as if the card was on top of your deck.

Which according to the rules won't do anything, and is effectively implemented as such since I can't think of a good strategy that revealing a creature would give.
