### ISSUE TITLE
Woe: Rule Question : [Suspended Animation] and [Destructive Analysis]

### ISSUE THREAD

**Issue by Osarek** [keyteki/keyteki#3396]
An enemy damaged creature is in my archive due to suspended animation
When i play Destructive analysis, and select it from my archive, it does not get purged, (so no extra damage) and get back into the owner hand (like described by Suspended animation

Is that correct behavior or it should be purged?

![image](https://github.com/keyteki/keyteki/assets/57572496/8ff8757c-669a-4bf4-aa64-4f8f82b2ceb0)

osarek2 brings Valdis “Susurrus” Jintrorion to The Crucible
Osarek-3651 brings Hạnh, the Wolf of the Rock to The Crucible
Osarek-3651 won the flip and is first player
 osarek2 has connected to the game server
 Osarek-3651 has connected to the game server
osarek2 is shuffling their deck
osarek2 draws 6 card  s to their maximum of 6
Osarek-3651 is shuffling their deck
Osarek-3651 draws 6 card  s to their maximum of 6
Osarek-3651 draws 1 card 
 Osarek-3651 is attempting to switch manual mode on
 osarek2 allows enabling manual mode
 Osarek-3651 switches manual mode on
Key phase - Osarek-3651
Osarek-3651 does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Osarek-3651
Osarek-3651 chooses unfathomable  as their active house this turn
Main phase - Osarek-3651
Ready phase - Osarek-3651
Draw phase - Osarek-3651
End of turn 1
osarek2: 0 Æmber  (0 keys) Osarek-3651: 0 Æmber  (0 keys)
TURN 1 - osarek2
Key phase - osarek2
osarek2 does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - osarek2
 Osarek-3651 manually moves Mothership Support from their deck to their hand
 Osarek-3651 manually moves Xanthyx Harvester from their hand to their play area
 osarek2 manually moves Firespitter from their hand to their play area
 osarek2 manually moves Chancellor Dexterus from their hand to their play area
 osarek2 manually moves The Old Tinker from their hand to their play area
osarek2 chooses ekwidon  as their active house this turn
Main phase - osarek2
Ready phase - osarek2
osarek2 readies their cards 
Draw phase - osarek2
osarek2 draws 3 card  s to their maximum of 6
End of turn 1
osarek2: 0 Æmber  (0 keys) Osarek-3651: 0 Æmber  (0 keys)
TURN 2 - Osarek-3651
Key phase - Osarek-3651
Osarek-3651 does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Osarek-3651
 Osarek-3651 adds a damage to Firespitter
Osarek-3651 chooses mars  as their active house this turn
Main phase - Osarek-3651
 Osarek-3651 switches manual mode off
Osarek-3651 plays Suspended Animation
Osarek-3651 gains an Æmber  due to Suspended Animation's bonus icon
Osarek-3651 uses Suspended Animation to archive Firespitter
Osarek-3651 plays Mothership Support
Osarek-3651 gains an Æmber  due to Mothership Support's bonus icon
Osarek-3651 uses Mothership Support to deal 2 damage to a creature for each ready Mars  creature they control
 Osarek-3651 is attempting to switch manual mode on
 osarek2 allows enabling manual mode
 Osarek-3651 switches manual mode on
 Osarek-3651 manually moves Destructive Analysis from their deck to their hand
 Osarek-3651 switches manual mode off
Osarek-3651 plays Destructive Analysis
Osarek-3651 gains an Æmber  due to Destructive Analysis's bonus icon
Osarek-3651 uses Destructive Analysis to deal 2 damage to The Old Tinker
**Firespitter leaves the archives and will be returned its owner hand**

**Comment by strib** [comment]
Yes I believe that is the correct behavior.  The Suspended Animation text supersedes the Destructive Analysis.  Same as how Collector Worm worked in AoA.

**Comment by Osarek** [comment]
ok i will close this issue then. THere is no bug
