### ISSUE TITLE
shard of hope 

### ISSUE THREAD

**Issue by MissTotoro** [keyteki/keyteki#340]
Shard of hope reads "a friendly creature captures..." but on crucible it captures one ember to one friendly creature and then one ember to another friendly creature. It should capture two to one creature if you have two shards, since its still to one creature.

![image](https://user-images.githubusercontent.com/54183105/63180183-02e42900-c04e-11e9-9ccc-72cf71bab898.png)

**Comment by hydrophilic-attack** [comment]
Actually, Brad Andres clarified in the Worlds Collide gameplay demo yesterday that effects like these do allow you to spread the effect on different creatures. See the video at the following link:

https://www.twitch.tv/ffglive/clip/WealthyAverageBaconANELE?filter=clips&range=7d&sort=time

In other words, the way you're describing it currently works, is the way it's supposed to work

**Comment by MissTotoro** [comment]
Oh, I hade ni idea that the text could be intepreted that way, but the more I think about it, it actually makes sence.... I really thought it was a bug, but maybe its suppose tog work that way, yes.
