### ISSUE TITLE
Played smite on skullion to fight shadow self and shadow selfs neighbor took 2 damage from the smite instead of killing shadow self

### ISSUE THREAD

**Issue by josephzucchetto** [keyteki/keyteki#341]
Played smite on skullion to kill shadow self but instead of the damage being redirected to shadow self his neighbor took 2 
![955596B7-B58D-4BE1-BBFA-A1A852CA72E1](https://user-images.githubusercontent.com/54218810/63216476-0c2fcd00-c104-11e9-863f-2f4934d718be.png)
![FE1C20A6-4B4D-4CE5-BD2A-65212FF1487F](https://user-images.githubusercontent.com/54218810/63216477-0cc86380-c104-11e9-9883-21a395e8697e.png)
![F64307C5-FC52-46D9-AD3F-18CB4DADC57F](https://user-images.githubusercontent.com/54218810/63216478-0cc86380-c104-11e9-8c46-d5a47ecd99e9.png)

**Comment by romanogit** [comment]
@josephzucchetto ,
this is a tricky one. The neighbor of Shadow's has 2 armor (Raiding Knight). Unless, the armor was zeroed before Smite hit him, it is very likely that the 2 damage just cleared Raiding Knight's armor and did not actually do any damage too it, so, the damage did not get redirected to Shadow Self.
Can you confirm Raiding Knight did not take the damage? (hard to know if that 2 damage was prior to the attack, but the armor is zeroed)
