### ISSUE TITLE
WoE: deck has wrong cards

### ISSUE THREAD

**Issue by dmikalova** [keyteki/keyteki#3411]
This deck had the wrong cards both in the decklist and those cards were also drawn into my opponents hand, for example the first four cards are completely incorrect:

- mothergun
- mindworm
- red aeronaut
- mookling

https://www.keyforgegame.com/deck-details/d7766c4a-17fe-4365-83e6-bb328f18d7bb

![image](https://github.com/keyteki/keyteki/assets/324548/7e0f3a99-72a7-44ca-b0cb-81d7c428c118)

**Comment by tobinlopes** [comment]
Also, 
This one had a lot of wrong cards in wrong houses.

https://www.keyforgegame.com/deck-details/e69b73b9-c2e9-4cfc-9cda-39bf7e82aa32

-tpl

**Comment by strib** [comment]
Looks like the Master Vault is having issues with these decks, likely not a TCO problem.

**Comment by tobinlopes** [comment]
Yep, 

You're right. I just sent them an email about them.

-tpl

**Comment by ydnus** [comment]
> Looks like the Master Vault is having issues with these decks, likely not a TCO problem.

i believe this is actually a TCO problem. I tried importing the same deck today that my buddy had previously imported back in may and it contained the incorrect cards.

Unless I'm incorrect and the master vault died on itself within the past few days

**Comment by tobinlopes** [comment]
It's with MV. It stopped working on the last few days. From what people were saying at the Vault, is that the addition of the Vault Masters decks messed things up.

**Comment by dmikalova** [comment]
MV is fixed now, although it seems like I have to delete and re-add broken decks.
