### ISSUE TITLE
WoE Deck Imported from DOK W/ Incorrect Cards

### ISSUE THREAD

**Issue by juliejuly** [keyteki/keyteki#3412]
I uploaded my [deck from DOK](https://decksofkeyforge.com/decks/913cae61-4653-46e7-97da-36255c433799) and two cards are not correct. I deleted the deck and reloaded it into TCO with the same result.  The missing cards are Generous Offer and Hire On, the incorrect cards are Lash and Mark of Dis.
![tco bug1](https://github.com/keyteki/keyteki/assets/87949193/1f4a58b1-4114-4134-9bd4-0876d12cd8a5)
![tco bug 2](https://github.com/keyteki/keyteki/assets/87949193/a283cee7-4965-450a-a5a7-f0b046806ea5)
![tco bug 3](https://github.com/keyteki/keyteki/assets/87949193/f24d2961-d6fd-462a-b7d5-8378eac35106)

**Comment by strib** [comment]
This is likely a Master Vault issue -- see #3411

**Comment by romanogit** [comment]
Duplicate, try to delete and reimport the deck, if the issue persists, let us know
