### ISSUE TITLE
B0-T giving action abilities to other creatures

### ISSUE THREAD

**Issue by rbray-lilly** [keyteki/keyteki#3413]
I think this is only happening when Nautilixian is out. I didn't notice earlier in the game but when I had two B0-T's out and a board of Mars creatures including Nautilixian when I attempted to use the White Aeronaut as well as a Yxlix Mesmerist there was a second action ability available that I accidentally tried to use another creature rather than the printed actions on the cards.
<img width="1335" alt="Screenshot 2023-07-07 at 9 32 18 AM" src="https://github.com/keyteki/keyteki/assets/21242725/143c60da-c8db-4046-92fe-48b90d24a6d4">

**Comment by romanogit** [comment]
Thanks for reporting. This is known and it not solved.

**Comment by romanogit** [comment]
Fixed by https://github.com/keyteki/keyteki/pull/3458
