### ISSUE TITLE
Befuddle prevented sandhopper from playing a card of the chosen house

### ISSUE THREAD

**Issue by agrandstudent** [keyteki/keyteki#3416]
I was befuddled into brobnar.  I chose ekwidon.  I used sandhopper to return a brobnar creature to my hand and then I was not allowed to play it with the second half of sandhoppers ability. 
agrandstudent turn 8 is where the bug happened
[sandhopper_befuddle.txt](https://github.com/keyteki/keyteki/files/12045829/sandhopper_befuddle.txt)

**Comment by dmikalova** [comment]
"cannot" overrides "must" and "may" so this seems correct.

https://archonarcana.com/Cannot

**Comment by strib** [comment]
I think this is a bug, since Befuddle says you cannot play cards of _other_ houses.  So they still should be able to play Brobnar cards on an Ekwidon turn.  I just haven't had time to dive into the play restriction code yet.

**Comment by dmikalova** [comment]
Just had a match where befuddle Mars also prevented [Zavel, "Archaeologist"](https://archonarcana.com/Zavel,_%E2%80%9CArchaeologist%E2%80%9D) from playing a Mars card - Loyalty Implants

**Comment by engelisengelis** [comment]
Had the same issue. My opponent played Befuddle and forbid me playing any other cards other than Brobnar. I chose Star Alliance and only used cards on board, including Retrotechnician Le who's reap effect lets me play a card from a discard pile. I chose a Brobnar card from the discard pile, and it stayed in my hand :(
