### ISSUE TITLE
Crash with Mirror Shell

### ISSUE THREAD

**Issue by kfoznot** [keyteki/keyteki#3424]
Got 2 game crashes in a row after reaping with Mirror Shell.

**Comment by romanogit** [comment]
I would need more logs to figure out the problem, such as board state, for example. 
There was a recent deploy that influence how Mirror Shell works and could have indirectly fixed the problem. If you observe the same problem again, paste the game log and screenshot of board state.

**Comment by romanogit** [comment]
Not enough information
