### ISSUE TITLE
WoE: Symposium does not trigger twice with fight death

### ISSUE THREAD

**Issue by dmikalova** [keyteki/keyteki#3434]
I played a symposium on a bellatoran warrior, and used it to fight and it died. This did not allow me to select a second creature to exalt, ready and use as expected.

dmikalova brings Argomaker, Spawn of Undincrucian to The Crucible
BHawk brings Vitatime, the Philosopher of the Bastion to The Crucible
dmikalova won the flip and is first player
 dmikalova has connected to the game server
 BHawk has connected to the game server
dmikalova is shuffling their deck
dmikalova draws 6 card  s to their maximum of 6
BHawk is shuffling their deck
BHawk draws 6 card  s to their maximum of 6
dmikalova draws 1 card 
BHawk
gl,hf
dmikalova
howdy gl hf :)
Key phase - dmikalova
dmikalova does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses saurian  as their active house this turn
Main phase - dmikalova
dmikalova plays Aquilia, Lone Hero
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 1 card  to their maximum of 6
End of turn 1
dmikalova: 0 Æmber  (0 keys) BHawk: 0 Æmber  (0 keys)
TURN 1 - BHawk
Key phase - BHawk
BHawk does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - BHawk
BHawk chooses logos  as their active house this turn
Main phase - BHawk
BHawk plays Auto-Encoder
BHawk plays Forge Compiler
BHawk plays Bot Bookton
Ready phase - BHawk
BHawk readies their cards 
Draw phase - BHawk
BHawk draws 3 card  s to their maximum of 6
End of turn 1
dmikalova: 0 Æmber  (0 keys) BHawk: 0 Æmber  (0 keys)
TURN 2 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses staralliance  as their active house this turn
Main phase - dmikalova
dmikalova plays Operations Officer Yshi
dmikalova plays Specialist Guthrak
dmikalova plays Securi-Droid
dmikalova uses Aquilia, Lone Hero without effect
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 3 card  s to their maximum of 6
End of turn 2
dmikalova: 0 Æmber  (0 keys) BHawk: 0 Æmber  (0 keys)
TURN 2 - BHawk
Key phase - BHawk
BHawk does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - BHawk
BHawk chooses logos  as their active house this turn
Main phase - BHawk
BHawk uses Bot Bookton to reap with Bot Bookton
BHawk uses Bot Bookton to play Quixo the “Adventurer”
BHawk plays Quixo the “Adventurer”
BHawk plays Mind Over Matter
BHawk uses Mind Over Matter to archive all creatures
BHawk plays Daughter
Ready phase - BHawk
BHawk readies their cards 
Draw phase - BHawk
BHawk draws 3 card  s to their maximum of 7
End of turn 2
dmikalova: 0 Æmber  (0 keys) BHawk: 1 Æmber  (0 keys)
TURN 3 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses sanctum  as their active house this turn
Main phase - dmikalova
dmikalova plays Katerina the Summoner
dmikalova uses Katerina the Summoner to capture 1 Æmber  from their opponent , placing it on Katerina the Summoner
dmikalova plays Battlefield Evangelist
dmikalova plays The Grey Rider
dmikalova uses The Grey Rider to ready and fight with a neighboring creature
dmikalova uses Battlefield Evangelist to make Battlefield Evangelist fight Daughter
dmikalova uses Battlefield Evangelist to make a token creature
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 3 card  s to their maximum of 6
End of turn 3
dmikalova: 0 Æmber  (0 keys) BHawk: 0 Æmber  (0 keys)
TURN 3 - BHawk
Key phase - BHawk
BHawk does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - BHawk
BHawk chooses saurian  as their active house this turn
Main phase - BHawk
BHawk plays City-State Interest
BHawk plays Curse of Vanity
BHawk gains an Æmber  due to Curse of Vanity's bonus icon
BHawk uses Curse of Vanity to exalt Daughter
Ready phase - BHawk
BHawk readies their cards 
Draw phase - BHawk
BHawk draws 2 card  s to their maximum of 7
End of turn 3
dmikalova: 0 Æmber  (0 keys) BHawk: 1 Æmber  (0 keys)
TURN 4 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses sanctum  as their active house this turn
Main phase - dmikalova
dmikalova uses Katerina the Summoner to reap with Katerina the Summoner
dmikalova uses Katerina the Summoner to capture 1 Æmber  from their opponent , placing it on Katerina the Summoner
dmikalova uses Battlefield Evangelist to make Battlefield Evangelist fight Daughter
dmikalova uses Battlefield Evangelist to make a token creature
dmikalova plays Grand Melee
dmikalova uses Grand Melee to destroy Daughter
dmikalova uses The Grey Rider to reap with The Grey Rider
dmikalova uses The Grey Rider to ready and fight with a neighboring creature
dmikalova uses Katerina the Summoner to reap with Katerina the Summoner
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 1 card  to their maximum of 6
End of turn 4
dmikalova: 4 Æmber  (0 keys) BHawk: 0 Æmber  (0 keys)
TURN 4 - BHawk
Key phase - BHawk
BHawk does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - BHawk
BHawk chooses dis  as their active house this turn
Main phase - BHawk
BHawk plays Mindfire
BHawk uses Mindfire to discard a card  at random from dmikalova's hand
dmikalova discards Training Costs at random
dmikalova
thanks!
BHawk
dang
BHawk plays Dance of Doom
BHawk uses Dance of Doom to destroy all creatures with power 5
BHawk plays Infurnace
BHawk chooses option ' Opponent's '
BHawk uses Infurnace to purge Membership Drive and Grand Melee
BHawk plays Impspector
Ready phase - BHawk
BHawk readies their cards 
Draw phase - BHawk
BHawk draws 3 card  s to their maximum of 6
End of turn 4
dmikalova: 4 Æmber  (0 keys) BHawk: 1 Æmber  (0 keys)
TURN 5 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses staralliance  as their active house this turn
dmikalova moves all the cards  in their archives to their hand
Main phase - dmikalova
dmikalova plays Recorded History
dmikalova gains an Æmber  due to Recorded History's bonus icon
dmikalova uses Recorded History to archive Rant and Rive and Imperator Drusilla
dmikalova plays Operations Officer Yshi
dmikalova plays Specialist Guthrak
dmikalova plays Securi-Droid
dmikalova plays Echo Reflector attaching it to Specialist Guthrak
dmikalova gains an Æmber  due to Echo Reflector's bonus icon
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 4 card  s to their maximum of 6
 dmikalova declares Check!
End of turn 5
dmikalova: 6 Æmber  (0 keys) BHawk: 1 Æmber  (0 keys)
TURN 5 - BHawk
Key phase - BHawk
BHawk does not forge a key. They have 1 amber. The current cost is 9 Æmber 
House phase - BHawk
BHawk chooses dis  as their active house this turn
Main phase - BHawk
BHawk plays Mindfire
BHawk uses Mindfire to discard a card  at random from dmikalova's hand
dmikalova discards Transporter Platform at random
BHawk uses Mindfire to steal 1 Æmber 
dmikalova
:(
BHawk uses Impspector to make Impspector fight The Grey Rider
BHawk uses Impspector to purge a card  at random from dmikalova's hand
dmikalova purges Aquilia, Lone Hero at random
BHawk uses Infurnace to make Infurnace fight Securi-Droid
BHawk plays Gleeful Mayhem
BHawk gains an Æmber  due to Gleeful Mayhem's bonus icon
BHawk uses Gleeful Mayhem to deal 5 damage to Battlefield Evangelist and Specialist Guthrak
Ready phase - BHawk
BHawk readies their cards 
Draw phase - BHawk
BHawk draws 2 card  s to their maximum of 6
End of turn 5
dmikalova: 5 Æmber  (0 keys) BHawk: 3 Æmber  (0 keys)
TURN 6 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses saurian  as their active house this turn
Main phase - dmikalova
dmikalova plays Beware the Ides
dmikalova gains an Æmber  due to Beware the Ides's bonus icon
dmikalova plays Arm the Plebeians
dmikalova gains an Æmber  due to Arm the Plebeians's bonus icon
dmikalova draws a card  due to Arm the Plebeians's bonus icon
dmikalova uses Arm the Plebeians to make a token creature
dmikalova discards Pale Into Insignificance
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 4 card  s to their maximum of 6
 dmikalova declares Check!
End of turn 6
dmikalova: 7 Æmber  (0 keys) BHawk: 3 Æmber  (0 keys)
TURN 6 - BHawk
Key phase - BHawk
BHawk does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - BHawk
BHawk chooses logos  as their active house this turn
BHawk moves all the cards  in their archives to their hand
Main phase - BHawk
BHawk plays Effervescent Principle
BHawk uses Effervescent Principle to gain a chain and make both players lose half their Æmber 
BHawk discards Munchling
BHawk uses Auto-Encoder to archive a card 
BHawk discards Quixo the “Adventurer”
BHawk uses Auto-Encoder to archive a card 
BHawk discards Bot Bookton
BHawk uses Auto-Encoder to archive a card 
Ready phase - BHawk
BHawk readies their cards 
Draw phase - BHawk
BHawk draws 1 card  to their maximum of 6
BHawk's chains are reduced by 1 to 0
End of turn 6
dmikalova: 4 Æmber  (0 keys) BHawk: 2 Æmber  (0 keys)
TURN 7 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses staralliance  as their active house this turn
Main phase - dmikalova
dmikalova plays Stealthster
dmikalova plays The Ulfberht Device
dmikalova gains an Æmber  due to The Ulfberht Device's bonus icon
dmikalova uses Operations Officer Yshi to reap with Operations Officer Yshi
dmikalova plays PYR*0
dmikalova deals 1 damage to Operations Officer Yshi due to PYR*0's bonus icon
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 3 card  s to their maximum of 6
 dmikalova declares Check!
End of turn 7
dmikalova: 6 Æmber  (0 keys) BHawk: 2 Æmber  (0 keys)
TURN 7 - BHawk
Key phase - BHawk
BHawk does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - BHawk
BHawk chooses saurian  as their active house this turn
Main phase - BHawk
BHawk plays Saurus Rex
BHawk plays Citizen Shrix
BHawk uses Citizen Shrix to exalt Citizen Shrix and steal 1 Æmber 
BHawk plays Ancient Power
BHawk gains an Æmber  due to Ancient Power's bonus icon
BHawk captures an Æmber  on Saurus Rex due to Ancient Power's bonus icon
BHawk uses Ancient Power to ward all friendly creatures with Æmber  on it
BHawk plays Consul Primus
Ready phase - BHawk
BHawk readies their cards 
Draw phase - BHawk
BHawk draws 5 card  s to their maximum of 6
End of turn 7
dmikalova: 4 Æmber  (0 keys) BHawk: 4 Æmber  (0 keys)
TURN 8 - dmikalova
Key phase - dmikalova
dmikalova does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - dmikalova
dmikalova chooses sanctum  as their active house this turn
Main phase - dmikalova
dmikalova uses Katerina the Summoner to reap with Katerina the Summoner
dmikalova uses Katerina the Summoner to capture 1 Æmber  from their opponent , placing it on Katerina the Summoner
dmikalova uses Katerina the Summoner to capture 1 Æmber  from their opponent , placing it on Katerina the Summoner
dmikalova plays Light Everlasting
dmikalova gains an Æmber  due to Light Everlasting's bonus icon
dmikalova uses Light Everlasting to play The Grey Rider
dmikalova plays The Grey Rider
dmikalova uses The Grey Rider to ready and fight with a neighboring creature
dmikalova uses PYR*0 to make PYR*0 fight Saurus Rex
Saurus Rex's ward token prevents the damage dealt by PYR*0 and is discarded
Citizen Shrix's ward token prevents the damage dealt by PYR*0 and is discarded
dmikalova plays One Stood Against Many
dmikalova gains an Æmber  due to One Stood Against Many's bonus icon
dmikalova uses One Stood Against Many to make Bellatoran Warrior fight against 3 different creatures
dmikalova uses Bellatoran Warrior to make Bellatoran Warrior fight Saurus Rex
Bellatoran Warrior's ward token prevents the damage dealt by Saurus Rex and is discarded
dmikalova uses Bellatoran Warrior to make Bellatoran Warrior fight Citizen Shrix
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 2 card  s to their maximum of 6
 dmikalova declares Check!
End of turn 8
dmikalova: 8 Æmber  (0 keys) BHawk: 2 Æmber  (0 keys)
TURN 8 - BHawk
Key phase - BHawk
BHawk does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - BHawk
BHawk chooses logos  as their active house this turn
Main phase - BHawk
BHawk plays Diametric Charge
BHawk gains an Æmber  due to Diametric Charge's bonus icon
BHawk uses Diametric Charge to deal 1 damage to Operations Officer Yshi and 2 to their neighbors
Ready phase - BHawk
BHawk readies their cards 
Draw phase - BHawk
BHawk draws 1 card  to their maximum of 6
End of turn 8
dmikalova: 8 Æmber  (0 keys) BHawk: 3 Æmber  (0 keys)
TURN 9 - dmikalova
Key phase - dmikalova
dmikalova forges the yellow key  , paying 6 Æmber 
BHawk uses Forge Compiler to destroy Forge Compiler and ward each friendly creature
House phase - dmikalova
dmikalova chooses saurian  as their active house this turn
dmikalova moves all the cards  in their archives to their hand
Main phase - dmikalova
dmikalova discards Crushing Charge
dmikalova plays Chancellor Dexterus
dmikalova plays Aquilia, Lone Hero
dmikalova plays Imperator Drusilla
dmikalova deals 1 damage to Saurus Rex due to Imperator Drusilla's bonus icon
Saurus Rex's ward token prevents the damage dealt by a bonus icon and is discarded
dmikalova uses Imperator Drusilla to destroy Chancellor Dexterus
dmikalova uses Bellatoran Warrior to reap with Bellatoran Warrior
dmikalova plays Symposium
dmikalova uses Symposium to exalt, ready, and use Bellatoran Warrior
dmikalova uses Bellatoran Warrior to make Bellatoran Warrior fight Saurus Rex
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 3 card  s to their maximum of 6
End of turn 9
dmikalova: 4 Æmber  (1 key) BHawk: 4 Æmber  (0 keys)
TURN 9 - BHawk
Key phase - BHawk
BHawk does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - BHawk
dmikalova
hmm that should have let me use two creatures but that's fine
BHawk
manual?
BHawk
to reap or something?
dmikalova
nah it's fine
BHawk
yeah that card  has been bugged
BHawk chooses dis  as their active house this turn
BHawk moves all the cards  in their archives to their hand
Main phase - BHawk
dmikalova
I can file a ticket
BHawk plays Mark of Dis
BHawk gains an Æmber  due to Mark of Dis's bonus icon
BHawk uses Mark of Dis to deal 2 damage to Stealthster
BHawk plays Break-key
BHawk gains an Æmber  due to Break-key's bonus icon
BHawk uses Break-key to cause dmikalova to unforge a key and gain 6 Æmber 
BHawk unforges dmikalova's yellow key 
BHawk plays Double Doom
BHawk uses Double Doom to return Katerina the Summoner to owners hand and discard random card 
dmikalova discards C.R. Officer Hawkins at random
BHawk plays Infurnace
BHawk chooses option ' Opponent's '
BHawk uses Infurnace to purge Echo Reflector and Arm the Plebeians
BHawk uses Infurnace to make dmikalova lose 2 Æmber 
BHawk plays Waking Nightmare
BHawk gains an Æmber  due to Waking Nightmare's bonus icon
BHawk uses Waking Nightmare to increase key cost by 1 for each Dis  creature during dmikalova's next turn
Ready phase - BHawk
BHawk readies their cards 
Draw phase - BHawk
BHawk draws 2 card  s to their maximum of 6
 BHawk declares Check!
End of turn 9
dmikalova: 8 Æmber  (0 keys) BHawk: 11 Æmber  (0 keys)
TURN 10 - dmikalova
Key phase - dmikalova
dmikalova forges the yellow key  , paying 7 Æmber 
House phase - dmikalova
dmikalova chooses staralliance  as their active house this turn
Main phase - dmikalova
dmikalova plays CPO Zytar
dmikalova uses Aquilia, Lone Hero without effect
dmikalova uses Stealthster to reap with Stealthster
dmikalova uses Stealthster to capture 1 Æmber  from their opponent , placing it on Stealthster
dmikalova uses Operations Officer Yshi to reap with Operations Officer Yshi
Ready phase - dmikalova
dmikalova readies their cards 
Draw phase - dmikalova
dmikalova draws 1 card  to their maximum of 6
End of turn 10
dmikalova: 3 Æmber  (1 key) BHawk: 10 Æmber  (0 keys)
TURN 10 - BHawk
Key phase - BHawk
BHawk
hey sorry gott to go
 BHawk concedes
 dmikalova has won the game
 BHawk has left the game
dmikalova
np have a good day

**Comment by sprek** [comment]
I've also seen this bug when symposium is used to take a strange shell back to your hand. It doesn't let you exalt and use another creature.

**Comment by romanogit** [comment]
Fixed by #3496
