### ISSUE TITLE
Bug with Friendship Upgrade

### ISSUE THREAD

**Issue by Ciampone** [keyteki/keyteki#3446]
I was playing against a deck with the friendship upgrade. I used my creature with splash againts the enemies creature with friendship, and killed all it's neighbors with the splash damage. But, after that, the game showed me a prompt to chose a neighrbor, based on friendship. But there was no neighbors anymore to select, as seen in the photo attached (I send the picture to my opponent, that's why my hand is covered)
![WhatsApp Image 2023-08-05 at 10 49 39](https://github.com/keyteki/keyteki/assets/71937565/876d0b95-d464-496a-93c0-fdba27eae3f1)

**Comment by romanogit** [comment]
This one was though! Splash attack should not kill neighbors before redistributing the damage from Friendship.
