### ISSUE TITLE
Tourist Trap swaps control when conditions aren’t satisifed

### ISSUE THREAD

**Issue by siaka-kf** [keyteki/keyteki#3447]
I have 1 token on board and my opponent has nothing. I use Tourist Trap. 

Expected: Nothing should happen. 
Actual: My opponent gains control of the token.

**Comment by romanogit** [comment]
I could not reproduce the behavior you mentioned, but I found a bug when you have no token creature and your opponent has a creature.

I would need more data to reproduce. Anyway, I am submitting a PR with tests
