### ISSUE TITLE
Timmoty The dammed not properly limited by "controling a token" condition

### ISSUE THREAD

**Issue by sukorski** [keyteki/keyteki#3451]
For at least 2 turns, my opponent did not forge a key, even though I did not have tokens.
Please find attached the best print I took before reading your "read here before you post a bug", then I had alreay left the match.
Thanks

![Capture](https://github.com/keyteki/keyteki/assets/142242866/a31be9ce-8b8d-4b99-b11a-24a22b6e1fcf)

**Comment by strib** [comment]
@romanogit maybe one of the creatures used to be a token and is still counting as a token, just like those other issues that leave a token action on the card that used to be a token?

**Comment by sukorski** [comment]
@strib it makes sense, my deck had Maelstrom and I'm 90% sure that one of the Ekwidon cards had been a token before in the match. In case it helps, my deck is "The Editor that Sits with Prophecy"

**Comment by romanogit** [comment]
The "was a token" problem is fixed, let me know if the problem persists.
