### ISSUE TITLE
Used Fresh Marks and select to exalt 2 enemy creatures, no enemy creatures been exalted

### ISSUE THREAD

**Issue by kennethkchiu** [keyteki/keyteki#3467]
Used Fresh Marks and select to exalt 2 enemy creatures, no enemy creatures been exalted

**Comment by strib** [comment]
Were they token creatures?  There is a bug right now that's not showing any tokens or counters on token creatures.  It is fixed in the code but not yet deployed.

**Comment by kennethkchiu** [comment]
Those two were token creatures. After I fought and destroyed the token creatures, I didn't capture and amber from the exalt.

**Comment by romanogit** [comment]
Need a game log on this, let me know if it still occurs
