### ISSUE TITLE
Verify account

### ISSUE THREAD

**Issue by Solagrenouille** [keyteki/keyteki#347]
Hello,

I register an account two times, both I didn't receive a verification account email.
I read a related issue and it says that it this no longer necessary. However, I tried to login and I still have this message ''You must verifiy your account before trying to log in''.

**Comment by cryogen** [comment]
What’s your account name? Maybe you registered it before verification was turned off

**Comment by Solagrenouille** [comment]
It is Solagrenouille.

**Comment by cryogen** [comment]
That should be verified for you now

**Comment by Solagrenouille** [comment]
Thanks!!
