### ISSUE TITLE
After creating token with Nirbor, tokens shown with their card showing instead of token back (half card size)

### ISSUE THREAD

**Issue by xoque** [keyteki/keyteki#3471]
Playing today on 8/28, after destroying Nirbor and making a token, the token appears as the card instead of the card back. After creating another token with Stratosmack, it too showed as the card. The opponent still only saw the tokens and not the cards.

![image](https://github.com/keyteki/keyteki/assets/19242747/f8718338-7dc3-4954-9f42-7437f3ff805d)

Log:
XoquE brings Preposterous Urien of the Avenue to The Crucible
blackholeX brings Trader Daniel Cottonharm to The Crucible
XoquE won the flip and is first player
 blackholeX has connected to the game server
 XoquE has connected to the game server
XoquE is shuffling their deck
XoquE draws 6 card  s to their maximum of 6
blackholeX is shuffling their deck
blackholeX draws 6 card  s to their maximum of 6
XoquE draws 1 card 
Key phase - XoquE
XoquE does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - XoquE
XoquE chooses staralliance  as their active house this turn
Main phase - XoquE
XoquE plays Recorded History
XoquE gains an Æmber  due to Recorded History's bonus icon
XoquE uses Recorded History to archive Red Alert, Membership Drive, and Harmal Atoon
Ready phase - XoquE
Draw phase - XoquE
XoquE draws 3 card  s to their maximum of 6
End of turn 1
XoquE: 1 Æmber  (0 keys) blackholeX: 0 Æmber  (0 keys)
TURN 1 - blackholeX
Key phase - blackholeX
blackholeX does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - blackholeX
blackholeX chooses brobnar  as their active house this turn
Main phase - blackholeX
blackholeX plays Nirbor Flamewing
blackholeX draws a card  due to Nirbor Flamewing's bonus icon
blackholeX plays Crogg the Clumsy
Ready phase - blackholeX
blackholeX readies their cards 
Draw phase - blackholeX
blackholeX draws 2 card  s to their maximum of 6
End of turn 1
XoquE: 1 Æmber  (0 keys) blackholeX: 0 Æmber  (0 keys)
TURN 2 - XoquE
Key phase - XoquE
XoquE does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - XoquE
XoquE chooses sanctum  as their active house this turn
Main phase - XoquE
XoquE plays Colonel Mariana
XoquE plays Ostentatious Mount attaching it to Colonel Mariana
XoquE gains an Æmber  due to Ostentatious Mount's bonus icon
XoquE draws a card  due to Ostentatious Mount's bonus icon
XoquE uses Ostentatious Mount to move Colonel Mariana and give it taunt
XoquE plays Outflank
XoquE gains an Æmber  due to Outflank's bonus icon
Ready phase - XoquE
XoquE readies their cards 
Draw phase - XoquE
XoquE draws 2 card  s to their maximum of 6
End of turn 2
XoquE: 3 Æmber  (0 keys) blackholeX: 0 Æmber  (0 keys)
TURN 2 - blackholeX
Key phase - blackholeX
blackholeX does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - blackholeX
blackholeX chooses brobnar  as their active house this turn
Main phase - blackholeX
blackholeX plays Brikk Nastee
blackholeX uses Nirbor Flamewing to make Nirbor Flamewing fight Colonel Mariana
blackholeX uses Nirbor Flamewing to make a token creature
blackholeX uses Brikk Nastee to gain 1 Æmber 
blackholeX plays Stratosmack
blackholeX uses Stratosmack to deal 3 damage to Colonel Mariana
blackholeX uses Crogg the Clumsy to reap with Crogg the Clumsy

**Comment by romanogit** [comment]
Fixed
