### ISSUE TITLE
Ragnarok Prep doesn't make the opponent lose aember.

### ISSUE THREAD

**Issue by vulinhchelsea** [keyteki/keyteki#3489]
Please find the game log and the screenshot attached, it should make opponent lose 2 aember as I have more creature.
![Screenshot 2023-09-23 104855](https://github.com/keyteki/keyteki/assets/85331895/6687f474-f174-4890-817a-c2ff14f1114f)
[Game Log.txt](https://github.com/keyteki/keyteki/files/12705557/Game.Log.txt)

**Comment by mariofuest** [comment]
In my experience, the aember loss works as expected, it's just the text in the log that's missing.

**Comment by Kebay** [comment]
In my experience, the aember loss works as expected, it's just the text in the log that's missing.
