### ISSUE TITLE
Newly added decks don’t go to the top of the list

### ISSUE THREAD

**Issue by cryogen** [keyteki/keyteki#350]
decks are sorted by most recently added, when a new deck is added it goes to the bottom instead of the top

**Comment by romanogit** [comment]
This one seems a quick fix, so I gave it a try.

**Comment by romanogit** [comment]
Sent a pull request for this one:
https://github.com/keyteki/keyteki/pull/370

**Comment by romanogit** [comment]
@cryogen , 
I believe we can close this one, after pull merge

**Comment by romanogit** [comment]
This one can be close (I now learnt how to do it automatically)
