### ISSUE TITLE
Revna Starsong vs exchanged Berserkers

### ISSUE THREAD

**Issue by fakatwork** [keyteki/keyteki#3519]
Need to investigate possible bug with Revna: managed to "exchange" a Berserker from my opponent. They had Revna on board. When I later called Brobnar I was able to attack with the Berserker but it didn't self-destruct like it should. 

I suspect the check is around Berserker's owner when it should be around its current controller. Revna should only apply to friendly Berserkers.

**Comment by jakelea99** [comment]
Same issue on me.
