### ISSUE TITLE
Alpha and omega under jargogle

### ISSUE THREAD

**Issue by AleksandrShepelev** [keyteki/keyteki#352]
if jargogle is destroyed on controller player turn by fight of any card except for strange gizmo, alpha card should be discarded and omega card should end turn.
Now alpha cards are not discarded, omega do not end turn

**Comment by romanogit** [comment]
@jeremylarner ,
this is a report that Jargogle can play Alpha and does not end with Omega.

**Comment by romanogit** [comment]
Added test cases and Alpha and Omega under Jargogle are now working.
