### ISSUE TITLE
ultragraviton bug

### ISSUE THREAD

**Issue by funderelele6** [keyteki/keyteki#3536]
It's the first turn, the deck has only one ultra graviton, but it appears as if it had two bottom parts and it doesn't let me play it, I don't know if it doesn't let me play it because it is two bottom parts or because it reads it as two cards instead of one to play in the first turn.
capture: 
![captura completa](https://github.com/keyteki/keyteki/assets/150404513/b96f9a0a-2491-4ec2-a62d-a65a7ec3a3aa)

close capture: ![ULTRAGRAVITON](https://github.com/keyteki/keyteki/assets/150404513/f91a9e5d-56d8-44ad-8356-0f6836adb2ba)

chat log: funderelele is shuffling their deck
funderelele draws 6 card  s to their maximum of 6
chacotei5 is shuffling their deck
chacotei5 draws 6 card  s to their maximum of 6
funderelele draws 1 card 
Key phase - funderelele
funderelele does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - funderelele
funderelele chooses logos  as their active house this turn.

**Comment by funderelele6** [comment]
I removed the deck from my pool and re-imported it and now it seems to work.

**Comment by romanogit** [comment]
Deck issue - reimport solved
