### ISSUE TITLE
project zyx ignores alpha/omega effects

### ISSUE THREAD

**Issue by lupo82** [keyteki/keyteki#355]
i reap with project zyx, i play duskwitch from my archives, it doesn't end my turn as it should

**Comment by 4ugeistr** [comment]
Had the same issue with Jargogle.
"Played" the Duskwitch by fighting with the Jargogle during my turn.
The turn should've ended immediately, but didn't.

Here's the rule discussion:
https://www.reddit.com/r/KeyforgeGame/comments/butflq/wild_wormhole_alphaomega_cards/

![image](https://user-images.githubusercontent.com/23107141/63372652-377a1c80-c38f-11e9-9143-3148838c1550.png)

**Comment by romanogit** [comment]
This is fixed. Same issues happened with Jargogle. Added test cases to validate.
See https://github.com/keyteki/keyteki/pull/1436
