### ISSUE TITLE
Director Z.Y.X Skipping Archive

### ISSUE THREAD

**Issue by Jarimy123** [keyteki/keyteki#356]
Had Director Z.Y.X out for several turns and he archived.  My opponent played Miasma and then Director did not archive.  This actually work that way?  I wouldn't think so.  It appears to me it's not working after Miama is played.

![DIRECTOR](https://user-images.githubusercontent.com/46849213/63375296-82793d00-c359-11e9-8335-97cbf2fb1319.jpg)

**Comment by jghomel** [comment]
Same bug exists with The Sting. All "at the beginning of the turn" effects seem to occur during the forge a key step.

**Comment by Daguerreo** [comment]
I can confirm the bug. A full report with the occurring bug can be found here:

https://www.thecrucibletracker.com/games/41ad4860-e9f7-11e9-a8cd-73a993355014/log

**Comment by jtrussell** [comment]
I came across this as well and was a little confused by the rules and [the timing chart put out by FFG](https://i.redd.it/3a6wgk783mk31.jpg). From those, It *looks* like start of turn effects explicitly trigger during the forge a key step. If you're strictly following that chart then you could argue that skipping the forge step causes you to skip all start of turn effects too.

It does seem natural that start of turn effects would trigger even if you skip that step, but then I'm not sure what the timing looks like - i.e. if they trigger during your choose a house phase, would it be before you choose a house, before/after "after you choose a house" effects like Memory Chip trigger, or later?

If there's official word from FFG on this - I'd love to see it 😄.

**Comment by Achocholacek** [comment]
Right now, the "official word" from FFG is the timing chart, which means the ZYX step being skipped is the "right" way to do things.

There might be a tweak to this in the WC RRG as this came up for discussion in the last few weeks and got a lot of eyes on it, but for now I think it's behaving as it should.
