### ISSUE TITLE
Shadow of dis

### ISSUE THREAD

**Issue by Annina83** [keyteki/keyteki#359]
Hello ! I just noticed two wrong interactions (I think) with shadow of dis : indeed after the opponent played shadow of dis, I played Skullion and it asked me to destroy a creature... Later I played shadow of dis and opponent played fila and was able to draw for creatures near fila... Thanks for your help. Anna

**Comment by Nerapiuma** [comment]
I'm here only to up this and report so much more issues with "Shadow of Dis".
When I play the card my opponent's creatures still be able to activate any abilities they have. So wrong ahahah :)
Ty for your work.

**Comment by cryogen** [comment]
@Nerapiuma Shadows of dis works in the majority of cases, so you'll need to provide more information about what is special about your case for it to be fixed

**Comment by Nerapiuma** [comment]
@cryogen Ah wow so i've been really unluky i think ahah.
Ok so i've played Shadow of Dis and my opponent played in his next turn Charrette and capture 3 from me and then an Onyx Knight ad trigger is play ability.
Another issues from a Z.Y.X. Researcher that come in to play and trigger is ability.
I think the biggest problem it's the play ability, maybe.
Ty so much, as usual :)

**Comment by Nerapiuma** [comment]
@cryogen add another issues coming out right now.
I've played Shadow of Dis, my opponent Wormhole in to a Chota and still loose one Aember

**Comment by cryogen** [comment]
I don't think that it's supposed to, but it's not at all clear.  Have updated that issue accordingly

**Comment by benjamintownsend** [comment]
Just had an issue with Shadow of Dis and Yxlix Dominator. YD has the text 'Yxlix Dominator enters play stunned' and was stunned when I played it. But SoD was in effect so it shouldn't have been stunned, right?

**Comment by stebsteb** [comment]
> Just had an issue with Shadow of Dis and Yxlix Dominator. YD has the text 'Yxlix Dominator enters play stunned' and was stunned when I played it. But SoD was in effect so it shouldn't have been stunned, right?

Mmm, its not so clear for this one as it isn't a "Play:" effect.

**Comment by benjamintownsend** [comment]
Thinking on it it shouldn't effect Yxlix Dominator. It's like Alpha cards, Alpha creatures are effected by Shadow of Dis as the alpha ability is active when it is played from your hand. So likewise YD should be stunned even when SoD is in effect.

**Comment by romanogit** [comment]
Both scenarios (fila and skullion should be fixed)
Yxlix Dominator enters play stunned, so it is not a play effect and working as expected
