### ISSUE TITLE
Poltergeist malfunctions targeting the player's own artifacts

### ISSUE THREAD

**Issue by YuliYudith** [keyteki/keyteki#361]
When targeting my own artifacts with Poltergeist, the artifact is destroyed but is not used. 

When targeting an opponent's artifact it works correctly.

**Comment by romanogit** [comment]
Can you tell us which of your own artifact you tried to use?

**Comment by YuliYudith** [comment]
The warchest. I killed 3 creatures in a fight and used it after I killed them.

**Comment by romanogit** [comment]
I was not able to reproduce it:

![image](https://user-images.githubusercontent.com/2104075/63600558-27825880-c59a-11e9-9cb8-4e7ec5ca08e1.png)

![image](https://user-images.githubusercontent.com/2104075/63600582-323ced80-c59a-11e9-9993-1f3783f37eb5.png)

```
romano2 uses Stealer of Souls to make Stealer of Souls fight Redlock
romano2 uses Stealer of Souls to purge Redlock
romano2 uses Pit Demon to make Pit Demon fight Yantzee Gang
romano2 uses Pit Demon to make Pit Demon fight Yantzee Gang
romano2 plays Poltergeist, gaining 1 Æmber
romano2 uses Poltergeist to use The Warchest and destroy it
romano2 uses The Warchest to gain 3 Æmber 
```

**Comment by YuliYudith** [comment]
Then it was a one time thing or I made a mistake. It was your own artifact?

Thanks for checking.

**Comment by romanogit** [comment]
Yes, it was my own artifact.
I am thinking here, did you "fight" the creatures you destroyed. `The Warchest` is pretty specific.
"Action: Gain 1 for each enemy creature that was destroyed in a fight this turn". The enemy creatures have to be destroyed in a fight.

**Comment by YuliYudith** [comment]
Yes, I fought them.

**Comment by romanogit** [comment]
Ok, we would need to see all the battle line. Maybe something is blocking the usage, such as Tentacus (Your opponent must pay you 1A in order to use an artifact.)

**Comment by romanogit** [comment]
Unable to reproduce. Created a new test https://github.com/keyteki/keyteki/pull/1115
