### ISSUE TITLE
Cult the weak and Soulkeeper

### ISSUE THREAD

**Issue by nikiva** [keyteki/keyteki#365]
Hi,

My opponent had a Bad Penny and Urchin on board. I played the Soulkeeper on Urchin and the used Cult the weak to destroy the Urchin. However, the effect of Soulkeeper did not destroy Bad Penny.

**Comment by romanogit** [comment]
I think you should prompted to select the most powerful creature. Since both Bad Penny and Urchin are still in play during Destroyed effect, in theory, you should be able to destroy Bad Penny or Urchin (silly choice, but possible)

**Comment by romanogit** [comment]
If your opponent had a Bad Penny and an Urchin, the Soulkeeper would never destroy Bad Penny because it says: "Destroyed: Destroy the most powerful **enemy** creature.”
Bad Penny was not an enemy of Urchin.
If bad Penny was yours, then it would destroy yours

**Comment by romanogit** [comment]
Not a bug
