### ISSUE TITLE
Earthbind ruling

### ISSUE THREAD

**Issue by CrookedWookie** [keyteki/keyteki#366]
I heard from Danny Schaefer today, who discussed it with Brad and they came up with a ruling on an Earthbind effect that I thought might be of interest to the Crucible:

Hey Brett,
I talked it over with Brad, and we came to a conclusion.

Because Earthbind’s ability doesn’t specify where the card has to be discarded from, it works with any “discard” effect, including cards that discard from deck or archive. Therefore discarding cards using a Homeworld Portal would allow you to use a creature with Eartbhind on it.

**Comment by Achocholacek** [comment]
Huh. Duly noted. Also, gross. But SO SPAKETH ANDRES. Thanks for letting us know.

**Comment by romanogit** [comment]
Looks like we have some different opinions:
https://archonarcana.com/index.php?title=Earthbind

![image](https://user-images.githubusercontent.com/2104075/68176821-7c9bfc80-ff43-11e9-9df9-86e440622199.png)
