### ISSUE TITLE
Master the Theory

### ISSUE THREAD

**Issue by CalumSLZ** [keyteki/keyteki#375]
Master theory says 'may' archive, so i should be able to choose to archive fewer cards than my opponent has creatures even if the board is empty. However it forces you to archive that number, so leaving no choice.

**Comment by cryogen** [comment]
I suppose that depends on how you read the card. That way I read it (and there being no “up to” involved) I’d say the way we have it is right. But if you can point me at a ruling that says otherwise we can change it

**Comment by 4ugeistr** [comment]
From Discord #rules-questions:
![image](https://user-images.githubusercontent.com/23107141/63843172-9c84d200-c98e-11e9-9479-73e2aa27a94f.png)

**Comment by ryanch** [comment]
I'll see if I can get a pull request up for this.
