### ISSUE TITLE
Possible Soulkeeper Issue

### ISSUE THREAD

**Issue by justicewebtech** [keyteki/keyteki#377]
Opponent had Yantzee Gang upgraded with Soulkeeper.

I had a board that included Dharna, Rustgnawer, Yxilx Dominator and a couple others.

I played Extinction on their Yantzee Gang.

My Dominator was destroyed via Soulkeeper.
Then their Yantzee Gang was destroyed by my extinction.
My Dharna was destroyed as it shared the trait "elf" via extinction.
And then it appeared that Soulkeeper triggered again and made me choose to kill off Rustgnawer.

**Comment by romanogit** [comment]
Fixed by Timing Refactor:

![image](https://user-images.githubusercontent.com/2104075/101218475-e2384c00-3661-11eb-8ae0-9cfc2c02f999.png)
