### ISSUE TITLE
2 Bryozoarch under my control results in my opponents action destroy 2 creatures

### ISSUE THREAD

**Issue by abeautifuljune** [keyteki/keyteki#3798]
2 Bryozoarch under my control results in my opponents action destroy 2 creatures. Bryozoarch has a replacement effect over actions. I don't believe the 2nd Bryozoarch has an effect to replace so only 1 creature would be destroyed.

**Comment by fakatwork** [comment]
Duplicate of https://github.com/keyteki/keyteki/issues/3539
