### ISSUE TITLE
Curse of Spontaneity artifact

### ISSUE THREAD

**Issue by pieeater81** [keyteki/keyteki#3803]
Curse of Spontaneity artifact did not enter play under opponents control.  When I played it it entered play under my control.

**Comment by strib** [comment]
Should be fixed now (stale JSON data cache).

**Comment by pieeater81** [comment]
In the test game I played by myself the curse artifact entered play under my control, unsure if this is as I didn’t have an opponent though.

**Comment by cryogen** [comment]
Yes you need an opponent for opponent affecting effects to trigger. Closing as a data issue
