### ISSUE TITLE
Plague Wind -3 power not showing

### ISSUE THREAD

**Issue by pieeater81** [keyteki/keyteki#3806]
After playing Plague Wind not all non-Mars creatures were shown to get -3 power until the end of the turn.  See image for the Immersioneer Unfathomable creature not receiving -3 power until the end of the turn.
![IMG_0271](https://github.com/keyteki/keyteki/assets/158294704/ec9f7c35-d201-4dd6-80c0-582407cd43ca)

**Comment by strib** [comment]
Should be good on the dev server now.
