### ISSUE TITLE
Singing Scythe - after reap purge

### ISSUE THREAD

**Issue by pieeater81** [keyteki/keyteki#3809]
After reaping with the upgrade singing scythe attached to one of my creatures I did not get the opinion to purge a card from a discard pile despite being haunted. 
![IMG_0273](https://github.com/keyteki/keyteki/assets/158294704/f5f27f31-7303-4901-9810-d967a43a1d1e)

**Comment by strib** [comment]
The implementation for Singing Scythe has not yet been merged.  Please see https://github.com/keyteki/keyteki/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc for a list of cards still in progress.

**Comment by strib** [comment]
Should be good on the dev server now.
