### ISSUE TITLE
Plan 10 issues

### ISSUE THREAD

**Issue by CatMarrow** [keyteki/keyteki#3825]
Plan 10 duplicates creatures that are not controlled by their owner. This causes a variety of other issues such as being able to play creatures that are already in play, allowing creatures in play to be selected to be returned to hand as though they are under plan 10, potential aember duplication if the creature affected has captured aember, and some other bizarre occurrences.

**Comment by CatMarrow** [comment]
The creature on the board is not removed from the board, but it also goes under Plan 10. 

As such, there is now a second copy of the creature.
![image](https://github.com/keyteki/keyteki/assets/50786711/2db5dcdf-46ec-4735-b006-ae5d5d8a878c)

Attached is an image from a game I played earlier.

**Comment by CatMarrow** [comment]
![image](https://github.com/keyteki/keyteki/assets/50786711/d6c948b4-e8e4-483e-8655-93c8c630166d)

**Comment by CatMarrow** [comment]
![image](https://github.com/keyteki/keyteki/assets/50786711/edeb5c0e-66cf-4130-99f5-afe1be00b7d3)

Plan 10 can also move out of the Artifact Line into the same plane as the Battleline. It then creates a weird ghost card where Plan 10 should normally be.

**Comment by CatMarrow** [comment]
![image](https://github.com/keyteki/keyteki/assets/50786711/d2149ac8-f06a-4f72-9dee-c400f51dbb19)

And even after Plan 10 is destroyed, the ghost card remains in the corner.

**Comment by strib** [comment]
Should be good on the dev server now.
