### ISSUE TITLE
Incorect deck list for Sealed deck

### ISSUE THREAD

**Issue by Ugluk4242** [keyteki/keyteki#3832]
I played a sealed game in wich I was assigned the deck: https://www.keyforgegame.com/deck-details/140a96c1-2086-4f24-afbe-19359d218a26.

The deck list in TCO included 2 Dis cards (Grim Reminder and Spyyder) which are not in the deck in the MasterVault.

![image](https://github.com/keyteki/keyteki/assets/68158046/8963a154-91eb-404a-9b33-375934541066)
![image](https://github.com/keyteki/keyteki/assets/68158046/0e0e0828-bdde-4ec2-8162-7ce3328abba5)

**Comment by cryogen** [comment]
Strange. The deck imports fine and there's at least one other user with it correctly added (which is also available in sealed). I've removed the broken instance from the sealed pool.
