### ISSUE TITLE
Westbur does not discard cards from top of deck after fight

### ISSUE THREAD

**Issue by Murph117** [keyteki/keyteki#3833]
<img width="1239" alt="Screenshot 2024-02-05 114631" src="https://github.com/keyteki/keyteki/assets/137451394/697ee0c0-38ed-4f20-85ea-00ac55822bf1">

The **After Fight:** effect on Westbur does not trigger.

Murph117_dev brings Adm. Jossaiz, the Mutable Death Knight to The Crucible
Murph117_alt brings Toymaker Branson to The Crucible
Murph117_alt won the flip and is first player
 Murph117_dev has connected to the game server
 Murph117_alt has connected to the game server
Murph117_dev is shuffling their deck
Murph117_dev draws 6 card  s to their maximum of 6
Murph117_alt is shuffling their deck
Murph117_alt draws 6 card  s to their maximum of 6
Murph117_alt draws 1 card 
Key phase - Murph117_alt
Murph117_alt does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Murph117_alt
Murph117_alt chooses geistoid as their active house this turn
Main phase - Murph117_alt
Murph117_alt plays Webstur
Murph117_alt discards Com. Officer Palik due to Webstur's bonus icon
Ready phase - Murph117_alt
Murph117_alt readies their cards 
Draw phase - Murph117_alt
Murph117_alt draws 1 card  to their maximum of 6
End of turn 1
Murph117_dev: 0 Æmber  (0 keys) Murph117_alt: 0 Æmber  (0 keys)
TURN 1 - Murph117_dev
Key phase - Murph117_dev
Murph117_dev does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Murph117_dev
Murph117_dev chooses unfathomable  as their active house this turn
Main phase - Murph117_dev
Murph117_dev plays Kamalani
Murph117_dev deals 1 damage to Webstur due to Kamalani's bonus icon
Murph117_dev plays Giltspine Netcaster
Murph117_dev plays Kelpminder
Ready phase - Murph117_dev
Murph117_dev readies their cards 
Draw phase - Murph117_dev
Murph117_dev draws 3 card  s to their maximum of 6
End of turn 1
Murph117_dev: 0 Æmber  (0 keys) Murph117_alt: 0 Æmber  (0 keys)
TURN 2 - Murph117_alt
Key phase - Murph117_alt
Murph117_alt does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Murph117_alt
Murph117_alt chooses geistoid as their active house this turn
Main phase - Murph117_alt
Murph117_alt plays Touchstone
Murph117_alt plays Exchange Officer
Murph117_alt plays Darklamp
Murph117_alt plays Soul Vial
Murph117_alt gains an Æmber  due to Soul Vial's bonus icon
Murph117_alt discards Ravening Morphazoid due to Soul Vial's bonus icon
Murph117_alt uses Webstur to make Webstur fight Kelpminder
Ready phase - Murph117_alt
Murph117_alt readies their cards 
Draw phase - Murph117_alt
Murph117_alt draws 5 card  s to their maximum of 6
End of turn 2
Murph117_dev: 0 Æmber  (0 keys) Murph117_alt: 1 Æmber  (0 keys)
TURN 2 - Murph117_dev
Key phase - Murph117_dev
Murph117_dev does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Murph117_dev
Murph117_dev chooses unfathomable  as their active house this turn
Main phase - Murph117_dev
Murph117_dev uses Kamalani to reap with Kamalani
Murph117_dev uses Giltspine Netcaster to reap with Giltspine Netcaster
Murph117_dev uses Giltspine Netcaster to exhaust Touchstone
Murph117_dev plays Abyssal Sight
Murph117_dev gains an Æmber  due to Abyssal Sight's bonus icon
Murph117_dev uses Abyssal Sight to destroy Kamalani
Murph117_dev uses Kamalani to make 2 token creatures
Murph117_dev uses Cleric to capture 1 Æmber  from their opponent , placing it on Cleric
Ready phase - Murph117_dev
Murph117_dev readies their cards 
Draw phase - Murph117_dev
Murph117_dev draws 1 card  to their maximum of 6
End of turn 2
Murph117_dev: 3 Æmber  (0 keys) Murph117_alt: 0 Æmber  (0 keys)
TURN 3 - Murph117_alt
Key phase - Murph117_alt
Murph117_alt does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Murph117_alt
Murph117_alt chooses geistoid as their active house this turn
Main phase - Murph117_alt
Murph117_alt plays Memette
Murph117_alt uses Memette to archive Junk Restoration
Murph117_alt plays Harvest Skimmer
Murph117_alt uses Webstur to make Webstur fight Cleric

**Comment by strib** [comment]
Webstur is still waiting code review.  https://github.com/keyteki/keyteki/pull/3763
