### ISSUE TITLE
[GR] Down To Size allows (and forces) selection of own creatures

### ISSUE THREAD

**Issue by kensterel** [keyteki/keyteki#3838]
If you play Down To Size and there isn't an opposing creature it forces you to select your own. It should only allow enemy creatures:
`Play: Choose an enemy creature. Until the end of the turn, that creature is considered to have 1 power and 0 armor.`
https://archonarcana.com/Down_To_Size

**Relevant Log:**
```
Tuxedo plays Memette
Tuxedo uses Memette to archive Winds of Death
...
Tuxedo plays Down To Size
Tuxedo gains an Æmber  due to Down To Size's bonus icon
Tuxedo uses Down To Size to make Memette have 1 power and 0 amor until the end of the turn
```

**Comment by cryogen** [comment]
Fix for this should now be deployed
