### ISSUE TITLE
Shrink-ray tech scrap ability affects all creatures

### ISSUE THREAD

**Issue by TomGraafland** [keyteki/keyteki#3846]
3 Creatures were affected.

Log:
House phase - Harmed
Harmed chooses mars  as their active house this turn
Harmed moves all the cards  in their archives to their hand
Main phase - Harmed
Harmed plays Glyxl Proliferator
Harmed plays Nameless Horror
Harmed plays Ironyx Rebel
Harmed draws a card  due to Ironyx Rebel's bonus icon
Harmed uses Ironyx Rebel to ready Nameless Horror and Glyxl Proliferator
Harmed uses Glyxl Proliferator to reap with Glyxl Proliferator
Harmed uses Glyxl Proliferator to archive Psychic Network
Harmed uses Nameless Horror to make Nameless Horror fight Grabber Jammer
Harmed plays Ironyx Rebel
Harmed discards Lieutenant Halasta due to Ironyx Rebel's bonus icon
Harmed uses Lieutenant Halasta to stun Distant Void Prober
Harmed uses Ironyx Rebel to ready Ironyx Rebel and Glyxl Proliferator
Harmed uses Ironyx Rebel to reap with Ironyx Rebel
Harmed uses Glyxl Proliferator to reap with Glyxl Proliferator
Harmed uses Glyxl Proliferator to archive Airlock
Harmed plays Ironyx Rebel
Harmed captures an Æmber  on Ironyx Rebel due to Ironyx Rebel's bonus icon
Harmed uses Ironyx Rebel to ready Ironyx Rebel and Glyxl Proliferator
Harmed uses Glyxl Proliferator to reap with Glyxl Proliferator
Harmed uses Glyxl Proliferator to archive Sniffer
Harmed discards Shrink-ray Technician
Harmed uses Shrink-ray Technician to make Abduct-o-Matic have 1 power and 0 armor for the remainder of the turn

**Comment by strib** [comment]
Thanks, this was already fixed in #3810 and is waiting a server restart.
