### ISSUE TITLE
Shadow of Dis doesn't blank play effects

### ISSUE THREAD

**Issue by Shifuede** [keyteki/keyteki#386]
AFAIK, while deploy & alpha are effects active from your hand, play effects should be blanked.  When watching a friends game: 

1. Player A played shadow of Dis (their turn 7).  
2. Player B, on their turn 7, played Raiding Knight which captured an Aember.

**Comment by cryogen** [comment]
I do not think that it blanks alpha, as the card is not in play at that point.  Happy to be point at a ruling to the contrary though

**Comment by cryogen** [comment]
My bad, I did indeed not read properly!

**Comment by Herzbube76** [comment]
Rule question in Crucible Cast Ep. 10:

[https://www.youtube.com/watch?v=A-9GuxylqBs](url)

**Comment by Shifuede** [comment]
> Rule question in Crucible Cast Ep. 10:
> 
> [https://www.youtube.com/watch?v=A-9GuxylqBs](url)

Yes, that just confirms what I've already stated. My issue is that play effects, like Play: Capture should have been blanked, but weren't.

**Comment by Gimu87** [comment]
Up.
Same issue with Charette (Play: capture 3) today

**Comment by romanogit** [comment]
This is already fixed, added test cases to prove

**Comment by romanogit** [comment]
Reopening, looks like when I merged it to the #2577 PR, it failed.
