### ISSUE TITLE
NFL in GR has anomaly graphic and wrong house visually

### ISSUE THREAD

**Issue by Murph117** [keyteki/keyteki#3873]
![Screenshot 2024-02-20 183041](https://github.com/keyteki/keyteki/assets/137451394/c4e435c5-b7fd-43b7-95fc-aed459fc0d05)
![Screenshot 2024-02-20 183053](https://github.com/keyteki/keyteki/assets/137451394/ac124dc1-6ab4-4e95-b49f-83a07a363aad)
The same gamestate from two seperate account's POV.
Near Future Lens on one is a brobnar anomaly in a GR deck with no brobnar

**Comment by strib** [comment]
I noticed the same thing with a Geistoid Grim Reaper that is showing up graphically as Brobnar.

@cryogen any ideas why cards that used to be anomalies in older sets, but are now normal cards in GR, are showing up graphically in the wrong house?

**Comment by strib** [comment]
(By the way, this was not the case on the dev server, so something is different about prod.  Maybe just that more decks are loaded with the older versions of those cards?)

**Comment by joaodperes** [comment]
Issue is still present as of March 25th (Grim Reaper showing as brobnar instead of Geistoid)

**Comment by cryogen** [comment]
Has anyone affected tried deleting and reimporting the deck? I need an example deck to look at this if so

**Comment by strib** [comment]
@cryogen it's definitely still happening for half-sized card images.  Here is a sample deck where the card The Grim Reaper show as Geistoid when it's not in play, but on the board it shows as Brobnar as a half-sized card: https://www.keyforgegame.com/deck-details/aa8eb2ce-8eea-457e-acd4-693f9319286c

#3931 is something I noticed but not sure it is relevant.  I'm not able to load GR decks in the full site locally, so I can't figure out how to test this.  Does it seem plausible to you?

**Comment by strib** [comment]
Sorry, my fix didn't work :(  I need to figure out how half-sized cards work I guess.

**Comment by cryogen** [comment]
This should be fixed now
