### ISSUE TITLE
Dimo destroyed didn't activate

### ISSUE THREAD

**Issue by Rikuns** [keyteki/keyteki#3877]
So I played Braindart on Blypyp and then Genetic Blast killing it while Blypyp's battlefield has Dimo, Elderghast. I currently has 22 discards, so haunted and Blypyp should have Dimo destroyed effect and gave me 1 aember but nothing happened. 
![image](https://github.com/keyteki/keyteki/assets/83189520/646eb762-1a8b-4ade-acdb-ad27d36bb686)

**Comment by strib** [comment]
Thanks for the report.  The log shows the `Emperor_Riku` started the turn with 0 amber, and so the Braindart couldn't have actually put any amber on the Blypyp, so there was nothing for Dimo to do.
