### ISSUE TITLE
House Geistoid not showing up in the Choose a House menu for Draco Praeco

### ISSUE THREAD

**Issue by r0gershrubber** [keyteki/keyteki#3882]
I haven't checked any other creatures with similar menus.

![image](https://github.com/keyteki/keyteki/assets/48815035/0e58ad64-f758-439f-b264-05af996a395c)

**Comment by strib** [comment]
Thanks for the report.  I just tested this and it looks fine to me:
![image](https://github.com/keyteki/keyteki/assets/8516691/07d71343-b332-425c-b32b-e68bebb37f46)

It looks your screenshot is using the old color scheme, so maybe you just need a hard refresh in your browser window to load the new code?

**Comment by cryogen** [comment]
As above, you need the latest client code. Surprised much of anything works :)
