### ISSUE TITLE
Nexus doesn't trigger Guard Disguise to sacrifice when it can't steal

### ISSUE THREAD

**Issue by cdenlin** [keyteki/keyteki#389]
I had Guard Disguise (Action: Sacrifice Guard Disguise. If opponent has 3 or fewer Aember steal 3) and opponent tried to have Nexus (Reap: Use an opponent's artifact as if it were yours) use the Disguise. The artifact was neither exhausted nor destroyed.

Both players had 5 aember: It should have been destroyed with no effect (no aember needed to change hands).
![Nexus and Guard disguise](https://user-images.githubusercontent.com/54557258/63783618-edbf9380-c8b2-11e9-8f7d-d206ac700c57.png)
[Nexus and Guard Disguise.txt](https://github.com/keyteki/keyteki/files/3546876/Nexus.and.Guard.Disguise.txt)

**Comment by romanogit** [comment]
This bug is now fixed. It is not happening anymore. Fixed by #1058
