### ISSUE TITLE
Curse of Fertility Reversed

### ISSUE THREAD

**Issue by KMarch82** [keyteki/keyteki#3890]
I just played a game where I played Curse of Fertility yet my opponent was receiving an amber each time they didn't play a creature. I believe that amber should go to the owner of Curse of Fertility.

**Comment by strib** [comment]
Thanks for the report.  I expect the log message is just wrong/confusing, and the opponent is actually the one gaining the amber.  I'll see if I can fix the log message but if you see it happening again and the wrong player is actually gaining the amber, please post screen shots or the entire chat log.
