### ISSUE TITLE
Issue with "The Warchest" Counting Error

### ISSUE THREAD

**Issue by kennethkchiu** [keyteki/keyteki#3903]
When using "The Warchest" after killing two or more enemy creatures in the same turn with "assault effect" cards like Ornar Skullface, it only counts as gaining 1 Æmber instead of 2+. This issue needs to be addressed and fixed.
![image1](https://github.com/keyteki/keyteki/assets/6643531/ce1b205b-0670-4058-be32-a0c5c4a7d307)
![image2](https://github.com/keyteki/keyteki/assets/6643531/fddc5495-2871-4b3d-9a99-92b20711487d)

**Comment by cryogen** [comment]
Thanks for the report. From the rulebook (via archon arcana):

![image](https://github.com/keyteki/keyteki/assets/1053365/85956eb2-d330-4c2d-ad88-00b14bc7df55)
