### ISSUE TITLE
Using Shrink Ray Scrap and Reap in same turn did not kill 2 power creature

### ISSUE THREAD

**Issue by funim** [keyteki/keyteki#3916]
Used shrink ray scrap to set 2 power creature to power of 1. Then used Dr X to bring shrink ray in ready, reaped and targeted the 2 (now 1) power creature, the creature did not die.

![image](https://github.com/keyteki/keyteki/assets/62214978/e468c5dc-9fe6-4b50-92ab-421ca2f38422)

**Comment by strib** [comment]
That is correct behavior.  The scrap ability sets it to 1 for the rest of the turn, so it can't be modified by -2.  See the Pale Star ruling here: https://archonarcana.com/The_Pale_Star
