### ISSUE TITLE
One Stood Against Many resolves the effect on a stunned creature

### ISSUE THREAD

**Issue by 4ugeistr** [keyteki/keyteki#393]
Opponent had a stunned Dodger.
He used [One Stood Against Many](https://keyforge-compendium.com/cards/223-one-stood-against-many) and [Dodger] fighted three times, even though it was stunned.

Expected result:
1st time - stun is removed, creature is exhausted
2nd and 3rd time: creature readies and fights.

Battlefield state:
![image](https://user-images.githubusercontent.com/23107141/63849926-ba0c6880-c99b-11e9-840d-f52766797523.png)

The battle log:
![image](https://user-images.githubusercontent.com/23107141/63849982-d5777380-c99b-11e9-8f9e-86bd8327f882.png)

Opponent said that he attacked Elusive creatures, so there were no damage exchange and no creature deaths.
But, looking on the the battlefield now I can see that there were only 2 Elusive creatures on my side (Aember Imp, Golden Key Imp). So something went wrong here as well.

**Comment by cryogen** [comment]
Consolidating OSAM issues in #241
