### ISSUE TITLE
The Grim Reaper and Near-Future Lens not displaying the cards

### ISSUE THREAD

**Issue by UltraUltraUltra** [keyteki/keyteki#3942]
"The Grim Reaper" and "Near-Future Lens" not displaying the cards in play.

<img width="1509" alt="image" src="https://github.com/keyteki/keyteki/assets/55008319/58b1da43-efad-48e9-8a77-96a7790d56a7">

**Comment by Kaiserchen** [comment]
I think the other cards just show as they are cached before it broke, Cleared cahce recently in FF no cards load anymore:

![image](https://github.com/user-attachments/assets/7e1a0ffe-e30d-4fe2-9eb7-94e0f7bbe6b9)
![image](https://github.com/user-attachments/assets/15c82d6b-cedd-4718-8d69-f1cc8a94be7e)

**Comment by Kaiserchen** [comment]
![2024-09-17_23-11](https://github.com/user-attachments/assets/eb11d295-1de5-4a91-b64f-42eeed4c8438)
i think its this JS piece

**Comment by Kaiserchen** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1916038 I think this fixes it!

**Comment by Kaiserchen** [comment]
No it doesnt

**Comment by strib** [comment]
I think I have the fix in #4179 (though it requires fixing all the NFL rows in the DB as well).
