### ISSUE TITLE
One Stood Against Many issue

### ISSUE THREAD

**Issue by justicewebtech** [keyteki/keyteki#395]
I had Evasion Sigil in play and it appears it was ignored when One Stood Against Many was played.

opponent for turn 10
Uses Maruck the Marked to reap with Maruck the Marked
Uses Hallowed Shield to apply a lasting effect to Maruck the Marked
Uses Evasion Sigil to discard the top card of keteor''s deck: “Lion” Bautrem. The Grey Rider is exhausted without effect
Plays One Stood Against Many, gaining 1 amber
Uses One Stood Against Many to do several things
Uses Shadow Self to redirect the damage
Draws 2 cards
Declares Check!

**Comment by cryogen** [comment]
Consolidating OSAM issues in #241
