### ISSUE TITLE
Sealed should show own deckname, but not opponent's.

### ISSUE THREAD

**Issue by 7razcal7** [keyteki/keyteki#397]
Currently both deck names are removed, which makes sealed completely unpredictable and also not in line with real world keyforge where players have a couple of minutes to look at their own decklist (but not their opponent's).

Please show the deckname of the sealed deck that has been drawn to the player, but not to the opponent.

**Comment by romanogit** [comment]
After you start the game, at the very top of the game message chat, you have a link to both decks.

**Comment by cryogen** [comment]
@romanogit I removed those links for sealed games, the requester want's it adding back for just your deck.

This isn't currently possible, as the chat log is always sent to both players.  We'll need to do this another way.

**Comment by hydrophilic-attack** [comment]
I haven't played Sealed on here in a long while, but in a normal game, if you click the deck, it shows you all undrawn cards yet left in the deck. If this is the case for sealed too, then you don't actually need a link to your own deck list. All information is available in the rest of the UI

**Comment by SkyJedi** [comment]
this has been implemented soome where around PR #2009
