### ISSUE TITLE
Bonerat Venom upgrade activates without using creature

### ISSUE THREAD

**Issue by Whiplashd-KF** [keyteki/keyteki#398]
My character had the Bonerat Venom upgrade applied to it that activated and damaged my creature for 2 without me actually using that creature. I selected the creature to take my action with it, then decided to do something else instead, but when I hit "Cancel" it still hit my creature for 2 damage. See below for the chat printout of that turn.

Turn 9
Key phase - Whiplashd
Whiplashd forges a key, paying 6 Æmber
House phase - Whiplashd
Whiplashd chooses untamed as their active house this turn
Main phase - Whiplashd
Whiplashd uses Rustgnawer to make Rustgnawer fight Agent Hoo-man
Whiplashd uses Rustgnawer to destroy Combat Pheromones
Count-Zero uses Bonerot Venom to deal 2 damage to Fanghouse
Whiplashd
wtf. I didn't use him and it still damaged me 2
Whiplashd uses Grovekeeper to make Grovekeeper fight Agent Hoo-man
Whiplashd uses Grovekeeper to reap with Grovekeeper
Whiplashd uses Fanghouse to make Fanghouse fight Culf the Quiet
Whiplashd uses Fanghouse to deal 3 damage to Culf the Quiet
Count-Zero uses Bonerot Venom to deal 2 damage to Fanghouse
Count-Zero
not sure why
Whiplashd
I clicked on him, but decided to cancel and use a different creature
Whiplashd
Guess it's a bug for the git
Whiplashd plays Duskwitch
Whiplashd uses Duskwitch to ready Duskwitch
Whiplashd played Duskwitch which has Omega, ending this step

**Comment by romanogit** [comment]
I think this issue has the same root cause as #188 .
What do you think @Achocholacek ?

**Comment by romanogit** [comment]
I think this issue has the same root cause as #268 (I mean)
What do you think @Achocholacek ?

**Comment by AGalassi** [comment]
Same happened to me

**Comment by ryanch** [comment]
I'll take a look at this.

**Comment by ryanch** [comment]
Confirmed that this also happens with Containment Field. I have an idea how to fix. Testing my idea now.

**Comment by ryanch** [comment]
My idea did not pan out.. I've spent a bunch of time looking at this, looks like way useAction event is generated today it happens as soon as a card is clicked on. Seems that fixing this will require a big change the way this action is created, or introduction of a new event that happens after the current event, but after any button is clicked (the later becoming the real use event to use in cards). For now I'm putting this one down (its above my current skill level in the code).

**Comment by benjamintownsend** [comment]
Can confirm there are still issues with Bonerot Venom. It damaged my opponent's Ganger Chieftain immediately after they chose their active house.

Turn 10
Key phase - SkippyTimehog
SkippyTimehog does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - SkippyTimehog
SkippyTimehog chooses brobnar  as their active house this turn
Main phase - SkippyTimehog
**Charzendat uses Bonerot Venom to deal 2 damage to Ganger Chieftain**
SkippyTimehog plays Screechbomb
SkippyTimehog plays Brammo
SkippyTimehog uses Brammo to deal 2 damage to Macis Asp and Brabble
Charzendat uses Brabble to make SkippyTimehog lose 3 Æmber 
SkippyTimehog uses Ganger Chieftain to reap with Ganger Chieftain
**Charzendat uses Bonerot Venom to deal 2 damage to Ganger Chieftain**
SkippyTimehog plays Bingle Bangbang
