### ISSUE TITLE
Nerve Blast does not inform which creature took a damage. [cosmetic]

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#407]
It just says it stole 1 amber:

![image](https://user-images.githubusercontent.com/2104075/64081779-eb5aa080-ccdb-11e9-825f-3ff9316c2363.png)

**Comment by Dicky-Boy** [comment]
Hi, I've not contributed before but this looks like a nice easy first issue - would anyone have any objections if I submitted a pull request for this one?
