### ISSUE TITLE
Mars Needs Aember Bug

### ISSUE THREAD

**Issue by justicewebtech** [keyteki/keyteki#411]
In this turn (second one below) I reaped with Skybooster which returned him to my hand.  This returned 5 captured aember that was on skybooster back to my opponent.  I split the Orbital Bombardment damage across his creatures.  I had damage on every single creature on his side of the board.  When I played Mars Needs Aember I was prompted to select which creatures to have capture aember from their own side.   I selected one of the Ancient Bears, it captured aember, and then the prompt disappeared and no other aember was captured.

opponent
Plays Dew Faerie
Plays Murmook
Plays Ancient Bear
Plays Ancient Bear
Plays Ancient Bear
Plays Ancient Bear
Plays Snufflegator
Draws 4 cards
opponent''s deck has run out of cards, so they shuffle
opponentis shuffling their deck
opponent''s chains are reduced by 1 to 0
opponent: 0 amber
me: 3 amber

me for turn 14
Plays Orbital Bombardment, gaining 1 amber
Uses Orbital Bombardment to reveal Glyxl Proliferator, Key Abduction, and Mars Needs Æmber and to deal 2 damage to a creature 3 times
Plays Glyxl Proliferator
Uses Skybooster Squadron to reap with Skybooster Squadron
Uses Skybooster Squadron to return Skybooster Squadron to their hand
Plays Key Abduction, gaining 1 amber
Uses Key Abduction to return all mars creatures to their owner''s hand
Plays Mars Needs Æmber, gaining 1 amber
Uses Mars Needs Æmber to make each damaged enemy non-mars creature capture 1 amber from their side
Plays Skybooster Squadron
Plays Glyxl Proliferator
Draws 4 cards
Declares Check!
opponent: 4 amber
me: 7 amber

**Comment by romanogit** [comment]
Working as expected after Capture refactor:

![image](https://user-images.githubusercontent.com/2104075/101055982-3e6b7500-3569-11eb-8f35-6b6349580d15.png)
