### ISSUE TITLE
Reap the Wild Wind reveals twice

### ISSUE THREAD

**Issue by JareCoder** [keyteki/keyteki#4190]
![image](https://github.com/user-attachments/assets/c3b800f2-d281-4b17-80c5-2c5684a838b2)

Reap the Wild Wind runs twice as seen in the image. First in the "Uses" statement and then twice after. Only the last 2 revealed cards are used for the amber gain.

**Comment by strib** [comment]
Well at least it's symmetric for both players.  Fixed in #4191 I think. Thanks!
