### ISSUE TITLE
Urchin and Autocannon

### ISSUE THREAD

**Issue by UltraUltraUltra** [keyteki/keyteki#420]
When I play an Urchin when I have Autocannon in play, Urchin does not steal aember from my opponent (even though they have aember to steal).  However, when my opponent plays an Urchin and I have Autocannon in play, their Urchin steals an aember from me.
![My Urchin Not Stealing](https://user-images.githubusercontent.com/55008319/64468348-bf944c00-d11b-11e9-8bab-68b494c5a9d7.jpg)
![Their Urchin Stealing](https://user-images.githubusercontent.com/55008319/64468349-c02ce280-d11b-11e9-87f9-cef1e6066cfa.png)

**Comment by romanogit** [comment]
This is fixed after Timing Refactor
