### ISSUE TITLE
Raince Furyheart does not exalt if opposing creature dies

### ISSUE THREAD

**Issue by dmikalova** [keyteki/keyteki#4295]
I had a match where Raince Furyheart fights Bosun Creen and I did not get an aember. I believe it should work that Raince exalts Bosun before Bosun dies, and then I get that aember. I tested it out and Raince does exalt an elusive creature on first fight.

**Comment by JareCoder** [comment]
![Raince_bug](https://github.com/user-attachments/assets/0b832c21-5d3e-4b54-ab22-6148e6d869a2)

More data for this! 

Maybe it's implemented as an After Fight right now? Before Fight only happens if creature can survive it right now.

**Comment by JareCoder** [comment]
Guess was right. Sorta. 

[Raince](https://github.com/keyteki/keyteki/blob/master/server/game/cards/08-AS/RainceFuryheart.js) currently has "this.fight".

Should be "this.beforeFight" as seen in [Tribune Pompitus](https://github.com/keyteki/keyteki/blob/master/server/game/cards/03-WC/TribunePompitus.js).
