### ISSUE TITLE
Fortune Reverser doesn't stop subsequent additions to text box

### ISSUE THREAD

**Issue by Tutenkharnage** [keyteki/keyteki#4308]
I played Fortune Reverser on an enemy Talent Scout. My opponent then played Ethereal Adapter on it and used the captured aember to forge. Text gained by upgrades is considered part of the creature's text box, and Fortune Reverser says the text box is blank except for traits, so this shouldn't work.

**Comment by strib** [comment]
Do you have a citation for a similar ruling?  In my mind, the creature with the blank text box is gaining some new text, so it's a "more recent effect wins" situation similar to double Collar of Subordination or something like that.

**Comment by Tutenkharnage** [comment]
I’ve got this from a judge (blinkingline):

**Comment by strib** [comment]
Ok I did my best in #4310 but blanking is a pretty complicated situation in the code; hopefully what I did doesn't break other stuff...

**Comment by Tutenkharnage** [comment]
Thanks, Jeremy! I appreciate everything you and the rest of the TCO crew do.
