### ISSUE TITLE
Speed Sigil + Pitlord + Three Fates + Round Table

### ISSUE THREAD

**Issue by MoonWalker0** [keyteki/keyteki#431]
So here is quite a complex issue:

During my turn I played Pitlord, which was readied by Speed Sigil. 
I did not reaped with the Pitlord and played the Three Fates.
I was unable to select three creatures and confirm - there was no "Confirm" button to do so.
I am pointing out that there was Round Table in play because it manipulates with the number of creatures I could select from.
Moreover, Pitlord did not receive orange border around him after clicking on him - its border was just pulsing.

![Uploading bug.png…]()

**Comment by MoonWalker0** [comment]
![bug](https://user-images.githubusercontent.com/32847809/64644176-5447c400-d412-11e9-841e-3bf490e98040.png)
Looks like the previous screenshot is broken. I am uploading a new one.

**Comment by hydrophilic-attack** [comment]
Looking at the screenshot, the reason you can't select done is that you seem to have selected two creatures that are tied for third highest power and left the second highest power creature unselected.

Gatekeeper is a knight and has 6 power, meaning you have to choose him as one of the 3. So you need to choose pitlord + gatekeeper plus shooler or horseman of war or raiding knight. you can't select shooler + horseman of war + pitlord which it looks like you're trying to do. So from here, it seems like the interaction was working as intended, you just tried to do an illegal move, and it didn't let you

**Comment by MoonWalker0** [comment]
Oh... you may be right. Well I tried multiple options but there is a chance that I missed that one described by you.

Ok, I will close the issue. I think @hydrophilic-attack explanation is sufficient.
