### ISSUE TITLE
De-Doss / Dr. Xylo problem

### ISSUE THREAD

**Issue by Tutenkharnage** [keyteki/keyteki#4321]
If I put De-Doss on an enemy creature and use Dr. Xylo to reap, TCO is looking at Dr. Xylo's power to determine whether a Mars creature can be played from discard.

- Dr. Xylo at P4, De-Doss on P2 creature: I can't play P2/P3 creatures.
- Add 1 power counter to that P2 De-Doss creature: I still can't play P2/P3 creatures.
- Add 1 more power counter: I can suddenly play both creatures.

This only seems to be a problem with Dr. Xylo. TCO lets me select what should be legal targets from discard, but when I try to play them, they show up in the log but are _not_ played to the battleline.

**Comment by strib** [comment]
Thanks for the report.  I'm having trouble understanding the issue though.  If it were really looking at Dr. X's power, why would adding power counters to the De-Doss creature have any effect at all?

I wrote a quick test that has De-Doss on a power 5 enemy creature, and Dr. X (at P2) is still able to play a Grabber Jammer (at P4) with no problem.  I'll try to set up the exact scenario you mention above when I get a chance.

**Comment by strib** [comment]
Ohh I see now, you mean it's using Dr X's power instead of the power of the creature in the discard pile.  I thought at first you were saying it used it instead of the De-Doss creature's power.  Got it, I will look into it when I can.

**Comment by Tutenkharnage** [comment]
I suspect it’s looking at Dr. X’s power and comparing it to the power of
the creature with De-Doss. If Xylo’s power is higher, it won’t let you play
creatures that should be legal.

I’ll check more later tonight.

**Comment by Tutenkharnage** [comment]
Yep, that seems to be what was happening! Thanks for the legwork.
