### ISSUE TITLE
Barter And Games Destroying Creatures Not Affiliated With Revealed Card

### ISSUE THREAD

**Issue by Yurkijo** [keyteki/keyteki#4337]
![image_2024-10-17_135312269](https://github.com/user-attachments/assets/f1e1fd6c-d9cb-48f1-b228-4e5ed1757c4c)

I used Barter And Games, revealed a card in house shadows on my opponents board, and I revealed nothing from my archives. It still destroyed my opponents' dis board. 

I believe it happened in regards to possibly associating the token creatures as a part of another house, or maybe it revealed another card in my opponents' hand that was not associated with what was said via the chat board?

**Comment by Yurkijo** [comment]
Its still showing wrong card via archives, see below. I had General Xalvador in my archives as well and it was removed instead of comandeer which was notified would be removed.
![image](https://github.com/user-attachments/assets/5f00cedd-57a1-4138-9525-79f5598faf0a)
![image](https://github.com/user-attachments/assets/5eeca3c4-3d3f-41d6-b4fd-612c20e03aa3)

**Comment by strib** [comment]
Thanks but as you can this PR is still open, which definitely means the fix hasn't been deployed yet.

**Comment by Yurkijo** [comment]
OH I see. My apoplogies, I misread your earlier message
