### ISSUE TITLE
Wild Wormhole shows a redundant out of format game message [cosmetic]

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#434]
> romano2 plays Wild Wormhole, gaining 1 Æmber

> romano2 uses Wild Wormhole to play the top card of their deck : Mars Needs Æmber

> Wild Wormhole reveals Mars Needs Æmber

The thirs message seems redundant and does not say "player does xxx". It starts with card name:

![image](https://user-images.githubusercontent.com/2104075/64659833-19469000-d414-11e9-9272-a7e85bdd082a.png)

**Comment by cryogen** [comment]
The reveal is because of when the card fails to play, so that you know what the card was, as that's what happens in a real game.

**Comment by romanogit** [comment]
I know, but if you look at the first sentence, it contains the same info, but says "to play", which is incorrect. We have 3 messages today:

```
romano2 plays Wild Wormhole, gaining 1 Æmber
romano2 uses Wild Wormhole to play the top card of their deck : Mars Needs Æmber
Wild Wormhole reveals Mars Needs Æmber
romano2 plays Mars Needs Æmber gaining 1 Æmber
```

Should we say:

```
romano2 plays Wild Wormhole, gaining 1 Æmber
romano2 uses Wild Wormhole to reveal the top card of their deck : Mars Needs Æmber
romano2 plays Mars Needs Æmber gaining 1 Æmber
```

In case it cannot be played:

```
romano2 plays Wild Wormhole, gaining 1 Æmber
romano2 uses Wild Wormhole to reveal the top card of their deck : Bumblebird
romano2 returns Bumblebird to the top of their deck
```

**Comment by cryogen** [comment]
We can probably make this smarter by making use of the chatMessage flag instead of always setting it to true
