### ISSUE TITLE
Sacro-Saurus is a dead card in saurian

### ISSUE THREAD

**Issue by Yurkijo** [keyteki/keyteki#4341]
I'm attempting to play my Set 4 (Mass Mutation) deck, but it seems Sacro-Saurus is not functioning correctly. I am unable to play it from my hand without switching to manual mode, and I'm also unable to attack, reap, use its play effect—essentially, nothing works. I suspect this may be due to a bug introduced when it was added to ToC.

Apologies if this issue has already been addressed; I did search but was unable to find any relevant information.

**Comment by strib** [comment]
Thanks, there wasn't an open issue for it yet but there is an outstanding PR to address it: #4339 .

**Comment by Yurkijo** [comment]
Is this associated with the fact that I was able to go into house saurian when I had it in hand?
![image](https://github.com/user-attachments/assets/e476a54b-150e-4172-a384-7c4efb2be51b)

**Comment by strib** [comment]
Yes.
