### ISSUE TITLE
House Error

### ISSUE THREAD

**Issue by vulinhchelsea** [keyteki/keyteki#4342]
I imported and played this deck on TCO https://decksofkeyforge.com/decks/1aa7d13c-d168-47e7-9888-b029d13e46d2
On the deck list on TCO, Sacro-Alien and The Shadowsmith have their house swapped, and the in-game houses are swapped also.
The card images are still correct though. Please take a look and help to fix it.
![Screenshot 2024-10-21 205809](https://github.com/user-attachments/assets/db256117-38a3-495a-90bd-3e7c26688c48)
![Screenshot 2024-10-21 205837](https://github.com/user-attachments/assets/324cf4b2-e74f-4d50-acb6-8b938887282a)
Many thanks.

**Comment by strib** [comment]
This is the same as #4341 -- it's fixed in the code and will be fixed on the server the next time we deploy.  Thanks.
