### ISSUE TITLE
Titanarpon does not enter play ready if it's the first creature played in the turn

### ISSUE THREAD

**Issue by robertojrocha** [keyteki/keyteki#4360]
### If Titanarpon is the first creature played in the turn, it should enter play ready.

**Titanarpon's text:**
Beast
Elusive.
The first creature you play each turn enters play ready.

**From page 14 of the manual:**
ENTERS PLAY
Some abilities modify how cards enter play. These abilities
resolve as the card is entering play and modify how a card enters
play (e.g. ”enters play ready,” “enters play stunned,” etc.). An
ability that modifies how a card enters play modifies how any
cards that meet the criteria of the ability enter play, including the
card with the ability. These abilities all resolve before the card is
actually in play.
If a card ability adds an ability or keywords, such as deploy, to a
card, that text is added as the card enters play and will modify
how the card enters play.
Related Topics: Playing Cards

Deck for reference (this deck is not mine, just grabbed a deck with Titanarpon from DoK to recreate the issue):
https://decksofkeyforge.com/decks/47b60f7c-e6bb-4ab0-b7c6-dc02be1d5986

### 
https://github.com/user-attachments/assets/15c30495-121c-4a4d-9ec6-772c7d85dc78

**Comment by strib** [comment]
No, Titanarpon's ability isn't in effect until it is already in the battleline, at which point the "enters play" timepoint is already passed.

cc: @blinkingline in case I'm wrong.

**Comment by strib** [comment]
Thanks, you are right, I had slightly misread the card and thought it was worded differently from Silverooth/maverick Fandangle.  I put up a fix for review.
