### ISSUE TITLE
Mimicry & Destroy Them All, Mimicry & They're Everywhere

### ISSUE THREAD

**Issue by JTLSound** [keyteki/keyteki#438]
Both instances lock the game in a prompt. With Destroy Them All, it requires you to select two creatures when there is no upgrade present. With They're Everywhere it locks the game in a prompt until the user of Mimicry selects a creature to deal extra damage to. Both are illegal uses of the copied cards.

**Comment by JTLSound** [comment]
To be more clear, They're Everywhere deals the appropriate amount of damage to the correct creatures, THEN puts you in a prompt. They're Everywhere should never have a prompt at all, but when used with Mimicry, a prompt appears.

**Comment by saluk** [comment]
Mimicry + destroy them all asked for 2 artifacts in my case when no upgrade was available.

**Comment by romanogit** [comment]
This is not happening anymore
