### ISSUE TITLE
De-Animator: Ward is saving artifacts from destroying themselves

### ISSUE THREAD

**Issue by Tutenkharnage** [keyteki/keyteki#4380]
I played Grizzled Wyvern and used Hologrammophone to ward it. Next turn, I played De-Animator and used its play ability to put a mineralize counter on Grizzled Wyvern, which moved to my artifact line with a ward on it. I then used its newly granted "Action: Destroy this artifact" ability (granted by De-Animator) to destroy it. TCO's log said I destroyed it; it may have said the ward was removed, but I don't remember. (Sorry!) Regardless, TCO did _not_ remove the ward, which shouldn't have prevented Grizzled Wyvern's destruction, because the rules for ward only refer to creatures, not cards or artifacts:

_**WARD**_
_When a creature becomes warded, place a ward status counter on it. If a creature with a ward counter on it would be damaged, destroyed, or leave play, instead discard each ward counter on it. (Note: This prevents the creature from being
tagged for destruction.)_

_While a creature has a ward counter on it, it cannot be warded again._

_If an effect attempts to ward a warded creature, that effect does not ward the already warded creature. If a ward counter is placed on a creature after it has already been tagged for destruction, the ward counter will not prevent the creature from leaving play. However, it will prevent the creature from leaving play in other ways, such as being returned to hand._

RAW, wards only prevent the destruction of creatures, not artifacts. Grizzled Wyvern should have been destroyed, and the aember should have been moved to the common supply.

**Comment by strib** [comment]
Thanks, though this is already fixed in #4362, which is waiting review.
