### ISSUE TITLE
Two bottom gigantic cards in a single gigantic deck

### ISSUE THREAD

**Issue by sdsantos** [keyteki/keyteki#4382]
The first time I tried playing with https://decksofkeyforge.com/decks/5c9c6c45-41a5-4b26-b522-8803639c3486, after archiving the bottom part of a gigantic, I drew another bottom part, ending up with this:

<img width="276" alt="Screenshot 2024-11-15 at 11 56 30" src="https://github.com/user-attachments/assets/8d8d10da-bad6-4525-878d-9adea901ca7c">

**Comment by sdsantos** [comment]
@strib still hapenning
<img width="1440" alt="Screenshot 2024-12-24 at 10 54 04" src="https://github.com/user-attachments/assets/b7b6b582-82ab-4da9-a037-bfb86f6eaa63" />

**Comment by strib** [comment]
Is this a newly-imported deck?  If you imported before the bug is fixed you'll have to delete it and try again.

If it's a new deck, please provide a link to the deck.

**Comment by sdsantos** [comment]
@strib Didn't realize it was an import bug! Will re-import, thanks.
