### ISSUE TITLE
Treasure island take amber from creature instead of my pool

### ISSUE THREAD

**Issue by Osarek** [keyteki/keyteki#4394]
Turn 1 - Osarek-3651
Key phase - Osarek-3651
Osarek-3651 does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - Osarek-3651
Osarek-3651 chooses skyborn as their active house this turn
Main phase - Osarek-3651
Osarek-3651 uses Scalawag Finn to reap with Scalawag Finn
Osarek-3651 uses Scalawag Finn to move 1 Æmber from Scalawag Finn to Treasure Island **_[0 on Treasure Island]_**
Osarek-3651 uses Ley, Earl of Hurl to reap with Ley, Earl of Hurl
Osarek-3651 uses Ley, Earl of Hurl to move 1 Æmber from Ley, Earl of Hurl to Treasure Island **_[0 on Treasure Island]_**
Osarek-3651 uses Bosun Creen to reap with Bosun Creen
Osarek-3651 uses Bosun Creen to move 1 Æmber from Bosun Creen to Treasure Island **_[0 on Treasure Island]_**
 Osarek-3651 is attempting to switch manual mode on
 osarek2 allows enabling manual mode
 Osarek-3651 switches manual mode on
 Osarek-3651 readies Scalawag Finn
 Osarek-3651 readies Ley, Earl of Hurl
 Osarek-3651 readies Bosun Creen
 **Osarek-3651 adds an Æmber to Scalawag Finn**
 Osarek-3651 switches manual mode off
Osarek-3651 uses Scalawag Finn to reap with Scalawag Finn
Osarek-3651 uses Scalawag Finn to move **1 Æmber from Scalawag Finn to Treasure Island** **_[1 on Treasure Island]_**

![image](https://github.com/user-attachments/assets/cffed6a8-f960-44e4-b173-a9dbe6bf578d)

**Comment by strib** [comment]
Thanks for the report!  Yikes, I totally misread that card.  Can't believe it took this long for someone to report it. A fix is now up for review in #4395.

**Comment by Osarek** [comment]
Haha yeah I had the problem a couple of time that I had to fix in manual, didn’t understand why sometime I get the aber on treasure island and sometime not 😃 
it was not working even in a fake game (me vs me) the log text was helpful to understand why :)

thanks for your service 🫡

**Comment by Osarek** [comment]
The most probable cause of your misread it probably that, this card was simple rewrites since the first spoilers?

**Comment by strib** [comment]
It is possible!  I can't remember what I was thinking, it is all a blur...

**Comment by D07U** [comment]
+1.
![rdeytdery](https://github.com/user-attachments/assets/4bd794bd-fbaf-4e63-baf1-966a1f2d9698)

I encountered this issue while testing my new Treasure Island deck too.

**Comment by D07U** [comment]
Thanksss a lottt!! <3
