### ISSUE TITLE
(Untamed) Cooperative Hunting not working properly

### ISSUE THREAD

**Issue by LifeIsPizza** [keyteki/keyteki#44]
Card Text Play: Deal 1 for each friendly creature in play. You may divide this damage among any number of creatures.

Expected behavior: Damage should be dealt all at once even if spread between creatures, not triggering any Destroyed effect nor moving creatures to the discard pile during resolution.

Actual behavior: Damage is dealt 1 by 1 and triggers Destroyed abilities if creatures are destroyed during resolution.

This is inconsistent because you might be forced to damage your own creatures (while you could technically assign 5 damage to an enemy Dust Pixie to avoid that, or bypass Shadow Self's ability by destroying it first) or trigger Destroyed abilities when they should not trigger.

**Comment by Achocholacek** [comment]
Resolved by https://github.com/keyteki/keyteki/pull/48

**Comment by LifeIsPizza** [comment]
Solved by #48
