### ISSUE TITLE
Upgrades are difficult to play in manual mode

### ISSUE THREAD

**Issue by dlocke** [keyteki/keyteki#451]
My apologies for not taking a screenshot.  I will instead try to describe the situation that we were in.

On my opponent's first turn they called Dis and played Streke.  On my first turn I called Mars and attached a Containment Field to my opponent's Streke.  On my opponent's second turn, they called Dis again, played two creatures and then their Streke was destroyed by the containment field without being used.

We attempted to remedy the situation by turning on manual mode.  My opponent was able to move the Streke to the right place in the battle line and I was able to take the Containment Field back into my hand.  However, I wasn't able to figure out a way to re-attach the Containment Field to the Streke.  The UI made it look like I could attach the Containment field to my own creature but not to my opponent's creature.

(In the end my opponent decided to just take an AEmber as if the Streke had been used to reap and eventually won the game when they forged their third key with zero AEmber to spare.)

**Comment by romanogit** [comment]
What I noticed is that we cannot manually play cards on opponent's area.
Best thing is to just move the card to your hand and play a dummy turn to place the CF is the opponent creature and continue with the game.

**Comment by cryogen** [comment]
Manual mode does not let you interact with opponent's cards at all.   The correct way to do this would be drag the card to your play area, place the upgrade on it, then do /take-control to hand it to your opponent.

But, the ux of this whole problem could be a lot better indeed
