### ISSUE TITLE
Archimedes behaving pre-nerf

### ISSUE THREAD

**Issue by nsalaway** [keyteki/keyteki#457]
My opponent's board:
Jargogle - Tantadlin - Helper Bot - Archimedes - Harlan Mindlock - Gub

I played Whistling Darts and Helper Bot, Mindlock, and Gub were all archived

**Comment by romanogit** [comment]
I was able to recreate this one

**Comment by romanogit** [comment]
@jeremylarner : is this one fixed with the latest simultaneous damage change?

**Comment by romanogit** [comment]
This is fixed by simultaneous damage refactor:
![image](https://user-images.githubusercontent.com/2104075/101212969-6685d180-3658-11eb-8518-e40d67cc37ac.png)
