### ISSUE TITLE
Word of returning on a creature next to a shadow self

### ISSUE THREAD

**Issue by saluk** [keyteki/keyteki#465]
Expected: the damage is redirected to the shadow self, the aember is not returned because the shadow self replaced dealing the damage to the creature that had the aember. So shadow self is one of "those" creatures, and the neighbor is not.
Actual: No aember is returned, but the shadow self is not dealt damage

In this screenshot the ether spider should have been dealt 9 damage, which would have redirected to and destroyed the shadow self.

![wordofreturning](https://user-images.githubusercontent.com/54372/65795252-b6950a00-e11e-11e9-8737-ab4a5de102a3.png)

**Comment by Achocholacek** [comment]
IMHO, in this situation (or those like it), Aember would still be returned regardless of whether or not the damage hits the actual creature or is redirected. Doesn't explain why the behaviour is wrong still.

**Comment by Achocholacek** [comment]
I was wrong with my comment in October.

That being said, WoR was recently refactored and I just updated the test case to reflect this situation and it works exactly as expected now:

1) Damage is dealt at Ether Spider
2) Damage is redirected to Shadow Self
3) Shadow Self is destroyed
4) The aember is attempted to be moved to the opposite player and immediately recaptured by Ether Spider.
5) WoR player gains no aember from ether spider, and they all (+1 from WoR) remain on Ether spider.
