### ISSUE TITLE
Consistent disconnects

### ISSUE THREAD

**Issue by JollyGrin** [keyteki/keyteki#472]
Greetings! I keep getting disconnected from the game and get booted out mid-session. Unfortunately, haven't been able to play a full game for awhile.

**Comment by cryogen** [comment]
Is this your crucible username?  If not, please can you provide it and i'll dig through the logs

**Comment by cryogen** [comment]
Please reopen this issue with traceroute and ping reports to 'play.thecrucible.online', while you're experiencing the issue, if you want me to look into this
