### ISSUE TITLE
Multiple Sir Marrows

### ISSUE THREAD

**Issue by brucollaco** [keyteki/keyteki#487]
Hello!!

I want to report a bug that happens when multiple sir marrows are in play. When an enemy creature reaps, all other sir marrows in play also capture amber from the pool if available.

I'm attaching screenshots.
![Screen Shot 2019-09-30 at 21 32 22](https://user-images.githubusercontent.com/42810905/65926778-4c55c100-e3cd-11e9-92f5-92e01eaf4502.png)
![Screen Shot 2019-09-30 at 21 32 12](https://user-images.githubusercontent.com/42810905/65926780-4c55c100-e3cd-11e9-8d2c-39cdc9f3091d.png)

**Comment by saluk** [comment]
@brucollaco This is the correct behavior. Each marrows tries to capture, if there is still aember to capture it will do so. If you only had 1 aember left, you should be able to choose which marrows triggers first (hence which will successfully capture)

**Comment by TicklesTheBrain** [comment]
I can confirm, ran into this problem a couple of times myself.

**Comment by OsramTaleka** [comment]
I can also confirm. This always happens when I have 2 Sir Marrows in play for me.

**Comment by ira212** [comment]
This is a duplicate of issue #190 . Probably safe to close this.

**Comment by brucollaco** [comment]
Closing because the is already issue #190 that address this issue already.
