### ISSUE TITLE
Overlord Greking/Drumble Combination

### ISSUE THREAD

**Issue by vitallish** [keyteki/keyteki#490]
Hello,

I ran into an issue yesterday where I used Overlord Greking to desctroy my opponents Drumble. The Drumble then was played on my battle line but did not capture my opponent's 7 aember.

You can see this in Turn 17 on the crucible tracker:
https://www.thecrucibletracker.com/games/06c9b030-e3f3-11e9-bfbf-491b7a2b9729/log

```
Uses Overlord Greking to make Overlord Greking fight Drumble
Uses Overlord Greking to put Drumble into play
{opponent} is attempting to switch manual mode on
vitallish allows enabling manual mode
```

**Comment by romanogit** [comment]
@vitallish ,
Putting into play is different than Play. When you put a creature into play, you do not activate the Play ability, so Drumple would move to your battle line with the amount of amber already on it, but it would not capture any new amber.

**Comment by vitallish** [comment]
Ah got it! Thank you. One quick note - the amber should be removed because the Drumble was technically destroyed.

**Comment by romanogit** [comment]
ok, got it. Makes sense. Thanks!
