### ISSUE TITLE
Bear Flute

### ISSUE THREAD

**Issue by jorgecachoh** [keyteki/keyteki#493]
Bear Flute has an incorrect behaviour

This is the correct behaviour: 

`Action: Fully heal an Ancient Bear. **If there are no Ancient Bears in play**, search your deck and discard pile and put each Ancient Bear from them into your hand. If you do, shuffle your discard pile into your deck.`

I had one Ancient Bear in play (in the table) but Bear Flute has asked me to search for more Ancient Bears in my discard pile

**Comment by Achocholacek** [comment]
Confirmed as above.

**Comment by LifeIsPizza** [comment]
Did this get fixed? I can't reproduce the bug.

**Comment by jorgecachoh** [comment]
I haven't been able to reproduce it again. So I think the bug can be closed
