### ISSUE TITLE
[WC] - New Cards - Saurian

### ISSUE THREAD

**Issue by Achocholacek** [keyteki/keyteki#498]
- [x] 214 - Auto-Legionary
- [x] 224 - Kompsos Haruspex
- [x] 225 - Livia the Elder

- [x] 203 - Gargantodon
- [x] 207 - Philophosaurus
- [x] 212 - The Callipygian Ideal
- [x] 213 - Tribune Pompitus

- [x] 215 - Cincinnatus Rex
- [x] 217 - Crassosaurus
- [x] 218 - Diplo-Macy
- [x] 219 - Favor of Rex
- [x] 223 - Imperial Road

- [x] 226 - Primus Unguis
- [x] 227 - Saurus Rex
- [x] 229 - Senator Bracchus
- [x] 230 - Sow Salt
- [x] 231 - Spartasaur
- [x] 233 - The Colosseum

- [x] 182 - Axiom of Grisk
- [x] 184 - Chant of Hubris
- [x] 185 - Imperial Scutum
- [x] 186 - Imperium
- [x] 187 - Legatus Raptor
- [x] 188 - Odoac the Patrician
- [x] 189 - Phalanx Strike
- [x] 190 - Praefectus Ludo
- [x] 191 - Questor Jarta
- [x] 192 - Rhetor Gallim
- [x] 193 - Senator Shrix
- [x] 194 - The Golden Spiral
- [x] 195 - Thero Centurian
- [x] 196 - Tribute
- [x] 197 - Tricerian Legionary
- [x] 198 - Ancient Power
- [x] 199 - Centurion Stenopius
- [x] 200 - City-State Interest
- [x] 201 - Draco Praeco
- [x] 202 - Exile
- [x] 204 - Library of Polliasaurus
- [x] 205 - Orator Hissaro
- [x] 206 - Paraguardian
- [x] 208 - Regrettable Meteor
- [x] 209 - Sic Semper Tyrannosaurus
- [x] 210 - Stomp
- [x] 211 - Terrordactyl
- [x] 216 - City Gates
- [x] 220 - Good of the Many
- [x] 221 - Grimlocus Dux
- [x] 222 - Imperial Forge
- [x] 228 - Saury About That
- [x] 232 - Tertiate
- [x] 234 - Triumph

**Comment by romanogit** [comment]
In PR https://github.com/keyteki/keyteki/pull/511/ 
- Tricerian Legionary

**Comment by romanogit** [comment]
In PR #511
- Tricerian Legionary
- Imperium

**Comment by romanogit** [comment]
In PR #511:
- Axiom of Grisk

**Comment by romanogit** [comment]
Implemented exalt in https://github.com/keyteki/keyteki/pull/539
Added cards:
- Questor Jarta
- The Golden Spiral

**Comment by romanogit** [comment]
- 183 Brutodon Auxillary does not need card. just taunt haz:2

**Comment by romanogit** [comment]
Added two more cards to #539:
- Ancient Power
- Paraguardian

**Comment by romanogit** [comment]
A few more cards added to #539:
- Chant of Hubris
- Imperial Scutum
- Thero Centurion
- Centurion Stenopius
- Exile
- Library of Polliasaurus

**Comment by romanogit** [comment]
@Achocholacek :
Five new cards added to #539:
- Good of the Many 
- Grimlocus Dux
- Orator Hissaro
- Regrettable Meteor
- Saury About That

**Comment by romanogit** [comment]
5 cards implemented:
- City Gates
- Draco Praeco
- Sic Semper Tyrannosaurus
- Terrordactyl
- Tertiate

**Comment by romanogit** [comment]
5 cards implemented:

    City Gates
    Draco Praeco
    Sic Semper Tyrannosaurus
    Terrordactyl
    Tertiate

**Comment by romanogit** [comment]
Added card to #621:
- Triumph
- Imperium Forge

**Comment by romanogit** [comment]
In #628:
- Cincinnatus Rex
- Primus Unguis
- Sow Salt
- Tribune Pompitus

**Comment by romanogit** [comment]
Diplo-Macy implemented in #645

**Comment by romanogit** [comment]
Draft `Favor of Rex` on #657

**Comment by romanogit** [comment]
In #659: `Imperial Road`

**Comment by cryogen** [comment]
Saurian - done (well, almost)
