### ISSUE TITLE
[WC] - New Cards - Star Alliance

### ISSUE THREAD

**Issue by Achocholacek** [keyteki/keyteki#499]
- [x] 295 - Com. Officer Kirby
- [x] 309 - CXO Taber
- [x] 313 - Lay of the Land
- [x] 314 - Navigator Ali
- [x] 318 - Science Officer Morpheus
- [x] 320 - Tactical Officer Moon
- [x] 325 - Book of IeQ
- [x] 328 - Disruption Field
- [x] 333 - General Order 24

- [x] 292 - Armsmaster Molina
- [x] 293 - Chief Engineer Walls
- [x] 294 - Cloaking Dongle
- [x] 296 - Commander Chan
- [x] 297 - Explo-rover
- [x] 298 - First Officer Frane
- [x] 300 - Light of the Archons
- [x] 301 - Medic Ingram
- [x] 302 - Molina's Blaster
- [x] 303 - Red Alert
- [x] 304 - Sci. Officer Qincan
- [x] 305 - Sensor Chief Garcia
- [x] 306 - Stealth Mode
- [x] 307 - Zap
- [x] 308 - CALV-1N
- [x] 310 - Force Field
- [x] 311 - Helmsman Spears
- [x] 312 - Information Officer Gray
- [x] 315 - Nurse Soto
- [x] 316 - Quadracorder
- [x] 317 - Quintrino Flux
- [x] 319 - Stunner
- [x] 321 - Transporter Platform
- [x] 322 - Universal Translator
- [x] 323 - Xenotraining
- [x] 324 - Aembertracker
- [x] 326 - Captain Val Jericho
- [x] 327 - Crash Muldoon
- [x] 329 - Doctor Driscoll
- [x] 330 - Encounter Suit
- [x] 331 - Forging an Alliance
- [x] 332 - Galactic Census
- [x] 334 - Operations Officer Yshi
- [x] 335 - Peace Accord
- [x] 336 - Plasma Nozzle
- [x] 337 - Psionic Officer Lang
- [x] 338 - Quixxle Stone
- [x] 339 - Special Agent "Fingers"
- [x] 340 - Tachyon Pulse
- [x] 341 - Techivore Pulpate
- [x] 342 - Uncharted Lands
- [x] 343 - United Action
- [x] 344 - We Can All Win
- [x] 345 - Chan's Blaster
- [x] 346 - Frane's Blaster
- [x] 347 - Garcia's Blaster
- [x] 348 - Ingram's Blaster
- [x] 349 - Khrkhar's Blaster
- [x] 350 - Kirby's Blaster
- [x] 351 - Qincan's Blaster
- [x] 352 - Walls' Blaster

**Comment by romanogit** [comment]
In master:
- Explo-rover

In PR https://github.com/keyteki/keyteki/pull/511 : 
- Force Field

**Comment by romanogit** [comment]
- 330 - Encounter Suit

**Comment by romanogit** [comment]
In PR #511 :
- Medic Ingram

**Comment by romanogit** [comment]
In PR #595 :
- CALV-1N
- Transporter Platform

**Comment by romanogit** [comment]
All Blasters implemented in PR #599

**Comment by romanogit** [comment]
Added card to #621:
- We Can ALL Win

**Comment by romanogit** [comment]
In #633 :
- Tachyon Pulse

**Comment by romanogit** [comment]
Sci. Officer Qincan in PR #643

**Comment by romanogit** [comment]
Disruption Field on #648

**Comment by cryogen** [comment]
star alliance - done
