### ISSUE TITLE
[WC] - New Cards - Brobnar

### ISSUE THREAD

**Issue by Achocholacek** [keyteki/keyteki#501]
- [x] 045 - Old Boomy

- [x] 001 - Alaka
- [x] 002 - Alaka's Brew
- [x] 003 - Ballcano
- [x] 004 - Barn Razing
- [x] 005 - Berserker Slam
- [x] 006 - Cowfyne
- [x] 007 - Ganger Chieftain
- [x] 008 - Groke
- [x] 009 - Gron Nine-Toes
- [x] 010 - Irestaff
- [x] 011 - Mogghunter
- [x] 012 - Narp
- [x] 013 - Shorty
- [x] 014 - Stilt-Kin
- [x] 015 - Tremor
- [x] 016 - Warriors' Refrain
- [x] 017 - Blood Money
- [x] 018 - Flamethrower
- [x] 019 - Flamewake Shaman
- [x] 020 - Fyre-Breath
- [x] 021 - Gargantes Scrapper
- [x] 022 - Gravelguts
- [x] 023 - Little Rapscal
- [x] 024 - Ogopogo
- [x] 025 - Overrun
- [x] 026 - Power of Fire
- [x] 027 - Ragwarg
- [x] 028 - Shattered Throne
- [x] 029 - Skoll
- [x] 030 - Slimy Jark
- [x] 031 - Smith
- [x] 032 - The Flex
- [x] 033 - Barehanded
- [x] 034 - Bellowing Patrizate
- [x] 035 - Cybergiant Rig
- [x] 036 - Forgemaster Og
- [x] 037 - Grumpus Tamer
- [x] 038 - Guji Dinosaur Hunter
- [x] 039 - Igon the Green
- [x] 040 - Iron Obelisk
- [x] 041 - Kaloch Stonefather
- [x] 042 - Lava Ball
- [x] 043 - Mugwump
- [x] 044 - Nogi Smartfist
- [x] 046 - Pile of Skulls
- [x] 047 - Ragnarok
- [x] 048 - Rock Hurling Giant
- [x] 049 - Signal Fire
- [x] 050 - The Big One
- [x] 051 - The Floor is Lava
- [x] 052 - War Grumpus
- [x] 053 - Igon the Terrible
- [x] 054 - Mega Alaka
- [x] 055 - Mega Cowfyne
- [x] 056 - Mega Ganger Chieftain
- [x] 057 - Mega Groke
- [x] 058 - Mega Gron Nine-Toes
- [x] 059 - Mega Mogghunter
- [x] 060 - Mega Narp
- [x] 061 - Mega Shorty
- [x] 062 - Chieftain's Brew
- [x] 063 - Cowfyne's Brew
- [x] 064 - Groke's Brew
- [x] 065 - Gron's Brew
- [x] 066 - Mogghunter's Brew
- [x] 067 - Narp's Brew
- [x] 068 - Shorty's Brew

**Comment by romanogit** [comment]
In master so far:
- Alaka
- Berserker Slam
- Irestaff
- Mogghunter
- The Grim Reaper

**Comment by romanogit** [comment]
In https://github.com/keyteki/keyteki/pull/497 :

FyreBreath 
PowerOfFire 
Shorty
Skoll
Slimy Jark
Stilt-Kin
The Big One

**Comment by saluk** [comment]
Grim reaper is missing an effect I just noticed - don't check that one off just yet

**Comment by saluk** [comment]
(Also grim reaper is not really brobnar - we might want to do anomaly separate)

**Comment by romanogit** [comment]
Ragnarok implemented in https://github.com/keyteki/keyteki/pull/576

**Comment by romanogit** [comment]
Igon the Green implemented in https://github.com/keyteki/keyteki/pull/579

**Comment by cryogen** [comment]
Brobnar - done
