### ISSUE TITLE
[WC] - New Cards - Untamed

### ISSUE THREAD

**Issue by Achocholacek** [keyteki/keyteki#502]
- [x] 356 - Ghosthawk
- [x] 373 - Gebuk
- [x] 386 - Creed of Nurture

- [x] 353 - Bramble Lynx
- [x] 354 - Cauldron Boil
- [x] 355 - Deepwood Druid
- [x] 357 - Harmonia
- [x] 358 - Imprinted Murmook
- [x] 359 - Key Charge
- [x] 360 - Molephin
- [x] 361 - Musthic Murmook
- [x] 362 - Regrowth
- [x] 363 - Rustgnawer
- [x] 364 - Song of the Wild
- [x] 365 - Tantadlin
- [x] 366 - The Fittest
- [x] 367 - Unnatural Selection
- [x] 368 - Unsuspecting Prey
- [x] 369 - Camouflage
- [x] 370 - Fangtooth Cavern
- [x] 371 - Flaxia
- [x] 372 - Fogbank
- [x] 374 - Grasping Vines
- [x] 375 - Instrument of Silence
- [x] 376 - Kangaphant
- [x] 377 - Low Dawn
- [x] 378 - Mab the Mad
- [x] 379 - Mimicry
- [x] 380 - Nature's Call
- [x] 381 - Panpaca, Anga
- [x] 382 - Panpaca, Jaga
- [x] 383 - The Feathered Shaman
- [x] 384 - Wild Spirit
- [x] 385 - Creed of Nature
- [x] 387 - Curiousity
- [x] 388 - Eldest Bear
- [x] 389 - Fuzzy Gruen
- [x] 390 - Giant Gnawbill
- [x] 391 - Gravid Cycle
- [x] 392 - Inka the Spider
- [x] 393 - Moor Wolf
- [x] 394 - Nepeta Gigantica
- [x] 395 - Perilous Wild
- [x] 396 - Piranha Monkeys
- [x] 397 - Po's Pixies
- [x] 398 - Punctuated Equilibrium
- [x] 399 - Quicksand
- [x] 400 - Roxador
- [x] 401 - Teliga
- [x] 402 - Vineapple Tree
- [x] 403 - Witch of the Wilds
- [x] 405 - Toad

**Comment by romanogit** [comment]
In PR https://github.com/keyteki/keyteki/pull/511/ :
- The Feathered Shaman

**Comment by romanogit** [comment]
I think 387 - Curiousity is from previous sets:
https://keyforge-compendium.com/sets/1-cota/cards/320-curiosity
https://keyforge-compendium.com/sets/2-aoa/cards/351-curiosity

**Comment by romanogit** [comment]
Bramble Lynx added to PR https://github.com/keyteki/keyteki/pull/572

**Comment by romanogit** [comment]
"Unnatural Selection" in PR https://github.com/keyteki/keyteki/pull/579

**Comment by romanogit** [comment]
@Achocholacek :
"Unnatural Selection" in PR #579 is already in master

**Comment by cryogen** [comment]
Untamed - done
