### ISSUE TITLE
[WC] - New Cards - Shadows

### ISSUE THREAD

**Issue by Achocholacek** [keyteki/keyteki#503]
- [x] 235 - A. Vinda
- [x] 236 - Bad Penny
- [x] 237 - Breaker Hill
- [x] 238 - Hit and Run
- [x] 239 - Hock
- [x] 240 - Hugger-Mugger
- [x] 241 - Inky Gloom
- [x] 242 - J. Vinda
- [x] 243 - Kymoor Eclipse
- [x] 244 - Mug
- [x] 245 - Pestering Blow
- [x] 246 - Ronnie Wristclocks
- [x] 247 - Symon
- [x] 248 - Trust No One
- [x] 249 - Umbra
- [x] 250 - Yantzee Gang
- [x] 251 - Brend the Fanatic
- [x] 252 - Chain Gang
- [x] 253 - Duskrunner
- [x] 254 - Fidgit
- [x] 255 - Hidden Stash
- [x] 256 - Into the Night
- [x] 257 - No Safety in Numbers
- [x] 258 - Oubliette
- [x] 259 - Skeleton Key
- [x] 260 - Special Delivery
- [x] 261 - Spike Trap
- [x] 262 - Subtle Chain
- [x] 263 - Subtle Maul
- [x] 264 - Too Much To Protect
- [x] 265 - Whisper
- [x] 266 - Customs Office
- [x] 267 - Finch Cloak
- [x] 268 - Gambling Den
- [x] 269 - Hunter or Hunted?
- [x] 270 - Key of Darkness
- [x] 271 - Keyforgery
- [x] 272 - Lethal Distraction
- [x] 273 - Longfused Mines
- [x] 274 - Mack the Knife
- [x] 275 - Manchego
- [x] 276 - Rigged Lottery
- [x] 277 - Ring of Invisibility
- [x] 278 - Sack of Coins
- [x] 279 - Scowly Caper
- [x] 280 - Selwyn the Fence
- [x] 281 - Sneklifter
- [x] 282 - The Quiet Anvil
- [x] 283 - The Shadow Council
- [x] 284 - Treasure Map
- [x] 285 - Weasand
- [x] 286 - Brobnar Plant
- [x] 287 - Dis Plant
- [x] 288 - Logos Plant
- [x] 289 - Saurian Plant
- [x] 290 - Star Alliance Plant
- [x] 291 - Untamed Plant

**Comment by romanogit** [comment]
269 - Hunter or Hunted?

**Comment by romanogit** [comment]
287 seems to be Dis Plant, not Hideaway hole, even though DoK still does not list as Dis Plant.

**Comment by romanogit** [comment]
@Achocholacek : PR https://github.com/keyteki/keyteki/pull/532 includes all plants: 286, 287 (Dis Plant), 288, 289, 290 and 291

**Comment by romanogit** [comment]
Shadow cards implemented in PR #534:
- AVinda
- BreakerHill
- HitAndRun
- Hock
- HuggerMugger
- InkyGloom
- JVinda
- KymoorEclipse
- Mug
-- PesteringBlow
- SpikeTrap
- Symon

**Comment by romanogit** [comment]
@Achocholacek 
PR #532 includes all plants: 286, 287 (Dis Plant, it is incorrect above), 288, 289, 290 and 291

**Comment by romanogit** [comment]
"276 - Rigged Lottery" is a reprint

**Comment by romanogit** [comment]
"251 Brend the Fanatic" and "276 - Rigged Lottery" are reprint

**Comment by romanogit** [comment]
"251 Brend the Fanatic"
"253 - Duskrunner"
"276 - Rigged Lottery" 
are reprint

**Comment by romanogit** [comment]
Fidgit is implemented in https://github.com/keyteki/keyteki/pull/579

**Comment by romanogit** [comment]
Implemented in #579:
- Fidgit
- Whisper

**Comment by romanogit** [comment]
Implemented the four remaining Shadows in https://github.com/keyteki/keyteki/pull/583

**Comment by cryogen** [comment]
Shadows - done
