### ISSUE TITLE
[WC] - Effects/Abilities

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#513]
Implement WC (and anomalies) abilities:
- [x] enrage
- [x] ward: actions and card changes
- [x] ward: destroy, leaves play
- [x] ward: damage
- [ ] ward: damage / no state update
- [x] ward: move ward
- [x] ward: move damage (check how ward will behave if damage > power)
- [x] exalt
- [x] graft (anomaly)
- [x] invulnerability (anomaly)
- [x] haunt (anomaly)
- [x] Tide (low and high, see valoocanth) (anomaly)
- [x] Reveal opponent's hand (anomaly)
- [x] Key color: select which key to forge
- [x] Key color: permanent effect while key of color is forged (anomaly)
- [x] New counters: growth, glory, doom, disruption, fuse
- [x] Counter on upgrade (GSA Disruption field)

**Comment by cryogen** [comment]
Closing this as all cards are done, I think ward is not perfect but we'll fix that as bugs are raised
