### ISSUE TITLE
[WC] - Anomalies

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#514]
- [x] A01 Ghostform
- [x] A02 Infomancer
- [x] A03 Lateral Shift
- [x] A04 Memolith
- [x] A05 Nizak, the Forgotten
- [x] A06 Orb of Wonder
- [x] A07 The Grim Reaper
- [x] A08 The Red Baron
- [x] A09 Timequake
- [x] A10 Valoocanth

**Comment by Achocholacek** [comment]
A04 - Memolith

**Comment by Achocholacek** [comment]
A05 - Nizak, the Forgotten

**Comment by cryogen** [comment]
done!
