### ISSUE TITLE
Chains reduced incorrectly

### ISSUE THREAD

**Issue by Dunkoro** [keyteki/keyteki#515]
Having a number of cards in hand at the end of turn that's between (non-inclusively) X and Y (where X is hand limit reduced by amount of cards one should draw less because of chains, and Y is the hand limit), one does not shed a chain, where according to the rules they should still do.

**Comment by SkyJedi** [comment]
https://github.com/keyteki/keyteki/pull/562

**Comment by cryogen** [comment]
Fixed in #562 (not yet deployed)
