### ISSUE TITLE
Exhume Automatically Plays Selected Creature

### ISSUE THREAD

**Issue by JTLSound** [keyteki/keyteki#516]
When Exhume is played, it automatically plays the selected creature.

It should, instead, present an option as to whether to play the chosen creature or not. 

The text of of Exhume reads: "You may play that creature as if it belonged to the active house and was in your hand." 

The term "you may" here, gives the option to play the chosen creature or not. This option needs to be implimented.

**Comment by romanogit** [comment]
what would be the other option? If you decide not play, it needs to remain in your discard pile.
It does not say that the creature goes to your hand.

**Comment by JTLSound** [comment]
You should be able to play the card, gain the aember, choose a creature, then, choose to leave it in the discard pile. If you discard Exhume, you wouldn't gain any aember.

**Comment by romanogit** [comment]
In theory, you should not need to select the creature in the discard. It makes no sense at all, right?
