### ISSUE TITLE
Relentless Whispers - Aember not stolen when killing enemy creatures

### ISSUE THREAD

**Issue by Dicky-Boy** [keyteki/keyteki#526]
Used 2 relentless whispers (on a bad penny and an urchin) and in both cases no aember was stolen.

**Comment by bensissel** [comment]
Bump. My relentless whispers hasn't been stealing either. used it on a drummernaut after first playing nerve blast on it. then again on a rematch game and in neither case did it steal. and opponent wouldn't let me manual mode for it either cause it's in competitive que....

**Comment by LifeIsPizza** [comment]
#536 fixes this, as soon as it gets merged
