### ISSUE TITLE
House Card: Cards showing under wrong houses

### ISSUE THREAD

**Issue by justbrown1980** [keyteki/keyteki#528]
When I hover over the card list (the card with the list of cards in the deck) to the left of the "draw" pile, some/all the cards appear under the wrong houses.

Screenshots. please give us a full board screenshot taken as close to when the issue occurs as possible. include both player's boards/decks/discard etc as well as the chat log.

![Screen Shot 2019-10-06 at 8 05 11 pm](https://user-images.githubusercontent.com/4043074/66266746-cd510480-e874-11e9-87bb-b4b96804b253.png)

Chat Log: Bug appears at the start of the game.

**Comment by cryogen** [comment]
Thanks for the report. This should have been fixed with the last update!
