### ISSUE TITLE
Feature request: Add a symbol on the lobby screen for reversal games

### ISSUE THREAD

**Issue by stebsteb** [keyteki/keyteki#531]
Request to add a symbol next to reversal games on the lobby screen, like the one there is for sealed games.

I've had a few pleople join my game, only for them to leave when I start and they realise it is reversal.

Thanks

**Comment by stebsteb** [comment]
https://drive.google.com/file/d/1JNK1lJ-418Sbd5dKPt_Ij5aykeS2N27J/view?usp=sharing

Feel free to use ... or not. This was 10 minutes work so I won't be offended if you come up with something better.

**Comment by cryogen** [comment]
Thanks, I’ve just deployed #530 which resolves this. It wasn’t intended to not have an icon so definitely a bug. Thanks you for the report, and for working on an icon!
