### ISSUE TITLE
Sack of Coins multiple targets

### ISSUE THREAD

**Issue by SieglHertzberg** [keyteki/keyteki#544]
Sack of Coins should be able to target different creatures for each aember in the pool, see Page 11 in the latest rule book v1.4:
“FOR EACH”
Some abilities include an effect that uses the term “for each” to
determine the magnitude of the effect. Unless otherwise specified, a
player may choose to affect a different card with each instance of such
an effect.
Example: Shard of Pain reads “Play: Deal 1 damage to an enemy
creature for each friendly Shard.” That damage may be distributed
among multiple creatures.

**Comment by SkyJedi** [comment]
https://github.com/keyteki/keyteki/pull/540

**Comment by SieglHertzberg** [comment]
Or even more explicitly in the FAQ part, page 28:

"I play the card Sack of Coins (AoA 312) with 3 Æmber in my pool.
Can I divide the 3 damage among multiple creatures?

Yes. Because Sack of Coins deals 1 damage “for each” Æmber in your
pool, each point of damage may be assigned to a different creature."

**Comment by romanogit** [comment]
The issue is fixed, but it needs time to move code to production.
