### ISSUE TITLE
Places which references all houses need to include Saurian and GSA

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#551]
- [x] ExperimentalTherapy
- [x] AbilityTargetHouse
- [x] FreeMarket
- [x] PrinceDerricUnifier
- [x] SelectHousePrompt
- [x] chatcommands
- [x] api/cards.js (/api/factions)
- [x] gameService.getAllGames in stats.js
- [x] Application.jsx
- [x] Profile.jsx
- [x] Messages.jsx

**Comment by cryogen** [comment]
This needs to be made a constant so there’s only two places to change this in future. One server one client

**Comment by romanogit** [comment]
I commited a PR with a suggestion. I put it as a "static" in Card.js.
Any better suggestion?
Util.js? Somewhere else which is reachable by client and server?

Em qua, 9 de out de 2019 2:56 AM, Stuart Walsh <notifications@github.com>
escreveu:

**Comment by cryogen** [comment]
Found it, put my comments there, I'd like, as part of that PR, to have all existing arrays that have house names in removed and using your constant please

**Comment by romanogit** [comment]
It is almost complete, Application and Profile require new houses background
