### ISSUE TITLE
Archimedes vs Collar of Subordination

### ISSUE THREAD

**Issue by YuliYudith** [keyteki/keyteki#552]
Set up: Using Collar of Subordination on an enemy creature and then placing Archimedes next to it.

Archimedes gives the stolen creature "Destroyed: Archive this card" but in the rules it says, if a card leaves play, it goes to the rightful owner. So before the card can enter the opponents archive, it should go to the discard pile of its rightful owner.

Right now, this is not the case. Maybe I'm interpreting the rules wrong but as I learned, it was done like this in Call of the Archons.

**Comment by romanogit** [comment]
I was able to create a test case for this one and it is indeed placing it in the controller's archive, not the owner's archive.
