### ISSUE TITLE
Reactions for onUseCard aren't triggered properly in some cases

### ISSUE THREAD

**Issue by LifeIsPizza** [keyteki/keyteki#560]
Some upgrades like Bonerot Venom & Containment Field that have a trigger onUseCard aren't triggered properly when the card is used to fight with the aid of something else, say a Gauntlet of Command.

Wrote some tests that might add as a PR but haven't found a solution currently

**Comment by mfstormy** [comment]
This is correct. In this game I had put a Containment Field on Maruck the Marked, and they were not destroyed when used

"Uses Gauntlet of Command to ready and fight with Maruck the Marked
Uses Maruck the Marked to make Maruck the Marked fight Nyzyk Resonator
Uses Maruck the Marked to capture 2 amber from stormy, placing it on Maruck the Marked"

**Comment by romanogit** [comment]
@cryogen : I think you fixed Bonerot Venom, right?

**Comment by xoque** [comment]
This still need to be fixed.  A Ghosthawk was played next to a Daughter that had Bonerot Venom on it.  The Daughter reaped, but was not damaged from the Bonerot Venom.

**Comment by cryogen** [comment]
The issue is open, so yes it still needs to be fixed :)
