### ISSUE TITLE
Safe Place & Pocket Universe

### ISSUE THREAD

**Issue by cygnussphere** [keyteki/keyteki#566]
I have had this happen in a couple of games where I have both Pocket Universe and Safe Place on the board at the same time. They both have 2 AE on them and I have 2 in my pool and it TCO has not prompted me to forge a key using the AE from both and later in the Game with more AE on both its prompted me to to use AE from each.

I can supply the screen of the game log if you want it.

**Comment by cryogen** [comment]
Duplicate of #518
