### ISSUE TITLE
Sir Marrows should capture from common supply when Po's Pixies is in play

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#567]
Sir Marrows should capture from common supply when Po's Pixies is in play.

I had a Po's Pixies and opponent had a Sir Marrows. He captured my amber after I reap and the amber came from my pool, not the common supply.

Sir Marrows text says: "After your opponent gains A by reaping, Sir Marrows captures it. " 

Po's Pixies says: A stolen or captured from your pool is taken from the common supply instead.

**Comment by romanogit** [comment]
Relates to #487

**Comment by moliFoot** [comment]
@romanogit Yes, only if there are 1 or more amber on your pool (if you are the owner of the Po's Pixies). In case your pool is empty, sir marrow cannot stole any amber.
