### ISSUE TITLE
Mars first did not ready and use my xanthyx harvester while little rapscal was out

### ISSUE THREAD

**Issue by saluk** [keyteki/keyteki#578]
Playing mars first on a xanthyx harvester readied it, but didn't ask me whether to fight or reap with it.

The image shows the chat log but the game state had moved on:

https://i.imgur.com/nWzynyv.png

**Comment by saluk** [comment]
maybe related: little rapscal + groggins fighting a 3 creature battleline with taunt in the middle should let groggins reap (since he can't fight the flank creatures)

**Comment by JTLSound** [comment]
Did the Harvester have a non-Mars neighbor? It's not clear if this is the case from the linked image. I've also noticed that if there is something in the game that restricts fighting or reaping, the game will automatically choose the other option now. For instance, if your opponent had no creatures to fight, Mars First would cause a creature to automatically reap. Did the game force you to choose a target for the Harvester to fight? Again, it's not clear from the image.

**Comment by JTLSound** [comment]
As for the second point, I think that's a rules question. Taunt states that neighbors Cannot be attacked, while Groggins and Rapscal use Can Only/Must respectively. There's a case to be made that Taunt's Cannot would overrule Groggins' Can Only, allowing it to fight the Taunt creature. But I'm no tournament judge.

**Comment by romanogit** [comment]
Forcing the creature to attack:
![image](https://user-images.githubusercontent.com/2104075/101795946-366e8080-3ae7-11eb-83d7-886e6da31a1f.png)

**Comment by romanogit** [comment]
Need more information to fix this one. Opponent caould have stopped you from fighting and you could have played Xanthyx next to a non-mars creature, so you would be blocked.

This is an old one. Please, report if you see it happening again.
