### ISSUE TITLE
Cannot use Epic Quest before playing 7 Sanctum cards

### ISSUE THREAD

**Issue by strib** [keyteki/keyteki#584]
Epic Quest has an Omni ability.  You should be able to use+exhaust it even if you haven't played 7 Sanctum cards that turn.  This matters in a deck I have because it has 2 Veylan Analysts that I could use to gain aember by using it without sacrificing it.  Thanks, keep up the good work!

**Comment by strib** [comment]
(Similarly, an opponent should be able to Nexus or Remote Access your Epic Quest to exhaust it, making it unusable for you the next turn.)

**Comment by romanogit** [comment]
Fixed in PR #650
