### ISSUE TITLE
Recap (in brackets) the number of keys - Save on clipboard the entire log

### ISSUE THREAD

**Issue by meta-lupo** [keyteki/keyteki#608]
Mr./Mrs. @cryogen is it possible to recap (in brackets) the number of the players keys near the total æmbers at the end of every turn? Helps a lot when People want to read the saved log after the game, to recap errors and so. And is it possible to add a button that saves on clipboard the entire log or select all the log for copying to facilitate archiving games?

Thank you a lot.

(you asked me to put this request as an issue in thecrucible.online chat yesterday; see you again and thank you)

**Comment by donders** [comment]
Copying text that is not in an input field is only possible in Chrome atm AFAIK.
