### ISSUE TITLE
Relentless Whispers does not log its steal effect

### ISSUE THREAD

**Issue by saluk** [keyteki/keyteki#626]
Apparently the aember the players saw after using relentless whispers to steal an aember didn't get updated, so they manually adjusted the values. Later, the values corrected themselves, and they manually changed them back.

![](https://cdn.discordapp.com/attachments/484154914038087680/637464951245766666/Capture.JPG)

![](https://cdn.discordapp.com/attachments/484154914038087680/637465299536576512/Capture.JPG)

**Comment by jeremylarner** [comment]
I think the issue here may actually just be that RW doesn't say in the log that it is stealing

**Comment by jtrussell** [comment]
The non-logging seems to also happen with Finishing Blow. Could be the `effectMsg` is getting silenced for game actions in a `then` block.

**Comment by romanogit** [comment]
They are not used in Then actions. One must define a message/messageArgs.

Main and then are not consistent in messaging

Em qui, 7 de nov de 2019 11:43 PM, Justin Russell <notifications@github.com>
escreveu:
