### ISSUE TITLE
Deploy effect of cards under Jargogle does not work

### ISSUE THREAD

**Issue by AGalassi** [keyteki/keyteki#644]
I've played Little Niff under Jargogle.
When I've caused the death of my Jargogle I wasn't able to use the Deploy ability of Niff and I was forced to choose either one side or the other

The screen is from the turn immediately after mine (I've played a second ZYX researcher on the right side)

![Cattura](https://user-images.githubusercontent.com/34279977/67699965-590a0c80-f9ad-11e9-89a7-3f94236f7859.PNG)
[log.txt](https://github.com/keyteki/keyteki/files/3779813/log.txt)

**Comment by johnnysavs** [comment]
Can confirm this is an issue. I had the same with Jargogle and Ghost Hawk, and also with Code Monkey

**Comment by romanogit** [comment]
Added test case and deploy effect is working.
