### ISSUE TITLE
Taunt/Before Fight Bug

### ISSUE THREAD

**Issue by JTLSound** [keyteki/keyteki#649]
There is a pervasive bug with Taunt and creatures with Before Fight damage abilities.

For instance: Cowfyne attacks Grabber Jammer. To Grabber Jammer's right is Mindwarper, and to Mindwarper's right is Champion Anaphiel. 

Expected Result: Cowfyne deals damage to Mindwarper, then Grabber Jammer and Cowfyne deal damage to each other. Mindwarper and Grabber Jammer are Destroyed, Cowfyne takes 4 damage. 

Current Result: Cowfyne deals damage to Mindwarper, Mindwarper is Destroyed. No other damage dealt. 

I've seen this same result across multiple cards with Before Fight Damage. There's no mechanic in the Keyforge rules to cancel out a fight after targets are selected, even if the target slides next to a Taunt creature. It seems like The Crucible thinks there is.

**Comment by romanogit** [comment]
I believe this issue is fixed, but not yet deployed.
