### ISSUE TITLE
Assault vs Hazardous

### ISSUE THREAD

**Issue by DMP1978** [keyteki/keyteki#654]
Had a game were my Fanghouse (with assault)  fighting Æmberspine Mongrel (with hazardous), Æmberspine Mongrel killed the Fanghouse with the Before fight ability, but assault is also a Before Fight ability, so shouldn't I the active choose which order it goes??

hope u understand

**Comment by cryogen** [comment]
This has been fixed for WC, you should be prompted from then on.
