### ISSUE TITLE
Stuck using Pile of Skulls

### ISSUE THREAD

**Issue by Mantishunter** [keyteki/keyteki#655]
![image](https://user-images.githubusercontent.com/57149320/67791042-29aadc80-fa4d-11e9-9917-21739d5373a6.png)
![Capture Crucible](https://user-images.githubusercontent.com/57149320/67792273-40eac980-fa4f-11e9-90c0-27d7848074aa.JPG)

Sartygo is shuffling their deck
Mantishunter is shuffling their deck
 Sartygo has connected to the game server
 Mantishunter has connected to the game server
Mantishunter is shuffling their deck
Key phase - Sartygo
Sartygo does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Sartygo
Sartygo chooses untamed  as their active house this turn
Main phase - Sartygo
Sartygo plays Nepenthe Seed
Ready phase - Sartygo
Sartygo readies all their cards 
Draw phase - Sartygo
End of turn 1
Sartygo: 0 Æmber  Mantishunter: 0 Æmber 
Turn 1
Key phase - Mantishunter
Mantishunter does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Mantishunter
Mantishunter chooses logos  as their active house this turn
Main phase - Mantishunter
Mantishunter plays Seismo-entangler
Mantishunter plays Labwork, gaining 1 Æmber 
Mantishunter uses Labwork to archive a card 
Ready phase - Mantishunter
Mantishunter readies all their cards 
Draw phase - Mantishunter
Mantishunter draws 4 cards  up to their maximum hand size of 6
End of turn 1
Sartygo: 0 Æmber  Mantishunter: 1 Æmber 
Turn 2
Key phase - Sartygo
Sartygo does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Sartygo
Sartygo chooses untamed  as their active house this turn
Main phase - Sartygo
Sartygo plays Knoxx
Sartygo plays Knoxx
Ready phase - Sartygo
Sartygo readies all their cards 
Draw phase - Sartygo
Sartygo draws 2 cards  up to their maximum hand size of 6
End of turn 2
Sartygo: 0 Æmber  Mantishunter: 1 Æmber 
Turn 2
Key phase - Mantishunter
Mantishunter does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Mantishunter
Mantishunter chooses mars  as their active house this turn
Main phase - Mantishunter
Mantishunter plays Phloxem Spike, gaining 1 Æmber 
Mantishunter plays Mothergun
Mantishunter plays Skybooster Squadron
Ready phase - Mantishunter
Mantishunter readies all their cards 
Draw phase - Mantishunter
Mantishunter draws 3 cards  up to their maximum hand size of 6
End of turn 2
Sartygo: 0 Æmber  Mantishunter: 2 Æmber 
Turn 3
Key phase - Sartygo
Sartygo does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Sartygo
Sartygo chooses brobnar  as their active house this turn
Main phase - Sartygo
Sartygo plays Groke
Ready phase - Sartygo
Sartygo readies all their cards 
Draw phase - Sartygo
Sartygo draws 1 cards  up to their maximum hand size of 6
End of turn 3
Sartygo: 0 Æmber  Mantishunter: 2 Æmber 
Turn 3
Key phase - Mantishunter
Mantishunter does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - Mantishunter
Mantishunter chooses brobnar  as their active house this turn
Main phase - Mantishunter
Mantishunter plays Flamethrower
Mantishunter plays Drummernaut
Mantishunter plays Blood of Titans, gaining 1 Æmber  attaching it to Drummernaut
Mantishunter plays Ganger Chieftain
Mantishunter uses Ganger Chieftain to ready and fight with a neighboring creature
Mantishunter uses Drummernaut to make Drummernaut fight Groke
Mantishunter uses Drummernaut to return Ganger Chieftain to their hand
Mantishunter plays Ganger Chieftain
Ready phase - Mantishunter
Mantishunter readies all their cards 
Draw phase - Mantishunter
Mantishunter draws 4 cards  up to their maximum hand size of 6
End of turn 3
Sartygo: 0 Æmber  Mantishunter: 3 Æmber 
Turn 4
Key phase - Sartygo
Sartygo does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Sartygo
Sartygo chooses logos  as their active house this turn
Main phase - Sartygo
Sartygo plays Archimedes
Sartygo plays Archimedes
 Sartygo has disconnected
 Sartygo has reconnected
 Sartygo has connected to the game server
 Sartygo has connected to the game server
Ready phase - Sartygo
Sartygo readies all their cards 
Draw phase - Sartygo
Sartygo draws 2 cards  up to their maximum hand size of 6
End of turn 4
Sartygo: 0 Æmber  Mantishunter: 3 Æmber 
Turn 4
Key phase - Mantishunter
Mantishunter does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - Mantishunter
Mantishunter chooses mars  as their active house this turn
Main phase - Mantishunter
Mantishunter uses Skybooster Squadron to reap with Skybooster Squadron
Mantishunter uses Skybooster Squadron to return Skybooster Squadron to their hand
Mantishunter plays Skybooster Squadron
Mantishunter plays Agent Hoo-man
Mantishunter plays Martian Generosity, gaining 1 Æmber 
Mantishunter uses Martian Generosity to lose 5 amber, and draw 10 cards 
Mantishunter plays Mindworm
Mantishunter plays Xanthyx Harvester
Mantishunter plays Exterminate! Exterminate!
Mantishunter uses Exterminate! Exterminate! to destroy a non-Mars creature for each Mars  creature they control
Mantishunter uses Mothergun to reveal Mars Needs Æmber and Mars Needs Æmber from their hand, and deal 2 damage to Knoxx
Mantishunter plays Mars Needs Æmber, gaining 1 Æmber 
Mantishunter plays Mars Needs Æmber, gaining 1 Æmber 
Ready phase - Mantishunter
Mantishunter readies all their cards 
Draw phase - Mantishunter
End of turn 4
Sartygo: 0 Æmber  Mantishunter: 2 Æmber 
Turn 5
Key phase - Sartygo
Sartygo does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Sartygo
Sartygo chooses brobnar  as their active house this turn
Main phase - Sartygo
Sartygo plays Bilgum Avalanche
Sartygo plays Champion’s Challenge
Sartygo uses Champion’s Challenge to destroy all enemy creatures except Drummernaut and all friendly creatures except Knoxx
Sartygo uses Knoxx to make Knoxx fight Drummernaut
Ready phase - Sartygo
Sartygo readies all their cards 
Draw phase - Sartygo
Sartygo draws 2 cards  up to their maximum hand size of 6
End of turn 5
Sartygo: 0 Æmber  Mantishunter: 2 Æmber 
Turn 5
Key phase - Mantishunter
Mantishunter does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - Mantishunter
Mantishunter chooses logos  as their active house this turn
Main phase - Mantishunter
Mantishunter plays Eureka!, gaining 1 Æmber 
Mantishunter uses Eureka! to gain 2 Æmber 
Mantishunter plays Labwork, gaining 1 Æmber 
Mantishunter uses Labwork to archive a card 
Mantishunter plays Pip Pip
Mantishunter plays Cutthroat Research, gaining 1 Æmber 
Mantishunter uses Seismo-entangler to stop creatures from brobnar  creatures from reaping next turn
Ready phase - Mantishunter
Mantishunter readies all their cards 
Draw phase - Mantishunter
Mantishunter draws 4 cards  up to their maximum hand size of 6
 Mantishunter declares Check!
End of turn 5
Sartygo: 0 Æmber  Mantishunter: 7 Æmber 
Turn 6
Key phase - Sartygo
Sartygo does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Sartygo
Sartygo chooses logos  as their active house this turn
Main phase - Sartygo
Sartygo plays Interdimensional Graft, gaining 1 Æmber 
Sartygo uses Interdimensional Graft to take any remaining Æmber  from Mantishunter if they forge a key next turn
Sartygo plays Jargogle
Sartygo uses Jargogle to place a card  under Jargogle
Sartygo plays Hexpion
Sartygo uses Nepenthe Seed to return Archimedes to their hand
Sartygo plays Archimedes
Ready phase - Sartygo
Sartygo readies all their cards 
Draw phase - Sartygo
Sartygo draws 4 cards  up to their maximum hand size of 6
End of turn 6
Sartygo: 1 Æmber  Mantishunter: 7 Æmber 
Turn 6
Key phase - Mantishunter
Mantishunter forges a key, paying 6 Æmber 
House phase - Mantishunter
Mantishunter chooses brobnar  as their active house this turn
Main phase - Mantishunter
Mantishunter plays Pile of Skulls
Mantishunter uses Flamethrower to deal 1 damage to Pip Pip and 1 to their neighbors
Mantishunter plays Coward’s End
Mantishunter uses Coward’s End to destroy each undamaged creature
Sartygo uses Jargogle to archive a card 
Sartygo uses Hexpion to archive Hexpion and the top card  of their deck
Sartygo uses Jargogle to return Jargogle to their archives
Mantishunter uses Pile of Skulls to capture 1 Æmber  from Sartygo, placing it on Drummernaut
Mantishunter
i'm stuck
 Mantishunter is attempting to switch manual mode on
Mantishunter
won't let me capture the second aember
 Mantishunter is attempting to switch manual mode on
Sartygo
But i dont ha e the second aember i ha e only one
Mantishunter
i capture the first (it's on drummer)
Sartygo
😟
Mantishunter
ok, i'm fine just trying to get out of it but it has me stuck.
 Sartygo has disconnected
Mantishunter
i won't capture anymore, i just want to be able to continue my turn
 Sartygo has reconnected
 Sartygo has connected to the game server
 Sartygo has connected to the game server
Mantishunter
can you approve manual mode?
 Mantishunter is attempting to switch manual mode on
 Mantishunter mutes spectators
 Mantishunter un mutes spectators
Mantishunter
or deny manual mode, either way, i can't do anything
 Sartygo has disconnected
 Sartygo has reconnected
 Sartygo has connected to the game server
 Sartygo has disconnected
Chat...
Mantishunter
0
3
brobnarlogosmars
Active House:
brobnar
Active Player
.

**Comment by Achocholacek** [comment]
I have updated the test spec to reflect this situation and cannot recreate the issue and am closing the case. 

If this occurs again please let us know.
