### ISSUE TITLE
Silent Dagger should be able to kill Mongrel before gaining amber

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#658]
A creature with [Silent Dagger] reaps and the opponent has [Mongrel]. Can they kill Mongrel before opponent gains the amber? Yes, should be APC.
TCO does not allow the choice

**Comment by romanogit** [comment]
Log
```
iluvatar plays Silent Dagger, gaining 1 Æmber attaching it to Nexus
iluvatar uses Nexus to reap with Nexus
romanomagacho22 uses Æmberspine Mongrel to gain 1 Æmber 
```

**Comment by jeremylarner** [comment]
Have you tested this on master? it should be fixed now

**Comment by romanogit** [comment]
@jeremylarner ,
it is not fixed in master:

![image](https://user-images.githubusercontent.com/2104075/67945110-e5d6e500-fbbc-11e9-9f09-30674789640e.png)

**Comment by romanogit** [comment]
What I noticed is that the behavior is not always the same. Sometimes, it asks me to kill a creature before gaining the amber.

**Comment by jeremylarner** [comment]
You do have the option set to order triggers, right?

**Comment by romanogit** [comment]
Yes.
![image](https://user-images.githubusercontent.com/2104075/67984038-b3e97100-fc04-11e9-80a0-b1bb26a683f9.png)

**Comment by stebsteb** [comment]
Reap abilities resolve _after_ the aember is gained from reap. I don't think this is a bug.

**Comment by romanogit** [comment]
This is now working as epxected:

![image](https://user-images.githubusercontent.com/2104075/101214996-bb771700-365b-11eb-8906-b3e3570bcd3a.png)
