### ISSUE TITLE
City-State Interest: should prompt for creatures if opponent's amber less than friendly creatures in play

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#677]
City-State Interest: should prompt for creatures if opponent's amber less than friendly creatures in play

At the moment, it is choosing the creatures in order of play or battleline (the left most captured the amber)

Other WC card that might have the same problem:
- [x] Xenotraining

Other non-WC cards that might have the same problem:
- [x] Yxili Marauder
- [x] Shard of Hope
- [x] Unguarded Camp
- [x] Pandemonium
- [x] Mars Needs Æmber
- [x] Honorable Claim

New MM
- [x] Spoils of Battle

Those are creatures that capture for each something.

**Comment by bensissel** [comment]
this is still happening for me. Any idea what can be done to fix this?

**Comment by cryogen** [comment]
It's still happening because the issue is not fixed, this issue will be closed when it is fixed

**Comment by romanogit** [comment]
Jadiel fixed this with the CaptureAction refactor. I will go through the cards, simplify them if needed and add test cases.

**Comment by romanogit** [comment]
I checked all cards above and all of them are implemented ok and also using the CaptureAction refactor.
