### ISSUE TITLE
Tireless Crocag remains in play after being destroyed

### ISSUE THREAD

**Issue by ghasolutions** [keyteki/keyteki#679]
I've played a couple games now where I play Tireless Crocag and he remains on the table even after all my opponents creatures are destroyed.

I've also had a game where Tireless Crocag took 8 damage from my opponent and did not leave the field.

Here's a log from a sample round I put together.

`vermithrax is shuffling their deck
vermithrax is playing as the Archon: Pandit Daraspawn, the Proportionate Club
 vermithrax has connected to the game server
vermithrax is shuffling their deck
Key phase - vermithrax
vermithrax does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - vermithrax
vermithrax chooses shadows  as their active house this turn
Main phase - vermithrax
vermithrax plays Subtle Maul
Ready phase - vermithrax
vermithrax readies all their cards 
Draw phase - vermithrax
vermithrax draws 1 cards  up to their maximum hand size of 6
End of turn 1
vermithrax: 0 Æmber 
Turn 2
Key phase - vermithrax
vermithrax does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - vermithrax
vermithrax chooses shadows  as their active house this turn
Main phase - vermithrax
vermithrax plays Umbra
vermithrax plays Seeker Needle
Ready phase - vermithrax
vermithrax readies all their cards 
Draw phase - vermithrax
vermithrax draws 2 cards  up to their maximum hand size of 6
End of turn 2
vermithrax: 0 Æmber 
Turn 3
Key phase - vermithrax
vermithrax does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - vermithrax
vermithrax chooses logos  as their active house this turn
Main phase - vermithrax
vermithrax plays Mother
vermithrax plays Doc Bookton
vermithrax plays Batdrone
Ready phase - vermithrax
vermithrax readies all their cards 
Draw phase - vermithrax
vermithrax draws 4 cards  up to their maximum hand size of 7
End of turn 3
vermithrax: 0 Æmber 
Turn 4
Key phase - vermithrax
vermithrax does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - vermithrax
vermithrax chooses brobnar  as their active house this turn
Main phase - vermithrax
vermithrax plays Coward’s End
vermithrax uses Coward’s End to destroy each undamaged creature
vermithrax plays Tireless Crocag
Tireless Crocag is destroyed as there are no opposing creatures
Ready phase - vermithrax
vermithrax readies all their cards 
Draw phase - vermithrax
vermithrax's chains are reduced by 1 to 2
End of turn 4
vermithrax: 0 Æmber 
Turn 5
Key phase - vermithrax
vermithrax does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - vermithrax`

<img width="1346" alt="Screen Shot 2019-11-03 at 9 29 37 AM" src="https://user-images.githubusercontent.com/7231415/68089365-0309ee80-fe1d-11e9-93a1-354bffe8a7f2.png">

**Comment by cryogen** [comment]
Thanks, this was fixed in #550 but that hasn't gone live yet.
