### ISSUE TITLE
Replicator not considering the upgrades?

### ISSUE THREAD

**Issue by AGalassi** [keyteki/keyteki#680]
I have a 

Ulyq Megamouth upgrade with Red Planet Ray Gun and a Replicator.

What I want to do (and should happen is)

- I reap with Megamouth. (+1 amber)
- I deal X damages to a creature due to the Gun on Megamouth
- I choose to use Replicator due to Megamouth
- I reap with replicator (+1 amber)
- I choose to copy the effect of Megamouth
- I deal X damages due to the copied effect of the Gun on Megamouth
- I can use another creature due to the copied effect of Megamouth (but I don't have any other)

Instead, I deal damages only one time

What happens is

- I reap with Megamouth
- I choose to use Replicator due to Megamouth
- I reap with replicator
- I choose to copy the effect of Megamouth
- I deal X damages (not sure if the Replicator is not replicating the effect or the original Megamouth effect didn't happen)

Log and screen

[log.txt](https://github.com/keyteki/keyteki/files/3801893/log.txt)
![Cattura](https://user-images.githubusercontent.com/34279977/68089606-e8f6fd00-fe6a-11e9-8e0b-0e800c2690a8.PNG)

**Comment by Achocholacek** [comment]
As per Crucible Cast 17, Replicator will not trigger MULTIPLE reap effects, but rather only a single reap effect, chosen by the active player.

Right now it simply defaults to duplicating the base reap effect of the card being replicated, and does not give the active player the choice of which reap effect (if multiple are present) to duplicate.

I can replicate this behaviour and have updated the test case to reflect it.

Unfortunately this will require a change to the core Replicator card code (as reflected in the TODO) to allow APC on which reap effect to duplicate.

**Comment by jeremylarner** [comment]
Fixed in #1247
