### ISSUE TITLE
Chaos Portal + Duskwitch (and possibly any Omega) doesn't End the turn and it should

### ISSUE THREAD

**Issue by ira212** [keyteki/keyteki#690]
Steps to Repro:
1) Have Chaos Portal in Play
2) Choose Untamed and use Chaos Portal to choose Untamed and reveal Duskwitch on the top of your deck.

Notice that your turn doesn't end.
Expected Behavior: Playing any Omega card (including Duskwitch) should

Here is a deck you can use to test if it's fixed, including a couple different Omega cards (Duskwitch, Gravid Cycle) and Alpha cards too (Glimmer and Binate Rupture) - I'm not sure if Chaos Portal respects Alpha either.

https://www.keyforgegame.com/deck-details/a5e58c6e-f9ed-495d-805a-99eb371a7788

**Comment by romanogit** [comment]
Fixed
