### ISSUE TITLE
Banish (Dis) and enemy controlled creatures

### ISSUE THREAD

**Issue by YuliYudith** [keyteki/keyteki#701]
If an opponent gains control of an enemy creature (through Murkens, Collar of Subordination), he has that creature on his side of the board and could use it. 

If I then play Banish (put an enemy creature into your opponent's archive) on this creature, it should go into my discard pile. Because my creature is leaving play to be put into my opponent's archive, it goes into my appropriate out of play zone (discard pile). It does not go into my opponent's archive because it's my card and leaves play and it certainly never can be put into my archive. Because although I'm the creature's opponent, the card clearly states: "into **your** opponent's archive" not the creature's opponent's archive. 

At the moment it is implemented so that the creature goes into my archive.

**Comment by romanogit** [comment]
This is a rule question that needs an FAQ, but the general understanding from the commit is that it should go to the owner's archive as it is implmented by TCO

**Comment by YuliYudith** [comment]
Why should it go to the owners archive? That makes no sense. The Banish card says put an enemy creature into your opponent's archive. When the creatures goes into his archive it leaves play, going into my out of play zone - discard pile. I don't see no rule problem? What am I missing?

**Comment by jtrussell** [comment]
Often cited is this Faygin ruling that you can find the FAQ section of the rulebook:

> I have a Faygin (CoTA 300) in play and my opponent has an Urchin
(CoTA 315) in play. I reap with Faygin and with its reap effect I
choose my opponent’s Urchin. What happens?

> Faygin’s effect causes the Urchin to try and go into your hand, however
when a card leaves play it always goes to its owner’s corresponding out
of play zone (See “Leaves Play” on Page 11) unless the card causing it to
leave play specifies otherwise. The Urchin is returned to your opponent’s
hand instead of yours.

**Comment by YuliYudith** [comment]
Yes, thank you for replying, I understand that completely. Although I think, it's a weird ruling and I'm still unclear if that will apply to the archive. That remains to be seen.

**Comment by romanogit** [comment]
Commentary from AA:
Banish's Play: ability does not allow for a change of control, so when Banish is played on an enemy card that has previously changed control, the rules for Leaves Play dictate that the targeted card will go into its Owner's archives, regardless if the Owner is the opponent or not.

About to select a controlled creature:
![image](https://user-images.githubusercontent.com/2104075/101066398-1d108600-3575-11eb-9ab1-5aba43cd62a0.png)

![image](https://user-images.githubusercontent.com/2104075/101066476-3b768180-3575-11eb-92f5-83f71542381d.png)

Working as expected...
