### ISSUE TITLE
Buzzle forces purge

### ISSUE THREAD

**Issue by muircurial** [keyteki/keyteki#707]
Buzzle's text states you "May" purge a creature, but currently on Crucible you must.

**Comment by romanogit** [comment]
Yesterday I worked on its test case and I am pretty sure you can opt not to
choose a neighbor by clicking 'Done'.

Can you post a screenshot right after you reap with it?

Em sex, 8 de nov de 2019 11:30 AM, muircurial <notifications@github.com>
escreveu:

**Comment by muircurial** [comment]
![buzzle](https://user-images.githubusercontent.com/7585185/68485010-6ffdf980-020c-11ea-8fbd-7258f5201191.png)

So this is after I played Buzzle. Couldn't choose not to purge. In previous example, which I don't have a screenshot, I had played, was forced to purge, used him to fight, and was forced to purge again. There is no Done button shown.

**Comment by lupo82** [comment]
same problem here, the DONE button doesn't show 
![Screenshot (216)](https://user-images.githubusercontent.com/54270461/68485536-cb95aa80-023f-11ea-9652-6a6186e7dcc4.png)

**Comment by romanogit** [comment]
ok, my mistake. Will handle it.

**Comment by muircurial** [comment]
Thanks romanogit!

**Comment by lupo82** [comment]
don't worry and thanks for your nice work!
