### ISSUE TITLE
Decklist/House Choice Bug possibly due to anomaly

### ISSUE THREAD

**Issue by OsramTaleka** [keyteki/keyteki#709]
This deck (Pérez, the Baker of Southplace)
![Anomaly Bug](https://user-images.githubusercontent.com/53394971/68484781-cc541f80-01f2-11ea-847b-ccd4e82de82b.png)
 has an Orb Of Wonder anomaly in Saurian. On the deck page, the Orb Of Wonder is missing from the list and the Star Alliance list is glitched. During games, if the Orb Of Wonder is in my hand, Star Alliance appears twice in my house choices. One of the selections has the house Icon and the other does not. When I choose the Star Alliance with no icon, no cards are able to be selected from my hand or the board.

**Comment by cryogen** [comment]
I'm guessing you added your deck to the site before today?  There's a known issue with decks imported before today.  I will be running a script later this afternoon to fix those existing decks.  In the mean time if you desperately want to play with it right now, remove and re-add it

**Comment by OsramTaleka** [comment]
I did yep. Just removed and re-added it and it came up just fine! Sorry about that!
