### ISSUE TITLE
New Set Starting turn play

### ISSUE THREAD

**Issue by KeyforgeJupiter** [keyteki/keyteki#711]

**Comment by romanogit** [comment]
What is the issue here?

**Comment by romanogit** [comment]
Is this the same as #712?

**Comment by KeyforgeJupiter** [comment]
Yeah I think it copied it lol
But on my first turns it is making me discard everything. Wont let me play a card.

Sent from Mail for Windows 10

**Comment by cryogen** [comment]
Duplicate of #712
