### ISSUE TITLE
Play effect on Medic Ingram does not trigger twice when Sci. Officer Morpheus is in play

### ISSUE THREAD

**Issue by jtrussell** [keyteki/keyteki#714]
Apologies, I meant to grab the text log after the game and then forgot.

You can see from the screenshot below that:

- Morpheus gets played,
- Tactical Officer Moon gets played (play effect triggers twice as expected)
- Medic Ingram gets played (play effect triggers once)

![image](https://user-images.githubusercontent.com/732758/68485280-06cab600-020d-11ea-80f4-dec8308a5a76.png)

**Comment by OsramTaleka** [comment]
I had the same thing happen but with Sci. Officer Morpheus and Information Officer Gray.
![Officers](https://user-images.githubusercontent.com/53394971/68486375-d0357100-01f5-11ea-8a92-b7e0407fcd44.png)

**Comment by muircurial** [comment]
Same for Morpheus and Medic Ingram here.
![image](https://user-images.githubusercontent.com/7585185/68503655-61760900-0231-11ea-9148-a33b9ac16d17.png)

**Comment by SkyJedi** [comment]
![image](https://user-images.githubusercontent.com/2967416/68513528-dac92800-0240-11ea-80c9-1bb74f27c76c.png)
![image](https://user-images.githubusercontent.com/2967416/68513562-f03e5200-0240-11ea-8062-c453affef649.png)

**Comment by avandever** [comment]
Same for me, but with Frane. I pulled the log.
Copypasta log and screenshot at https://justpaste.it/7tu6c, tracker log at https://www.thecrucibletracker.com/games/ca44da30-0284-11ea-91e0-a5a22d3f9d00/log.

**Comment by romanogit** [comment]
It is a silly mistake. It only happens if Sci. Officer Morpheus is not on a center.
I will work on the fix.
