### ISSUE TITLE
Center of Battleline with even numbered field

### ISSUE THREAD

**Issue by OsramTaleka** [keyteki/keyteki#716]
The newest rules update determined the center of the battleline (For cards like Captain Val Jericho) to only exist in the middle of battlelines with an odd number of creatures (Including 1). It looks like at least for Captain Val Jericho, even numbered battlelines are counting the middle two creatures as the center
![Battleline](https://user-images.githubusercontent.com/53394971/68486033-2ce45c00-01f5-11ea-8564-94ca54454eea.png)

**Comment by muircurial** [comment]
Can confirm. Also had this occur.

**Comment by romanogit** [comment]
Found the bug. Will fix it.
