### ISSUE TITLE
Borr nit's touch doesn't trigger play ability

### ISSUE THREAD

**Issue by Ahoapap** [keyteki/keyteki#719]
When playing Borr Nit's touch, the user is not left with any choices.

![borr nits](https://user-images.githubusercontent.com/4840179/68486901-af761700-0207-11ea-8855-417c74df017f.PNG)

**Comment by Foolishbigj** [comment]
I just stopped by to say the same thing. The touch didn't trigger and there isn't really a way to do this manually.

**Comment by hydrophilic-attack** [comment]
yeah this happened in a game i was in too
