### ISSUE TITLE
Encounter Suit

### ISSUE THREAD

**Issue by bensissel** [keyteki/keyteki#720]
Had encounter suit on a creature. It's not warding the creature when an action is played. It literally isn't doing anything.

Encounter suit was attached to Questor Jarta. The action played was Unlocked Gateway. everything got destroyed so no ward was added. I then manually moved Questor back and put encounter suit on it and no action - no matter if it was played by myself or opponent, would add a ward counter to the creature.

**Comment by cryogen** [comment]
Whoops, we seem to have missed a card!

**Comment by SkyJedi** [comment]
![image](https://user-images.githubusercontent.com/2967416/68513505-cdac3900-0240-11ea-880b-7ec01b43d9cf.png)

**Comment by KeyforgeJupiter** [comment]
I am having the same problem

**Comment by cryogen** [comment]
Fixed
