### ISSUE TITLE
Buzzle forces purge?

### ISSUE THREAD

**Issue by sighentist** [keyteki/keyteki#730]
I played Buzzle next to Snag and the only option I had was to choose Snag to purge it and ready Buzzle (card says it's a 'may' effect). I'm sorry I didn't get a screenshot at the time :(

**Comment by cygnussphere** [comment]
I have the same thing happening.

**Comment by muircurial** [comment]
Reported this earlier. Issue was closed, but may not have been pushed yet.

**Comment by cryogen** [comment]
Indeed, is fixed and not deployed, leaving this issue open as people keep reporting it, must be a popular card :)

**Comment by cryogen** [comment]
Fix for this is deployed now
