### ISSUE TITLE
GhostForm

### ISSUE THREAD

**Issue by KeyforgeBeans** [keyteki/keyteki#731]
My opponent had Ghostform on a creature, but its neighbors also did not take damage.

**Comment by cryogen** [comment]
Will need more information on this one, there's nothing in the code that would be causing this.

Where they warded?

**Comment by KeyforgeBeans** [comment]
They were not, but I realize now that it happened around the time the
server crashed, so that may have been the issue.

**Comment by KeyforgeJupiter** [comment]
Ghostform is blanketing all the battle line instead of just the one creature

**Comment by cryogen** [comment]
That should be fixed now

**Comment by KeyforgeJupiter** [comment]
I am in a game that it is not


Sent from Mail for Windows 10
