### ISSUE TITLE
feature request: manual mode command to discard cards from top of deck

### ISSUE THREAD

**Issue by hydrophilic-attack** [keyteki/keyteki#735]
when borr nit's touch bugged out, we tried to resolve it by hand. but it appears there was no way to discard the top card of the deck. i would have to first draw cards, then manually discard them one by one. i could cheat that way though and discard different cards from hand than the ones i drew

so a command to discard from top of deck would be nice

**Comment by cryogen** [comment]
Typing /discard in manual mode would achieve this

**Comment by Achocholacek** [comment]
/discard <x> does indeed work as expected. closing.
