### ISSUE TITLE
Sic Semper Tyrannosaurus on warded creature still destroys creature

### ISSUE THREAD

**Issue by muircurial** [keyteki/keyteki#748]
Used Sic Semper on a warded Tribune Pompitus. Aember was transferred, but the ward removed and creature destroyed. Correct ruling or bug?

![image](https://user-images.githubusercontent.com/7585185/68503822-c0d41900-0231-11ea-837b-377ef6bbdf94.png)

**Comment by romanogit** [comment]
If the creature is warded, it should not destroy it. I will take a look

**Comment by romanogit** [comment]
Is the creature really destroyed? just ran a test case and it passes.
Can you highlight it in the discard?
Isn't it in the battleline?

**Comment by SkyJedi** [comment]
![image](https://user-images.githubusercontent.com/2967416/68509068-b451bf80-0235-11ea-80f7-ef852f26f248.png)
![image](https://user-images.githubusercontent.com/2967416/68509090-c29fdb80-0235-11ea-8c7d-2c1940b439ec.png)

**Comment by muircurial** [comment]
Romanogit, this was a while ago so I can't pull up the discard, but you can probably see in the chat log how it played it. Reaped with Tribune, used Sic Semper on it, and then it goes to discard after being destroyed even though it was warded. Cannot see it as I discarded the Meteor. However, Jupiter has a point and I cannot remember the particulars.

I do not remember if it had damage on it, Jupiter, so there is a possibility that it became 0 power after Aember was removed.
