### ISSUE TITLE
Mug With No Aember on Field

### ISSUE THREAD

**Issue by JTLSound** [keyteki/keyteki#749]
As Mug targets Aember, and not a creature, if there is no aember on the field, it should just give the player 1 aember, and enter the discard. Instead, it prompts the player to select a creature, and deals damage.

For a further explanation, Mug says "Play: Move 1 Æmber from a creature to your pool. Deal 2 damage to that creature." The card cannot target a creature without moving aember. If you cannot move an Aember, there is no creature to deal damage to.

**Comment by romanogit** [comment]
I think there is room for discussion here. I will mark as rule question

**Comment by JTLSound** [comment]
I can see that. It's just worded so oddly as is. Have to say, if the card started with "Select a creature with Aember on it," things would be much clearer. Alas, it is not.

**Comment by SkyJedi** [comment]
![image](https://user-images.githubusercontent.com/2967416/68508050-faf1ea80-0232-11ea-81d9-509bf5fef330.png)

**Comment by JTLSound** [comment]
Thanks!!!
