### ISSUE TITLE
Zap hits shield instead of removing Ward

### ISSUE THREAD

**Issue by muircurial** [keyteki/keyteki#752]
Used Zap with 3 houses in play. Applied 1 damage to a dino with 1 shield and a ward and then 2 damage to star alliance guy. Shield soaked the damage and ward remained. The latest timing chart indicates the ward should be removed first, then damage to shield.

![image](https://user-images.githubusercontent.com/7585185/68506249-34c4f000-0237-11ea-8c32-180155561380.png)

**Comment by romanogit** [comment]
This is an incremental damage issue. I will check it.
