### ISSUE TITLE
Information Officer Gray Reap ability not revealing card which was archived

### ISSUE THREAD

**Issue by muircurial** [keyteki/keyteki#753]
Information Officer Gray Reap ability not revealing card which was archived. Please see chat log to confirm. Thanks!

![image](https://user-images.githubusercontent.com/7585185/68506387-8a999800-0237-11ea-9eaa-2bdc423fe70a.png)

**Comment by SkyJedi** [comment]
![image](https://user-images.githubusercontent.com/2967416/68509455-920c7180-0236-11ea-8e6c-81b5ce770771.png)

**Comment by cryogen** [comment]
Fixed in #762
