### ISSUE TITLE
Code Monkey checks that archived cards are both CM's house instead of matching each other

### ISSUE THREAD

**Issue by jtrussell** [keyteki/keyteki#757]
My opponent deployed Code Monkey between two Untamed creatures.

What happened:

- They gained no amber.
- The messaging says they "gained 2 amber for each house they share with Code Monkey".

What I think should have happened:

- My opponent should have gained 2 amber
- The message should note that amber is gained when the creatures being archived share a house rather than when their house matches Code Monkey's house.

![image](https://user-images.githubusercontent.com/732758/68509096-28906100-023e-11ea-82f4-473c17a4d14a.png)

**Comment by SkyJedi** [comment]
![image](https://user-images.githubusercontent.com/2967416/68509513-b10b0380-0236-11ea-8023-bf439e7b184f.png)
