### ISSUE TITLE
[WC-014] Stilt-Kin ability procs when non-giants are placed adjacent

### ISSUE THREAD

**Issue by mortivas** [keyteki/keyteki#758]
Stilt-kin appears to proc off non-giant creatures. In my case it was Little Rapscal (goblin) and then later with Musthic Murmook (beast). Screenshot and chat log below!

****************************
Stilt-Kin • 014 • Brobnar • Creature • Goblin • Power: 2 • Common • WC • Skirmish. (When you use this creature to fight, it is dealt no damage in return.) After a Giant creature is played adjacent to Stilt-Kin, ready and fight with Stilt-Kin. skyj.io/36I9ac8
****************************

Chat Log:
https://gist.github.com/mortivas/b57edeca2144eee2d85a10e075ac0061

![stilt](https://user-images.githubusercontent.com/55995924/68509562-32ff2a80-023f-11ea-9f33-97a3eb32e004.PNG)

**Comment by romanogit** [comment]
Fixed

**Comment by SkyJedi** [comment]
![image](https://user-images.githubusercontent.com/2967416/68512353-c8012400-023d-11ea-8d26-0be639840563.png)
