### ISSUE TITLE
Moor Wolf Exhalted Mysteriously

### ISSUE THREAD

**Issue by JTLSound** [keyteki/keyteki#760]
My Moor Wolf was mysteriously Exhalted when it was used to Fight. I removed the aember in manual.
![Moor Wolf](https://user-images.githubusercontent.com/49758354/68510828-81fa8f00-0242-11ea-9f61-369e6a476a9c.jpg)

**Comment by SkyJedi** [comment]
https://decksofkeyforge.com/cards/moor-wolf
![image](https://user-images.githubusercontent.com/2967416/68513398-8625ad00-0240-11ea-8078-94f14e39f66e.png)

**Comment by romanogit** [comment]
I was not able to reproduce this one, so I will try adding test cases.

**Comment by romanogit** [comment]
@JTLSound ,
I know this is an old one. Any chance Diplo-Macy was played by your opponent:

![image](https://user-images.githubusercontent.com/2104075/79698588-50a9d480-8260-11ea-973b-4a36afe289c0.png)

**Comment by romanogit** [comment]
There is a good chance you played againt this deck: https://decksofkeyforge.com/decks/733b50ad-fbd3-4063-a171-d6a216c88074
which does contain Diplo-Macy
