### ISSUE TITLE
[WC 028] Shattered Throne doesn't capture for opponents attacks

### ISSUE THREAD

**Issue by mortivas** [keyteki/keyteki#764]
Screenshot and chat log below. It captures just fine for the player who played/controls the artifact, but not for the opposing player.

Chat Log:
https://gist.github.com/mortivas/b76298e81f1a4233148ee1318abc851a

![shattered-throne](https://user-images.githubusercontent.com/55995924/68513476-1c5dd100-0249-11ea-926d-f48d9475d833.png)

![shattered throne](https://user-images.githubusercontent.com/55995924/68513502-2bdd1a00-0249-11ea-944f-2b23d42db378.PNG)

**Comment by SkyJedi** [comment]
i love you posting a card image
