### ISSUE TITLE
Dr Milli claims to archive a negative number of cards

### ISSUE THREAD

**Issue by Dicky-Boy** [keyteki/keyteki#765]
When playing Dr Milli with more creatures than opponent, chat message claims to archive a negative number of cards e.g.:

"Player uses Dr. Milli to archive -1 cards"

No cards are archived, appears it's just the chat message which is incorrect.

**Comment by SkyJedi** [comment]
![image](https://user-images.githubusercontent.com/2967416/68517070-9d1dcc80-024b-11ea-9a88-ce08d08ad283.png)

**Comment by mnapoleon** [comment]
I'll take a look at this one

**Comment by Jimmwils** [comment]
I also had this issue but I had played Dr. Milli and was unable to clear the prompt asking me to select a negative number of cards to archive
