### ISSUE TITLE
book of leQ ended the other player's next turn

### ISSUE THREAD

**Issue by hydrophilic-attack** [keyteki/keyteki#767]
My opponent had book of leQ. They used it but a star alliance card was revealed. This ended their turn correctly. However, the problems started on my turn which came after. I could only play 1 card before the game automatically ended my turn whether I wanted to or not. See the attached log.
[leQ+multiple upgrades+playing upgrades in manual mode.txt](https://github.com/keyteki/keyteki/files/3826625/leQ%2Bmultiple.upgrades%2Bplaying.upgrades.in.manual.mode.txt)

Trouble started on turn 4

**Comment by SkyJedi** [comment]
![image](https://user-images.githubusercontent.com/2967416/68517079-ac9d1580-024b-11ea-959a-a7f92b561b87.png)
