### ISSUE TITLE
Stilt-kin triggers when non-giant creature played adjacent

### ISSUE THREAD

**Issue by Dicky-Boy** [keyteki/keyteki#770]
Stilt-kin seems not to consider whether the card played next to it is a giant, triggering regardless

**Comment by Dicky-Boy** [comment]
Duplicate of #769  (apologies)

**Comment by mnapoleon** [comment]
Appears this was also fixed by #761 commit 52c228ff80f4e7370ada325caaba3ecd83dc10c2
