### ISSUE TITLE
Robot creatures used as uprades

### ISSUE THREAD

**Issue by n00noom4st3r** [keyteki/keyteki#774]
I upgraded a creature (I believe Praefectus Ludo) with CALV-1N, but then a few turns later, when i nominated Star Alliance as my active house, the game gave me the option to reap with CALV-1N, even though it was now considered an upgrade. So I believe this was a bug as the game still considered CALV-1N a creature despite it now being an upgrade. What's interesting is that the game didn't give me the option to fight with CALV-1N, so it knew something was wrong but it still allowed me to reap with it.

I'm sorry I don't have screenshots or copies of the chat log, I'm posting this issue a few hours after the problem because I assumed it was an intended mechanic at first, but a couple of reddit threads later I realised it must have been a bug.

**Comment by SkyJedi** [comment]
![image](https://user-images.githubusercontent.com/2967416/68522694-d2d6ab80-0273-11ea-958c-d90f4f6f299c.png)
reproduced
