### ISSUE TITLE
Weasand Does Not Grant Aember When Opponent Forges

### ISSUE THREAD

**Issue by JTLSound** [keyteki/keyteki#776]
Weasand will not give Aember when an opponent forges a key. Seen in two games now.
![Weasand](https://user-images.githubusercontent.com/49758354/68523826-7338ca00-028c-11ea-8283-f18d48939bb8.jpg)

**Comment by cryogen** [comment]
Apparently we missed another card!

**Comment by romanogit** [comment]
![image](https://user-images.githubusercontent.com/2104075/68532143-2fb77d80-02d7-11ea-8045-3f3258412b82.png)

**Comment by JTLSound** [comment]
To be clear, it does grant aember with I forge.

**Comment by romanogit** [comment]
oh, that's true.
