### ISSUE TITLE
Double Harbinger + Soul Snatcher caused huge aember gain

### ISSUE THREAD

**Issue by strib** [keyteki/keyteki#781]
I had a big board of like 12 creatures, including 2 Harbinger of Dooms.  I also had out a Soul Snatcher.  My opponent had 2 creatures.

I played Draining Touch on one of my own Harbingers.  That seemed to cause a recursive loop where each Harbinger kept destroying the other Harbinger and all the other creatures, over and over again, and we each got one aember for every destruction, ending with 10,000s of aember.

Here's a screenshot, the log was too long to capture:
![Screenshot from 2019-11-08 22-55-50](https://user-images.githubusercontent.com/8516691/68524414-78d9e400-027b-11ea-880a-7dcd0724f6ac.png)

My client basically froze as well.

**Comment by cryogen** [comment]
Well, that's pretty hilarious :)

**Comment by Kaosumaru** [comment]
I also encountered error with two harbringers :)

`Kaosumaru uses Harbinger of Doom to make Harbinger of Doom fight Saurus Rex
Kaosumaru uses Harbinger of Doom to destroy Com. Officer Kirby, CALV-1N, Sci. Officer Morpheus, Medic Ingram, Saurus Rex, Odoac the Patrician, and Harbinger of Doom
damianxian uses CALV-1N to remove its ward token
damianxian uses Medic Ingram to remove its ward token
Kaosumaru uses Harbinger of Doom to destroy Com. Officer Kirby, CALV-1N, Sci. Officer Morpheus, Medic Ingram, Saurus Rex, Odoac the Patrician, and Harbinger of Doom
Kaosumaru uses Harbinger of Doom to destroy Com. Officer Kirby, CALV-1N, Sci. Officer Morpheus, Medic Ingram, Saurus Rex, Odoac the Patrician, and Harbinger of Doom`

Not sure how double harbringers should react with ward, but I would say that
1. First harbringer dies, it's marked for destruction, marks all other creatures as "marked for destruction" (destroyed abilities happens), and removes ward from others
2. Second harbringer is marked for destruction, its destroyed ability marks for destruction previously warded creature

**Comment by Kaosumaru** [comment]
Seems that DestroyAction doesn't check if card is already marked for destruction, and allows Destroyed effects to trigger once again after game want to destroy card already marked for destruction.

Card should "save" current Destroyed effects when marked for destruction, and then trigger them only once.

Also, per instruction  we shouldn't be able to be able to destroy or sacrifice card after it was marked for destruction. Connected to #457 ?

**Comment by cryogen** [comment]
@jeremylarner is looking at this I believe

**Comment by jeremylarner** [comment]
Fixed in #825
