### ISSUE TITLE
Gamblin Den artifact does not properly work

### ISSUE THREAD

**Issue by LucaAmbrosino** [keyteki/keyteki#782]
With this artifact in play, each turn the active player gain two aember, even without the revealed card is not the named one.

**Comment by romanogit** [comment]
Do you have more information about the state of the game?
The test cases are working and I was not able to reproduce:

![image](https://user-images.githubusercontent.com/2104075/68533485-a445e880-02e6-11ea-9c6f-376d77d51ebb.png)

![image](https://user-images.githubusercontent.com/2104075/68533489-bd4e9980-02e6-11ea-891b-00f88172369c.png)

**Comment by LucaAmbrosino** [comment]
I consider it as solved, because now I tried a new game and Gamblin Den properly worked.
