### ISSUE TITLE
Moor wolf got ready but can't click on it

### ISSUE THREAD

**Issue by HalifBakri** [keyteki/keyteki#783]
Hi,

I had 4 moor wolves in my hand and when I placed my last moor wolf I wasn't allowed to use my other 3 moor wolves. Prior to placing the last Moor wolf I had been attacking and reaping with them.

I've only encountered this once since it is quite rare to get all 4 in one hand.

Here is the deck I was using.

https://www.keyforgegame.com/deck-details/a6c046ba-b3b3-4aea-8794-b10a2adc5ac6

**Comment by SkyJedi** [comment]
If you had 4 you'd hit the rule of six after playing the third.

Play-Play-Reap-play-reap-reap

6 uses and you can't use again

**Comment by HalifBakri** [comment]
Ah ok thanks for clarifying it.
