### ISSUE TITLE
Com. Officer Kirby allows multiple cards to be played on first turn

### ISSUE THREAD

**Issue by Dicky-Boy** [keyteki/keyteki#784]
Opponent played Com. Officer Kirby on turn 1, which then enabled them to play an extra card.

<img width="313" alt="Screen Shot 2019-11-09 at 15 39 24" src="https://user-images.githubusercontent.com/22052583/68531156-3cec6080-0307-11ea-9e97-c19e0175a85b.png">

**Comment by cryogen** [comment]
I see this the same as phase shift:

> Playing Phase Shift will allow you to play another card from your hand this turn, since the First Turn Rule can be modified by card effects.
