### ISSUE TITLE
Trust no one

### ISSUE THREAD

**Issue by wo3dy** [keyteki/keyteki#788]
"Trust no one" doesnt trigger its steal effect.
atleast with the second option of the effect 
(when no friendly creatures...)

game log if that helps (Turn 10)
https://www.thecrucibletracker.com/games/85dec040-0301-11ea-91e0-a5a22d3f9d00

**Comment by SkyJedi** [comment]
![248](https://user-images.githubusercontent.com/2967416/68537608-784d5600-032c-11ea-8d9d-d043fb928a33.png)

**Comment by cryogen** [comment]
I'm not sure what the issue is here?  From looking at your log it seems to do exactly what I'd expect.

You go from 5 amber to 8 amber, as there are 3 hours in play from the other side of the board?

**Comment by wo3dy** [comment]
thats manualy changed.
cause it didnt do what it should

**Comment by SkyJedi** [comment]
i can't reproduce this
