### ISSUE TITLE
Nightforge didn't offer to forge key as expected

### ISSUE THREAD

**Issue by MKHAUS** [keyteki/keyteki#789]
When playing Nightforge it should offer player to forge at 10 aember unless 1) The current cost is not six, or 2) The player had already forged that turn.

In this example I checked that neither were prohibiting the card from firing. This has worked for me in the past so I'm not sure what had changed. Perhaps I'm mistaken but I don't think so. I'll see if I can recreate it since I assume it's intermittent. 

![image](https://user-images.githubusercontent.com/13820050/68532984-2687da00-02f2-11ea-99ce-ca5c2f8bec92.png)

**Comment by SkyJedi** [comment]
![291](https://user-images.githubusercontent.com/2967416/68537597-45a35d80-032c-11ea-85a3-5dc44681b600.png)

**Comment by SkyJedi** [comment]
lets ignore the fact that i broke this, yeah 

https://github.com/keyteki/keyteki/commit/cf4106418b3f143291e88bf553f7775a1124f2ed#diff-de288cb146e577e736d41adc6bcf9af6
