### ISSUE TITLE
Phalanx Strike didn't offer to exalt

### ISSUE THREAD

**Issue by MKHAUS** [keyteki/keyteki#792]
I feel like I had this trigger previously where I had the option to exalt but in this case I wasn't given the option to exalt. I had creatures on the board and aember with which to exalt. I didn't, however, have any Saurian on the board so perhaps that was the issue?

![image](https://user-images.githubusercontent.com/13820050/68533410-94ce9b80-02f6-11ea-94cc-cbbdb737698f.png)

**Comment by cryogen** [comment]
You didn't get this prompt? 
<img width="246" alt="image" src="https://user-images.githubusercontent.com/1053365/68534212-80f05d00-0329-11ea-846e-a30c85c412f2.png">

**Comment by MKHAUS** [comment]
Maybe I did, but I don't think so. I'll try to recreate to be certain. Perhaps declining a prompt option should be logged.

**Comment by MKHAUS** [comment]
I guess I do get the prompt. I think perhaps what threw me off is the Tribute explicitly asks if you want to exalt to repeat the effect and Phalanx Strike did not. So it's not a bug but maybe they could be made more consistent.
