### ISSUE TITLE
Senator Bracchus not allowing aember on other friendly creatures to be used to forge

### ISSUE THREAD

**Issue by Jimmwils** [keyteki/keyteki#795]
Only aember on Senator Bracchus himself is offered to forge a key, whereas his ability should let you use aember on any friendly creature

**Comment by SkyJedi** [comment]
![229](https://user-images.githubusercontent.com/2967416/68537575-096ffd00-032c-11ea-816f-a6b4ce484b71.png)

**Comment by cryogen** [comment]
Duplicate of #816 (yours was first but i've added other details to that issue)
