### ISSUE TITLE
Obsidian Forge sacrifices your creatures and doesn't let you forge a key

### ISSUE THREAD

**Issue by Josemmb97** [keyteki/keyteki#797]
When using Obsidian Forge at 8 aember, I sacrificed 6 creatures and didn't let me forge my key (current cost was 6). The creatures went to the discard pile but Obsidian Forge was still there, as if I used it just for sacrificing my creatures lol. Thanks for your patience and your hard job!

**Comment by SkyJedi** [comment]
![on forge](https://cdn.discordapp.com/attachments/521750321270358056/642906460845506620/093.png)

**Comment by Kaosumaru** [comment]
This situation could happen, if you would sacrifice creature that have replacement effect on destroyed (reproduced with 6 bad pennies). I think that server code would not consider this creatures to be "sacrificed", as replacement effect doesn't caused them to be destroyed. Hmm, this is perhaps not correct.

**Comment by Kaosumaru** [comment]
OK, after consulting rules "Cards that being sacrificed also count as being destroyed", "Effect can move tagged [for destruction] creature to different play zone, but creature still counts to be destroyed for purposes of all card efffects".

So, we should probably treat cards that are marked for destruction, and leaving game at any other means as still being destroyed.

**Comment by skillzontoast** [comment]
@Kaosumaru I had a similar problem. The current cost was 10 plus 6 aember. I sacrificed 11 creatures and also generated 11 aember from Soul Snatcher so I had 14 aember in total. Each sacrificed creature should have reduced the cost by one so the final cost should have been 5. It did not give me the option to forge and win the game. You can see this in the match report https://www.thecrucibletracker.com/games/bd96dc10-06d6-11ea-a3a4-7fdf1f52c38c

**Comment by lutzr437** [comment]
I had the same problem just now. I'm attaching the screen grab of the final state and the text from the game. 

I'm continually amazed at how few problems like this I see! Thanks for everything!

![game state - obsidian forge issue](https://user-images.githubusercontent.com/56323640/71752108-7216ba00-2e43-11ea-89a7-82c1b20da8fc.png)
[game text - obsidian forge issue.txt](https://github.com/keyteki/keyteki/files/4021072/game.text.-.obsidian.forge.issue.txt)

**Comment by romanogit** [comment]
![image](https://user-images.githubusercontent.com/2104075/101065443-eede7680-3573-11eb-90ca-9d4a0d4088bf.png)

![image](https://user-images.githubusercontent.com/2104075/101065487-fb62cf00-3573-11eb-8352-857afe3b9dd9.png)

![image](https://user-images.githubusercontent.com/2104075/101065540-087fbe00-3574-11eb-859a-bc0e188e850c.png)

It forged and allowed my to use Senator Shrix's amber as well. Working as expected.
