### ISSUE TITLE
Add AoA Cards - Shadows

### ISSUE THREAD

**Issue by Achocholacek** [keyteki/keyteki#8]
- [x] #287 - Hideaway Hole       
- [x] #290 - Murkens 
- [x] #305 - Lethal Distraction 

.
.
.
- [x] #270 - Gamgee                  
- [x] #279 - Throwing Stars               
- [x] #283 - Bonerot Venom
- [x] #291 - Nightforge          
- [x] #293 - Perplexing Sophistry          
- [x] #294 - Redlock   
- [x] #289 - Little Niff         
- [x] #302 - Guard Disguise      
- [x] #303 - Heist Night          
- [x] #308 - Plague Rat          
- [x] #309 - Rigged Lottery      
- [x] #312 - Sack of Coins     
- [x] #313 - Scowly Caper        
- [x] #315 - Shard of Greed

**Comment by ripred45676** [comment]
Going to try to implement knuckles bolton

**Comment by ripred45676** [comment]
Knuckles Bolton should be implemented now. Going to take a stab at more of the shadows cards

**Comment by cryogen** [comment]
Cool, just checked off a couple, double check the list before you start

**Comment by ripred45676** [comment]
Will do thanks!

**Comment by saluk** [comment]
Implemented scowly caper https://github.com/keyteki/keyteki/pull/47/files
