### ISSUE TITLE
Ragwarg deals damage before Reap Abilities

### ISSUE THREAD

**Issue by JTLSound** [keyteki/keyteki#801]
Ragwarg's damage prevents reap abilities from triggering. This should not be the case. Ragwarg uses the phrase "after a creature reaps".
![Ragwarg](https://user-images.githubusercontent.com/49758354/68538085-c79b8280-033c-11ea-938b-5a0ca9907798.jpg)

**Comment by romanogit** [comment]
It should be APC:
![image](https://user-images.githubusercontent.com/2104075/68538746-b51e4a80-0336-11ea-8fba-67df81b318c9.png)

**Comment by jeremylarner** [comment]
Fixed in #825
