### ISSUE TITLE
Navigator Ali bugs when deck is empty

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#803]
Bug: when Navigator Ali must look at cards and there are no cards left in the deck, it still prompts for a choice (between no cards) and it makes the game bug.

**Comment by SkyJedi** [comment]
![image](https://user-images.githubusercontent.com/2967416/68545153-eb3be880-038f-11ea-9797-2d5ae8328a9a.png)

**Comment by SkyJedi** [comment]
same bug will be present in 
![image](https://user-images.githubusercontent.com/2967416/68546795-20e8cd80-03a0-11ea-9509-1a6f72eac9d4.png)
