### ISSUE TITLE
Soulkeeper destroyed ability should be simultaneous with destroy after fight 

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#809]
TCO does not destroy a creature with SK at the same timewindow as after fight destruction. We can see that a creature destroyed by the fight (the attacker) left play before SK selecting a creature.

Also, in the prompt, should SK appear instead of the creature holding it?

![image](https://user-images.githubusercontent.com/2104075/68540001-b193bf00-0348-11ea-9072-d1102c63c01d.png)

**Comment by jeremylarner** [comment]
Fixed in #825

**Comment by romanogit** [comment]
Very good. Closing
