### ISSUE TITLE
(Brobnar) 1-2 Punch not working as expected

### ISSUE THREAD

**Issue by Ollybob** [keyteki/keyteki#81]
At least one instance of 1-2 punch with a board state of all brobnar (1 on one side and 2 on the other) resulted in all cards being stunned.

No other game effect existed to explain this.

Lorimir Flamefist on one side
Groggins and Little Rapscal, on the other.

**Comment by Laxie5372** [comment]
I confirm no matter the board is, when 1-2 punch is used all the creatures on the board are stunned.

Thanks
