### ISSUE TITLE
Bellowing Patrizate and Play Abilities

### ISSUE THREAD

**Issue by JTLSound** [keyteki/keyteki#812]
As both the rules for Play abilities and Bellowig use the text "after it enters play" the controlling player should be able to choose to have the Play ability.
![Bellowig](https://user-images.githubusercontent.com/49758354/68540219-0ee53b80-035c-11ea-9d97-7ef0205278a9.jpg)
 trigger.

**Comment by cryogen** [comment]
Duplicate of #420
