### ISSUE TITLE
Ward token removed only after second attack by gargantodon

### ISSUE THREAD

**Issue by Osarek** [keyteki/keyteki#814]
initial state : Crassosaurus has 10amber captured and a ward token

Main phase - Osarek
Osarek uses Gargantodon to make Gargantodon fight Crassosaurus
Osarek uses The Golden Spiral to exalt, ready and use Gargantodon
Osarek uses Gargantodon to make Gargantodon fight Crassosaurus
**hressagehorse uses Crassosaurus to remove its ward token**

the ward token should be removed on the first attack of gargantodon

Thanks for your support

[ward.txt](https://github.com/keyteki/keyteki/files/3828195/ward.txt)
![ward1](https://user-images.githubusercontent.com/57572496/68540762-740a5280-0397-11ea-8b00-fc87fa0be23a.png)

**Comment by cryogen** [comment]
Crassosaurus has elusive, so takes no damage on the first attack, so ward will not be removed.

This is not a bug

**Comment by Osarek** [comment]
ok, sorry about that...

**Comment by cryogen** [comment]
No problem! Thanks for taking the time to make a report.
