### ISSUE TITLE
Senator bracchus doesnt let me use amber from my other creatures

### ISSUE THREAD

**Issue by MaxDGS** [keyteki/keyteki#816]
had more than 6 amber with my board included but game doesnt let me forged

**Comment by SkyJedi** [comment]
![229](https://user-images.githubusercontent.com/2967416/68543712-8fb62e80-0380-11ea-9631-5e68388400e5.png)

**Comment by cryogen** [comment]
The card is wrong, but needs #518 fixing to fix properly

**Comment by Achocholacek** [comment]
518 was fixed so this should now be resolved. closing.
