### ISSUE TITLE
Wrong order to remove WARD token

### ISSUE THREAD

**Issue by MaxDGS** [keyteki/keyteki#818]
in the rules, it says that you can remove a ward only if the creature would be damaged
Yet, if i have enough armor to compensate the damage, the ward is removed anyway

**Comment by SkyJedi** [comment]
Ward gets removed before armor gets pinged

![Screenshot_20191110-060141](https://user-images.githubusercontent.com/2967416/68543654-ac059b80-037f-11ea-912b-015ff2218b9d.png)

**Comment by cryogen** [comment]
As Mr Jedi says, the new rules update specifies the order that damage happens in.  This is working correctly.

**Comment by MaxDGS** [comment]
oh okay my bad, i read the wrong thing then
