### ISSUE TITLE
odoac the patrician / stealing

### ISSUE THREAD

**Issue by Fabiuz2** [keyteki/keyteki#822]
Suppose I have Odoac the patrician (#188) in play with aember on it, and opponent tries to steal 1 of my aembers. 
Odoac correctly prevents aember from being stolen, but the opponent still receives an additional aember from the pool, which must then be removed manually.

**Comment by Fabiuz2** [comment]
[https://keyforge-card-images.s3-us-west-2.amazonaws.com/card-imgs/odoac-the-patrician.png](url)

**Comment by Kaosumaru** [comment]
Couldn't reproduce it, there is no message in game log that stealing is prevented - would be nice, if `CannotRestriction` would leave message in log

**Comment by romanogit** [comment]
Maybe the card played by the opponent did have an amber on it. So they gainged the card amber. Without the game log, it is difficult to reproduce.
