### ISSUE TITLE
Tribute not allowing to repeat

### ISSUE THREAD

**Issue by Kaosumaru** [keyteki/keyteki#829]
I think that Tribute don't allowed me to repeat effect when I failed to capture first time (opponent was at 0).

**Comment by SkyJedi** [comment]
![image](https://user-images.githubusercontent.com/2967416/68548456-c4db7480-03b2-11ea-9a4b-6a938e87402c.png)

**Comment by Kaosumaru** [comment]
Since I'm not very acquintanted with codebase, following may or may not be correct:

1. Tribute plays captureAction, and have "then" clause with exalt & capture, with same context
2. captureAction fails, "then" clause doesn't happen

I think that if we want to be 100% exact with card wording, card should
1. Most powerful creature captures 2
2. We can exalt this creature (so we should use target from previous context here) to...
3. Most powerful creature captures 2 (and theoretically, this can be different creature than creature from first point - you can capture on different creaature, if you have 2 with same power)

I will try to look into it :)

**Comment by Kaosumaru** [comment]
OK, so issue looks to me like this:
1. Player plays Tribute
2. Tribute looks for eligible targets for MostStatCardSelector & CaptureAction
3. Capture action filters targets by CanAffect - it returns false on each, since there is no amber to capture
4. so 'then' clause doesn't apply - and even if it would always apply, there is no target selected from last step


I see two potential fixes:
1. Change flow to "select most powerful friendly creature, then capture on target context, then may exalt & repeat previous effect"
2. Add something like "alwaysCanAffect" parameter to captureAction
