### ISSUE TITLE
Gargantodon wrong stealing and wrong capture

### ISSUE THREAD

**Issue by Osarek** [keyteki/keyteki#831]
initial state :
my board : Gargantodon and E’e on the Fringes 
oponent board, any creature

I discard a dis card, and i should steal 1 amber (E’e on the Fringes) and capture it on one of my creature (Gargantodon).  
instead of that, my amber is reduce by one, and it is captured by opponent creature

[log2.txt](https://github.com/keyteki/keyteki/files/3828905/log2.txt)
![garganton3](https://user-images.githubusercontent.com/57572496/68549625-9ed9c280-03fa-11ea-8ad6-1dbda1af34d7.png)

**Comment by AdamPhilpotMDX** [comment]
Sorry I don't have a picture. I had this scenario: 

I have Dexus (Dis) Paraguardian (SR), Senator Shrix (SR) (with 1 aember), Grimlocus Dux (SR) (with 2 aember) and Gargantodon (stunned) (SR) (in that order) on the battleline. Opponent has a Ronnie and 3 aember. I play Favour of Rex and target Ronnie. I was able to capture the aember and place it on Ronnie. However, this is incorrect. Also, the opponents aember did not decrease by 1.

Thanks!
