### ISSUE TITLE
Lateral Shift doesnt show opponents hand

### ISSUE THREAD

**Issue by MrAwesomePossum** [keyteki/keyteki#835]
As a result, you cant play a card from their hand either.

**Comment by romanogit** [comment]
@cryogen : I don't remember you pushing the code to reveal opponents hand

**Comment by KeyforgeJupiter** [comment]
I am having the smae problem it is not working as intended.

**Comment by romanogit** [comment]
@cryogen : i think this is related to the undefined image

Em ter, 12 de nov de 2019 4:40 PM, KeyforgeJupiter <notifications@github.com>
escreveu:
