### ISSUE TITLE
Blaster's message are printing itself as target [cosmetic]

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#838]
After moving Qincan's blaster to sly Qincan, opponent archived one of my cards. Message looked like:

`SkyJedi uses Qincan’s Blaster to archive Qincan’s Blaster`

**Comment by romanogit** [comment]
The same with other Blaster:
`Nekome uses Ingram’s Blaster to heal Ingram’s Blaster fully `

**Comment by dlocke** [comment]
Also Wall's Blaster:

`hyramgraff uses Wall's Blaster to stun Wall's Blaster`
