### ISSUE TITLE
bugs in card use ( I think)

### ISSUE THREAD

**Issue by scyco** [keyteki/keyteki#853]
Hi,
during my last game I faced this problem:
- my opponent played inky gloom that avoid me to play creatures
- in my turn I selesct Star alliance and would like to play CALV-1N as an upgrade card but I cannot.

Is it a bug or not?
thanks a lot

**Comment by romanogit** [comment]
Inky Gloom prevent opponents from reaping.
Maybe he used Lifeward?

**Comment by saluk** [comment]
Lifeward + star alliance creature-upgrades is probably a bug here. You are playing it as an upgrade INSTEAD of a creature. I think we prevent playing the card before the code changes the card into an upgrade (I did that one... oops).

**Comment by scyco** [comment]
> Inky Gloom prevent opponents from reaping.
> Maybe he used Lifeward?

yes it was Lifeward ;-)

**Comment by romanogit** [comment]
Dupe of #938 and #966
