### ISSUE TITLE
Power of Fire on a Self-Bolstering Automata causes aember loss, but shouldn't

### ISSUE THREAD

**Issue by strib** [keyteki/keyteki#858]
Opponent has [Self-Bolstering Automata](https://archonarcana.com/index.php?title=Self-Bolstering_Automata) out with a power of 13, plus a few other creatures.  Then they played [Power of Fire](https://archonarcana.com/index.php?title=Power_of_Fire), chose the Automata, and caused both players to lose up to 6 A.  But the Automata survived and increased in power.  I believe since the text of Power of Fire says "If you do", and they didn't actually sacrifice the creature since it stayed in the battleline, there should be no aember loss (but they still gain the chain).

![](https://cdn.keyforgegame.com/media/card_front/en/452_026_H6QXMJQ9V8X8_en.png)

![](https://cdn.keyforgegame.com/media/card_front/en/452_176_FG2R278749GW_en.png)

I believe the same thing should apply to wards, but I don't know if there's actually a bug with wards or if it works correctly.

Thanks for everything, WC in TCO rocks!

**Comment by Aureliaar** [comment]
I've talked it over with the italian group of fan judges, and the rule interpretation is correct as it is now.    
Since Destroyed: effects have triggered, Sacrifice costs have been paid - the *effect* of that sacrifice has then been replaced, but the costs have still been paid and the card can continue.

**Comment by romanogit** [comment]
@Aureliaar , I believe the interpretation of @strib is correct. There should not be an amber loss here

**Comment by romanogit** [comment]
There is also a caveat that the Chains should be gained even if no amber loss.
