### ISSUE TITLE
Replicator able to replicate non-reap abilities

### ISSUE THREAD

**Issue by Dicky-Boy** [keyteki/keyteki#862]
Used Replicator to reap, accidentally selected a non-reap creature (Infurnace) and was able to use it's play ability:

<img width="299" alt="Screen Shot 2019-11-11 at 16 51 09" src="https://user-images.githubusercontent.com/22052583/68607237-13b70600-04a8-11ea-83ee-ebab4b3bc96f.png">

**Comment by romanogit** [comment]
According to #894, it is also replicating fight abilities

**Comment by romanogit** [comment]
@jeremylarner : I believe you fixed this one, right?

**Comment by jeremylarner** [comment]
Fixed in #1247
