### ISSUE TITLE
Phalanx Strike Exalt issue.

### ISSUE THREAD

**Issue by CatMarrow** [keyteki/keyteki#873]
Phalanx strike seems to not be offering the prompt to exalt and repeat if I used it to remove a ward token.

**Comment by mortivas** [comment]
I think the key to reproducing this might be the ward (not sure if that was tried in https://github.com/keyteki/keyteki/issues/792).

angie_btw just reproduced this on stream: https://www.twitch.tv/videos/507277671?t=7h12m45s

Sorry I don't have access to the chat log beyond what is visible in that video.

![phalanx-strike](https://user-images.githubusercontent.com/55995924/68696733-84fbc500-054b-11ea-96c5-37c621191b01.png)

**Comment by mortivas** [comment]
Yea, the ward is definitely the key to reproducing this :)

https://gist.github.com/mortivas/64f38ced15fcec72d04e2876d154dc18
