### ISSUE TITLE
The Grim Reaper

### ISSUE THREAD

**Issue by LucaAmbrosino** [keyteki/keyteki#874]
I have this anomaly within Untamed house. Each time I reap with The Grim Reaper I obtain 1 aember without activating it's ability: no creatures are purged. Me and my opponent have to manually purge two creatures.

**Comment by Philingero** [comment]
echoing post above. played Ghosthawk beside a ready Armsmaster Molina and a ready Star Alliance Grim reaper. I got the amber but Grim reapers reap trigger did not happen.

**Comment by romanogit** [comment]
![image](https://user-images.githubusercontent.com/2104075/68742324-20715200-05ad-11ea-81a3-2fac6a4ddc9d.png)

**Comment by romanogit** [comment]
Fixed

**Comment by LucaAmbrosino** [comment]
Thanks
