### ISSUE TITLE
Quadracorder affecting me when attached to opponents creature

### ISSUE THREAD

**Issue by AdamPhilpotMDX** [keyteki/keyteki#875]
Hey guys,

I attached the Quadracorder to my opponent's valuable creature (a Saurian) and it affected my key cost and not the opponent's, as it should have.

For reference: https://clips.twitch.tv/BlightedCutePicklesSuperVinlin 

Thanks!!

**Comment by SkyJedi** [comment]
I think this can be closed. @romanogit 
![image](https://user-images.githubusercontent.com/2967416/78063149-5db85f80-7355-11ea-9a15-e3336d63f403.png)
