### ISSUE TITLE
Mimic Gel to Ronnie with Gargantodon in play

### ISSUE THREAD

**Issue by GavinForge** [keyteki/keyteki#879]
I have Gargantodon in play. I play Mimic Gel to copy my opponent's in-play Ronnie Wristlocks. I Steal 2 amber, but Gargantodon forces me to capture the 2 amber by a creature controlled by the active player (me) instead.

The glitch however in is that Curcible doesn't allow me to pick any of my own creatures to capture the amber, it forced me to capture the 2 amber on one of my opponent's creatures. It seems Mimic Gel might 'mimic' the controller aspect of Ronnie, but it shouldn't.

**Comment by romanogit** [comment]
Fixed by https://github.com/keyteki/keyteki/pull/1107
