### ISSUE TITLE
Purged cards are not accessible, so Universal Recycle Bin gets stuck

### ISSUE THREAD

**Issue by Aureliaar** [keyteki/keyteki#881]
https://i.imgur.com/tQUFrpr.jpg

Not being able to access the purged cards, attempting to use Universal Recycle Bin disallows any further player input.

> Aureon is shuffling their deck
Saxoncheung01 is shuffling their deck
Aureon is playing as the Archon: J. G. Che Apprende il Diniego della Centrale
Saxoncheung01 is playing as the Archon: 大學敘事人¶“琥魄”卡梅倫
 Aureon has connected to the game server
 Saxoncheung01 has connected to the game server
Aureon draws 6 cards up to their maximum hand size of 6
Saxoncheung01 draws 6 cards up to their maximum hand size of 6
Key phase - Aureon
Aureon does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - Aureon
Aureon chooses logos as their active house this turn
Main phase - Aureon
Aureon plays Cutthroat Research, gaining 1 Æmber
Ready phase - Aureon
Aureon readies all of their cards
Draw phase - Aureon
End of turn 1
Aureon: 1 Æmber Saxoncheung01: 0 Æmber
Turn 1
Key phase - Saxoncheung01
Saxoncheung01 does not forge a key. They have 0 amber. The current cost is 6 Æmber
House phase - Saxoncheung01
Saxoncheung01 chooses dis as their active house this turn
Main phase - Saxoncheung01
Saxoncheung01 plays Poltergeist, gaining 1 Æmber
Saxoncheung01 plays Three Fates, gaining 1 Æmber
Ready phase - Saxoncheung01
Saxoncheung01 readies all of their cards
Draw phase - Saxoncheung01
Saxoncheung01 draws 2 cards up to their maximum hand size of 6
End of turn 1
Aureon: 1 Æmber Saxoncheung01: 2 Æmber
Turn 2
Key phase - Aureon
Aureon does not forge a key. They have 1 amber. The current cost is 6 Æmber
House phase - Aureon
Aureon chooses staralliance as their active house this turn
Main phase - Aureon
Aureon plays Stealth Mode, gaining 1 Æmber
Aureon uses Stealth Mode to stop Saxoncheung01 from playing any actions on their next turn
Aureon plays Zap, gaining 1 Æmber
Aureon plays Armsmaster Molina
Ready phase - Aureon
Aureon readies all of their cards
Draw phase - Aureon
Aureon draws 3 cards up to their maximum hand size of 6
End of turn 2
Aureon: 3 Æmber Saxoncheung01: 2 Æmber
Turn 2
Key phase - Saxoncheung01
Saxoncheung01 does not forge a key. They have 2 amber. The current cost is 6 Æmber
House phase - Saxoncheung01
Saxoncheung01 chooses untamed as their active house this turn
Main phase - Saxoncheung01
Saxoncheung01 plays Musthic Murmook
Saxoncheung01 uses Musthic Murmook to deal 4 damage to Armsmaster Molina
Ready phase - Saxoncheung01
Saxoncheung01 readies all of their cards
Draw phase - Saxoncheung01
Saxoncheung01 draws 1 cards up to their maximum hand size of 6
End of turn 2
Aureon: 3 Æmber Saxoncheung01: 2 Æmber
Turn 3
Key phase - Aureon
Aureon does not forge a key. They have 3 amber. The current cost is 7 Æmber
House phase - Aureon
Aureon chooses untamed as their active house this turn
Main phase - Aureon
Aureon plays Musthic Murmook
Aureon uses Musthic Murmook to deal 4 damage to Musthic Murmook
Aureon plays Deepwood Druid
Aureon uses Deepwood Druid to heal Musthic Murmook fully
Aureon plays Fangtooth Cavern, gaining 1 Æmber
Ready phase - Aureon
Aureon readies all of their cards
Draw phase - Aureon
Aureon draws 3 cards up to their maximum hand size of 6
Aureon uses Fangtooth Cavern to destroy Deepwood Druid
End of turn 3
Aureon: 4 Æmber Saxoncheung01: 2 Æmber
Turn 3
Key phase - Saxoncheung01
Saxoncheung01 does not forge a key. They have 2 amber. The current cost is 7 Æmber
House phase - Saxoncheung01
Saxoncheung01 chooses saurian as their active house this turn
Main phase - Saxoncheung01
Saxoncheung01 plays Imperial Scutum, gaining 1 Æmber attaching it to Musthic Murmook
Saxoncheung01 plays Imperial Forge, gaining 1 Æmber
Saxoncheung01 plays City-State Interest
Ready phase - Saxoncheung01
Saxoncheung01 readies all of their cards
Draw phase - Saxoncheung01
Saxoncheung01 draws 3 cards up to their maximum hand size of 6
End of turn 3
Aureon: 4 Æmber Saxoncheung01: 4 Æmber
Turn 4
Key phase - Aureon
Aureon does not forge a key. They have 4 amber. The current cost is 7 Æmber
House phase - Aureon
Aureon chooses logos as their active house this turn
Main phase - Aureon
Aureon plays Wild Wormhole, gaining 1 Æmber
Aureon uses Wild Wormhole to play the top card of their deck : Chief Engineer Walls
Aureon plays Chief Engineer Walls
Aureon plays Dr. Milli
Aureon plays Remote Access, gaining 1 Æmber
Ready phase - Aureon
Aureon readies all of their cards
Draw phase - Aureon
Aureon draws 3 cards up to their maximum hand size of 6
Aureon uses Fangtooth Cavern to destroy Dr. Milli
End of turn 4
Aureon: 6 Æmber Saxoncheung01: 4 Æmber
Turn 4
Key phase - Saxoncheung01
Saxoncheung01 does not forge a key. They have 4 amber. The current cost is 7 Æmber
House phase - Saxoncheung01
Saxoncheung01 chooses untamed as their active house this turn
Main phase - Saxoncheung01
Saxoncheung01 plays Unsuspecting Prey
Saxoncheung01 uses Unsuspecting Prey to deal 2 damage to Chief Engineer Walls and Musthic Murmook
Saxoncheung01 plays Regrowth, gaining 1 Æmber
Saxoncheung01 uses Regrowth to return Musthic Murmook to their hand
Saxoncheung01 plays Musthic Murmook
Saxoncheung01 uses Musthic Murmook to deal 4 damage to Musthic Murmook
Saxoncheung01 plays Song of the Wild
Saxoncheung01 uses Song of the Wild to give each friendly creature 'Reap: Gain 1 amber' for the remainder of the turn
Ready phase - Saxoncheung01
Saxoncheung01 readies all of their cards
Draw phase - Saxoncheung01
Saxoncheung01 draws 3 cards up to their maximum hand size of 6
End of turn 4
Aureon: 6 Æmber Saxoncheung01: 5 Æmber
Turn 5
Key phase - Aureon
Aureon does not forge a key. They have 6 amber. The current cost is 7 Æmber
House phase - Aureon
Aureon chooses staralliance as their active house this turn
Main phase - Aureon
Aureon plays Operations Officer Yshi
Aureon plays Stealth Mode, gaining 1 Æmber
Aureon uses Stealth Mode to stop Saxoncheung01 from playing any actions on their next turn
Aureon plays Universal Translator, gaining 1 Æmber attaching it to Operations Officer Yshi
Aureon discards Helmsman Spears
Ready phase - Aureon
Aureon readies all of their cards
Draw phase - Aureon
Aureon draws 4 cards up to their maximum hand size of 6
Aureon uses Fangtooth Cavern to destroy Musthic Murmook
 Aureon declares Check!
End of turn 5
Aureon: 8 Æmber Saxoncheung01: 5 Æmber
Turn 5
Key phase - Saxoncheung01
Saxoncheung01 does not forge a key. They have 5 amber. The current cost is 6 Æmber
House phase - Saxoncheung01
Saxoncheung01 chooses dis as their active house this turn
Main phase - Saxoncheung01
Saxoncheung01 plays Soulkeeper, gaining 1 Æmber attaching it to Operations Officer Yshi
Saxoncheung01 plays Infurnace
Saxoncheung01 uses Infurnace to purge Stealth Mode and Stealth Mode
Saxoncheung01 plays Infurnace
Saxoncheung01 uses Infurnace to purge Wild Wormhole and Zap
Ready phase - Saxoncheung01
Saxoncheung01 readies all of their cards
Draw phase - Saxoncheung01
Saxoncheung01 draws 3 cards up to their maximum hand size of 6
 Saxoncheung01 declares Check!
End of turn 5
Aureon: 4 Æmber Saxoncheung01: 6 Æmber
Turn 6
Key phase - Aureon
Aureon does not forge a key. They have 4 amber. The current cost is 6 Æmber
House phase - Aureon
Aureon chooses untamed as their active house this turn
Main phase - Aureon
Aureon plays Teliga
Aureon plays The Fittest, gaining 1 Æmber
Aureon uses The Fittest to place 1 +1 power counter on Teliga and Operations Officer Yshi
Aureon plays Low Dawn, gaining 1 Æmber
Aureon uses Low Dawn to return Musthic Murmook and Deepwood Druid to their deck
Aureon is shuffling their deck
Ready phase - Aureon
Aureon readies all of their cards
Draw phase - Aureon
Aureon draws 3 cards up to their maximum hand size of 6
Aureon uses Fangtooth Cavern to destroy Infurnace
 Aureon declares Check!
End of turn 6
Aureon: 6 Æmber Saxoncheung01: 6 Æmber
Turn 6
Key phase - Saxoncheung01
Saxoncheung01 forges the red key , paying 6 Æmber
House phase - Saxoncheung01
Saxoncheung01 chooses dis as their active house this turn
Main phase - Saxoncheung01
Saxoncheung01 uses Infurnace to reap with Infurnace
Saxoncheung01 plays Harbinger of Doom
Aureon uses Teliga to gain 1 Æmber
Saxoncheung01 plays Not Finished with You, gaining 1 Æmber
Saxoncheung01 uses Not Finished with You to return Infurnace to their deck
Saxoncheung01 is shuffling their deck
Saxoncheung01 discards Borr Nit
Ready phase - Saxoncheung01
Saxoncheung01 readies all of their cards
Draw phase - Saxoncheung01
Saxoncheung01 draws 3 cards up to their maximum hand size of 6
End of turn 6
Aureon: 7 Æmber Saxoncheung01: 2 Æmber
Turn 7
Key phase - Aureon
Aureon forges the red key , paying 6 Æmber
House phase - Aureon
Aureon chooses logos as their active house this turn
Main phase - Aureon
Aureon
laggy as fuck, sorry
Aureon plays Eyegor
Aureon uses Eyegor to to look at the top 3 cards of their deck
Aureon adds a card to their hand and discards the other 2
Aureon plays Eyegor
Aureon uses Eyegor to to look at the top 3 cards of their deck
Aureon adds a card to their hand and discards the other 2
Aureon plays Tautau Vapors
Aureon uses Tautau Vapors to draw 2 cards
Aureon plays Twin Bolt Emission, gaining 1 Æmber
Aureon uses Twin Bolt Emission to deal 2 damage to Harbinger of Doom and Infurnace
Aureon plays Information Exchange
Aureon uses Information Exchange to steal 1 Æmber from Saxoncheung01
Aureon plays Universal Recycle Bin, gaining 1 Æmber
Aureon plays Groupthink Tank
Aureon plays Thorium Plasmate, gaining 1 Æmber
Aureon uses Thorium Plasmate to move Infurnace on Saxoncheung01's battleline and deal 2 damage to it for each neighbor that shares a house with it
Ready phase - Aureon
Aureon readies all of their cards
Draw phase - Aureon
Aureon draws 5 cards up to their maximum hand size of 6
Aureon uses Fangtooth Cavern to destroy Eyegor
End of turn 7
Aureon: 5 Æmber Saxoncheung01: 1 Æmber
Turn 7
Key phase - Saxoncheung01
Saxoncheung01 does not forge a key. They have 1 amber. The current cost is 6 Æmber
House phase - Saxoncheung01
Saxoncheung01 chooses dis as their active house this turn
Main phase - Saxoncheung01
Saxoncheung01 uses Harbinger of Doom to make Harbinger of Doom fight Operations Officer Yshi
Saxoncheung01 uses Harbinger of Doom to destroy Groupthink Tank, Eyegor, Teliga, and Operations Officer Yshi
Ready phase - Saxoncheung01
Saxoncheung01 readies all of their cards
Draw phase - Saxoncheung01
End of turn 7
Aureon: 5 Æmber Saxoncheung01: 1 Æmber
Turn 8
Key phase - Aureon
Aureon does not forge a key. They have 5 amber. The current cost is 6 Æmber
House phase - Aureon
Aureon chooses staralliance as their active house this turn
Main phase - Aureon
Aureon plays Chief Engineer Walls
Aureon uses Chief Engineer Walls to return Universal Translator to their hand
Aureon plays Com. Officer Kirby
Aureon uses Com. Officer Kirby to allow them to play one non-star alliance artifact, upgrade, or action​ card this turn
Aureon plays The Fittest, gaining 1 Æmber
Aureon uses The Fittest to place 1 +1 power counter on Chief Engineer Walls and Com. Officer Kirby
Aureon plays Universal Translator, gaining 1 Æmber attaching it to Com. Officer Kirby
Ready phase - Aureon
Aureon readies all of their cards
Draw phase - Aureon
Aureon draws 3 cards up to their maximum hand size of 6
Aureon's deck has run out of cards, so they shuffle
Aureon is shuffling their deck
Aureon uses Fangtooth Cavern to destroy Chief Engineer Walls
 Aureon declares Check!
End of turn 8
Aureon: 7 Æmber Saxoncheung01: 1 Æmber
Turn 8
Key phase - Saxoncheung01
Saxoncheung01 does not forge a key. They have 1 amber. The current cost is 6 Æmber
House phase - Saxoncheung01
Saxoncheung01 chooses saurian as their active house this turn
Main phase - Saxoncheung01
Saxoncheung01 plays Brutodon Auxiliary
Saxoncheung01 plays Philophosaurus
Saxoncheung01 plays Philophosaurus
Saxoncheung01 plays Tribune Pompitus
Ready phase - Saxoncheung01
Saxoncheung01 readies all of their cards
Draw phase - Saxoncheung01
Saxoncheung01 draws 4 cards up to their maximum hand size of 6
End of turn 8
Aureon: 7 Æmber Saxoncheung01: 1 Æmber
Turn 9
Key phase - Aureon
Aureon forges the blue key , paying 6 Æmber
House phase - Aureon
Aureon chooses untamed as their active house this turn
Aureon moves all the cards in their archives to their hand
Main phase - Aureon
Aureon plays Perilous Wild, gaining 1 Æmber
Aureon uses Mimicry to to copy Three Fates
Aureon plays Mimicry, gaining 1 Æmber
Aureon uses Mimicry to destroy Philophosaurus, Brutodon Auxiliary, and Philophosaurus
Aureon plays Gebuk
Aureon plays Tantadlin
Aureon plays Musthic Murmook
Aureon uses Musthic Murmook to deal 4 damage to Tribune Pompitus
Ready phase - Aureon
Aureon readies all of their cards
Draw phase - Aureon
Aureon draws 4 cards up to their maximum hand size of 6
Aureon uses Fangtooth Cavern to destroy Tribune Pompitus
End of turn 9
Aureon: 3 Æmber Saxoncheung01: 1 Æmber
Turn 9
Key phase - Saxoncheung01
Saxoncheung01 does not forge a key. They have 1 amber. The current cost is 7 Æmber
House phase - Saxoncheung01
Saxoncheung01 chooses saurian as their active house this turn
Main phase - Saxoncheung01
Saxoncheung01 plays Praefectus Ludo
Saxoncheung01 plays Axiom of Grisk
Saxoncheung01 uses Axiom of Grisk to ward Praefectus Ludo; destroy Musthic Murmook, Tantadlin, Gebuk, Com. Officer Kirby, and Praefectus Ludo; and increase their chains by 2
Aureon uses Gebuk to discard Cutthroat Research
Saxoncheung01 uses Praefectus Ludo to remove its ward token
Saxoncheung01 plays Rhetor Gallim
Saxoncheung01 uses Rhetor Gallim to increase Aureon's key cost by 3 until the end of their next turn
Ready phase - Saxoncheung01
Saxoncheung01 readies all of their cards
Draw phase - Saxoncheung01
Saxoncheung01 draws 2 cards up to their maximum hand size of 6
Saxoncheung01's chains are reduced by 1 to 1
End of turn 9
Aureon: 3 Æmber Saxoncheung01: 1 Æmber
Turn 10
Key phase - Aureon
Aureon does not forge a key. They have 3 amber. The current cost is 9 Æmber
House phase - Aureon
Aureon chooses untamed as their active house this turn
Main phase - Aureon
Aureon plays Teliga
Aureon plays Regrowth, gaining 1 Æmber
Aureon uses Regrowth to return Gebuk to their hand
Aureon plays Gebuk
Ready phase - Aureon
Aureon readies all of their cards
Draw phase - Aureon
Aureon draws 2 cards up to their maximum hand size of 6
Aureon uses Fangtooth Cavern to destroy Rhetor Gallim
End of turn 10
Aureon: 4 Æmber Saxoncheung01: 1 Æmber
Turn 10
Key phase - Saxoncheung01
Saxoncheung01 does not forge a key. They have 1 amber. The current cost is 6 Æmber
House phase - Saxoncheung01
Saxoncheung01 chooses untamed as their active house this turn
Main phase - Saxoncheung01
Saxoncheung01 plays Nature’s Call, gaining 1 Æmber
Saxoncheung01 uses Nature’s Call to return Gebuk and Teliga to their hand
Saxoncheung01 plays Panpaca, Anga
Saxoncheung01 plays Molephin
Ready phase - Saxoncheung01
Saxoncheung01 readies all of their cards
Draw phase - Saxoncheung01
Saxoncheung01 draws 3 cards up to their maximum hand size of 6
Saxoncheung01's chains are reduced by 1 to 0
End of turn 10
Aureon: 4 Æmber Saxoncheung01: 2 Æmber
Turn 11
Key phase - Aureon
Aureon does not forge a key. They have 4 amber. The current cost is 6 Æmber
House phase - Aureon
Aureon chooses logos as their active house this turn
Main phase - Aureon
Aureon plays Dr. Milli
Aureon uses Dr. Milli to archive 3 cards
 Aureon is attempting to switch manual mode on
 Saxoncheung01 disallows enabling manual mode
Aureon
not implemented yet apparently
Aureon
need to manually do that

**Comment by romanogit** [comment]
Fixed by #892
