### ISSUE TITLE
Obsidian Forge Logic Wrong

### ISSUE THREAD

**Issue by ValpoCarnie** [keyteki/keyteki#883]
Obsidian Forge is being destroyed on use when it should only be destroyed if a key is successfully forged.

**Comment by stebsteb** [comment]
In a recent game my opponent had Nefru which meant that I was able to sacrifice my creatures to gain 1 aember. On turn 13 I had 2 aember and 5 creatures. I used Obsidian forge to sacrifice all 5 and then selected yes to forge a key. The result was that Obsidian Forge was sacrificed and then I gained 5 aember (up to 7) but I didn't forge a key. I should have been able to forge at cost 7.

https://www.thecrucibletracker.com/games/918babc0-0bd9-11ea-a3ea-d3428020ef3a

**Comment by DaveCordeiro** [comment]
When being used via remote access it does not forge a key or sacrifice. I forgot to grab logs but it is here in the crucible tracker https://www.thecrucibletracker.com/games/bea888c0-16b1-11ea-bf0f-17d500721408

**Comment by romanogit** [comment]
Remote Access an opponent OF and Chose 2 creatures

![image](https://user-images.githubusercontent.com/2104075/101065858-6e6c4580-3574-11eb-9cc6-8c64af3199ad.png)

Prompts to forge:

![image](https://user-images.githubusercontent.com/2104075/101065914-8217ac00-3574-11eb-9142-c5448de4363f.png)

Forged (including amber from Senator Shrix):

![image](https://user-images.githubusercontent.com/2104075/101065964-9065c800-3574-11eb-80fc-946860303721.png)

It is working as expected
