### ISSUE TITLE
Gleeful Mayhem removes ward and damages

### ISSUE THREAD

**Issue by muircurial** [keyteki/keyteki#884]
Gleeful Mayhem removed the ward from a Legatus Raptor I had in play and did 5 damage, 1 blocked by the shield. I don't currently have a screenshot, but will look to see if I can grab one the next time it occurs.

**Comment by mortivas** [comment]
I was able to reproduce this, except in my case it didn't even remove the ward, just directly applied damage.

https://gist.github.com/mortivas/bd9f5fc402640838cf3e5f600c8c1b9b

![gm](https://user-images.githubusercontent.com/55995924/68711258-4aa02100-0567-11ea-9ace-9552398ce581.PNG)

![gleeful-mayhem](https://user-images.githubusercontent.com/55995924/68711296-5855a680-0567-11ea-8019-fd61d56d39fd.png)

**Comment by OsramTaleka** [comment]
This also happened to me just now but it removed the ward and then just killed the creature, the creature was undamaged and 6 power. It had been attacked and had elusive though.

**Comment by romanogit** [comment]
Hello guys,
we are aware of the issue and trying to work on a fix.
