### ISSUE TITLE
CXO Taber not allowing non-Star Alliance cards to be played/used

### ISSUE THREAD

**Issue by muircurial** [keyteki/keyteki#886]
CXO Taber not allowing non-Star Alliance cards to be played/used. As the screenshot indicates, I've reaped with Taber, but cannot use the Saurian on the battle line or play non-Star Alliance cards from my hand (with the exception of Mack the Knife).

![image](https://user-images.githubusercontent.com/7585185/68692801-16673900-0544-11ea-92ac-a21d18763570.png)

**Comment by cryogen** [comment]
This was fixed yesterday but not deployed properly.  Should be properly fixed and deployed now

**Comment by muircurial** [comment]
Just now had it happen again. I'll get a screenshot if it happens again and upload.
