### ISSUE TITLE
Kymoor Eclipse Does Not Shuffle

### ISSUE THREAD

**Issue by BOBONA** [keyteki/keyteki#887]
Kymoor eclipse doesn't shuffle your deck. This is not an issue with the shuffling algorithm or whatever. It just places the cards on top instead of shuffling.

**Comment by romanogit** [comment]
It is a known bug:
https://github.com/keyteki/keyteki/issues/805

It is already fixed, but pending review and deploy.

**Comment by ju4np4** [comment]
I have seen this now, thanks.
