### ISSUE TITLE
Senator Bracchus : Inconsistent Prompt

### ISSUE THREAD

**Issue by SadCryBear** [keyteki/keyteki#889]
With Senator Bracchus in play I saw two different things happen:

Game 1: No prompt to forge key with 5 amber on Gigantodon, 6 in pool, key cost at 7
Game 2: Prompt to use Amber on Senator Brachhus and other Dinosaur, no prompt to use Amber on Gigantodon (12+ total amber)

I didn't get screenshots but crucible game tracker reports are here:
Gme 1: Turn 7 relevant (I tried to fix in manual so log is weird: https://www.thecrucibletracker.com/games/2c04ae10-059d-11ea-bf5b-c9306381255f
Game 2: Turn 7 relevant : https://www.thecrucibletracker.com/games/9f401f20-059f-11ea-bf5b-c9306381255f

**Comment by SadCryBear** [comment]
Also, you guys are awesome. Thank you.

**Comment by romanogit** [comment]
I was not able to reproduce this issue
