### ISSUE TITLE
Gargantugaun 

### ISSUE THREAD

**Issue by KeyforgeJupiter** [keyteki/keyteki#890]
IT is leaving amber on my opponent's creatures, and not taking it from the player pool when a steal effect is going off. Looks like it is coming from the common pool.

**Comment by Osarek** [comment]
duplicate  with #831

**Comment by Osarek** [comment]
duplicate with #831 ?

**Comment by romanogit** [comment]
Duplicate of #831. It is a capture problem at the moment.
