### ISSUE TITLE
Gebuk putting artifact into play

### ISSUE THREAD

**Issue by Greymarch2000** [keyteki/keyteki#893]
Gebuk has a **Destroyed** effect of: _Discard the top card of your deck. If it is a creature, after Gebuk leaves play, put that creature into play in Gebuk’s position in the battleline._

Just played a game where I destroyed my opponents Gebuk and it discarded a _The Quiet Anvil_ artifact from the top of his deck and put it into play, even though it is not a creature. The chat pane only says it discarded it but it was put into play, you can see later at the beginning of his turn it let him forge and was then discarded as it normally works.

![2019-11-13](https://user-images.githubusercontent.com/57699055/68736561-f28d0d00-05ae-11ea-8c59-ae129a174ce2.png)

(I didn't take a screenshot while it was up, but got one after the game was done.)

**Comment by romanogit** [comment]
Just pushed a PR to fix it:
https://github.com/keyteki/keyteki/pull/895
