### ISSUE TITLE
When forging third key with colloseum game doesn't end

### ISSUE THREAD

**Issue by Dunkoro** [keyteki/keyteki#910]
https://prnt.sc/pwram3

Happened while I had enough aember in my pool and also some on Senator(s).

**Comment by stebsteb** [comment]
Common factor in these two cases is that there was aember on  a card that could have been used to forge but wasn't needed as there was enough in the pool (Senator in the first case, Safe Place in the other)

**Comment by cryogen** [comment]
Fixed by #1048
