### ISSUE TITLE
[WC] Imperial Road - should only play cards from hand

### ISSUE THREAD

**Issue by iisfet** [keyteki/keyteki#913]
Hello,

When you use imperial road (saurian) we should only be able to play a saurian creature from hand

But for now, we can play a card from discard or even from the board. 

Hope you can fix it :) 

Thanks

**Comment by iisfet** [comment]
Edit : we can play a Saurian Creature from discard or from the board

**Comment by Achocholacek** [comment]
I have updated the test for Imperial road but cannot recreate this issue. If it reoccurs please let us know.
