### ISSUE TITLE
Senator Bracchus not working

### ISSUE THREAD

**Issue by oxysmartass** [keyteki/keyteki#918]
Senator Bracchus is supposed to allow me to use amber on friendly creatures as if it were part of my pool.  When I used imperial Forge during my turn I should have had anough aember to forge a key but instead all it did was give me the 1 aember it comes with.  Below is text log, unfortunately I did not get a screenshot (was trying to figure out what happened when my opponent wiped my board along with all my aember on my creatures that should have been used to forge a key).

eba is shuffling their deck
oxysmartass is shuffling their deck
seba is playing as the Archon: Banning, Cliff Patron
oxysmartass is playing as the Archon: Mark, Library Spelunker
 seba has connected to the game server
 oxysmartass has connected to the game server
seba draws 6 cards  up to their maximum hand size of 6
oxysmartass draws 6 cards  up to their maximum hand size of 6
Key phase - seba
seba does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - seba
seba chooses dis  as their active house this turn
Main phase - seba
seba plays Key to Dis
Ready phase - seba
seba readies all of their cards 
Draw phase - seba
End of turn 1
seba: 0 Æmber  oxysmartass: 0 Æmber 
Turn 1
Key phase - oxysmartass
oxysmartass does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - oxysmartass
oxysmartass chooses logos  as their active house this turn
Main phase - oxysmartass
oxysmartass plays C.Æ.N.D.L.E. Unit
oxysmartass plays Wild Wormhole, gaining 1 Æmber 
oxysmartass uses Wild Wormhole to play the top card  of their deck : Psionic Officer Lang
oxysmartass plays Psionic Officer Lang
Ready phase - oxysmartass
oxysmartass readies all of their cards 
Draw phase - oxysmartass
oxysmartass draws 2 cards  up to their maximum hand size of 6
End of turn 1
seba: 0 Æmber  oxysmartass: 1 Æmber 
Turn 2
Key phase - seba
seba does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - seba
seba chooses brobnar  as their active house this turn
Main phase - seba
seba plays Blood Money
seba uses Blood Money to place 2 Æmber  on Psionic Officer Lang
seba uses Key to Dis to sacrifice Key to Dis
seba plays Cowfyne
Ready phase - seba
seba readies all of their cards 
Draw phase - seba
seba draws 2 cards  up to their maximum hand size of 6
End of turn 2
seba: 2 Æmber  oxysmartass: 1 Æmber 
Turn 2
Key phase - oxysmartass
oxysmartass does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - oxysmartass
oxysmartass chooses saurian  as their active house this turn
Main phase - oxysmartass
oxysmartass plays Centurion Stenopius
oxysmartass uses Centurion Stenopius to exalt Centurion Stenopius
oxysmartass plays Tribune Pompitus
oxysmartass plays Senator Bracchus
oxysmartass plays Good of the Many
oxysmartass uses Good of the Many to destroy Cowfyne
Ready phase - oxysmartass
oxysmartass readies all of their cards 
Draw phase - oxysmartass
oxysmartass draws 4 cards  up to their maximum hand size of 6
End of turn 2
seba: 2 Æmber  oxysmartass: 1 Æmber 
Turn 3
Key phase - seba
seba does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - seba
seba chooses dis  as their active house this turn
Main phase - seba
seba plays Angwish
seba plays Gub
seba plays Exhume, gaining 1 Æmber 
seba uses Exhume to play Cowfyne
seba plays Cowfyne
Ready phase - seba
seba readies all of their cards 
Draw phase - seba
seba draws 3 cards  up to their maximum hand size of 6
End of turn 3
seba: 3 Æmber  oxysmartass: 1 Æmber 
Turn 3
Key phase - oxysmartass
oxysmartass does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - oxysmartass
oxysmartass chooses saurian  as their active house this turn
Main phase - oxysmartass
oxysmartass uses Centurion Stenopius to reap with Centurion Stenopius
oxysmartass uses Centurion Stenopius to exalt Centurion Stenopius
oxysmartass uses Senator Bracchus to reap with Senator Bracchus
oxysmartass uses Senator Bracchus to exalt Senator Bracchus
oxysmartass uses Tribune Pompitus to make Tribune Pompitus fight Gub
oxysmartass uses Tribune Pompitus to exalt Tribune Pompitus
oxysmartass plays Library of Polliasaurus
oxysmartass plays Phalanx Strike, gaining 1 Æmber 
oxysmartass uses Phalanx Strike to deal 3 damage to Cowfyne
oxysmartass exalts Centurion Stenopius to repeat Phalanx Strike's effect
oxysmartass uses Phalanx Strike to deal 3 damage to Cowfyne
oxysmartass plays Imperial Forge, gaining 1 Æmber 
Ready phase - oxysmartass
oxysmartass readies all of their cards 
Draw phase - oxysmartass
oxysmartass draws 3 cards  up to their maximum hand size of 6
 oxysmartass declares Check!
End of turn 3
seba: 3 Æmber  oxysmartass: 5 Æmber 
Turn 4
Key phase - seba
seba does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - seba
seba chooses dis  as their active house this turn
Main phase - seba
seba plays Three Fates, gaining 1 Æmber 
seba uses Three Fates to destroy Centurion Stenopius, Tribune Pompitus, and Senator Bracchus
seba uses Angwish to reap with Angwish
Ready phase - seba
seba readies all of their cards 
Draw phase - seba
seba draws 1 cards  up to their maximum hand size of 6
 seba declares Check!
End of turn 4
seba: 10 Æmber  oxysmartass: 5 Æmber 
Turn 4
Key phase - oxysmartass
oxysmartass does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - oxysmartass
 oxysmartass concedes
 seba has won the game

**Comment by cryogen** [comment]
Fixed by #917
