### ISSUE TITLE
Rothais the Fierce incorrect damage

### ISSUE THREAD

**Issue by OzOhM** [keyteki/keyteki#92]
Flaxia, undamaged, with a +1 power counter on it, fought undamaged Rothais the Fierce, and resulted in Flaxia not dying, with 4 damage counters on it.

**Comment by Achocholacek** [comment]
In this instance, Flaxia would be a 5 power creature (4 base, +1 Power Counter), therefore she needs >= 5 damage on her before she would die.

**Comment by Achocholacek** [comment]
Rothais is Hazardous +4 so she should have ultimately died. Will investigate.

**Comment by Achocholacek** [comment]
@cryogen - is this due to incorrect json data? aka #83? I can recreate this but I'm wondering if it is just because card data isnt up to date...

**Comment by cryogen** [comment]
It may have been a missing keyword, I'll close this but please reopen it if it's still an issue
