### ISSUE TITLE
Harbinger of Doom/Hecatomb bug

### ISSUE THREAD

**Issue by faultymonkey** [keyteki/keyteki#925]
Had something come up on TCO last night- I had Harbinger out amongst my Dis creatures, and played Hecatomb. I expected my 3 amber, but I also destroyed my opponents 3 Brobnar. I received all 6 amber.

**Comment by Achocholacek** [comment]
I have written the test spec for Hecatomb, and included a case to specifically reference this scenario and I cannot recreate it. Closing this for now but if you see something like this happen again please re-open a ticket with additional info so we can get to the bottom of it!
