### ISSUE TITLE
Axiom of Grisk

### ISSUE THREAD

**Issue by collectorofdata** [keyteki/keyteki#926]
![report](https://user-images.githubusercontent.com/57809566/68964005-3bdd9680-0813-11ea-8cda-533118a889af.JPG)
Shoulnt creatrures with aember survive?

**Comment by muircurial** [comment]
Think it was the combination of Axiom and Harbinger dying.

**Comment by collectorofdata** [comment]
> Think it was the combination of Axiom and Harbinger dying.

but it is warded so it would not be destroyed right?

**Comment by muircurial** [comment]
Ooooh I see now. So the Harbinger lived. Yeah, interesting.

**Comment by Aureliaar** [comment]
Two harbringers of doom, maybe?
Please provide full chat logs and screens

**Comment by cryogen** [comment]
Fixed by #953
