### ISSUE TITLE
Tribune Pompitus & Aemberspine Mongrel interaction

### ISSUE THREAD

**Issue by muircurial** [keyteki/keyteki#927]
- Fought Tribune into Mongrel (both undamaged before fight).
- Exalted Tribune, making Tribune a 6 with 2 shield.
- Hazard damage from Mongrel applied, leaving Tribune at 5 with 0 shield.
- Fight damage applied. Mongrel dies taking 6 damage. Tribune dies taking 3. Should still have 2 power left.

![image](https://user-images.githubusercontent.com/7585185/68965495-ede07880-07a9-11ea-8c9b-1548cf9d9371.png)

**Comment by Aureliaar** [comment]
Are you sure the Mongrel didn't have two +1 strength tokens?
The chat log shows it getting one, and i've seen Tribune Pompitus working correctly all around

**Comment by muircurial** [comment]
You know what, you're right! Reported this days later and forgot. Thanks! Closing this.
