### ISSUE TITLE
(Sanctum) Maruck the Marked - too much AEmber captured

### ISSUE THREAD

**Issue by MoonWalker0** [keyteki/keyteki#93]
While attacked, Maruck the Marked captures more AEmber than armor it currently has.

**Comment by cryogen** [comment]
I can't reproduce this.  Do you have an example board state where this occurs?

**Comment by skrohmagnon** [comment]
he has 1 armor. Last game, he attacks a 2 power creature and captures 2 aembers. Should be one.

**Comment by cryogen** [comment]
![image](https://user-images.githubusercontent.com/1053365/62006564-0b75cd80-b13a-11e9-976e-6ef695bfab8d.png)

This isn't the case when I test it, is there some other effect coming into play?

Can you get a screenshot of the board state when it occurs?

**Comment by MoonWalker0** [comment]
![bug](https://user-images.githubusercontent.com/32847809/62006776-927c7300-b145-11e9-9391-02e601dc8253.png)

**Comment by cryogen** [comment]
Found it!

Thanks, the screenshot helped, it looks like it's the second time it fights it's triggering incorrectly.
