### ISSUE TITLE
Odoac the Patrician/Too Much to Protect

### ISSUE THREAD

**Issue by Invizigoth** [keyteki/keyteki#936]
I had 1 amber on Odoac and 14 in my pool and my opponent played Too Much to Protect to steal my amber over 6. He did not steal but he got 8 amber anyway and I still got 14 amber left.
My opponent shouldn`t get any amber at all is my opinion! Or am I wrong? If not there is a bug for someone to fix.
Best regards Thomas

**Comment by Achocholacek** [comment]
I have updated both test specs for these cards and I cannot reproduce the issue. If this reoccurs please open a new ticket with as much additional info as you can provide!
