### ISSUE TITLE
The Callipygian Ideal lets you spend aember from any friendly creature

### ISSUE THREAD

**Issue by imaji** [keyteki/keyteki#937]
‘Play: Exalt this creature.

This creature gains, “you may spend aember on this creature as if it were in your pool.”’

But it lets you spend it off of ANY friendly creature with aember on.

**Comment by DaveCordeiro** [comment]
It also lets you spend aember from your artifacts too 
![image](https://user-images.githubusercontent.com/57851149/69002248-f2438900-08b0-11ea-95c2-2f2335e9663d.png)

**Comment by benjamintownsend** [comment]
I too had this problem

**Comment by Philingero** [comment]
echoing the sentiments above. i wasnt able to get screenshots but it prompted me to use amber from other creatures.

**Comment by cryogen** [comment]
This issue is fixed but not yet deployed. Thanks for your reports!

**Comment by cryogen** [comment]
Fixed by #949 (now deployed)
