### ISSUE TITLE
Explo-Rover can't be used as an upgrade

### ISSUE THREAD

**Issue by Hartmanator** [keyteki/keyteki#938]
When trying playing Explo-Rover, it doesn't let you play as an upgrade.

**Comment by mnapoleon** [comment]
I was able to click on the Explo-Rover card and 'Play as an Upgrade' was an option in the prompt box.  After selecting that it allowed to me to select a creature as a target for the upgrade.
If doesn't allow you to just drag the upgrade onto the creature but I'm not sure the UI allows that anyway.  Doesn't appear to be an issue.
![2019-11-18](https://user-images.githubusercontent.com/152280/69108152-cdcae680-0a41-11ea-8bfe-758999adf1d7.png)

**Comment by romanogit** [comment]
Probably he had some card preventing him from playing creatures such as Lifeward. We have a similar #853

**Comment by romanogit** [comment]
This seems to be a medium complexity fix, but when I thought about interactions with other play cards such as Wild Wormhole or Murkens, it can become tricky.

**Comment by romanogit** [comment]
We need more details to fix this one. Please, reopen if the problem repeats.
