### ISSUE TITLE
Thorium plasmate does not consistently relocate creatures to where they are selected to move

### ISSUE THREAD

**Issue by DaveCordeiro** [keyteki/keyteki#939]
I don't have screenshots or game logs, but there really isn't anything you could gain from them since there is no indication in the logs of where I clicked to move a creature.That said this occurs in nearly every single game I play with my double plasmate deck so it shouldn't be super hard to reproduce (I'll come back with screenshots when I get a chance). Essentially instead of moving the creature to the right of the creature selected or left of creature selected it moves the creature several spaces further to the selected direction. This happens roughly 70% of the time. I cannot fix this in manual mode either because I cannot figure out how to move creatures in manual mode. All other battleline reordering cards seem to work as intended. 
EDIT: I did more testing and it "further in that direction" seems to not be the case, it just randomly moves things around

**Comment by Rodigee** [comment]
I've experience this bug as well and I have a theory of what's causing it: 
Could it be that prompt of whether the targeted creature should be moved to the left or right of another battleline creature be referring to left/right from the opponent's perspective? If so, the prompt should make this clear or the code should be changed to be from the prospective of the player playing the card.

**Comment by DaveCordeiro** [comment]
I chose left of the creature that is now on the center 
![image](https://user-images.githubusercontent.com/57851149/69021811-b7a82200-097e-11ea-981d-d155355a4919.png)

**Comment by DaveCordeiro** [comment]
This issue is still occurring and there is no good workaround for situations where you don't kill the creature since you can't relocate creatures in manual mode, which is very relevant in worlds collide.
