### ISSUE TITLE
(Logos) Jargogle AoA131 is not implemented

### ISSUE THREAD

**Issue by Gimu87** [keyteki/keyteki#94]
The text of Jargogle is not implemented:
Play: put a card from your hand facedown under Jargogle
Destroyed: if it is your turn play the card under Jargogle, otherwise, archive that card

**Comment by cryogen** [comment]
Huh.  I could have sworn someone did this card, but it is indeed missing.  Thanks for reporting

**Comment by cryogen** [comment]
Fixed in  feb99af
