### ISSUE TITLE
Warded creature died before fight fighting a hazardous creature

### ISSUE THREAD

**Issue by imaji** [keyteki/keyteki#941]
I had a warded Thero Centurian with 5 damage on and 1 shield attack a Lieutenant Khrkar. The Lieutenant survived, the warded creature died. Both should of died.

The ward should of absorbed the hazardous, then the creatures should of fought and both died.

Chat log:

imaji is shuffling their deck
Samurai_riky is shuffling their deck
imaji is playing as the Archon: Sintusk, the Queen of Resistance
Samurai_riky is playing as the Archon: “Chimera”, Mozzo di Lagobanale
 Samurai_riky has connected to the game server
 imaji has connected to the game server
imaji draws 6 cards  up to their maximum hand size of 6
Samurai_riky draws 6 cards  up to their maximum hand size of 6
Key phase - Samurai_riky
Samurai_riky does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Samurai_riky
Samurai_riky chooses dis  as their active house this turn
Main phase - Samurai_riky
Samurai_riky plays Snag
Ready phase - Samurai_riky
Samurai_riky readies all of their cards 
Draw phase - Samurai_riky
End of turn 1
imaji: 0 Æmber  Samurai_riky: 0 Æmber 
Turn 1
Key phase - imaji
imaji does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - imaji
imaji chooses saurian  as their active house this turn
Main phase - imaji
imaji plays Thero Centurion
Ready phase - imaji
imaji readies all of their cards 
Draw phase - imaji
imaji draws 1 cards  up to their maximum hand size of 6
End of turn 1
imaji: 0 Æmber  Samurai_riky: 0 Æmber 
Turn 2
Key phase - Samurai_riky
Samurai_riky does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Samurai_riky
Samurai_riky chooses staralliance  as their active house this turn
Main phase - Samurai_riky
Samurai_riky plays Commander Chan
Samurai_riky plays Medic Ingram
Samurai_riky uses Medic Ingram to heal 3 damage and ward Medic Ingram
Samurai_riky plays Force Field, gaining 1 Æmber  attaching it to Commander Chan
Samurai_riky plays Xenotraining, gaining 1 Æmber 
Ready phase - Samurai_riky
Samurai_riky readies all of their cards 
Draw phase - Samurai_riky
Samurai_riky draws 4 cards  up to their maximum hand size of 6
End of turn 2
imaji: 0 Æmber  Samurai_riky: 2 Æmber 
Turn 2
Key phase - imaji
imaji does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - imaji
imaji chooses shadows  as their active house this turn
Main phase - imaji
imaji plays Ronnie Wristclocks
imaji uses Ronnie Wristclocks to steal 1 Æmber  from Samurai_riky
imaji plays Whisper
imaji plays Subtle Maul
imaji plays Hugger-Mugger
imaji uses Hugger-Mugger to capture 1 Æmber  from Samurai_riky, placing it on Hugger-Mugger
Ready phase - imaji
imaji readies all of their cards 
Draw phase - imaji
imaji draws 4 cards  up to their maximum hand size of 6
End of turn 2
imaji: 1 Æmber  Samurai_riky: 0 Æmber 
Turn 3
Key phase - Samurai_riky
Samurai_riky does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Samurai_riky
Samurai_riky chooses staralliance  as their active house this turn
Main phase - Samurai_riky
Samurai_riky plays Tachyon Pulse, gaining 1 Æmber 
Samurai_riky uses Tachyon Pulse to destroy Subtle Maul
Samurai_riky uses Tachyon Pulse to exhaust Commander Chan
Samurai_riky plays Lieutenant Khrkhar
Samurai_riky uses Medic Ingram to make Medic Ingram fight Whisper
Ready phase - Samurai_riky
Samurai_riky readies all of their cards 
Draw phase - Samurai_riky
Samurai_riky draws 2 cards  up to their maximum hand size of 6
End of turn 3
imaji: 1 Æmber  Samurai_riky: 1 Æmber 
Turn 3
Key phase - imaji
imaji does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - imaji
imaji chooses shadows  as their active house this turn
Main phase - imaji
imaji plays Yantzee Gang
imaji plays Pestering Blow, gaining 1 Æmber 
imaji uses Pestering Blow to deal 1 damage and enrage Commander Chan
imaji uses Whisper to make imaji lose 1 Æmber 
imaji uses Whisper to destroy Commander Chan
imaji uses Hugger-Mugger to reap with Hugger-Mugger
imaji uses Ronnie Wristclocks to reap with Ronnie Wristclocks
Ready phase - imaji
imaji readies all of their cards 
Draw phase - imaji
imaji draws 2 cards  up to their maximum hand size of 6
End of turn 3
imaji: 3 Æmber  Samurai_riky: 1 Æmber 
Turn 4
Key phase - Samurai_riky
Samurai_riky does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Samurai_riky
Samurai_riky chooses staralliance  as their active house this turn
Main phase - Samurai_riky
Samurai_riky plays Stealth Mode, gaining 1 Æmber 
Samurai_riky uses Stealth Mode to stop imaji from playing any actions on their next turn
Samurai_riky uses Lieutenant Khrkhar to make Lieutenant Khrkhar fight Whisper
Samurai_riky uses Medic Ingram to make Medic Ingram fight Whisper
Samurai_riky uses Medic Ingram to remove its ward token
Samurai_riky uses Medic Ingram to heal 3 damage and ward Lieutenant Khrkhar
Samurai_riky plays Tactical Officer Moon
Samurai_riky uses Tactical Officer Moon to rearrange creatures on a battleline
Ready phase - Samurai_riky
Samurai_riky readies all of their cards 
Draw phase - Samurai_riky
Samurai_riky draws 2 cards  up to their maximum hand size of 6
End of turn 4
imaji: 3 Æmber  Samurai_riky: 2 Æmber 
Turn 4
Key phase - imaji
imaji does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - imaji
imaji chooses shadows  as their active house this turn
Main phase - imaji
imaji plays Umbra
imaji uses Yantzee Gang to steal 1 Æmber  from Samurai_riky
imaji
gah, forgot about taunt
 imaji is attempting to switch manual mode on
 Samurai_riky allows enabling manual mode
 imaji switches manual mode on
 imaji readies Hugger-Mugger
 imaji switches manual mode off
imaji
ty
imaji uses Ronnie Wristclocks to reap with Ronnie Wristclocks
imaji uses Hugger-Mugger to reap with Hugger-Mugger
Ready phase - imaji
imaji readies all of their cards 
Draw phase - imaji
imaji draws 1 cards  up to their maximum hand size of 6
 imaji declares Check!
End of turn 4
imaji: 6 Æmber  Samurai_riky: 1 Æmber 
Turn 5
Key phase - Samurai_riky
Samurai_riky does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Samurai_riky
Samurai_riky chooses dis  as their active house this turn
Main phase - Samurai_riky
Samurai_riky uses Snag to make Snag fight Thero Centurion
Samurai_riky plays Lilithal
Samurai_riky plays Impspector
Ready phase - Samurai_riky
Samurai_riky readies all of their cards 
Draw phase - Samurai_riky
Samurai_riky draws 2 cards  up to their maximum hand size of 6
End of turn 5
imaji: 6 Æmber  Samurai_riky: 1 Æmber 
Turn 5
Key phase - imaji
imaji forges the yellow key  , paying 6 Æmber 
House phase - imaji
imaji chooses saurian  as their active house this turn
Main phase - imaji
imaji plays Imperium, gaining 1 Æmber 
imaji uses Imperium to ward Thero Centurion and Yantzee Gang
imaji plays Phalanx Strike, gaining 1 Æmber 
imaji uses Phalanx Strike to deal 5 damage to Medic Ingram
imaji exalts Thero Centurion to repeat Phalanx Strike's effect
imaji uses Phalanx Strike to deal 5 damage to Lilithal
imaji uses Thero Centurion to make Thero Centurion fight Lieutenant Khrkhar
Samurai_riky uses Lieutenant Khrkhar to deal 3 damage to Thero Centurion
imaji uses Thero Centurion to remove its ward token
Samurai_riky uses Lieutenant Khrkhar to remove its ward token

**Comment by jeremylarner** [comment]
Khrkhar was warded, so both creatures fought, Centurion died and Khrkhar lost its ward
