### ISSUE TITLE
Kirby and spears defect

### ISSUE THREAD

**Issue by DaveCordeiro** [keyteki/keyteki#944]
if you use kirby, then use spears the new cards in your hand are not tagged as playable 
![image](https://user-images.githubusercontent.com/57851149/69022540-3bfba480-0981-11ea-8923-e8110788962c.png)
https://pastebin.com/Yh8VZtTu

**Comment by Achocholacek** [comment]
Expanded test coverage to include this scenario. Cannot make this issue happen.

Reviewed provided game log, log does not actually show the issue occurring (Kirby reaps, Axiom of Grisk is played).

Closing for now. Please open a new ticket if this is incorrect or the situation reoccurs.
