### ISSUE TITLE
Assault and Hazardous does not prompt for ordering

### ISSUE THREAD

**Issue by DaveCordeiro** [keyteki/keyteki#945]
They happen in the same place on the timing chart, therefor as the attacker I should be able to choose the order they happen in. In this game I attacked a xenos with my moon and the moon just died without dealing the assault damage https://pastebin.com/Yh8VZtTu
Sorry the screenshot is right before this happened, I encountered multiple bugs this game and lost the other screenshot of after 
![image](https://user-images.githubusercontent.com/57851149/69022936-8e899080-0982-11ea-862a-877a7dc8674f.png)

**Comment by romanogit** [comment]
Can you take a screenshot of your profile preferences? There are two checkboxes at the button for auto prompt that might interfere with this behavior.

**Comment by DaveCordeiro** [comment]
![image](https://user-images.githubusercontent.com/57851149/69066362-c9251480-09e6-11ea-9926-ed134cf6355f.png)
Also, even if that is not checked, should this not default to assault first, as I imagine most people will want their damage to happen first?

**Comment by romanogit** [comment]
The behavior of "Prompt to order si... abilities" is incorrect. I fixed it in #1023
