### ISSUE TITLE
Unable to log in after making an account.

### ISSUE THREAD

**Issue by JarettRoman** [keyteki/keyteki#946]
Hello. I'm unable to log in after making an account. The email address I signed up with is afrocious@gmail.com. I'm able to change my password just fine, but every time I use the new password, I get the error saying username/password is invalid. This is not true, so I'm wondering if there's something weird on the backend preventing me from logging in.

My username is afrocious.

Thanks!

**Comment by cryogen** [comment]
I don't see anything in the logs.  If you get that error then it probably is a wrong username/password combination.  Let me know if you're still having trouble and a timestamp of when you try
