### ISSUE TITLE
No way to specify which cross house cheating you are using

### ISSUE THREAD

**Issue by DaveCordeiro** [keyteki/keyteki#947]
![image](https://user-images.githubusercontent.com/57851149/69024880-5a19d280-098a-11ea-9ae9-1847bc3fed6a.png)
https://pastebin.com/jCQxtX4H
Here, the player with Val played a kirby then played trust no one, which it counted as the play for Val, then she could not play the off house creatures in her hand.

**Comment by blinkingline** [comment]
I thought I had added this previously, but we did get a message back from FFG on this:

> I have three cards in my battleline; Captain Val Jericho in the Center of the Battleline with Com. Officer Kirby as a neighbor. On my turn, I reap with Com. Officer Kirby, granting me a play allowance of a non-Star Alliance action, artifact, or upgrade for the rest of the turn. Captain Val Jericho is also granting a play allowance of a card that is not of the active house. If I play a Shadows action, does this use up both allowances?
> This follows the same precedent as playing two Phase Shifts, which gives you two play allowances and only uses one on the first non-Logos card you play. Playing a Shadows action in this case will only use up one of your two play allowances, leaving you one more to use. You can choose whether to use Com. Officer Kirby's or Captain Val Jericho's play allowance first, leaving the other open (with the caveat that Captain Val has to be in the center of your battleline when you use her play allowance).
