### ISSUE TITLE
C.A.N.D.L.E. UNIT captures one with action, but the opponent's amber remains the same

### ISSUE THREAD

**Issue by cmorenoserrano** [keyteki/keyteki#948]
Just played a match and at the key moment, I used C.A.N.D.L.E. unit to capture the decisive 1 amber to take the win, however, 1 amber appears on top of the C.A.N.D.L.E. card, but the amber counter for my opponent did not go one down, allowing him to forge his last key and depriving me from my win.

Please fix.
Many thanks.

**Comment by SkyJedi** [comment]
sounds like a Po's pixies was out maybe? 
![image](https://user-images.githubusercontent.com/2967416/69244773-2ea20e00-0b6b-11ea-9fe3-02d4832c1af1.png)

**Comment by cmorenoserrano** [comment]
No, it was not in play.

**Comment by Achocholacek** [comment]
At this point, I am unable to recreate the scenario and test coverage does not show a fail. Should this issue occur again, please open a new ticket with as much additional game state data as you can provide!
