### ISSUE TITLE
J. Vinda is not stealing Aember on reap

### ISSUE THREAD

**Issue by Zurek96** [keyteki/keyteki#954]
Hi,
I have spotted the issue today. I have used J. Vinda to reap, and the effect triggered (I was able do deal damage to opponents' Bad Penny), but then I didn't steal any aember. As far as I'm concerned Bad Penny is destroyed so the stealing effect should be triggered. 

Below is a chat log (VarsVikernes is my opponent, I'm Zurek96):

VarsVikernes is shuffling their deck
Zurek96 is shuffling their deck
VarsVikernes is playing as the Archon: Fontaine el Terrible
Zurek96 is playing as the Archon: W. Morales, Rzeźnik ze Słynnej Jamy
 Zurek96 has connected to the game server
 VarsVikernes has connected to the game server
VarsVikernes draws 6 cards  up to their maximum hand size of 6
Zurek96 draws 6 cards  up to their maximum hand size of 6
Key phase - VarsVikernes
VarsVikernes does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - VarsVikernes
VarsVikernes chooses sanctum  as their active house this turn
Main phase - VarsVikernes
VarsVikernes plays Champion Anaphiel
Ready phase - VarsVikernes
VarsVikernes readies all of their cards 
Draw phase - VarsVikernes
End of turn 1
VarsVikernes: 0 Æmber  Zurek96: 0 Æmber 
Turn 1
Key phase - Zurek96
Zurek96 does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Zurek96
Zurek96 chooses logos  as their active house this turn
Main phase - Zurek96
Zurek96 plays Hologrammophone, gaining 1 Æmber 
Zurek96 plays Pocket Universe
Zurek96 plays Daughter
Zurek96 plays Groupthink Tank
Zurek96 plays Cutthroat Research, gaining 1 Æmber 
Ready phase - Zurek96
Zurek96 readies all of their cards 
Draw phase - Zurek96
Zurek96 draws 6 cards  up to their maximum hand size of 7
End of turn 1
VarsVikernes: 0 Æmber  Zurek96: 2 Æmber 
Turn 2
Key phase - VarsVikernes
VarsVikernes does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - VarsVikernes
VarsVikernes chooses dis  as their active house this turn
Main phase - VarsVikernes
VarsVikernes plays Ember Imp
VarsVikernes plays Dust Imp
Ready phase - VarsVikernes
VarsVikernes readies all of their cards 
Draw phase - VarsVikernes
VarsVikernes draws 2 cards  up to their maximum hand size of 6
End of turn 2
VarsVikernes: 0 Æmber  Zurek96: 2 Æmber 
Turn 2
Key phase - Zurek96
Zurek96 does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - Zurek96
Zurek96 chooses shadows  as their active house this turn
Main phase - Zurek96
Zurek96 plays Mug, gaining 1 Æmber 
Zurek96 uses Mug to move 1 Æmber  from Ember Imp to their pool and deal 2 damage to it
Zurek96 plays J. Vinda
Zurek96 plays Mack the Knife
Zurek96 discards Hit and Run
Zurek96 plays No Safety in Numbers, gaining 1 Æmber 
Ready phase - Zurek96
Zurek96 readies all of their cards 
Draw phase - Zurek96
Zurek96 draws 5 cards  up to their maximum hand size of 7
End of turn 2
VarsVikernes: 0 Æmber  Zurek96: 4 Æmber 
Turn 3
Key phase - VarsVikernes
VarsVikernes does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - VarsVikernes
VarsVikernes chooses shadows  as their active house this turn
Main phase - VarsVikernes
VarsVikernes plays Urchin
VarsVikernes uses Urchin to steal 1 Æmber  from Zurek96
VarsVikernes plays Bad Penny
VarsVikernes plays Noddy the Thief
VarsVikernes plays Ghostly Hand, gaining 2 Æmber 
Ready phase - VarsVikernes
VarsVikernes readies all of their cards 
Draw phase - VarsVikernes
VarsVikernes draws 4 cards  up to their maximum hand size of 6
End of turn 3
VarsVikernes: 3 Æmber  Zurek96: 3 Æmber 
Turn 3
Key phase - Zurek96
Zurek96 does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - Zurek96
Zurek96 chooses dis  as their active house this turn
Main phase - Zurek96
Zurek96 plays Draining Touch
Zurek96 uses Draining Touch to destroy Noddy the Thief
Zurek96 uses Mack the Knife to deal damage to Urchin
Zurek96 plays Soul Snatcher
Zurek96 plays Obsidian Forge, gaining 1 Æmber 
Zurek96 plays Bloodshard Imp
Zurek96 plays Etaromme
Zurek96 plays Skullion
Zurek96 uses Skullion to sacrifice Bloodshard Imp
Zurek96 uses Soul Snatcher to make Zurek96 gain 1 Æmber  due to Bloodshard Imp being destroyed
Ready phase - Zurek96
Zurek96 readies all of their cards 
Draw phase - Zurek96
Zurek96 draws 6 cards  up to their maximum hand size of 7
 Zurek96 declares Check!
End of turn 3
VarsVikernes: 3 Æmber  Zurek96: 6 Æmber 
Turn 4
Key phase - VarsVikernes
VarsVikernes does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - VarsVikernes
VarsVikernes chooses shadows  as their active house this turn
Main phase - VarsVikernes
VarsVikernes plays Booby Trap, gaining 1 Æmber 
VarsVikernes uses Booby Trap to deal 4 damage to Mack the Knife and 2 to their neighbors
Zurek96 uses Soul Snatcher to make Zurek96 gain 1 Æmber  due to Mack the Knife being destroyed
Zurek96 uses Soul Snatcher to make Zurek96 gain 1 Æmber  due to Daughter being destroyed
VarsVikernes plays Miasma, gaining 1 Æmber 
VarsVikernes uses Miasma to make Zurek96 skip their key step next turn
VarsVikernes uses Bad Penny to reap with Bad Penny
Ready phase - VarsVikernes
VarsVikernes readies all of their cards 
Draw phase - VarsVikernes
VarsVikernes draws 2 cards  up to their maximum hand size of 6
 VarsVikernes declares Check!
End of turn 4
VarsVikernes: 6 Æmber  Zurek96: 8 Æmber 
Turn 4
House phase - Zurek96
Zurek96 chooses shadows  as their active house this turn
Main phase - Zurek96
Zurek96 plays Oubliette
Zurek96 uses Oubliette to purge Dust Imp
Zurek96 uses J. Vinda to reap with J. Vinda
Zurek96 uses J. Vinda to deal 1 damage to Bad Penny
VarsVikernes uses Bad Penny to return Bad Penny to their hand
Zurek96 uses Soul Snatcher to make VarsVikernes gain 1 Æmber  due to Bad Penny being destroyed
Zurek96 plays Yantzee Gang

And here is screenshot:
![image](https://user-images.githubusercontent.com/38273257/69141963-175d1500-0ac6-11ea-82e3-c5bc0722e102.png)

**Comment by romanogit** [comment]
It did steal, just the message was not displayed.

You started turn with 8.
Reaped with J. Vinda: 9
Damage Penny and stole: 10

Opponent started turn with 6.
You stole with J. Vinda: 5
Soul Snatcher gave him +1: 6

I will fix the message.
