### ISSUE TITLE
Information Exchange and Sci. Officer Quincan interaction

### ISSUE THREAD

**Issue by Warfare13** [keyteki/keyteki#956]
Hi,
I had Sci. Officer Quincan (Star Alliance) in play and my opponent played Information Exchange (Logos) and stole 2 aember but I hadn't stolen in my turn, only stole 1 in their turn due to no Logos cards in play when they called their house

**Comment by avandever** [comment]
Happened to me today. I saved the log and took a screenshot:
https://justpaste.it/3s6f5
