### ISSUE TITLE
Infurnace 

### ISSUE THREAD

**Issue by Duxer86** [keyteki/keyteki#957]
Hi, played Infurnace and purged Interdimensional Graft and Force Field, but my opponent lost only 1 amber.
![board_state](https://user-images.githubusercontent.com/14357933/69199105-58414200-0b37-11ea-8a82-557ce6c35459.png)
[chat_log.txt](https://github.com/keyteki/keyteki/files/3866729/chat_log.txt)

**Comment by romanogit** [comment]
`Infurnace` is working as expected in this scenario.

Your opponent played IG in the previous turn.
You had 7 amber and forged a key handling him the remaining amber. He then goes from 5 to 6.
You play Infurnace and he loses 2 ambers ending the turn with 2 amber as expected.

However, I found a corner case while trying to recreate this one. 
Infurnace does not make your opponent lose amber if you have Ether Spider in play. I am fixing that.
