### ISSUE TITLE
Spartasaur portuguese image missing

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#958]
Not sure why, but Spartasaur portuguese image seems to be missing on the server:
https://www.thecrucible.online/img/cards/pt/spartasaur.png

![image](https://user-images.githubusercontent.com/2104075/69202936-ce3aae80-0b21-11ea-8f25-ef2e4aad6faa.png)

All others are available.

**Comment by SkyJedi** [comment]
![231](https://user-images.githubusercontent.com/2967416/69203153-3f219c80-0b09-11ea-97f1-27f3d454abc2.png)

**Comment by cryogen** [comment]
Fixed
