### ISSUE TITLE
Spartasaur interaction with Reassembling Automaton is causing multiple destroy calls

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#959]
After `Gebuk` was destroyed, Spartasaur trigger a massive destruction, and `Reassembling Automaton` kept prompting for reaction until it stopped after almost 10 prompts.

adamgrey uses Gebuk to make Gebuk fight Shooler
adamgrey uses Gebuk to discard Titan Guardian
adamgrey uses Spartasaur to destroy Titan Guardian, Brutodon Auxiliary, Reassembling Automaton, Titan Guardian, Molephin, Inka the Spider, Toad, Charette, and Restringuntus
adamgrey uses Titan Guardian to draw 2 cards 
adamgrey uses Reassembling Automaton to heal all damage from Reassembling Automaton, exhaust it and move it to a flank
romanomagacho22 uses Charette to destroy Odoac the Patrician  <----- This was due to Soulkeeper
adamgrey uses Odoac the Patrician to remove all Æmber  from Odoac the Patrician
adamgrey uses Spartasaur to destroy Titan Guardian, Brutodon Auxiliary, Titan Guardian, Molephin, Inka the Spider, Toad, Reassembling Automaton, Charette, and Restringuntus
adamgrey uses Reassembling Automaton to heal all damage from Reassembling Automaton, exhaust it and move it to a flank
adamgrey uses Spartasaur to destroy Reassembling Automaton
adamgrey uses Reassembling Automaton to heal all damage from Reassembling Automaton, exhaust it and move it to a flank
adamgrey uses Spartasaur to destroy Reassembling Automaton
adamgrey uses Reassembling Automaton to heal all damage from Reassembling Automaton, exhaust it and move it to a flank
adamgrey uses Spartasaur to destroy Reassembling Automaton
adamgrey uses Reassembling Automaton to heal all damage from Reassembling Automaton, exhaust it and move it to a flank
adamgrey uses Spartasaur to destroy Reassembling Automaton
adamgrey uses Reassembling Automaton to heal all damage from Reassembling Automaton, exhaust it and move it to a flank
adamgrey uses Spartasaur to destroy Reassembling Automaton
adamgrey uses Reassembling Automaton to heal all damage from Reassembling Automaton, exhaust it and move it to a flank
adamgrey uses Spartasaur to destroy Reassembling Automaton
adamgrey uses Reassembling Automaton to heal all damage from Reassembling Automaton, exhaust it and move it to a flank

**Comment by oli0** [comment]
Spartasaur effect destroyed warded Daughter from me and Chief Engineer Walls played under Jargogle, so at least in case of Daughter the effect triggered twice. Titan Guardian was present on this match too.

**Comment by oli0** [comment]
olio is shuffling their deck
CLAUDIS is shuffling their deck
olio is playing as the Archon: The Hostile Bandit
CLAUDIS is playing as the Archon: Efesto, il Pulito del Burrone Gioioso
 olio has connected to the game server
 CLAUDIS has connected to the game server

olio
Greetings! Good luck and have fun :)
olio draws 6 cards  up to their maximum hand size of 6
CLAUDIS draws 6 cards  up to their maximum hand size of 6

Key phase - CLAUDIS
CLAUDIS does not forge a key. They have 0 amber. The current cost is 6 Æmber 

House phase - CLAUDIS

CLAUDIS
hi, have fun and good luck
CLAUDIS chooses logos  as their active house this turn

Main phase - CLAUDIS
CLAUDIS plays Zenzizenzizenzic

Ready phase - CLAUDIS
CLAUDIS readies all of their cards 

Draw phase - CLAUDIS
CLAUDIS draws 2 cards  up to their maximum hand size of 8

End of turn 1
olio: 0 Æmber  CLAUDIS: 0 Æmber 

Turn 1

Key phase - olio
olio does not forge a key. They have 0 amber. The current cost is 6 Æmber 

House phase - olio
olio chooses logos  as their active house this turn

Main phase - olio
olio plays Seismo-entangler
olio plays Hologrammophone, gaining 1 Æmber 
olio plays Quantum Fingertrap, gaining 1 Æmber 

Ready phase - olio
olio readies all of their cards 

Draw phase - olio
olio draws 3 cards  up to their maximum hand size of 6

End of turn 1
olio: 2 Æmber  CLAUDIS: 0 Æmber 

Turn 2

Key phase - CLAUDIS
CLAUDIS does not forge a key. They have 0 amber. The current cost is 6 Æmber 

House phase - CLAUDIS
CLAUDIS chooses logos  as their active house this turn

Main phase - CLAUDIS
CLAUDIS uses Zenzizenzizenzic to reap with Zenzizenzizenzic
CLAUDIS plays Jargogle
CLAUDIS uses Jargogle to place a card  under Jargogle
CLAUDIS plays Babbling Bibliophile

Ready phase - CLAUDIS
CLAUDIS readies all of their cards 

Draw phase - CLAUDIS
CLAUDIS draws 3 cards  up to their maximum hand size of 8

End of turn 2
olio: 2 Æmber  CLAUDIS: 1 Æmber 

Turn 2

Key phase - olio
olio does not forge a key. They have 2 amber. The current cost is 6 Æmber 

House phase - olio
olio chooses shadows  as their active house this turn

Main phase - olio
olio plays Mug, gaining 1 Æmber 
olio uses Mug to move 1 Æmber  from Babbling Bibliophile to their pool and deal 2 damage to it
olio plays Spike Trap, gaining 1 Æmber 
olio plays The Quiet Anvil, gaining 1 Æmber 

Ready phase - olio
olio readies all of their cards 

Draw phase - olio
olio draws 3 cards  up to their maximum hand size of 6
 olio declares Check!

End of turn 2
olio: 5 Æmber  CLAUDIS: 1 Æmber 

Turn 3

Key phase - CLAUDIS
CLAUDIS does not forge a key. They have 1 amber. The current cost is 4 Æmber 

House phase - CLAUDIS
CLAUDIS chooses logos  as their active house this turn

Main phase - CLAUDIS
CLAUDIS uses Zenzizenzizenzic to reap with Zenzizenzizenzic
CLAUDIS uses Jargogle to reap with Jargogle
CLAUDIS plays Titan Guardian
CLAUDIS discards Positron Bolt

Ready phase - CLAUDIS
CLAUDIS readies all of their cards 

Draw phase - CLAUDIS
CLAUDIS draws 2 cards  up to their maximum hand size of 8

End of turn 3
olio: 5 Æmber  CLAUDIS: 3 Æmber 

Turn 3

Key phase - olio
olio forges the yellow key  , paying 4 Æmber 
olio uses The Quiet Anvil to destroy The Quiet Anvil

House phase - olio
olio chooses logos  as their active house this turn

Main phase - olio
olio uses Quantum Fingertrap to swap the position of Zenzizenzizenzic and Jargogle
olio uses Spike Trap to sacrifice Spike Trap
olio uses Spike Trap to deal 3 damage to Titan Guardian and Zenzizenzizenzic
olio plays Twin Bolt Emission, gaining 1 Æmber 
olio uses Twin Bolt Emission to deal 2 damage to Jargogle and Zenzizenzizenzic
CLAUDIS uses Jargogle to archive a card 
olio plays Titan Guardian
olio plays Jargogle
olio uses Jargogle to place a card  under Jargogle
olio uses Hologrammophone to ward Titan Guardian
olio uses Seismo-entangler to stop logos  creatures from reaping next turn

Ready phase - olio
olio readies all of their cards 

Draw phase - olio
olio draws 4 cards  up to their maximum hand size of 6

End of turn 3
olio: 2 Æmber  CLAUDIS: 3 Æmber 

Turn 4

Key phase - CLAUDIS
CLAUDIS does not forge a key. They have 3 amber. The current cost is 6 Æmber 

House phase - CLAUDIS
CLAUDIS chooses staralliance  as their active house this turn

Main phase - CLAUDIS
CLAUDIS plays Sensor Chief Garcia
CLAUDIS uses Sensor Chief Garcia to increase olio's key cost by 2 until the end of their next turn
CLAUDIS plays Cloaking Dongle, gaining 1 Æmber  attaching it to Sensor Chief Garcia
CLAUDIS plays Light of the Archons, gaining 1 Æmber  attaching it to Sensor Chief Garcia

Ready phase - CLAUDIS
CLAUDIS readies all of their cards 

Draw phase - CLAUDIS
CLAUDIS draws 3 cards  up to their maximum hand size of 8

End of turn 4
olio: 2 Æmber  CLAUDIS: 5 Æmber 

Turn 4

Key phase - olio
olio does not forge a key. They have 2 amber. The current cost is 8 Æmber 

House phase - olio
olio chooses saurian  as their active house this turn

Main phase - olio
olio plays Rhetor Gallim
olio uses Rhetor Gallim to increase CLAUDIS's key cost by 3 until the end of their next turn
olio plays Auto-Legionary
olio plays Odoac the Patrician
olio uses Odoac the Patrician to capture 1 Æmber  from CLAUDIS, placing it on Odoac the Patrician
olio plays Imperial Scutum, gaining 1 Æmber  attaching it to Rhetor Gallim
olio plays Chant of Hubris, gaining 1 Æmber 
olio uses Chant of Hubris to remove 1 Æmber  from Odoac the Patrician
olio uses Chant of Hubris to place 1 Æmber  on Rhetor Gallim

Ready phase - olio
olio readies all of their cards 

Draw phase - olio
olio draws 5 cards  up to their maximum hand size of 6

End of turn 4
olio: 4 Æmber  CLAUDIS: 4 Æmber 

Turn 5

Key phase - CLAUDIS
CLAUDIS does not forge a key. They have 4 amber. The current cost is 9 Æmber 

House phase - CLAUDIS
CLAUDIS chooses logos  as their active house this turn

Main phase - CLAUDIS
CLAUDIS plays Wild Wormhole, gaining 1 Æmber 
CLAUDIS uses Wild Wormhole to play the top card  of their deck : Sic Semper Tyrannosaurus
CLAUDIS plays Sic Semper Tyrannosaurus
CLAUDIS uses Sic Semper Tyrannosaurus to take all Æmber  from Odoac the Patrician and destroy it
CLAUDIS uses Titan Guardian to reap with Titan Guardian
CLAUDIS uses Zenzizenzizenzic to reap with Zenzizenzizenzic
CLAUDIS plays Thorium Plasmate, gaining 1 Æmber 
CLAUDIS uses Thorium Plasmate to move Rhetor Gallim on olio's battleline and deal 2 damage to it for each neighbor that shares a house with it

Ready phase - CLAUDIS
CLAUDIS readies all of their cards 

Draw phase - CLAUDIS
CLAUDIS draws 2 cards  up to their maximum hand size of 8

End of turn 5
olio: 4 Æmber  CLAUDIS: 8 Æmber 

Turn 5

Key phase - olio
olio does not forge a key. They have 4 amber. The current cost is 6 Æmber 

House phase - olio
olio chooses saurian  as their active house this turn

Main phase - olio
olio uses Auto-Legionary to do several things
olio plays Tribute, gaining 1 Æmber 
olio uses Tribute to capture 2 Æmber  from CLAUDIS, placing it on Auto-Legionary
olio exalts Auto-Legionary to repeat the effect of Tribute
olio uses Tribute to capture 2 Æmber  from CLAUDIS, placing it on Auto-Legionary
olio plays Exile, gaining 1 Æmber 
olio uses Exile to give control of Auto-Legionary to CLAUDIS
olio uses Rhetor Gallim to reap with Rhetor Gallim

Ready phase - olio
olio readies all of their cards 

Draw phase - olio
olio draws 2 cards  up to their maximum hand size of 6
 olio declares Check!

End of turn 5
olio: 7 Æmber  CLAUDIS: 4 Æmber 

Turn 6

Key phase - CLAUDIS
CLAUDIS does not forge a key. They have 4 amber. The current cost is 6 Æmber 

House phase - CLAUDIS
CLAUDIS chooses saurian  as their active house this turn
CLAUDIS moves all the cards  in their archives to their hand

Main phase - CLAUDIS
CLAUDIS plays Rhetor Gallim
CLAUDIS uses Rhetor Gallim to increase olio's key cost by 3 until the end of their next turn
CLAUDIS plays Tricerian Legionary
CLAUDIS uses Tricerian Legionary to ward Auto-Legionary
CLAUDIS plays Paraguardian
CLAUDIS discards Questor Jarta
CLAUDIS plays Tribute, gaining 1 Æmber 
CLAUDIS uses Tribute to capture 2 Æmber  from olio, placing it on Paraguardian
CLAUDIS exalts Paraguardian to repeat the effect of Tribute
CLAUDIS uses Tribute to capture 2 Æmber  from olio, placing it on Paraguardian
CLAUDIS plays Imperial Forge, gaining 1 Æmber 
CLAUDIS uses Imperial Forge to forge a key at -2 Æmber  current cost
CLAUDIS forges the red key  , paying 4 Æmber 

Ready phase - CLAUDIS
CLAUDIS readies all of their cards 

Draw phase - CLAUDIS
CLAUDIS draws 5 cards  up to their maximum hand size of 8

End of turn 6
olio: 3 Æmber  CLAUDIS: 2 Æmber 

Turn 6

Key phase - olio
olio does not forge a key. They have 3 amber. The current cost is 9 Æmber 

House phase - olio
olio chooses logos  as their active house this turn

Main phase - olio
olio uses Quantum Fingertrap to swap the position of Paraguardian and Auto-Legionary
olio uses Jargogle to make Jargogle fight Auto-Legionary
CLAUDIS uses Auto-Legionary to remove its ward token
olio uses Jargogle to play J. Vinda
olio plays J. Vinda
olio uses Titan Guardian to make Titan Guardian fight Auto-Legionary
olio uses Titan Guardian to remove its ward token
olio plays Dr. Milli
olio uses Dr. Milli to archive 3 cards 
olio plays Daughter
olio uses Hologrammophone to ward Daughter
olio plays Dysania
olio uses Seismo-entangler to stop saurian  creatures from reaping next turn

Ready phase - olio
olio readies all of their cards 

Draw phase - olio
olio draws 7 cards  up to their maximum hand size of 7

End of turn 6
olio: 8 Æmber  CLAUDIS: 2 Æmber 

Turn 7

Key phase - CLAUDIS
CLAUDIS does not forge a key. They have 2 amber. The current cost is 6 Æmber 

House phase - CLAUDIS
CLAUDIS chooses staralliance  as their active house this turn

Main phase - CLAUDIS
CLAUDIS uses Sensor Chief Garcia to reap with Sensor Chief Garcia
CLAUDIS uses Sensor Chief Garcia to increase olio's key cost by 2 until the end of their next turn
CLAUDIS plays Armsmaster Molina
CLAUDIS plays Sensor Chief Garcia
CLAUDIS uses Sensor Chief Garcia to increase olio's key cost by 2 until the end of their next turn
CLAUDIS plays Explo-rover
CLAUDIS plays Stealth Mode, gaining 1 Æmber 
CLAUDIS uses Stealth Mode to stop olio from playing any actions on their next turn
CLAUDIS plays Zap, gaining 1 Æmber 
CLAUDIS uses Zap to deal 1 damage to a creature for each house represented among creatures in play

Ready phase - CLAUDIS
CLAUDIS readies all of their cards 

Draw phase - CLAUDIS
CLAUDIS draws 5 cards  up to their maximum hand size of 8

End of turn 7
olio: 8 Æmber  CLAUDIS: 5 Æmber 

Turn 7

Key phase - olio
olio does not forge a key. They have 8 amber. The current cost is 10 Æmber 

House phase - olio
olio chooses shadows  as their active house this turn
olio moves all the cards  in their archives to their hand

Main phase - olio
olio plays Breaker Hill
olio plays Whisper
olio plays Yantzee Gang
olio plays Fidgit
olio plays Umbra
olio uses J. Vinda to reap with J. Vinda
olio uses J. Vinda to deal 1 damage to Rhetor Gallim

Ready phase - olio
olio readies all of their cards 

Draw phase - olio
olio draws 2 cards  up to their maximum hand size of 7

End of turn 7
olio: 9 Æmber  CLAUDIS: 5 Æmber 

Turn 8

Key phase - CLAUDIS
CLAUDIS does not forge a key. They have 5 amber. The current cost is 6 Æmber 

House phase - CLAUDIS
CLAUDIS chooses logos  as their active house this turn

Main phase - CLAUDIS
CLAUDIS uses Zenzizenzizenzic to make Zenzizenzizenzic fight Whisper
CLAUDIS uses Titan Guardian to make Titan Guardian fight Whisper
CLAUDIS plays Positron Bolt, gaining 1 Æmber 
CLAUDIS uses Positron Bolt to deal 3 damage to Fidgit, 2 damage to Breaker Hill and 1 damage to Dysania
CLAUDIS plays Memory Chip
CLAUDIS plays Jargogle
CLAUDIS uses Jargogle to place a card  under Jargogle
CLAUDIS plays Wormhole Technician
CLAUDIS discards Wormhole Technician

Ready phase - CLAUDIS
CLAUDIS readies all of their cards 

Draw phase - CLAUDIS
CLAUDIS draws 6 cards  up to their maximum hand size of 8
 CLAUDIS declares Check!

End of turn 8
olio: 9 Æmber  CLAUDIS: 6 Æmber 

Turn 8

Key phase - olio
olio forges the red key  , paying 6 Æmber 

House phase - olio
olio chooses shadows  as their active house this turn

Main phase - olio
olio plays Treasure Map, gaining 1 Æmber 
olio uses Treasure Map to make themselves unable to play any more cards  this turn and gain 3 Æmber 
olio uses Umbra to make Umbra fight Wormhole Technician
olio uses Umbra to steal 1 Æmber  from CLAUDIS
olio uses J. Vinda to reap with J. Vinda
olio uses J. Vinda to deal 1 damage to Wormhole Technician
olio uses J. Vinda to steal 1 Æmber  from CLAUDIS
olio uses Yantzee Gang to steal 1 Æmber  from CLAUDIS

Ready phase - olio
olio readies all of their cards 

Draw phase - olio
olio draws 1 cards  up to their maximum hand size of 7
 olio declares Check!

End of turn 8
olio: 11 Æmber  CLAUDIS: 3 Æmber 

Turn 9

Key phase - CLAUDIS
CLAUDIS does not forge a key. They have 3 amber. The current cost is 6 Æmber 

House phase - CLAUDIS
CLAUDIS chooses saurian  as their active house this turn

Main phase - CLAUDIS
CLAUDIS plays Chant of Hubris, gaining 1 Æmber 
CLAUDIS uses Chant of Hubris to remove 1 Æmber  from Paraguardian
CLAUDIS uses Chant of Hubris to place 1 Æmber  on Umbra
CLAUDIS plays Spartasaur
CLAUDIS uses Rhetor Gallim to make Rhetor Gallim fight Yantzee Gang
CLAUDIS uses Spartasaur to destroy Dysania, Daughter, Titan Guardian, J. Vinda, Yantzee Gang, Umbra, Sensor Chief Garcia, Armsmaster Molina, Titan Guardian, Zenzizenzizenzic, Sensor Chief Garcia, Explo-rover, and Jargogle
olio uses Daughter to remove its ward token
CLAUDIS uses Titan Guardian to draw 2 cards 
CLAUDIS's deck has run out of cards, so they shuffle
CLAUDIS is shuffling their deck
olio uses Titan Guardian to draw 2 cards 
CLAUDIS uses Jargogle to play Chief Engineer Walls
CLAUDIS plays Chief Engineer Walls
CLAUDIS uses Spartasaur to destroy Daughter and Chief Engineer Walls
CLAUDIS plays Rhetor Gallim
CLAUDIS uses Rhetor Gallim to increase olio's key cost by 3 until the end of their next turn
CLAUDIS uses Paraguardian to reap with Paraguardian
CLAUDIS uses Paraguardian to exalt Paraguardian and ward its neighbors
CLAUDIS uses Tricerian Legionary to make Tricerian Legionary fight Rhetor Gallim
CLAUDIS uses Tricerian Legionary to remove its ward token
olio uses Rhetor Gallim to remove all Æmber  from Rhetor Gallim
CLAUDIS plays Praefectus Ludo
CLAUDIS plays Tribute, gaining 1 Æmber 
CLAUDIS uses Tribute to capture 2 Æmber  from olio, placing it on Spartasaur
CLAUDIS exalts Spartasaur to repeat the effect of Tribute
CLAUDIS uses Tribute to capture 2 Æmber  from olio, placing it on Spartasaur
CLAUDIS plays Chant of Hubris, gaining 1 Æmber 
CLAUDIS uses Chant of Hubris to remove 1 Æmber  from Spartasaur
CLAUDIS uses Chant of Hubris to place 1 Æmber  on Rhetor Gallim

Ready phase - CLAUDIS
CLAUDIS readies all of their cards 

Draw phase - CLAUDIS
CLAUDIS draws 2 cards  up to their maximum hand size of 6
 CLAUDIS declares Check!

End of turn 9
olio: 7 Æmber  CLAUDIS: 8 Æmber 

Turn 9

Key phase - olio
olio does not forge a key. They have 7 amber. The current cost is 9 Æmber 

House phase - olio

olio
Nice one!

CLAUDIS
ty

CLAUDIS
but it's hard

olio
Why did Spartasaurus effect work twice?

CLAUDIS
what do you mean? everything went destroyed in a single effect

olio
The ward token from Daughter was first removed and after that it was destroyed.

olio
*she

CLAUDIS
mmmh

CLAUDIS
don't know

olio
Yeah, I'll file a bug report after the game, it's ok!
olio chooses logos  as their active house this turn

Main phase - olio
olio uses Seismo-entangler to stop saurian  creatures from reaping next turn
olio plays Cutthroat Research, gaining 1 Æmber 
olio uses Cutthroat Research to steal 2 Æmber  from CLAUDIS
olio plays Remote Access, gaining 1 Æmber 
olio uses Remote Access to use Memory Chip

Ready phase - olio
olio readies all of their cards 

Draw phase - olio
 olio declares Check!

End of turn 9
olio: 11 Æmber  CLAUDIS: 6 Æmber 

Turn 10

Key phase - CLAUDIS
CLAUDIS forges the blue key  , paying 6 Æmber 

House phase - CLAUDIS

CLAUDIS
i think that chief enginer walls returning somehow triggered the effect of spartasaurus again

CLAUDIS
definitely a bug
CLAUDIS chooses saurian  as their active house this turn

Main phase - CLAUDIS

olio
Yeah, it must be something like that.
CLAUDIS plays Sic Semper Tyrannosaurus
CLAUDIS uses Sic Semper Tyrannosaurus to take all Æmber  from Paraguardian and destroy it
CLAUDIS plays Imperial Forge, gaining 1 Æmber 

Ready phase - CLAUDIS
CLAUDIS readies all of their cards 

Draw phase - CLAUDIS
CLAUDIS draws 2 cards  up to their maximum hand size of 6
 CLAUDIS declares Check!

End of turn 10
olio: 11 Æmber  CLAUDIS: 6 Æmber 

Turn 10

Key phase - olio
olio forges the blue key  , paying 6 Æmber 
 olio has won the game

CLAUDIS
almost XD

olio
Well played, tight match :)

CLAUDIS
gg
 CLAUDIS has left the game

**Comment by romanogit** [comment]
Automaton fix
