### ISSUE TITLE
Not registered as Maverick mavericks (shadows, marmo swarm)

### ISSUE THREAD

**Issue by Deuzerre** [keyteki/keyteki#96]
I ahve a deck with a shadows marmo swarm (https://www.keyforgegame.com/deck-details/f6e29d06-c3f0-44ec-851c-4b2a56ece73c) but it is counted as untamed.

Not a big deal, just forces some manual plays.

**Comment by Jarimy123** [comment]
Same issue my maverick grump buggy in logos isn’t

**Comment by Jarimy123** [comment]
https://decksofkeyforge.com/decks/5fabb70d-d908-423a-8155-102536fb3c03
