### ISSUE TITLE
Ragnarok gives aember for assault

### ISSUE THREAD

**Issue by Dunkoro** [keyteki/keyteki#965]
When Ragnarok is in effect and a creature kills another one through assault, Ragnarok rewards the player with 1 aember, which is incorrect. If a creature fighting dies to assault or hazardous, "the rest of the fight doesn't occur" including fighting itself.

**Comment by romanogit** [comment]
Similar to #1122 
Similar to #1338

**Comment by romanogit** [comment]
Has this rule been reviewed?
![image](https://user-images.githubusercontent.com/2104075/100667610-78563480-3339-11eb-999c-dfd0fa26948c.png)

**Comment by romanogit** [comment]
@Dunkoro 
Ragnarok uses "whenever a friendly creature fights.", which is not clarified. If we understand whenever as each time, and look at the timing chart Note: Effects that use the term “each time” occur at the same timing point as effects that use the term “after.” , Ragnarok should reward 1 amber even if killed by hazardous or kills by assault.

**Comment by romanogit** [comment]
Fixed with other fight cards.
