### ISSUE TITLE
Quixxle Stone and Explo-rover

### ISSUE THREAD

**Issue by Warfare13** [keyteki/keyteki#966]
Hi,

I had Quixxle Stone on board with 1 creature, none on the opponents side and it wouldn't let me play Explo-rover as an upgrade, just had the discard option

**Comment by SkyJedi** [comment]
duplicate https://github.com/keyteki/keyteki/issues/853 https://github.com/keyteki/keyteki/issues/938

**Comment by romanogit** [comment]
![image](https://user-images.githubusercontent.com/2104075/70367960-4a542680-1884-11ea-9c93-eb57255e1db1.png)
