### ISSUE TITLE
CALV-1N played through Wild Wormhole didn't offer me the choice to play it as an upgrad

### ISSUE THREAD

**Issue by hydrophilic-attack** [keyteki/keyteki#968]
See the attached log

(also it would be good if playing upgrades in manual mode could be done more smoothly)

[calv-1n wild wormhole.txt](https://github.com/keyteki/keyteki/files/3869836/calv-1n.wild.wormhole.txt)

**Comment by not2night** [comment]
Happened to me as well

**Comment by jeremylarner** [comment]
Fixed in #1247
