### ISSUE TITLE
Deploy - sometimes jumps to sides

### ISSUE THREAD

**Issue by Deuzerre** [keyteki/keyteki#97]
I haven't really identified the issue, but at least twice I clicked "deploy left" of a creature and it put it to the far left.

I tried in solo with a few creatures and it didn't bug out.

Will develop more as I gather more info. (was with little niff)

**Comment by cryogen** [comment]
From @thebrianfactor:

This error happened twice in the same match.

When attempting to Deploy Lamindra into my battleline I selected "Deploy Right" - with the impression that I'd select a creature and she would Deploy to the right of said creature. I wanted to Deploy Lamindra in the center of my battleline. Taking the steps above, I selected the creature, Yxilx Dominator, that I wanted to deploy to the right of. After I selected the creature, Lamindra deployed TWO battleline spaces to the LEFT of Yxilx Dominator. Ultimately being 3 spaces to the LEFT of where I wanted her. Please correct - and thank you for all the hard work to get AoA live!

**Comment by poeticmatter** [comment]
I get the most consistent result by choosing deploy left, then clicking a creature, and it deploys one further to the left than expected. But even that sometimes results in the creature deploying even further down the battle line.

**Comment by justbrown1980** [comment]
Grey rider seems to cause the above problem cryogen mentions above each time it has been  played for me so maybe try that to replicate issue?

**Comment by MythicMikeneto** [comment]
Try deploying multiples across multiple turns with different deploy positions.

I deployed Lamindra "Deploy left"
Then I tried to deploy another "Deploy right", and it went "Deploy left."

It also may be an issue with deploying on a flank. In the above example deploy right would have been on a right flank.

I have had this deploy issue with Lion, Laminda, and Challe.

**Comment by bensissel** [comment]
Same thing happened to me. Produced the same effect. I had Aubade - Challe Safeguard - Bordan. Tried playing Grey rider to the right of Challe. No matter which way I tried to put him down "Deploy left" of bordan or "Deploy right" of challe, grey rider ended up on the left flank every time.

**Comment by MythicMikeneto** [comment]
It seems that when using Deploy, it does not recognize the exisisting card on the field that have deploy.

I was able to reproduce the bug multiple times by trying to deploy a card on a card with the Deploy trait.

**Comment by gadamgrey** [comment]
I experienced this while trying to deploy Little Niff in between two Umbras.  I chose Deploy Left and clicked on the right most Umbra.  Niff was placed to the left of both.

**Comment by romanogit** [comment]
I was able to see the problem happening today.

**Comment by cryogen** [comment]
Reopening this as it's still not working
