### ISSUE TITLE
Senator Shrix exalting for free

### ISSUE THREAD

**Issue by Chrissyboytux** [keyteki/keyteki#973]
Hi,

I have a deck with 3x Senator Shrix from the Saurian house. When you play or reap with him, you can exalt him and put an aember on him. With exalting you require an aember in your pool to use the effect, but you can exalt him without having any aember and even if you do it doesn't spend the aember in your pool to exalt him. That is how I understand exalting to work anyway and I know it is a new mechanic and seems to work fine with the rest of my Saurian cards. 

Please let me know if this is a bug or if I am mistaken as I don't want to cheat people in my matches.

Kind Regards,

Chris

**Comment by cryogen** [comment]
Thanks for the report! Exalt comes from the common supply and not your pool. This is not a bug and is working correctly.

**Comment by Chrissyboytux** [comment]
Oh thanks. I must have read the rules of exalt wrong!

Kind Regards,

Christopher Tucker
Utopia Property Films
07746913874
info@utopiapropertyfilms.com
http://www.utopiapropertyfilms.com
