### ISSUE TITLE
Gargantodon/ Obsidian Forge

### ISSUE THREAD

**Issue by jaybrayuk** [keyteki/keyteki#974]
Played a game where I tried to steal aember with a Trust no one and a Gargantodon in play on my side of the board. The aember came from my pool and was captured by an enemy creature instead of the aember coming from the opponent's pool and being captured on Gargantodon. 

Also, the opponent used an Obsidian forge with a soul snatcher artifact also in play, the aember was added correctly and the obsidian forge was discarded but no key was forged.

**Comment by romanogit** [comment]
There are dupes
#831
#797
