### ISSUE TITLE
Shattered Throne attackers shouldn't capture aember if they are destroyed in battle

### ISSUE THREAD

**Issue by TeaSeaLancs** [keyteki/keyteki#975]
Related to https://github.com/keyteki/keyteki/issues/952, https://github.com/keyteki/keyteki/pull/940

I don't believe the fix for this is correct unfortunately. Looking at the timing charts and the "tagged for destruction" rules, attacking creatures that are destroyed shouldn't capture aember.

Reasoning: 

* The text for Shattered Throne reads "After a creature is used to fight, it captures 1A.". 
* Effects for "After a creature fights" are only applied after the step where damage is applied, creatures are tagged for destruction and removed from the board.

This all would be fairly academic however there's a fun interaction with Praefectus Ludo (https://archonarcana.com/index.php?title=Praefectus_Ludo) that was in a game yesterday:

I attacked an enemy creature while Praefectus Ludo was on my side of the board and my creature died. The creature captured aember and then it was returned to the common supply. 

See https://www.thecrucibletracker.com/games/bcc0f6d0-0baa-11ea-a3ea-d3428020ef3a for a transcript of what happened.

A replicable test case can be found at https://github.com/TeaSeaLancs/keyteki/commit/0bf80c2de3a9272cbe7358de6b4d980f07909409

I would offer to fix this, but I don't know the codebase well enough to fix it, just to create test cases ;-)

**Comment by Achocholacek** [comment]
Thank you for writing the test code. Fix incoming!
