### ISSUE TITLE
shattered throne, again

### ISSUE THREAD

**Issue by lupo82** [keyteki/keyteki#977]
i already reported this, but it's not solved.
here a chat log and a screenshot
Main phase - Gulipo
Gulipo plays Shattered Throne, gaining 1 Æmber 
Gulipo plays Lava Ball
Gulipo uses Lava Ball to deal 4 damage to Charette and 2 to their neighbors
Gulipo uses Ganger Chieftain to reap with Ganger Chieftain
Gulipo uses Alaka to reap with Alaka
 Lupo82 has connected to the game server
Ready phase - Gulipo
Gulipo readies all of their cards 
Draw phase - Gulipo
Gulipo draws 2 cards  up to their maximum hand size of 6
 Gulipo declares Check!
End of turn 5
Lupo82: 5 Æmber  Gulipo: 6 Æmber 
Turn 6
Key phase - Lupo82
Lupo82 does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - Lupo82
 Lupo82 has connected to the game server
Lupo82 chooses dis  as their active house this turn
Main phase - Lupo82
Lupo82 uses Lash of Broken Dreams to increase Gulipo's key cost by 3 until the end of their next turn
Lupo82 uses The Terror to make The Terror fight Groupthink Tank
Gulipo uses Shattered Throne to capture 1 Æmber  from Gulipo, placing it on The Terror
Lupo82 uses Drumble to reap with Drumble
 Lupo82 is attempting to switch manual mode on
Lupo82
you have to add 1 aember
Lupo82
you had 6
 Gulipo allows enabling manual mode
 Lupo82 switches manual mode on
Lupo82
terro captured 1
Lupo82
then it died
Lupo82
so you should have 6
 Gulipo sets Æmber  to 6 ( +1 )
 Gulipo switches manual mode off
Ready phase - Lupo82
Lupo82 readies all of their cards 
![Screenshot (221)](https://user-images.githubusercontent.com/54270461/69444545-daf11980-0d50-11ea-887a-dcb03c11c0b7.png)

**Comment by lupo82** [comment]
again, i used arise to take back the creatures who captured dying, and they came back with the aembers captured on them
here a screenshot
![Screenshot (222)](https://user-images.githubusercontent.com/54270461/69444943-a7fb5580-0d51-11ea-854f-83f7b5e9f3a8.png)

**Comment by cryogen** [comment]
This was fixed some time ago but the game node that hadnt been updated got back into the pool.  It's updated now.
