### ISSUE TITLE
Sinestra/Dexus should trigger on first creature played

### ISSUE THREAD

**Issue by takkuso** [keyteki/keyteki#978]
Sinestra says "After your opponent plays a creature on their left flank, they lose 1A"
Dexus says "After your opponent plays a creature on their right flank, they lose 1A."
According to the rulebook, Flank is defined as "The creatures on the far left and far right of a player's battleline are on the flanks of the line. A creature in this position is referred to as a flank creature. Any time a creature enters play or changes control, the active player chooses which flank of its controller's battleline it is placed on. If a battleline only has one creature in it, **that creature is on both the left flank and the right flank** and is considered a flank creature." (Bolding mine)

Since the first creature is considered both flanks, Sinestra and Dexus should trigger, causing the first creature of opponent's battleline to make them lose an Æmber.

**Comment by romanogit** [comment]
This bug seems to happen only if opponent has artifacts in play before they play the first creature.
