### ISSUE TITLE
The Callipygian Ideal BUG

### ISSUE THREAD

**Issue by LucaAmbrosino** [keyteki/keyteki#979]
Instead of let me spending aember that are only on the creature upgraded with the Callipygian Ideal, the system gives me the opportunity to use the aember that are on ALL my creatures, even if they are not equipped with The Callipygian Ideal. This happens only when I play this card.

Thanks a lot for all the work

![the-callipygian-ideal](https://user-images.githubusercontent.com/22912858/69477747-5521ac80-0dea-11ea-8d7c-1f24481f40f8.png)

**Comment by MKHAUS** [comment]
I've noticed this a couple of times recently as well. I think it is related to work resolving the prior Senator Bracchus bug.

**Comment by cryogen** [comment]
This was fixed some time ago but the game node that hadn't been updated yet got back into the pool so it appeared as if the bug was back.  It's gone for good now :)
