### ISSUE TITLE
Festering Touch did not damage Noddy

### ISSUE THREAD

**Issue by greggraham** [keyteki/keyteki#981]
I played Festering Touch when the only opponent creature was Noddy the Thief. I clicked on Noddy and then done, but no damage was dealt to Noddy.

I'm sorry, but this is my first issue, and I did not read the guidelines until after I had left the game. However, I thought this still might be helpful to know. I will do better next time.

**Comment by romanogit** [comment]
![image](https://user-images.githubusercontent.com/2104075/70256395-2b13a700-1767-11ea-921c-f4861927b075.png)

![image](https://user-images.githubusercontent.com/2104075/70256411-323ab500-1767-11ea-8e77-62e768afadd7.png)

**Comment by romanogit** [comment]
I am unable to reproduce. There might be many reasons a creature cannot be dealt damage. Maybe it had extra armor, ward, next to Shadow Self, etc.

We would need the full game log here.

**Comment by greggraham** [comment]
Thank you.
