### ISSUE TITLE
Borr Nit and his touch arent shuffling

### ISSUE THREAD

**Issue by SkyJedi** [keyteki/keyteki#984]
This guy and his touching should shuffle the deck afterwards

**Comment by romanogit** [comment]
I fixed one part (Borr Nit) in #911 and his touch is fixed here : https://github.com/keyteki/keyteki/pull/967

I guess this is still not in prod.

**Comment by cryogen** [comment]
Live has everything from this commit and back: https://github.com/keyteki/keyteki/commit/a6f3440af0cc0a9cdaab06fe2acd5a874259461f

**Comment by romanogit** [comment]
I played it once and I noticed the first two cards came to my hand after shuffle, but not the 4 cards. I did not have much time to test again. I will try later. Could have been coincidence.

**Comment by romanogit** [comment]
Only Borr touch is not shuffling.
Borr Nit is shuffling:

![image](https://user-images.githubusercontent.com/2104075/69571753-7e386d80-0fa1-11ea-9cec-628cb9343e70.png)

I purged Amberspine, then I draw my deck:

![image](https://user-images.githubusercontent.com/2104075/69571781-8db7b680-0fa1-11ea-8b89-9605620600de.png)

**Comment by mnapoleon** [comment]
The fix I made for touch is currently in an open pull request

**Comment by romanogit** [comment]
This is not merged.
