### ISSUE TITLE
An optional Play ability with morpheus on board automatically triggers

### ISSUE THREAD

**Issue by Dunkoro** [keyteki/keyteki#988]
When I have Sci. Officer Morpheus on board and play Senator Shrix, Senator's Play ability triggers once without prompting, placing 1 aember on him and only the second instance asks whether I'd want to or not.

**Comment by romanogit** [comment]
This is a known issue. It is listed here #662

**Comment by cryogen** [comment]
Also affects Cincinnatus rex

**Comment by jeremylarner** [comment]
Fixed in #1247
