### ISSUE TITLE
Sci officer Morpheus issue

### ISSUE THREAD

**Issue by GregT1982** [keyteki/keyteki#990]
Hello, sorry I don't have a state of the game screen shot but with Sci officer Morpheus in my battleline and then played Helper Bot (legacy) only one non logos card can be played instead of two with the officer's static ability.

Thanks

**Comment by Achocholacek** [comment]
Confirmed as bug. Updated test case with test for this scenario.

Multiple helper bots are confirmed as stacking properly, not sure why the 2xPlay code doesn't stack in the same way.

**Comment by jeremylarner** [comment]
Fixed in #1247
