### ISSUE TITLE
Card under Jargogle Face Down in Archives

### ISSUE THREAD

**Issue by JTLSound** [keyteki/keyteki#991]
When Jargogle is destroyed on its owner's turn, and the card underneath it is archived, it is archived face down. No card in your archives should ever be hidden or face down, no matter its origin.

**Comment by oli0** [comment]
When you play Jargogle, you put a card under it. That card doesn't show a back of the card, only outlines. Like JTLSound describes, when the card underneath Jargogle is archived, you can't view it.
<img width="1656" alt="Jargogle_error" src="https://user-images.githubusercontent.com/4337643/70371367-b06b9880-18da-11ea-8b03-4d13cbf8772d.png">

**Comment by palpster** [comment]
The correct card does get drawn to hand after you pick up archives, but before that all that is visible is the back of the card (other cards are still visible in archives)

**Comment by SkyJedi** [comment]
The card played under jargogle also should show the cardback to opponent and when zoomed should should player the cardface

**Comment by SkyJedi** [comment]
I believe this is fixed now?  can anyone @JTLSound  let me know if its still wonky?

**Comment by JTLSound** [comment]
That's great! I'll check it out tonight.
