### ISSUE TITLE
Infurnace

### ISSUE THREAD

**Issue by KeyforgeJupiter** [keyteki/keyteki#993]
When you play Infurnace it allows you to target both graveyards at the same time for a one adn one split of cards which is not how it functions.

**Comment by romanogit** [comment]
![image](https://user-images.githubusercontent.com/2104075/70233541-8df04880-173d-11ea-8d59-0ec4ca48b8e7.png)

**Comment by romanogit** [comment]
It is the same problem as Creeping Oblivion, reported here https://github.com/keyteki/keyteki/issues/392

![image](https://user-images.githubusercontent.com/2104075/70233657-c55ef500-173d-11ea-96df-85c037b63baa.png)
