### ISSUE TITLE
Gongoozle does not discard card when used on creature with ward

### ISSUE THREAD

**Issue by mikefuni** [keyteki/keyteki#994]
Sorry I do not have screen shots or the chat window but I have had this happen twice. Gongoozle removes the ward but does not discard a random card from opponent.

**Comment by dlocke** [comment]
This happened to me as well.

**Comment by romanogit** [comment]
![image](https://user-images.githubusercontent.com/2104075/70233735-ecb5c200-173d-11ea-98da-74f5f27ac27a.png)
