### ISSUE TITLE
Song of the wild not giving additional Aember 

### ISSUE THREAD

**Issue by stechu2** [keyteki/keyteki#995]
![image](https://user-images.githubusercontent.com/17553255/69903879-a0662d00-139f-11ea-9135-7e08c635ef09.png)

https://pastebin.com/zgSPVWQR

**Comment by bensissel** [comment]
I'm encountering the same issue. Bramble Lynx coming in ready from a ghosthawk enable battline reap, reaps but no extra amber from song of the wild.

**Comment by romanogit** [comment]
This is duplicate, the linked issue #1125
