### ISSUE TITLE
Unnatural Selection card highlighting inconsistent with ready Untamed cratrues

### ISSUE THREAD

**Issue by JHCover** [keyteki/keyteki#998]
Apparently, when you use Unnatural Selection to select the creatures on your side you want to preserve from destruction, when you select off-house creatures they are highlighted with a solid green frame like normal, but when you select a ready untamed creature, it highlights it with the golden, pulsing, 'available-for-selection' frame, not the green 'has been selected' frame.

**Comment by romanogit** [comment]
This is similar to https://github.com/keyteki/keyteki/issues/665

**Comment by romanogit** [comment]
A screenshot to illustrate. Both cards are selected, but one is highlighted and the other is glowing:

![image](https://user-images.githubusercontent.com/2104075/71177134-0bda4680-224a-11ea-998f-aa2352a03a09.png)
